# Funding options for Qui Browser VR

# GitHub Sponsors
github: [] # Add GitHub username here if you set up GitHub Sponsors

# Patreon
patreon: # Add Patreon username

# Open Collective
open_collective: # Add Open Collective project name

# Ko-fi
ko_fi: # Add Ko-fi username

# Tidelift
tidelift: # Add Tidelift package name

# Community Bridge
community_bridge: # Add Community Bridge project name

# Liberapay
liberapay: # Add Liberapay username

# IssueHunt
issuehunt: # Add IssueHunt username

# Otechie
otechie: # Add Otechie username

# LFX Mentorship (formerly CommunityBridge)
lfx_crowdfunding: # Add LFX Crowdfunding project name

# Custom URLs
custom: [] # Add custom funding URLs
# Example:
# custom: ['https://www.buymeacoffee.com/yourusername', 'https://paypal.me/yourusername']
