// Pass CCLIII: EN submerge/silence/contain + JA sink/paint-over/garbage/chase-away (pass CCLIII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLIII: close-tab coverage', () => {
  test.each([
    "submerge it", "immerse it", "dunk it", "douse it",
    "drench it", "soak it", "saturate it", "souse it",
    "plunge it", "submerse it", "engulf it", "inundate it",
    "swamp it", "submerge the tab", "immerse the tab", "dunk the tab",
    "drench the tab", "soak the tab", "plunge the tab", "drown it in the bath",
    "drown it in a bucket", "drown it in a barrel", "drown it in a vat", "drown it like a kitten",
    "drown it like a rat", "drown it forever", "drown it completely", "sink it to the bottom",
    "sink it to the bottom of the sea", "sink it to the bottom of the ocean", "sink it to the bottom of the lake", "sink it to the bottom of the river",
    "sink it like a rock", "sink it like a lead weight", "sink it completely", "sink it forever",
    "plunge it underwater", "plunge it under water", "plunge it beneath the waves", "plunge it into the deep end",
    "plunge it into the abyss", "plunge it into the mire", "plunge it into the muck", "plunge it into the mud",
    "plunge it into the swamp", "plunge it into the bog", "plunge it into the marsh", "plunge it into the tar pit",
    "plunge it into the tar", "plunge it into quicksand", "plunge it into the quicksand", "plunge it into the sludge",
    "plunge it into the slime", "plunge it into the ooze", "plunge it into the grease", "plunge it into the oil",
    "plunge it into the acid", "plunge it into acid", "plunge it into a vat of acid", "dunk it under",
    "dunk it underwater", "dunk it under water", "dunk it in the tub", "dunk it in the pool",
    "dunk it in the bath", "hold it underwater", "hold it under water", "submerge it completely",
    "submerge it forever", "submerge it entirely", "immerse it completely", "immerse it fully",
    "immerse it forever", "flood it completely", "inundate it", "swamp it",
    "swamp the tab", "engulf it", "engulf the tab", "engulf it completely",
    "engulf it entirely", "engulf it in flames", "engulf it in fire", "engulf it in smoke",
    "engulf it in darkness", "engulf it in shadow", "engulf it in shadows", "engulf it in mist",
    "engulf it in fog", "engulf it in the void", "engulf it in oblivion", "engulf it in nothingness",
    "gag it shut", "muzzle it shut", "stifle it forever", "smother it in its sleep",
    "smother it to death", "smother it completely", "strangle it to death", "throttle it to death",
    "wring the tabs neck", "snap the tabs neck", "break the tabs neck", "twist its neck",
    "twist the tabs neck", "crush its throat", "crush the tabs throat", "clamp its beak",
    "duct tape it", "duct tape it shut", "duct tape the tab", "duct tape its mouth",
    "duct tape its mouth shut", "tape its mouth shut", "tape the tabs mouth shut", "put a sock in it",
    "stuff a sock in it", "shove a sock in it", "put a cork in it", "shove a cork in it",
    "stick a cork in it", "put the lid on it", "clamp down on it", "clamp it down",
    "clamp it down forever", "cover it up", "cover it up forever", "shroud it",
    "shroud the tab", "shroud it in darkness", "shroud it in silence", "shroud it in secrecy",
    "shroud it in shadow", "cloak it", "cloak the tab", "cloak it in darkness",
    "cloak it in shadow", "cloak it in secrecy", "veil it", "veil the tab",
    "obscure it", "obscure the tab", "obscure it forever", "hide it",
    "hide the tab", "hide it away", "hide it for good", "hide it from view",
    "hide it from sight", "hide it from me", "hide it from everyone", "hide it from the world",
    "conceal it", "conceal the tab", "conceal it forever", "conceal it from view",
    "conceal it from sight", "mask it", "mask the tab", "camouflage it",
    "camouflage the tab", "screen it off", "screen the tab off", "cordon it off",
    "cordon the tab off", "quarantine it", "quarantine the tab", "quarantine it forever",
    "quarantine it permanently", "quarantine it for good", "isolate it", "isolate the tab",
    "isolate it forever", "isolate it permanently", "isolate it for good", "segregate it",
    "segregate the tab", "sequester it", "sequester the tab", "seclude it",
    "seclude the tab", "cord it off", "zone it off", "fence it off",
    "fence the tab off", "rope it off", "rope the tab off", "barrier it",
    "barrier the tab", "wall it off", "wall the tab off", "partition it",
    "partition the tab", "partition it off", "curtain it off", "curtain the tab off",
    "contain it", "contain the tab", "contain it forever", "contain it permanently",
    "contain it for good", "confine it", "confine the tab", "confine it forever",
    "confine it permanently", "confine it for good", "enclose it", "enclose it forever",
    "enclose it permanently", "enclose it for good", "impound it", "impound the tab",
    "impound it forever", "impound it permanently", "impound it for good", "pen it in",
    "pen the tab in", "pen it up", "pen the tab up", "corral it",
    "corral the tab", "corral it in", "corral the tab in", "coop it up",
    "coop the tab up", "cage it", "cage the tab", "cage it up",
    "cage the tab up", "kennel it", "kennel the tab", "leash it",
    "leash the tab", "leash it up", "tether it", "tether the tab",
    "chain it", "chain the tab", "chain the tab up", "shackle it",
    "shackle the tab", "shackle it up", "fetter it", "fetter the tab",
    "bind it", "bind the tab", "bind it up", "bind the tab up",
    "tie it up", "tie the tab up", "truss it", "truss the tab",
    "truss it up", "hogtie it", "hogtie the tab", "restrain it",
    "restrain the tab", "restrain it forever", "restrain it permanently", "arrest it",
    "arrest the tab", "detain it", "detain the tab", "detain it forever",
    "detain it permanently", "detain it indefinitely", "hold it", "hold the tab",
    "hold it indefinitely", "hold it forever", "hold it permanently", "hold it captive",
    "hold it prisoner", "hold it hostage", "take it captive", "take it prisoner",
    "take it hostage", "imprison it", "imprison the tab", "imprison it forever",
    "imprison it permanently", "imprison it for life", "imprison it for good", "incarcerate it",
    "incarcerate the tab", "incarcerate it forever", "incarcerate it permanently", "incarcerate it for life",
    "jail it", "jail the tab", "jail it forever", "jail it permanently",
    "jail it for life", "gaol it", "gaol the tab", "lock it up for life",
    "lock it away forever", "throw it in jail", "throw it in prison", "throw it in the slammer",
    "throw it in the clink", "throw it in the hole", "throw it in solitary", "throw it in a cell",
    "toss it in jail", "toss it in prison", "toss it in the slammer", "toss it in the clink",
    "put it in jail", "put it in prison", "put it in the slammer", "put it in the clink",
    "put it in solitary", "put it in a cell", "send it to jail", "send it to prison",
    "send it to the slammer", "send it to the clink", "send it to solitary", "ship it off to prison",
    "ship it off to jail", "throw away the key", "throw the key away", "lock it up and throw away the key",
    "lock it up and throw the key away", "lock it and throw away the key", "lock it and throw the key away", "jail it and throw away the key",
    "imprison it and throw away the key", "sentence it to life", "sentence it to life in prison", "sentence it to life imprisonment",
    "sentence it to prison", "sentence it to jail", "sentence it to solitary", "sentence it to hard labor",
    "sentence it to hard labour", "condemn it to prison", "condemn it to jail", "condemn it to solitary",
    "condemn it to life", "consign it to prison", "consign it to jail", "consign it to solitary",
    "commit it to prison", "commit it to jail", "remand it", "remand the tab",
    "remand it to custody", "remand it to prison", "remand it to jail", "沈めちゃえ",
    "沈めろと言ってんだ", "沈めるからな", "水没にしろ", "水没させちゃえ",
    "沈没にしろ", "沈没させちゃえ", "沈黙にしろ", "沈黙させて",
    "水底へ沈め", "水底に落として", "水底に投げろ", "水底に投げて",
    "水底に投げ込め", "水底に投げ込んで", "水底に沈めて", "川底に沈め",
    "川底へ沈め", "川底に落とせ", "川底に投げろ", "川底に投げ込め",
    "海底へ沈め", "海底に投げろ", "海底に投げ込め", "海の底に沈め",
    "海の底へ沈め", "海の底に落とせ", "海の底に投げろ", "海の底に沈めろ",
    "沼に投げろ", "淵に投げろ", "湖底に投げろ", "池に落とせ",
    "池に投げろ", "井戸に投げろ", "井戸に沈めろ", "川に投げろ",
    "湖に落とせ", "湖に投げろ", "湖に沈めろ", "プールに沈め",
    "プールに落とせ", "プールに投げろ", "浴槽に沈め", "浴槽に沈めろ",
    "風呂に沈め", "風呂に沈めろ", "風呂に沈めて", "バケツに沈め",
    "樽に沈め", "桶に沈め", "塗り潰せ", "塗り潰して",
    "塗り潰すんだ", "塗り潰せよ", "塗り潰せって", "塗り潰せと言ってんだ",
    "塗り潰すんだよ", "塗り潰すのだ", "塗り潰すことにした", "塗り潰すべきだ",
    "塗り潰すべきと思う", "塗りつぶせ", "塗りつぶして", "塗りつぶすんだ",
    "塗りつぶせよ", "塗りつぶせって", "塗りつぶすのだ", "塗りつぶすべきだ",
    "墨で塗り潰せ", "墨で塗り潰して", "墨で塗りつぶせ", "墨で塗りつぶして",
    "墨で消せ", "墨で消して", "墨で塗れ", "墨で塗って",
    "黒で塗り潰せ", "黒で塗り潰して", "黒で塗りつぶせ", "黒で塗りつぶして",
    "黒で塗れ", "黒で塗って", "黒塗りだ", "黒塗りにしろ",
    "真っ黒にしろ", "真っ黒にして", "真っ黒に塗れ", "真っ黒に塗って",
    "塗り潰せ", "ペンキで塗れ", "ペンキで塗って", "ペンキで塗り潰せ",
    "ペンキで塗り潰して", "ペンキ漬けにしろ", "ペンキ漬けだ", "上書きしろ",
    "上書きだ", "上書きして", "上書きしちまえ", "上書きしちゃえ",
    "上書きしてしまえ", "書き潰せ", "書き潰して", "書き消せ",
    "書き消して", "書き換えろ", "書き換えて", "書き換えてしまえ",
    "線を引いて消せ", "二重線で消せ", "取り消し線を引け", "取り消し線だ",
    "線引きだ", "抹消線を引け", "消しゴムで消せ", "消しゴムで消して",
    "消しゴムだ", "消しゴムにかけろ", "修正液で消せ", "修正液で塗れ",
    "修正テープで消せ", "修正テープだ", "マジックで消せ", "マジックで塗り潰せ",
    "生ゴミにしろ", "生ゴミだ", "生ゴミに出せ", "生ゴミに出して",
    "生ゴミに捨てろ", "生ゴミに捨てて", "生ゴミに入れろ", "生ゴミに放り込め",
    "生ごみにしろ", "生ごみだ", "生ごみに出せ", "生ごみに捨てろ",
    "生ごみに放り込め", "不燃ゴミにしろ", "不燃ゴミに出せ", "不燃ゴミに出して",
    "不燃ゴミに捨てろ", "不燃ゴミに放り込め", "不燃ごみにしろ", "不燃ごみだ",
    "不燃ごみに出せ", "不燃ごみに捨てろ", "可燃ゴミにしろ", "可燃ゴミだ",
    "可燃ゴミに出せ", "可燃ゴミに捨てろ", "可燃ごみにしろ", "可燃ごみだ",
    "可燃ごみに出せ", "粗大ゴミにしろ", "粗大ゴミに出せ", "粗大ゴミに捨てろ",
    "粗大ごみにしろ", "粗大ごみに出せ", "粗大ごみに捨てろ", "ゴミ袋に放り込め",
    "ゴミ袋に入れて", "ゴミ袋に詰めて", "ゴミ袋行きだ", "ゴミ袋行きにしろ",
    "ゴミ箱に放り込め", "ゴミ箱に捨てて", "ゴミ箱に入れて", "ゴミ箱行きにしろ",
    "ゴミ箱に直行だ", "ゴミ箱直行だ", "ポイ捨てしろ", "ポイ捨てだ",
    "ポイ捨てしちまえ", "ポイ捨てしちゃえ", "ポイ捨てしてしまえ", "ゴミ収集に出せ",
    "ゴミ収集に出して", "収集日に出せ", "収集日に出して", "ゴミの日に出せ",
    "ゴミの日に出して", "燃えるゴミに出せ", "燃えるゴミに捨てろ", "燃えないゴミに出せ",
    "燃えないゴミに捨てろ", "資源ゴミに出せ", "資源ゴミに捨てろ", "資源ごみに出せ",
    "資源ごみに捨てろ", "リサイクルに出して", "リサイクルだ", "リサイクルにしろ",
    "リサイクルに回せ", "リサイクルに回して", "リサイクル処分だ", "シュレッダー処分だ",
    "シュレッダー処分にしろ", "産廃にしろ", "産業廃棄物にしろ", "廃棄物にしろ",
    "廃棄物だ", "廃棄して", "廃棄しちまえ", "廃棄しちゃえ",
    "廃棄してしまえ", "廃棄処分にしろ", "処分場へ行け", "処分場に送れ",
    "処分場に送って", "処分場に運べ", "処分場に運んで", "処分場行きだ",
    "処分場行きにしろ", "埋め立て地へ行け", "埋め立て地に送れ", "埋め立て地に運べ",
    "埋立地へ行け", "埋立地に送れ", "埋立地に運べ", "最終処分場へ",
    "最終処分場へ行け", "最終処分場に送れ", "清掃センターへ", "清掃センターに送れ",
    "クリーンセンターへ", "クリーンセンターに送れ", "焼却場へ行け", "焼却場に送れ",
    "焼却場に運べ", "焼却場行きだ", "焼却場行きにしろ", "灰になるまで焼け",
    "灰にしてしまえ", "灰に変えろ", "灰に変えてしまえ", "灰に帰れ",
    "塵に変えろ", "塵にしてしまえ", "塵に帰せ", "塵に帰れ",
    "塵にして", "チリに変えろ", "チリに還せ", "チリに還れ",
    "破棄宣言だ", "破棄を宣言する", "破棄する", "破棄するんだ",
    "破棄しちゃえ", "破棄することにした", "破棄するつもりだ", "破棄するわ",
    "破棄するぞ", "破棄するぜ", "破棄するからな", "破棄だって",
    "放棄宣言だ", "放棄を宣言する", "放棄する", "放棄すんだ",
    "放棄しちまえ", "放棄しちゃえ", "放棄してしまえ", "放棄したまえ",
    "放棄しやがれ", "放棄しろや", "放棄することにした", "放棄するわ",
    "放棄するぞ", "放棄するぜ", "放棄だって", "撤棄だ",
    "撤棄しろ", "撤棄して", "棄てろ", "棄てて",
    "棄てるんだ", "棄てちまえ", "棄てちゃえ", "棄ててしまえ",
    "棄てなよ", "棄てたまえ", "棄てやがれ", "棄てろや",
    "棄てるべきだ", "棄てることにした", "棄てるわ", "棄てるぞ",
    "棄てるぜ", "棄てるからな", "捨て去るからな", "追い払いにしろ",
    "追い払いをかけろ", "追い払えって", "追い払えと言ってんだ", "追い払うからな",
    "追い出しちゃえ", "追い出せや", "追い出せと言ってんだ", "追い出すからな",
    "ぶん殴って追い出せ", "ぶん殴って追い払え", "叩き追い出せ", "散り去れ",
    "散り去って", "散り去るんだ", "散り去れよ", "散り去るべきだ",
    "散り去れと言ってんだ", "掃き散らせ", "掃き散らして", "掃き散らすんだ",
    "掃き溜めにしろ", "掃き溜めだ", "掃き溜めに捨てろ", "掃き溜めに放り込め",
    "掃き溜めに入れろ", "掃き溜め行きだ", "掃き溜め行きにしろ", "塵溜めにしろ",
    "塵溜めだ", "塵溜めに捨てろ", "塵溜めに放り込め", "塵溜めに入れろ",
    "塵溜め行きだ", "チリ溜めにしろ", "チリ溜めだ", "チリ溜めに捨てろ",
    "チリ溜めに放り込め",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
