// Pass CCXLVII: EN dismember/strangle + broadcast-cancel + termination-notice + memorial/valediction + condemnatory; JA takedown/massacre/execution/crush/garbage/duty (pass CCXLVII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCXLVII: close-tab coverage', () => {
  test.each([
    "cancel the tab", "abort it", "abort the tab", "nix the plan",
    "yank the plug on it", "unplug the tab", "pull its plug", "cut the power on it",
    "kill the power", "cut its power", "kill its feed", "cut its feed",
    "cut the feed", "kill the feed", "starve it", "starve the tab",
    "starve it out", "choke the tab", "choke it to death", "strangle the tab",
    "throttle it", "throttle the tab", "wring its neck", "snap its neck",
    "break its neck", "neck it", "garrote the tab", "garotte the tab",
    "decapitate the tab", "lop its head off", "lop off its head", "chop its head off",
    "cut its head off", "slice its head off", "hack its head off", "heads off",
    "sever its head", "carve it up", "carve it open", "split it open",
    "split the tab open", "crack it open", "crack the tab open", "pry it open",
    "force it open", "break it open", "break the tab open", "smash it open",
    "rip it open", "tear it open", "cut it open", "dissect it",
    "dissect the tab", "vivisect it", "autopsy it", "autopsy the tab",
    "post mortem it", "autopsy on it", "dissect it piece by piece", "take the tab apart",
    "take it to pieces", "pull it apart", "pull the tab apart", "pull it to pieces",
    "pull it to bits", "rend it to pieces", "rip it apart", "rip it asunder",
    "break it apart", "break it to pieces", "shatter it to pieces", "shatter it to bits",
    "shatter it to nothing", "smash it to pieces", "smash it to bits", "smash it to smithereens",
    "blast it to bits", "blast it to pieces", "blast it to smithereens", "set the charge",
    "lit the fuse", "fuse is lit", "spark it", "spark the tab",
    "burn it up", "burn it to the ground",
    "burn it to ashes", "burn it to dust", "burn it to a crisp", "burn it to cinders",
    "incinerate it completely", "char the tab", "char it black", "scorch it",
    "scorch the tab", "toast it", "toast the tab", "cook it",
    "cook the tab", "cook it alive", "boil it", "boil the tab",
    "boil it alive", "poach it", "simmer it down", "steam it",
    "steam the tab", "nuke it in the microwave", "microwave it to death", "irradiate the tab",
    "gamma it", "electrocute the tab", "shock it", "shock the tab",
    "shock it to death", "juice the tab", "short the tab out", "overload it to death",
    "surge it", "surge the tab", "power surge it", "spike it",
    "spike the tab", "spike it through", "impale the tab", "impale it on a stake",
    "stake it", "stake the tab", "skewer the tab", "shish kebab it",
    "lance the tab", "spear it", "spear the tab", "pike it",
    "put it on a pike", "head on a pike", "its head on a pike", "mount its head",
    "mount its head on the wall", "trophy it", "stuff it", "stuff the tab",
    "stuff and mount it", "taxidermy it", "nail it to the wall", "nail it up",
    "nail the tab up", "crucify it", "crucify the tab", "put it on a cross",
    "martyr it", "martyr the tab", "sacrifice it", "sacrifice the tab",
    "sacrifice it to the gods", "offer it up", "offer it up as a sacrifice", "offering it",
    "ritual sacrifice", "ritual sacrifice for it", "aztec sacrifice", "cut out its heart",
    "rip out its heart", "tear out its heart", "pull out its heart", "remove its heart",
    "extract its heart", "heart extraction", "rip out its spine", "tear out its spine",
    "pull out its spine", "remove its spine", "spine rip", "fatality for it",
    "end this tab", "end this nonsense", "end the madness", "stop the madness",
    "stop this madness", "end the insanity", "stop the insanity", "pull it off the air",
    "take it off the air", "take it off air", "off the air", "off air",
    "cancel its broadcast", "pull the broadcast", "pull the show", "cancel the show",
    "cancel its run", "end its run", "its run is over", "run is over",
    "the run is over", "no second season", "cancel the series", "cancel the season",
    "cancel the sequel", "no sequel", "no sequel for it", "axe the show",
    "axe the series", "boot the tab out", "give it the heave", "shove it out",
    "push it out", "walking papers for it", "serve it its papers", "serve it with notice",
    "serve it an eviction", "eviction notice", "eviction notice for it", "notice to quit",
    "notice to quit for it", "give it its notice", "two weeks notice", "thirty days notice",
    "ninety days notice", "final notice", "final notice for it", "severance notice",
    "pink slip for it", "fire it from its job", "let it go from its job", "terminate it with prejudice",
    "terminate with prejudice", "end its employment", "end its tenure", "end its service",
    "end its watch", "its watch is over", "watch has ended", "the watch has ended",
    "its watch ends", "retire it from service", "retire it from duty", "discharge it",
    "discharge the tab", "cashier the tab", "mustard out", "muster it out",
    "muster out", "honorable discharge", "honorable discharge for it", "release it from service",
    "release it from duty", "free it from service", "free it from duty", "discharge it from duty",
    "end of service", "end of service for it", "service ended", "service is over",
    "duty is done", "duty calls elsewhere", "retire the number", "retire its number",
    "retire its jersey", "hang up its jersey", "hang up the jersey", "rafter it",
    "to the rafters", "immortalize it", "immortalise it", "hall of fame it",
    "put it in the hall", "put it in the hall of fame", "enshrine it", "enshrine the tab",
    "memorialize the tab", "commemorate it", "commemorate the tab", "honor its memory",
    "honour its memory", "honor its legacy", "honour its legacy", "cherish its memory",
    "treasure its memory", "remember it fondly", "remember it always", "rest in peace for it",
    "r i p it", "rip the tab", "say ri p", "rest easy tab",
    "rest easy", "sleep tight tab", "sleep tight", "sweet dreams tab",
    "sweet dreams for it", "good night tab", "good night sweet tab", "good night sweet prince",
    "flights of angels", "angels sing thee", "sing thee to thy rest", "parting is such sweet sorrow",
    "we hardly knew ye", "gone too soon", "taken too soon", "taken from us",
    "taken from us too soon", "lost but not forgotten", "forever in our hearts", "forever in our memory",
    "forever remembered", "always remembered", "eternally remembered", "in loving memory",
    "in memoriam for it", "dedication to it", "pour one out for it", "pour it out",
    "pour out a forty", "pour a forty for it", "pour a drink for it", "raise a glass",
    "raise a glass for it", "toast to it", "a toast to it", "raise a toast",
    "raise a toast to it", "drink to it", "drink to its memory", "cheers to it",
    "cheers to the tab", "farewell toast", "farewell toast for it", "bon voyage tab",
    "bon voyage for it", "safe travels tab", "safe journey tab", "godspeed tab",
    "godspeed for it", "godspeed to it", "another life for it", "send it to a better place",
    "send it to a better home", "a better place for it", "a better world for it", "to a better world",
    "off to a better place", "off to a better world", "it is in a better place", "in a better place now",
    "in a better place", "better off gone", "better off dead", "better off without it",
    "riddance for it", "glad to see it go", "glad to see the back of it", "good to see it go",
    "pleased to see it go", "happy to see it go", "happy to see the back of it", "wont miss it",
    "wont be missed", "will not be missed", "not missed", "unmourned",
    "unloved", "unwanted", "unwanted for it", "no one wanted it",
    "nobody wanted it", "no one will miss it", "nobody will miss it", "it was a mistake",
    "it was a mistake all along", "a mistake to open", "mistake of a tab", "worst tab ever",
    "worst tab", "the worst tab", "worst of the bunch", "rotten tab",
    "rotten to the core", "bad seed", "bad apple", "bad apple of a tab",
    "the bad one", "the bad tab", "the problem tab", "problem tab",
    "the trouble tab", "trouble tab", "the cursed tab", "cursed tab",
    "the damned tab", "damned tab", "the doomed tab", "doomed tab",
    "the accursed tab", "accursed tab", "降ろせ", "降ろして",
    "降ろすんだ", "降ろすべき", "降ろすべきだ", "降ろしたほうがいい",
    "中止せよ", "中止だ", "廃止するんだ", "停止せよ",
    "停止だ", "凍結しろ", "凍結せよ", "凍結だ",
    "凍結するんだ", "凍結すべき", "凍結すべきだ", "終わりにしろ",
    "終わりにせよ", "終わらせちゃえ", "惨殺しろ", "惨殺せよ",
    "惨殺だ", "虐殺しろ", "虐殺せよ", "虐殺だ",
    "鏖殺しろ", "皆殺しせよ", "血祭りだ", "血祭りにしろ",
    "血祭りにあげろ", "血祭りに上げろ", "生贄だ", "生贄にしろ",
    "生贄に捧げろ", "生贄にするんだ", "贄だ", "贄にしろ",
    "犠牲だ", "犠牲にしろ", "生け贄にしろ", "生け贄だ",
    "生け贄に捧げろ", "斬首しろ", "首を刎ねろ", "首をはねろ",
    "首を斬れ", "首刈れ", "首を刈れ", "首を落とせ",
    "首を落としてやれ", "八つ裂きにするんだ", "五馬分屍だ", "五馬分屍にしろ",
    "四肢切断だ", "四肢を切断しろ", "四肢切断しろ", "四肢をもげ",
    "串刺しだ", "串刺しにしろ", "串刺しにしてやれ", "串刺しにするんだ",
    "刺し殺せ", "刺し殺せよ", "刺し貫け", "刺し貫いて",
    "突き刺せ", "突き刺して", "切り刻め", "切り刻んで",
    "切り刻むんだ", "細切れにしろ", "細切れだ", "ミンチにしろ",
    "ミンチにしてやれ", "ミンチにするんだ", "ひき肉にしろ", "ひき肉にしてやれ",
    "握り潰せ", "握りつぶせ", "握り殺せ", "握り殺して",
    "絞め殺せ", "絞め殺して", "絞殺しろ", "絞殺だ",
    "扼殺しろ", "扼殺だ", "窒息させろ", "窒息させて",
    "窒息死させろ", "締め殺せ", "締め殺して", "締め上げろ",
    "絞め上げろ", "締めろ殺せ", "圧し潰せ", "押しつぶせ",
    "叩き潰せ", "叩き割れ", "叩き壊せ", "叩きのめせ",
    "叩き沈めろ", "撃ち殺せ", "撃ち殺して", "撃て",
    "撃って", "射殺せ", "射殺しろ", "射殺だ",
    "銃殺だ", "銃殺しろ", "銃殺刑だ", "銃殺刑にしろ",
    "蜂の巣にしろ", "蜂の巣にしてやれ", "蜂の巣だ", "平らげろ",
    "平らげて", "喰らい尽くせ", "食い尽くせ", "喰い殺せ",
    "喰い殺せよ", "喰い潰せ", "喰いつぶせ", "食い潰せ",
    "食いつぶせ", "骨まで食え", "骨まで喰え", "残さず食え",
    "残さず喰え", "バラバラにしてやれ", "八つに割れ", "四分五裂だ",
    "四分五裂にしろ", "木っ端微塵だ", "木っ端微塵にしろ", "消去するんだ",
    "消去すべきだ", "抹消するんだ", "抹消すべきだ", "削除するんだ",
    "消去対象だ", "抹消対象だ", "削除対象だ", "無かったことにするんだ",
    "痕跡を消去しろ", "証拠を消去しろ", "隠滅せよ", "もみ消せ",
    "もみ消して", "解雇せよ", "解雇するんだ", "クビにしてやれ",
    "クビにするんだ", "首を切れ会社から", "整理解雇だ", "整理解雇しろ",
    "人員整理だ", "人員整理しろ", "お役御免にしろ", "役目は終わりだ",
    "役目を終えました", "役割は終わりだ", "使命は終わりだ", "用済みとなった",
    "用が済みました", "用は済んだ", "用は終わった", "任務完了だ",
    "任務を完了した", "ミッション完了だ", "ミッションを完了した", "任務達成だ",
    "任務を達成した", "目的を達成した", "目的達成だ", "目的は果たした",
    "目的は果たしたぞ", "お勤めを果たした", "お勤め終了だ", "勤めを終えた",
    "勤めを果たした", "務めを果たした", "務めは終わった", "務めは終わりだ",
    "仕事を終えた", "仕事は終わった", "仕事は終わりだ", "役に立たない",
    "役に立たなくなった", "役に立たなくなったぞ", "役に立たん", "役に立たんな",
    "役に立たないな", "役立たずだ", "役立たずめ", "役に立たないゴミだ",
    "無用だ", "無用のものだ", "無用の長物だ", "長物だ",
    "お荷物だ", "お荷物だよ", "お荷物です", "お荷物になった",
    "お荷物となった", "お荷物だな", "荷物だ", "荷物になった",
    "足手まといだ", "足手まといだな", "足手まといになった", "邪魔だ",
    "邪魔だな", "邪魔になった", "邪魔ものだ", "邪魔者だ",
    "邪魔者め", "目障りだ", "目障りだな", "目障りものだ",
    "目障り者だ", "視界の邪魔だ", "邪魔だから消えろ", "邪魔だから消せ",
    "邪魔だから閉じろ", "邪魔だから殺せ", "邪魔者は消せ", "邪魔者は殺せ",
    "目障りだから消せ", "目障りだから消えろ", "目障りものは消せ", "目障りだから殺せ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});

describe('pass CCXLVII: vr-exit coverage', () => {
  test.each([
    "bon voyage", "safe travels", "safe journey", "godspeed",
    "fare thee well", "farewell for now", "until we meet again",
    "till we meet again", "until next time", "till next time", "see you on the other side",
    "see you in the next life", "see you in another life", "catch you in the next life", "meet again in another life",
    "until another life",
  ])('routes %s to vr-exit', (p) => {
    expect(key(mk(), p)).toBe('vr-exit');
  });
});
