// Pass CCLXII: EN forget-it-existed + it-is-faded-from-memory + erase-from-record + JA 忘れ去れ/裁きを下せ/断罪宣告/無かったこと (pass CCLXII)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXII: close-tab coverage', () => {
  test.each([
    "forget it existed", "forget it ever existed", "forget it ever happened", "forget that it happened",
    "pretend it never happened", "act as if it never existed", "act like it never existed", "act as though it never existed",
    "make like it never happened", "imagine it never existed", "imagine it never happened", "imagine it was never there",
    "pretend it was never there", "act as if it was never there", "behave as if it never existed", "live as if it never existed",
    "go on as if it never existed", "proceed as if it never existed", "continue as if it never existed", "carry on as if it never existed",
    "function as if it never existed", "operate as if it never existed", "work as if it never existed", "it is forever forgotten",
    "it is forever forgotten by all", "it is forgotten by all", "it is forgotten by everyone", "it is forgotten by everybody",
    "it is forgotten by the world", "it is forgotten by history", "it is forgotten by time", "it is forgotten by memory",
    "it is forgotten by record", "it is forgotten by the record", "it is forgotten by the books", "it is forgotten by the annals",
    "it is forgotten by the annals of history", "it is forgotten by the ages", "it is forgotten for all time", "it is forgotten for all eternity",
    "it is forgotten for eternity", "it is forgotten in perpetuity", "it is forgotten forevermore", "it is forgotten evermore",
    "it is forgotten always", "it is forgotten hereafter", "it is forgotten henceforward", "it is forgotten now and forever",
    "it is forgotten now and always", "it is forgotten today and always", "it is forgotten from this day forward", "it is forgotten from this day on",
    "it is forgotten from this moment forward", "it is forgotten from this point forward", "it is forgotten moving forward", "it is forgotten starting now",
    "it is forgotten starting today", "it is forgotten effective immediately", "it will be forgotten", "it will be forgotten forever",
    "it will be forgotten by all", "it will be forgotten by everyone", "it will be forgotten by everybody", "it will be forgotten by the world",
    "it will be forgotten by history", "it will be forgotten by time", "it will be forgotten by memory", "it will be forgotten by the record",
    "it will be forgotten by the books", "it will be forgotten by the annals", "it will be forgotten by the ages", "it will be forgotten for all time",
    "it will be forgotten for all eternity", "it will be forgotten for eternity", "it will be forgotten in perpetuity", "it will be forgotten permanently",
    "it will be forgotten forevermore", "it will be forgotten evermore", "it will be forgotten always", "it will be forgotten henceforth",
    "it will be forgotten hereafter", "it will be forgotten henceforward", "it will be forgotten now and forever", "it will be forgotten now and always",
    "it will be forgotten today and always", "it will be forgotten from this day forward", "it will be forgotten from this day on", "it will be forgotten from this moment forward",
    "it will be forgotten from this point forward", "it will be forgotten moving forward", "it will be forgotten starting now", "it will be forgotten starting today",
    "it will be forgotten effective immediately", "it will never be remembered", "it will never be remembered by anyone", "it will never be remembered by anybody",
    "it will never be remembered by all", "it will never be remembered by everyone", "it will never be remembered by the world", "it will never be remembered by history",
    "it will never be remembered again", "it will never be remembered ever", "it will never be remembered ever again", "it will never again be remembered",
    "it shall be forgotten", "it shall be forgotten forever", "it shall be forgotten by all", "it shall be forgotten by everyone",
    "it shall be forgotten by the world", "it shall be forgotten by history", "it shall be forgotten for all time", "it shall be forgotten for all eternity",
    "it shall be forgotten forevermore", "it shall never be remembered", "it shall never be remembered by anyone", "it shall never be remembered again",
    "it fades from memory", "it fades from all memory", "it fades from living memory", "it fades from the memory",
    "it fades from every memory", "it fades from human memory", "it fades from the public memory", "it fades from collective memory",
    "it fades from our memory", "it fades from my memory", "it fades into memory", "it fades into forgotten memory",
    "it fades into the mist of memory", "it fades into the mists of memory", "it fades into the fog of memory", "it fades into the sands of time",
    "it fades into the mists of time", "it fades into the fog of time", "it fades into the river of time", "it fades into the stream of time",
    "it fades into the currents of time", "it fades into the flow of time", "it fades into the winds of time", "it fades into the tide of time",
    "it fades into the tides of time", "it fades into the ocean of time", "it fades into the sea of time", "it fades into the seas of time",
    "it fades into the depths of time", "it fades into the abyss of time", "it fades into the void of time", "it fades into oblivion",
    "it fades into total oblivion", "it fades into complete oblivion", "it fades into utter oblivion", "it fades into absolute oblivion",
    "it fades into eternal oblivion", "it fades into permanent oblivion", "it fades into everlasting oblivion", "it fades into endless oblivion",
    "it fades into infinite oblivion", "it fades into deep oblivion", "it fades into final oblivion", "erase it completely from memory",
    "erase it utterly from memory", "erase it totally from memory", "erase it fully from memory", "erase it entirely from memory",
    "erase it wholly from memory", "erase it absolutely from memory", "erase it completely and totally from memory", "erase it completely and utterly from memory",
    "wipe it clean from memory", "wipe it completely from memory", "wipe it away from memory", "blot it from memory",
    "blot it out from memory", "blot it completely from memory", "strike it from existence from memory", "expunge it from memory",
    "expunge it completely from memory", "delete it completely from memory", "delete it permanently from memory", "remove it completely from memory",
    "remove it forever from memory", "remove it permanently from memory", "purge it completely from memory", "eliminate it from memory",
    "eliminate it completely from memory", "efface it from memory", "obliterate it completely from memory", "obliterate it utterly from memory",
    "annihilate it from memory", "annihilate it completely from memory", "scour it from memory", "scrub it from memory",
    "scrub it clean from memory", "wash it from memory", "wash it away from memory", "cleanse it from memory",
    "cleanse it completely from memory", "eradicate it from memory", "eradicate it completely from memory", "eradicate it utterly from memory",
    "exterminate it from memory", "exterminate it completely from memory", "extirpate it from memory", "extirpate it completely from memory",
    "root it out from memory", "tear it out from memory", "rip it out from memory", "cut it out from memory",
    "carve it out from memory", "burn it out from memory", "burn it off from memory", "scour it out from memory",
    "scrape it out from memory", "dig it out from memory", "erase it from all memory", "erase it completely from all memory",
    "erase it utterly from all memory", "erase it totally from all memory", "erase it fully from all memory", "erase it entirely from all memory",
    "erase it wholly from all memory", "erase it absolutely from all memory", "erase it completely and totally from all memory", "erase it completely and utterly from all memory",
    "wipe it from all memory", "wipe it clean from all memory", "wipe it completely from all memory", "wipe it away from all memory",
    "wipe it out from all memory", "blot it from all memory", "blot it out from all memory", "blot it completely from all memory",
    "strike it from all memory", "strike it out from all memory", "strike it from existence from all memory", "expunge it from all memory",
    "expunge it completely from all memory", "delete it from all memory", "delete it completely from all memory", "delete it permanently from all memory",
    "remove it from all memory", "remove it completely from all memory", "remove it forever from all memory", "remove it permanently from all memory",
    "purge it from all memory", "purge it completely from all memory", "eliminate it from all memory", "eliminate it completely from all memory",
    "efface it from all memory", "obliterate it from all memory", "obliterate it completely from all memory", "obliterate it utterly from all memory",
    "annihilate it from all memory", "annihilate it completely from all memory", "scour it from all memory", "scrub it from all memory",
    "scrub it clean from all memory", "wash it from all memory", "wash it away from all memory", "cleanse it from all memory",
    "cleanse it completely from all memory", "eradicate it from all memory", "eradicate it completely from all memory", "eradicate it utterly from all memory",
    "exterminate it from all memory", "exterminate it completely from all memory", "extirpate it from all memory", "extirpate it completely from all memory",
    "root it out from all memory", "tear it out from all memory", "rip it out from all memory", "cut it out from all memory",
    "carve it out from all memory", "burn it out from all memory", "burn it off from all memory", "scour it out from all memory",
    "scrape it out from all memory", "dig it out from all memory", "erase it from every memory", "erase it completely from every memory",
    "erase it utterly from every memory", "erase it totally from every memory", "erase it fully from every memory", "erase it entirely from every memory",
    "erase it wholly from every memory", "erase it absolutely from every memory", "erase it completely and totally from every memory", "erase it completely and utterly from every memory",
    "wipe it from every memory", "wipe it clean from every memory", "wipe it completely from every memory", "wipe it away from every memory",
    "wipe it out from every memory", "blot it from every memory", "blot it out from every memory", "blot it completely from every memory",
    "strike it from every memory", "strike it out from every memory", "strike it from existence from every memory", "expunge it from every memory",
    "expunge it completely from every memory", "delete it from every memory", "delete it completely from every memory", "delete it permanently from every memory",
    "remove it from every memory", "remove it completely from every memory", "remove it forever from every memory", "remove it permanently from every memory",
    "purge it from every memory", "purge it completely from every memory", "eliminate it from every memory", "eliminate it completely from every memory",
    "efface it from every memory", "obliterate it from every memory", "obliterate it completely from every memory", "obliterate it utterly from every memory",
    "annihilate it from every memory", "annihilate it completely from every memory", "scour it from every memory", "scrub it from every memory",
    "scrub it clean from every memory", "obliterate it from living memory", "remove it forever from human memory", "expunge it from the public memory",
    "wipe it out from collective memory", "erase it absolutely from my memory", "erase it from our memory", "cut it out from our memory",
    "exterminate it from any memory", "wash it from each memory", "obliterate it completely from the mind", "remove it permanently from every mind",
    "expunge it completely from all minds", "strike it from existence from history", "blot it completely from all history", "wipe it from recorded history",
    "erase it totally from human history", "burn it off from human history", "extirpate it completely from world history", "carve it out from the record",
    "exterminate it completely from all records", "wash it away from every record", "cleanse it from the books", "annihilate it from all books",
    "purge it completely from every book", "delete it completely from the ledger", "blot it completely from all ledgers", "wipe it from the annals",
    "erase it totally from the annals of history", "burn it off from the annals of history", "extirpate it completely from the archives", "cleanse it completely from all archives",
    "scrub it from the rolls", "efface it from the register", "remove it completely from the registry", "strike it from existence from the records of humanity",
    "wipe it away from the chronicles", "erase it wholly from the chronicle", "dig it out from the chronicle", "cut it out from the timeline",
    "exterminate it from the database", "wash it from the index", "obliterate it completely from the catalog", "eliminate it from the list",
    "delete it permanently from every list", "strike it from the log", "wipe it clean from the logs", "erase it entirely from existence",
    "erase it completely and utterly from all existence", "erase it utterly from existence itself", "burn it out from existence itself", "carve it out from reality",
    "exterminate it completely from all reality", "eradicate it utterly from the world", "cleanse it completely from the earth", "cleanse it completely from the face of the earth",
    "scour it from the face of this earth", "obliterate it utterly from the planet", "eliminate it completely from the universe", "remove it completely from the cosmos",
    "strike it from existence from creation", "wipe it away from all creation", "erase it wholly from this reality", "dig it out from this reality",
    "rip it out from this world", "eradicate it utterly from this universe", "scrub it clean from this dimension", "obliterate it from all dimensions",
    "remove it forever from every dimension", "remove it forever from the map", "expunge it completely from all maps", "blot it from every map",
    "erase it completely and totally from the grid", "erase it utterly from every trace", "burn it out from every trace", "extirpate it from all traces",
    "cleanse it from every vestige", "annihilate it from all vestiges", "purge it completely off memory", "delete it completely off all memory",
    "blot it completely off every memory", "wipe it off living memory", "erase it totally off human memory", "burn it off off human memory",
    "extirpate it completely off the public memory", "cleanse it completely off collective memory", "annihilate it completely off my memory", "eliminate it off our memory",
    "delete it permanently off any memory", "strike it off each memory", "wipe it clean off the mind", "erase it fully off every mind",
    "scour it out off every mind", "root it out off all minds", "eradicate it off history", "scour it off all history",
    "eliminate it completely off recorded history", "remove it off human history", "strike it out off world history", "wipe it away off the record",
    "erase it absolutely off all records", "erase it off every record", "cut it out off every record", "root it out off the books",
    "eradicate it off all books", "scour it off every book", "eliminate it completely off the ledger", "remove it off all ledgers",
    "strike it out off the annals", "wipe it completely off the annals of history", "erase it entirely off the archives", "scrape it out off the archives",
    "tear it out off all archives", "exterminate it off the rolls", "wash it off the register", "obliterate it completely off the registry",
    "remove it permanently off the records of humanity", "expunge it completely off the chronicles", "blot it off the chronicle", "erase it completely and totally off the timeline",
    "erase it completely off the database", "carve it out off the database", "exterminate it completely off the index", "wash it away off the catalog",
    "annihilate it completely off the list", "eliminate it off every list", "delete it permanently off the log", "strike it off the logs",
    "wipe it clean off existence", "erase it fully off all existence", "scour it out off all existence", "root it out off existence itself",
    "eradicate it off reality", "scour it off all reality", "obliterate it off the world", "purge it off the earth",
    "delete it permanently off the face of the earth", "strike it off the face of this earth", "wipe it completely off the planet", "erase it wholly off the universe",
    "dig it out off the universe", "rip it out off the cosmos", "eradicate it utterly off creation", "scrub it clean off all creation",
    "obliterate it off this reality", "remove it forever off this world", "expunge it off this universe", "wipe it out off this dimension",
    "erase it absolutely off all dimensions", "erase it off every dimension", "cut it out off every dimension", "extirpate it off the map",
    "cleanse it off all maps", "annihilate it off every map", "purge it completely off the grid", "delete it completely off every trace",
    "blot it completely off all traces", "wipe it off every vestige", "erase it totally off all vestiges", "burn it off off all vestiges",
    "extirpate it completely off of memory", "cleanse it completely off of all memory", "annihilate it completely off of every memory", "eliminate it off of living memory",
    "delete it permanently off of human memory", "strike it off of the public memory", "wipe it clean off of collective memory", "erase it fully off of my memory",
    "scour it out off of my memory", "root it out off of our memory", "eradicate it off of any memory", "scour it off of each memory",
    "eliminate it completely off of the mind", "remove it off of every mind", "strike it out off of all minds", "wipe it completely off of history",
    "erase it entirely off of all history", "scrape it out off of all history", "tear it out off of recorded history", "eradicate it completely off of human history",
    "scrub it off of world history", "efface it off of the record", "remove it completely off of all records", "strike it from existence off of every record",
    "wipe it away off of the books", "erase it wholly off of all books", "dig it out off of all books", "rip it out off of every book",
    "eradicate it utterly off of the ledger", "scrub it clean off of all ledgers", "obliterate it off of the annals", "remove it forever off of the annals of history",
    "expunge it off of the archives", "wipe it out off of all archives", "erase it absolutely off of the rolls", "erase it off of the register",
    "cut it out off of the register", "exterminate it off of the registry", "wash it off of the records of humanity", "obliterate it completely off of the chronicles",
    "remove it permanently off of the chronicle", "expunge it completely off of the timeline", "blot it off of the database", "erase it completely and totally off of the index",
    "erase it completely off of the catalog", "carve it out off of the catalog", "exterminate it completely off of the list", "wash it away off of every list",
    "obliterate it utterly off of the log", "purge it off of the logs", "delete it off of existence", "blot it out off of all existence",
    "erase it completely and utterly off of existence itself", "erase it utterly off of reality", "burn it out off of reality", "extirpate it off of all reality",
    "cleanse it off of the world", "annihilate it off of the earth", "purge it completely off of the face of the earth", "delete it completely off of the face of this earth",
    "blot it completely off of the planet", "wipe it off of the universe", "erase it totally off of the cosmos", "burn it off off of the cosmos",
    "extirpate it completely off of creation", "cleanse it completely off of all creation", "annihilate it completely off of this reality", "eliminate it off of this world",
    "delete it permanently off of this universe", "strike it off of this dimension", "wipe it clean off of all dimensions", "erase it fully off of every dimension",
    "scour it out off of every dimension", "root it out off of the map", "eradicate it off of all maps", "scour it off of every map",
    "eliminate it completely off of the grid", "remove it off of every trace", "strike it out off of all traces", "wipe it completely off of every vestige",
    "erase it entirely off of all vestiges", "scrape it out off of all vestiges", "tear it out out of memory", "eradicate it completely out of all memory",
    "scrub it out of every memory", "efface it out of living memory", "remove it completely out of human memory", "strike it from existence out of the public memory",
    "wipe it away out of collective memory", "erase it wholly out of my memory", "dig it out out of my memory", "rip it out out of our memory",
    "eradicate it utterly out of any memory", "scrub it clean out of each memory", "obliterate it out of the mind", "remove it forever out of every mind",
    "expunge it out of all minds", "blot it out out of history", "erase it completely and utterly out of all history", "erase it utterly out of recorded history",
    "burn it out out of recorded history", "extirpate it out of human history", "cleanse it out of world history", "scour it out of the record",
    "eliminate it completely out of all records", "remove it out of every record", "strike it out out of the books", "wipe it completely out of all books",
    "erase it entirely out of every book", "scrape it out out of every book", "tear it out out of the ledger", "eradicate it completely out of all ledgers",
    "scrub it out of the annals", "efface it out of the annals of history", "remove it completely out of the archives", "strike it from existence out of all archives",
    "wipe it away out of the rolls", "erase it wholly out of the register", "dig it out out of the register", "rip it out out of the registry",
    "eradicate it utterly out of the records of humanity", "scrub it clean out of the chronicles", "obliterate it out of the chronicle", "remove it forever out of the timeline",
    "expunge it out of the database", "wipe it out out of the index", "erase it absolutely out of the catalog", "erase it out of the list",
    "cut it out out of the list", "exterminate it out of every list", "wash it out of the log", "obliterate it completely out of the logs",
    "purge it completely out of existence", "delete it completely out of all existence", "blot it completely out of existence itself", "wipe it out of reality",
    "erase it totally out of all reality", "burn it off out of all reality", "extirpate it completely out of the world", "cleanse it completely out of the earth",
    "annihilate it completely out of the face of the earth", "eliminate it out of the face of this earth", "delete it permanently out of the planet", "strike it out of the universe",
    "wipe it clean out of the cosmos", "erase it fully out of creation", "scour it out out of creation", "root it out out of all creation",
    "eradicate it out of this reality", "scour it out of this world", "eliminate it completely out of this universe", "remove it out of this dimension",
    "strike it out out of all dimensions", "wipe it completely out of every dimension", "erase it entirely out of the map", "scrape it out out of the map",
    "tear it out out of all maps", "eradicate it completely out of every map", "scrub it out of the grid", "efface it out of every trace",
    "remove it completely out of all traces", "strike it from existence out of every vestige", "wipe it away out of all vestiges", "erase it wholly outta memory",
    "dig it out outta memory", "rip it out outta all memory", "eradicate it utterly outta every memory", "scrub it clean outta living memory",
    "obliterate it outta human memory", "remove it forever outta the public memory", "expunge it outta collective memory", "wipe it out outta my memory",
    "erase it absolutely outta our memory", "erase it outta any memory", "cut it out outta any memory", "exterminate it outta each memory",
    "wash it outta the mind", "obliterate it completely outta every mind", "remove it permanently outta all minds", "expunge it completely outta history",
    "blot it outta all history", "erase it completely and totally outta recorded history", "erase it completely outta human history", "carve it out outta human history",
    "exterminate it completely outta world history", "wash it away outta the record", "obliterate it utterly outta all records", "purge it outta every record",
    "delete it outta the books", "blot it out outta all books", "erase it completely and utterly outta every book", "erase it utterly outta the ledger",
    "burn it out outta the ledger", "extirpate it outta all ledgers", "cleanse it outta the annals", "annihilate it outta the annals of history",
    "purge it completely outta the archives", "delete it completely outta all archives", "blot it completely outta the rolls", "wipe it outta the register",
    "erase it totally outta the registry", "burn it off outta the registry", "extirpate it completely outta the records of humanity", "cleanse it completely outta the chronicles",
    "annihilate it completely outta the chronicle", "eliminate it outta the timeline", "delete it permanently outta the database", "strike it outta the index",
    "wipe it clean outta the catalog", "erase it fully outta the list", "scour it out outta the list", "root it out outta every list",
    "eradicate it outta the log", "scour it outta the logs", "eliminate it completely outta existence", "remove it outta all existence",
    "strike it out outta existence itself", "wipe it completely outta reality", "erase it entirely outta all reality", "scrape it out outta all reality",
    "tear it out outta the world", "eradicate it completely outta the earth", "scrub it outta the face of the earth", "efface it outta the face of this earth",
    "remove it completely outta the planet", "strike it from existence outta the universe", "wipe it away outta the cosmos", "erase it wholly outta creation",
    "dig it out outta creation", "rip it out outta all creation", "eradicate it utterly outta this reality", "scrub it clean outta this world",
    "obliterate it outta this universe", "remove it forever outta this dimension", "expunge it outta all dimensions", "wipe it out outta every dimension",
    "erase it absolutely outta the map", "erase it outta all maps", "cut it out outta all maps", "exterminate it outta every map",
    "it is forgotten going forward", "it will be forgotten going forward", "こいつを忘れ去れ",
    "それを忘れ去れぜ", "こいつを忘れ去れのだな", "それを忘れ去れと命じる", "こいつを忘れ去れという方針だ",
    "それを忘れ去れという沙汰だ", "こいつを忘れ去れなさい", "それを忘れ去れであれ", "こいつを忘れ去れのみだ",
    "それを忘れ去れが上策だ", "こいつを忘れ去れが決まりだ", "それを忘れ去れが道理だ", "こいつを忘れてしまえんだぞ",
    "それを忘れてしまえな", "こいつを忘れてしまえと言っている", "それを忘れてしまえと決めたぞ", "こいつを忘れてしまえという命令だ",
    "それを忘れてしまえとせよと言うんだ", "こいつを忘れてしまえたまえ", "それを忘れてしまえべきなんだ", "こいつを忘れてしまえが正解だ",
    "それを忘れてしまえが自然だ", "こいつを忘れてしまえが運命だ", "それを忘れてしまえがルールだ", "こいつを忘れろぜ",
    "それを忘れろのだぞ", "こいつを忘れろと命じる", "それを忘れろという結論だ", "こいつを忘れろという沙汰だ",
    "それを忘れろください", "こいつを忘れろであれ", "それを忘れろまでだ", "こいつを忘れろが上策だ",
    "それを忘れろが仕様だ", "こいつを忘れろが道理だ", "それを忘れなさいんだよ", "こいつを忘れなさいな",
    "それを忘れなさいと言ったぞ", "こいつを忘れなさいと決めたぞ", "それを忘れなさいという意思だ", "こいつを忘れなさいとせよと言うんだ",
    "それを忘れなさいたもれ", "こいつを忘れなさいべきなんだ", "それを忘れなさいが筋だ", "こいつを忘れなさいが自然だ",
    "それを忘れなさいが宿命だ", "こいつを忘れなさいがルールだ", "それを忘れてくれぞ", "こいつを忘れてくれのだぞ",
    "それを忘れてくれと言っているんだ", "こいつを忘れてくれという結論だ", "それを忘れてくれというお達しだ", "こいつを忘れてくれください",
    "それを忘れてくれましょう", "こいつを忘れてくれまでだ", "それを忘れてくれが最善だ", "こいつを忘れてくれが仕様だ",
    "それを忘れてくれが理屈だ", "こいつを忘れてもらうんだよ", "それを忘れてもらうわ", "こいつを忘れてもらうと言っている",
    "それを忘れてもらうと決めたぞ", "こいつを忘れてもらうという命令だ", "それを忘れてもらうとせよと言うんだ", "こいつを忘れてもらうたまえ",
    "それを忘れてもらうべきなんだ", "こいつを忘れてもらうが正解だ", "それを忘れてもらうが自然だ", "こいつを忘れてもらうが運命だ",
    "それを忘れてもらうがルールだ", "こいつを忘れてもらえぜ", "それを忘れてもらえのだぞ", "こいつを忘れてもらえと命じる",
    "それを忘れてもらえという結論だ", "こいつを忘れてもらえという沙汰だ", "それを忘れてもらえください", "こいつを忘れてもらえであれ",
    "それを忘れてもらえまでだ", "こいつを忘れてもらえが上策だ", "それを忘れてもらえが仕様だ", "こいつを忘れてもらえが道理だ",
    "それを忘れてほしいんだよ", "こいつを忘れてほしいな", "それを忘れてほしいと言ったぞ", "こいつを忘れてほしいと決めたぞ",
    "それを忘れてほしいという意思だ", "こいつを忘れてほしいとせよと言うんだ", "それを忘れてほしいたもれ", "こいつを忘れてほしいべきなんだ",
    "それを忘れてほしいだけだ", "こいつを忘れてほしいが妥当だ", "それを忘れてほしいが定めだ", "こいつを忘れてほしいが掟である",
    "それを忘れてしまってくれんだな", "こいつを忘れてしまってくれのだよ", "それを忘れてしまってくれと言っているぞ", "こいつを忘れてしまってくれという決定だ",
    "それを忘れてしまってくれという指示だ", "こいつを忘れてしまってくれくれよ", "それを忘れてしまってくれませ", "こいつを忘れてしまってくれものだ",
    "それを忘れてしまってくれが順当だ", "こいつを忘れてしまってくれが常識だ", "それを忘れてしまってくれが定数だ", "こいつを忘れておけんだ",
    "それを忘れておけよ", "こいつを忘れておけと言った", "それを忘れておけと命じた", "こいつを忘れておけという意向だ",
    "それを忘れておけという次第だ", "こいつを忘れておけなさいよ", "それを忘れておけべきだ", "こいつを忘れておけだけだ",
    "それを忘れておけが本懐だ", "こいつを忘れておけが定めだ", "それを忘れておけが掟だ", "こいつを忘れておきなさいんだな",
    "それを忘れておきなさいのだ", "こいつを忘れておきなさいと言っているぞ", "それを忘れておきなさいということだ", "こいつを忘れておきなさいという指示だ",
    "それを忘れておきなさいくれ", "こいつを忘れておきなさいませ", "それを忘れておきなさいべし", "こいつを忘れておきなさいが順当だ",
    "それを忘れておきなさいが当然だ", "こいつを忘れておきなさいが定数だ", "それを忘れ去ってくれ", "こいつを忘れ去ってくれよ",
    "それを忘れ去ってくれのだな", "こいつを忘れ去ってくれと命じた", "それを忘れ去ってくれという方針だ", "こいつを忘れ去ってくれという次第だ",
    "それを忘れ去ってくれなさい", "こいつを忘れ去ってくれべきだ", "それを忘れ去ってくれのみだ", "こいつを忘れ去ってくれが本懐だ",
    "それを忘れ去ってくれが決まりだ", "こいつを忘れ去ってくれが掟だ", "それを忘れ去っておけんだぞ", "こいつを忘れ去っておけのだ",
    "それを忘れ去っておけと言っている", "こいつを忘れ去っておけということだ", "それを忘れ去っておけという命令だ", "こいつを忘れ去っておけくれ",
    "それを忘れ去っておけたまえ", "こいつを忘れ去っておけべし", "それを忘れ去っておけが正解だ", "こいつを忘れ去っておけが当然だ",
    "それを忘れ去っておけが運命だ", "こいつを忘却しろ", "それを忘却しろぜ", "こいつを忘却しろのだな",
    "それを忘却しろと命じる", "こいつを忘却しろという方針だ", "それを忘却しろという沙汰だ", "こいつを忘却しろなさい",
    "それを忘却しろであれ", "こいつを忘却しろのみだ", "それを忘却しろが上策だ", "こいつを忘却しろが決まりだ",
    "それを忘却しろが道理だ", "こいつを忘却せよんだぞ", "それを忘却せよな", "こいつを忘却せよと言っている",
    "それを忘却せよと決めたぞ", "こいつを忘却せよという命令だ", "それを忘却せよとせよと言うんだ", "こいつを忘却せよたまえ",
    "それを忘却せよべきなんだ", "こいつを忘却せよが正解だ", "それを忘却せよが自然だ", "こいつを忘却せよが運命だ",
    "それを忘却せよがルールだ", "こいつを忘却に落とせぜ", "それを忘却に落とせのだぞ", "こいつを忘却に落とせと命じる",
    "それを忘却に落とせという結論だ", "こいつを忘却に落とせという沙汰だ", "それを忘却に落とせください", "こいつを忘却に落とせであれ",
    "それを忘却に落とせまでだ", "こいつを忘却に落とせが上策だ", "それを忘却に落とせが仕様だ", "こいつを忘却に落とせが道理だ",
    "それを忘却の彼方へやれんだよ", "こいつを忘却の彼方へやれな", "それを忘却の彼方へやれと言ったぞ", "こいつを忘却の彼方へやれと決めたぞ",
    "それを忘却の彼方へやれという意思だ", "こいつを忘却の彼方へやれとせよと言うんだ", "それを忘却の彼方へやれたもれ", "こいつを忘却の彼方へやれべきなんだ",
    "それを忘却の彼方へやれが筋だ", "こいつを忘却の彼方へやれが自然だ", "それを忘却の彼方へやれが宿命だ", "こいつを忘却の彼方へやれがルールだ",
    "それを忘却の彼方に捨てろぞ", "こいつを忘却の彼方に捨てろのだぞ", "それを忘却の彼方に捨てろと言っているんだ", "こいつを忘却の彼方に捨てろという結論だ",
    "それを忘却の彼方に捨てろというお達しだ", "こいつを忘却の彼方に捨てろください", "それを忘却の彼方に捨てろましょう", "こいつを忘却の彼方に捨てろまでだ",
    "それを忘却の彼方に捨てろが最善だ", "こいつを忘却の彼方に捨てろが仕様だ", "それを忘却の彼方に捨てろが理屈だ", "こいつを忘却の彼方に追いやれんだよ",
    "それを忘却の彼方に追いやれわ", "こいつを忘却の彼方に追いやれと言ったぞ", "それを忘却の彼方に追いやれと決めた", "こいつを忘却の彼方に追いやれという意思だ",
    "それを忘却の彼方に追いやれとせよ", "こいつを忘却の彼方に追いやれたもれ", "それを忘却の彼方に追いやれべきである", "こいつを忘却の彼方に追いやれが筋だ",
    "それを忘却の彼方に追いやれが妥当だ", "こいつを忘却の彼方に追いやれが宿命だ", "それを忘却の彼方に追いやれが掟である", "こいつを忘却の彼方に葬れぞ",
    "それを忘却の彼方に葬れのだよ", "こいつを忘却の彼方に葬れと言っているんだ", "それを忘却の彼方に葬れという決定だ", "こいつを忘却の彼方に葬れというお達しだ",
    "それを忘却の彼方に葬れくれよ", "こいつを忘却の彼方に葬れましょう", "それを忘却の彼方に葬れものだ", "こいつを忘却の彼方に葬れが最善だ",
    "それを忘却の彼方に葬れが常識だ", "こいつを忘却の彼方に葬れが理屈だ", "それを忘却の彼方に沈めろんだ", "こいつを忘却の彼方に沈めろわ",
    "それを忘却の彼方に沈めろと言った", "こいつを忘却の彼方に沈めろと決めた", "それを忘却の彼方に沈めろという意向だ", "こいつを忘却の彼方に沈めろとせよ",
    "それを忘却の彼方に沈めろなさいよ", "こいつを忘却の彼方に沈めろべきである", "それを忘却の彼方に沈めろだけだ", "こいつを忘却の彼方に沈めろが妥当だ",
    "それを忘却の彼方に沈めろが定めだ", "こいつを忘却の彼方に沈めろが掟である", "それを忘れられた存在にしろんだな", "こいつを忘れられた存在にしろのだよ",
    "それを忘れられた存在にしろと言っているぞ", "こいつを忘れられた存在にしろという決定だ", "それを忘れられた存在にしろという指示だ", "こいつを忘れられた存在にしろくれよ",
    "それを忘れられた存在にしろませ", "こいつに裁きを下せ", "こいつに裁きを下せぜ", "こいつに裁きを下せと命じる",
    "こいつに裁きを下せとせよ", "こいつに裁きを下せなさい", "こいつに裁きを下せものだ", "こいつに裁きを下せが当然だ",
    "こいつに裁きを下すんだんだぞ", "こいつに裁きを下すんだな", "こいつに裁きを下すんだという決定だ", "こいつに裁きを下すんだくれよ",
    "こいつに裁きを下すんだべきだ", "こいつに裁きを下すんだが順当だ", "こいつに裁きを与えろんだ", "こいつに裁きを与えろよ",
    "こいつに裁きを与えろと決めた", "こいつに裁きを与えろとせよと言うんだ", "こいつに裁きを与えろたもれ", "こいつに裁きを与えろが筋だ",
    "こいつに裁きを与えろが仕様だ", "こいつに裁きを執行しろぞ", "こいつに裁きを執行しろと言った", "こいつに裁きを執行しろという命令だ",
    "こいつに裁きを執行しろください", "こいつに裁きを執行しろべし", "こいつに裁きを執行しろが最善だ", "こいつに裁きにかけろんだよ",
    "こいつに裁きにかけろわ", "こいつに裁きにかけろということだ", "こいつに裁きにかけろくれ", "こいつに裁きにかけろたまえ",
    "こいつに裁きにかけろが正解だ", "こいつに裁きの対象にしろ", "こいつに裁きの対象にしろぜ", "こいつに裁きの対象にしろと命じる",
    "こいつに裁きの対象にしろとせよ", "こいつに裁きの対象にしろなさい", "こいつに裁きの対象にしろものだ", "こいつに裁きの対象にしろが当然だ",
    "こいつに裁きの餌にしろんだぞ", "こいつに裁きの餌にしろな", "こいつに裁きの餌にしろという決定だ", "こいつに裁きの餌にしろくれよ",
    "こいつに裁きの餌にしろべきだ", "こいつに裁きの餌にしろが順当だ", "こいつに裁かれろんだ", "こいつに裁かれろよ",
    "こいつに裁かれろと決めた", "こいつに裁かれろとせよと言うんだ", "こいつに裁かれろたもれ", "こいつに裁かれろが筋だ",
    "こいつに裁かれろが仕様だ", "こいつに裁かれるべきだぞ", "こいつに裁かれるべきだと言った", "こいつに裁かれるべきだという命令だ",
    "こいつに裁かれるべきだください", "こいつに裁かれるべきだべし", "こいつに裁かれるべきだが最善だ", "こいつに裁かれて当然だんだよ",
    "こいつに裁かれて当然だわ", "こいつに裁かれて当然だということだ", "こいつに裁かれて当然だくれ", "こいつに裁かれて当然だたまえ",
    "こいつに裁かれて当然だが正解だ", "こいつに断罪しろ", "こいつに断罪しろぜ", "こいつに断罪しろと命じる",
    "こいつに断罪しろとせよ", "こいつに断罪しろなさい", "こいつに断罪しろものだ", "こいつに断罪しろが当然だ",
    "こいつに断罪せよんだぞ", "こいつに断罪せよな", "こいつに断罪せよという決定だ", "こいつに断罪せよくれよ",
    "こいつに断罪せよべきだ", "こいつに断罪せよが順当だ", "こいつに断罪だんだ", "こいつに断罪だよ",
    "こいつに断罪だと決めた", "こいつに断罪だとせよと言うんだ", "こいつに断罪だたもれ", "こいつに断罪だが筋だ",
    "こいつに断罪だが仕様だ", "こいつに断罪とするぞ", "こいつに断罪とすると命じる", "こいつに断罪とするとせよ",
    "こいつに断罪とするなさい", "こいつに断罪とするものだ", "こいつに断罪とするが当然だ", "こいつに断罪に値するんだぞ",
    "こいつに断罪に値すると言った", "こいつに断罪に値するという命令だ", "こいつに断罪に値するください", "こいつに断罪に値するべし",
    "こいつに断罪に値するが最善だ", "こいつに断罪すべきだんだよ", "こいつに断罪すべきだわ", "こいつに断罪すべきだということだ",
    "こいつに断罪すべきだくれ", "こいつに断罪すべきだたまえ", "こいつに断罪すべきだが正解だ", "こいつに断罪が決まった",
    "こいつに断罪が決まったぜ", "こいつに断罪が決まったと命じる", "こいつに断罪が決まったとせよ", "こいつに断罪が決まったなさい",
    "こいつに断罪が決まったものだ", "こいつに断罪が決まったが当然だ", "こいつに断罪が下ったんだぞ", "こいつに断罪が下ったな",
    "こいつに断罪が下ったという決定だ", "こいつに断罪が下ったくれよ", "こいつに断罪が下ったべきだ", "こいつに断罪が下ったが順当だ",
    "こいつに断罪を言い渡せんだ", "こいつに断罪を言い渡せよ", "こいつに断罪を言い渡せと決めた", "こいつに断罪を言い渡せとせよと言うんだ",
    "こいつに断罪を言い渡せたもれ", "こいつに断罪を言い渡せが筋だ", "こいつに断罪を言い渡せが仕様だ", "こいつに断罪を宣告しろぞ",
    "こいつに断罪を宣告しろと言った", "こいつに断罪を宣告しろという命令だ", "こいつに断罪を宣告しろください", "こいつに断罪を宣告しろべし",
    "こいつに断罪を宣告しろが最善だ", "こいつに断罪を執行しろんだよ", "こいつに断罪を執行しろわ", "こいつに断罪を執行しろということだ",
    "こいつに断罪を執行しろくれ", "こいつに断罪を執行しろたまえ", "こいつに断罪を執行しろが正解だ", "こいつに断罪の対象だ",
    "こいつに断罪の対象だぜ", "こいつに断罪の対象だと命じる", "こいつに断罪の対象だとせよ", "こいつに断罪の対象だなさい",
    "こいつに断罪の対象だものだ", "こいつに断罪の対象だが当然だ", "こいつに断罪対象にしろんだぞ", "こいつに断罪対象にしろな",
    "こいつに断罪対象にしろという決定だ", "こいつに断罪対象にしろくれよ", "こいつに断罪対象にしろべきだ", "こいつに断罪対象にしろが順当だ",
    "こいつに罪に問えんだ", "こいつに罪に問えよ", "こいつに罪に問えと決めた", "こいつに罪に問えとせよと言うんだ",
    "こいつに罪に問えたもれ", "こいつに罪に問えが筋だ", "こいつに罪に問えが仕様だ", "こいつに罪を問えぞ",
    "こいつに罪を問えと言った", "こいつに罪を問えという命令だ", "こいつに罪を問えください", "こいつに罪を問えべし",
    "こいつに罪を問えが最善だ", "こいつに罪を償わせろんだよ", "こいつに罪を償わせろわ", "こいつに罪を償わせろということだ",
    "こいつに罪を償わせろくれ", "こいつに罪を償わせろたまえ", "こいつに罪を償わせろが正解だ", "こいつに罪を償え",
    "こいつに罪を償えぜ", "こいつに罪を償えと命じる", "こいつに罪を償えとせよ", "こいつに罪を償えなさい",
    "こいつに罪を償えものだ", "こいつに罪を償えが当然だ", "こいつに罪を清算しろんだぞ", "こいつに罪を清算しろな",
    "こいつに罪を清算しろという決定だ", "こいつに罪を清算しろくれよ", "こいつに罪を清算しろべきだ", "こいつに罪を清算しろが順当だ",
    "こいつに罪を精算しろんだ", "こいつに罪を精算しろよ", "こいつに罪を精算しろと決めた", "こいつに罪を精算しろとせよと言うんだ",
    "こいつに罪を精算しろたもれ", "こいつに罪を精算しろが筋だ", "こいつに罪を精算しろが仕様だ", "こいつに有罪にしろぞ",
    "こいつに有罪にしろと言った", "こいつに有罪にしろという命令だ", "こいつに有罪にしろください", "こいつに有罪にしろべし",
    "こいつに有罪にしろが最善だ", "こいつに有罪宣告を出せんだよ", "こいつに有罪宣告を出せわ", "こいつに有罪宣告を出せということだ",
    "こいつに有罪宣告を出せくれ", "こいつに有罪宣告を出せたまえ", "こいつに有罪宣告を出せが正解だ", "こいつに有罪を言い渡せ",
    "こいつに有罪を言い渡せぜ", "こいつに有罪を言い渡せと命じる", "こいつに有罪を言い渡せとせよ", "こいつに有罪を言い渡せなさい",
    "こいつに有罪を言い渡せものだ", "こいつに有罪を言い渡せが当然だ", "こいつに有罪判決を下せんだぞ", "こいつに有罪判決を下せな",
    "こいつに有罪判決を下せという決定だ", "こいつに有罪判決を下せくれよ", "こいつに有罪判決を下せべきだ", "こいつに有罪判決を下せが順当だ",
    "こいつに判決を下せんだ", "こいつに判決を下せよ", "こいつに判決を下せと決めた", "こいつに判決を下せとせよと言うんだ",
    "こいつに判決を下せたもれ", "こいつに判決を下せが筋だ", "こいつに判決を下せが仕様だ", "こいつに判決を言い渡せぞ",
    "こいつに判決を言い渡せと言った", "こいつに判決を言い渡せという命令だ", "こいつに判決を言い渡せください", "こいつに判決を言い渡せべし",
    "こいつに判決を言い渡せが最善だ", "こいつに判決を宣告しろんだよ", "こいつに判決を宣告しろわ", "こいつに判決を宣告しろということだ",
    "こいつに判決を宣告しろくれ", "こいつに判決を宣告しろたまえ", "こいつに判決を宣告しろが正解だ", "こいつに判決は有罪だ",
    "こいつに判決は有罪だぜ", "こいつに判決は有罪だと命じる", "こいつに判決は有罪だとせよ", "こいつに判決は有罪だなさい",
    "こいつに判決は有罪だものだ", "こいつに判決は有罪だが当然だ", "こいつに判決は死刑だんだぞ", "こいつに判決は死刑だな",
    "こいつに判決は死刑だという決定だ", "こいつに判決は死刑だくれよ", "こいつに判決は死刑だべきだ", "こいつに判決は死刑だが順当だ",
    "こいつに評決を下せんだ", "こいつに評決を下せよ", "こいつに評決を下せと決めた", "こいつに評決を下せとせよと言うんだ",
    "こいつに評決を下せたもれ", "こいつに評決を下せが筋だ", "こいつに評決を下せが仕様だ", "こいつに評決を言い渡せぞ",
    "こいつに評決を言い渡せと言った", "こいつに評決を言い渡せという命令だ", "こいつに評決を言い渡せください", "こいつに評決を言い渡せべし",
    "こいつに評決を言い渡せが最善だ", "こいつに刑を宣告しろんだよ", "こいつに刑を宣告しろわ", "こいつに刑を宣告しろということだ",
    "こいつに刑を宣告しろくれ", "こいつに刑を宣告しろたまえ", "こいつに刑を宣告しろが正解だ", "こいつに刑を言い渡せ",
    "こいつに刑を言い渡せぜ", "こいつに刑を言い渡せと命じる", "こいつに刑を言い渡せとせよ", "こいつに刑を言い渡せなさい",
    "こいつに刑を言い渡せものだ", "こいつに刑を言い渡せが当然だ", "こいつに刑を科せんだぞ", "こいつに刑を科せな",
    "こいつに刑を科せという決定だ", "こいつに刑を科せくれよ", "こいつに刑を科せべきだ", "こいつに刑を科せが順当だ",
    "こいつに刑に処せんだ", "こいつに刑に処せよ", "こいつに刑に処せと決めた", "こいつに刑に処せとせよと言うんだ",
    "こいつに刑に処せたもれ", "こいつに刑に処せが筋だ", "こいつに刑に処せが仕様だ", "こいつに刑を執行しろぞ",
    "こいつに刑を執行しろと言った", "こいつに刑を執行しろという命令だ", "こいつに刑を執行しろください", "こいつに刑を執行しろべし",
    "こいつに刑を執行しろが最善だ", "こいつに刑罰を科せんだよ", "こいつに刑罰を科せわ", "こいつに刑罰を科せということだ",
    "こいつに刑罰を科せくれ", "こいつに刑罰を科せたまえ", "こいつに刑罰を科せが正解だ", "こいつに刑罰を与えろ",
    "こいつに刑罰を与えろぜ", "こいつに刑罰を与えろと命じる", "こいつに刑罰を与えろとせよ", "こいつに刑罰を与えろなさい",
    "こいつに刑罰を与えろものだ", "こいつに刑罰を与えろが当然だ", "こいつに処罰しろんだぞ", "こいつに処罰しろな",
    "こいつに処罰しろという決定だ", "こいつに処罰しろくれよ", "こいつに処罰しろべきだ", "こいつに処罰しろが順当だ",
    "こいつに処罰せよんだ", "こいつに処罰せよよ", "こいつに処罰せよと決めた", "こいつに処罰せよとせよと言うんだ",
    "こいつに処罰せよたもれ", "こいつに処罰せよが筋だ", "こいつに処罰せよが仕様だ", "こいつに処罰だぞ",
    "こいつに処罰だと言った", "こいつに処罰だという命令だ", "こいつに処罰だください", "こいつに処罰だべし",
    "こいつに処罰だが最善だ", "こいつに処断しろんだよ", "こいつに処断しろわ", "こいつに処断しろということだ",
    "こいつに処断しろくれ", "こいつに処断しろたまえ", "こいつに処断しろが正解だ", "こいつに処断せよ",
    "こいつに処断せよぜ", "こいつに処断せよと命じる", "こいつに処断せよとせよ", "こいつに処断せよなさい",
    "こいつに処断せよものだ", "こいつに処断せよが当然だ", "こいつに処断だんだぞ", "こいつに処断だな",
    "こいつに処断だという決定だ", "こいつに処断だくれよ", "こいつに処断だべきだ", "こいつに処断だが順当だ",
    "こいつに成敗を加えろんだ", "こいつに成敗を加えろよ", "こいつに成敗を加えろと決めた", "こいつに成敗を加えろとせよと言うんだ",
    "こいつに成敗を加えろたもれ", "こいつに成敗を加えろが筋だ", "こいつに成敗を加えろが仕様だ", "こいつに成敗を下せぞ",
    "こいつに成敗を下せと言った", "こいつに成敗を下せという命令だ", "こいつに成敗を下せください", "こいつに成敗を下せべし",
    "こいつに成敗を下せが最善だ", "こいつにお仕置きしろんだよ", "こいつにお仕置きしろわ", "こいつにお仕置きしろということだ",
    "こいつにお仕置きしろくれ", "こいつにお仕置きしろたまえ", "こいつにお仕置きしろが正解だ", "こいつにお仕置きだ",
    "こいつにお仕置きだぜ", "こいつにお仕置きだと命じる", "こいつにお仕置きだとせよ", "こいつにお仕置きだなさい",
    "こいつにお仕置きだものだ", "こいつにお仕置きだが当然だ", "こいつにお仕置きを執行しろんだぞ", "こいつにお仕置きを執行しろな",
    "こいつにお仕置きを執行しろという決定だ", "こいつにお仕置きを執行しろくれよ", "こいつにお仕置きを執行しろべきだ", "こいつにお仕置きを執行しろが順当だ",
    "こいつに報いを受けさせろんだ", "こいつに報いを受けさせろよ", "こいつに報いを受けさせろと決めた", "こいつに報いを受けさせろとせよと言うんだ",
    "こいつに報いを受けさせろたもれ", "こいつに報いを受けさせろが筋だ", "こいつに報いを受けさせろが仕様だ", "こいつに報いを与えろぞ",
    "こいつに報いを与えろと言った", "こいつに報いを与えろという命令だ", "こいつに報いを与えろください", "こいつに報いを与えろべし",
    "こいつに報いを与えろが最善だ", "こいつに報復しろんだよ", "こいつに報復しろわ", "こいつに報復しろということだ",
    "こいつに報復しろくれ", "こいつに報復しろたまえ", "こいつに報復しろが正解だ", "こいつに制裁を加えろ",
    "こいつに制裁を加えろぜ", "こいつに制裁を加えろと命じる", "こいつに制裁を加えろとせよ", "こいつに制裁を加えろなさい",
    "こいつに制裁を加えろものだ", "こいつに制裁を加えろが当然だ", "こいつに制裁を下せんだぞ", "こいつに制裁を下せな",
    "こいつに制裁を下せという決定だ", "こいつに制裁を下せくれよ", "こいつに制裁を下せべきだ", "こいつに制裁を下せが順当だ",
    "こいつに制裁を科せんだ", "こいつに制裁を科せよ", "こいつに制裁を科せと決めた", "こいつに制裁を科せとせよと言うんだ",
    "こいつに制裁を科せたもれ", "こいつに制裁を科せが筋だ", "こいつに制裁を科せが仕様だ", "こいつに制裁を執行しろぞ",
    "こいつに制裁を執行しろと言った", "こいつに制裁を執行しろという命令だ", "こいつに制裁を執行しろください", "こいつに制裁を執行しろべし",
    "こいつに制裁を執行しろが最善だ", "こいつに罰を与えろんだよ", "こいつに罰を与えろわ", "こいつに罰を与えろということだ",
    "こいつに罰を与えろくれ", "こいつをなかったことにしろ", "こいつはなかったことにしろぞ", "それをなかったことにしろと言った",
    "こいつをなかったことにしろという命令だ", "こいつはなかったことにしろください", "それをなかったことにしろが筋だ", "こいつをなかったことにせよんだ",
    "こいつはなかったことにせよぜ", "それをなかったことにせよと命じる", "こいつをなかったことにせよとせよ", "こいつはなかったことにせよなさい",
    "それをなかったことにせよが正解だ", "こいつをなかったことにするんだよ", "こいつはなかったことにするよ", "それをなかったことにするということだ",
    "こいつをなかったことにするくれよ", "こいつはなかったことにするべし", "それをなかったことにするが仕様だ", "こいつをなかったことにしなさいぞ",
    "こいつはなかったことにしなさいな", "それをなかったことにしなさいという決定だ", "こいつをなかったことにしなさいください", "こいつはなかったことにしなさいものだ",
    "それをなかったことにしてくれ", "こいつをなかったことにしてくれぜ", "こいつはなかったことにしてくれと言った", "それをなかったことにしてくれという命令だ",
    "こいつをなかったことにしてくれなさい", "こいつはなかったことにしてくれが筋だ", "それをなかったことにしてほしいんだ", "こいつをなかったことにしてほしいよ",
    "こいつはなかったことにしてほしいと命じる", "それをなかったことにしてほしいとせよ", "こいつをなかったことにしてほしいべきだ", "こいつはなかったことにしてほしいが正解だ",
    "それを無かったことにしろんだよ", "こいつを無かったことにしろわ", "こいつは無かったことにしろと決めた", "それを無かったことにしろくれ",
    "こいつを無かったことにしろべし", "こいつは無かったことにしろが当然だ", "それを存在しなかったことにしろんだぞ", "こいつを存在しなかったことにしろな",
    "こいつは存在しなかったことにしろということだ", "それを存在しなかったことにしろくれよ", "こいつを存在しなかったことにしろものだ", "こいつは存在しなかったことにしろが仕様だ",
    "それを最初からなかったことにしろぞ", "こいつを最初からなかったことにしろと言った", "こいつは最初からなかったことにしろという決定だ", "それを最初からなかったことにしろください",
    "こいつを最初からなかったことにしろが筋だ", "こいつははじめからなかったことにしろ", "それをはじめからなかったことにしろぜ", "こいつをはじめからなかったことにしろと命じる",
    "こいつははじめからなかったことにしろという命令だ", "それをはじめからなかったことにしろなさい", "こいつをはじめからなかったことにしろが正解だ", "こいつは最初から存在しなかったことにしろんだ",
    "それを最初から存在しなかったことにしろよ", "こいつを最初から存在しなかったことにしろと決めた", "こいつは最初から存在しなかったことにしろとせよ", "それを最初から存在しなかったことにしろべきだ",
    "こいつを最初から存在しなかったことにしろが当然だ", "こいつは帳消しにしろんだよ", "それを帳消しにしろわ", "こいつを帳消しにしろということだ",
    "こいつは帳消しにしろくれ", "それを帳消しにしろべし", "こいつを帳消しにしろが仕様だ", "こいつは帳消しだんだぞ",
    "それを帳消しだな", "こいつを帳消しだという決定だ", "こいつは帳消しだくれよ", "それを帳消しだものだ",
    "こいつを帳消しにする", "こいつは帳消しにするぞ", "それを帳消しにすると命じる", "こいつを帳消しにするとせよ",
    "こいつは帳消しにするなさい", "それを帳消しにするが正解だ", "こいつを水に流せんだよ", "こいつは水に流せよ",
    "それを水に流せと決めた", "こいつを水に流せくれ", "こいつは水に流せべきだ", "それを水に流せが当然だ",
    "こいつを水に流すんだんだぞ", "こいつは水に流すんだわ", "それを水に流すんだということだ", "こいつを水に流すんだくれよ",
    "こいつは水に流すんだべし", "それを水に流すんだが仕様だ", "こいつを闇に葬れぞ", "こいつは闇に葬れな",
    "それを闇に葬れという決定だ", "こいつを闇に葬れください", "こいつは闇に葬れものだ", "それを闇に葬り去れ",
    "こいつを闇に葬り去れぜ", "こいつは闇に葬り去れと言った", "それを闇に葬り去れという命令だ", "こいつを闇に葬り去れなさい",
    "こいつは闇に葬り去れが筋だ", "それを闇に消えろんだ", "こいつを闇に消えろよ", "こいつを闇に消えろと決めた",
    "こいつは闇に消えるとせよ", "それを闇に消えろべきだ", "こいつを闇に消えろが当然だ", "こいつは歴史から消えるんだよ",
    "それを歴史から消えろわ", "それを歴史から消えろということだ", "こいつを歴史から消えろくれよ", "こいつは歴史から消えるべし",
    "それを歴史から消えろが仕様だ", "こいつを歴史から抹消しろぞ", "こいつは歴史から抹消しろな", "それを歴史から抹消しろという決定だ",
    "こいつを歴史から抹消しろください", "こいつは歴史から抹消しろものだ", "こいつを歴史に名を残すなんだ", "こいつは歴史に名を残さないと命じる",
    "それを歴史に名を残すなくれ", "こいつを歴史に名を残すなべし", "こいつは歴史に名を残さないが当然だ", "それを記録から消えろんだぞ",
    "こいつを記録から消えろな", "こいつを記録から消えろという決定だ", "こいつは記録から消えるくれよ", "それを記録から消えろものだ",
    "こいつを記録から抹消しろ", "こいつは記録から抹消しろぞ", "それを記録から抹消しろと言った", "こいつを記録から抹消しろという命令だ",
    "こいつは記録から抹消しろください", "それを記録から抹消しろが筋だ", "こいつを記録を抹消しろんだ", "こいつは記録を抹消しろぜ",
    "それを記録を抹消しろと命じる", "こいつを記録を抹消しろとせよ", "こいつは記録を抹消しろなさい", "それを記録を抹消しろが正解だ",
    "こいつを記録を消せんだよ", "こいつは記録を消せよ", "それを記録を消せと決めた", "こいつを記録を消せくれ",
    "こいつは記録を消せべきだ", "それを記録を消せが当然だ", "こいつを帳簿から消せんだぞ", "こいつは帳簿から消せわ",
    "それを帳簿から消せということだ", "こいつを帳簿から消せくれよ", "こいつは帳簿から消せべし", "それを帳簿から消せが仕様だ",
    "こいつを名簿から消せぞ", "こいつは名簿から消せな", "それを名簿から消せという決定だ", "こいつを名簿から消せください",
    "こいつは名簿から消せものだ", "それを名簿から外せ", "こいつを名簿から外せぜ", "こいつは名簿から外せと言った",
    "それを名簿から外せという命令だ", "こいつを名簿から外せなさい", "こいつは名簿から外せが筋だ", "それをリストから消せんだ",
    "こいつをリストから消せよ", "こいつはリストから消せと命じる", "それをリストから消せとせよ", "こいつをリストから消せべきだ",
    "こいつはリストから消せが正解だ", "それをリストから外せんだよ", "こいつをリストから外せわ", "こいつはリストから外せと決めた",
    "それをリストから外せくれ", "こいつをリストから外せべし", "こいつはリストから外せが当然だ", "それを台帳から消せんだぞ",
    "こいつを台帳から消せな", "こいつは台帳から消せということだ", "それを台帳から消せくれよ", "こいつを台帳から消せものだ",
    "こいつは台帳から消せが仕様だ", "それを戸籍から消せぞ", "こいつを戸籍から消せと言った", "こいつは戸籍から消せという決定だ",
    "それを戸籍から消せください", "こいつを戸籍から消せが筋だ", "こいつは記憶から消える", "それを記憶から消えろぜ",
    "それを記憶から消えろと命じる", "こいつを記憶から消えろとせよ", "こいつは記憶から消えるなさい", "それを記憶から消えろが正解だ",
    "こいつを記憶から消せんだよ", "こいつは記憶から消せよ", "それを記憶から消せと決めた", "こいつを記憶から消せくれ",
    "こいつは記憶から消せべきだ", "それを記憶から消せが当然だ", "こいつを記憶を消せんだぞ", "こいつは記憶を消せわ",
    "それを記憶を消せということだ", "こいつを記憶を消せくれよ", "こいつは記憶を消せべし", "それを記憶を消せが仕様だ",
    "こいつを思い出から消えろぞ", "こいつを思い出から消えろと言った", "こいつは思い出から消えるという決定だ", "それを思い出から消えろください",
    "こいつを思い出から消えろが筋だ", "こいつはこの世から消える", "それをこの世から消えろぜ", "それをこの世から消えろと命じる",
    "こいつをこの世から消えろとせよ", "こいつはこの世から消えるなさい", "それをこの世から消えろが正解だ", "こいつを世から消えろんだよ",
    "こいつは世から消えるよ", "こいつは世から消えると決めた", "それを世から消えろくれ", "こいつを世から消えろべし",
    "こいつは世から消えるが当然だ", "それを世界から消えろんだぞ", "こいつを世界から消えろな", "こいつを世界から消えろという決定だ",
    "こいつは世界から消えるくれよ", "それを世界から消えろものだ", "こいつを画面から消えろ", "こいつは画面から消えるぞ",
    "こいつは画面から消えると言った", "それを画面から消えろという命令だ", "こいつを画面から消えろなさい", "こいつは画面から消えるが筋だ",
    "それを視界から消えろんだ", "こいつを視界から消えろよ", "こいつを視界から消えろと決めた", "こいつは視界から消えるとせよ",
    "それを視界から消えろべきだ", "こいつを視界から消えろが当然だ", "こいつは目の前から消えるんだよ", "それを目の前から消えろわ",
    "それを目の前から消えろということだ", "こいつを目の前から消えろくれよ", "こいつは目の前から消えるべし", "それを目の前から消えろが仕様だ",
    "こいつを俺の前から消えろぞ", "こいつを俺の前から消えろと言った", "こいつは俺の前から消えるという決定だ", "それを俺の前から消えろください",
    "こいつを俺の前から消えろが筋だ", "こいつは俺の視界から消える", "それを俺の視界から消えろぜ", "それを俺の視界から消えろと命じる",
    "こいつを俺の視界から消えろとせよ", "こいつは俺の視界から消えるなさい", "それを俺の視界から消えろが正解だ", "こいつを存在を消せんだよ",
    "こいつは存在を消せよ", "それを存在を消せと決めた", "こいつを存在を消せくれ", "こいつは存在を消せべきだ",
    "それを存在を消せが当然だ", "こいつを存在を抹消しろんだぞ", "こいつは存在を抹消しろわ", "それを存在を抹消しろということだ",
    "こいつを存在を抹消しろくれよ", "こいつは存在を抹消しろべし", "それを存在を抹消しろが仕様だ", "こいつを痕跡を消せぞ",
    "こいつは痕跡を消せな", "それを痕跡を消せという決定だ", "こいつを痕跡を消せください", "こいつは痕跡を消せものだ",
    "こいつを痕跡を残すなんだ", "こいつは痕跡を残さないと命じる", "それを痕跡を残すなくれ", "こいつは痕跡を残さないべし",
    "それを痕跡を残すなが仕様だ", "こいつは形跡を残さないな", "それを形跡を残すなとせよ", "こいつは形跡を残さないべきだ",
    "それを形跡を残すなが当然だ", "こいつを証拠を消せんだぞ", "こいつは証拠を消せわ", "それを証拠を消せということだ",
    "こいつを証拠を消せくれよ", "こいつは証拠を消せべし", "それを証拠を消せが仕様だ", "こいつを証拠を隠滅しろぞ",
    "こいつは証拠を隠滅しろな", "それを証拠を隠滅しろという決定だ", "こいつを証拠を隠滅しろください", "こいつは証拠を隠滅しろものだ",
    "それを証拠隠滅しろ", "こいつを証拠隠滅しろぜ", "こいつは証拠隠滅しろと言った", "それを証拠隠滅しろという命令だ",
    "こいつを証拠隠滅しろなさい", "こいつは証拠隠滅しろが筋だ", "それを跡形もなく消えろんだ", "こいつを跡形もなく消えろよ",
    "こいつを跡形もなく消えろと決めた", "こいつは跡形もなく消えるとせよ", "それを跡形もなく消えろべきだ", "こいつを跡形もなく消えろが当然だ",
    "こいつは跡形も残さないんだぞ", "こいつを跡形も残すなという命令だ", "こいつは跡形も残さないください", "こいつを跡形も残すなが正解だ",
    "それを一欠片も残すなんだよ", "こいつを一欠片も残すなという決定だ", "こいつは一欠片も残さないくれよ", "こいつは一欠片も残さないものだ",
    "こいつを一片も残すなんだ", "こいつは一片も残さないと命じる", "それを一片も残すなくれ", "こいつは一片も残さないべし",
    "それを一片も残すなが仕様だ", "こいつは何も残さないな", "それを何も残すなとせよ", "こいつは何も残さないべきだ",
    "それを何も残すなが当然だ", "こいつは微塵も残さないぞ", "それを微塵も残すなという命令だ", "こいつを微塵も残すななさい",
    "それを微塵も残すなが正解だ", "こいつを跡を残すなんだぞ", "それを跡を残すなという決定だ",
          ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
