// pass DCCXXIII: certified professional (士業) licensing — scrivener / labor /
// patent / maritime agents + registry & IP filing ops -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXXIII: certified professional licensing (buccina)', () => {
  const closeTab = ['bar association admitted', 'scrivener licensed', 'labor attorney certified'];
  const closeTabJa = [
    '司法書士',
    '司法書士会',
    '日本司法書士会',
    '司法書士試験',
    '司法書士登録',
    '司法書士事務所',
    '司法書士法人',
    '認定司法書士',
    '簡裁訴訟代理',
    '登記業務',
    '登記申請',
    '商業登記',
    '会社設立登記',
    '役員変更登記',
    '本店移転登記',
    '支店登記',
    '抵当権設定登記',
    '抵当権抹消登記',
    '根抵当権',
    '所有権移転登記',
    '相続登記',
    '遺贈登記',
    '贈与登記',
    '買戻し登記',
    '仮登記',
    '予告登記',
    '登記識別情報',
    '登記事項証明書',
    '登記簿謄本',
    '閉鎖登記簿',
    '附属書類',
    '登記原因証明情報',
    '登記完了証',
    'オンライン登記申請',
    '登記情報提供',
    '成年後見登記',
    '後見登記',
    '供託',
    '供託書',
    '供託所',
    '仮差押',
    '仮処分',
    '督促手続',
    '少額訴訟',
    '調停申立',
    '本人訴訟支援',
    '裁判書類作成',
    '法律相談センター',
    '司法支援',
    '行政書士',
    '行政書士会',
    '日本行政書士会',
    '行政書士試験',
    '行政書士登録',
    '行政書士事務所',
    '行政書士法人',
    '許認可申請',
    '官公署提出書類',
    '建設業許可申請',
    '宅建業免許申請',
    '飲食店営業許可',
    '古物商許可',
    '産廃許可申請',
    '風俗営業許可申請',
    '旅館業許可申請',
    '運送業許可',
    '利用運送登録',
    '自動車登録',
    '車庫証明申請',
    '出店届',
    '契約書作成',
    '内容証明作成',
    '遺言書作成',
    '遺産分割協議書',
    '任意後見契約',
    '民事委任契約',
    '入管業務',
    '在留資格申請',
    '帰化申請',
    '永住許可申請',
    '就労資格証明',
    '経営管理ビザ',
    '技能実習監理',
    '特定活動申請',
    '外国人在留',
    '社会保険労務士',
    '社労士',
    '社労士会',
    '社会保険労務士試験',
    '社労士事務所',
    '開業届',
    '雇用保険届出',
    '社会保険手続',
    '労働保険手続',
    '労働保険料申告',
    '算定基礎届',
    '随時改定',
    '育休給付申請',
    '労災請求書',
    '就業規則作成',
    '36協定',
    '変形労働時間',
    '給与計算代行',
    '助成金申請',
    '両立支援助成金',
    'キャリアアップ助成金',
    '是正勧告対応',
    '労働基準監督署',
    '労働局',
    'ハローワーク届出',
    '求人票作成',
    '派遣届出',
    '弁理士',
    '弁理士会',
    '日本弁理士会',
    '弁理士試験',
    '弁理士登録',
    '特許事務所',
    '特許業務法人',
    '出願代理',
    '明細書作成',
    '審査請求書',
    '拒絶査定',
    '拒絶理由通知',
    '意見書提出',
    '手続補正書',
    '分割出願',
    '優先権主張',
    'pct出願',
    '国際出願',
    '移行手続',
    '特許料納付',
    '年金納付',
    '特許原簿',
    '審決取消訴訟',
    '無効審判',
    '訂正審判',
    '侵害警告',
    '鑑定書',
    '職務発明',
    '先行技術調査',
    '公知事実',
    '出願公開',
    '出願番号',
    '特許番号',
    '実用新案登録',
    '意匠登録',
    '商標出願',
    '商標調査',
    '称呼類似',
    '指定商品',
    '役務区分',
    '商標使用',
    '更新登録',
    '防護標章',
    '地域団体商標',
    '著作権相談',
    '著作権登録申請',
    'プログラム登録',
    '営業秘密管理',
    '知財戦略',
    '知財コンサル',
    '知財評価',
    '海事代理士',
    '海事代理士会',
    '海事代理士試験',
    '海事法令',
    '船舶登記',
    '船舶国籍証書',
    '船舶検査証書',
    '船舶保有者',
    '船員手続',
    '海技免状更新',
    '船舶安全法',
    '船舶職員法',
    '臨時国籍',
    '登録船舶',
    '船舶ローン',
    '船舶抵当',
    '新造船登記',
    '売買登記',
    '船舶抹消',
    '国土交通省海事',
    '運輸局船舶',
    '海運企業'
  ];
  const negate = [
    'still awaiting the patent license',
    'still awaiting the scrivener registration',
    'まだ出願前',
    'まだ登記申請前',
    'これから提出',
    'まだ審査請求前'
  ];
  const nullPins = ['about to visit the patent office', 'about to file the scrivener report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
