// Round 110: JA compound request frames (てもらう〜できますか / ということ /
// 方向で / 次第です / 意向報告II / 条件・譲歩 / 閉鎖名詞依頼), EN politeness
// nests (i was hoping / it would be great if / do me a favor / care to),
// EN disposal idioms (make it go away / want it gone), back/scroll idioms.
const VC = require('../src/vr/input/VoiceCommands').VoiceCommands;

function run(phrase) {
  const vc = new VC({ enabled: true });
  const tm = {
    activeTabId: 't1',
    tabs: [{ id: 't1', title: 'Example' }],
    closeTab() {},
    setActive() {},
    closeTabs() {},
    closeAllTabs() {},
    closeOtherTabs() {},
    goBack() {},
    goForward() {},
    reload() {},
    getActiveTab() { return { title: 'Example', url: 'https://example.com' }; },
  };
  vc.connectBrowser({ tabManager: tm, onGoTo: () => {} });
  vc.lastCommand = null;
  vc.processCommand(phrase, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : 'NONE';
}

const cases = [
  // === JA desire+intent reports → close-tab ===
  ['閉じたいと思います', 'close-tab'],
  ['閉じたいと思ってます', 'close-tab'],
  ['閉じたいんですが', 'close-tab'],
  ['閉じようと考えて', 'close-tab'],
  ['閉じようと思っています', 'close-tab'],
  ['閉じようかと思って', 'close-tab'],
  ['閉じようかと考えて', 'close-tab'],
  ['閉じた方がいいと思う', 'close-tab'],
  ['閉じるしかないんです', 'close-tab'],
  ['閉じるしかありません', 'close-tab'],
  ['閉じるしかないのでは', 'close-tab'],
  ['閉じざるを得ないです', 'close-tab'],
  // === JA dict+noun tails → close-tab ===
  ['閉じるということです', 'close-tab'],
  ['閉じるということで', 'close-tab'],
  ['閉じるというわけです', 'close-tab'],
  ['閉じるということですね', 'close-tab'],
  ['閉じる方向で', 'close-tab'],
  ['閉じる方向性で', 'close-tab'],
  ['閉じる感じで', 'close-tab'],
  ['閉じる形で', 'close-tab'],
  ['閉じる次第です', 'close-tab'],
  ['閉じる予定です', 'close-tab'],
  // === JA conditional/concessive frames → close-tab ===
  ['閉じればよろしい', 'close-tab'],
  ['閉じればよいのですが', 'close-tab'],
  ['閉じるなら早く', 'close-tab'],
  ['閉じるなら今のうち', 'close-tab'],
  ['閉じてもいいのであれば', 'close-tab'],
  ['閉じるのであれば', 'close-tab'],
  ['閉じてもかまわないのであれば', 'close-tab'],
  ['閉じてしまってもよい', 'close-tab'],
  // === JA benefactive mega-tails → close-tab ===
  ['閉じてもらうことはできますか', 'close-tab'],
  ['閉じていただくことはできますか', 'close-tab'],
  ['閉じてくれませんかね', 'close-tab'],
  ['閉じてくださるでしょうか', 'close-tab'],
  ['閉じていただけないものでしょうか', 'close-tab'],
  ['閉じていただけたらと思います', 'close-tab'],
  ['閉じていただければと思います', 'close-tab'],
  ['閉じてもらえたら嬉しい', 'close-tab'],
  ['閉じてもらえれば助かる', 'close-tab'],
  ['閉じてもらえるとありがたい', 'close-tab'],
  ['閉じてくれたら助かる', 'close-tab'],
  ['閉じてもらうと助かる', 'close-tab'],
  ['閉じてもらいました', 'close-tab'],
  ['閉じていただきました', 'close-tab'],
  ['閉じてくれればと', 'close-tab'],
  ['閉じてもらえたらなあ', 'close-tab'],
  ['閉じてくださるとありがたいです', 'close-tab'],
  ['閉じてもらいたいんです', 'close-tab'],
  ['閉じてもらえると', 'close-tab'],
  ['閉じていただけると', 'close-tab'],
  ['閉じていただければ幸いに存じます', 'close-tab'],
  ['閉じてもらえると助かります', 'close-tab'],
  ['閉じていただけますと大変助かります', 'close-tab'],
  // === JA 閉鎖/削除/リセット noun requests ===
  ['閉鎖してください', 'close-tab'],
  ['閉鎖お願いします', 'close-tab'],
  ['閉鎖をお願いします', 'close-tab'],
  ['閉鎖を願います', 'close-tab'],
  ['閉鎖希望です', 'close-tab'],
  ['閉鎖してくれ', 'close-tab'],
  ['タブ閉鎖して', 'close-tab'],
  ['タブを閉鎖して', 'close-tab'],
  ['消去してください', 'close-tab'],
  ['削除してください', 'close-tab'],
  ['削除お願いします', 'close-tab'],
  ['削除をお願いします', 'close-tab'],
  ['リセットしてください', 'settings-reset'],
  ['リセットお願いします', 'settings-reset'],
  ['クリアしてください', 'clear-history'],
  ['クリアをお願いします', 'clear-history'],
  ['クリアしてくださいね', 'clear-history'],
  // === JA repeat/reread → read-aloud / redo ===
  ['もう一度読んで', 'read-aloud'],
  ['も一回読んで', 'read-aloud'],
  ['再び読んで', 'read-aloud'],
  ['再度読んで', 'read-aloud'],
  ['もう一回読み直して', 'read-aloud'],
  ['読み直してほしい', 'read-aloud'],
  ['最初からやり直して', 'redo'],
  // === JA back idioms ===
  ['後戻りして', 'back'],
  ['逆戻りして', 'back'],
  ['前のページに戻る', 'back'],
  ['ひとつ前に戻って', 'back'],
  ['前のに戻って', 'back'],
  ['元に戻って', 'reopen-tab'],
  ['もとに戻して', 'reopen-tab'],
  ['元に戻してください', 'reopen-tab'],
  ['前に引き返して', 'back'],
  ['来た道を戻って', 'back'],
  ['さかのぼって', 'back'],
  // === JA scroll-down idioms ===
  ['スクロールをお願い', 'scroll-down'],
  ['下の方にスクロール', 'scroll-down'],
  ['下のほうまで', 'scroll-down'],
  ['ページを下げて', 'scroll-down'],
  ['画面を下げて', 'scroll-down'],
  ['もうちょっと下に', 'scroll-down'],
  ['もう少しだけ下に', 'scroll-down'],
  // === JA read-from-start / progress queries ===
  ['読み始めから', 'read-aloud'],
  ['先頭から読んで', 'read-aloud'],
  ['最初の行から読んで', 'read-aloud'],
  ['冒頭から読んで', 'read-aloud'],
  ['一行目から読んで', 'reader-goto-line'],
  ['今何枚目', 'reader-progress'],
  ['今何ページ目', 'reader-progress'],
  ['あと何ページ', 'reader-progress'],
  ['あとどのくらい', 'remaining-time'],
  ['全体の何割', 'reader-progress'],
  ['どのくらい読んだ', 'reader-progress'],
  ['どこまでいった', 'reader-progress'],
  ['進み具合は', 'reader-progress'],
  ['進捗は', 'reader-progress'],
  // === JA read directives ===
  ['読み聞かせてくれ', 'read-aloud'],
  ['読み上げてもらえますか', 'read-aloud'],
  ['音読してください', 'read-aloud'],
  ['朗読して', 'read-aloud'],
  ['朗読をお願い', 'read-aloud'],
  ['声で読んで', 'read-aloud'],
  ['音声で読んで', 'read-aloud'],
  ['読み上げを続けて', 'resume-reading'],
  // === EN politeness nests → close-tab ===
  ['be kind enough to close it', 'close-tab'],
  ['i was hoping youd close it', 'close-tab'],
  ['i was hoping you would close it', 'close-tab'],
  ['it would be great if you could close it', 'close-tab'],
  ['id appreciate if you closed it', 'close-tab'],
  ['i would be grateful if you could close it', 'close-tab'],
  ['would you do me a favor and close it', 'close-tab'],
  ['do me the favor of closing it', 'close-tab'],
  ['could you do me a favor and close it', 'close-tab'],
  ['if you could close it that would be great', 'close-tab'],
  ['if you could just close it', 'close-tab'],
  ['you might want to close it', 'close-tab'],
  ['you may want to close it', 'close-tab'],
  ['you probably want to close it', 'close-tab'],
  ['what if you closed it', 'close-tab'],
  ['suppose you closed it', 'close-tab'],
  ['how about closing it for me', 'close-tab'],
  ['would you care to close it', 'close-tab'],
  // === EN disposal idioms → close-tab ===
  ['make sure it is closed', 'close-tab'],
  ['see to it that it gets closed', 'close-tab'],
  ['make it go away', 'close-tab'],
  ['make it disappear', 'close-tab'],
  ['make it vanish', 'close-tab'],
  ['have it gone', 'close-tab'],
  ['want it gone', 'close-tab'],
  ['need it gone', 'close-tab'],
  ['want it out of here', 'close-tab'],
  // === EN continuation/completion ===
  ['get on with it', 'resume-reading'],
  ['get it over with', 'stop-everything'],
  ['finish reading it', 'read-aloud'],
  ['finish it up', 'stop-everything'],
  ['wrap up reading', 'stop-reading'],
  ['keep on reading for me', 'resume-reading'],
  ['go on reading', 'resume-reading'],
  ['carry on reading', 'resume-reading'],
  ['read on please', 'resume-reading'],
  // === coexistence: earlier owners must keep their phrases ===
  ['閉じてください', 'close-tab'],
  ['閉じて', 'close-tab'],
  ['読んで', 'read-aloud'],
  ['戻って', 'back'],
  ['close it', 'close-tab'],
  ['go back', 'back'],
  ['read it', 'read-aloud'],
  ['first tab', 'first-tab'],
  ['last tab', 'last-tab'],
  ['tab 3', 'tab-select'],
  ['もう読まない', 'stop-reading'],
  ['i want my money back', 'NONE'],
  ['閉じてほしい', 'close-tab'],
  ['閉じていただけますか', 'close-tab'],
];

describe('Round 110: compound-request atoms', () => {
  test.each(cases)('%s → %s', (phrase, key) => {
    expect(run(phrase)).toBe(key);
  });
});
