// Round 112: conditional-request atoms — JA 条件/許可・緩い接続尾 + て受益残置IV +
// EN 譲歩前置詞・want-me-to 枠・just-have-to 枠・名誉表現 + find/go 誤ルート修正。
// Failing-first: every expectation below was probed NO-MATCH (or misroute) before impl.
const { VoiceCommands } = require('../src/vr/input/VoiceCommands');

describe('conditional-request atoms (round 112)', () => {
  let vc, tm;
  const mkTab = (id, title) => ({ id, title, url: `https://${id}.example.com` });
  beforeEach(() => {
    tm = {
      activeTabId: 't1',
      tabs: [mkTab('t1', 'Example')],
      closeTab() {}, setActive() {}, closeTabs() {}, closeAllTabs() {},
      closeOtherTabs() {}, goBack() {}, goForward() {}, reload() {},
      getActiveTab() { return { title: 'Example', url: 'https://example.com' }; },
    };
    vc = new VoiceCommands({ enabled: true });
    vc.connectBrowser({ tabManager: tm, onGoTo: () => {} });
  });
  const run = (p) => { vc.lastCommand = null; vc.processCommand(p, 0.9); return vc.lastCommand ? vc.lastCommand.key : 'NONE'; };

  // --- JA: て + 受益残置IV ---
  test.each([
    ['閉じてくれますれば', 'close-tab'],
    ['閉じてくれれば幸い', 'close-tab'],
    ['閉じてくれれば助かります', 'close-tab'],
    ['閉じてくれれば嬉しい', 'close-tab'],
    ['閉じてくれれば助かるんだ', 'close-tab'],
    ['戻ってくれれば幸い', 'back'],
    ['読んでくれれば助かります', 'read-aloud'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));

  // --- JA: dict + 条件枠 ---
  test.each([
    ['閉じるならいい', 'close-tab'],
    ['閉じるなら早い', 'close-tab'],
    ['閉じるならば', 'close-tab'],
    ['閉じるのであれば早く', 'close-tab'],
    ['閉じるのなら早く', 'close-tab'],
    ['閉じるなら今のうちに', 'close-tab'],
    ['閉じるならいいんだけど', 'close-tab'],
    ['閉じるのでいい', 'close-tab'],
    ['閉じるのでよい', 'close-tab'],
    ['閉じるのでしたら', 'close-tab'],
    ['閉じるのであればよろしい', 'close-tab'],
    ['閉じるのであれば大丈夫', 'close-tab'],
    ['閉じるならばよろしい', 'close-tab'],
    ['閉じるならば結構です', 'close-tab'],
    ['閉じるので結構です', 'close-tab'],
    ['閉じるというのであれば', 'close-tab'],
    ['閉じるということであれば', 'close-tab'],
    ['閉じるのならいい', 'close-tab'],
    ['閉じることならいい', 'close-tab'],
    ['閉じることならできる', 'close-tab'],
    ['戻るならいい', 'back'],
    ['読むのであれば', 'read-aloud'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));

  // --- JA: て + 許可質問 ---
  test.each([
    ['閉じてよいか', 'close-tab'],
    ['閉じていいか', 'close-tab'],
    ['閉じてもいいか', 'close-tab'],
    ['閉じてもよいか', 'close-tab'],
    ['閉じていいのか', 'close-tab'],
    ['閉じていいんでしょうか', 'close-tab'],
    ['閉じていいのでしょうか', 'close-tab'],
    ['閉じていいんですか', 'close-tab'],
    ['閉じていいですか', 'close-tab'],
    ['閉じていいのでは', 'close-tab'],
    ['閉じていいものか', 'close-tab'],
    ['閉じていいものですか', 'close-tab'],
    ['閉じてよろしいか', 'close-tab'],
    ['閉じてよろしいですか', 'close-tab'],
    ['閉じてよろしいんでしょうか', 'close-tab'],
    ['閉じていいわけですね', 'close-tab'],
    ['閉じていいんですよね', 'close-tab'],
    ['閉じていいですよね', 'close-tab'],
    ['閉じていいんだね', 'close-tab'],
    ['閉じていいかしら', 'close-tab'],
    ['閉じていいかなと', 'close-tab'],
    ['閉じていいかと', 'close-tab'],
    ['戻っていいか', 'back'],
    ['読んでよろしいか', 'read-aloud'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));

  // --- JA: dict + 緩い接続 (とか/なんか/くらい/だけ/さえ/でも) ---
  test.each([
    ['閉じるとかいう', 'close-tab'],
    ['閉じるとか言って', 'close-tab'],
    ['閉じるとかで', 'close-tab'],
    ['閉じるとかして', 'close-tab'],
    ['閉じるとかね', 'close-tab'],
    ['閉じるとかよ', 'close-tab'],
    ['閉じるなんかして', 'close-tab'],
    ['閉じるなんかで', 'close-tab'],
    ['閉じるくらいなら', 'close-tab'],
    ['閉じるくらいで', 'close-tab'],
    ['閉じるくらいして', 'close-tab'],
    ['閉じるぐらいなら', 'close-tab'],
    ['閉じる程度で', 'close-tab'],
    ['閉じるほどで', 'close-tab'],
    ['閉じるだけなら', 'close-tab'],
    ['閉じるだけでいい', 'close-tab'],
    ['閉じるだけならいい', 'close-tab'],
    ['閉じるだけのこと', 'close-tab'],
    ['閉じるだけの話', 'close-tab'],
    ['閉じるだけなんだけど', 'close-tab'],
    ['閉じるだけなんです', 'close-tab'],
    ['閉じるだけなのに', 'close-tab'],
    ['閉じるさえすれば', 'close-tab'],
    ['閉じるすらすれば', 'close-tab'],
    ['閉じるでもいい', 'close-tab'],
    ['閉じるでもして', 'close-tab'],
    ['閉じるでもすれば', 'close-tab'],
    ['閉じるか何かして', 'close-tab'],
    ['閉じるかなんかして', 'close-tab'],
    ['閉じるとかなんとかして', 'close-tab'],
    ['戻るだけでいい', 'back'],
    ['読むくらいして', 'read-aloud'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));

  // --- EN: concessive/conditional prefixes ---
  test.each([
    ['the tab if you would close it', 'close-tab'],
    ['if youd just close it', 'close-tab'],
    ['if you would just close it', 'close-tab'],
    ['if you would be so kind as to close it', 'close-tab'],
    ['if you would be kind enough to close it', 'close-tab'],
    ['if you could be so kind as to close it', 'close-tab'],
    ['if it is not too much trouble could you close it', 'close-tab'],
    ['if its not too much to ask close it', 'close-tab'],
    ['if it isnt too much trouble close it', 'close-tab'],
    ['if it wouldnt be too much trouble close it', 'close-tab'],
    ['if you wouldnt mind terribly close it', 'close-tab'],
    ['if you wouldnt mind awfully close it', 'close-tab'],
    ['if you wouldnt mind at all close it', 'close-tab'],
    ['unless you object close it', 'close-tab'],
    ['unless you mind close it', 'close-tab'],
    ['barring objection close it', 'close-tab'],
    ['subject to your approval close it', 'close-tab'],
    ['with your permission close it', 'close-tab'],
    ['by your leave close it', 'close-tab'],
    ['if you will permit close it', 'close-tab'],
    ['permit me to close it', 'close-tab'],
    ['allow me to close it', 'close-tab'],
    ['let me close it for you', 'close-tab'],
    ['may i close it for you', 'close-tab'],
    ['want me to close it', 'close-tab'],
    ['want me to go ahead and close it', 'close-tab'],
    ['need me to close it', 'close-tab'],
    ['would you like me to close it', 'close-tab'],
    ['would you like for me to close it', 'close-tab'],
    ['do you want me to close it', 'close-tab'],
    ['do you need me to close it', 'close-tab'],
    ['did you want me to close it', 'close-tab'],
    ['did you need me to close it', 'close-tab'],
    ['you want me to close it', 'close-tab'],
    ['you need me to close it', 'close-tab'],
    ['tell me to close it', 'close-tab'],
    ['just tell me to close it', 'close-tab'],
    ['say the word and close it', 'close-tab'],
    ['say the word to close it', 'close-tab'],
    ['give the word to close it', 'close-tab'],
    ['if you want me to close it', 'close-tab'],
    ['whenever you want close it', 'close-tab'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));

  // --- EN: have-to / honor / try frames ---
  test.each([
    ['all you have to do is close it', 'close-tab'],
    ['all you gotta do is close it', 'close-tab'],
    ['all you need to do is close it', 'close-tab'],
    ['all you have to do is go back', 'back'],
    ['all you need to do is read it', 'read-aloud'],
    ['you only have to close it', 'close-tab'],
    ['you only need to close it', 'close-tab'],
    ['you just have to close it', 'close-tab'],
    ['you just need to close it', 'close-tab'],
    ['you have only to close it', 'close-tab'],
    ['you need only close it', 'close-tab'],
    ['you need only to close it', 'close-tab'],
    ['all it takes is to close it', 'close-tab'],
    ['all it takes is closing it', 'close-tab'],
    ['it takes only closing it', 'close-tab'],
    ['just do the closing', 'close-tab'],
    ['just do the honors and close it', 'close-tab'],
    ['do the honors and close it', 'close-tab'],
    ['have the honor of closing it', 'close-tab'],
    ['be honored to close it', 'close-tab'],
    ['be so honored as to close it', 'close-tab'],
    ['have the pleasure of closing it', 'close-tab'],
    ['take a stab at closing it', 'close-tab'],
    ['take a crack at closing it', 'close-tab'],
    ['take a shot at closing it', 'close-tab'],
    ['take a whack at closing it', 'close-tab'],
    ['give closing it a shot', 'close-tab'],
    ['give it a go closing it', 'close-tab'],
    ['give closing it a try', 'close-tab'],
    ['try your hand at closing it', 'close-tab'],
    ['try closing it for once', 'close-tab'],
    ['go ahead with closing it', 'close-tab'],
    ['proceed with closing it', 'close-tab'],
    ['proceed to close it', 'close-tab'],
    ['go forth and close it', 'close-tab'],
    ['venture to close it', 'close-tab'],
    ['dare to close it', 'close-tab'],
    ['trouble yourself to close it', 'close-tab'],
    ['bother to close it', 'close-tab'],
    ['bother closing it', 'close-tab'],
    ['deign to close it', 'close-tab'],
    ['condescend to close it', 'close-tab'],
    ['vouchsafe to close it', 'close-tab'],
    ['see fit to close it', 'close-tab'],
    ['see fit and close it', 'close-tab'],
    ['think fit to close it', 'close-tab'],
    ['find it in yourself to close it', 'close-tab'],
    ['find it in your heart to close it', 'close-tab'],
    ['have the goodness to close it', 'close-tab'],
    ['have the kindness to close it', 'close-tab'],
    ['do us the kindness of closing it', 'close-tab'],
    ['do us the favor of closing it', 'close-tab'],
    ['oblige me by closing it', 'close-tab'],
    ['indulge me and close it', 'close-tab'],
    ['humor me and close it', 'close-tab'],
    ['bear with me and close it', 'close-tab'],
    ['bear with it and close it', 'close-tab'],
    ['put up with it and close it', 'close-tab'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));

  // --- coexistence / regression guards ---
  test.each([
    ['close it', 'close-tab'],
    ['戻って', 'back'],
    ['読んで', 'read-aloud'],
    ['shall i close it', 'help'],
    ['should i close it', 'help'],
    ['do you think you could close it', 'close-tab'],
    ['it would help a lot', 'scoped-help'],
    ['first tab', 'first-tab'],
    ['find in page cats', 'find-in-page'],
  ])('%s → %s', (p, key) => expect(run(p)).toBe(key));
});
