// Pass CCLIV: EN rejection/contempt declaratives + JA erase/chase/verdict-pronounce (pass CCLIV)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLIV: close-tab coverage', () => {
  test.each([
    "reject it", "spurn it", "scorn it", "despise it",
    "detest it", "loathe it", "abhor it", "execrate it",
    "abominate it", "contemn it", "disdain it", "decline it",
    "deny it", "disallow it", "disapprove it", "object it",
    "oppose it", "dispute it", "contest it", "dispute it",
    "reject the tab", "spurn the tab", "scorn the tab", "despise the tab",
    "loathe the tab", "decline the tab", "deny the tab", "disallow the tab",
    "disapprove the tab", "object to the tab", "oppose the tab", "i reject it",
    "i reject the tab", "i repudiate it", "i repudiate the tab", "i spurn it",
    "i spurn the tab", "i scorn it", "i scorn the tab", "i despise it",
    "i despise the tab", "i detest it", "i detest the tab", "i loathe it",
    "i loathe the tab", "i abhor it", "i abhor the tab", "i disdain it",
    "i disdain the tab", "i decline it", "i decline the tab", "i refuse it",
    "i refuse the tab", "i veto it", "i veto the tab", "i deny it",
    "i deny the tab", "i disallow it", "i disallow the tab", "i disapprove of it",
    "i disapprove of the tab", "i object to it", "i object to the tab", "i oppose it",
    "i oppose the tab", "i contest it", "i contest the tab", "it is rejected",
    "it is repudiated", "it is spurned", "it is scorned", "it is despised",
    "it is detested", "it is loathed", "it is abhorred", "it is declined",
    "it is refused", "it is vetoed", "it is denied", "it is disallowed",
    "it is disapproved", "it is opposed", "it is contested", "the tab is rejected",
    "the tab is repudiated", "the tab is spurned", "the tab is vetoed", "the tab is denied",
    "the tab is disallowed", "the tab is disapproved", "rejection approved", "veto approved",
    "objection sustained", "objection overruled it", "objection upheld", "the veto stands",
    "the rejection stands", "rejected forever", "vetoed forever", "denied forever",
    "disallowed forever", "declined forever", "refused forever", "rejected permanently",
    "vetoed permanently", "denied permanently", "rejected outright", "vetoed outright",
    "denied outright", "declined outright", "refused outright", "rejected completely",
    "vetoed completely", "denied completely", "it is trash", "it is garbage",
    "it is rubbish", "it is junk", "it is waste", "it is refuse",
    "it is debris", "it is detritus", "it is slop", "it is sludge",
    "it is sewage", "it is dregs", "it is scum", "it is filth",
    "it is grime", "it is muck", "it is mire", "it is slime",
    "it is crud", "it is crap", "it is shit", "it is trash forever",
    "it is garbage forever", "it is junk forever", "it is trash to me", "it is garbage to me",
    "it is junk to me", "it is trash anyway", "it is garbage anyway", "it is junk anyway",
    "it is trash regardless", "it is garbage regardless", "it is trash anyway you look at it", "it is garbage no matter what",
    "the tab is trash", "the tab is rubbish", "the tab is junk", "the tab is refuse",
    "the tab is debris", "the tab is detritus", "the tab is slop", "the tab is sludge",
    "the tab is sewage", "the tab is dregs", "the tab is scum", "the tab is filth",
    "the tab is grime", "the tab is muck", "the tab is mire", "the tab is slime",
    "the tab is crud", "the tab is crap", "the tab is shit", "the tab is trash anyway",
    "the tab is garbage anyway", "the tab is junk anyway", "the tab is worthless", "the tab is useless",
    "the tab is pointless", "the tab is hopeless", "the tab is worthless anyway", "the tab is useless anyway",
    "the tab is pointless anyway", "the tab is worthless to me", "the tab is useless to me", "the tab is worthless trash",
    "the tab is complete garbage", "the tab is complete trash", "the tab is utter garbage", "the tab is utter trash",
    "the tab is pure garbage", "the tab is pure trash", "the tab is nothing but trash", "the tab is nothing but garbage",
    "the tab is a waste of space", "the tab is a waste of time", "the tab is a waste of memory", "the tab is a waste of a slot",
    "the tab is taking up space", "the tab is just wasting space", "the tab is just clutter", "the tab is pure clutter",
    "the tab is nothing but clutter", "the tab is an eyesore", "the tab is a nuisance", "the tab is a pest",
    "the tab is a plague", "the tab is a plague on this browser", "the tab is a blight", "the tab is a blight on this browser",
    "the tab is a curse", "the tab is cursed", "the tab is damned", "the tab is doomed",
    "the tab is doomed anyway", "the tab is doomed regardless", "the tab is dead anyway", "the tab is dead either way",
    "the tab is a lost cause", "the tab is a lost cause anyway", "the tab is beyond saving", "the tab is beyond help",
    "the tab is beyond repair", "the tab is beyond redemption", "the tab is beyond hope", "the tab is unsalvageable",
    "the tab is unsavable", "the tab is irredeemable", "the tab is irreparable", "the tab is unfixable",
    "the tab is unfixable anyway", "the tab is broken beyond repair", "the tab is broken anyway", "the tab is rotten",
    "the tab is rotten to the core", "the tab is rotten anyway", "the tab is spoiled", "the tab is spoiled anyway",
    "the tab is tainted", "the tab is tainted goods", "the tab is damaged goods", "the tab is defective",
    "the tab is defective anyway", "the tab is a dud", "the tab is a lemon", "the tab is a bust",
    "the tab is a failure", "the tab is a failed experiment", "the tab is a mistake", "the tab was a mistake",
    "the tab was a bad idea", "the tab was a mistake anyway", "the tab was a mistake regardless", "the tab was a mistake all along",
    "the tab was doomed anyway", "the tab was garbage anyway", "the tab was trash anyway", "the tab was worthless anyway",
    "the tab was a waste anyway", "the tab was dead anyway", "the tab was done for anyway", "the tab was over anyway",
    "the tab was finished anyway", "the tab was through anyway", "the tab was history anyway", "the tab was toast anyway",
    "the tab was a goner anyway", "the tab was gone anyway", "the tab was going anyway", "the tab was on its way out anyway",
    "the tab was on the way out anyway", "the tab was expired anyway", "the tab was stale anyway", "the tab was moldy anyway",
    "the tab was rotten anyway", "the tab was rotten to the core anyway", "it was a bad idea", "it was a mistake anyway",
    "it was a bad idea anyway", "it was a waste of time", "it was a waste of space", "it was a waste anyway",
    "it was garbage anyway", "it was trash anyway", "it was doomed anyway", "it was done for anyway",
    "it was over anyway", "it was finished anyway", "it was through anyway", "it was history anyway",
    "it was toast anyway", "it was a goner anyway", "it was gone anyway", "it was going anyway",
    "it was expired anyway", "it was stale anyway", "it was moldy anyway", "it was rotten anyway",
    "it was a lost cause", "it was a lost cause anyway", "it was hopeless anyway", "it was pointless anyway",
    "it was worthless anyway", "it was useless anyway", "it was broken anyway", "it was damaged anyway",
    "it was defective anyway", "it was a dud anyway", "it was a lemon anyway", "it was a bust anyway",
    "it was a failure anyway", "it was a failed experiment anyway", "the tab was doomed from the start", "取り去れ",
    "取り去って", "取り去るんだ", "取り去りだ", "取り去りにしろ",
    "取り去れよ", "取り去るべきだ", "取り去るつもりだ", "取り去るわ",
    "取り去るぞ", "取り去るぜ", "取り去るからな", "ふき取れ",
    "ふき取って", "ふき取るんだ", "吹っ飛ばせ", "吹っ飛ばして",
    "吹っ飛ばすんだ", "吹っ飛べ", "打ち消せ", "打ち消して",
    "打ち消すんだ", "打ち消せよ", "打ち消すべきだ", "取り消せ",
    "取り消せよ", "取り消せと言ってんだ", "消し飛べ", "消し飛んでしまえ",
    "消し去れと言ったはずだ", "消し去るからな", "消し去るのが筋だ", "消し去るのが正解だ",
    "消し去ると言ったのに", "消し去ると言ったろ", "消し去ると言っただろ", "消し去るように言ったのに",
    "消し去るよう頼んだのに", "消し去るはずだった", "消し去るはずなのに", "消し去るはずだったのに",
    "消し去ってもらうぞ", "消し去ってもらうつもりだ", "消し去っていいだろ", "消し去っていいだろう",
    "消し去っていいと思うんだ", "消し去っちゃえ", "消し去っちゃったよ", "消し去った",
    "消し去ったよ", "消し去った方がいいよ", "消し去りたい", "消し去りたいんだよ",
    "消し去りたいです", "消し去りたいですよ", "消し去りたいのだ", "消し去りたいのだが",
    "消し去りたいだけど", "消し去りたかった", "消し去りたかったんだ", "消し去りたかったのに",
    "消し去るかも", "消し去るかもしれない", "消し去るかもね", "消し去るけどな",
    "消し去るけどね", "消し去るしな", "消し去るしよ", "消し去るしよう",
    "消し去るんだよな", "消し去るのかな", "消し去るのかなぁ", "消し去るのがいいよ",
    "消し去るのが正解だよ", "消し去るのが順当だ", "消し去るのが妥当だ", "消し去るのが筋だよ",
    "消し去るのが本懐だ", "消し去るのが上策だ", "消し去るのが最善だ", "消し去るのが勝ちだ",
    "消し去るのが正義だ", "消し去るのが仕様だ", "消し去るのが妥当だろ", "消し去るのは当然だ",
    "消し去るのは当然だろ", "消し去るのは当然です", "消し去るのは道理だ", "消し去るのは道理だろ",
    "消し去るのは道理です", "消し去るのは順当だ", "消し去るのは順当だろ", "消し去るのは順当です",
    "消し去るのは当たり前だ", "消し去るのは当たり前だろ", "消し去るのは当たり前です", "消し去るのは当然でしょ",
    "消し去るのは当然だって", "消し去るべき事案だ", "消し去るべき案件だ", "消し去るべき課題だ",
    "消し去るべきものだよ", "消し去るべきものでしょう", "消し去るべきものです", "消し去るべき案件です",
    "消し去るべき課題です", "消し去るべき対象だ", "消し去るべき対象だよ", "消し去るべき対象です",
    "消し去るべきタブだ", "消し去るべきタブだよ", "消し去るべきタブです", "消し去るべきページだ",
    "消し去るべきページです", "消し去る予定だよ", "消し去る計画だ", "消し去る計画だよ",
    "消し去る計画です", "消し去る構えだ", "消し去る構えだよ", "消し去る構えです",
    "消し去る手筈だ", "消し去る手筈です", "消し去る手はずだ", "消し去る手はずです",
    "消し去る算段だ", "消し去る算段です", "消し去る段取りだ", "消し去る段取りです",
    "消し去る手順だ", "消し去る手順です", "消し去る流れだ", "消し去る流れです",
    "消し去る運びだ", "消し去る運びです", "消し去る次第だ", "消し去る旨だ",
    "消し去る旨です", "消し去る意向だ", "消し去る意志だ", "消し去る意志です",
    "消し去る意思だ", "消し去る意思です", "消し去る腹だ", "消し去る腹です",
    "消し去る心だ", "消し去る心です", "消し去る方針だ", "消し去る方向だ",
    "消し去る方向です", "消し去る結論だ", "消し去る結論です", "消し去る判断だ",
    "消し去る判断です", "消し去る決定だ", "消し去る決定です", "消し去る決議だ",
    "消し去る決議です", "消し去る議決だ", "消し去る議決です", "消し去る採決だ",
    "消し去る採決です", "消し去る可決だ", "消し去る可決です", "消し去る裁定だ",
    "消し去る裁定です", "消し去る判決だ", "消し去る判決です", "消し去る命令だ",
    "消し去る命令です", "消し去る指令だ", "消し去る指令です", "消し去る布告だ",
    "消し去る布告です", "消し去る宣言だ", "消し去る宣言です", "消し去るお達しだ",
    "消し去るお達しです", "消し去る沙汰だ", "消し去る沙汰です", "消し去る由だ",
    "消し去る由です", "消し去る模様だ", "消し去る模様です", "消し去る件だ",
    "消し去る件です", "消し去る話だ", "消し去る話です", "消し去ることだ",
    "消し去ることです", "消し去るのだから", "消し去るのです", "消し去るんです",
    "見世物にしろ", "見世物だ", "見世物にして", "見世物にするんだ",
    "晒し者にして", "晒し者にするんだ", "晒し首にして", "獄門に晒せ",
    "獄門にして", "獄門にするんだ", "市松に晒せ", "市中に晒せ",
    "市中引き回しにして", "斬罪だ", "斬罪にしろ", "斬罪にして",
    "斬罪にするんだ", "不名誉除名だ", "不名誉だ", "不名誉にしろ",
    "不名誉な除名だ", "不名誉な終わりだ", "不名誉な最期だ", "不名誉な死だ",
    "不名誉な破門だ", "不名誉な追放だ", "不名誉な失脚だ", "不名誉な転落だ",
    "失脚させろ", "失脚だ", "失脚にしろ", "失脚させて",
    "失脚させちまえ", "失脚させちゃえ", "失脚させろや", "転落にしろ",
    "転落させちゃえ", "没落させろ", "没落だ", "没落にしろ",
    "没落させて", "没落させちまえ", "没落させちゃえ", "没落させろや",
    "没落させるべきだ", "転覆させろ", "転覆だ", "転覆にしろ",
    "転覆させて", "転覆させちまえ", "転覆させちゃえ", "転覆させろや",
    "転覆させるべきだ", "失墜にしろ", "失墜させて", "失墜させちまえ",
    "失墜させちゃえ", "失墜させろや", "失墜させるべきだ", "失墜させるつもりだ",
    "失墜させるわ", "失墜させるぞ", "失墜させるぜ", "失墜させるからな",
    "退場にしろ", "退場させて", "退場させちまえ", "退場させちゃえ",
    "退場させろや", "退場させるべきだ", "退場させるつもりだ", "退場させるわ",
    "退場させるぞ", "退場させるぜ", "退場させるからな", "退場処分だ",
    "退場処分にしろ", "退場命令だ", "退場命令にしろ", "退場を宣告する",
    "退場を宣告しろ", "退場宣告だ", "退場宣告にしろ", "退場言い渡しだ",
    "退場言い渡しにしろ", "退場を言い渡す", "退場を言い渡せ", "退場を言い渡して",
    "退場を言い渡すんだ", "退場を言い渡せよ", "退場を言い渡すべきだ", "退場を言い渡すつもりだ",
    "退場を言い渡すわ", "退場を言い渡すぞ", "退場を言い渡すぜ", "退場を言い渡すからな",
    "死刑宣告にしろ", "死刑を宣告しろ", "死刑を言い渡す", "死刑を言い渡せ",
    "死刑を言い渡して", "死刑を言い渡すんだ", "死刑を言い渡せよ", "死刑を言い渡すべきだ",
    "死刑を言い渡すつもりだ", "死刑を言い渡すわ", "死刑を言い渡すぞ", "死刑を言い渡すぜ",
    "死刑を言い渡すからな", "死刑判決だ", "死刑判決にしろ", "死刑判決を言い渡す",
    "死刑判決を言い渡せ", "死刑判決を言い渡して", "死刑判決を言い渡すんだ", "死刑判決を言い渡せよ",
    "死刑判決を言い渡すべきだ", "死刑判決を言い渡すつもりだ", "死刑判決を言い渡すわ", "死刑判決を言い渡すぞ",
    "死刑判決を言い渡すぜ", "死刑判決を言い渡すからな", "有罪宣告だ", "有罪宣告にしろ",
    "有罪を宣告する", "有罪を宣告しろ", "有罪を言い渡す", "有罪を言い渡せ",
    "有罪を言い渡して", "有罪を言い渡すんだ", "有罪を言い渡せよ", "有罪を言い渡すべきだ",
    "有罪を言い渡すつもりだ", "有罪を言い渡すわ", "有罪を言い渡すぞ", "有罪を言い渡すぜ",
    "有罪を言い渡すからな", "有罪判決にしろ", "有罪判決を言い渡す", "有罪判決を言い渡せ",
    "有罪判決を言い渡して", "有罪判決を言い渡すんだ", "有罪判決を言い渡せよ", "有罪判決を言い渡すべきだ",
    "有罪判決を言い渡すつもりだ", "有罪判決を言い渡すわ", "有罪判決を言い渡すぞ", "有罪判決を言い渡すぜ",
    "有罪判決を言い渡すからな", "有罪とする", "有罪とするんだ", "有罪とせよ",
    "有罪とせよと言うんだ", "有罪とせよと言う", "有罪とせよと言っている", "有罪とせよと言っているんだ",
    "有罪とせよと言っているのだ", "有罪とせよと言っているのです", "有罪とせよと言っているんだよ", "有罪とせよと言っているんだって",
    "有罪とせよと言ってんだ", "有罪とせよと言ってんだよ", "有罪とせよと言ってんだって", "有罪とせよと言っているわ",
    "有罪とせよと言っているぞ", "有罪とせよと言っているぜ", "有罪とせよと言っているからな", "有罪とせよというんだ",
    "有罪とせよというんだよ", "有罪とせよというのだ", "有罪とせよというのだよ", "有罪とせよということだ",
    "有罪とせよということだよ", "有罪とせよという件だ", "有罪とせよという件だよ", "有罪とせよという判断だ",
    "有罪とせよという判断だよ", "有罪とせよという決定だ", "有罪とせよという決定だよ", "有罪とせよという議決だ",
    "有罪とせよという議決だよ", "有罪とせよという採決だ", "有罪とせよという採決だよ", "有罪とせよという可決だ",
    "有罪とせよという可決だよ", "有罪とせよという裁定だ", "有罪とせよという裁定だよ", "有罪とせよという判決だ",
    "有罪とせよという判決だよ", "有罪とせよという命令だ", "有罪とせよという命令だよ", "有罪とせよという指令だ",
    "有罪とせよという指令だよ", "有罪とせよという布告だ", "有罪とせよという布告だよ", "有罪とせよという宣言だ",
    "有罪とせよという宣言だよ", "有罪とせよというお達しだ", "有罪とせよというお達しだよ", "有罪とせよという沙汰だ",
    "有罪とせよという沙汰だよ", "有罪とせよという由だ", "有罪とせよという由だよ", "有罪とせよという模様だ",
    "有罪とせよという模様だよ", "有罪とせよという意向だ", "有罪とせよという意向だよ", "有罪とせよという意志だ",
    "有罪とせよという意志だよ", "有罪とせよという意思だ", "有罪とせよという意思だよ", "有罪とせよという腹だ",
    "有罪とせよという腹だよ", "有罪とせよという心だ", "有罪とせよという心だよ", "有罪とせよという運びだ",
    "有罪とせよという運びだよ", "有罪とせよという段取りだ", "有罪とせよという段取りだよ", "有罪とせよという流れだ",
    "有罪とせよという流れだよ", "有罪とせよという次第だ", "有罪とせよという次第だよ", "有罪とせよという旨だ",
    "有罪とせよという旨だよ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
