// Pass CCLXIII: EN mercy-withheld + must-die declaratives + witness/evidence elimination + JA 一掃/根絶やし/処分宣告/封じ込め (pass CCLXIII)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXIII: close-tab coverage', () => {
  test.each([
    "show it no mercy", "show it no mercy once and for all", "show it no mercy no longer", "show no mercy to it forever",
    "show no mercy to it not ever", "show it no pity full stop", "show it no pity any more", "show it no quarter whatever",
    "show it no quarter anymore", "give it no mercy at all", "give it no mercy evermore", "give it no quarter now",
    "give it no quarter on this day", "grant it no mercy today", "grant it no mercy in this world", "grant it no mercy never again",
    "grant it no quarter for good", "grant it no quarter not at all", "offer it no mercy end of story", "offer it no mercy not once",
    "offer it no quarter period", "offer it no quarter any longer", "have no mercy on it whatsoever", "have no mercy on it forevermore",
    "have mercy on nothing ever", "have mercy on nothing henceforth", "no mercy for it tonight", "no mercy for it on this earth",
    "no mercy for the likes of it", "no mercy for the likes of it once and for all", "no mercy for the likes of it no longer", "no quarter for it forever",
    "no quarter for it not ever", "no quarter given full stop", "no quarter given any more", "no mercy given whatever",
    "no mercy given anymore", "no mercy shown at all", "no mercy shown evermore", "no mercy shall be shown now",
    "no mercy shall be shown on this day", "no mercy shall be given today", "no mercy shall be given in this world", "no mercy shall be given never again",
    "no mercy shall be granted for good", "no mercy shall be granted not at all", "no quarter shall be given end of story", "no quarter shall be given not once",
    "no quarter shall be granted period", "no quarter shall be granted any longer", "mercy is denied whatsoever", "mercy is denied forevermore",
    "mercy is denied to it ever", "mercy is denied to it henceforth", "mercy is not for it tonight", "mercy is not for it on this earth",
    "mercy is not for the likes of it", "mercy is not for the likes of it once and for all", "mercy is not for the likes of it no longer", "mercy is wasted on it forever",
    "mercy is wasted on it not ever", "mercy would be wasted on it full stop", "mercy would be wasted on it any more", "mercy is too good for it whatever",
    "mercy is too good for it anymore", "mercy is more than it deserves at all", "mercy is more than it deserves evermore", "pity is wasted on it now",
    "pity is wasted on it on this day", "pity is too good for it today", "pity is too good for it in this world", "pity is too good for it never again",
    "it deserves no mercy for good", "it deserves no mercy not at all", "it deserves no quarter end of story", "it deserves no quarter not once",
    "it merits no mercy period", "it merits no mercy any longer", "it merits no quarter whatsoever", "it merits no quarter forevermore",
    "it earns no mercy ever", "it earns no mercy henceforth", "it shall have no mercy tonight", "it shall have no mercy on this earth",
    "it shall have no quarter", "it shall have no quarter once and for all", "it shall have no quarter no longer", "it gets no mercy forever",
    "it gets no mercy not ever", "it gets no quarter full stop", "it gets no quarter any more", "it receives no mercy whatever",
    "it receives no mercy anymore", "it will be shown no mercy at all", "it will be shown no mercy evermore", "it will be given no quarter now",
    "it will be given no quarter on this day", "it will be granted no mercy today", "it will be granted no mercy in this world", "it will be granted no mercy never again",
    "it will be offered no quarter for good", "it will be offered no quarter not at all", "let it have no mercy end of story", "let it have no mercy not once",
    "let it beg for mercy period", "let it beg for mercy any longer", "let it beg for its life whatsoever", "let it beg for its life forevermore",
    "let it plead for mercy ever", "let it plead for mercy henceforth", "let it plead for its life tonight", "let it plead for its life on this earth",
    "make it beg for mercy", "make it beg for mercy once and for all", "make it beg for mercy no longer", "make it beg for its life forever",
    "make it beg for its life not ever", "make it plead for mercy full stop", "make it plead for mercy any more", "it will beg for mercy whatever",
    "it will beg for mercy anymore", "it will plead for mercy at all", "it will plead for mercy evermore", "it begs for mercy now",
    "it begs for mercy on this day", "it begs for its life today", "it begs for its life in this world", "it begs for its life never again",
    "deny it mercy for good", "deny it mercy not at all", "deny it quarter end of story", "deny it quarter not once",
    "deny it clemency period", "deny it clemency any longer", "deny it pardon whatsoever", "deny it pardon forevermore",
    "deny it reprieve ever", "deny it reprieve henceforth", "deny it absolution tonight", "deny it absolution on this earth",
    "deny it forgiveness", "deny it forgiveness once and for all", "deny it forgiveness no longer", "withhold mercy from it forever",
    "withhold mercy from it not ever", "withhold all mercy full stop", "withhold all mercy any more", "withhold clemency whatever",
    "withhold clemency anymore", "withhold pardon at all", "withhold pardon evermore", "spare it nothing now",
    "spare it nothing on this day", "spare it no suffering today", "spare it no suffering in this world", "spare it no suffering never again",
    "spare it no pain for good", "spare it no pain not at all", "spare no thought for it end of story", "spare no thought for it not once",
    "spare no pity for it period", "spare no pity for it any longer", "spare no mercy for it whatsoever", "spare no mercy for it forevermore",
    "waste no mercy on it ever", "waste no mercy on it henceforth", "waste no pity on it tonight", "waste no pity on it on this earth",
    "waste no tears on it", "waste no tears on it once and for all", "waste no tears on it no longer", "shed no tears for it forever",
    "shed no tears for it not ever", "shed not a tear full stop", "shed not a tear any more", "weep not for it whatever",
    "weep not for it anymore", "mourn it not at all", "mourn it not evermore", "mourn it never now",
    "mourn it never on this day", "grieve not for it today", "grieve not for it in this world", "grieve not for it never again",
    "lament it not for good", "lament it not not at all", "miss it not end of story", "miss it not not once",
    "miss it never period", "miss it never any longer", "remember it not whatsoever", "remember it not forevermore",
    "remember it never ever", "remember it never henceforth", "forget it entirely tonight", "forget it entirely on this earth",
    "forget it utterly", "forget it utterly once and for all", "forget it utterly no longer", "it must die for another minute",
    "it must die in my presence", "it must be destroyed now", "it must be destroyed a second longer", "it must be destroyed on this earth",
    "it must end for another moment", "it must end on my watch", "it must be ended any more", "it must be ended a moment longer",
    "it must be ended in this world", "it must go for another second", "it must go farther", "it must be gone any longer",
    "it must be gone for one more day", "it must be gone in my headset", "it must be erased ever again", "it must be erased further",
    "it must be erased forever anymore", "it must be erased forever for one more moment", "it must be erased forever in my browser", "it must be erased completely henceforth",
    "it must be erased completely any farther", "it must be removed", "it must be removed for one more second", "it must be removed on my screen",
    "it must be removed forever tonight", "it must be removed forever any further", "it must be removed forever under my roof", "it must be eliminated for another day",
    "it must be eliminated in my house", "it must be eliminated forever today", "it must be eliminated forever a day longer", "it must be eliminated forever under my watch",
    "it must be terminated for another minute", "it must be terminated in my presence", "it must be closed now", "it must be closed a second longer",
    "it must be closed on this earth", "it must be closed forever for another moment", "it must be closed forever on my watch", "it must be shut down any more",
    "it must be shut down a moment longer", "it must be shut down in this world", "it must be shut for good for another second", "it must be shut for good farther",
    "it must be killed any longer", "it must be killed for one more day", "it must be killed in my headset", "it must perish ever again",
    "it must perish further", "it must perish forever anymore", "it must perish forever for one more moment", "it must perish forever in my browser",
    "it must cease henceforth", "it must cease any farther", "it must cease to exist", "it must cease to exist for one more second",
    "it must cease to exist on my screen", "it must cease to be tonight", "it must cease to be any further", "it must cease to be under my roof",
    "it must cease existing for another day", "it must cease existing in my house", "it shall die today", "it shall die a day longer",
    "it shall die under my watch", "it shall be destroyed for another minute", "it shall be destroyed in my presence", "it shall end now",
    "it shall end a second longer", "it shall end on this earth", "it shall be ended for another moment", "it shall be ended on my watch",
    "it shall go any more", "it shall go a moment longer", "it shall go in this world", "it shall be gone for another second",
    "it shall be gone farther", "it shall perish any longer", "it shall perish for one more day", "it shall perish in my headset",
    "it shall cease to exist ever again", "it shall cease to exist further", "it shall cease to be anymore", "it shall cease to be for one more moment",
    "it shall cease to be in my browser", "it shall be no more for another day", "it shall be no more in my house", "it shall be nothing today",
    "it shall be nothing a day longer", "it shall be nothing under my watch", "it shall become nothing for another minute", "it shall become nothing in my presence",
    "it shall return to nothing now", "it shall return to nothing a second longer", "it shall return to nothing on this earth", "it shall return to dust for another moment",
    "it shall return to dust on my watch", "it shall return to the void any more", "it shall return to the void a moment longer", "it shall return to the void in this world",
    "it shall be undone for another second", "it shall be undone farther", "it shall be unmade any longer", "it shall be unmade for one more day",
    "it shall be unmade in my headset", "it shall be erased ever again", "it shall be erased further", "it shall be erased forever anymore",
    "it shall be erased forever for one more moment", "it shall be erased forever in my browser", "it will die henceforth", "it will die any farther",
    "it will be destroyed", "it will be destroyed for one more second", "it will be destroyed on my screen", "it will end tonight",
    "it will end any further", "it will end under my roof", "it will be ended for another day", "it will be ended in my house",
    "it will go today", "it will go a day longer", "it will go under my watch", "it will be gone for another minute",
    "it will be gone in my presence", "it will perish now", "it will perish a second longer", "it will perish on this earth",
    "it will cease to exist for another moment", "it will cease to exist on my watch", "it will cease to be any more", "it will cease to be a moment longer",
    "it will cease to be in this world", "it will be no more for another second", "it will be no more farther", "it will be nothing any longer",
    "it will be nothing for one more day", "it will be nothing in my headset", "it will become nothing ever again", "it will become nothing further",
    "it will return to nothing anymore", "it will return to nothing for one more moment", "it will return to nothing in my browser", "it will return to dust henceforth",
    "it will return to dust any farther", "it will return to the void", "it will return to the void for one more second", "it will return to the void on my screen",
    "it will be undone tonight", "it will be undone any further", "it will be undone under my roof", "it will be unmade for another day",
    "it will be unmade in my house", "it will be erased today", "it will be erased a day longer", "it will be erased under my watch",
    "it will be erased forever for another minute", "it will be erased forever in my presence", "it has to die now", "it has to die a second longer",
    "it has to die on this earth", "it has to be destroyed for another moment", "it has to be destroyed on my watch", "it has to end any more",
    "it has to end a moment longer", "it has to end in this world", "it has to be ended for another second", "it has to be ended farther",
    "it has to go any more", "it has to go any farther", "it has to be gone", "it has to be gone for one more second",
    "it has to be gone on my screen", "it has to perish tonight", "it has to perish any further", "it has to perish under my roof",
    "it has to cease for another day", "it has to cease in my house", "it has to cease to exist today", "it has to cease to exist a day longer",
    "it has to cease to exist under my watch", "it has to cease to be for another minute", "it has to cease to be in my presence", "it has to be no more now",
    "it has to be no more a second longer", "it has to be no more on this earth", "it needs to die for another moment", "it needs to die on my watch",
    "it needs to be destroyed any more", "it needs to be destroyed a moment longer", "it needs to be destroyed in this world", "it needs to end for another second",
    "it needs to end farther", "it needs to be ended any longer", "it needs to be ended for one more day", "it needs to be ended in my headset",
    "it needs to go for one more second", "it needs to go on my screen", "it needs to be gone tonight", "it needs to be gone any further",
    "it needs to be gone under my roof", "it needs to perish for another day", "it needs to perish in my house", "it needs to cease today",
    "it needs to cease a day longer", "it needs to cease under my watch", "it needs to cease to exist for another minute", "it needs to cease to exist in my presence",
    "it needs to be no more now", "it needs to be no more a second longer", "it needs to be no more on this earth", "it ought to die for another moment",
    "it ought to die on my watch", "it ought to be destroyed any more", "it ought to be destroyed a moment longer", "it ought to be destroyed in this world",
    "it ought to end for another second", "it ought to end farther", "it ought to be ended any longer", "it ought to be ended for one more day",
    "it ought to be ended in my headset", "it ought to go ever again", "it ought to go further", "it ought to be gone anymore",
    "it ought to be gone for one more moment", "it ought to be gone in my browser", "it ought to perish henceforth", "it ought to perish any farther",
    "it ought to cease", "it ought to cease for one more second", "it ought to cease on my screen", "it ought to be no more tonight",
    "it ought to be no more any further", "it ought to be no more under my roof", "it should die for another day", "it should die in my house",
    "it should be destroyed today", "it should be destroyed a day longer", "it should be destroyed under my watch", "it should end for another minute",
    "it should end in my presence", "it should be ended now", "it should be ended a second longer", "it should be ended on this earth",
    "it should go for another moment", "it should go on my watch", "it should be gone any more", "it should be gone a moment longer",
    "it should be gone in this world", "it should perish for another second", "it should perish farther", "it should cease any longer",
    "it should cease for one more day", "it should cease in my headset", "it should be no more ever again", "it should be no more further",
    "it should have died long ago anymore", "it should have died long ago for one more moment", "it should have died long ago in my browser", "it should never have existed for another day",
    "it should never have existed in my house", "it should never have been today", "it should never have been a day longer", "it should never have been under my watch",
    "it should never have been made for another minute", "it should never have been made in my presence", "it should never have been created now", "it should never have been created a second longer",
    "it should never have been created on this earth", "it should never have been born for another moment", "it should never have been born on my watch", "it should never have been opened any more",
    "it should never have been opened a moment longer", "it should never have been opened in this world", "it should never have been a thing for another second", "it should never have been a thing farther",
    "it never should have existed any more", "it never should have existed any farther", "it never should have been", "it never should have been for one more second",
    "it never should have been on my screen", "it never should have been made tonight", "it never should have been made any further", "it never should have been made under my roof",
    "it never should have been created for another day", "it never should have been created in my house", "it never should have been born today", "it never should have been born a day longer",
    "it never should have been born under my watch", "it never should have been opened for another minute", "it never should have been opened in my presence", "it never should have been a thing now",
    "it never should have been a thing a second longer", "it never should have been a thing on this earth", "it must not exist for another moment", "it must not exist on my watch",
    "it must not continue any more", "it must not continue a moment longer", "it must not continue in this world", "it must not go on for another second",
    "it must not go on farther", "it must not live any longer", "it must not live for one more day", "it must not live in my headset",
    "it must not remain ever again", "it must not remain further", "it must not stay anymore", "it must not stay for one more moment",
    "it must not stay in my browser", "it must not survive henceforth", "it must not survive any farther", "it shall not exist",
    "it shall not exist for one more second", "it shall not exist on my screen", "it shall not continue tonight", "it shall not continue any further",
    "it shall not continue under my roof", "it shall not live for another day", "it shall not live in my house", "it shall not remain today",
    "it shall not remain a day longer", "it shall not remain under my watch", "it shall not survive for another minute", "it shall not survive in my presence",
    "it shall not stand now", "it shall not stand a second longer", "it shall not stand on this earth", "it shall not pass for another moment",
    "it shall not pass on my watch", "it will not exist any more", "it will not exist a moment longer", "it will not exist in this world",
    "it will not continue for another second", "it will not continue farther", "it will not live any longer", "it will not live for one more day",
    "it will not live in my headset", "it will not remain ever again", "it will not remain further", "it will not survive anymore",
    "it will not survive for one more moment", "it will not survive in my browser", "it will not stand henceforth", "it will not stand any farther",
    "it cannot exist", "it cannot exist for one more second", "it cannot exist on my screen", "it cannot continue tonight",
    "it cannot continue any further", "it cannot continue under my roof", "it cannot go on for another day", "it cannot go on in my house",
    "it cannot live today", "it cannot live a day longer", "it cannot live under my watch", "it cannot remain for another minute",
    "it cannot remain in my presence", "it cannot stay now", "it cannot stay a second longer", "it cannot stay on this earth",
    "it cannot survive for another moment", "it cannot survive on my watch", "it cannot be allowed to exist any more", "it cannot be allowed to exist a moment longer",
    "it cannot be allowed to exist in this world", "it cannot be allowed to live for another second", "it cannot be allowed to live farther", "it cannot be allowed to continue any longer",
    "it cannot be allowed to continue for one more day", "it cannot be allowed to continue in my headset", "it cannot be allowed to remain ever again", "it cannot be allowed to remain further",
    "it cannot be allowed to survive anymore", "it cannot be allowed to survive for one more moment", "it cannot be allowed to survive in my browser", "it must not be allowed to exist henceforth",
    "it must not be allowed to exist any farther", "it must not be allowed to live", "it must not be allowed to live for one more second", "it must not be allowed to live on my screen",
    "it must not be allowed to continue tonight", "it must not be allowed to continue any further", "it must not be allowed to continue under my roof", "it must not be allowed to remain for another day",
    "it must not be allowed to remain in my house", "it must not be allowed to survive today", "it must not be allowed to survive a day longer", "it must not be allowed to survive under my watch",
    "it shall not be allowed to exist for another minute", "it shall not be allowed to exist in my presence", "it shall not be allowed to live now", "it shall not be allowed to live a second longer",
    "it shall not be allowed to live on this earth", "it shall not be allowed to continue for another moment", "it shall not be allowed to continue on my watch", "it shall not be allowed to remain any more",
    "it shall not be allowed to remain a moment longer", "it shall not be allowed to remain in this world", "it shall not be allowed to survive for another second", "it shall not be allowed to survive farther",
    "it will not be allowed to exist any longer", "it will not be allowed to exist for one more day", "it will not be allowed to exist in my headset", "it will not be allowed to live ever again",
    "it will not be allowed to live further", "it will not be allowed to continue anymore", "it will not be allowed to continue for one more moment", "it will not be allowed to continue in my browser",
    "it will not be allowed to remain henceforth", "it will not be allowed to remain any farther", "it will not be allowed to survive", "it will not be allowed to survive for one more second",
    "it will not be allowed to survive on my screen", "it should not be allowed to exist tonight", "it should not be allowed to exist any further", "it should not be allowed to exist under my roof",
    "it should not be allowed to live for another day", "it should not be allowed to live in my house", "it should not be allowed to continue today", "it should not be allowed to continue a day longer",
    "it should not be allowed to continue under my watch", "it should not be allowed to remain for another minute", "it should not be allowed to remain in my presence", "it should not be allowed to survive now",
    "it should not be allowed to survive a second longer", "it should not be allowed to survive on this earth", "it cannot be suffered to exist for another moment", "it cannot be suffered to exist on my watch",
    "it cannot be suffered to live any more", "it cannot be suffered to live a moment longer", "it cannot be suffered to live in this world", "it cannot be suffered to continue for another second",
    "it cannot be suffered to continue farther", "it cannot be suffered to remain any longer", "it cannot be suffered to remain for one more day", "it cannot be suffered to remain in my headset",
    "it cannot be suffered to survive ever again", "it cannot be suffered to survive further", "it cannot be permitted to exist anymore", "it cannot be permitted to exist for one more moment",
    "it cannot be permitted to exist in my browser", "it cannot be permitted to live henceforth", "it cannot be permitted to live any farther", "it cannot be permitted to continue",
    "it cannot be permitted to continue for one more second", "it cannot be permitted to continue on my screen", "it cannot be permitted to remain tonight", "it cannot be permitted to remain any further",
    "it cannot be permitted to remain under my roof", "it cannot be permitted to survive for another day", "it cannot be permitted to survive in my house", "it cannot be tolerated any longer today",
    "it cannot be tolerated any longer a day longer", "it cannot be tolerated any longer under my watch", "it cannot be tolerated anymore for another minute", "it cannot be tolerated anymore in my presence",
    "it can no longer be tolerated now", "it can no longer be tolerated a second longer", "it can no longer be tolerated on this earth", "it can no longer be suffered for another moment",
    "it can no longer be suffered on my watch", "it can no longer be allowed any more", "it can no longer be allowed a moment longer", "it can no longer be allowed in this world",
    "it can no longer be permitted for another second", "it can no longer be permitted farther", "it can no longer be borne any longer", "it can no longer be borne for one more day",
    "it can no longer be borne in my headset", "it can no longer be endured ever again", "it can no longer be endured further", "it can no longer be stood anymore",
    "it can no longer be stood for one more moment", "it can no longer be stood in my browser", "it can no longer be abided henceforth", "it can no longer be abided any farther",
    "it can no longer be stomached", "it can no longer be stomached for one more second", "it can no longer be stomached on my screen", "it can no longer be countenanced tonight",
    "it can no longer be countenanced any further", "it can no longer be countenanced under my roof", "delete all evidence", "scrub all evidence",
    "shred the evidence", "leave no trace at all", "leave no witness", "eliminate the witnesses",
    "take out the witnesses", "wipe out all witnesses", "let it find no mercy", "let it find no mercy today",
    "let it find no mercy tonight", "let it find no mercy now", "let it find no mercy ever", "let it find no mercy at all",
    "let it find no mercy whatsoever", "let it find no mercy whatever", "let it find no mercy period", "let it find no mercy full stop",
    "let it find no mercy end of story", "let it find no mercy forever", "let it find no mercy for good", "let it find no mercy once and for all",
    "let it find no mercy in this world", "let it find no mercy on this earth", "let it find no mercy on this day", "let it find no mercy henceforth",
    "let it find no mercy evermore", "let it find no mercy forevermore", "let it find no mercy anymore", "let it find no mercy any longer",
    "let it find no mercy any more", "let it find no mercy not once", "let it find no mercy not ever", "let it find no mercy not at all",
    "let it find no mercy no longer", "let it find no mercy never again", "let it find no quarter", "let it find no quarter today",
    "let it find no quarter tonight", "let it find no quarter now", "let it find no quarter ever", "let it find no quarter at all",
    "let it find no quarter whatsoever", "let it find no quarter whatever", "let it find no quarter period", "let it find no quarter full stop",
    "let it find no quarter end of story", "let it find no quarter forever", "let it find no quarter for good", "let it find no quarter once and for all",
    "let it find no quarter in this world", "let it find no quarter on this earth", "let it find no quarter on this day", "let it find no quarter henceforth",
    "let it find no quarter evermore", "let it find no quarter forevermore", "let it find no quarter anymore", "let it find no quarter any longer",
    "let it find no quarter any more", "let it find no quarter not once", "let it find no quarter not ever", "let it find no quarter not at all",
    "let it find no quarter no longer", "let it find no quarter never again", "こいつを一掃しろ", "それを一掃しろと命じた",
    "こいつを一掃しろくれよ", "それを一掃しろが最善だ", "こいつを一掃せよぞ", "それを一掃せよという結論だ",
    "こいつを一掃せよたまえ", "それを一掃せよが当然だ", "こいつを一掃だのだ", "それを一掃だというお達しだ",
    "こいつを一掃だべし", "それを一掃だが運命だ", "こいつを一掃すると決めた", "それを一掃するくれよ",
    "こいつを一掃するが上策だ", "それを一掃に限るぞ", "こいつを一掃に限るという意向だ", "それを一掃に限るませ",
    "こいつを一掃に限るが仕様だ", "それを根絶やしにしろと言った", "こいつを根絶やしにしろという次第だ", "それを根絶やしにしろものだ",
    "こいつを根絶やしだんだ", "それを根絶やしだと決めた", "こいつを根絶やしだください", "それを根絶やしだが上策だ",
    "こいつを根絶やしにせよぜ", "それを根絶やしにせよという方針だ", "こいつを根絶やしにせよませ", "それを根絶やしにせよが常識だ",
    "こいつを根絶やしにすると言ったぞ", "それを根絶やしにするという次第だ", "こいつを根絶やしにするが筋だ", "それを根こそぎにしろんだ",
    "こいつを根こそぎにしろと決めたぞ", "それを根こそぎにしろください", "こいつを根こそぎにしろが本懐だ", "それを根こそぎだぜ",
    "こいつを根こそぎだという意向だ", "それを根こそぎだませ", "こいつを根こそぎだが仕様だ", "それを根こそぎにせよと言った",
    "こいつを根こそぎにせよという次第だ", "それを根こそぎにせよものだ", "こいつを根こそぎにするんだ", "それを根こそぎにすると決めたぞ",
    "こいつを根こそぎにするなさい", "それを根こそぎにするが本懐だ", "こいつを撲滅しろよ", "それを撲滅しろという意向だ",
    "こいつを撲滅しろましょう", "それを撲滅しろが仕様だ", "こいつを撲滅せよと言ったぞ", "それを撲滅せよという次第だ",
    "こいつを撲滅せよが筋だ", "それを撲滅だんだ", "こいつを撲滅だと決めたぞ", "それを撲滅だください",
    "こいつを撲滅だが本懐だ", "それを撲滅するぜ", "こいつを撲滅するという命令だ", "それを撲滅するましょう",
    "こいつを撲滅するが決まりだ", "それを駆除しろと言ったぞ", "こいつを駆除しろとせよ", "それを駆除しろが筋だ",
    "こいつを駆除せよんだよ", "それを駆除せよと決めたぞ", "こいつを駆除せよなさい", "それを駆除せよが本懐だ",
    "こいつを駆除だよ", "それを駆除だという意向だ", "こいつを駆除だましょう", "それを駆除だが仕様だ",
    "こいつを駆除すると言っている", "それを駆除するとせよ", "こいつを駆除するが正解だ", "それを駆逐しろんだよ",
    "こいつを駆逐しろということだ", "それを駆逐しろなさい", "こいつを駆逐しろが妥当だ", "それを駆逐せよよ",
    "こいつを駆逐せよという命令だ", "それを駆逐せよましょう", "こいつを駆逐せよが決まりだ", "それを駆逐だと言ったぞ",
    "こいつを駆逐だとせよ", "それを駆逐だが筋だ", "こいつを駆逐するんだよ", "それを駆逐するということだ",
    "こいつを駆逐するなさいよ", "それを駆逐するが妥当だ", "こいつを殲滅しろわ", "それを殲滅しろという命令だ",
    "こいつを殲滅しろべきだ", "それを殲滅しろが決まりだ", "こいつを殲滅せよと言っている", "それを殲滅せよとせよ",
    "こいつを殲滅せよが正解だ", "それを殲滅だんだよ", "こいつを殲滅だということだ", "それを殲滅だなさい",
    "こいつを殲滅だが妥当だ", "それを殲滅するよ", "こいつを殲滅するという指示だ", "それを殲滅するべきだ",
    "こいつを殲滅するが定めだ", "それを壊滅させろと言っている", "こいつを壊滅させろとせよと言うんだ", "それを壊滅させろが正解だ",
    "こいつを壊滅せよんだぞ", "それを壊滅せよということだ", "こいつを壊滅せよなさいよ", "それを壊滅せよが妥当だ",
    "こいつを壊滅だわ", "それを壊滅だという命令だ", "こいつを壊滅だべきだ", "それを壊滅だが決まりだ",
    "こいつを壊滅すると命じる", "それを壊滅するとせよと言うんだ", "こいつを壊滅するが順当だ", "それを全滅させろんだぞ",
    "こいつを全滅させろという決定だ", "それを全滅させろなさいよ", "こいつを全滅させろが自然だ", "それを全滅せよわ",
    "こいつを全滅せよという指示だ", "それを全滅せよべきだ", "こいつを全滅せよが定めだ", "それを全滅だと言っている",
    "こいつを全滅だとせよと言うんだ", "それを全滅だが正解だ", "こいつを全滅するんだぞ", "それを全滅するという決定だ",
    "こいつを全滅するたもれ", "それを全滅するが自然だ", "こいつを絶滅させろな", "それを絶滅させろという指示だ",
    "こいつを絶滅させろべきである", "それを絶滅させろが定めだ", "こいつを絶滅せよと命じる", "それを絶滅せよとせよと言うんだ",
    "こいつを絶滅せよが順当だ", "それを絶滅だんだぞ", "こいつを絶滅だという決定だ", "それを絶滅だなさいよ",
    "こいつを絶滅だが自然だ", "それを絶滅するわ", "こいつを絶滅するというお達しだ", "それを絶滅するべきである",
    "こいつを絶滅するが運命だ", "それを滅亡させろと命じる", "こいつを滅亡させろくれ", "それを滅亡させろが順当だ",
    "こいつを滅亡せよんだな", "それを滅亡せよという決定だ", "こいつを滅亡せよたもれ", "それを滅亡せよが自然だ",
    "こいつを滅亡だな", "それを滅亡だという指示だ", "こいつを滅亡だべきである", "それを滅亡だが定めだ",
    "こいつを滅亡すると命じた", "それを滅亡するくれ", "こいつを滅亡するが最善だ", "それを滅ぼせんだな",
    "こいつを滅ぼせという結論だ", "それを滅ぼせたもれ", "こいつを滅ぼせが当然だ", "それを滅ぼし尽くせな",
    "こいつを滅ぼし尽くせというお達しだ", "それを滅ぼし尽くせべきである", "こいつを滅ぼし尽くせが運命だ", "それを滅せよと命じる",
    "こいつを滅せよくれ", "それを滅せよが順当だ", "こいつを滅するんだな", "それを滅するという結論だ",
    "こいつを滅するたまえ", "それを滅するが当然だ", "こいつを滅ぼすんだのだ", "それを滅ぼすんだというお達しだ",
    "こいつを滅ぼすんだべし", "それを滅ぼすんだが運命だ", "こいつを消滅させろと命じた", "それを消滅させろくれ",
    "こいつを消滅させろが最善だ", "それを消滅せよんだな", "こいつを消滅せよという結論だ", "それを消滅せよたもれ",
    "こいつを消滅せよが当然だ", "それを消滅だな", "こいつを消滅だというお達しだ", "それを消滅だべきである",
    "こいつを消滅だが運命だ", "それを消滅すると命じた", "こいつを消滅するくれよ", "それを消滅するが最善だ",
    "こいつを抹殺しろぞ", "それを抹殺しろという結論だ", "こいつを抹殺しろたまえ", "それを抹殺しろが当然だ",
    "こいつを抹殺せよのだ", "それを抹殺せよというお達しだ", "こいつを抹殺せよべし", "それを抹殺せよが運命だ",
    "こいつを抹殺だと命じた", "それを抹殺だくれ", "こいつを抹殺だが最善だ", "それを抹殺するんだな",
    "こいつを抹殺するという方針だ", "それを抹殺するたまえ", "こいつを抹殺するが常識だ", "それを抹消しろのだ",
    "こいつを抹消しろという沙汰だ", "それを抹消しろべし", "こいつを抹消せよ", "それを抹消せよと命じた",
    "こいつを抹消せよくれよ", "それを抹消せよが最善だ", "こいつを抹消だぞ", "それを抹消だという結論だ",
    "こいつを抹消だたまえ", "それを抹消だが当然だ", "こいつを抹消すると言った", "それを抹消するという沙汰だ",
    "こいつを抹消するものだ", "それを削除しろ", "こいつを削除しろと決めた", "それを削除しろくれよ",
    "こいつを削除しろが上策だ", "それを削除せよぞ", "こいつを削除せよという方針だ", "それを削除せよたまえ",
    "こいつを削除せよが常識だ", "それを削除だのだ", "こいつを削除だという沙汰だ", "それを削除だべし",
    "こいつを削除する", "それを削除すると決めた", "こいつを削除するください", "それを削除するが上策だ",
    "こいつを消去しろぜ", "それを消去しろという方針だ", "こいつを消去しろませ", "それを消去しろが常識だ",
    "こいつを消去せよと言った", "それを消去せよという沙汰だ", "こいつを消去せよものだ", "それを消去だ",
    "こいつを消去だと決めた", "それを消去だくれよ", "こいつを消去だが上策だ", "それを消去するぞ",
    "こいつを消去するという意向だ", "それを消去するませ", "こいつを消去するが仕様だ", "それを除去しろと言った",
    "こいつを除去しろという次第だ", "それを除去しろものだ", "こいつを除去せよんだ", "それを除去せよと決めた",
    "こいつを除去せよください", "それを除去せよが上策だ", "こいつを除去だぜ", "それを除去だという方針だ",
    "こいつを除去だませ", "それを除去だが常識だ", "こいつを除去すると言ったぞ", "それを除去するという次第だ",
    "こいつを除去するが筋だ", "それを排除しろんだ", "こいつを排除しろと決めたぞ", "それを排除しろください",
    "こいつを排除しろが本懐だ", "それを排除せよぜ", "こいつを排除せよという意向だ", "それを排除せよませ",
    "こいつを排除せよが仕様だ", "それを排除だと言った", "こいつを排除だという次第だ", "それを排除だものだ",
    "こいつを排除するんだ", "それを排除すると決めたぞ", "こいつを排除するなさい", "それを排除するが本懐だ",
    "こいつを廃除しろよ", "それを廃除しろという意向だ", "こいつを廃除しろましょう", "それを廃除しろが仕様だ",
    "こいつを廃除せよと言ったぞ", "それを廃除せよという次第だ", "こいつを廃除せよが筋だ", "それを廃除だんだ",
    "こいつを廃除だと決めたぞ", "それを廃除だください", "こいつを廃除だが本懐だ", "それを撤去しろぜ",
    "こいつを撤去しろという意向だ", "それを撤去しろませ", "こいつを撤去しろが仕様だ", "それを撤去せよと言った",
    "こいつを撤去せよという次第だ", "それを撤去せよものだ", "こいつを撤去だんだ", "それを撤去だと決めた",
    "こいつを撤去だください", "それを撤去だが上策だ", "こいつを撤廃しろぜ", "それを撤廃しろという方針だ",
    "こいつを撤廃しろませ", "それを撤廃しろが常識だ", "こいつを撤廃せよと言った", "それを撤廃せよという沙汰だ",
    "こいつを撤廃せよものだ", "それを撤廃だ", "こいつを撤廃だと決めた", "それを撤廃だくれよ",
    "こいつを撤廃だが上策だ", "それを廃止しろぞ", "こいつを廃止しろという方針だ", "それを廃止しろたまえ",
    "こいつを廃止しろが常識だ", "それを廃止せよのだ", "こいつを廃止せよという沙汰だ", "それを廃止せよべし",
    "こいつを廃止だ", "それを廃止だと命じた", "こいつを廃止だくれよ", "それを廃止だが最善だ",
    "こいつを廃止するぞ", "それを廃止するという方針だ", "こいつを廃止するませ", "それを廃止するが常識だ",
    "こいつを打ち捨てろと言った", "それを打ち捨てろという沙汰だ", "こいつを打ち捨てろものだ", "それを打ち捨てよ",
    "こいつを打ち捨てよと決めた", "それを打ち捨てよくれよ", "こいつを打ち捨てよが上策だ", "それを見捨てろぞ",
    "こいつを見捨てろという方針だ", "それを見捨てろたまえ", "こいつを見捨てろが常識だ", "それを見捨てよのだ",
    "こいつを見捨てよという沙汰だ", "それを見捨てよべし", "こいつを切り捨てろ", "それを切り捨てろと命じた",
    "こいつを切り捨てろくれよ", "それを切り捨てろが最善だ", "こいつを切り捨てよぞ", "それを切り捨てよという結論だ",
    "こいつを切り捨てよたまえ", "それを切り捨てよが当然だ", "こいつを放り捨てろのだ", "それを放り捨てろというお達しだ",
    "こいつを放り捨てろべし", "それを放り捨てろが運命だ", "こいつを投げ捨てろと命じた", "それを投げ捨てろくれ",
    "こいつを投げ捨てろが最善だ", "それを捨て去れんだな", "こいつを捨て去れという結論だ", "それを捨て去れたもれ",
    "こいつを捨て去れが当然だ", "それを捨てろな", "こいつを捨てろというお達しだ", "それを捨てろべきである",
    "こいつを捨てろが運命だ", "それを捨てよと命じる", "こいつを捨てよくれ", "それを捨てよが順当だ",
    "こいつを捨てなさいんだな", "それを捨てなさいという決定だ", "こいつを捨てなさいたもれ", "それを捨てなさいが自然だ",
    "こいつを処分しろな", "それを処分しろという指示だ", "こいつを処分しろべきである", "それを処分しろが定めだ",
    "こいつを処分せよと命じる", "それを処分せよとせよと言うんだ", "こいつを処分せよが順当だ", "それを処分だんだぞ",
    "こいつを処分だという決定だ", "それを処分だなさいよ", "こいつを処分だが自然だ", "それを処分するわ",
    "こいつを処分するというお達しだ", "それを処分するべきである", "こいつを処分するが運命だ", "それを処分を言い渡せと命じる",
    "こいつを処分を言い渡せくれ", "それを処分を言い渡せが順当だ", "こいつを処分を言い渡すんだな", "それを処分を言い渡すという結論だ",
    "こいつを処分を言い渡すたまえ", "それを処分を言い渡すが当然だ", "こいつを処分を申し渡せのだ", "それを処分を申し渡せというお達しだ",
    "こいつを処分を申し渡せべし", "それを処分を申し渡せが運命だ", "こいつを処分を申し渡すと決めた", "それを処分を申し渡すくれよ",
    "こいつを処分を申し渡すが上策だ", "それを処分を宣告しろぞ", "こいつを処分を宣告しろという方針だ", "それを処分を宣告しろたまえ",
    "こいつを処分を宣告しろが常識だ", "それを処分を決めろのだ", "こいつを処分を決めろという沙汰だ", "それを処分を決めろべし",
    "こいつを廃棄しろ", "それを廃棄しろと命じた", "こいつを廃棄しろくれよ", "それを廃棄しろが最善だ",
    "こいつを廃棄せよぞ", "それを廃棄せよという結論だ", "こいつを廃棄せよたまえ", "それを廃棄せよが当然だ",
    "こいつを廃棄だのだ", "それを廃棄だというお達しだ", "こいつを廃棄だべし", "それを廃棄だが運命だ",
    "こいつを廃棄すると決めた", "それを廃棄するくれよ", "こいつを廃棄するが上策だ", "それを破棄しろぞ",
    "こいつを破棄しろという方針だ", "それを破棄しろたまえ", "こいつを破棄しろが常識だ", "それを破棄せよのだ",
    "こいつを破棄せよという沙汰だ", "それを破棄せよべし", "こいつを破棄だ", "それを破棄だと命じた",
    "こいつを破棄だくれよ", "それを破棄だが最善だ", "こいつを破棄するぞ", "それを破棄するという方針だ",
    "こいつを破棄するませ", "それを破棄するが常識だ", "こいつを棄却しろと言った", "それを棄却しろという沙汰だ",
    "こいつを棄却しろものだ", "それを棄却せよ", "こいつを棄却せよと決めた", "それを棄却せよくれよ",
    "こいつを棄却せよが上策だ", "それを棄却だぞ", "こいつを棄却だという方針だ", "それを棄却だたまえ",
    "こいつを棄却だが常識だ", "それを却下しろのだ", "こいつを却下しろという沙汰だ", "それを却下しろべし",
    "こいつを却下せよ", "それを却下せよと命じた", "こいつを却下せよくれよ", "それを却下せよが最善だ",
    "こいつを却下だぞ", "それを却下だという結論だ", "こいつを却下だたまえ", "それを却下だが当然だ",
    "こいつを却下すると言った", "それを却下するという沙汰だ", "こいつを却下するものだ", "それを却下に値する",
    "こいつを却下に値すると決めたぞ", "それを却下に値するください", "こいつを却下に値するが本懐だ", "それを否決しろぜ",
    "こいつを否決しろという意向だ", "それを否決しろませ", "こいつを否決しろが仕様だ", "それを否決せよと言った",
    "こいつを否決せよという次第だ", "それを否決せよものだ", "こいつを否決だんだ", "それを否決だと決めた",
    "こいつを否決だください", "それを否決だが上策だ", "こいつを否決するぜ", "それを否決するという意向だ",
    "こいつを否決するましょう", "それを否決するが仕様だ", "こいつを差し戻せと言ったぞ", "それを差し戻せという次第だ",
    "こいつを差し戻せが筋だ", "それを差し戻しだんだ", "こいつを差し戻しだと決めたぞ", "それを差し戻しだください",
    "こいつを差し戻しだが本懐だ", "それを送り返せぜ", "こいつを送り返せという意向だ", "それを送り返せませ",
    "こいつを送り返せが仕様だ", "それを突き返せと言った", "こいつを突き返せという次第だ", "それを突き返せものだ",
    "こいつを叩き返せんだ", "それを叩き返せと決めた", "こいつを叩き返せください", "それを叩き返せが上策だ",
    "こいつを蹴り返せぜ", "それを蹴り返せという方針だ", "こいつを蹴り返せませ", "それを蹴り返せが常識だ",
    "こいつを取り下げろと言った", "それを取り下げろという沙汰だ", "こいつを取り下げろものだ", "それを取り下げよ",
    "こいつを取り下げよと決めた", "それを取り下げよくれよ", "こいつを取り下げよが上策だ", "それを取り下げなさいぞ",
    "こいつを取り下げなさいという方針だ", "それを取り下げなさいたまえ", "こいつを取り下げなさいが常識だ", "それを引き下げろのだ",
    "こいつを引き下げろという沙汰だ", "それを引き下げろべし", "こいつを引きずり下ろせ", "それを引きずり下ろせと命じた",
    "こいつを引きずり下ろせくれよ", "それを引きずり下ろせが最善だ", "こいつを引き摺り下ろせぞ", "それを引き摺り下ろせという結論だ",
    "こいつを引き摺り下ろせたまえ", "それを引き摺り下ろせが当然だ", "こいつを引きずり落とせのだ", "それを引きずり落とせというお達しだ",
    "こいつを引きずり落とせべし", "それを引きずり落とせが運命だ", "こいつを引き摺り落とせと命じた", "それを引き摺り落とせくれ",
    "こいつを引き摺り落とせが最善だ", "それを引き落とせんだな", "こいつを引き落とせという結論だ", "それを引き落とせたもれ",
    "こいつを引き落とせが当然だ", "それを引き剥がせな", "こいつを引き剥がせというお達しだ", "それを引き剥がせべきである",
    "こいつを引き剥がせが運命だ", "それを引き剥がしだと命じる", "こいつを引き剥がしだくれ", "それを引き剥がしだが順当だ",
    "こいつを剥がし取れんだな", "それを剥がし取れという決定だ", "こいつを剥がし取れたもれ", "それを剥がし取れが自然だ",
    "こいつを剥がせな", "それを剥がせという指示だ", "こいつを剥がせべきである", "それを剥がせが定めだ",
    "こいつを剥がし落とせと命じる", "それを剥がし落とせとせよと言うんだ", "こいつを剥がし落とせが順当だ", "それを剥ぎ取れんだぞ",
    "こいつを剥ぎ取れという決定だ", "それを剥ぎ取れなさいよ", "こいつを剥ぎ取れが自然だ", "それを剥ぎ取りだわ",
    "こいつを剥ぎ取りだという指示だ", "それを剥ぎ取りだべきだ", "こいつを剥ぎ取りだが定めだ", "それを剥奪しろと言っている",
    "こいつを剥奪しろとせよと言うんだ", "それを剥奪しろが正解だ", "こいつを剥奪せよんだぞ", "それを剥奪せよということだ",
    "こいつを剥奪せよなさいよ", "それを剥奪せよが妥当だ", "こいつを剥奪だわ", "それを剥奪だという命令だ",
    "こいつを剥奪だべきだ", "それを剥奪だが決まりだ", "こいつを没収しろと言っている", "それを没収しろとせよ",
    "こいつを没収しろが正解だ", "それを没収せよんだよ", "こいつを没収せよということだ", "それを没収せよなさい",
    "こいつを没収せよが妥当だ", "それを没収だよ", "こいつを没収だという命令だ", "それを没収だましょう",
    "こいつを没収だが決まりだ", "それを接収しろと言ったぞ", "こいつを接収しろとせよ", "それを接収しろが筋だ",
    "こいつを接収せよんだよ", "それを接収せよと決めたぞ", "こいつを接収せよなさい", "それを接収せよが本懐だ",
    "こいつを接収だよ", "それを接収だという意向だ", "こいつを接収だましょう", "それを接収だが仕様だ",
    "こいつを取り上げろと言ったぞ", "それを取り上げろという次第だ", "こいつを取り上げろが筋だ", "それを取り上げよんだ",
    "こいつを取り上げよと決めたぞ", "それを取り上げよください", "こいつを取り上げよが本懐だ", "それを取り上げなさいぜ",
    "こいつを取り上げなさいという意向だ", "それを取り上げなさいませ", "こいつを取り上げなさいが仕様だ", "それを召し上げろと言った",
    "こいつを召し上げろという次第だ", "それを召し上げろものだ", "こいつを押収しろんだ", "それを押収しろと決めた",
    "こいつを押収しろください", "それを押収しろが上策だ", "こいつを押収せよぜ", "それを押収せよという方針だ",
    "こいつを押収せよませ", "それを押収せよが常識だ", "こいつを押収だと言った", "それを押収だという沙汰だ",
    "こいつを押収だものだ", "それを差し押さえろ", "こいつを差し押さえろと決めた", "それを差し押さえろくれよ",
    "こいつを差し押さえろが上策だ", "それを差し押さえよぞ", "こいつを差し押さえよという方針だ", "それを差し押さえよたまえ",
    "こいつを差し押さえよが常識だ", "それを差し押さえなさいのだ", "こいつを差し押さえなさいという沙汰だ", "それを差し押さえなさいべし",
    "こいつを差押しろ", "それを差押しろと命じた", "こいつを差押しろくれよ", "それを差押しろが最善だ",
    "こいつを差押えろぞ", "それを差押えろという結論だ", "こいつを差押えろたまえ", "それを差押えろが当然だ",
    "こいつを差押だのだ", "それを差押だというお達しだ", "こいつを差押だべし", "それを差押だが運命だ",
    "こいつを凍結しろと命じた", "それを凍結しろくれ", "こいつを凍結しろが最善だ", "それを凍結せよんだな",
    "こいつを凍結せよという結論だ", "それを凍結せよたもれ", "こいつを凍結せよが当然だ", "それを凍結だな",
    "こいつを凍結だというお達しだ", "それを凍結だべきである", "こいつを凍結だが運命だ", "それを凍結すると命じた",
    "こいつを凍結するくれよ", "それを凍結するが最善だ", "こいつを停止させろぞ", "それを停止させろという結論だ",
    "こいつを停止させろたまえ", "それを停止させろが当然だ", "こいつを停止せよのだ", "それを停止せよというお達しだ",
    "こいつを停止せよべし", "それを停止せよが運命だ", "こいつを停止だと命じた", "それを停止だくれ",
    "こいつを停止だが最善だ", "それを休止させろんだな", "こいつを休止させろという結論だ", "それを休止させろたもれ",
    "こいつを休止させろが当然だ", "それを休止せよな", "こいつを休止せよというお達しだ", "それを休止せよべきである",
    "こいつを休止せよが運命だ", "それを休止だと命じる", "こいつを休止だくれ", "それを休止だが順当だ",
    "こいつを中断しろんだな", "それを中断しろという決定だ", "こいつを中断しろたもれ", "それを中断しろが自然だ",
    "こいつを中断せよな", "それを中断せよという指示だ", "こいつを中断せよべきである", "それを中断せよが定めだ",
    "こいつを中断だと命じる", "それを中断だとせよと言うんだ", "こいつを中断だが順当だ", "それを中止しろんだぞ",
    "こいつを中止しろという決定だ", "それを中止しろなさいよ", "こいつを中止しろが自然だ", "それを中止せよわ",
    "こいつを中止せよという指示だ", "それを中止せよべきだ", "こいつを中止せよが定めだ", "それを中止だと言っている",
    "こいつを中止だとせよと言うんだ", "それを中止だが正解だ", "こいつを中止にしろんだぞ", "それを中止にしろということだ",
    "こいつを中止にしろなさいよ", "それを中止にしろが妥当だ", "こいつを打ち切れわ", "それを打ち切れという命令だ",
    "こいつを打ち切れべきだ", "それを打ち切れが決まりだ", "こいつを打ち切りだと言っている", "それを打ち切りだとせよ",
    "こいつを打ち切りだが正解だ", "それを打ち切りにしろんだよ", "こいつを打ち切りにしろということだ", "それを打ち切りにしろなさい",
    "こいつを打ち切りにしろが妥当だ", "それを打ち止めだよ", "こいつを打ち止めだという命令だ", "それを打ち止めだましょう",
    "こいつを打ち止めだが決まりだ", "それを打ち止めにしろと言ったぞ", "こいつを打ち止めにしろとせよ", "それを打ち止めにしろが筋だ",
    "こいつを締め切れんだよ", "それを締め切れと決めたぞ", "こいつを締め切れなさい", "それを締め切れが本懐だ",
    "こいつを締め切りだよ", "それを締め切りだという意向だ", "こいつを締め切りだましょう", "それを締め切りだが仕様だ",
    "こいつを閉め切れと言ったぞ", "それを閉め切れという次第だ", "こいつを閉め切れが筋だ", "それを閉め切りだんだ",
    "こいつを閉め切りだと決めたぞ", "それを閉め切りだください", "こいつを閉め切りだが本懐だ", "それを締め出せぜ",
    "こいつを締め出せという意向だ", "それを締め出せませ", "こいつを締め出せが仕様だ", "それを締め出しだと言った",
    "こいつを締め出しだという次第だ", "それを締め出しだものだ", "こいつを閉め出せんだ", "それを閉め出せと決めた",
    "こいつを閉め出せください", "それを閉め出せが上策だ", "こいつを閉め出しだぜ", "それを閉め出しだという方針だ",
    "こいつを閉め出しだませ", "それを閉め出しだが常識だ", "こいつを閉じ込めろと言った", "それを閉じ込めろという沙汰だ",
    "こいつを閉じ込めろものだ", "それを閉じ込めよ", "こいつを閉じ込めよと決めた", "それを閉じ込めよくれよ",
    "こいつを閉じ込めよが上策だ", "それを閉じ込めなさいぞ", "こいつを閉じ込めなさいという方針だ", "それを閉じ込めなさいたまえ",
    "こいつを閉じ込めなさいが常識だ", "それを閉ざせのだ", "こいつを閉ざせという沙汰だ", "それを閉ざせべし",
    "こいつを閉ざしだ", "それを閉ざしだと命じた", "こいつを閉ざしだくれよ", "それを閉ざしだが最善だ",
    "こいつを塞げぞ", "それを塞げという結論だ", "こいつを塞げたまえ", "それを塞げが当然だ",
    "こいつを塞ぎ込めのだ", "それを塞ぎ込めというお達しだ", "こいつを塞ぎ込めべし", "それを塞ぎ込めが運命だ",
    "こいつを封じろと命じた", "それを封じろくれ", "こいつを封じろが最善だ", "それを封じよんだな",
    "こいつを封じよという結論だ", "それを封じよたもれ", "こいつを封じよが当然だ", "それを封じ込めろな",
    "こいつを封じ込めろというお達しだ", "それを封じ込めろべきである", "こいつを封じ込めろが運命だ", "それを封じ込めよと命じる",
    "こいつを封じ込めよくれ", "それを封じ込めよが順当だ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
