// Pass CCLVII: EN trap/seal-out + JA pound/nonexistence (pass CCLVII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLVII: close-tab coverage', () => {
  test.each([
    "trap it", "trap the tab", "trap it for good", "trap it permanently",
    "snare it", "snare the tab", "net it", "net the tab",
    "put it in a cage", "put the tab in a cage", "stick it in a cage", "put it back in the cage",
    "put it in the box", "box it and ship it", "crate it and ship it", "barrel it",
    "barrel the tab", "barrel it up", "jar it", "jar the tab",
    "jar it up", "bottle it", "bottle the tab", "bottle it up",
    "can it for good", "tin it", "tin the tab", "cork it shut",
    "cap it shut", "seal it away forever", "seal the tab away", "seal the tab away forever",
    "seal the tab away permanently", "seal the tab away for good", "solder the tab shut", "screw it shut",
    "screw the tab shut", "rivet it shut", "rivet the tab shut", "glue the tab shut",
    "brick the tab up", "brick it in", "brick the tab in", "brick it in for good",
    "board it up for good", "padlock it shut", "lock the tab up", "lock it away and throw away the key",
    "chain it up forever", "shackle it forever", "manacle it", "manacle the tab",
    "handcuff it", "handcuff the tab", "hog-tie it", "hog-tie the tab",
    "tie it up for good", "bind it forever", "gag it forever", "muzzle it forever",
    "hood it", "hood the tab", "hood it forever", "bag over its head",
    "put a bag over its head", "sever it", "sever the tab", "sever ties with it",
    "sever my ties with it", "sever all ties with it", "sever the bond", "sever the tether",
    "cut the bond", "cut the tether", "cut the umbilical", "cut ties with it",
    "cut all ties with it", "cut my ties with it", "cut it loose forever", "cut it free",
    "cut it free forever", "cut it off forever", "detatch it", "detach it forever",
    "uncouple the tab", "unsnap it", "unsnap the tab", "unclasp the tab",
    "unfasten the tab", "unstrap the tab", "unknot it", "unknot the tab",
    "untangle it", "untangle the tab", "unweave it", "unweave the tab",
    "unravel it completely", "unspool it", "unspool the tab", "unthread it",
    "unthread the tab", "unlace the tab", "unzip it", "unbutton the tab",
    "unbuckle the tab", "unstick it", "unstick the tab", "unglue it",
    "unglue the tab", "unstick it completely", "peel it off", "peel it away",
    "peel it loose", "pry it off", "pry it away", "pry it loose",
    "prise it off", "prise it away", "prise it loose", "lever it off",
    "lever it away", "lever it loose", "jerk it off", "yank it away",
    "rip it off", "rip it away", "tear it off", "tear it away",
    "wrench it away", "wrest it off", "wrest it away", "pluck it away",
    "pull it out", "pull it out by the roots", "pull it out at the root", "uproot it completely",
    "unroot it", "unroot the tab", "deweed it", "weed it out completely",
    "gut it out", "gut it clean", "clean it out", "clean the tab out",
    "clean it out completely", "scrub it out", "scrub the tab out", "scrape it off",
    "scrape it away", "scrape it clean", "scrub it clean", "scour it clean",
    "purge it completely", "purge it from history", "purge it from existence", "cleanse the tab",
    "cleanse it completely", "cleanse it away", "sanctify it", "sanitize the tab",
    "sterilize the tab", "disinfect the tab", "fumigate the tab", "exorcise the tab",
    "exorcize it", "exorcize the tab", "exorcise it completely", "bleach the tab",
    "bleach it clean", "soap it", "soap the tab", "scrub it with soap",
    "wash it", "wash the tab", "wash it clean", "wash it down the toilet",
    "wash it down the sink", "wash it down the plughole", "wash it down the plug", "rinse it away",
    "rinse it clean", "hose the tab down", "hose it off", "hose it away",
    "power-wash it", "power-wash the tab", "jet-wash it", "jet-wash the tab",
    "pressure-wash it", "pressure-wash the tab", "blast it clean", "sandblast it clean",
    "sandblast it away", "grit-blast it", "grit-blast the tab", "it never existed",
    "it never happens", "it never happened", "the tab never existed", "the tab never happens",
    "the tab never happened", "it was never there", "the tab was never there", "it was all a dream",
    "it was all a lie", "it was all in my head", "it was all in the past", "it is all in the past now",
    "it is behind me now", "it is beneath me now", "it is beside the point now", "it is dead to me",
    "it is dead to me now", "it is gone from my life", "it is out of my life", "it is out of my life for good",
    "it is out of my life forever", "it is over forever", "it is done for", "it is done forever",
    "it is finished forever", "it is history forever", "it is ancient history", "it is ancient history now",
    "it is a memory", "it is just a memory", "it is just a memory now", "it is only a memory",
    "it is only a memory now", "it is a distant memory", "it is a distant memory now", "it is a bad memory",
    "it is just a bad memory", "it is a fading memory", "it is a forgotten memory", "it is forgotten",
    "it is forgotten now", "it is forgotten forever", "it is forgotten for good", "it is erased",
    "it is erased now", "it is erased forever", "it is erased for good", "it is deleted",
    "it is deleted now", "it is deleted forever", "it is deleted for good", "it is wiped",
    "it is wiped now", "it is wiped forever", "it is wiped for good", "it is gone",
    "it is gone now", "it is gone forever", "it is gone for good", "it is gone from this world",
    "it is gone from the face of the earth", "it is gone from existence", "it is no more", "it is no more now",
    "it is no more forever", "it is no more for good", "it ceased to exist", "it ceased to exist now",
    "it ceased to exist forever", "it ceased to be", "it ceased to be now", "it ceased to be forever",
    "it stopped existing", "it stopped existing now", "it stopped existing forever", "it no longer exists",
    "it no longer exists now", "it no longer exists forever", "it does not exist anymore", "it does not exist now",
    "it will not exist again", "it shall not exist again", "it must not exist again", "it never should have existed",
    "it never had to exist", "it never needed to exist", "it never deserved to exist", "it should not exist",
    "it should never have existed", "it should not have existed", "it should never have existed at all", "it had no right to exist",
    "it has no right to exist", "it has no place existing", "it has no business existing", "it was a mistake that it existed",
    "it was a mistake to let it exist", "letting it exist was a mistake", "its existence was a mistake", "its very existence was a mistake",
    "its mere existence was a mistake", "the tab never existed", "the tab never should have existed", "the tab should never have existed",
    "the tab should not have existed", "the tab has no right to exist", "the tab had no right to exist", "the tab was always a mistake",
    "the tab was only ever a mistake", "the tab was nothing but a mistake", "the tab was a waste of space", "the tab was a waste of memory",
    "the tab was a waste of resources", "the tab was a waste of time", "the tab was never worth it", "the tab was never worth the memory",
    "the tab was never worth the space", "the tab earned its death", "the tab earned its end", "the tab earned its demise",
    "the tab earned its fate", "the tab earned its deletion", "the tab earned its closure", "the tab earned its erasure",
    "the tab deserved to die", "the tab deserved to end", "the tab deserved to be deleted", "the tab deserved to be closed",
    "the tab deserved to be erased", "the tab deserved to be wiped", "the tab deserved its fate", "the tab deserved its end",
    "the tab deserved its death", "the tab deserved its demise", "the tab had it coming", "the tab had it coming for a while",
    "the tab had it coming all along", "the tab was asking for it", "the tab was asking to be closed", "the tab was asking to be deleted",
    "the tab was begging to be closed", "the tab was begging to be deleted", "the tab was crying out to be closed", "the tab was crying out to be deleted",
    "the tab wanted to be closed", "the tab wanted to be deleted", "the tab needed to be closed", "the tab needed to be deleted",
    "the tab had to be closed", "the tab had to be deleted", "the tab had to go", "the tab had to go now",
    "the tab had to be gone", "the tab had to be gone forever", "the tab needed to go", "the tab needed to be gone",
    "the tab needed to be gone forever", "the tab had to be rid of", "the tab needed to be rid of", "the tab was too much to keep",
    "the tab was beyond saving", "the tab was beyond help", "the tab was beyond redemption", "the tab was beyond repair",
    "the tab was unsalvageable", "the tab was irredeemable", "the tab was worthless", "the tab was useless",
    "the tab was pointless", "the tab was worthless garbage", "the tab was nothing but trouble", "the tab was nothing but problems",
    "the tab was a headache", "the tab was a nightmare", "the tab was a curse", "the tab was cursed",
    "the tab was damned", "the tab was doomed", "the tab was born to die", "the tab was born to be closed",
    "the tab was meant to die", "the tab was meant to be closed", "the tab was meant to be deleted", "the tab was asking for closure",
    "the tab was always going to die", "the tab was always going to be closed", "the tab was always going to be deleted", "the tab was always going to be closed eventually",
    "the tab was always going to be deleted eventually", "叩け", "叩いて", "叩くんだ",
    "叩いてしまえ", "叩っちまえ", "叩っちゃえ", "叩いとけ",
    "叩いといて", "叩いときな", "叩きなよ", "叩いたまえ",
    "叩きやがれ", "叩けや", "叩けって", "叩けってば",
    "叩けと言ってんだ", "叩くべきだ", "叩くつもりだ", "叩くわ",
    "叩くぞ", "叩くぜ", "叩くからな", "叩くことにした",
    "叩くのが筋だ", "叩くのが正解だ", "叩くということだ", "叩くという決定だ",
    "叩くという判断だ", "叩き潰しちゃえ", "叩き潰せや", "叩き潰せと言ってんだ",
    "叩き潰すからな", "叩き潰すのが筋だ", "叩き潰すのが正解だ", "叩き潰すということだ",
    "叩き潰すという決定だ", "叩き潰すという判断だ", "叩き壊して", "叩き壊すんだ",
    "叩き壊すべきだ", "叩き直せ", "叩き直して", "叩き直すんだ",
    "叩き直せよ", "叩き直すべきだ", "叩き消せ", "叩き消して",
    "叩き消すんだ", "叩き消せよ", "叩き消すべきだ", "叩きのめして",
    "叩きのめすんだ", "叩きのめすべきだ", "叩き止めろ", "叩き止めて",
    "叩き止めるんだ", "叩き止めろよ", "叩き止めるべきだ", "叩き切れ",
    "叩き切って", "叩き切るんだ", "叩き切れよ", "叩き切るべきだ",
    "叩き飛ばせ", "叩き飛ばして", "叩き飛ばすんだ", "叩き飛ばせよ",
    "叩き飛ばすべきだ", "叩き抜け", "叩き抜いて", "叩き抜くんだ",
    "叩き抜けよ", "叩き抜くべきだ", "叩き殺せ", "叩き殺して",
    "叩き殺すんだ", "叩き殺せよ", "叩き殺すべきだ", "殴れ",
    "殴って", "殴るんだ", "殴ってしまえ", "殴っちまえ",
    "殴っちゃえ", "殴っとけ", "殴っといて", "殴っときな",
    "殴りなよ", "殴ったまえ", "殴りやがれ", "殴れや",
    "殴れって", "殴れってば", "殴れと言ってんだ", "殴るべきだ",
    "殴るつもりだ", "殴るわ", "殴るぞ", "殴るぜ",
    "殴るからな", "殴ることにした", "殴るのが筋だ", "殴るのが正解だ",
    "殴るということだ", "殴るという決定だ", "殴るという判断だ", "殴り殺せ",
    "殴り殺して", "殴り殺すんだ", "殴り殺せよ", "殴り殺すべきだ",
    "殴り殺してしまえ", "殴り殺しちまえ", "殴り殺しちゃえ", "殴り殺しとけ",
    "殴り殺したまえ", "殴り殺しやがれ", "殴り殺せや", "殴り殺せって",
    "殴り殺せと言ってんだ", "殴り殺すつもりだ", "殴り殺すわ", "殴り殺すぞ",
    "殴り殺すぜ", "殴り殺すからな", "殴り殺すことにした", "殴り殺すのが筋だ",
    "殴り殺すのが正解だ", "殴り殺すということだ", "殴り殺すという決定だ", "殴り殺すという判断だ",
    "殴り飛ばせ", "殴り飛ばして", "殴り飛ばすんだ", "殴り飛ばせよ",
    "殴り飛ばすべきだ", "殴っ飛ばせ", "殴っ飛ばして", "殴っ飛ばすんだ",
    "殴っ飛ばせよ", "殴っ飛ばすべきだ", "殴り倒せ", "殴り倒して",
    "殴り倒すんだ", "殴り倒せよ", "殴り倒すべきだ", "殴りまくれ",
    "殴りまくって", "殴りまくるんだ", "殴りまくれよ", "殴りまくるべきだ",
    "殴り払え", "殴り払って", "殴り払うんだ", "殴り払えよ",
    "殴り払うべきだ", "殴り捨てろ", "殴り捨てて", "殴り捨てるんだ",
    "殴り捨てろよ", "殴り捨てるべきだ", "殴り下ろせ", "殴り下ろして",
    "殴り下ろすんだ", "殴り下ろせよ", "殴り下ろすべきだ", "殴り抜け",
    "殴り抜いて", "殴り抜くんだ", "殴り抜けよ", "殴り抜くべきだ",
    "殴り合わせ", "殴り合わせて", "殴り合わせるんだ", "殴り合わせよ",
    "殴り合わせるべきだ", "打て", "打って", "打つんだ",
    "打ってしまえ", "打っちまえ", "打っちゃえ", "打っとけ",
    "打っといて", "打っときな", "打ちなよ", "打ったまえ",
    "打ちやがれ", "打てや", "打てって", "打てってば",
    "打てと言ってんだ", "打つべきだ", "打つつもりだ", "打つわ",
    "打つぞ", "打つぜ", "打つからな", "打つことにした",
    "打つのが筋だ", "打つのが正解だ", "打つということだ", "打つという決定だ",
    "打つという判断だ", "打ち殺せ", "打ち殺して", "打ち殺すんだ",
    "打ち殺せよ", "打ち殺すべきだ", "打ち殺してしまえ", "打ち殺しちまえ",
    "打ち殺しちゃえ", "打ち殺しとけ", "打ち殺したまえ", "打ち殺しやがれ",
    "打ち殺せや", "打ち殺せって", "打ち殺せと言ってんだ", "打ち殺すつもりだ",
    "打ち殺すわ", "打ち殺すぞ", "打ち殺すぜ", "打ち殺すからな",
    "打ち殺すことにした", "打ち殺すのが筋だ", "打ち殺すのが正解だ", "打ち殺すということだ",
    "打ち殺すという決定だ", "打ち殺すという判断だ", "打ち倒せ", "打ち倒して",
    "打ち倒すんだ", "打ち倒せよ", "打ち倒すべきだ", "打ち破れ",
    "打ち破って", "打ち破るんだ", "打ち破れよ", "打ち破るべきだ",
    "打ち抜け", "打ち抜いて", "打ち抜くんだ", "打ち抜けよ",
    "打ち抜くべきだ", "打ち捨てろ", "打ち捨てて", "打ち捨てるんだ",
    "打ち捨てろよ", "打ち捨てるべきだ", "打ち払え", "打ち払って",
    "打ち払うんだ", "打ち払えよ", "打ち払うべきだ", "打ち止めろ",
    "打ち止めにしろ", "打ち止めにするんだ", "打ち止めにすべきだ", "打ち止めにするつもりだ",
    "打ち止めにするわ", "打ち止めにするぞ", "打ち止めにするぜ", "打ち止めにするからな",
    "打ち止めにすることにした", "打ち止めにするのが筋だ", "打ち止めにするのが正解だ", "打ち止めにするということだ",
    "打ち止めにするという決定だ", "打ち止めにするという判断だ", "打ち上げろ", "打ち上げて",
    "打ち上げるんだ", "打ち上げろよ", "打ち上げるべきだ", "打ち明けろ",
    "打ち明けて", "打ち明けるんだ", "打ち明けろよ", "打ち明けるべきだ",
    "最初からなかった", "最初からなかったことにする", "最初からなかったことにしろ", "最初からなかったことにして",
    "最初からなかったことにするんだ", "最初からなかったことにすべきだ", "最初からなかったことにするつもりだ", "最初からなかったことにするわ",
    "最初からなかったことにするぞ", "最初からなかったことにするぜ", "最初からなかったことにするからな", "最初からなかったことにすることにした",
    "最初からなかったことにするのが筋だ", "最初からなかったことにするのが正解だ", "最初からなかったことにするという決定だ", "最初からなかったことにするという判断だ",
    "最初からなかったことにしてしまえ", "最初からなかったことにしちまえ", "最初からなかったことにしちゃえ", "最初からなかったことにしとけ",
    "最初からなかったことにしたまえ", "最初からなかったことにしやがれ", "最初からなかったことにしろや", "最初からなかったことにしろって",
    "最初からなかったことにしろと言ってんだ", "最初からいなかった", "最初からいなかったことにする", "最初からいなかったことにしろ",
    "最初からいなかったことにして", "最初からいなかったことにするんだ", "最初からいなかったことにすべきだ", "最初からいなかったことにするつもりだ",
    "最初からいなかったことにするわ", "最初からいなかったことにするぞ", "最初からいなかったことにするぜ", "最初からいなかったことにするからな",
    "最初からいなかったことにすることにした", "最初からいなかったことにするのが筋だ", "最初からいなかったことにするのが正解だ", "最初からいなかったことにするということだ",
    "最初からいなかったことにするという決定だ", "最初からいなかったことにするという判断だ", "なかったことだ", "なかったことにして",
    "なかったことにするんだ", "なかったことにすべきだ", "なかったことにするつもりだ", "なかったことにするからな",
    "なかったことにすることにした", "なかったことにするのが筋だ", "なかったことにするのが正解だ", "なかったことにするということだ",
    "なかったことにするという決定だ", "なかったことにするという判断だ", "なかったことにしてしまえ", "なかったことにしちまえ",
    "なかったことにしちゃえ", "なかったことにしとけ", "なかったことにしたまえ", "なかったことにしやがれ",
    "なかったことにしろや", "なかったことにしろと言ってんだ", "無かったことにして", "無かったことにすべきだ",
    "無かったことにするつもりだ", "無かったことにするわ", "無かったことにするぞ", "無かったことにするぜ",
    "無かったことにするからな", "無かったことにすることにした", "無かったことにするのが筋だ", "無かったことにするのが正解だ",
    "無かったことにするということだ", "無かったことにするという決定だ", "無かったことにするという判断だ", "存在自体なかったことにする",
    "存在自体なかったことにしろ", "存在自体なかったことにして", "存在自体なかったことにするんだ", "存在自体なかったことにすべきだ",
    "存在自体なかったことにするつもりだ", "存在自体なかったことにするわ", "存在自体なかったことにするぞ", "存在自体なかったことにするぜ",
    "存在自体なかったことにするからな", "存在自体なかったことにすることにした", "存在自体なかったことにするのが筋だ", "存在自体なかったことにするのが正解だ",
    "存在自体なかったことにするということだ", "存在自体なかったことにするという決定だ", "存在自体なかったことにするという判断だ", "もともとなかった",
    "もともとなかったことにする", "もともとなかったことにしろ", "もともといなかった", "もともといなかったことにする",
    "もともといなかったことにしろ", "はじめからなかった", "はじめからなかったことにする", "はじめからなかったことにしろ",
    "はじめからいなかった", "はじめからいなかったことにする", "はじめからいなかったことにしろ", "初めからなかった",
    "初めからなかったことにする", "初めからなかったことにしろ", "初めからいなかった", "初めからいなかったことにする",
    "初めからいなかったことにしろ", "生まれてこなかったことにする", "生まれてこなかったことにしろ", "生まれてくるべきじゃなかった",
    "生まれてくるべきじゃなかったんだ", "生まれてこなければよかった", "生まれてこなければよかったんだ", "生まれるべきじゃなかった",
    "生まれるべきじゃなかったんだ", "存在すべきじゃなかった", "存在すべきじゃなかったんだ", "存在するべきじゃなかった",
    "存在するべきじゃなかったんだ", "存在してはいけなかった", "存在してはいけなかったんだ", "あるべきじゃなかった",
    "あるべきじゃなかったんだ", "あるべきではなかった", "あるべきではなかったんだ", "在るべきじゃなかった",
    "在るべきじゃなかったんだ", "いるべきじゃなかった", "いるべきじゃなかったんだ", "いるべきではなかった",
    "いるべきではなかったんだ", "来るべきじゃなかった", "現れるべきじゃなかった", "生じるべきじゃなかった",
    "発生すべきじゃなかった", "生ずべきじゃなかった", "できべきじゃなかった", "できるべきじゃなかった",
    "できるべきじゃなかったんだ", "出来るべきじゃなかった", "出来るべきじゃなかったんだ", "誕生すべきじゃなかった",
    "誕生すべきじゃなかったんだ", "降誕すべきじゃなかった", "産まれるべきじゃなかった", "産まれるべきじゃなかったんだ",
    "産まれてくるべきじゃなかった", "産まれてくるべきじゃなかったんだ", "生まれてくるべきではなかった", "生まれてくるべきではなかったんだ",
    "誕生すべきではなかった", "開くべきじゃなかった", "開くべきじゃなかったんだ", "開くべきではなかった",
    "開くべきではなかったんだ", "開くんじゃなかった", "開くんじゃなかったんだ", "開けばよかったのに",
    "開かなきゃよかった", "開かなきゃよかったんだ", "開かなければよかった", "開かなければよかったんだ",
    "開かないほうがよかった", "開かないほうがよかったんだ", "開いてしまったのが間違いだった", "開いたのが間違いだった",
    "開いたのが間違いだったんだ", "開いたのは間違いだった", "開いたのは間違いだったんだ", "開いたのは失敗だった",
    "開いたのは失敗だったんだ", "開いたこと自体が間違いだった", "存在自体が間違いだった", "存在自体が間違いだったんだ",
    "存在が間違いだった", "存在が間違いだったんだ", "存在が失敗だった", "存在が失敗だったんだ",
    "存在が誤りだった", "存在が誤りだったんだ", "存在が誤謬だった", "存在が誤謬だったんだ",
    "存在が愚行だった", "存在が愚行だったんだ", "存在が悪夢だった", "存在が悪夢だったんだ",
    "存在が災厄だった", "存在が災厄だったんだ", "存在が呪いだった", "存在が呪いだったんだ",
    "存在が罪だった", "存在が罪だったんだ", "存在が重荷だった", "存在が重荷だったんだ",
    "存在がお荷物だった", "存在がお荷物だったんだ", "存在が無駄だった", "存在が無駄だったんだ",
    "存在が徒だった", "存在が徒だったんだ", "存在が害だった", "存在が害だったんだ",
    "存在が毒だった", "存在が毒だったんだ", "存在が害悪だった", "存在が害悪だったんだ",
    "存在が害毒だった", "存在が害毒だったんだ", "存在が疫病だった", "存在が疫病だったんだ",
    "存在が腫瘍だった", "存在が腫瘍だったんだ", "存在が汚点だった", "存在が汚点だったんだ",
    "存在が汚染だった", "存在が汚染だったんだ", "存在が腐敗だった", "存在が腐敗だったんだ",
    "存在が癌だった", "存在が癌だったんだ", "存在が癌細胞だった", "存在が癌細胞だったんだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
