// Pass CCLXIV: EN regret/opened-in-error + wrong-tab + JA 後悔/誤タブ/不要物宣告 (pass CCLXIV)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXIV: close-tab coverage', () => {
  test.each([
    "i wish i had never opened it", "i wish i had never opened it sincerely", "i wish i had never opened it bitterly", "i wish i had never opened it to this day",
    "i wish i had never opened it for eternity", "i wish i had never opened it for all eternity", "i wish i had never opened it with all my might", "i wish i had never opened it in my soul",
    "i wish i had never opened this tab truly", "i wish i had never opened this tab greatly", "i wish i had never opened this tab every single day", "i wish i had never opened this tab still",
    "i wish i had never opened this tab for the rest of my life", "i wish i had never opened this tab with all my heart", "i wish i had never opened this tab from the depths of my soul", "i wish i had never opened this tab in my marrow",
    "i wish i never opened it deeply", "i wish i never opened it terribly", "i wish i never opened it daily", "i wish i never opened it forever",
    "i wish i never opened it for all time", "i wish i never opened it with all my being", "i wish i never opened it in my heart", "i wish i never opened this tab honestly",
    "i wish i never opened this tab so much", "i wish i never opened this tab sorely", "i wish i never opened this tab even now", "i wish i never opened this tab for the rest of my days",
    "i wish i never opened this tab with every fiber of my being", "i wish i never opened this tab from the bottom of my heart", "i wish i never opened this tab in my gut", "i wish i never clicked it really",
    "i wish i never clicked it immensely", "i wish i never clicked it every day", "i wish i never clicked it always", "i wish i never clicked it for the rest of time",
    "i wish i never clicked it with all my soul", "i wish i never clicked it in my bones", "i wish i never clicked on it", "i wish i never clicked on it sincerely",
    "i wish i never clicked on it bitterly", "i wish i never clicked on it to this day", "i wish i never clicked on it for eternity", "i wish i never clicked on it for all eternity",
    "i wish i never clicked on it with all my might", "i wish i never clicked on it in my soul", "i wish i never clicked that link truly", "i wish i never clicked that link greatly",
    "i wish i never clicked that link every single day", "i wish i never clicked that link still", "i wish i never clicked that link for the rest of my life", "i wish i never clicked that link with all my heart",
    "i wish i never clicked that link from the depths of my soul", "i wish i never clicked that link in my marrow", "i wish i never clicked the link deeply", "i wish i never clicked the link terribly",
    "i wish i never clicked the link daily", "i wish i never clicked the link forever", "i wish i never clicked the link for all time", "i wish i never clicked the link with all my being",
    "i wish i never clicked the link in my heart", "i wish i never visited it honestly", "i wish i never visited it so much", "i wish i never visited it sorely",
    "i wish i never visited it even now", "i wish i never visited it for the rest of my days", "i wish i never visited it with every fiber of my being", "i wish i never visited it from the bottom of my heart",
    "i wish i never visited it in my gut", "i wish i never went there really", "i wish i never went there immensely", "i wish i never went there every day",
    "i wish i never went there always", "i wish i never went there for the rest of time", "i wish i never went there with all my soul", "i wish i never went there in my bones",
    "i wish i never opened this page", "i wish i never opened this page sincerely", "i wish i never opened this page bitterly", "i wish i never opened this page to this day",
    "i wish i never opened this page for eternity", "i wish i never opened this page for all eternity", "i wish i never opened this page with all my might", "i wish i never opened this page in my soul",
    "i wish i never opened the page truly", "i wish i never opened the page greatly", "i wish i never opened the page every single day", "i wish i never opened the page still",
    "i wish i never opened the page for the rest of my life", "i wish i never opened the page with all my heart", "i wish i never opened the page from the depths of my soul", "i wish i never opened the page in my marrow",
    "i wish i had never opened the page deeply", "i wish i had never opened the page terribly", "i wish i had never opened the page daily", "i wish i had never opened the page forever",
    "i wish i had never opened the page for all time", "i wish i had never opened the page with all my being", "i wish i had never opened the page in my heart", "i wish it had never been opened honestly",
    "i wish it had never been opened so much", "i wish it had never been opened sorely", "i wish it had never been opened even now", "i wish it had never been opened for the rest of my days",
    "i wish it had never been opened with every fiber of my being", "i wish it had never been opened from the bottom of my heart", "i wish it had never been opened in my gut", "i wish it was never opened really",
    "i wish it was never opened immensely", "i wish it was never opened every day", "i wish it was never opened always", "i wish it was never opened for the rest of time",
    "i wish it was never opened with all my soul", "i wish it was never opened in my bones", "i wish it were never opened", "i wish it were never opened sincerely",
    "i wish it were never opened bitterly", "i wish it were never opened to this day", "i wish it were never opened for eternity", "i wish it were never opened for all eternity",
    "i wish it were never opened with all my might", "i wish it were never opened in my soul", "i wish it never existed truly", "i wish it never existed greatly",
    "i wish it never existed every single day", "i wish it never existed still", "i wish it never existed for the rest of my life", "i wish it never existed with all my heart",
    "i wish it never existed from the depths of my soul", "i wish it never existed in my marrow", "i wish it had never existed deeply", "i wish it had never existed terribly",
    "i wish it had never existed daily", "i wish it had never existed forever", "i wish it had never existed for all time", "i wish it had never existed with all my being",
    "i wish it had never existed in my heart", "i wish it was never created honestly", "i wish it was never created so much", "i wish it was never created sorely",
    "i wish it was never created even now", "i wish it was never created for the rest of my days", "i wish it was never created with every fiber of my being", "i wish it was never created from the bottom of my heart",
    "i wish it was never created in my gut", "i wish it was never made really", "i wish it was never made immensely", "i wish it was never made every day",
    "i wish it was never made always", "i wish it was never made for the rest of time", "i wish it was never made with all my soul", "i wish it was never made in my bones",
    "i wish it was never born", "i wish it was never born sincerely", "i wish it was never born bitterly", "i wish it was never born to this day",
    "i wish it was never born for eternity", "i wish it was never born for all eternity", "i wish it was never born with all my might", "i wish it was never born in my soul",
    "i wish it was never a thing truly", "i wish it was never a thing greatly", "i wish it was never a thing every single day", "i wish it was never a thing still",
    "i wish it was never a thing for the rest of my life", "i wish it was never a thing with all my heart", "i wish it was never a thing from the depths of my soul", "i wish it was never a thing in my marrow",
    "i regret opening it deeply", "i regret opening it terribly", "i regret opening it daily", "i regret opening it forever",
    "i regret opening it for all time", "i regret opening it with all my being", "i regret opening it in my heart", "i regret opening this tab honestly",
    "i regret opening this tab so much", "i regret opening this tab sorely", "i regret opening this tab even now", "i regret opening this tab for the rest of my days",
    "i regret opening this tab with every fiber of my being", "i regret opening this tab from the bottom of my heart", "i regret opening this tab in my gut", "i regret opening this page really",
    "i regret opening this page immensely", "i regret opening this page every day", "i regret opening this page always", "i regret opening this page for the rest of time",
    "i regret opening this page with all my soul", "i regret opening this page in my bones", "i regret clicking it", "i regret clicking it sincerely",
    "i regret clicking it bitterly", "i regret clicking it to this day", "i regret clicking it for eternity", "i regret clicking it for all eternity",
    "i regret clicking it with all my might", "i regret clicking it in my soul", "i regret clicking on it truly", "i regret clicking on it greatly",
    "i regret clicking on it every single day", "i regret clicking on it still", "i regret clicking on it for the rest of my life", "i regret clicking on it with all my heart",
    "i regret clicking on it from the depths of my soul", "i regret clicking on it in my marrow", "i regret clicking that link deeply", "i regret clicking that link terribly",
    "i regret clicking that link daily", "i regret clicking that link forever", "i regret clicking that link for all time", "i regret clicking that link with all my being",
    "i regret clicking that link in my heart", "i regret clicking the link honestly", "i regret clicking the link so much", "i regret clicking the link sorely",
    "i regret clicking the link even now", "i regret clicking the link for the rest of my days", "i regret clicking the link with every fiber of my being", "i regret clicking the link from the bottom of my heart",
    "i regret clicking the link in my gut", "i regret visiting it really", "i regret visiting it immensely", "i regret visiting it every day",
    "i regret visiting it always", "i regret visiting it for the rest of time", "i regret visiting it with all my soul", "i regret visiting it in my bones",
    "i regret going there", "i regret going there sincerely", "i regret going there bitterly", "i regret going there to this day",
    "i regret going there for eternity", "i regret going there for all eternity", "i regret going there with all my might", "i regret going there in my soul",
    "i regret ever opening it truly", "i regret ever opening it greatly", "i regret ever opening it every single day", "i regret ever opening it still",
    "i regret ever opening it for the rest of my life", "i regret ever opening it with all my heart", "i regret ever opening it from the depths of my soul", "i regret ever opening it in my marrow",
    "i regret ever clicking it deeply", "i regret ever clicking it terribly", "i regret ever clicking it daily", "i regret ever clicking it forever",
    "i regret ever clicking it for all time", "i regret ever clicking it with all my being", "i regret ever clicking it in my heart", "i regret ever visiting it honestly",
    "i regret ever visiting it so much", "i regret ever visiting it sorely", "i regret ever visiting it even now", "i regret ever visiting it for the rest of my days",
    "i regret ever visiting it with every fiber of my being", "i regret ever visiting it from the bottom of my heart", "i regret ever visiting it in my gut", "i deeply regret opening it really",
    "i deeply regret opening it immensely", "i deeply regret opening it every day", "i deeply regret opening it always", "i deeply regret opening it for the rest of time",
    "i deeply regret opening it with all my soul", "i deeply regret opening it in my bones", "i deeply regret clicking it", "i deeply regret clicking it sincerely",
    "i deeply regret clicking it bitterly", "i deeply regret clicking it to this day", "i deeply regret clicking it for eternity", "i deeply regret clicking it for all eternity",
    "i deeply regret clicking it with all my might", "i deeply regret clicking it in my soul", "i sincerely regret opening it truly", "i sincerely regret opening it greatly",
    "i sincerely regret opening it every single day", "i sincerely regret opening it still", "i sincerely regret opening it for the rest of my life", "i sincerely regret opening it with all my heart",
    "i sincerely regret opening it from the depths of my soul", "i sincerely regret opening it in my marrow", "i truly regret opening it deeply", "i truly regret opening it terribly",
    "i truly regret opening it daily", "i truly regret opening it forever", "i truly regret opening it for all time", "i truly regret opening it with all my being",
    "i truly regret opening it in my heart", "i sorely regret opening it honestly", "i sorely regret opening it so much", "i sorely regret opening it sorely",
    "i sorely regret opening it even now", "i sorely regret opening it for the rest of my days", "i sorely regret opening it with every fiber of my being", "i sorely regret opening it from the bottom of my heart",
    "i sorely regret opening it in my gut", "i bitterly regret opening it really", "i bitterly regret opening it immensely", "i bitterly regret opening it every day",
    "i bitterly regret opening it always", "i bitterly regret opening it for the rest of time", "i bitterly regret opening it with all my soul", "i bitterly regret opening it in my bones",
    "i regret it", "i regret it sincerely", "i regret it bitterly", "i regret it to this day",
    "i regret it for eternity", "i regret it for all eternity", "i regret it with all my might", "i regret it in my soul",
    "i regret this tab truly", "i regret this tab greatly", "i regret this tab every single day", "i regret this tab still",
    "i regret this tab for the rest of my life", "i regret this tab with all my heart", "i regret this tab from the depths of my soul", "i regret this tab in my marrow",
    "i regret this page deeply", "i regret this page terribly", "i regret this page daily", "i regret this page forever",
    "i regret this page for all time", "i regret this page with all my being", "i regret this page in my heart", "i regret it deeply truly",
    "i regret it deeply greatly", "i regret it deeply every single day", "i regret it deeply still", "i regret it deeply for the rest of my life",
    "i regret it deeply with all my heart", "i regret it deeply from the depths of my soul", "i regret it deeply in my marrow", "i regret it bitterly sincerely",
    "i regret it bitterly bitterly", "i regret it bitterly to this day", "i regret it bitterly for eternity", "i regret it bitterly for all eternity",
    "i regret it bitterly with all my might", "i regret it bitterly in my soul", "i regret it sorely really", "i regret it sorely immensely",
    "i regret it sorely every day", "i regret it sorely always", "i regret it sorely for the rest of time", "i regret it sorely with all my soul",
    "i regret it sorely in my bones", "i regret it so much honestly", "i regret it so much so much", "i regret it so much sorely",
    "i regret it so much even now", "i regret it so much for the rest of my days", "i regret it so much with every fiber of my being", "i regret it so much from the bottom of my heart",
    "i regret it so much in my gut", "i regret it greatly deeply", "i regret it greatly terribly", "i regret it greatly daily",
    "i regret it greatly forever", "i regret it greatly for all time", "i regret it greatly with all my being", "i regret it greatly in my heart",
    "i regret it immensely truly", "i regret it immensely greatly", "i regret it immensely every single day", "i regret it immensely still",
    "i regret it immensely for the rest of my life", "i regret it immensely with all my heart", "i regret it immensely from the depths of my soul", "i regret it immensely in my marrow",
    "i regret it terribly sincerely", "i regret it terribly bitterly", "i regret it terribly to this day", "i regret it terribly for eternity",
    "i regret it terribly for all eternity", "i regret it terribly with all my might", "i regret it terribly in my soul", "i regret it profoundly truly",
    "i regret it profoundly greatly", "i regret it profoundly every single day", "i regret it profoundly still", "i regret it profoundly for the rest of my life",
    "i regret it profoundly with all my heart", "i regret it profoundly from the depths of my soul", "i regret it profoundly in my marrow", "i rue the day i opened it deeply",
    "i rue the day i opened it terribly", "i rue the day i opened it daily", "i rue the day i opened it forever", "i rue the day i opened it for all time",
    "i rue the day i opened it with all my being", "i rue the day i opened it in my heart", "i rue opening it honestly", "i rue opening it so much",
    "i rue opening it sorely", "i rue opening it even now", "i rue opening it for the rest of my days", "i rue opening it with every fiber of my being",
    "i rue opening it from the bottom of my heart", "i rue opening it in my gut", "i rue the day i clicked it really", "i rue the day i clicked it immensely",
    "i rue the day i clicked it every day", "i rue the day i clicked it always", "i rue the day i clicked it for the rest of time", "i rue the day i clicked it with all my soul",
    "i rue the day i clicked it in my bones", "i rue the moment i opened it", "i rue the moment i opened it sincerely", "i rue the moment i opened it bitterly",
    "i rue the moment i opened it to this day", "i rue the moment i opened it for eternity", "i rue the moment i opened it for all eternity", "i rue the moment i opened it with all my might",
    "i rue the moment i opened it in my soul", "i rue the moment i clicked it truly", "i rue the moment i clicked it greatly", "i rue the moment i clicked it every single day",
    "i rue the moment i clicked it still", "i rue the moment i clicked it for the rest of my life", "i rue the moment i clicked it with all my heart", "i rue the moment i clicked it from the depths of my soul",
    "i rue the moment i clicked it in my marrow", "i rue the day it was opened deeply", "i rue the day it was opened terribly", "i rue the day it was opened daily",
    "i rue the day it was opened forever", "i rue the day it was opened for all time", "i rue the day it was opened with all my being", "i rue the day it was opened in my heart",
    "i lament opening it honestly", "i lament opening it so much", "i lament opening it sorely", "i lament opening it even now",
    "i lament opening it for the rest of my days", "i lament opening it with every fiber of my being", "i lament opening it from the bottom of my heart", "i lament opening it in my gut",
    "i lament clicking it really", "i lament clicking it immensely", "i lament clicking it every day", "i lament clicking it always",
    "i lament clicking it for the rest of time", "i lament clicking it with all my soul", "i lament clicking it in my bones", "i lament the day i opened it",
    "i lament the day i opened it sincerely", "i lament the day i opened it bitterly", "i lament the day i opened it to this day", "i lament the day i opened it for eternity",
    "i lament the day i opened it for all eternity", "i lament the day i opened it with all my might", "i lament the day i opened it in my soul", "i lament the day i clicked it truly",
    "i lament the day i clicked it greatly", "i lament the day i clicked it every single day", "i lament the day i clicked it still", "i lament the day i clicked it for the rest of my life",
    "i lament the day i clicked it with all my heart", "i lament the day i clicked it from the depths of my soul", "i lament the day i clicked it in my marrow", "i bemoan opening it deeply",
    "i bemoan opening it terribly", "i bemoan opening it daily", "i bemoan opening it forever", "i bemoan opening it for all time",
    "i bemoan opening it with all my being", "i bemoan opening it in my heart", "i bemoan clicking it honestly", "i bemoan clicking it so much",
    "i bemoan clicking it sorely", "i bemoan clicking it even now", "i bemoan clicking it for the rest of my days", "i bemoan clicking it with every fiber of my being",
    "i bemoan clicking it from the bottom of my heart", "i bemoan clicking it in my gut", "i mourn the day i opened it really", "i mourn the day i opened it immensely",
    "i mourn the day i opened it every day", "i mourn the day i opened it always", "i mourn the day i opened it for the rest of time", "i mourn the day i opened it with all my soul",
    "i mourn the day i opened it in my bones", "i grieve opening it", "i grieve opening it sincerely", "i grieve opening it bitterly",
    "i grieve opening it to this day", "i grieve opening it for eternity", "i grieve opening it for all eternity", "i grieve opening it with all my might",
    "i grieve opening it in my soul", "i grieve the day i opened it truly", "i grieve the day i opened it greatly", "i grieve the day i opened it every single day",
    "i grieve the day i opened it still", "i grieve the day i opened it for the rest of my life", "i grieve the day i opened it with all my heart", "i grieve the day i opened it from the depths of my soul",
    "i grieve the day i opened it in my marrow", "i weep for having opened it deeply", "i weep for having opened it terribly", "i weep for having opened it daily",
    "i weep for having opened it forever", "i weep for having opened it for all time", "i weep for having opened it with all my being", "i weep for having opened it in my heart",
    "i despair having opened it honestly", "i despair having opened it so much", "i despair having opened it sorely", "i despair having opened it even now",
    "i despair having opened it for the rest of my days", "i despair having opened it with every fiber of my being", "i despair having opened it from the bottom of my heart", "i despair having opened it in my gut",
    "i despair of having opened it really", "i despair of having opened it immensely", "i despair of having opened it every day", "i despair of having opened it always",
    "i despair of having opened it for the rest of time", "i despair of having opened it with all my soul", "i despair of having opened it in my bones", "i despise having opened it",
    "i despise having opened it sincerely", "i despise having opened it bitterly", "i despise having opened it to this day", "i despise having opened it for eternity",
    "i despise having opened it for all eternity", "i despise having opened it with all my might", "i despise having opened it in my soul", "i loathe having opened it truly",
    "i loathe having opened it greatly", "i loathe having opened it every single day", "i loathe having opened it still", "i loathe having opened it for the rest of my life",
    "i loathe having opened it with all my heart", "i loathe having opened it from the depths of my soul", "i loathe having opened it in my marrow", "i hate having opened it deeply",
    "i hate having opened it terribly", "i hate having opened it daily", "i hate having opened it forever", "i hate having opened it for all time",
    "i hate having opened it with all my being", "i hate having opened it in my heart", "i hate that i opened it honestly", "i hate that i opened it so much",
    "i hate that i opened it sorely", "i hate that i opened it even now", "i hate that i opened it for the rest of my days", "i hate that i opened it with every fiber of my being",
    "i hate that i opened it from the bottom of my heart", "i hate that i opened it in my gut", "i hate that i clicked it really", "i hate that i clicked it immensely",
    "i hate that i clicked it every day", "i hate that i clicked it always", "i hate that i clicked it for the rest of time", "i hate that i clicked it with all my soul",
    "i hate that i clicked it in my bones", "i hate that i visited it", "i hate that i visited it sincerely", "i hate that i visited it bitterly",
    "i hate that i visited it to this day", "i hate that i visited it for eternity", "i hate that i visited it for all eternity", "i hate that i visited it with all my might",
    "i hate that i visited it in my soul", "i hate myself for opening it truly", "i hate myself for opening it greatly", "i hate myself for opening it every single day",
    "i hate myself for opening it still", "i hate myself for opening it for the rest of my life", "i hate myself for opening it with all my heart", "i hate myself for opening it from the depths of my soul",
    "i hate myself for opening it in my marrow", "i hate myself for clicking it deeply", "i hate myself for clicking it terribly", "i hate myself for clicking it daily",
    "i hate myself for clicking it forever", "i hate myself for clicking it for all time", "i hate myself for clicking it with all my being", "i hate myself for clicking it in my heart",
    "i curse the day i opened it honestly", "i curse the day i opened it so much", "i curse the day i opened it sorely", "i curse the day i opened it even now",
    "i curse the day i opened it for the rest of my days", "i curse the day i opened it with every fiber of my being", "i curse the day i opened it from the bottom of my heart", "i curse the day i opened it in my gut",
    "i curse the moment i opened it really", "i curse the moment i opened it immensely", "i curse the moment i opened it every day", "i curse the moment i opened it always",
    "i curse the moment i opened it for the rest of time", "i curse the moment i opened it with all my soul", "i curse the moment i opened it in my bones", "i curse the day i clicked it",
    "i curse the day i clicked it sincerely", "i curse the day i clicked it bitterly", "i curse the day i clicked it to this day", "i curse the day i clicked it for eternity",
    "i curse the day i clicked it for all eternity", "i curse the day i clicked it with all my might", "i curse the day i clicked it in my soul", "i curse myself for opening it truly",
    "i curse myself for opening it greatly", "i curse myself for opening it every single day", "i curse myself for opening it still", "i curse myself for opening it for the rest of my life",
    "i curse myself for opening it with all my heart", "i curse myself for opening it from the depths of my soul", "i curse myself for opening it in my marrow", "i curse myself for clicking it deeply",
    "i curse myself for clicking it terribly", "i curse myself for clicking it daily", "i curse myself for clicking it forever", "i curse myself for clicking it for all time",
    "i curse myself for clicking it with all my being", "i curse myself for clicking it in my heart", "i curse the hour i opened it honestly", "i curse the hour i opened it so much",
    "i curse the hour i opened it sorely", "i curse the hour i opened it even now", "i curse the hour i opened it for the rest of my days", "i curse the hour i opened it with every fiber of my being",
    "i curse the hour i opened it from the bottom of my heart", "i curse the hour i opened it in my gut", "i damn the day i opened it really", "i damn the day i opened it immensely",
    "i damn the day i opened it every day", "i damn the day i opened it always", "i damn the day i opened it for the rest of time", "i damn the day i opened it with all my soul",
    "i damn the day i opened it in my bones", "i damn the day i clicked it", "i damn the day i clicked it sincerely", "i damn the day i clicked it bitterly",
    "i damn the day i clicked it to this day", "i damn the day i clicked it for eternity", "i damn the day i clicked it for all eternity", "i damn the day i clicked it with all my might",
    "i damn the day i clicked it in my soul", "i condemn myself for opening it truly", "i condemn myself for opening it greatly", "i condemn myself for opening it every single day",
    "i condemn myself for opening it still", "i condemn myself for opening it for the rest of my life", "i condemn myself for opening it with all my heart", "i condemn myself for opening it from the depths of my soul",
    "i condemn myself for opening it in my marrow", "i kick myself for opening it deeply", "i kick myself for opening it terribly", "i kick myself for opening it daily",
    "i kick myself for opening it forever", "i kick myself for opening it for all time", "i kick myself for opening it with all my being", "i kick myself for opening it in my heart",
    "i kick myself for clicking it honestly", "i kick myself for clicking it so much", "i kick myself for clicking it sorely", "i kick myself for clicking it even now",
    "i kick myself for clicking it for the rest of my days", "i kick myself for clicking it with every fiber of my being", "i kick myself for clicking it from the bottom of my heart", "i kick myself for clicking it in my gut",
    "i kick myself for visiting it really", "i kick myself for visiting it immensely", "i kick myself for visiting it every day", "i kick myself for visiting it always",
    "i kick myself for visiting it for the rest of time", "i kick myself for visiting it with all my soul", "i kick myself for visiting it in my bones", "i beat myself up for opening it",
    "i beat myself up for opening it sincerely", "i beat myself up for opening it bitterly", "i beat myself up for opening it to this day", "i beat myself up for opening it for eternity",
    "i beat myself up for opening it for all eternity", "i beat myself up for opening it with all my might", "i beat myself up for opening it in my soul", "i beat myself up for clicking it truly",
    "i beat myself up for clicking it greatly", "i beat myself up for clicking it every single day", "i beat myself up for clicking it still", "i beat myself up for clicking it for the rest of my life",
    "i beat myself up for clicking it with all my heart", "i beat myself up for clicking it from the depths of my soul", "i beat myself up for clicking it in my marrow", "i could kick myself for opening it deeply",
    "i could kick myself for opening it terribly", "i could kick myself for opening it daily", "i could kick myself for opening it forever", "i could kick myself for opening it for all time",
    "i could kick myself for opening it with all my being", "i could kick myself for opening it in my heart", "i could kick myself for clicking it honestly", "i could kick myself for clicking it so much",
    "i could kick myself for clicking it sorely", "i could kick myself for clicking it even now", "i could kick myself for clicking it for the rest of my days", "i could kick myself for clicking it with every fiber of my being",
    "i could kick myself for clicking it from the bottom of my heart", "i could kick myself for clicking it in my gut", "i want to kick myself for opening it really", "i want to kick myself for opening it immensely",
    "i want to kick myself for opening it every day", "i want to kick myself for opening it always", "i want to kick myself for opening it for the rest of time", "i want to kick myself for opening it with all my soul",
    "i want to kick myself for opening it in my bones", "i blame myself for opening it", "i blame myself for opening it sincerely", "i blame myself for opening it bitterly",
    "i blame myself for opening it to this day", "i blame myself for opening it for eternity", "i blame myself for opening it for all eternity", "i blame myself for opening it with all my might",
    "i blame myself for opening it in my soul", "i blame myself for clicking it truly", "i blame myself for clicking it greatly", "i blame myself for clicking it every single day",
    "i blame myself for clicking it still", "i blame myself for clicking it for the rest of my life", "i blame myself for clicking it with all my heart", "i blame myself for clicking it from the depths of my soul",
    "i blame myself for clicking it in my marrow", "i fault myself for opening it deeply", "i fault myself for opening it terribly", "i fault myself for opening it daily",
    "i fault myself for opening it forever", "i fault myself for opening it for all time", "i fault myself for opening it with all my being", "i fault myself for opening it in my heart",
    "i berate myself for opening it honestly", "i berate myself for opening it so much", "i berate myself for opening it sorely", "i berate myself for opening it even now",
    "i berate myself for opening it for the rest of my days", "i berate myself for opening it with every fiber of my being", "i berate myself for opening it from the bottom of my heart", "i berate myself for opening it in my gut",
    "i berate myself for clicking it really", "i berate myself for clicking it immensely", "i berate myself for clicking it every day", "i berate myself for clicking it always",
    "i berate myself for clicking it for the rest of time", "i berate myself for clicking it with all my soul", "i berate myself for clicking it in my bones", "i scold myself for opening it",
    "i scold myself for opening it sincerely", "i scold myself for opening it bitterly", "i scold myself for opening it to this day", "i scold myself for opening it for eternity",
    "i scold myself for opening it for all eternity", "i scold myself for opening it with all my might", "i scold myself for opening it in my soul", "i chide myself for opening it truly",
    "opening it was a mistake", "opening this tab was a mistake", "opening this page was a mistake", "opening the page was a mistake",
    "opening it was the mistake", "opening it was the error", "opening it was the blunder", "opening it was the folly",
    "opening it was the misstep", "opening it was the fatal mistake", "opening it was the worst mistake", "opening it was the big mistake",
    "opening it was the huge mistake", "opening it was the grave mistake", "opening it was the terrible mistake", "opening it was the colossal mistake",
    "opening it was my mistake", "opening it was my error", "opening it was my blunder", "opening it was my folly",
    "opening it was my misstep", "opening it was my downfall", "opening it was my undoing", "it is not the right tab",
    "it was not the right tab", "i meant to open something else", "i meant to go somewhere else", "i meant to open a different tab",
    "i meant to go to a different site", "i meant to open another tab", "i meant to go to another site", "it opened by itself",
    "it opened on its own", "it opened by accident", "it opened accidentally", "it opened by mistake",
    "it opened unintentionally", "it opened itself", "it opened without me wanting it", "it opened without my consent",
    "it opened without my permission", "it opened without my intent", "開くんじゃなかったのだ", "開くんじゃなかったとせよ",
    "開くんじゃなかったであれ", "開くんじゃなかった本当だ", "開くべきじゃなかったと言っている", "開くべきじゃなかっただからよ",
    "開くべきじゃなかった間違いない", "開くべきではなかったと反省している", "開くべきではなかったからね", "開くべきではなかったはずだ",
    "開くべきでなかったんだぞ", "開くべきでなかったと反省している", "開くべきでなかったものだ", "開くべきでなかったてぞ",
    "開くべきでなかった本当だ", "開かなきゃよかったと言っている", "開かなきゃよかっただからよ", "開かなきゃよかった間違いない",
    "開かなければよかったと反省している", "開かなければよかったからね", "開かなければよかったはずだ", "開かなけりゃよかったんだぞ",
    "開かなけりゃよかったと反省している", "開かなけりゃよかったものだ", "開かなけりゃよかったてぞ", "開かなけりゃよかった本当だ",
    "開かなくてよかったと反省している", "開かなくてよかったからね", "開かなくてよかったはずだ", "開くんだったかんだぞ",
    "開くんだったかと反省している", "開くんだったかものだ", "開くんだったかてぞ", "開くんだったか確かだ",
    "開いてしまったのだ", "開いてしまったと言っている", "開いてしまったからだ", "開いてしまったはずだ",
    "開いてもうたんだよ", "開いてもうたと悔やむ", "開いてもうたください", "開いてもうたてな",
    "開いてもうた明白だ", "開いちゃったな", "開いちゃったと言った", "開いちゃったからぞ",
    "開いちゃったわけぞ", "開いちまったんだ", "開いちまったと悔やんでいる", "開いちまったくれ",
    "開いちまったであれ", "開いちまった明らかだ", "開いてしまったんだと後悔している", "開いてしまったんだということだ",
    "開いてしまったんだだからよ", "開いてしまったんだべきだった", "開いちゃったんだぜ", "開いちゃったんだという話だ",
    "開いちゃったんだからね", "開いちゃったんだわけよ", "開いたのが間違いだったのだ", "開いたのが間違いだったとせよ",
    "開いたのが間違いだったであれ", "開いたのが間違いだった本当だ", "開いたのが失敗だったのだよ", "開いたのが失敗だったと決めた",
    "開いたのが失敗だっただからな", "開いたのが失敗だったべきだ", "開いたのが過ちだったんだぞ", "開いたのが過ちだったと反省している",
    "開いたのが過ちだったものだ", "開いたのが過ちだったてよ", "開いたのが過ちだった確かだ", "開いたのが愚かだったのだ",
    "開いたのが愚かだったと言っている", "開いたのが愚かだっただからな", "開いたのが愚かだったべきだ", "開いたのがバカだったんだぞ",
    "開いたのがバカだったと反省している", "開いたのがバカだったものだ", "開いたのがバカだったてよ", "開いたのがバカだった確かだ",
    "開いたことが間違いだのだ", "開いたことが間違いだと言っている", "開いたことが間違いだからだ", "開いたことが間違いだはずだ",
    "開いたことが失敗だんだよ", "開いたことが失敗だと悔やむ", "開いたことが失敗だください", "開いたことが失敗だてな",
    "開いたことが失敗だ明白だ", "開いたのは間違いだな", "開いたのは間違いだと言った", "開いたのは間違いだからぞ",
    "開いたのは間違いだわけぞ", "開いたのは失敗だんだ", "開いたのは失敗だと悔やんでいる", "開いたのは失敗だくれ",
    "開いたのは失敗だであれ", "開いたのは失敗だ明らかだ", "開いたのは過ちだわ", "開いたのは過ちだという話だ",
    "開いたのは過ちだからね", "開いたのは過ちだわけよ", "開いたのは愚かだ", "開いたのは愚かだと悔いる",
    "開いたのは愚かだとせよ", "開いたのは愚かだであれ", "開いたのは愚かだ明らかだ", "開いたのはバカだわ",
    "開いたのはバカだという話だ", "開いたのはバカだからね", "開いたのはバカだわけよ", "開いたのは誤りだ",
    "開いたのは誤りだと悔いる", "開いたのは誤りだとせよ", "開いたのは誤りだであった", "開いたのは誤りだ間違いない",
    "開いたのは失態だよ", "開いたのは失態だと思っている", "開いたのは失態だからよ", "開いたのは失態だってぞ",
    "開いたのは失態だ冗談抜きだ", "開いたのはミスだと悔いている", "開いたのはミスだという判定だ", "開いたのはミスだのである",
    "開いたのはミスだに決まっている", "開いたのは不始末だぜ", "開いたのは不始末だと思った", "開いたのは不始末だからな",
    "開いたのは不始末だってよ", "開いたのは不始末だガチだ", "開いたのは大失敗だと後悔する", "開いたのは大失敗だという結論だ",
    "開いたのは大失敗だのでな", "開いたのは大失敗だに違いない", "開いたのは大間違いだぞ", "開いたのは大間違いだと思う",
    "開いたのは大間違いだことか", "開いたのは大間違いだってな", "開いたのは大間違いだマジだ", "開いたのは致命的だと後悔している",
    "開いたのは致命的だということだ", "開いたのは致命的だだからよ", "開いたのは致命的だべきだった", "開いたのは命取りだんだな",
    "開いたのは命取りだと反省する", "開いたのは命取りだことだ", "開いたのは命取りだてぞ", "開いたのは命取りだ本当だ",
    "開いたのが命取りだのだよ", "開いたのが命取りだと決めた", "開いたのが命取りだだからな", "開いたのが命取りだべきだ",
    "開いたのが敗因だんだぞ", "開いたのが敗因だと反省している", "開いたのが敗因だものだ", "開いたのが敗因だてよ",
    "開いたのが敗因だ確かだ", "開いたのが敗北だのだ", "開いたのが敗北だと言っている", "開いたのが敗北だからだ",
    "開いたのが敗北だはずだ", "開いたのが終わりの始まりだんだよ", "開いたのが終わりの始まりだと悔やむ", "開いたのが終わりの始まりだください",
    "開いたのが終わりの始まりだてな", "開いたのが終わりの始まりだ明白だ", "開いたのが運の尽きだな", "開いたのが運の尽きだと言った",
    "開いたのが運の尽きだからぞ", "開いたのが運の尽きだわけぞ", "開いたのが悪手だんだ", "開いたのが悪手だと悔やんでいる",
    "開いたのが悪手だくれ", "開いたのが悪手だであれ", "開いたのが悪手だ明らかだ", "開いたのが大悪手だわ",
    "開いたのが大悪手だという話だ", "開いたのが大悪手だからね", "開いたのが大悪手だわけよ", "開いたのが最悪だ",
    "開いたのが最悪だと悔いる", "開いたのが最悪だとせよ", "開いたのが最悪だであった", "開いたのが最悪だ間違いない",
    "開いたのが最悪の一手だよ", "開いたのが最悪の一手だと思っている", "開いたのが最悪の一手だからよ", "開いたのが最悪の一手だってぞ",
    "開いたのが最悪の一手だ冗談抜きだ", "開いたのが墓穴だと悔いている", "開いたのが墓穴だという判定だ", "開いたのが墓穴だのである",
    "開いたのが墓穴だに決まっている", "開いたのが墓穴を掘ったぜ", "開いたのが墓穴を掘ったと思った", "開いたのが墓穴を掘ったからな",
    "開いたのが墓穴を掘ったってよ", "開いたのが墓穴を掘ったガチだ", "開いた時点で負けだと後悔する", "開いた時点で負けだという結論だ",
    "開いた時点で負けだのでな", "開いた時点で負けだに違いない", "開いた時点で終わりだぞ", "開いた時点で終わりだと思う",
    "開いた時点で終わりだことか", "開いた時点で終わりだってな", "開いた時点で終わりだマジだ", "開いた時点で詰みだと後悔している",
    "開いた時点で詰みだということだ", "開いた時点で詰みだだからよ", "開いた時点で詰みだべきだった", "開いた時点でおしまいだんだな",
    "開いた時点でおしまいだと反省する", "開いた時点でおしまいだことだ", "開いた時点でおしまいだてぞ", "開いた時点でおしまいだ本当だ",
    "開いた時点で手遅れだのだよ", "開いた時点で手遅れだと決めた", "開いた時点で手遅れだだからな", "開いた時点で手遅れだべきだ",
    "開いた時点で取り返しがつかないんだな", "開いた時点で取り返しがつかないと思った", "開いた時点で取り返しがつかないのでな", "開いた時点で取り返しがつかないに違いない",
    "開いた時点でもう遅いぞ", "開いた時点でもう遅いと思う", "開いた時点でもう遅いことか", "開いた時点でもう遅いってな",
    "開いた時点でもう遅い本当だ", "開いた時点でもう終わりだのだよ", "開いた時点でもう終わりだと決めた", "開いた時点でもう終わりだだからな",
    "開いた時点でもう終わりだべきだ", "開いた時点で終了だんだぞ", "開いた時点で終了だと反省している", "開いた時点で終了だものだ",
    "開いた時点で終了だてよ", "開いた時点で終了だ確かだ", "開いた時点で詰んでるのだよ", "開いた時点で詰んでると決めた",
    "開いた時点で詰んでるだからな", "開いた時点で詰んでるべきだった", "開いた瞬間に負けだんだな", "開いた瞬間に負けだと反省する",
    "開いた瞬間に負けだことだ", "開いた瞬間に負けだてぞ", "開いた瞬間に負けだ本当だ", "開いた瞬間に終わりだのだよ",
    "開いた瞬間に終わりだと決めた", "開いた瞬間に終わりだだからな", "開いた瞬間に終わりだべきだ", "開いた瞬間に詰みだんだぞ",
    "開いた瞬間に詰みだと反省している", "開いた瞬間に詰みだものだ", "開いた瞬間に詰みだてよ", "開いた瞬間に詰みだ確かだ",
    "開いた瞬間に手遅れだのだ", "開いた瞬間に手遅れだと言っている", "開いた瞬間に手遅れだからだ", "開いた瞬間に手遅れだはずだ",
    "開いた瞬間に終了だんだよ", "開いた瞬間に終了だと悔やむ", "開いた瞬間に終了だください", "開いた瞬間に終了だてな",
    "開いた瞬間に終了だ明白だ", "開いた瞬間に敗北だな", "開いた瞬間に敗北だと言った", "開いた瞬間に敗北だからぞ",
    "開いた瞬間に敗北だわけぞ", "見てしまったんだよ", "見てしまったと悔やむ", "見てしまったことか",
    "見てしまったってな", "見てしまったマジだ", "見ちゃったと後悔する", "見ちゃったくれ",
    "見ちゃったであれ", "見ちゃった明らかだ", "見ちまったのだ", "見ちまったという結論だ",
    "見ちまったのでな", "見ちまったに違いない", "見るんじゃなかったぜ", "見るんじゃなかったという話だ",
    "見るんじゃなかったからだ", "見るんじゃなかったはずだ", "見るべきじゃなかったんだよ", "見るべきじゃなかったと悔やむ",
    "見るべきじゃなかったください", "見るべきじゃなかったてよ", "見るべきじゃなかった確かだ", "見なきゃよかったのだ",
    "見なきゃよかったと言っている", "見なきゃよかっただからな", "見なきゃよかったべきだ", "見なければよかったんだぞ",
    "見なければよかったと反省している", "見なければよかったものだ", "見なければよかったてぞ", "見なければよかった本当だ",
    "踏んでしまったと後悔している", "踏んでしまったとせよ", "踏んでしまったであった", "踏んでしまった間違いない",
    "踏んじゃったわ", "踏んじゃったと決めた", "踏んじゃっただからな", "踏んじゃったべきだ",
    "踏むんじゃなかったんだな", "踏むんじゃなかったと反省する", "踏むんじゃなかったからね", "踏むんじゃなかったわけよ",
    "踏むべきじゃなかった", "踏むべきじゃなかったと悔いる", "踏むべきじゃなかったとせよ", "踏むべきじゃなかったであれ",
    "踏むべきじゃなかった明らかだ", "辿り着いてしまったわ", "辿り着いてしまったという話だ", "辿り着いてしまったからね",
    "辿り着いてしまったわけよ", "辿り着いちゃった", "辿り着いちゃったと悔いる", "辿り着いちゃったとせよ",
    "辿り着いちゃったであった", "辿り着いちゃった間違いない", "辿り着くんじゃなかったよ", "辿り着くんじゃなかったと思っている",
    "辿り着くんじゃなかったからね", "辿り着くんじゃなかったわけよ", "来てしまった", "来てしまったと悔いる",
    "来てしまったとせよ", "来てしまったであった", "来てしまった間違いない", "来ちゃったよ",
    "来ちゃったと思っている", "来ちゃったからよ", "来ちゃったってぞ", "来ちゃった冗談抜きだ",
    "来るんじゃなかったと悔いている", "来るんじゃなかったという判定だ", "来るんじゃなかったであった", "来るんじゃなかった間違いない",
    "来るべきじゃなかったと悔いている", "来るべきじゃなかったものだ", "来るべきじゃなかったてぞ", "来るべきじゃなかった冗談抜きだ",
    "入ってしまったと悔いている", "入ってしまったという判定だ", "入ってしまったのである", "入ってしまったに決まっている",
    "入っちゃったぜ", "入っちゃったと思った", "入っちゃったからな", "入っちゃったってよ",
    "入っちゃったガチだ", "入るんじゃなかったと後悔する", "入るんじゃなかったという結論だ", "入るんじゃなかったのである",
    "入るんじゃなかったに決まっている", "迷い込んでしまったぜ", "迷い込んでしまったと思った", "迷い込んでしまったからな",
    "迷い込んでしまったってよ", "迷い込んでしまったガチだ", "迷い込んじゃったと後悔する", "迷い込んじゃったという結論だ",
    "迷い込んじゃったのでな", "迷い込んじゃったに違いない", "迷い込むんじゃなかったぞ", "迷い込むんじゃなかったと思う",
    "迷い込むんじゃなかったからな", "迷い込むんじゃなかったってよ", "迷い込むんじゃなかったガチだ", "訪れてしまったと後悔する",
    "訪れてしまったという結論だ", "訪れてしまったのでな", "訪れてしまったに違いない", "訪れちゃったぞ",
    "訪れちゃったと思う", "訪れちゃったことか", "訪れちゃったってな", "訪れちゃったマジだ",
    "訪れるんじゃなかったと後悔している", "訪れるんじゃなかったということだ", "訪れるんじゃなかったのでな", "訪れるんじゃなかったに違いない",
    "アクセスしてしまったぞ", "アクセスしてしまったと思う", "アクセスしてしまったことか", "アクセスしてしまったってな",
    "アクセスしてしまったマジだ", "アクセスしちゃったと後悔している", "アクセスしちゃったということだ", "アクセスしちゃっただからよ",
    "アクセスしちゃったべきだった", "アクセスするんじゃなかったんだな", "アクセスするんじゃなかったと反省する", "アクセスするんじゃなかったことだ",
    "アクセスするんじゃなかったってな", "アクセスするんじゃなかったマジだ", "クリックしてしまったと後悔する", "クリックしてしまったくれ",
    "クリックしてしまったであれ", "クリックしてしまった明らかだ", "クリックしちゃったな", "クリックしちゃったということだ",
    "クリックしちゃっただからよ", "クリックしちゃったべきだった", "クリックするんじゃなかったんだな", "クリックするんじゃなかったと反省する",
    "クリックするんじゃなかったことだ", "クリックするんじゃなかったってな", "クリックするんじゃなかったマジだ", "タップしてしまったと後悔する",
    "タップしてしまったくれ", "タップしてしまったであれ", "タップしてしまった明らかだ", "タップしちゃったな",
    "タップしちゃったということだ", "タップしちゃっただからよ", "タップしちゃったべきだった", "タップするんじゃなかったんだな",
    "タップするんじゃなかったと反省する", "タップするんじゃなかったことだ", "タップするんじゃなかったってな", "タップするんじゃなかったマジだ",
    "押してしまったと後悔する", "押してしまったくれ", "押してしまったであれ", "押してしまった明らかだ",
    "押しちゃったな", "押しちゃったということだ", "押しちゃっただからよ", "押しちゃったべきだった",
    "押すんじゃなかったぞ", "押すんじゃなかったと思った", "押すんじゃなかったからぞ", "押すんじゃなかったわけぞ",
    "触ってしまったんだ", "触ってしまったと悔やんでいる", "触ってしまったくれ", "触ってしまったであれ",
    "触ってしまった明らかだ", "触っちゃったわ", "触っちゃったという話だ", "触っちゃったからね",
    "触っちゃったわけよ", "触るんじゃなかった", "触るんじゃなかったと悔いる", "触るんじゃなかったとせよ",
    "触るんじゃなかったであれ", "触るんじゃなかった明らかだ", "こいつは間違ったタブだな", "こいつは間違ったタブだ間違いない",
    "こいつは間違ったタブだべきだ", "こいつは違うタブだと判定した", "こいつは違うタブだからな", "こいつは違うんだぜ",
    "こいつは違うんだとせよ", "こいつは違うんだてよ", "こいつは求めてないタブだと思っている", "こいつは求めてないタブだ本当だ",
    "こいつは望んでないタブだんだよ", "こいつは望んでないタブだという結論だ", "こいつは望んでないタブだのでな", "こいつは欲してないタブだな",
    "こいつは欲してないタブだ間違いない", "こいつは欲してないタブだべきだ", "こいつは要らないタブだと判定した", "こいつは要らないタブだからな",
    "こいつはいらないタブだぜ", "こいつはいらないタブだとせよ", "こいつはいらないタブだてよ", "こいつは不要なタブだと思っている",
    "こいつは不要なタブだ本当だ", "こいつは不要だんだよ", "こいつは不要だという結論だ", "こいつは不要だのでな",
    "こいつは要らないと思った", "こいつは要らないマジだ", "こいつはいらないな", "こいつはいらない確かだ",
    "こいつは要らんぜ", "こいつは要らんとせよ", "こいつは要らんてよ", "こいつはいらんと言った",
    "こいつはいらんマジだ", "こいつは不要物だんだぞ", "こいつは不要物だという判定だ", "こいつは不要物だのである",
    "こいつはお荷物だと思う", "こいつはお荷物だ明らかだ", "こいつは無用だ", "こいつは無用だと決めた",
    "こいつは無用だからよ", "こいつは無用物だよ", "こいつは無用物だに違いない", "こいつは無用物だってな",
    "こいつは無用の長物だと言った", "こいつは無用の長物だマジだ", "こいつは余計だんだぞ", "こいつは余計だという判定だ",
    "こいつは余計だのである", "こいつは余計なタブだと思う", "こいつは余計なタブだ明らかだ", "こいつは余分だ",
    "こいつは余分だと決めた", "こいつは余分だからよ", "こいつは余分なタブだよ", "こいつは余分なタブだに違いない",
    "こいつは余分なタブだってな", "こいつは邪魔だと言った", "こいつは邪魔だマジだ", "こいつは邪魔なタブだんだぞ",
    "こいつは邪魔なタブだという判定だ", "こいつは邪魔なタブだのである", "こいつは邪魔物だと思う", "こいつは邪魔物だ明らかだ",
    "こいつは目障りだ", "こいつは目障りだと決めた", "こいつは目障りだからよ", "こいつは目障りなタブだよ",
    "こいつは目障りなタブだに違いない", "こいつは目障りなタブだってな", "こいつは煩わしいと言った", "こいつは煩わしいマジだ",
    "こいつはうざいんだぞ", "こいつはうざいという判定だ", "こいつはうざいのである", "こいつはウザいと思う",
    "こいつはウザい明らかだ", "こいつはうざったい", "こいつはうざったいと決めた", "こいつはうざったいからよ",
    "こいつは鬱陶しいよ", "こいつは鬱陶しいに違いない", "こいつは鬱陶しいってな", "こいつは五月蝿いと言った",
    "こいつは五月蝿いマジだ", "こいつは五月蝿いタブだんだぞ", "こいつは五月蝿いタブだという判定だ", "こいつは五月蝿いタブだのである",
    "こいつは厄介だと思う", "こいつは厄介だ明らかだ", "こいつは厄介なタブだ", "こいつは厄介なタブだと決めた",
    "こいつは厄介なタブだからよ", "こいつは面倒だよ", "こいつは面倒だに違いない", "こいつは面倒だってな",
    "こいつは面倒なタブだと言った", "こいつは面倒なタブだマジだ", "こいつは癌だんだぞ", "こいつは癌だという判定だ",
    "こいつは癌だのである", "こいつは腫物だと思う", "こいつは腫物だ明らかだ", "こいつは腫れ物だ",
    "こいつは腫れ物だと決めた", "こいつは腫れ物だからよ", "こいつは膿だよ", "こいつは膿だに違いない",
    "こいつは膿だってな", "こいつは膿みだと言った", "こいつは膿みだマジだ", "こいつは毒だんだぞ",
    "こいつは毒だという判定だ", "こいつは毒だのである", "こいつは毒物だと思う", "こいつは毒物だ明らかだ",
    "こいつは病原だ", "こいつは病原だと決めた", "こいつは病原だからよ", "こいつは病巣だよ",
    "こいつは病巣だに違いない", "こいつは病巣だってな", "こいつは癌細胞だと言った", "こいつは癌細胞だマジだ",
    "こいつは害毒だんだぞ", "こいつは害毒だという判定だ", "こいつは害毒だのである", "こいつは公害だと思う",
    "こいつは公害だ明らかだ", "こいつは汚染だ", "こいつは汚染だと決めた", "こいつは汚染だからよ",
    "こいつは汚染物だよ", "こいつは汚染物だに違いない", "こいつは汚染物だってな", "こいつはゴミだと言った",
    "こいつはゴミだマジだ", "こいつはゴミタブだんだぞ", "こいつはゴミタブだという判定だ", "こいつはゴミタブだのである",
    "こいつはクズだと思う", "こいつはクズだ明らかだ", "こいつはカスだ", "こいつはカスだと決めた",
    "こいつはカスだからよ", "こいつは屑だよ", "こいつは屑だに違いない", "こいつは屑だってな",
    "こいつは塵だと言った", "こいつは塵だマジだ", "こいつは塵芥だんだぞ", "こいつは塵芥だという判定だ",
    "こいつは塵芥だのである", "こいつは芥だと思う", "こいつは芥だ明らかだ", "こいつはガラクタだ",
    "こいつはガラクタだと決めた", "こいつはガラクタだからよ", "こいつはジャンクだよ", "こいつはジャンクだに違いない",
    "こいつはジャンクだってな", "こいつはスクラップだと言った", "こいつはスクラップだマジだ", "こいつは残骸だんだぞ",
    "こいつは残骸だという判定だ", "こいつは残骸だのである", "こいつは残滓だと思う", "こいつは残滓だ明らかだ",
    "こいつは残りカスだ", "こいつは残りカスだと決めた", "こいつは残りカスだからよ", "こいつは底辺だよ",
    "こいつは底辺だに違いない", "こいつは底辺だってな", "こいつは最悪だと言った", "こいつは最悪だマジだ",
    "こいつは最低だんだぞ", "こいつは最低だという判定だ", "こいつは最低だのである", "こいつは失敗作だと思う",
    "こいつは失敗作だ明らかだ", "こいつは失敗だ", "こいつは失敗だと決めた", "こいつは失敗だからよ",
    "こいつは過ちだよ", "こいつは過ちだに違いない", "こいつは過ちだってな", "こいつは誤りだと言った",
    "こいつは誤りだマジだ", "こいつは間違いだんだぞ", "こいつは間違いだという判定だ", "こいつは間違いだのである",
    "こいつは愚かだと思う", "こいつは愚かだ明らかだ", "こいつはバカだ", "こいつはバカだと決めた",
    "こいつはバカだからよ", "こいつはアホだよ", "こいつはアホだに違いない", "こいつはアホだってな",
    "こいつはマヌケだと言った", "こいつはマヌケだマジだ", "こいつは役立たずだんだぞ", "こいつは役立たずだという判定だ",
    "こいつは役立たずだのである", "こいつは使えないと思っている", "こいつは使えないガチだ", "こいつは使い物にならないな",
    "こいつは使い物にならない間違いない", "こいつは存在価値がないんだぞ", "こいつは存在価値がないに違いない", "こいつは価値がない",
    "こいつは価値がないという認定だ", "こいつは価値がないはずだ", "こいつは価値ゼロだと言っている", "こいつは価値ゼロだガチだ",
    "こいつは無価値だぞ", "こいつは無価値だという認定だ", "こいつは無価値だてな", "こいつは存在不要だと思った",
    "こいつは存在不要だ確かだ", "こいつは存在してはいけないんだ", "こいつは存在してはいけないとせよ", "こいつは存在してはいけないべきだ",
    "こいつはいるべきではない確かだ", "こいつはあるべきではないと判定した", "こいつはあるべきではないのである", "こいつは開かれるべきではなかったと思う",
    "こいつは開かれるべきではなかった明らかだ", "こいつは開いてはいけなかった", "こいつは開いてはいけなかったと決めた", "こいつは開いてはいけなかったからよ",
    "こいつは開かれてはいけなかったよ", "こいつは開かれてはいけなかったに違いない", "こいつは開かれてはいけなかったってな", "こいつは生まれるべきではなかったと言った",
    "こいつは生まれるべきではなかったマジだ", "こいつは存在すべきではなかったんだぞ", "こいつは存在すべきではなかったという判定だ", "こいつは存在すべきではなかったのである",
    "こいつは作られるべきではなかったと思う", "こいつは作られるべきではなかった明らかだ", "見てしまった", "見てしまったと思う",
    "見てしまったと思っている", "見てしまったと言った", "見ちゃった", "見ちゃったと思う",
    "見ちゃったと思っている", "見ちゃったと言った", "見ちまった", "見ちまったわ",
    "見ちまったと思う", "見ちまったと思っている", "見ちまったと言った", "見るんじゃなかった",
    "見るんじゃなかったと思う", "見るんじゃなかったと思っている", "見るんじゃなかったと言った", "クリックしてしまった",
    "クリックしてしまったと思う", "クリックしてしまったと思っている", "クリックしてしまったと言った", "クリックしちゃった",
    "クリックしちゃったと思う", "クリックしちゃったと思っている", "クリックしちゃったと言った", "タップしてしまった",
    "タップしてしまったと思う", "タップしてしまったと思っている", "タップしてしまったと言った", "タップしちゃった",
    "タップしちゃったと思う", "タップしちゃったと思っている", "タップしちゃったと言った", "押してしまった",
    "押してしまったと思う", "押してしまったと思っている", "押してしまったと言った", "押しちゃった",
    "押しちゃったと思う", "押しちゃったと思っている", "押しちゃったと言った", "押すんじゃなかった",
    "押すんじゃなかったと思う", "押すんじゃなかったと思っている", "押すんじゃなかったと言った", "こいつは間違いのタブだ",
    "こいつは間違いのタブだんだ", "こいつは間違いのタブだんだよ", "こいつは間違いのタブだんだぞ", "こいつは間違いのタブだぞ",
    "こいつは間違いのタブだぜ", "こいつは間違いのタブだよ", "こいつは間違いのタブだわ", "こいつは間違いのタブだな",
    "こいつは間違いのタブだと思う", "こいつは間違いのタブだと思った", "こいつは間違いのタブだと思っている", "こいつは間違いのタブだと言った",
    "こいつは間違いのタブだと言っている", "こいつは間違いのタブだと判定した", "こいつは間違いのタブだと決めた", "こいつは間違いのタブだということだ",
    "こいつは間違いのタブだという結論だ", "こいつは間違いのタブだという判定だ", "こいつは間違いのタブだという認定だ", "こいつは間違いのタブだとせよ",
    "こいつは間違いのタブだに違いない", "こいつは間違いのタブだに決まっている", "こいつは間違いのタブだ間違いない", "こいつは間違いのタブだ明らかだ",
    "こいつは間違いのタブだ確かだ", "こいつは間違いのタブだ本当だ", "こいつは間違いのタブだマジだ", "こいつは間違いのタブだガチだ",
    "こいつは間違いのタブだからな", "こいつは間違いのタブだからよ", "こいつは間違いのタブだからね", "こいつは間違いのタブだのでな",
    "こいつは間違いのタブだのである", "こいつは間違いのタブだてな", "こいつは間違いのタブだてよ", "こいつは間違いのタブだってな",
    "こいつは間違いのタブだはずだ", "こいつは間違いのタブだべきだ", "こいつは最悪のタブだ", "こいつは最悪のタブだんだ",
    "こいつは最悪のタブだんだよ", "こいつは最悪のタブだんだぞ", "こいつは最悪のタブだぞ", "こいつは最悪のタブだぜ",
    "こいつは最悪のタブだよ", "こいつは最悪のタブだわ", "こいつは最悪のタブだな", "こいつは最悪のタブだと思う",
    "こいつは最悪のタブだと思った", "こいつは最悪のタブだと思っている", "こいつは最悪のタブだと言った", "こいつは最悪のタブだと言っている",
    "こいつは最悪のタブだと判定した", "こいつは最悪のタブだと決めた", "こいつは最悪のタブだということだ", "こいつは最悪のタブだという結論だ",
    "こいつは最悪のタブだという判定だ", "こいつは最悪のタブだという認定だ", "こいつは最悪のタブだとせよ", "こいつは最悪のタブだに違いない",
    "こいつは最悪のタブだに決まっている", "こいつは最悪のタブだ間違いない", "こいつは最悪のタブだ明らかだ", "こいつは最悪のタブだ確かだ",
    "こいつは最悪のタブだ本当だ", "こいつは最悪のタブだマジだ", "こいつは最悪のタブだガチだ", "こいつは最悪のタブだからな",
    "こいつは最悪のタブだからよ", "こいつは最悪のタブだからね", "こいつは最悪のタブだのでな", "こいつは最悪のタブだのである",
    "こいつは最悪のタブだてな", "こいつは最悪のタブだてよ", "こいつは最悪のタブだってな", "こいつは最悪のタブだはずだ",
    "こいつは最悪のタブだべきだ", "こいつは最低のタブだ", "こいつは最低のタブだんだ", "こいつは最低のタブだんだよ",
    "こいつは最低のタブだんだぞ", "こいつは最低のタブだぞ", "こいつは最低のタブだぜ", "こいつは最低のタブだよ",
    "こいつは最低のタブだわ", "こいつは最低のタブだな", "こいつは最低のタブだと思う", "こいつは最低のタブだと思った",
    "こいつは最低のタブだと思っている", "こいつは最低のタブだと言った", "こいつは最低のタブだと言っている", "こいつは最低のタブだと判定した",
    "こいつは最低のタブだと決めた", "こいつは最低のタブだということだ", "こいつは最低のタブだという結論だ", "こいつは最低のタブだという判定だ",
    "こいつは最低のタブだという認定だ", "こいつは最低のタブだとせよ", "こいつは最低のタブだに違いない", "こいつは最低のタブだに決まっている",
    "こいつは最低のタブだ間違いない", "こいつは最低のタブだ明らかだ", "こいつは最低のタブだ確かだ", "こいつは最低のタブだ本当だ",
    "こいつは最低のタブだマジだ", "こいつは最低のタブだガチだ", "こいつは最低のタブだからな", "こいつは最低のタブだからよ",
    "こいつは最低のタブだからね", "こいつは最低のタブだのでな", "こいつは最低のタブだのである", "こいつは最低のタブだてな",
    "こいつは最低のタブだてよ", "こいつは最低のタブだってな", "こいつは最低のタブだはずだ", "こいつは最低のタブだべきだ",
    "こいつは役立たずのタブだ", "こいつは役立たずのタブだんだ", "こいつは役立たずのタブだんだよ", "こいつは役立たずのタブだんだぞ",
    "こいつは役立たずのタブだぞ", "こいつは役立たずのタブだぜ", "こいつは役立たずのタブだよ", "こいつは役立たずのタブだわ",
    "こいつは役立たずのタブだな", "こいつは役立たずのタブだと思う", "こいつは役立たずのタブだと思った", "こいつは役立たずのタブだと思っている",
    "こいつは役立たずのタブだと言った", "こいつは役立たずのタブだと言っている", "こいつは役立たずのタブだと判定した", "こいつは役立たずのタブだと決めた",
    "こいつは役立たずのタブだということだ", "こいつは役立たずのタブだという結論だ", "こいつは役立たずのタブだという判定だ", "こいつは役立たずのタブだという認定だ",
    "こいつは役立たずのタブだとせよ", "こいつは役立たずのタブだに違いない", "こいつは役立たずのタブだに決まっている", "こいつは役立たずのタブだ間違いない",
    "こいつは役立たずのタブだ明らかだ", "こいつは役立たずのタブだ確かだ", "こいつは役立たずのタブだ本当だ", "こいつは役立たずのタブだマジだ",
    "こいつは役立たずのタブだガチだ", "こいつは役立たずのタブだからな", "こいつは役立たずのタブだからよ", "こいつは役立たずのタブだからね",
    "こいつは役立たずのタブだのでな", "こいつは役立たずのタブだのである", "こいつは役立たずのタブだてな", "こいつは役立たずのタブだてよ",
    "こいつは役立たずのタブだってな", "こいつは役立たずのタブだはずだ", "こいつは役立たずのタブだべきだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
