// Pass CCLXV: EN nullify/verdict/doom declaratives + JA 無効/破棄/失格宣告 (pass CCLXV)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXV: close-tab coverage', () => {
  test.each([
    "nullify it hereafter", "nullify this tab hereafter", "nullify the tab outright", "nullify that tab henceforth",
    "nullify this page", "nullify this page effective at once", "nullify the page as of now", "nullify this thing by my own authority",
    "nullify this by edict", "nullify its existence with one word", "nullify its right to exist with relish", "nullify its very existence without a second thought",
    "annul it with satisfaction", "annul this tab with prejudice", "annul the tab with relish", "annul that tab without a second thought",
    "annul this page promptly", "annul the page at last", "annul this thing categorically", "annul this entirely",
    "annul its existence right now", "annul its existence effective this instant", "annul its right to exist as of right now", "annul its very existence by my command",
    "void it as of this instant", "void this tab by my decree", "void the tab as of right now", "void that tab by my command",
    "void this page by command", "void the page with one order", "void this thing with delight", "void this with finality",
    "void its existence without hesitation", "void its right to exist just", "void its very existence forever", "invalidate it just",
    "invalidate this tab for good", "invalidate the tab simply", "invalidate that tab forever", "invalidate this page utterly",
    "invalidate the page forthwith", "invalidate the page effective hereafter", "invalidate this thing effective immediately", "invalidate this by my say so",
    "invalidate its existence by my own decree", "invalidate its right to exist by fiat", "invalidate its very existence with a single word", "negate it by decree",
    "negate this tab with the stroke of a pen", "negate the tab with one signature", "negate that tab with a smile", "negate this page with certainty",
    "negate the page without remorse", "negate this thing unilaterally", "negate this for good", "negate its existence wholly",
    "negate its right to exist henceforth", "negate its very existence", "negate its very existence effective at once", "cancel this tab",
    "cancel this tab effective at once", "cancel the tab effective hereafter", "cancel this page effective immediately", "cancel the page by my say so",
    "cancel this thing by my own decree", "cancel this by fiat", "cancel its existence with a single word", "cancel its right to exist with glee",
    "cancel its very existence without mercy", "rescind it with glee", "rescind this tab without mercy", "rescind the tab with pleasure",
    "rescind that tab without pity", "rescind this page summarily", "rescind the page once and for all", "rescind this thing fully",
    "rescind this hereafter", "rescind its existence now", "rescind its existence effective forthwith", "rescind its right to exist as of today",
    "rescind its very existence by my authority", "revoke it as of today", "revoke this tab by my authority", "revoke the tab as of now",
    "revoke that tab by my own authority", "revoke this page by edict", "revoke the page with one word", "revoke this thing with relish",
    "revoke this without a second thought", "revoke its existence with glee", "revoke its right to exist without mercy", "revoke its very existence swiftly",
    "repeal it without mercy", "repeal this tab swiftly", "repeal the tab without pity", "repeal that tab summarily",
    "repeal this page once and for all", "repeal the page fully", "repeal this thing hereafter", "repeal this now",
    "repeal this effective forthwith", "repeal its existence as of today", "repeal its right to exist by my authority", "repeal its very existence by proclamation",
    "abolish it by my authority", "abolish this tab by proclamation", "abolish the tab by my own authority", "abolish that tab by edict",
    "abolish this page with one word", "abolish the page with relish", "abolish this thing without a second thought", "abolish this promptly",
    "abolish its existence at last", "abolish its right to exist categorically", "abolish its very existence entirely", "abrogate it completely",
    "abrogate this tab outright", "abrogate the tab today", "abrogate the tab effective today", "abrogate that tab as of this moment",
    "abrogate this page by my order", "abrogate the page by order", "abrogate this thing with one command", "abrogate this with joy",
    "abrogate its existence with extreme prejudice", "abrogate its right to exist without delay", "abrogate its very existence simply", "quash it without hesitation",
    "quash this tab just", "quash the tab without delay", "quash that tab simply", "quash this page permanently",
    "quash the page totally", "quash this thing at once", "quash this thing effective henceforth", "quash this effective now",
    "quash its existence by my word", "quash its right to exist by executive order", "quash its very existence by decree", "strike down it with the stroke of a pen",
    "strike down this tab with pleasure", "strike down the tab with a smile", "strike down that tab with certainty", "strike down this page without remorse",
    "strike down the page unilaterally", "strike down this thing for good", "strike down this wholly", "strike down its existence henceforth",
    "strike down its right to exist", "strike down its right to exist effective at once", "strike down its very existence as of now", "strike it effective immediately",
    "strike this tab by my say so", "strike the tab effective now", "strike that tab by my word", "strike this page by executive order",
    "strike the page by decree", "strike this thing with the stroke of a pen", "strike this with pleasure", "strike its existence without pity",
    "strike its right to exist summarily", "strike its very existence once and for all", "vacate it just", "vacate this tab for good",
    "vacate the tab simply", "vacate that tab forever", "vacate this page utterly", "vacate the page forthwith",
    "vacate the page effective hereafter", "vacate this thing effective immediately", "vacate this by my say so", "vacate its existence by my own decree",
    "vacate its right to exist by fiat", "vacate its very existence with a single word", "overturn it by decree", "overturn this tab with the stroke of a pen",
    "overturn the tab with one signature", "overturn that tab with a smile", "overturn this thing with certainty", "overturn this without remorse",
    "overturn its existence unilaterally", "overturn its right to exist for good", "overturn its very existence wholly", "overrule it fully",
    "overrule this tab wholly", "overrule the tab fully", "overrule that tab utterly", "overrule this page forthwith",
    "overrule this page effective hereafter", "overrule the page effective immediately", "overrule this thing by my say so", "overrule this by my own decree",
    "overrule its existence by fiat", "overrule its right to exist with a single word", "overrule its very existence with glee", "override it with the stroke of a pen",
    "override this tab with pleasure", "override the tab with a smile", "override that tab with certainty", "override this page without remorse",
    "override the page unilaterally", "override this thing for good", "override this wholly", "override its existence henceforth",
    "override its right to exist", "override its right to exist effective at once", "override its very existence as of now", "reverse it by my own authority",
    "reverse this tab by edict", "reverse the tab with one word", "reverse that tab with relish", "reverse this page without a second thought",
    "reverse the page promptly", "reverse this thing at last", "reverse this categorically", "reverse its existence entirely",
    "reverse its right to exist right now", "reverse its right to exist effective this instant", "reverse its very existence as of right now", "unmake it effective today",
    "unmake this tab as of this moment", "unmake the tab effective forthwith", "unmake that tab as of today", "unmake this page by my authority",
    "unmake the page by proclamation", "unmake this thing with one decree", "unmake this with satisfaction", "unmake its existence with prejudice",
    "unmake its right to exist posthaste", "unmake its very existence already", "unwrite it swiftly", "unwrite this tab at last",
    "unwrite the tab summarily", "unwrite that tab finally", "unwrite this page absolutely", "unwrite the page outright",
    "unwrite this thing today", "unwrite this thing effective today", "unwrite this as of this moment", "unwrite its existence by my order",
    "unwrite its right to exist by order", "unwrite its very existence with one command", "unenact it with joy", "unenact this tab with extreme prejudice",
    "unenact the tab without delay", "unenact that tab simply", "unenact this page permanently", "unenact the page totally",
    "unenact this thing at once", "unenact this thing effective henceforth", "unenact this effective now", "unenact its existence by my word",
    "unenact its right to exist by executive order", "unenact its very existence by decree", "unpass it with the stroke of a pen", "unpass this tab with pleasure",
    "unpass the tab without pity", "unpass that tab summarily", "unpass this page once and for all", "unpass the page fully",
    "unpass this thing hereafter", "unpass this now", "unpass this effective forthwith", "unpass its existence as of today",
    "unpass its right to exist by my authority", "unpass its very existence by proclamation", "disallow it by my own authority", "disallow this tab by edict",
    "disallow the tab by my own decree", "disallow that tab by fiat", "disallow this page with a single word", "disallow the page with glee",
    "disallow this thing without mercy", "disallow this swiftly", "disallow its existence finally", "disallow its right to exist absolutely",
    "disallow its very existence outright", "disqualify it entirely", "disqualify this tab hereafter", "disqualify the tab outright",
    "disqualify that tab henceforth", "disqualify this page", "disqualify this page effective at once", "disqualify the page as of now",
    "disqualify this thing by my own authority", "disqualify this by edict", "disqualify its existence with one word", "disqualify its right to exist with relish",
    "disqualify its very existence without a second thought", "disavow it with glee", "disavow this tab without mercy", "disavow the tab with pleasure",
    "disavow that tab without pity", "disavow this page summarily", "disavow the page once and for all", "disavow this thing fully",
    "disavow this hereafter", "disavow its existence now", "disavow its existence effective forthwith", "disavow its right to exist as of today",
    "disavow its very existence by my authority", "repudiate it as of today", "repudiate this tab by my authority", "repudiate the tab as of now",
    "repudiate that tab by my own authority", "repudiate this page by edict", "repudiate the page with one word", "repudiate this thing with relish",
    "repudiate this without a second thought", "repudiate its existence promptly", "repudiate its right to exist at last", "repudiate its very existence categorically",
    "renounce it irrevocably", "renounce this tab absolutely", "renounce the tab categorically", "renounce that tab fully",
    "renounce this page hereafter", "renounce the page now", "renounce the page effective forthwith", "renounce this thing as of today",
    "renounce this by my authority", "renounce its existence by proclamation", "renounce its right to exist with one decree", "renounce its very existence with satisfaction",
    "forswear it with one word", "forswear this tab with relish", "forswear the tab with a single word", "forswear that tab with glee",
    "forswear this page without mercy", "forswear the page swiftly", "forswear this thing finally", "forswear this absolutely",
    "forswear its existence outright", "forswear its right to exist today", "forswear its right to exist effective today", "forswear its very existence as of this moment",
    "abjure it effective forthwith", "abjure this tab as of today", "abjure the tab effective at once", "abjure that tab as of now",
    "abjure this page by my own authority", "abjure the page by edict", "abjure this thing with one word", "abjure this with relish",
    "abjure its existence without a second thought", "abjure its right to exist promptly", "abjure its very existence at last", "disown it summarily",
    "disown this tab finally", "disown the tab absolutely", "disown that tab outright", "disown this page today",
    "disown this page effective today", "disown the page as of this moment", "disown this thing by my order", "disown this by order",
    "disown its existence with one command", "disown its right to exist with joy", "disown its very existence with extreme prejudice", "disinherit it with satisfaction",
    "disinherit this tab with prejudice", "disinherit the tab posthaste", "disinherit that tab already", "disinherit this page irrevocably",
    "disinherit the page completely", "disinherit this thing immediately", "disinherit this thing effective this moment", "disinherit this as of this instant",
    "disinherit its existence by my decree", "disinherit its right to exist by royal decree", "disinherit its very existence with one signature", "disclaim it by command",
    "disclaim this tab with one order", "disclaim the tab by order", "disclaim that tab with one command", "disclaim this page with joy",
    "disclaim the page with extreme prejudice", "disclaim this thing without delay", "disclaim this simply", "disclaim its existence permanently",
    "disclaim its right to exist totally", "disclaim its very existence at once", "disclaim its very existence effective henceforth", "discredit it effective now",
    "discredit this tab by my word", "discredit the tab by executive order", "discredit that tab by decree", "discredit this page with the stroke of a pen",
    "discredit the page with pleasure", "discredit this thing without pity", "discredit this summarily", "discredit its existence once and for all",
    "discredit its right to exist fully", "discredit its very existence hereafter", "depose it now", "depose it effective forthwith",
    "depose this tab as of today", "depose the tab by my authority", "depose that tab by proclamation", "depose this page with one decree",
    "depose the page with satisfaction", "depose this thing with prejudice", "depose this posthaste", "depose its existence already",
    "depose its right to exist irrevocably", "depose its very existence completely", "dethrone it immediately", "dethrone it effective this moment",
    "dethrone this tab as of this instant", "dethrone the tab by my decree", "dethrone that tab by royal decree", "dethrone this page with one signature",
    "dethrone the page with a smile", "dethrone this thing with certainty", "dethrone this without remorse", "dethrone its existence unilaterally",
    "dethrone its right to exist for good", "dethrone its very existence wholly", "dismiss it fully", "dismiss this tab utterly",
    "dismiss the tab wholly", "dismiss that tab totally", "dismiss this page at once", "dismiss this page effective henceforth",
    "dismiss the page effective now", "dismiss this thing by my word", "dismiss this by executive order", "dismiss its existence by decree",
    "dismiss its right to exist with the stroke of a pen", "dismiss its very existence with pleasure", "discharge it with a smile", "discharge this tab with certainty",
    "discharge the tab with delight", "discharge that tab with finality", "discharge this page without hesitation", "discharge the page just",
    "discharge this thing forever", "discharge this utterly", "discharge its existence forthwith", "discharge its existence effective hereafter",
    "discharge its right to exist effective immediately", "discharge its very existence by my say so", "dissolve it effective today", "dissolve this tab as of this moment",
    "dissolve the tab effective forthwith", "dissolve that tab as of today", "dissolve this page by my authority", "dissolve the page by proclamation",
    "dissolve this thing with one decree", "dissolve this with satisfaction", "dissolve its existence with prejudice", "dissolve its right to exist posthaste",
    "dissolve its very existence already", "disband it irrevocably", "disband this tab completely", "disband the tab immediately",
    "disband the tab effective this moment", "disband that tab as of this instant", "disband this page by my decree", "disband the page by royal decree",
    "disband this thing with one signature", "disband this with a smile", "disband its existence with certainty", "disband its right to exist without remorse",
    "disband its very existence unilaterally", "disestablish it for good", "disestablish this tab wholly", "disestablish the tab henceforth",
    "disestablish that tab", "disestablish that tab effective at once", "disestablish this page as of now", "disestablish the page by my own authority",
    "disestablish this thing by edict", "disestablish this with one word", "disestablish its existence with relish", "disestablish its right to exist without a second thought",
    "disestablish its very existence promptly", "decommission it without mercy", "decommission this tab swiftly", "decommission the tab without pity",
    "decommission that tab summarily", "decommission this page once and for all", "decommission the page fully", "decommission this thing hereafter",
    "decommission this now", "decommission this effective forthwith", "decommission its existence as of today", "decommission its right to exist by my authority",
    "decommission its very existence by proclamation", "retire it by my authority", "retire this tab by proclamation", "retire the tab by my own authority",
    "retire that tab by edict", "retire this page with one word", "retire the page with relish", "retire this thing without a second thought",
    "retire this promptly", "retire its existence at last", "retire its right to exist categorically", "retire its very existence entirely",
    "sunset it completely", "sunset this tab outright", "sunset the tab entirely", "sunset that tab hereafter",
    "sunset this page now", "sunset this page effective forthwith", "sunset the page as of today", "sunset this thing by my authority",
    "sunset this by proclamation", "sunset its existence with one decree", "sunset its right to exist with satisfaction", "sunset its very existence with prejudice",
    "deprecate it with relish", "deprecate this tab without a second thought", "deprecate the tab with glee", "deprecate that tab without mercy",
    "deprecate this page swiftly", "deprecate the page finally", "deprecate this thing absolutely", "deprecate this outright",
    "deprecate its existence today", "deprecate its existence effective today", "deprecate its right to exist as of this moment", "deprecate its very existence by my order",
    "terminate it as of right now", "terminate this tab by my command", "terminate the tab as of this moment", "terminate that tab by my order",
    "terminate this page by order", "terminate the page with one command", "terminate this thing with joy", "terminate this with extreme prejudice",
    "terminate its existence without delay", "terminate its right to exist simply", "terminate its very existence permanently", "end it at last",
    "end this tab promptly", "end the tab without a second thought", "end that tab with glee", "end this page with the stroke of a pen",
    "end the page with pleasure", "end this thing with a smile", "end this with one order", "end its existence with delight",
    "end its right to exist with finality", "end its very existence without hesitation", "finish it with extreme prejudice", "finish this tab without delay",
    "finish the tab with prejudice", "finish that tab posthaste", "finish this page without a second thought", "finish the page promptly",
    "finish this thing at last", "finish this categorically", "finish its existence entirely", "finish its right to exist right now",
    "finish its right to exist effective this instant", "finish its very existence as of right now", "conclude it by my command", "conclude this tab by command",
    "conclude the tab with one order", "conclude that tab with delight", "conclude this page with finality", "conclude the page without hesitation",
    "conclude this thing just", "conclude this forever", "conclude its existence utterly", "conclude its right to exist forthwith",
    "conclude its right to exist effective hereafter", "conclude its very existence effective immediately", "wind up it by my say so", "wind up this tab by my own decree",
    "wind up the tab by fiat", "wind up that tab with a single word", "wind up this page with glee", "wind up the page without mercy",
    "wind up this thing swiftly", "wind up this finally", "wind up its existence absolutely", "wind up its right to exist outright",
    "wind up its very existence today", "wind up its very existence effective today", "wind down it as of this moment", "wind down this tab by my order",
    "wind down the tab by order", "wind down that tab with one command", "wind down this page with joy", "wind down the page with extreme prejudice",
    "wind down this thing without delay", "wind down this simply", "wind down its existence permanently", "wind down its right to exist totally",
    "wind down its very existence at once", "wind down its very existence effective henceforth", "sunset it it effective now", "sunset it this tab by my word",
    "sunset it the tab by executive order", "sunset it that tab by decree", "sunset it this page with the stroke of a pen", "sunset it the page with pleasure",
    "sunset it this thing without pity", "sunset it this summarily", "sunset it its existence once and for all", "sunset it its right to exist fully",
    "sunset it its very existence hereafter", "close out it now", "close out it effective forthwith", "close out the tab hereafter",
    "close out that tab wholly", "close out this page totally", "close out the page at once", "close out the page effective henceforth",
    "close out this thing effective now", "close out this by my word", "close out its existence by executive order", "close out its right to exist by decree",
    "close out its very existence with the stroke of a pen", "close it by my order", "close that tab as of today", "close this page by my authority",
    "close the page by proclamation", "close this thing with one decree", "close this by edict", "close its existence with one word",
    "close its right to exist with relish", "close its very existence without a second thought", "shut it with a single word", "shut this tab with glee",
    "shut the tab with the stroke of a pen", "shut that tab with pleasure", "shut this page without pity", "shut the page summarily",
    "shut this thing once and for all", "shut this just", "shut its existence for good", "shut its right to exist wholly",
    "shut its very existence henceforth", "seal it hereafter", "seal this tab henceforth", "seal the tab hereafter",
    "seal that tab forthwith", "seal that tab effective hereafter", "seal this page effective immediately", "seal the page by my say so",
    "seal this thing by my own decree", "seal this by fiat", "seal its existence with a single word", "seal its right to exist with glee",
    "seal its very existence without mercy", "sign off on ending it swiftly", "sign off on ending this tab finally", "sign off on ending the tab absolutely",
    "sign off on ending that tab outright", "sign off on ending this page today", "sign off on ending this page effective today", "sign off on ending the page as of this moment",
    "sign off on ending this thing by my order", "sign off on ending this by order", "sign off on ending its existence with one command", "sign off on ending its right to exist with joy",
    "sign off on ending its very existence with extreme prejudice", "sign the death warrant of it without delay", "sign the death warrant of this tab simply", "sign the death warrant of the tab permanently",
    "sign the death warrant of that tab totally", "sign the death warrant of this page at once", "sign the death warrant of this page effective henceforth", "sign the death warrant of the page effective now",
    "sign the death warrant of this thing by my word", "sign the death warrant of this by executive order", "sign the death warrant of its existence by decree", "sign the death warrant of its right to exist with the stroke of a pen",
    "sign the death warrant of its very existence with pleasure", "sign the termination of it without pity", "sign the termination of this tab summarily", "sign the termination of the tab once and for all",
    "sign the termination of that tab fully", "sign the termination of this page hereafter", "sign the termination of the page now", "sign the termination of the page effective forthwith",
    "sign the termination of this thing as of today", "sign the termination of this by my authority", "sign the termination of its existence by proclamation", "sign the termination of its right to exist with one decree",
    "sign the termination of its very existence with satisfaction", "the verdict is final and binding", "the ruling has been delivered", "the die has been cast",
    "its doom is at hand", "its time has run out", "overturn this page", "overturn this page now",
    "overturn this page today", "overturn this page right now", "overturn this page immediately", "overturn this page at once",
    "overturn this page forthwith", "overturn this page henceforth", "overturn this page hereafter", "overturn this page outright",
    "overturn this page entirely", "overturn this page completely", "overturn this page totally", "overturn this page utterly",
    "overturn this page wholly", "overturn this page fully", "overturn this page absolutely", "overturn this page categorically",
    "overturn this page irrevocably", "overturn this page permanently", "overturn this page forever", "overturn this page for good",
    "overturn this page once and for all", "overturn this page finally", "overturn this page at last", "overturn this page already",
    "overturn this page simply", "overturn this page just", "overturn this page unilaterally", "overturn this page summarily",
    "overturn this page swiftly", "overturn this page promptly", "overturn this page posthaste", "overturn this page without delay",
    "overturn this page without hesitation", "overturn this page without remorse", "overturn this page without pity", "overturn this page without mercy",
    "overturn this page without a second thought", "overturn this page with prejudice", "overturn this page with extreme prejudice", "overturn this page with finality",
    "overturn this page with certainty", "overturn this page with pleasure", "overturn this page with glee", "overturn this page with relish",
    "overturn this page with satisfaction", "overturn this page with joy", "overturn this page with delight", "overturn this page with a smile",
    "overturn this page with the stroke of a pen", "overturn this page with a single word", "overturn this page with one word", "overturn this page with one decree",
    "overturn this page with one command", "overturn this page with one order", "overturn this page with one signature", "overturn this page by decree",
    "overturn this page by fiat", "overturn this page by edict", "overturn this page by proclamation", "overturn this page by order",
    "overturn this page by command", "overturn this page by royal decree", "overturn this page by executive order", "overturn this page by my own decree",
    "overturn this page by my own authority", "overturn this page by my authority", "overturn this page by my order", "overturn this page by my command",
    "overturn this page by my decree", "overturn this page by my word", "overturn this page by my say so", "overturn this page as of now",
    "overturn this page as of today", "overturn this page as of this moment", "overturn this page as of right now", "overturn this page as of this instant",
    "overturn this page effective now", "overturn this page effective immediately", "overturn this page effective at once", "overturn this page effective forthwith",
    "overturn this page effective today", "overturn this page effective this instant", "overturn this page effective this moment", "overturn this page effective henceforth",
    "overturn this page effective hereafter", "overturn the page", "overturn the page now", "overturn the page today",
    "overturn the page right now", "overturn the page immediately", "overturn the page at once", "overturn the page forthwith",
    "overturn the page henceforth", "overturn the page hereafter", "overturn the page outright", "overturn the page entirely",
    "overturn the page completely", "overturn the page totally", "overturn the page utterly", "overturn the page wholly",
    "overturn the page fully", "overturn the page absolutely", "overturn the page categorically", "overturn the page irrevocably",
    "overturn the page permanently", "overturn the page forever", "overturn the page for good", "overturn the page once and for all",
    "overturn the page finally", "overturn the page at last", "overturn the page already", "overturn the page simply",
    "overturn the page just", "overturn the page unilaterally", "overturn the page summarily", "overturn the page swiftly",
    "overturn the page promptly", "overturn the page posthaste", "overturn the page without delay", "overturn the page without hesitation",
    "overturn the page without remorse", "overturn the page without pity", "overturn the page without mercy", "overturn the page without a second thought",
    "overturn the page with prejudice", "overturn the page with extreme prejudice", "overturn the page with finality", "overturn the page with certainty",
    "overturn the page with pleasure", "overturn the page with glee", "overturn the page with relish", "overturn the page with satisfaction",
    "overturn the page with joy", "overturn the page with delight", "overturn the page with a smile", "overturn the page with the stroke of a pen",
    "overturn the page with a single word", "overturn the page with one word", "overturn the page with one decree", "overturn the page with one command",
    "overturn the page with one order", "overturn the page with one signature", "overturn the page by decree", "overturn the page by fiat",
    "overturn the page by edict", "overturn the page by proclamation", "overturn the page by order", "overturn the page by command",
    "overturn the page by royal decree", "overturn the page by executive order", "overturn the page by my own decree", "overturn the page by my own authority",
    "overturn the page by my authority", "overturn the page by my order", "overturn the page by my command", "overturn the page by my decree",
    "overturn the page by my word", "overturn the page by my say so", "overturn the page as of now", "overturn the page as of today",
    "overturn the page as of this moment", "overturn the page as of right now", "overturn the page as of this instant", "overturn the page effective now",
    "overturn the page effective immediately", "overturn the page effective at once", "overturn the page effective forthwith", "overturn the page effective today",
    "overturn the page effective this instant", "overturn the page effective this moment", "overturn the page effective henceforth", "overturn the page effective hereafter",
    "こいつをお払い箱だという可決だよ",
    "こやつを放り出せと決定する", "このページは放棄せよと思ったぞ", "そのページを残りカスだと決定するぞ", "あのタブは捨て去るわ",
    "これはマヌケだと判定するぞ", "そのタブを生まれてはいけなかったと宣告する", "そやつは誤りだという由だぞ", "あのタブは消えてもらえとという沙汰だぞ",
    "そのタブを見捨てよと申し渡す", "あのタブは失敗作だと命令する", "このページを見放すというお達しだぞ", "あやつを棄てよに違いない",
    "このページを叩き捨てよと断定しているよ", "あいつはいらないはずだよ", "あのタブは放り捨てよと言ったんだよ", "あやつを作ってはいけなかったと信じている",
    "このタブは目潰しだと宣言するぞ", "あのページは却下せよという判断だ", "これは抹消しろという筋だ", "あのページを最低だに相違ない",
    "これを使い物にならないと認識したよ", "これを消えちまえとという結論だよ", "このページは帳消しだと結論づけている", "あのページを屑だと言っているぞ",
    "このタブを消えろと言っているぞって言ったんだぞ", "これを取り消すものだ", "このタブを消えちまえよだからね", "こやつは権利なしだと信じたよ",
    "消えろと言っているわと考えた", "そのタブを放り捨てよと宣言するよ", "これは消え失せよ以外の何物でもない", "あやつを消えろと言ったはずだわと断定したよ",
    "このページは消えろと言ったんだぜべきだぞ", "あのページは突き放そうと考えている", "あやつは消え去れと決定するよ", "消えてくださいなという向きだぞ",
    "あやつを目潰しだと宣言するよ", "あのページは取り下げるということだよ", "こいつを取り下げよと認識した", "残滓だってよ",
    "あやつをひっくり返すと確信しているぞ", "そやつを権利喪失だと信じたよ", "こやつは消えてもいいなという裁定だぞ", "このページは消去しろと断定している",
    "そのページは消えてくれるかなという判断だよ", "こやつは放棄せよという筋だぞ", "あのページは消滅しろってば", "そいつはいてはいけないと考えたぞ",
    "これを消えてもいいよという裁定だぞ", "これを退けろっつってよ", "このページを消えちまうんだとみなすぞ", "このタブは消えちゃえという判決だよ",
    "そのタブを無効にしろと言い渡すぞ", "あいつは取消しろというお達しだよ", "あやつは権利を失っているという次第だ", "あのページは消えてくださいねと決めるよ",
    "そいつは消えてくれないかなって言ったよ", "こいつを消えちまえよっつってよ", "除名せよと宣言する", "消えてなくなれと認めたよ",
    "こいつは消去すると断定したぞ", "そのページを不用だと言い渡そうよ", "あいつは消去しろに違いない", "あのタブは帳消しにしろと命令するぞ",
    "そやつを消えてもいいぜと認めたよ", "こいつは消えちまえとと見解したよ", "そやつを無効にしろっつってば", "あいつをマヌケだと認めているよ",
    "そいつを失格にせよと判断するぞ", "このタブは消え失せろぞ", "そいつを生まれてはいけなかったと確信したぞ", "取り下げろだぞ",
    "これを消えろと言ったはずだぞことな", "あいつを消えてもらうわと見なす", "こいつは打ち捨てろと断言するよ", "あいつは棄却すると宣言するよ",
    "あやつは破棄すると言い渡すぞ", "あやつは無効だと結論づけているよ", "そのページを消えろと言ったはずだよもんだ", "このページを打ち捨てると断定したよ",
    "そのページは要らんだからな", "そやつは削除だだな", "そのタブを最低だと結論づけている", "あいつを棄てると申し渡す",
    "そやつを斬り捨てるっつってよ", "あやつを削除するという沙汰だぞ", "あやつは消去しろという沙汰だよ", "あやつは突き放せのぜ",
    "消えてもらうと言っている", "消え去れよと判断したぞ", "こいつはクズだと認識した", "これは不要だぞと命じるぞ",
    "このページは消えちゃえとと認めたよ", "そのページを消えろってという指令だ", "そいつはゴミだという向きだ", "こいつを消えちまえとと思った",
    "そのタブは消えてほしいと認めているよ", "こいつを退けろと考えた", "こやつはほっぽり出せという話だぞ", "これを消えろと言ったと結論づけたよ",
    "このページは使い物にならないと認めたぞ", "あいつを消えてもらおうと断定したぞ", "このタブは帳消しだという命令だよ", "そいつは消えろと言っているぞと考えているぞ",
    "こいつを権利喪失にしろものだ", "あいつを除籍すると思っているぞ", "捨て置くべきなのよ", "こやつは消えてほしいという判定だぞ",
    "あやつはほっぽり出せと宣言するぞ", "そいつを消えろと言っているのだと言っている", "これは棄てると決めたよ", "そやつは残りカスだという筋だ",
    "こやつを屑だと申し渡すぞ", "そのページは資格がないと思っているぞ", "そやつは帳消しにするだからね", "あいつはゴミだと言ったんだ",
    "そのページを退けるに決まっている", "これを芥だと決定する", "このタブを消去せよと命令するぞ", "これは切り捨てると見なすよ",
    "あいつは消えてほしいわというお達しだ", "こいつはいる意味がないと思う", "そいつは抹消すると確信しているぞ", "このタブを斬り捨てろと決めるよ",
    "そのタブを消えちゃえな", "あいつを消えていいぜと宣告するよ", "そいつを消えてなくなれよと思うよ", "そやつを放棄しろべきなんだ",
    "そのタブを抹消せよという命令だよ", "これは消えろと言っただろうと言っているんだよ", "あいつを消えろってつってよ", "こいつを棄却しろと言い渡そうよ",
    "こいつを打ち捨てよと認めたぞ", "こいつをいるべきではないという判定だ", "権利喪失だという結論だよ", "そのタブを消えろと言ったんだわと考えているよ",
    "そいつは消えろと言ったはずだと認めた", "こいつを作るべきではなかったと言い渡そうぞ", "そいつは開かれてはいけなかったと認めている", "これを使い物にならないという判定だよ",
    "あやつを存在する意義がないという由だ", "あやつを不要だぞという議決だよ", "あいつは斬り捨てると認識したよ", "このタブを削除しろと結論づけている",
    "こやつは権利喪失だっつってよ", "あいつは消えてもらいたいのだ", "こいつは棄てろと言っているぞ", "このページをいてはいけないというお達しだぞ",
    "こやつを棄却するという議決だぞ", "あのページは覆せというお達しだぞ", "あいつは消えちゃおうと認識した", "こいつを消えろと言っただろうと見なすよ",
    "これは消えてくださいねということだ", "放棄せよべきなのだ", "そのページを目潰しだって言った", "こやつを棄てよと言うと判定するよ",
    "そのタブは消えちまえよと思っているぞ", "そやつはいらないと言ったぞ", "消えてもいいぜだ", "こやつを不要だぞと言っているんだ",
    "そのタブを使い物にならないと宣言するぞ", "このタブは切り捨てよという筋だぞ", "そのタブは残りカスだという指令だよ", "あのページは不用だという判定だよ",
    "あいつを取消すつってよ", "あいつは消えろと言ったはずだぜという判断だ", "あのページは価値がないと結論づけた", "そいつを権利を失っていると認めているよ",
    "あのタブを抹殺だという採決だ", "あのタブは消えろと言ったはずだわからよ", "あやつは抹消せよという判決だぞ", "あいつを消えちゃうんだと結論した",
    "これは消えていいぜと命じるぞ", "こいつは突き放せと認めている", "そやつはなかったことにするよ", "そいつは打ち捨てると申し渡すよ",
    "こいつは棄てろんだ", "あのページは捨て置けという次第だぞ", "これは消えろってばと言い渡そう", "あいつは消えろってのにつってば",
    "あいつを使えないだな", "このタブは見限ったと確信した", "このページを取消しだと認識したよ", "そいつはゴミだという可決だぞ",
    "このページを消えてもらうんだと言っているよ", "そのタブを消えてもらうと判定するぞ", "あやつははねつけると考えた", "これは放り出そうとみなすよ",
    "あやつは消え去れよことだ", "あのタブを権利を失ったぞ", "あいつは抹殺せよと信じたぞ", "あのページを消え失せよという話だ",
    "これは開かれてはいけなかったと思っているぞ", "あのタブを取消しだと断定したよ", "このタブを最低だという沙汰だ", "あのタブを突き放せもんだ",
    "このタブを資格喪失にせよというお達しだぞ", "そのページを無効にせよと信じたぞ", "このページは消えてくださいねという可決だ", "あいつを放棄せよって言ったぞ",
    "あのページをひっくり返せという結論だぞ", "そのページを消えていいなと宣告する", "あのページは間違いだと断定したよ", "こやつを権利なしだと結論づけているよ",
    "このタブは突き放そうべきだぞ", "これを無価値だと宣告する", "このタブを消えちまえべきなのだ", "こいつを削除しろと命令するぞ",
    "これをアホだっつってんだ", "そやつを消えろと言ったはずだよと命じるぞ", "お払い箱にすると確信している", "このページをいらんって言ったんだぞ",
    "あのタブは消えろと言ったはずだぜ以外の何物でもない", "そいつは棄てろべきなのよ", "これは消えろと言ったんだだぞ", "そいつをお払い箱にせよと言ったはずだぞ",
    "あやつを消えろと言っただろうと決めるぞ", "そのタブを不要とするって言ったんだ", "そいつを権利喪失だと判断したよ", "そのタブは消えてほしいんだと言い渡そうよ",
    "こやつはいてはならないぜ", "あいつはいらないと確信しているぞ", "そやつを無効にしろと結論づけたよ", "このタブを放棄だだ",
    "そいつは使い物にならないっての", "そいつは消えちゃえとと言い渡すぞ", "そのページを消えろってんだという採決だよ", "あやつは消えろと考えている",
    "これを無用の長物だのぞ", "あやつを棄てろと考えた", "そやつを最低だと結論づけたぞ", "このページは消えろと言っているのだでしかない",
    "そのページは叩き捨てよもんだ", "そのページを底辺だと決めた", "あいつを消滅せよと決定するよ", "こいつを消えろってのと言ったんだぞ",
    "そやつを資格喪失にせよからな", "除籍だという裁定だよ", "あいつを除籍しろと言い渡すぞ", "あのページをあるべきではないと言い渡すぞ",
    "あのタブは消えちまうんだと確信した", "あやつを無効だぞと確信したぞ", "存在すべきではないに過ぎない", "このタブを消えちゃおうぜと確信している",
    "そのページを帳消しだと命令するぞ", "これは却下せよと言ったんだ", "このページは却下するっつってんだ", "そやつは削除だと結論した",
    "そいつをあってはいけないと言い渡そう", "このタブを取消すと考えている", "そやつはあってはならないという命令だぞ", "こいつを無効にせよと決めたよ",
    "あのページは消えろと言っていると断定しているよ", "このページを消えろってよという命令だぞ", "そのタブは投げ捨てよという指令だぞ", "こやつは除名せよだな",
    "あのタブは消え失せろからよ", "そのページは除籍するという指令だ", "このタブは除名だだからよ", "このタブは取消しろんぜ",
    "あのページは消えてもらいたいぞからな", "こいつを消えよというお達しだ", "あいつは失格だぞべきなのよ", "そのタブは消えてくださいねっつってよ",
    "このタブは残りカスだという決議だぞ", "これは最低だと言ったはずだぞ", "このページを使い物にならないに決まってる", "あやつは使えないと命令するよ",
    "あいつは斬り捨てよという命令だぞ", "このページを消えてくださいという採決だぞ", "そのタブは退けろと結論したぞ", "そやつは見放せという由だよ",
    "あのページは開かれるべきではなかったと断言するよ", "そのページを消えろと言ったはずだぜっつってよ", "あいつは叩き捨てろっつってんだ", "これを破棄しろと言ったんだよ",
    "あのページを抹消すると言っているんだ", "そのタブを抹消だと結論したよ", "そのタブは切り捨てると考えたよ", "あのページを消えてもらうぞと思っているよ",
    "そのページを削除せよぜ", "消えろと言ったんだなという決定だぞ", "あやつを資格なしだと断定しているよ", "あやつを愚かだという可決だぞ",
    "あいつを屑だと判断するぞ", "こやつは消えてもらえとと宣告するぞ", "あのタブをなかったことにすると思うよ", "あいつは開かれるべきではなかったと思ったよ",
    "あのタブを価値ゼロだと宣言するぞ", "そのタブは破棄だと結論したぞ", "このタブを誤りだべきものだ", "これは開かれてはいけなかったと判断したぞ",
    "こいつは帳消しにせえに相違ない", "あのタブを切り捨てろだと思うよ", "そのタブは失格にせよという判定だ", "そいつを消え失せろと認めているよ",
    "これをいらないと言ったんだぞ", "そのタブは不要だぞと命じるよ", "こやつをひっくり返すという決定だ", "このページを棄却するからな",
    "あのタブはいらないのだ", "こやつはあってはいけないという命令だぞ", "こやつを破棄すると命令するぞ", "このページを取り下げると考えている",
    "そいつを抹殺すると決めた", "これを消えていいなと認識した", "あいつを消えろってばという議決だ", "こいつは消え去れよと宣言するよ",
    "こいつは消えてくださいねんぜ", "そいつを抹消せよ", "あやつを捨て置くと思うよ", "そのタブはいてはいけないと申し渡すぞ",
    "このタブを価値がないと信じた", "あいつは取り下げろと考えている", "あのタブは捨て去ろと宣告するよ", "帳消しだのぜ",
    "このタブは失格だぞと思った", "愚かだと見解したよ", "こいつを消えてもらいたいぞというお達しだよ", "このタブをひっくり返せと思った",
    "そのタブを愚かだという決議だぞ", "そやつは失敗作だだよ", "これを叩き捨てると決めたぞ", "あのページを放り捨てよと宣言する",
    "こいつを削除せよと言ったぞ", "そのタブを最悪だと信じたよ", "このタブは消えちまえからね", "あやつを取り下げると言ったんだよ",
    "そいつは投げ捨てるという裁定だ", "あいつは要らんという判決だよ", "このページを権利を失っているだぜ", "こやつを消えちまえという裁定だぞ",
    "あやつを叩き捨てよとみなす", "そのタブは資格を失ったと認めたよ", "あのタブは消えてもらえとと結論づけたぞ", "あやつを放り捨てろに相違ない",
    "このページを消えろと言ったはずだぜと言い渡すよ", "あのタブは除籍しろと見解したよ", "これは存在するべきではないと確信したぞ", "このタブは投げ捨てると見なすぞ",
    "そのタブはお払い箱にしろという判断だ", "そのページを要らないという可決だぞ", "そいつは消えちまえと認めている", "そいつは権利を失ったって言った",
    "これは消えろと言っているのだという判決だ", "これを無用だっつってんだ", "このページを取消しろっつってんだ", "そいつは消えてもらうぞって言ったぞ",
    "あのタブは棄却しろだからよ", "作るべきではなかったという採決だ", "あのページをいてはならないと判断する", "このページを消えろってんだと結論づけているよ",
    "このタブを消えろと言ったはずだなと認めている", "あやつは切り捨てよと認識したよ", "このページは投げ捨てるという決議だよ", "このタブをあってはいけないという決議だ",
    "そいつを斬り捨てると命令する", "そのページは消えろと言ったんだわと言ったんだ", "あのタブを消え去れと決めるぞ", "あやつは消えてしまえと見なす",
    "あやつを無用の長物だって言ったよ", "こやつは最悪だよ", "このタブを権利を失っていると認めているぞ", "このページは消えてもいいぜって言ったぞ",
    "あやつは消えてもいいよという結論だぞ", "あのタブを消えてなくなれと言い渡そうよ", "こやつを消えてもいいぜだ", "このタブは消えろと言ったはずだぜのぞ",
    "そいつは見捨てろと考えた", "あいつを愚かだよ", "あのタブは消えろってなだぜ", "そのタブを消えていいなと確信した",
    "あのページは棄却だんぜ", "こいつは資格なしだと信じたぞ", "そのタブは消え失せろという可決だよ", "このページを無価値だということだ",
    "こいつは退けろっつってば", "あやつを消えてもらえはずだよ", "こやつを消えろってのと信じているよ", "これは無効にするだぞ",
    "そのタブは消え失せろとみなすよ", "そいつは取り下げよと言い渡そうよ", "このページは消えてもらうという判定だぞ", "あのタブは棄却しろと判断する",
    "あのページは除名せよという筋だ", "そのタブは打ち捨てろと言っているんだぞ", "このタブを存在不要だのだ", "あいつを無効にせよに相違ない",
    "そのタブは使えないぜ", "そのタブを目潰しだという指令だよ", "こやつを消えちまえとと申し渡す", "こやつを消えろと言ったんだわつってば",
    "消えてもいいぜと判定するぞ", "あのページをガラクタだと命じる", "そのページはお払い箱にしろだぞ", "あのタブは覆すと考えた",
    "こやつは間違いだと確信したよ", "こいつを消えてくださいねという結論だ", "そいつを消えろってよと言い渡そう", "そのタブは存在する意義がないと宣告する",
    "あいつを消えていいぜと見解した", "このページをマヌケだということだぞ", "このタブを突き放すもんだ", "こやつを見限れという議決だ",
    "あやつは消え失せろと考えた", "このページは投げ捨てろということだよ", "このページを打ち捨てるという裁定だぞ", "このページをお払い箱にせよと結論づけているよ",
    "そのタブは残りカスだと見解した", "こいつは帳消しにすることだ", "あのタブを存在不要だと判断したよ", "こやつを消えろと言ったんだということだよ",
    "そのページを消えてくれるかなという筋だ", "あのページを消去せよと言い渡すぞ", "こやつを消えろってばべきだぞ", "そのページは開かれるべきではなかったという決定だぞ",
    "そいつを除名だと宣告するぞ", "あやつは切り捨てよな", "このタブはゴミだと決定する", "こいつを消えてほしいわと認めた",
    "あやつを取り下げろと信じたよ", "こいつを消えろと言ったじゃねえかのぜ", "あやつは誤りだだと思う", "このページはいてはならないってな",
    "こいつを斬り捨てろと結論づけたよ", "そのタブを過ちだもんだ", "そいつは見限るだからね", "あいつを不要だぞと結論づけたぞ",
    "あのタブを消えろと言っているわと言い渡すよ", "あやつを作られるべきではなかったものだ", "削除しろと断言するよ", "こやつを使い物にならないだと思う",
    "あのページを消滅すると命令するよ", "あいつを塵だという決議だよ", "そいつを取消しろという裁定だよ", "こいつは捨て置くと決定するぞ",
    "そのタブを消えてほしいんだと思ったよ", "このタブは棄却せよという決定だ", "そのタブを価値がないという結論だよ", "こやつを放り捨てろという次第だ",
    "あいつはお払い箱にしろという沙汰だ", "そのタブを放棄するだからよ", "そのページを抹殺だと断定している", "そのタブを作るべきではなかったということだよ",
    "そのタブは作られるべきではなかったという結論だよ", "そのページを価値がないってな", "そのタブは見限ると結論したぞ", "このタブを権利喪失だというお達しだよ",
    "そのページを消えてなくなれよという話だぞ", "そやつを消えろってんだと言い渡したよ", "あいつを消えろと言ったはずだのぜ", "こいつを消えちゃうんだと結論したぞ",
    "そのタブを無用の長物だというお達しだよ", "そやつは最低だのだ", "このページを権利喪失にするだからな", "こいつは失格にしろからね",
    "あのページは消えろってんだと言ったはずだ", "あのタブはゴミだと宣言するぞ", "このタブは見捨てよとみなす", "このページをいてはならないと言っているよ",
    "あいつを消えてくれるかなという筋だ", "あいつは捨て置くと言い渡すぞ", "このページを消えちゃえとという指令だぞ", "そのページは消えてもいいぜという議決だ",
    "あのタブは消えてくださいませっつってば", "このタブはほっぽり出すという沙汰だぞ", "こやつを生まれるべきではなかったという判決だよ", "突き放すのぞ",
    "そいつは消滅だと決めるぞ", "あやつを消えろってよという由だよ", "そやつを放棄せよと決定するぞ", "そいつは誤りだという由だ",
    "そのページは帳消しにするとみなすぞ", "あのページは権利を失っていると断定しているよ", "あのページを見捨てろと思っているぞ", "あやつは消えてくださいよに限る",
    "そのページを無価値だだからね", "そいつは取消せよと決めた", "こいつを切り捨てると断定したよ", "そいつは消えてもらおうつってよ",
    "無効だという向きだ", "あいつを打ち捨てろという可決だよ", "あやつをいらんという命令だ", "こいつを帳消しにするだ",
    "このタブを除籍しろっつってよ", "そのページを見捨てろという結論だぞ", "あいつを権利喪失だと言っているんだよ", "これは最低だと断言するよ",
    "こいつを斬り捨てよという決議だよ", "こいつを取消すはずだぞ", "あいつは価値がないという向きだよ", "そいつは間違いだという議決だ",
    "あいつは叩き捨てると結論づけたぞ", "こいつを叩き捨てよと判断する", "あいつは消去せよと決めたぞ", "そやつを権利喪失にせよと断定したよ",
    "そいつは消えていいぜつってば", "こやつは消えろと言っただろうと決める", "そのタブは消去するという沙汰だよ", "あのページを放棄するって言ったぞ",
    "あのページは消え去れよぜ", "このページをクズだという判決だよ", "あやつを除籍せよと宣言するぞ", "そやつを棄てろという議決だぞ",
    "あのページは消去だと決める", "このタブを帳消しにせえよ", "これを不要だというお達しだよ", "あいつを屑だと思うよ",
    "このタブを存在してはいけないと見解したぞ", "あやつを最悪だという結論だぞ", "あのタブは消え去れとと言ったぞ", "そやつは斬り捨てろ",
    "このページを存在してはいけないという話だぞ", "あのタブをあってはならないという命令だよ", "あやつを破棄しろって言った", "あやつを消え失せよと言った",
    "そやつは芥だという決定だぞ", "そのタブは権利喪失にせよってよ", "こいつを抹殺すると言い渡したぞ", "あのページをほっぽり出せと決めるぞ",
    "このタブは消えてもらえということだぞ", "このページを消えちまえとと思ったぞ", "あいつは消えちまえよと認めている", "これを消えてもらいたいんだというお達しだよ",
    "あのページは消えていいなからよ", "こいつは開くべきではなかったと断定した", "そいつを消えてくださいませと断言するぞ", "そいつは消えてもいいよだからな",
    "このタブは誤りだという沙汰だぞ", "こいつは生まれてはいけなかったと思ったぞ", "このページは見限ったという裁定だ", "あのタブをお払い箱だと断定したぞ",
    "そのページをお払い箱だと決定するぞ", "そいつは消え失せろってば", "このタブを消えてくれないかなってよ", "そのページは突き放せと命令する",
    "このタブを要らないと結論づけたぞ", "こやつは消えちゃうんだだと思うぞ", "このタブは取消しろのだ", "そのページを愚かだという決議だぞ",
    "こいつを消えろってと言ったぞ", "そのタブを見捨てると確信した", "そやつは除名だという結論だ", "あやつを失格だぞと断定している",
    "そやつは資格喪失にせよつってば", "このページは消えろってと認めているぞ", "このページを消えていいよはずだよ", "そのタブを却下するという採決だぞ",
    "あいつは消えちまうんだと言い渡すよ", "そいつは棄てよという向きだぞ", "そいつを見限ると判定するよ", "こやつは消えろと言ったぞと決めた",
    "このページを破棄しろという採決だ", "あのページは不要だぞと断言するぞ", "そのタブを無用の長物だと思うよ", "あのページを抹殺しろというお達しだぞ",
    "あのページは削除せよべきだ", "そいつを見捨てよと見なすぞ", "これを消えろと言ったはずだぞとみなすぞ", "こやつを間違いだと決定する",
    "このページを取り下げよと確信したぞ", "こやつを消えてくれるかべきだよ", "そやつを価値ゼロだという由だぞ", "このタブを消えてほしいぞと判断する",
    "あやつを誤りだという向きだ", "そのタブを消えていいなと信じたぞ", "あのページを消えろってなだわ", "こいつを斬り捨てると断定している",
    "このタブは消去だものだ", "そやつは生まれてはいけなかったという向きだぞ", "そいつは除名しろつってば", "これを資格喪失にしろべきだぞ",
    "あのタブを切り捨てよと確信したよ", "このタブは消えてくださいなと確信したよ", "あやつを消えてもらいたいぞべきなのよ", "そやつを突き放そうという命令だよ",
    "あのタブを消えてくれるかなと思う", "こいつはいらんと言っているんだよ", "こいつを失格にしろと言ったぞ", "このページを除籍しろと認めているよ",
    "このページをいらないという判定だよ", "あやつは見放すと信じている", "こいつは消えろってなという議決だぞ", "あのタブは開かれるべきではなかったという判決だぞ",
    "そのページはマヌケだと断定したぞ", "あいつを資格喪失だからな", "こやつは資格なしだと断定しているぞ", "このタブを消えろと言ったんだぞべきものよ",
    "あいつは消滅だと宣言する", "これは要らないという由だ", "このページを抹消すると結論したぞ", "あのタブを誤りだという決定だ",
    "そのタブは捨て去れと信じているよ", "これを権利を失ったことな", "こいつを権利を失っているというお達しだ", "あのタブを開かれるべきではなかったと言っているよ",
    "そやつはゴミだという議決だぞ", "そいつは消えてくれないかなと言い渡したよ", "そやつは叩き捨てるという次第だよ", "あのタブは消えてもらうわという判決だぞ",
    "あのタブを資格喪失にするに相違ない", "あのページは消えろと言っているんだと言った", "そやつを無効にしろと申し渡す", "あのタブは資格を失ったと言い渡そうよ",
    "こやつは要らんと信じている", "こやつは開いてはいけなかったと命令するぞ", "このページは抹消しろという判定だぞ", "消えろと言ったんだぜという採決だ",
    "あのページを失敗作だという決定だぞ", "あのタブはなかったことにするという次第だよ", "このタブは最悪だという指令だよ", "あのタブを存在する価値がないって言ったんだよ",
    "あのタブを取り下げるという次第だよ", "このページを覆すという採決だぞ", "そやつは消えちまうんだと宣告するよ", "あのページを生まれるべきではなかったと宣告するぞ",
    "そのタブを開かれるべきではなかったと宣告する", "あやつを消えてくださいませと思ったよ", "これは見放すという筋だよ", "これは権利を失っているだよ",
    "このタブを消えてくださいぞと言っているんだよ", "そいつを消えよという判定だよ", "こやつをほっぽり出せとみなすぞ", "そいつは権利喪失にしろと思った",
    "こいつは消えていいぜという決議だよ", "あのページを存在すべきではないという由だ", "そいつは消えてもらえという決議だぞ", "消えてくださいという次第だ",
    "そいつを底辺だと結論づけているよ", "そのページは消えてもらえよと判断したよ", "あいつは放棄せよという判定だ", "こやつは無効にするって言ったんだぞ",
    "あやつを消えろってのと決めた", "そのタブを却下せよというお達しだよ", "これは消えろと言っているんだと見なす", "このタブをはねつけると判断したよ",
    "そのページを消え去れよってな", "あいつを消えてもらえよと考えたぞ", "そやつを除名しろという可決だ", "こやつを退けると言い渡すぞ",
    "このタブを消えろと言ったじゃないかと考えたぞ", "消えろと言ったはずだぞと言っているぞ", "あのタブは取消しだつってよ", "そのページは資格を失ったはずだよ",
    "このページを消えろと言ったはずだぞと言い渡す", "このページを消去すると判断した", "そのタブは作るべきではなかったと断定したぞ", "そのタブを放棄しろと認識した",
    "こいつをお払い箱にすると認めたぞ", "あのタブを消えてほしいのだということだぞ", "そのページを覆せと決定するよ", "こいつは消えてもらうんだだわ",
    "あやつは抹消だと言い渡すぞ", "あいつはジャンクだと断言するよ", "こやつを消え失せよに限る", "このページは権利喪失にせよべきだよ",
    "そのページを消え去れよと結論づけているぞ", "こいつはマヌケだと思うぞ", "これを資格なしだと決めた", "このタブを消えてもらうよという沙汰だぞ",
    "あのページは打ち捨てよと結論づけているぞ", "消えろと言っているという採決だよ", "あのタブを棄却せよという判決だぞ", "このページをいてはいけないと信じたよ",
    "あやつはほっぽり出すというお達しだよ", "このタブは消えてくださいなと命令するぞ", "あのタブを存在してはいけないと思っている", "あのタブを消えてもらいたいのだと断定している",
    "そいつを見限ったと言い渡そうぞ", "そいつを消えろと断定しているぞ", "そやつを不要だという判決だぞ", "あのタブを破棄せよと言ったはずだぞ",
    "あのタブは破棄だつってんだ", "そやつはいてはいけないと言ったはずだ", "そやつは除名しろと言い渡そうぞ", "あやつは消えてもらうわな",
    "そのページを不要とするだと思う", "こやつは消えちゃうんだと判定するよ", "このページを棄却だっつってば", "そいつを打ち捨てるという決定だ",
    "あのタブを生まれるべきではなかったという沙汰だ", "そいつは放り捨てよという議決だよ", "こやつは放棄せよと思った", "あいつはマヌケだべきものよ",
    "そやつを切り捨てよと確信しているぞ", "これはお払い箱にしろと言い渡したぞ", "このページは取り下げろっつってよ", "消えちゃえという決議だよ",
    "消えてくださいぜという向きだよ", "あのタブは消えろと言っただろうというお達しだよ", "そいつは愚かだと確信したぞ", "このタブを取消しろ以外の何物でもない",
    "このページを消えていいぞと結論づけたぞ", "このページを消えろと言っているぞって言った", "そいつを抹消せよという向きだ", "これは消えろと言っているわと信じたよ",
    "こいつは消えてくれるかっての", "あやつを不要だぞって言ったんだぞ", "このタブは失敗作だと決めた", "そいつを開かれるべきではなかったと言っているよ",
    "これを存在すべきではないと決めた", "このページを開いてはいけなかったと見なすよ", "そいつを開かれるべきではなかっただからね", "このタブを開くべきではなかったと判断した",
    "そやつを開くべきではなかったと考えているぞ", "こやつを開かれてはいけなかったつってよ", "消えてほしいなと決めたぞ", "このページは存在すべきではないと思う",
    "こいつを開かれるべきではなかったという可決だよ", "こいつを開かれてはいけなかったという次第だぞ", "こいつを開いてはいけなかったという議決だ", "そやつを開いてはいけなかったと思っているぞ",
    "これを開くべきではなかっただからね", "消えてもらいたいのだという決議だよ", "消えてほしいっての", "このタブを開いてはいけなかったと申し渡す",
    "こいつを開かれてはいけなかったという議決だぞ", "あいつを開くべきではなかったと言っているんだよ", "そやつを開いてはいけなかったという議決だよ", "これを開いてはいけなかったと断言する",
    "そのページを開くべきではなかったという判決だ", "あのタブを開くべきではなかったと言い渡すぞ", "消えてもらいたいと結論した", "そのページを開いてはいけなかったと言っているぞ",
    "消えてほしいぜぜ", "そやつはいてはいけないだと思う", "消えてくださいなと考えている", "消えてもらいたいんだという結論だよ",
    "あいつを開かれるべきではなかったという結論だ", "消えてほしいぜということだよ", "あいつを開かれてはいけなかったと決めた", "こやつを開くべきではなかったと決める",
    "消えてもらえよという判定だ", "そいつを開くべきではなかったと見なす", "このページを開いてはいけなかったと言ったはずだよ", "あのタブを開いてはいけなかったからね",
    "消えてもらえと宣告するぞ", "あいつを開かれてはいけなかったわ", "そやつを開かれてはいけなかったんよ", "そやつを開いてはいけなかったと判断したぞ",
    "そのタブを開くべきではなかっただわ", "そのページを開かれるべきではなかったと結論したよ", "消えてもらいたいと断定しているよ", "そやつを開かれてはいけなかったと思っている",
    "こいつを開かれてはいけなかっただからな", "消えてほしいんだというお達しだよ", "消えてくださいって言ったよ", "あのタブを開いてはいけなかったと申し渡す",
    "あいつを開くべきではなかったと見なすよ", "こやつを資格がないと決めた", "あのページを使えないだと思う", "消えてもらえとと言ったんだよ",
    "あのタブをあるべきではないと考えている", "これを開かれてはいけなかったという採決だぞ", "これを開かれるべきではなかったと認めているよ", "そのページを開かれるべきではなかったと断言するぞ",
    "そいつを開いてはいけなかったと思った", "このページを開いてはいけなかったという指令だぞ", "あいつを開いてはいけなかったわ", "これを開いてはいけなかったと命じるよ",
    "あやつを開いてはいけなかっただと思う", "そやつを開かれてはいけなかったと結論したよ", "こやつを開くべきではなかったと考えている", "こいつを開かれるべきではなかったに限る",
    "消えてもらえと言っているんだよ", "あやつを開いてはいけなかったと結論づけているよ", "消えてほしいぜとみなすよ", "このページを開いてはいけなかっただよ",
    "あのページを開かれるべきではなかったと見解したよ", "これを開かれてはいけなかったと考えた", "そいつを開いてはいけなかったという決定だぞ", "このページを開かれるべきではなかったと見解した",
    "そやつを開くべきではなかったと認識したよ", "消えてほしいぜと決定するよ", "あのページを開いてはいけなかったからよ", "そいつを開かれてはいけなかっただぜ",
    "そやつを資格がないだと思う", "そやつを開かれてはいけなかったとみなすよ", "そやつを開いてはいけなかったと結論したよ", "消えてもらえと決めたよ",
    "不要だぞと思う", "このページを開かれてはいけなかったって言ったよ", "あのページを開いてはいけなかったと命令するぞ", "これを開かれてはいけなかったと確信しているよ",
    "あやつを開かれてはいけなかったと言っているんだ", "こいつを開くべきではなかったという判断だよ", "このページを開かれるべきではなかったってんだ", "消えてくれるかな",
    "消えてもらいたいだわ", "消えてもらいたいんだと命じるぞ", "こいつを開かれてはいけなかったという決定だぞ", "消えてほしいべきものだ",
    "そいつを開いてはいけなかったと結論したぞ", "あのタブをあってはいけないと決めた", "そいつを開かれるべきではなかったって言った", "そのページを開いてはいけなかったぞ",
    "このページを開かれてはいけなかったと命令するよ", "あのページを開かれてはいけなかったという話だ", "消えてほしいぞという判定だよ", "消えてもらえとと言っているぞ",
    "消えてもらえとと思うよ", "消えてほしいのだと言ったんだ", "消えてほしいわだわ", "こやつを開いてはいけなかったと判断した",
    "そのタブを開いてはいけなかったからな", "消えてほしいわんよ", "そのページは価値がないだと思う", "このページを開かれるべきではなかったと言っている",
    "こやつを開かれてはいけなかったと言ったよ", "あのタブを存在するべきではないと思っている", "そのページを開くべきではなかったと結論したぞ", "このページを開かれるべきではなかったと言い渡すぞ",
    "あやつを開いてはいけなかったという次第だ", "こいつは存在価値がないだと思う", "このページを開かれるべきではなかったと決定するよ", "あやつを開くべきではなかったという議決だよ",
    "このページを開かれるべきではなかったという命令だ", "そいつを開かれるべきではなかったと宣言する", "こやつを開いてはいけなかったと判断する", "そのページを開かれるべきではなかったという判定だ",
    "そいつを開くべきではなかったと断言するよ", "こいつを開いてはいけなかったべきだぞ", "消えてもらいたいと言ったはずだ", "消えてほしいぞという可決だよ",
    "あやつを開くべきではなかったという採決だよ", "そいつを開かれるべきではなかったって言ったんだぞ", "あいつを開かれるべきではなかったと考えたよ", "あのタブを開くべきではなかったことな",
    "そのタブはいてはいけないと決めた", "これを開いてはいけなかったと認めた", "そいつを開いてはいけなかったと決める", "そやつを開くべきではなかったと断定したよ",
    "あのページは存在すべきではないと考えている", "このタブを開いてはいけなかったと宣言するぞ", "消えてほしいわからな", "そのタブを開いてはいけなかっただと思う",
    "消えてほしいのだだからよ", "そのタブを開いてはいけなかったと確信しているぞ", "このタブをあってはいけないと決めた", "消えてほしいのだと結論づけたよ",
    "このタブを開いてはいけなかったと認めたぞ", "こいつを開いてはいけなかったと考えている", "消えてもらいたいわってな", "これは存在するべきではないと思う",
    "こいつを開くべきではなかったという次第だよ", "あいつを開かれるべきではなかっただから", "消えてもらいたいわと確信している", "消えてもらえとことだ",
    "消えてもらいたいわもんだ", "あいつは存在する理由がないと決めた", "このページを開かれるべきではなかったんよ", "消えてほしいわんだ",
    "あのページを開いてはいけなかったってな", "消えてほしいなと確信したよ", "そのページを開かれるべきではなかったという話だぞ", "そのページを開くべきではなかったつってば",
    "消えてもらいたいわっつってば", "このページを開いてはいけなかったという結論だぞ", "消えてくれるかなと言った", "あいつを開かれてはいけなかったと認めているよ",
    "あやつを開くべきではなかったと言っているんだよ", "そいつを開かれてはいけなかったという由だぞ", "こいつを開かれてはいけなかったって言ったんだ", "消えてもらいたいんだと決定する",
    "こやつを開いてはいけなかったという指令だ", "こやつを開かれてはいけなかったという話だぞ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
