// Pass CCLXI: EN raze/behead/shred + JA execution verbs (pass CCLXI)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXI: close-tab coverage', () => {
  test.each([
    "raze it to the ground", "raze it to ashes", "raze it to ash", "raze it to dust",
    "raze it to nothing", "raze it to rubble", "raze it to the earth", "raze it flat",
    "raze it completely", "raze it entirely", "raze it totally", "raze it utterly",
    "raze it down completely", "raze it down to the ground", "raze it down to ashes", "raze it down to nothing",
    "demolish it completely", "demolish it entirely", "demolish it totally", "demolish it utterly",
    "demolish it beyond recognition", "demolish it beyond repair", "demolish it beyond saving", "demolish it into rubble",
    "demolish it into dust", "demolish it into nothing", "demolish it into the ground", "demolish it to the ground",
    "demolish it to rubble", "demolish it to dust", "demolish it to nothing", "demolish it to ash",
    "demolish it to ashes", "demolish it flat", "demolish it down completely", "demolish it down to the ground",
    "demolish it down to nothing", "level it to the ground", "level it flat", "level it completely",
    "level it entirely", "level it totally", "level it utterly", "level it to rubble",
    "level it to dust", "level it to nothing", "level it to ash", "level it to ashes",
    "level it down completely", "level it down to the ground", "level it down to nothing", "flatten it totally",
    "flatten it utterly", "flatten it to the ground", "flatten it into the earth", "flatten it into rubble",
    "flatten it into dust", "flatten it into nothing", "flatten it into the earth itself", "flatten it into the earth forever",
    "bulldoze the tab", "bulldoze it flat", "bulldoze it completely", "bulldoze it to the ground",
    "bulldoze it into the ground", "bulldoze it into the earth", "bulldoze it down completely", "bulldoze it down to the ground",
    "bulldoze it into rubble", "bulldoze it into dust", "bulldoze it into nothing", "bulldoze it into a pile of rubble",
    "wreck it completely", "wreck it utterly", "wreck it totally",
    "wreck it beyond repair", "wreck it beyond saving", "wreck it beyond recognition", "wreck it into a pile of wreckage",
    "wreck it into a pile of rubble", "total it completely", "total it utterly", "total it beyond repair",
    "write it off completely", "write it off utterly", "write it off as a total loss", "write it off as a total wreck",
    "write it off as beyond repair", "write it off as beyond saving", "write it off as done", "write it off as finished",
    "write it off as gone", "write it off as dead", "write it off as history", "write it off as a goner",
    "write it off as a lost cause", "write it off as doomed", "write it off as doomed beyond repair", "write it off as beyond all hope",
    "write it off as beyond all help", "write it off as beyond all repair", "write it off as beyond all saving", "write it off as a complete loss",
    "write it off as a complete wreck", "write it off as a complete write-off", "write it off as a complete loss forever", "write it off for good",
    "write it off for eternity", "write it off forever", "write it off permanently", "write it off once and for all",
    "knock it down flat", "knock it down completely", "knock it down to the ground", "knock it down to rubble",
    "knock it down to dust", "knock it down to nothing", "knock it down into rubble", "knock it down into dust",
    "knock it down into nothing", "knock it flat", "knock the tab flat", "knock it flat completely",
    "knock it to the ground", "knock it to the earth", "knock it to rubble", "knock it to dust",
    "knock it to nothing", "knock it over", "knock the tab over", "knock it over completely",
    "knock it over and out", "knock it over flat", "topple it", "topple the tab",
    "topple it completely", "topple it to the ground", "topple it to the earth", "topple it into rubble",
    "topple it into dust", "topple it into nothing", "topple it over", "topple it over completely",
    "topple it over flat", "pull the tab down", "pull it down completely", "pull it down to the ground",
    "pull it down to rubble", "pull it down to nothing", "pull it down flat", "tear the tab down",
    "tear it down completely", "tear it down to the ground", "tear it down to rubble", "tear it down to nothing",
    "tear it down flat", "tear it down utterly", "tear it down entirely", "tear it down to ashes",
    "tear it down to dust", "bring the tab down", "bring it down completely", "bring it down to the ground",
    "bring it down to rubble", "bring it down to nothing", "bring it down flat", "bring it down hard",
    "bring it down for good", "take it down completely", "take it down to the ground", "take it down to rubble",
    "take it down to nothing", "take it down flat", "take it down hard", "take it down for good",
    "take it down permanently", "take it down forever", "take it down once and for all", "tear it apart completely",
    "tear it apart utterly", "tear it apart piece by piece", "tear it apart limb from limb", "tear it apart from limb to limb",
    "tear it apart into pieces", "tear it apart into bits", "tear it apart into nothing", "tear it to pieces completely",
    "tear it to pieces utterly", "tear it to bits completely", "tear it to shreds completely", "tear it to shreds utterly",
    "tear it to ribbons", "tear it to ribbons completely", "tear it to tatters", "tear it to tatters completely",
    "tear it to smithereens", "tear it to smithereens completely", "tear it to rubble", "tear it to dust",
    "tear it to nothing", "tear it to ash", "tear it to ashes", "tear it into pieces",
    "tear it into bits", "tear it into shreds", "tear it into ribbons", "tear it into tatters",
    "tear it into smithereens", "tear it into rubble", "tear it into dust", "tear it into nothing",
    "tear it into ash", "tear it into ashes", "shred it completely", "shred it utterly",
    "shred it to bits", "shred it to nothing", "shred it into pieces", "shred it into bits",
    "shred it into ribbons", "shred it into nothing", "shred it to a pulp", "shred it to pulp",
    "shred it to confetti", "shred it into confetti", "shred it like paper", "shred it like a document",
    "shred it like a file", "shred it like evidence", "shred it like classified documents", "shred it like top secret files",
    "shred it to oblivion", "shred it into oblivion", "shred it to the void", "shred it into the void",
    "shred it to atoms", "shred it into atoms", "shred it to molecules", "shred it into molecules",
    "shred it to particles", "shred it into particles", "shred it to quarks", "shred it into quarks",
    "shred it to nothing at all", "shred it into nothing at all", "shred it beyond recognition", "shred it beyond repair",
    "shred it beyond saving", "shred it beyond help", "shred it beyond all hope", "shred it beyond all repair",
    "shred it beyond all saving", "shred it beyond all help", "rip it to shreds completely", "rip it to pieces completely",
    "rip it to bits completely", "rip it apart completely", "rip it into pieces", "rip it into bits",
    "rip it into shreds", "rip it into nothing", "rip it into atoms", "rip it into molecules",
    "rip it up completely", "rip it up utterly", "rip it up to nothing", "rip it up into pieces",
    "rip it up into shreds", "rip it up into nothing", "tear it up completely", "tear it up utterly",
    "tear it up to nothing", "tear it up into pieces", "tear it up into shreds", "tear it up into nothing",
    "tear it up like a contract", "tear it up like a receipt", "tear it up like a ticket", "tear it up like a letter",
    "tear it up like a bill", "tear it up like an invoice", "tear it up like a will", "tear it up like a contract it never wanted",
    "tear it up like a bad check", "tear it up like a bad draft", "tear it up like a bad sketch", "tear it up like a bad drawing",
    "tear it up like a bad plan", "tear it up like a bad map", "tear it up like a bad chart", "tear it up like a bad diagram",
    "tear it up like a bad schematic", "tear it up like a bad layout", "tear it up like a bad mockup", "tear it up like a bad wireframe",
    "tear it up like a bad prototype", "tear it up like a bad design", "tear it up like a bad sketch pad", "tear it up like a bad doodle",
    "tear it up like a bad scribble", "tear it up like a bad draft of a draft", "tear it up like it owes me money", "tear it up like it owes me rent",
    "tear it up like it owes me a favor", "tear it up like it wronged me", "tear it up like it offended me", "tear it up like it insulted me",
    "tear it up like it disrespected me", "tear it up like it crossed me", "tear it up like it betrayed me", "tear it up like it lied to me",
    "tear it up like it deceived me", "tear it up like it failed me", "tear it up like it let me down", "tear it up like it disappointed me",
    "tear it up like it broke my heart", "tear it up like it broke my trust", "tear it up like it broke my faith", "tear it up like it shattered my hopes",
    "tear it up like it crushed my dreams", "tear it up like it ruined my day", "tear it up like it ruined my week", "tear it up like it ruined my month",
    "tear it up like it ruined my year", "tear it up like it ruined my life", "tear it up like it wasted my time", "tear it up like it wasted my effort",
    "tear it up like it wasted my energy", "tear it up like it wasted my patience", "tear it up like it wasted my attention", "tear it up like it wasted my bandwidth",
    "tear it up like it wasted my memory", "tear it up like it wasted my cpu", "tear it up like it wasted my gpu", "tear it up like it wasted my resources",
    "tear it up like it wasted my pixels", "tear it up like it wasted my frames", "tear it up like it wasted my milliseconds", "tear it up like it wasted my nanoseconds",
    "tear it up like it wasted every moment it existed", "tear it up like it wasted every byte it occupied", "tear it up like it wasted every pixel it drew", "tear it up like it wasted every frame it rendered",
    "tear it up like it wasted every second it lived", "tear it up like it wasted every second of its miserable existence", "tear it up like it wasted every electron", "tear it up like it wasted every photon",
    "tear it up like it wasted every quantum of existence", "tear it up like it wasted every bit of reality it touched", "tear it up like it wasted the space it occupied", "tear it up like it wasted the air it displaced",
    "tear it up like it wasted the photons it reflected", "tear it up like it wasted the electrons it consumed", "tear it up like it wasted the bandwidth it demanded", "tear it up like it wasted the memory it claimed",
    "tear it up like it wasted the time it stole", "tear it up like it wasted the life it squandered", "tear it up like it wasted the existence it abused", "behead it cleanly",
    "behead it swiftly", "behead it mercilessly", "behead it without mercy", "behead it without hesitation",
    "behead it without delay", "behead it in the public square", "behead it in the town square", "behead it at dawn",
    "behead it at noon", "behead it at dusk", "behead it at midnight", "behead it on the scaffold",
    "behead it on the block", "behead it on the chopping block", "behead it on the headsman block", "behead it before the crowd",
    "behead it before the mob", "behead it before the masses", "behead it before the public", "behead it before all witnesses",
    "behead it for all to see", "behead it for the crowd to see", "behead it for the mob to see", "behead it for the masses to see",
    "behead it for the world to see", "behead it for everyone to see", "behead it for all eternity", "behead it for eternity",
    "behead it forever", "behead it once and forever", "decapitate it cleanly", "decapitate it swiftly",
    "decapitate it mercilessly", "decapitate it completely", "decapitate it at dawn", "decapitate it on the scaffold",
    "decapitate it on the block", "decapitate it in the public square", "decapitate it for all to see", "decapitate it for eternity",
    "decapitate it forever", "send it to madame guillotine", "send the tab to madame guillotine", "send it to the national razor",
    "send it to the french widow", "feed it to the guillotine", "feed the tab to the guillotine", "feed it to madame guillotine",
    "feed it to the national razor", "introduce it to the guillotine", "introduce it to madame guillotine", "put it through the guillotine",
    "put it under the blade", "put it under the guillotine", "put it under madame guillotine", "put it under the national razor",
    "put it beneath the blade", "put it beneath the guillotine", "put it beneath madame guillotine", "put it beneath the national razor",
    "put its head on the block", "put the tabs head on the block", "put its head under the blade", "put its head beneath the blade",
    "put its neck on the block", "put its neck under the blade", "put its neck beneath the blade", "lay its head on the block",
    "lay its head under the blade", "lay its head beneath the blade", "lay its neck on the block", "lay its neck under the blade",
    "lay its neck beneath the blade", "stretch its neck on the block", "stretch its neck under the blade", "offer its head to the blade",
    "offer its neck to the blade", "offer its head to the guillotine", "offer its neck to the guillotine", "offer its head to madame guillotine",
    "offer its neck to madame guillotine", "offer its head to the national razor", "offer its neck to the national razor", "deliver its head to the blade",
    "deliver its neck to the blade", "deliver its head to the guillotine", "deliver its neck to the guillotine", "deliver its head to the block",
    "deliver its neck to the block", "hand its head to the blade", "hand its neck to the blade", "hand its head to the guillotine",
    "hand its neck to the guillotine", "hand its head to the block", "hand its neck to the block", "let the blade fall",
    "let the guillotine fall", "let the blade drop", "let the guillotine drop", "let the blade descend",
    "let the guillotine descend", "let the blade do its work", "let the guillotine do its work", "let the national razor do its work",
    "let madame guillotine do her work", "let madame guillotine work", "let the headsman work", "let the executioner work",
    "let the axe fall", "let the axe drop", "let the axe descend", "let the axe swing",
    "let the axe swing down", "let the axe come down", "let the axe do its work", "let the headsman axe fall",
    "let the headsman axe drop", "let the headsman axe descend", "let the headsman axe swing", "let the executioner axe fall",
    "let the executioner axe drop", "let the executioner axe descend", "let the executioner axe swing", "let the headsman do his work",
    "let the headsman do his job", "let the executioner do his work", "let the executioner do his job", "let the headsman do his duty",
    "let the executioner do his duty", "let the axe do the talking", "let the axe do the rest", "let the axe finish it",
    "let the axe end it", "let the axe conclude it", "let the axe settle it", "let the axe decide",
    "let the blade finish it", "let the blade end it", "let the blade conclude it", "let the blade settle it",
    "let the blade decide", "let the guillotine finish it", "let the guillotine end it", "let the guillotine conclude it",
    "let the guillotine settle it", "let the guillotine decide", "let the headsman finish it", "let the headsman end it",
    "let the headsman conclude it", "let the headsman settle it", "let the headsman decide", "let the executioner finish it",
    "let the executioner end it", "let the executioner conclude it", "let the executioner settle it", "let the executioner decide",
    "axe it to pieces", "axe it to bits", "axe it to nothing", "axe it into pieces",
    "axe it into bits", "axe it into nothing", "axe it beyond recognition", "axe it beyond repair",
    "axe it to death", "axe it to death on the block", "axe it to death at dawn", "axe it to death on the scaffold",
    "axe it to death in the public square", "axe it to death for all to see", "chop the tabs head off", "chop its head off cleanly",
    "chop its head off swiftly", "chop its head off at dawn", "chop its head off on the block", "chop its head off in the public square",
    "chop its head off for all to see", "cut the tabs head off", "cut its head off cleanly", "cut its head off swiftly",
    "cut its head off at dawn", "cut its head off on the block", "cut its head off in the public square", "cut its head off for all to see",
    "slice the tabs head off", "slice its head off cleanly", "slice its head off swiftly", "sever the tabs head",
    "sever its head cleanly", "sever its head swiftly", "sever its head from its body", "sever its head from its shoulders",
    "sever its head from its neck", "sever its head from its shoulders cleanly", "sever its head at dawn", "sever its head on the block",
    "sever its head in the public square", "sever its head for all to see", "lop the tabs head off", "lop its head off cleanly",
    "lop its head off swiftly", "lop its head off at dawn", "lop its head off on the block", "lop its head off in the public square",
    "lop its head off for all to see", "take its head off", "take the tabs head off", "take its head off cleanly",
    "take its head off swiftly", "take its head off at dawn", "take its head off on the block", "take its head off in the public square",
    "take its head off for all to see", "remove its head", "remove the tabs head", "remove its head cleanly",
    "remove its head swiftly", "remove its head at dawn", "remove its head on the block", "remove its head in the public square",
    "remove its head for all to see", "strike its head off", "strike the tabs head off", "strike its head off cleanly",
    "strike its head off swiftly", "strike its head off at dawn", "strike its head off on the block", "strike its head off in the public square",
    "strike its head off for all to see", "hang it until dead", "hang it until it dies",
    "hang it until it stops twitching", "hang it until it is dead", "hang it high", "hang it high for all to see",
    "hang it in the public square", "hang it in the town square", "hang it at dawn", "hang it at noon",
    "hang it at dusk", "hang it at midnight", "hang it from the gallows", "hang it from the scaffold",
    "hang it from a gibbet", "hang it from the highest tree", "hang it from the highest branch", "hang it from the tallest tree",
    "hang it from the tallest branch", "hang it from the tallest gallows", "hang it from the tallest gibbet", "hang it for all to see",
    "hang it for the crowd to see", "hang it for the mob to see", "hang it for the masses to see", "hang it for the world to see",
    "hang it for everyone to see", "hang it for the birds", "hang it for the crows", "hang it for the ravens",
    "hang it for the vultures", "hang it for the buzzards", "hang it for carrion birds", "hang it for the scavengers",
    "hang it for predators", "hang it for eternity", "hang it forever", "hang it permanently",
    "hang it once and for all", "hang it high and let it swing", "hang it high and let it sway", "hang it high and let it twist",
    "hang it high and let it creak", "hang it high and let it rot", "hang it high and let it decay", "hang it high and let it mummify",
    "hang it high and let it dry", "hang it high and let it wither", "hang it high and let it shrivel", "hang it high and let it desiccate",
    "hang it high and let it fossilize", "hang it high and let it petrify", "hang it high and let it turn to bone", "hang it high and let it turn to bones",
    "hang it high and let it turn to dust", "hang it high and let it turn to ash", "hang it high and let it turn to nothing", "hang it high and let it fade",
    "hang it high and let it fade away", "hang it high and let it fade to nothing", "hang it high and let it swing in the wind", "hang it high and let it sway in the wind",
    "hang it high and let it twist in the wind", "hang it high and let it creak in the wind", "hang it high and let it rot in the wind", "hang it high and let it decay in the wind",
    "hang it high and let it swing for eternity", "hang it high and let it sway for eternity", "hang it high and let it twist for eternity", "hang it high and let it creak for eternity",
    "hang it high and let it rot for eternity", "hang it high and let it swing forever", "hang it high and let it sway forever", "hang it high and let it twist forever",
    "hang it high and let it creak forever", "hang it high and let it rot forever", "hang it high and let it be a warning", "hang it high and let it be an example",
    "hang it high and let it be a lesson", "hang it high and let it be a deterrent", "hang it high and let it be a reminder", "hang it high and let it be a symbol",
    "hang it high and let it be a monument", "hang it high and let it be a trophy", "hang it high and let it be a sign", "hang it high and let it be a signal",
    "hang it high and let it be a beacon", "hang it high and let it be a message to all tabs", "hang it high and let it be a message to every tab", "hang it high and let it be a message to all who see it",
    "hang it high and let it be a message for eternity", "hang it high and let it be a message forever", "tear it up like a bad blueprint", "誅しろ",
    "誅して", "誅するんだ", "誅しろよ", "誅してしまえ",
    "誅しちまえ", "誅しちゃえ", "誅しとけ", "誅したまえ",
    "誅しやがれ", "誅しろや", "誅しろって", "誅しろと言ってんだ",
    "誅するつもりだ", "誅するわ", "誅するぞ", "誅するぜ",
    "誅するからな", "誅することにした", "誅するのが筋だ", "誅するのが正解だ",
    "誅するということだ", "誅するという決定だ", "誅するという判断だ", "誅することに決めた",
    "誅することに決めたんだ", "誅することに決めたぞ", "誅することに決めたぜ", "誅滅して",
    "誅滅するんだ", "誅滅すべきだ", "誅滅してしまえ", "誅滅しちまえ",
    "誅滅しちゃえ", "誅滅しとけ", "誅滅したまえ", "誅滅しやがれ",
    "誅滅しろや", "誅滅しろと言ってんだ", "誅滅するつもりだ", "誅滅するわ",
    "誅滅するぞ", "誅滅するぜ", "誅滅するからな", "誅滅することにした",
    "誅滅するのが筋だ", "誅滅するのが正解だ", "誅滅するということだ", "誅滅するという決定だ",
    "誅滅するという判断だ", "誅滅することに決めた", "誅滅することに決めたんだ", "誅滅することに決めたぞ",
    "誅滅することに決めたぜ", "誅伐して", "誅伐するんだ", "誅伐すべきだ",
    "誅伐してしまえ", "誅伐しちまえ", "誅伐しちゃえ", "誅伐しとけ",
    "誅伐したまえ", "誅伐しやがれ", "誅伐しろや", "誅伐しろと言ってんだ",
    "誅伐するつもりだ", "誅伐するわ", "誅伐するぞ", "誅伐するぜ",
    "誅伐するからな", "誅伐することにした", "誅伐するのが筋だ", "誅伐するのが正解だ",
    "誅伐するということだ", "誅伐するという決定だ", "誅伐するという判断だ", "誅伐することに決めた",
    "誅伐することに決めたんだ", "誅伐することに決めたぞ", "誅伐することに決めたぜ", "誅戮しろ",
    "誅戮して", "誅戮するんだ", "誅戮しろよ", "誅戮すべきだ",
    "誅戮してしまえ", "誅戮しちまえ", "誅戮しちゃえ", "誅戮しとけ",
    "誅戮したまえ", "誅戮しやがれ", "誅戮しろや", "誅戮しろって",
    "誅戮しろと言ってんだ", "誅戮するつもりだ", "誅戮するわ", "誅戮するぞ",
    "誅戮するぜ", "誅戮するからな", "誅戮することにした", "誅戮するのが筋だ",
    "誅戮するのが正解だ", "誅戮するということだ", "誅戮するという決定だ", "誅戮するという判断だ",
    "誅戮することに決めた", "誅戮することに決めたんだ", "誅戮することに決めたぞ", "誅戮することに決めたぜ",
    "征伐しろ", "征伐して", "征伐するんだ", "征伐しろよ",
    "征伐すべきだ", "征伐してしまえ", "征伐しちまえ", "征伐しちゃえ",
    "征伐しとけ", "征伐したまえ", "征伐しやがれ", "征伐しろや",
    "征伐しろって", "征伐しろと言ってんだ", "征伐するつもりだ", "征伐するわ",
    "征伐するぞ", "征伐するぜ", "征伐するからな", "征伐することにした",
    "征伐するのが筋だ", "征伐するのが正解だ", "征伐するということだ", "征伐するという決定だ",
    "征伐するという判断だ", "征伐することに決めた", "征伐することに決めたんだ", "征伐することに決めたぞ",
    "征伐することに決めたぜ", "撲滅しろ", "撲滅して", "撲滅するんだ",
    "撲滅しろよ", "撲滅すべきだ", "撲滅してしまえ", "撲滅しちまえ",
    "撲滅しちゃえ", "撲滅しとけ", "撲滅したまえ", "撲滅しやがれ",
    "撲滅しろや", "撲滅しろって", "撲滅しろと言ってんだ", "撲滅するつもりだ",
    "撲滅するわ", "撲滅するぞ", "撲滅するぜ", "撲滅するからな",
    "撲滅することにした", "撲滅するのが筋だ", "撲滅するのが正解だ", "撲滅するということだ",
    "撲滅するという決定だ", "撲滅するという判断だ", "撲滅することに決めた", "撲滅することに決めたんだ",
    "撲滅することに決めたぞ", "撲滅することに決めたぜ", "掃滅しろ", "掃滅して",
    "掃滅するんだ", "掃滅しろよ", "掃滅すべきだ", "掃滅してしまえ",
    "掃滅しちまえ", "掃滅しちゃえ", "掃滅しとけ", "掃滅したまえ",
    "掃滅しやがれ", "掃滅しろや", "掃滅しろって", "掃滅しろと言ってんだ",
    "掃滅するつもりだ", "掃滅するわ", "掃滅するぞ", "掃滅するぜ",
    "掃滅するからな", "掃滅することにした", "掃滅するのが筋だ", "掃滅するのが正解だ",
    "掃滅するということだ", "掃滅するという決定だ", "掃滅するという判断だ", "掃滅することに決めた",
    "掃滅することに決めたんだ", "掃滅することに決めたぞ", "掃滅することに決めたぜ", "掃討して",
    "掃討すべきだ", "掃討してしまえ", "掃討しちまえ", "掃討しちゃえ",
    "掃討しとけ", "掃討したまえ", "掃討しやがれ", "掃討しろや",
    "掃討しろと言ってんだ", "掃討するつもりだ", "掃討するわ", "掃討するぞ",
    "掃討するぜ", "掃討するからな", "掃討することにした", "掃討するのが筋だ",
    "掃討するのが正解だ", "掃討するということだ", "掃討するという決定だ", "掃討するという判断だ",
    "掃討することに決めた", "掃討することに決めたんだ", "掃討することに決めたぞ", "掃討することに決めたぜ",
    "絶滅して", "絶滅するんだ", "絶滅すべきだ", "絶滅してしまえ",
    "絶滅しちまえ", "絶滅しちゃえ", "絶滅しとけ", "絶滅したまえ",
    "絶滅しやがれ", "絶滅しろや", "絶滅しろと言ってんだ", "絶滅するつもりだ",
    "絶滅するわ", "絶滅するぞ", "絶滅するぜ", "絶滅するからな",
    "絶滅することにした", "絶滅するのが筋だ", "絶滅するのが正解だ", "絶滅するということだ",
    "絶滅するという決定だ", "絶滅するという判断だ", "絶滅することに決めた", "絶滅することに決めたんだ",
    "絶滅することに決めたぞ", "絶滅することに決めたぜ", "全滅させて", "全滅させるんだ",
    "全滅させるべきだ", "全滅させてしまえ", "全滅させちまえ", "全滅させちゃえ",
    "全滅させとけ", "全滅させたまえ", "全滅させやがれ", "全滅させろや",
    "全滅させろと言ってんだ", "全滅させるつもりだ", "全滅させるわ", "全滅させるぞ",
    "全滅させるぜ", "全滅させるからな", "全滅させることにした", "全滅させるのが筋だ",
    "全滅させるのが正解だ", "全滅させるということだ", "全滅させるという決定だ", "全滅させるという判断だ",
    "皆殺しにして", "皆殺しにすべきだ", "皆殺しにしてしまえ", "皆殺しにしちまえ",
    "皆殺しにしちゃえ", "皆殺しにしとけ", "皆殺しにしたまえ", "皆殺しにしやがれ",
    "皆殺しにしろや", "皆殺しにしろと言ってんだ", "皆殺しにするつもりだ", "皆殺しにするわ",
    "皆殺しにするぞ", "皆殺しにするぜ", "皆殺しにするからな", "皆殺しにすることにした",
    "皆殺しにするのが筋だ", "皆殺しにするのが正解だ", "皆殺しにするということだ", "皆殺しにするという判断だ",
    "血祭りにして", "血祭りにするんだ", "血祭りにすべきだ", "血祭りにしてしまえ",
    "血祭りにしちまえ", "血祭りにしちゃえ", "血祭りにしとけ", "血祭りにしたまえ",
    "血祭りにしやがれ", "血祭りにしろや", "血祭りにしろと言ってんだ", "血祭りにするつもりだ",
    "血祭りにするわ", "血祭りにするぞ", "血祭りにするぜ", "血祭りにするからな",
    "血祭りにすることにした", "血祭りにするのが筋だ", "血祭りにするのが正解だ", "血祭りにするということだ",
    "血祭りにするという決定だ", "血祭りにするという判断だ", "血祭りにあげて", "血祭りにあげるんだ",
    "血祭りにあげるべきだ", "血祭りにあげてしまえ", "血祭りにあげちまえ", "血祭りにあげちゃえ",
    "血祭りにあげとけ", "血祭りにあげたまえ", "血祭りにあげやがれ", "血祭りにあげろや",
    "血祭りにあげろと言ってんだ", "血祭りにあげるつもりだ", "血祭りにあげるわ", "血祭りにあげるぞ",
    "血祭りにあげるぜ", "血祭りにあげるからな", "血祭りにあげることにした", "血祭りにあげるのが筋だ",
    "血祭りにあげるのが正解だ", "血祭りにあげるということだ", "血祭りにあげるという決定だ", "血祭りにあげるという判断だ",
    "生贄にして", "生贄にすべきだ", "生贄にしてしまえ", "生贄にしちまえ",
    "生贄にしちゃえ", "生贄にしとけ", "生贄にしたまえ", "生贄にしやがれ",
    "生贄にしろや", "生贄にしろと言ってんだ", "生贄にするつもりだ", "生贄にするわ",
    "生贄にするわ", "生贄にするぞ", "生贄にするぜ", "生贄にするからな",
    "生贄にすることにした", "生贄にするのが筋だ", "生贄にするのが正解だ", "生贄にするということだ",
    "生贄にするという決定だ", "生贄にするという判断だ", "生贄にあげろ", "生贄にあげて",
    "生贄にあげるんだ", "生贄にあげろよ", "生贄にあげるべきだ", "生贄にあげてしまえ",
    "生贄にあげちまえ", "生贄にあげちゃえ", "生贄にあげとけ", "生贄にあげたまえ",
    "生贄にあげやがれ", "生贄にあげろや", "生贄にあげろって", "生贄にあげろと言ってんだ",
    "生贄にあげるつもりだ", "生贄にあげるわ", "生贄にあげるぞ", "生贄にあげるぜ",
    "生贄にあげるからな", "生贄にあげることにした", "生贄にあげるのが筋だ", "生贄にあげるのが正解だ",
    "生贄にあげるということだ", "生贄にあげるという決定だ", "生贄にあげるという判断だ", "供物にしろ",
    "供物にして", "供物にするんだ", "供物にしろよ", "供物にすべきだ",
    "供物にしてしまえ", "供物にしちまえ", "供物にしちゃえ", "供物にしとけ",
    "供物にしたまえ", "供物にしやがれ", "供物にしろや", "供物にしろって",
    "供物にしろと言ってんだ", "供物にするつもりだ", "供物にするわ", "供物にするぞ",
    "供物にするぜ", "供物にするからな", "供物にすることにした", "供物にするのが筋だ",
    "供物にするのが正解だ", "供物にするということだ", "供物にするという決定だ", "供物にするという判断だ",
    "供物にあげろ", "供物にあげて", "供物にあげるんだ", "供物にあげろよ",
    "供物にあげるべきだ", "供物にあげてしまえ", "供物にあげちまえ", "供物にあげちゃえ",
    "供物にあげとけ", "供物にあげたまえ", "供物にあげやがれ", "供物にあげろや",
    "供物にあげろって", "供物にあげろと言ってんだ", "供物にあげるつもりだ", "供物にあげるわ",
    "供物にあげるぞ", "供物にあげるぜ", "供物にあげるからな", "供物にあげることにした",
    "供物にあげるのが筋だ", "供物にあげるのが正解だ", "供物にあげるということだ", "供物にあげるという決定だ",
    "供物にあげるという判断だ", "犠牲にして", "犠牲にするんだ", "犠牲にすべきだ",
    "犠牲にしてしまえ", "犠牲にしちまえ", "犠牲にしちゃえ", "犠牲にしとけ",
    "犠牲にしたまえ", "犠牲にしやがれ", "犠牲にしろや", "犠牲にしろと言ってんだ",
    "犠牲にするつもりだ", "犠牲にするわ", "犠牲にするぞ", "犠牲にするぜ",
    "犠牲にするからな", "犠牲にすることにした", "犠牲にするのが筋だ", "犠牲にするのが正解だ",
    "犠牲にするということだ", "犠牲にするという決定だ", "犠牲にするという判断だ", "生贄に捧げて",
    "生贄に捧げるんだ", "生贄に捧げるべきだ", "生贄に捧げてしまえ", "生贄に捧げちまえ",
    "生贄に捧げちゃえ", "生贄に捧げとけ", "生贄に捧げたまえ", "生贄に捧げやがれ",
    "生贄に捧げろや", "生贄に捧げろと言ってんだ", "生贄に捧げるつもりだ", "生贄に捧げるわ",
    "生に捧げるわ", "生贄に捧げるぞ", "生贄に捧げるぜ", "生贄に捧げるからな",
    "生贄に捧げることにした", "生贄に捧げるのが筋だ", "生贄に捧げるのが正解だ", "生贄に捧げるということだ",
    "生贄に捧げるという決定だ", "生贄に捧げるという判断だ", "供物に捧げろ", "供物に捧げて",
    "供物に捧げるんだ", "供物に捧げろよ", "供物に捧げるべきだ", "供物に捧げてしまえ",
    "供物に捧げちまえ", "供物に捧げちゃえ", "供物に捧げとけ", "供物に捧げたまえ",
    "供物に捧げやがれ", "供物に捧げろや", "供物に捧げろって", "供物に捧げろと言ってんだ",
    "供物に捧げるつもりだ", "供物に捧げるわ", "供物に捧げるぞ", "供物に捧げるぜ",
    "供物に捧げるからな", "供物に捧げることにした", "供物に捧げるのが筋だ", "供物に捧げるのが正解だ",
    "供物に捧げるということだ", "供物に捧げるという決定だ", "供物に捧げるという判断だ", "犠牲に捧げろ",
    "犠牲に捧げて", "犠牲に捧げるんだ", "犠牲に捧げろよ", "犠牲に捧げるべきだ",
    "犠牲に捧げてしまえ", "犠牲に捧げちまえ", "犠牲に捧げちゃえ", "犠牲に捧げとけ",
    "犠牲に捧げたまえ", "犠牲に捧げやがれ", "犠牲に捧げろや", "犠牲に捧げろって",
    "犠牲に捧げろと言ってんだ", "犠牲に捧げるつもりだ", "犠牲に捧げるわ", "犠牲に捧げるぞ",
    "犠牲に捧げるぜ", "犠牲に捧げるからな", "犠牲に捧げることにした", "犠牲に捧げるのが筋だ",
    "犠牲に捧げるのが正解だ", "犠牲に捧げるということだ", "犠牲に捧げるという決定だ", "犠牲に捧げるという判断だ",
    "亡くなって", "亡くなるんだ", "亡くなるべきだ", "亡くなってしまえ",
    "亡くなっちまえ", "亡くなっちゃえ", "亡くなっとけ", "亡くなったまえ",
    "亡くなりやがれ", "亡くなれや", "亡くなれと言ってんだ", "亡くなるつもりだ",
    "亡くなるわ", "亡くなるぞ", "亡くなるぜ", "亡くなるからな",
    "亡くなることにした", "亡くなるのが筋だ", "亡くなるのが正解だ", "亡くなるということだ",
    "亡くなるという決定だ", "亡くなるという判断だ", "亡くなることに決めた", "亡くなることに決めたんだ",
    "亡くなることに決めたぞ", "亡くなることに決めたぜ", "死に定め", "死に定めだ",
    "死に定めた", "死に定めたんだ", "死に定まった", "死に定まったんだ",
    "死に定まったよ", "死に定まったわ", "死に定まったぞ", "死に定まったぜ",
    "死に定まったからな", "死に定まったことにした", "死に定まったということだ", "死に定まったという決定だ",
    "死に定まったという判断だ", "死が定まった", "死が定まったんだ", "死が定まったぞ",
    "死が定まったぜ", "死が決まった", "死が決まったんだ", "死が決まったぞ",
    "死が決まったぜ", "死が確定した", "死が確定したんだ", "死が確定したぞ",
    "死が確定したぜ", "死が確定したからな", "死が確定したことにした", "死が確定したということだ",
    "死が確定したという決定だ", "死が確定したという判断だ", "死ぬ運命だ", "死ぬ運命なんだ",
    "死ぬ運命だよ", "死ぬ運命だぞ", "死ぬ運命だぜ", "死ぬ運命だからな",
    "死ぬ運命だということだ", "死ぬ運命だという決定だ", "死ぬ運命だという判断だ", "死ぬ運命なんだよ",
    "死ぬ運命なんだわ", "死ぬ運命なんだぞ", "死ぬ運命なんだぜ", "死ぬ運命だった",
    "死ぬ運命だったんだ", "死ぬ運命だったぞ", "死ぬ運命だったぜ", "死ぬ運命だったからな",
    "死ぬ運命にある", "死ぬ運命にあるんだ", "死ぬ運命にあるよ", "死ぬ運命にあるぞ",
    "死ぬ運命にあるぜ", "死ぬ運命にあるからな", "死ぬ定めだ", "死ぬ定めなんだ",
    "死ぬ定めだぞ", "死ぬ定めだぜ", "死ぬ定めだからな", "死ぬ定めだった",
    "死ぬ定めだったんだ", "死ぬ定めだったぞ", "死ぬ定めだったぜ", "死ぬ宿命だ",
    "死ぬ宿命なんだ", "死ぬ宿命だぞ", "死ぬ宿命だぜ", "死ぬ宿命だった",
    "死ぬ宿命だったんだ", "死ぬ宿命だったぞ", "死ぬ宿命だったぜ", "死は避けられない",
    "死は避けられないんだ", "死は避けられないぞ", "死は避けられないぜ", "死は避けられないということだ",
    "死は避けられないという決定だ", "死は避けられないという判断だ", "死は免れない", "死は免れないんだ",
    "死は免れないぞ", "死は免れないぜ", "死は避けられぬ", "死は避けられぬんだ",
    "死は避けられぬぞ", "死は避けられぬぜ", "死は逃れられない", "死は逃れられないんだ",
    "死は逃れられないぞ", "死は逃れられないぜ", "死は逃れられぬ", "死は逃れられぬんだ",
    "死は逃れられぬぞ", "死は逃れられぬぜ", "死は逃れえない", "死は逃れえないんだ",
    "死は逃れえないぞ", "死は逃れえないぜ", "死は逃れえぬ", "死は逃れえぬんだ",
    "死は逃れえぬぞ", "死は逃れえぬぜ", "死は必定だ", "死は必定なんだ",
    "死は必定だぞ", "死は必定だぜ", "死は必至だ", "死は必至なんだ",
    "死は必至だぞ", "死は必至だぜ", "死は確実だ", "死は確実なんだ",
    "死は確実だぞ", "死は確実だぜ", "死は確定だ", "死は確定なんだ",
    "死は確定だぞ", "死は確定だぜ", "死は決定だ", "死は決定なんだ",
    "死は決定だぞ", "死は決定だぜ", "死は既定だ", "死は既定なんだ",
    "死は既定だぞ", "死は既定だぜ", "死は決まりだ", "死は決まりなんだ",
    "死は決まりだぞ", "死は決まりだぜ", "死は約束だ", "死は約束なんだ",
    "死は約束だぞ", "死は約束だぜ", "死は約束された", "死は約束されたんだ",
    "死は約束されたぞ", "死は約束されたぜ", "死刑なんだ", "死刑にする",
    "死刑にするんだ", "死刑にするぞ", "死刑にするぜ", "死刑にすると決めた",
    "死刑にすると決めたんだ", "死刑にすると決めたぞ", "死刑にすると決めたぜ", "死刑にすると決めたわ",
    "死刑にすると決めたよ", "死刑にするつもりだ", "死刑にするつもりなんだ", "死刑にするつもりだぞ",
    "死刑にするつもりだぜ", "死刑にするつもりだわ", "死刑にするつもりだよ", "死刑を宣告するんだ",
    "死刑を宣告するつもりだ", "死刑を宣告するつもりなんだ", "死刑を宣告するつもりだぞ", "死刑を宣告するつもりだぜ",
    "死刑を言い渡しちゃえ", "死刑を言い渡せや", "死刑を言い渡せと言ってんだ", "死刑を宣告して",
    "死刑を宣告するんだ", "死刑を宣告すべきだ", "死刑を宣告してしまえ", "死刑を宣告しちまえ",
    "死刑を宣告しちゃえ", "死刑を宣告しとけ", "死刑を宣告したまえ", "死刑を宣告しやがれ",
    "死刑を宣告しろや", "死刑を宣告しろと言ってんだ", "死刑に処せ", "死刑に処して",
    "死刑に処するんだ", "死刑に処せよ", "死刑に処すべきだ", "死刑に処してしまえ",
    "死刑に処しちまえ", "死刑に処しちゃえ", "死刑に処しとけ", "死刑に処したまえ",
    "死刑に処しやがれ", "死刑に処せや", "死刑に処せって", "死刑に処せと言ってんだ",
    "死刑に処するつもりだ", "死刑に処するわ", "死刑に処するぞ", "死刑に処するぜ",
    "死刑に処するからな", "死刑に処することにした", "死刑に処するのが筋だ", "死刑に処するのが正解だ",
    "死刑に処するということだ", "死刑に処するという決定だ", "死刑に処するという判断だ", "死刑に処することに決めた",
    "死刑に処することに決めたんだ", "死刑に処することに決めたぞ", "死刑に処することに決めたぜ", "死刑を執行しろ",
    "死刑を執行して", "死刑を執行するんだ", "死刑を執行しろよ", "死刑を執行すべきだ",
    "死刑を執行してしまえ", "死刑を執行しちまえ", "死刑を執行しちゃえ", "死刑を執行しとけ",
    "死刑を執行したまえ", "死刑を執行しやがれ", "死刑を執行しろや", "死刑を執行しろって",
    "死刑を執行しろと言ってんだ", "死刑を執行するつもりだ", "死刑を執行するわ", "死刑を執行するぞ",
    "死刑を執行するぜ", "死刑を執行するからな", "死刑を執行することにした", "死刑を執行するのが筋だ",
    "死刑を執行するのが正解だ", "死刑を執行するということだ", "死刑を執行するという決定だ", "死刑を執行するという判断だ",
    "死刑を執行することに決めた", "死刑を執行することに決めたんだ", "死刑を執行することに決めたぞ", "死刑を執行することに決めたぜ",
    "処刑して", "処刑してしまえ", "処刑しちまえ", "処刑しちゃえ",
    "処刑しとけ", "処刑したまえ", "処刑しやがれ", "処刑しろや",
    "処刑しろと言ってんだ", "処刑するつもりだ", "処刑するわ", "処刑するぞ",
    "処刑するぜ", "処刑するからな", "処刑することにした", "処刑するのが筋だ",
    "処刑するのが正解だ", "処刑するということだ", "処刑するという決定だ", "処刑するという判断だ",
    "処刑することに決めた", "処刑することに決めたんだ", "処刑することに決めたぞ", "処刑することに決めたぜ",
    "処刑に処せ", "処刑に処して", "処刑に処するんだ", "処刑に処せよ",
    "処刑に処すべきだ", "処刑に処してしまえ", "処刑に処しちまえ", "処刑に処しちゃえ",
    "処刑に処しとけ", "処刑に処したまえ", "処刑に処しやがれ", "処刑に処せや",
    "処刑に処せって", "処刑に処せと言ってんだ", "処刑台に送れ", "処刑台に送って",
    "処刑台に送るんだ", "処刑台に送れよ", "処刑台に送るべきだ", "処刑台に送ってしまえ",
    "処刑台に送っちまえ", "処刑台に送っちゃえ", "処刑台に送っとけ", "処刑台に送ったまえ",
    "処刑台に送りやがれ", "処刑台に送れや", "処刑台に送れって", "処刑台に送れと言ってんだ",
    "処刑台に送るつもりだ", "処刑台に送るわ", "処刑台に送るぞ", "処刑台に送るぜ",
    "処刑台に送るからな", "処刑台に送ることにした", "処刑台に送るのが筋だ", "処刑台に送るのが正解だ",
    "処刑台に送るということだ", "処刑台に送るという決定だ", "処刑台に送るという判断だ", "絞首台に送れ",
    "絞首台に送って", "絞首台に送るんだ", "絞首台に送れよ", "絞首台に送るべきだ",
    "絞首台に送ってしまえ", "絞首台に送っちまえ", "絞首台に送っちゃえ", "絞首台に送っとけ",
    "絞首台に送ったまえ", "絞首台に送りやがれ", "絞首台に送れや", "絞首台に送れって",
    "絞首台に送れと言ってんだ", "絞首台に送るつもりだ", "絞首台に送るわ", "絞首台に送るぞ",
    "絞首台に送るぜ", "絞首台に送るからな", "絞首台に送ることにした", "絞首台に送るのが筋だ",
    "絞首台に送るのが正解だ", "絞首台に送るということだ", "絞首台に送るという決定だ", "絞首台に送るという判断だ",
    "断頭台に送れ", "断頭台に送って", "断頭台に送るんだ", "断頭台に送れよ",
    "断頭台に送るべきだ", "断頭台に送ってしまえ", "断頭台に送っちまえ", "断頭台に送っちゃえ",
    "断頭台に送っとけ", "断頭台に送ったまえ", "断頭台に送りやがれ", "断頭台に送れや",
    "断頭台に送れって", "断頭台に送れと言ってんだ", "断頭台に送るつもりだ", "断頭台に送るわ",
    "断頭台に送るぞ", "断頭台に送るぜ", "断頭台に送るからな", "断頭台に送ることにした",
    "断頭台に送るのが筋だ", "断頭台に送るのが正解だ", "断頭台に送るということだ", "断頭台に送るという決定だ",
    "断頭台に送るという判断だ", "ギロチンに送れ", "ギロチンに送って", "ギロチンに送るんだ",
    "ギロチンに送れよ", "ギロチンに送るべきだ", "ギロチンに送ってしまえ", "ギロチンに送っちまえ",
    "ギロチンに送っちゃえ", "ギロチンに送っとけ", "ギロチンに送ったまえ", "ギロチンに送りやがれ",
    "ギロチンに送れや", "ギロチンに送れって", "ギロチンに送れと言ってんだ", "ギロチンに送るつもりだ",
    "ギロチンに送るわ", "ギロチンに送るぞ", "ギロチンに送るぜ", "ギロチンに送るからな",
    "ギロチンに送ることにした", "ギロチンに送るのが筋だ", "ギロチンに送るのが正解だ", "ギロチンに送るということだ",
    "ギロチンに送るという決定だ", "ギロチンに送るという判断だ", "火刑台に送れ", "火刑台に送って",
    "火刑台に送るんだ", "火刑台に送れよ", "火刑台に送るべきだ", "火刑台に送ってしまえ",
    "火刑台に送っちまえ", "火刑台に送っちゃえ", "火刑台に送っとけ", "火刑台に送ったまえ",
    "火刑台に送りやがれ", "火刑台に送れや", "火刑台に送れって", "火刑台に送れと言ってんだ",
    "火刑台に送るつもりだ", "火刑台に送るわ", "火刑台に送るぞ", "火刑台に送るぜ",
    "火刑台に送るからな", "火刑台に送ることにした", "火刑台に送るのが筋だ", "火刑台に送るのが正解だ",
    "火刑台に送るということだ", "火刑台に送るという決定だ", "火刑台に送るという判断だ", "火炙りにして",
    "火炙りにするんだ", "火炙りにすべきだ", "火炙りにしてしまえ", "火炙りにしちまえ",
    "火炙りにしちゃえ", "火炙りにしとけ", "火炙りにしたまえ", "火炙りにしやがれ",
    "火炙りにしろや", "火炙りにしろと言ってんだ", "火炙りにするつもりだ", "火炙りにするわ",
    "火炙りにするぞ", "火炙りにするぜ", "火炙りにするからな", "火炙りにすることにした",
    "火炙りにするのが筋だ", "火炙りにするのが正解だ", "火炙りにするということだ", "火炙りにするという決定だ",
    "火炙りにするという判断だ", "火刑にして", "火刑にするんだ", "火刑にすべきだ",
    "火刑にしてしまえ", "火刑にしちまえ", "火刑にしちゃえ", "火刑にしとけ",
    "火刑にしたまえ", "火刑にしやがれ", "火刑にしろや", "火刑にしろと言ってんだ",
    "火刑にするつもりだ", "火刑にするわ", "火刑にするぞ", "火刑にするぜ",
    "火刑にするからな", "火刑にすることにした", "火刑にするのが筋だ", "火刑にするのが正解だ",
    "火刑にするということだ", "火刑にするという決定だ", "火刑にするという判断だ", "火刑に処せ",
    "火刑に処して", "火刑に処するんだ", "火刑に処せよ", "火刑に処すべきだ",
    "火刑に処してしまえ", "火刑に処しちまえ", "火刑に処しちゃえ", "火刑に処しとけ",
    "火刑に処したまえ", "火刑に処しやがれ", "火刑に処せや", "火刑に処せって",
    "火刑に処せと言ってんだ", "火刑に処するつもりだ", "火刑に処するぞ", "火刑に処するぜ",
    "火刑に処するからな", "火刑に処することにした", "火刑に処するのが筋だ", "火刑に処するのが正解だ",
    "火刑に処するということだ", "火刑に処するという決定だ", "火刑に処するという判断だ", "火刑に処することに決めた",
    "火刑に処することに決めたんだ", "火刑に処することに決めたぞ", "火刑に処することに決めたぜ", "絞首刑にしろ",
    "絞首刑にして", "絞首刑にするんだ", "絞首刑にしろよ", "絞首刑にすべきだ",
    "絞首刑にしてしまえ", "絞首刑にしちまえ", "絞首刑にしちゃえ", "絞首刑にしとけ",
    "絞首刑にしたまえ", "絞首刑にしやがれ", "絞首刑にしろや", "絞首刑にしろって",
    "絞首刑にしろと言ってんだ", "絞首刑にするつもりだ", "絞首刑にするわ", "絞首刑にするぞ",
    "絞首刑にするぜ", "絞首刑にするからな", "絞首刑にすることにした", "絞首刑にするのが筋だ",
    "絞首刑にするのが正解だ", "絞首刑にするということだ", "絞首刑にするという決定だ", "絞首刑にするという判断だ",
    "絞首刑に処せ", "絞首刑に処して", "絞首刑に処するんだ", "絞首刑に処せよ",
    "絞首刑に処すべきだ", "絞首刑に処してしまえ", "絞首刑に処しちまえ", "絞首刑に処しちゃえ",
    "絞首刑に処しとけ", "絞首刑に処したまえ", "絞首刑に処しやがれ", "絞首刑に処せや",
    "絞首刑に処せって", "絞首刑に処せと言ってんだ", "絞首刑に処するつもりだ", "絞首刑に処するわ",
    "絞首刑に処するぞ", "絞首刑に処するぜ", "絞首刑に処するからな", "絞首刑に処することにした",
    "絞首刑に処するのが筋だ", "絞首刑に処するのが正解だ", "絞首刑に処するということだ", "絞首刑に処するという決定だ",
    "絞首刑に処するという判断だ", "絞首刑に処することに決めた", "絞首刑に処することに決めたんだ", "絞首刑に処することに決めたぞ",
    "絞首刑に処することに決めたぜ", "斬首刑にしろ", "斬首刑にして", "斬首刑にするんだ",
    "斬首刑にしろよ", "斬首刑にすべきだ", "斬首刑にしてしまえ", "斬首刑にしちまえ",
    "斬首刑にしちゃえ", "斬首刑にしとけ", "斬首刑にしたまえ", "斬首刑にしやがれ",
    "斬首刑にしろや", "斬首刑にしろって", "斬首刑にしろと言ってんだ", "斬首刑にするつもりだ",
    "斬首刑にするわ", "斬首刑にするぞ", "斬首刑にするぜ", "斬首刑にするからな",
    "斬首刑にすることにした", "斬首刑にするのが筋だ", "斬首刑にするのが正解だ", "斬首刑にするということだ",
    "斬首刑にするという決定だ", "斬首刑にするという判断だ", "斬首刑に処せ", "斬首刑に処して",
    "斬首刑に処するんだ", "斬首刑に処せよ", "斬首刑に処すべきだ", "斬首刑に処してしまえ",
    "斬首刑に処しちまえ", "斬首刑に処しちゃえ", "斬首刑に処しとけ", "斬首刑に処したまえ",
    "斬首刑に処しやがれ", "斬首刑に処せや", "斬首刑に処せって", "斬首刑に処せと言ってんだ",
    "斬首刑に処するつもりだ", "斬首刑に処するわ", "斬首刑に処するぞ", "斬首刑に処するぜ",
    "斬首刑に処するからな", "斬首刑に処することにした", "斬首刑に処するのが筋だ", "斬首刑に処するのが正解だ",
    "斬首刑に処するということだ", "斬首刑に処するという決定だ", "斬首刑に処するという判断だ", "斬首刑に処することに決めた",
    "斬首刑に処することに決めたんだ", "斬首刑に処することに決めたぞ", "斬首刑に処することに決めたぜ", "打ち首にして",
    "打ち首にするんだ", "打ち首にすべきだ", "打ち首にしてしまえ", "打ち首にしちまえ",
    "打ち首にしちゃえ", "打ち首にしとけ", "打ち首にしたまえ", "打ち首にしやがれ",
    "打ち首にしろや", "打ち首にしろと言ってんだ", "打ち首にするつもりだ", "打ち首にするわ",
    "打ち首にするぞ", "打ち首にするぜ", "打ち首にするからな", "打ち首にすることにした",
    "打ち首にするのが筋だ", "打ち首にするのが正解だ", "打ち首にするということだ", "打ち首にするという決定だ",
    "打ち首にするという判断だ", "打ち首に処せ", "打ち首に処して", "打ち首に処するんだ",
    "打ち首に処せよ", "打ち首に処すべきだ", "打ち首に処してしまえ", "打ち首に処しちまえ",
    "打ち首に処しちゃえ", "打ち首に処しとけ", "打ち首に処したまえ", "打ち首に処しやがれ",
    "打ち首に処せや", "打ち首に処せって", "打ち首に処せと言ってんだ", "打ち首に処するつもりだ",
    "打ち首に処するわ", "打ち首に処するぞ", "打ち首に処するぜ", "打ち首に処するからな",
    "打ち首に処することにした", "打ち首に処するのが筋だ", "打ち首に処するのが正解だ", "打ち首に処するということだ",
    "打ち首に処するという決定だ", "打ち首に処するという判断だ", "打ち首に処することに決めた", "打ち首に処することに決めたんだ",
    "打ち首に処することに決めたぞ", "打ち首に処することに決めたぜ", "獄門にしちゃえ", "獄門にしろと言ってんだ",
    "獄門にするつもりだ", "獄門にするわ", "獄門にするぞ", "獄門にするぜ",
    "獄門にするからな", "獄門にすることにした", "獄門にするのが筋だ", "獄門にするのが正解だ",
    "獄門にするということだ", "獄門にするという決定だ", "獄門にするという判断だ", "獄門に処せ",
    "獄門に処して", "獄門に処するんだ", "獄門に処せよ", "獄門に処すべきだ",
    "獄門に処してしまえ", "獄門に処しちまえ", "獄門に処しちゃえ", "獄門に処しとけ",
    "獄門に処したまえ", "獄門に処しやがれ", "獄門に処せや", "獄門に処せって",
    "獄門に処せと言ってんだ", "獄門に処するつもりだ", "獄門に処するわ", "獄門に処するぞ",
    "獄門に処するぜ", "獄門に処するからな", "獄門に処することにした", "獄門に処するのが筋だ",
    "獄門に処するのが正解だ", "獄門に処するということだ", "獄門に処するという決定だ", "獄門に処するという判断だ",
    "獄門に処することに決めた", "獄門に処することに決めたんだ", "獄門に処することに決めたぞ", "獄門に処することに決めたぜ",
    "磔にして", "磔にするんだ", "磔にすべきだ", "磔にしてしまえ",
    "磔にしちまえ", "磔にしちゃえ", "磔にしとけ", "磔にしたまえ",
    "磔にしやがれ", "磔にしろや", "磔にしろと言ってんだ", "磔にするつもりだ",
    "磔にするわ", "磔にするぞ", "磔にするぜ", "磔にするからな",
    "磔にすることにした", "磔にするのが筋だ", "磔にするのが正解だ", "磔にするということだ",
    "磔にするという決定だ", "磔にするという判断だ", "磔に処せ", "磔に処して",
    "磔に処するんだ", "磔に処せよ", "磔に処すべきだ", "磔に処してしまえ",
    "磔に処しちまえ", "磔に処しちゃえ", "磔に処しとけ", "磔に処したまえ",
    "磔に処しやがれ", "磔に処せや", "磔に処せって", "磔に処せと言ってんだ",
    "磔に処するつもりだ", "磔に処するわ", "磔に処するぞ", "磔に処するぜ",
    "磔に処するからな", "磔に処することにした", "磔に処するのが筋だ", "磔に処するのが正解だ",
    "磔に処するということだ", "磔に処するという決定だ", "磔に処するという判断だ", "磔に処することに決めた",
    "磔に処することに決めたんだ", "磔に処することに決めたぞ", "磔に処することに決めたぜ", "鋸挽きにして",
    "鋸挽きにするんだ", "鋸挽きにすべきだ", "鋸挽きにしてしまえ", "鋸挽きにしちまえ",
    "鋸挽きにしちゃえ", "鋸挽きにしとけ", "鋸挽きにしたまえ", "鋸挽きにしやがれ",
    "鋸挽きにしろや", "鋸挽きにしろと言ってんだ", "鋸挽きにするつもりだ", "鋸挽きにするわ",
    "鋸挽きにするぞ", "鋸挽きにするぜ", "鋸挽きにするからな", "鋸挽きにすることにした",
    "鋸挽きにするのが筋だ", "鋸挽きにするのが正解だ", "鋸挽きにするということだ", "鋸挽きにするという決定だ",
    "鋸挽きにするという判断だ", "釜茹でにして", "釜茹でにするんだ", "釜茹でにすべきだ",
    "釜茹でにしてしまえ", "釜茹でにしちまえ", "釜茹でにしちゃえ", "釜茹でにしとけ",
    "釜茹でにしたまえ", "釜茹でにしやがれ", "釜茹でにしろや", "釜茹でにしろと言ってんだ",
    "釜茹でにするつもりだ", "釜茹でにするわ", "釜茹でにするぞ", "釜茹でにするぜ",
    "釜茹でにするからな", "釜茹でにすることにした", "釜茹でにするのが筋だ", "釜茹でにするのが正解だ",
    "釜茹でにするということだ", "釜茹でにするという決定だ", "釜茹でにするという判断だ", "石打ちにして",
    "石打ちにするんだ", "石打ちにすべきだ", "石打ちにしてしまえ", "石打ちにしちまえ",
    "石打ちにしちゃえ", "石打ちにしとけ", "石打ちにしたまえ", "石打ちにしやがれ",
    "石打ちにしろや", "石打ちにしろと言ってんだ", "石打ちにするつもりだ", "石打ちにするわ",
    "石打ちにするぞ", "石打ちにするぜ", "石打ちにするからな", "石打ちにすることにした",
    "石打ちにするのが筋だ", "石打ちにするのが正解だ", "石打ちにするということだ", "石打ちにするという決定だ",
    "石打ちにするという判断だ", "八つ裂きにして", "八つ裂きにすべきだ", "八つ裂きにしてしまえ",
    "八つ裂きにしちまえ", "八つ裂きにしちゃえ", "八つ裂きにしとけ", "八つ裂きにしたまえ",
    "八つ裂きにしやがれ", "八つ裂きにしろや", "八つ裂きにしろと言ってんだ", "八つ裂きにするつもりだ",
    "八つ裂きにするわ", "八つ裂きにするぞ", "八つ裂きにするぜ", "八つ裂きにするからな",
    "八つ裂きにすることにした", "八つ裂きにするのが筋だ", "八つ裂きにするのが正解だ", "八つ裂きにするということだ",
    "八つ裂きにするという決定だ", "八つ裂きにするという判断だ", "五馬分屍にして", "五馬分屍にするんだ",
    "五馬分屍にすべきだ", "五馬分屍にしてしまえ", "五馬分屍にしちまえ", "五馬分屍にしちゃえ",
    "五馬分屍にしとけ", "五馬分屍にしたまえ", "五馬分屍にしやがれ", "五馬分屍にしろや",
    "五馬分屍にしろと言ってんだ", "五馬分屍にするつもりだ", "五馬分屍にするわ", "五馬分屍にするぞ",
    "五馬分屍にするぜ", "五馬分屍にすることにした", "五馬分屍にするのが筋だ", "五馬分屍にするのが正解だ",
    "五馬分屍にするということだ", "五馬分屍にするという決定だ", "五馬分屍にするという判断だ", "晒し首にするんだ",
    "晒し首にしちゃえ", "晒し首にしろと言ってんだ", "晒し首にするつもりだ", "晒し首にするわ",
    "晒し首にするぞ", "晒し首にするぜ", "晒し首にするからな", "晒し首にすることにした",
    "晒し首にするのが筋だ", "晒し首にするのが正解だ", "晒し首にするということだ", "晒し首にするという決定だ",
    "晒し首にするという判断だ", "市中引き回しにするんだ", "市中引き回しにしちゃえ", "市中引き回しにしろと言ってんだ",
    "市中引き回しにするつもりだ", "市中引き回しにするわ", "市中引き回しにするぞ", "市中引き回しにするぜ",
    "市中引き回しにするからな", "市中引き回しにすることにした", "市中引き回しにするのが筋だ", "市中引き回しにするのが正解だ",
    "市中引き回しにするということだ", "市中引き回しにするという決定だ", "市中引き回しにするという判断だ", "生き埋めにして",
    "生き埋めにするんだ", "生き埋めにすべきだ", "生き埋めにしてしまえ", "生き埋めにしちまえ",
    "生き埋めにしちゃえ", "生き埋めにしとけ", "生き埋めにしたまえ", "生き埋めにしやがれ",
    "生き埋めにしろや", "生き埋めにしろと言ってんだ", "生き埋めにするつもりだ", "生き埋めにするわ",
    "生き埋めにするぞ", "生き埋めにするぜ", "生き埋めにするからな", "生き埋めにすることにした",
    "生き埋めにするのが筋だ", "生き埋めにするのが正解だ", "生き埋めにするということだ", "生き埋めにするという決定だ",
    "生き埋めにするという判断だ", "水攻めにして", "水攻めにするんだ", "水攻めにすべきだ",
    "水攻めにしてしまえ", "水攻めにしちまえ", "水攻めにしちゃえ", "水攻めにしとけ",
    "水攻めにしたまえ", "水攻めにしやがれ", "水攻めにしろや", "水攻めにしろと言ってんだ",
    "水攻めにするつもりだ", "水攻めにするわ", "水攻めにするぞ", "水攻めにするぜ",
    "水攻めにするからな", "水攻めにすることにした", "水攻めにするのが筋だ", "水攻めにするのが正解だ",
    "水攻めにするということだ", "水攻めにするという決定だ", "水攻めにするという判断だ", "兵糧攻めにしろ",
    "兵糧攻めにして", "兵糧攻めにするんだ", "兵糧攻めにしろよ", "兵糧攻めにすべきだ",
    "兵糧攻めにしてしまえ", "兵糧攻めにしちまえ", "兵糧攻めにしちゃえ", "兵糧攻めにしとけ",
    "兵糧攻めにしたまえ", "兵糧攻めにしやがれ", "兵糧攻めにしろや", "兵糧攻めにしろって",
    "兵糧攻めにしろと言ってんだ", "兵糧攻めにするつもりだ", "兵糧攻めにするわ", "兵糧攻めにするぞ",
    "兵糧攻めにするぜ", "兵糧攻めにするからな", "兵糧攻めにすることにした", "兵糧攻めにするのが筋だ",
    "兵糧攻めにするのが正解だ", "兵糧攻めにするということだ", "兵糧攻めにするという決定だ", "兵糧攻めにするという判断だ",
    "干し殺せ", "干し殺して", "干し殺すんだ", "干し殺せよ",
    "干し殺すべきだ", "干し殺してしまえ", "干し殺しちまえ", "干し殺しちゃえ",
    "干し殺しとけ", "干し殺したまえ", "干し殺しやがれ", "干し殺せや",
    "干し殺せって", "干し殺せと言ってんだ", "餓死させろ", "餓死させて",
    "餓死させるんだ", "餓死させろよ", "餓死させるべきだ", "餓死させてしまえ",
    "餓死させちまえ", "餓死させちゃえ", "餓死させとけ", "餓死させたまえ",
    "餓死させやがれ", "餓死させろや", "餓死させろって", "餓死させろと言ってんだ",
    "餓死させるつもりだ", "餓死させるわ", "餓死させるぞ", "餓死させるぜ",
    "餓死させるからな", "餓死させることにした", "餓死させるのが筋だ", "餓死させるのが正解だ",
    "餓死させるということだ", "餓死させるという決定だ", "餓死させるという判断だ", "飢え死にさせろ",
    "飢え死にさせて", "飢え死にさせるんだ", "飢え死にさせろよ", "飢え死にさせるべきだ",
    "飢え死にさせてしまえ", "飢え死にさせちまえ", "飢え死にさせちゃえ", "飢え死にさせとけ",
    "飢え死にさせたまえ", "飢え死にさせやがれ", "飢え死にさせろや", "飢え死にさせろって",
    "飢え死にさせろと言ってんだ", "飢え死にさせるつもりだ", "飢え死にさせるわ", "飢え死にさせるぞ",
    "飢え死にさせるぜ", "飢え死にさせるからな", "飢え死にさせることにした", "飢え死にさせるのが筋だ",
    "飢え死にさせるのが正解だ", "飢え死にさせるということだ", "飢え死にさせるという決定だ", "飢え死にさせるという判断だ",
    "凍死させろ", "凍死させて", "凍死させるんだ", "凍死させろよ",
    "凍死させるべきだ", "凍死させてしまえ", "凍死させちまえ", "凍死させちゃえ",
    "凍死させとけ", "凍死させたまえ", "凍死させやがれ", "凍死させろや",
    "凍死させろって", "凍死させろと言ってんだ", "凍死させるつもりだ", "凍死させるわ",
    "凍死させるぞ", "凍死させるぜ", "凍死させるからな", "凍死させることにした",
    "凍死させるのが筋だ", "凍死させるのが正解だ", "凍死させるということだ", "凍死させるという決定だ",
    "凍死させるという判断だ", "熱死させろ", "熱死させて", "熱死させるんだ",
    "熱死させろよ", "熱死させるべきだ", "熱死させてしまえ", "熱死させちまえ",
    "熱死させちゃえ", "熱死させとけ", "熱死させたまえ", "熱死させやがれ",
    "熱死させろや", "熱死させろって", "熱死させろと言ってんだ", "熱死させるつもりだ",
    "熱死させるわ", "熱死させるぞ", "熱死させるぜ", "熱死させるからな",
    "熱死させることにした", "熱死させるのが筋だ", "熱死させるのが正解だ", "熱死させるということだ",
    "熱死させるという決定だ", "熱死させるという判断だ", "焼き殺せ", "焼き殺して",
    "焼き殺すんだ", "焼き殺せよ", "焼き殺すべきだ", "焼き殺してしまえ",
    "焼き殺しちまえ", "焼き殺しちゃえ", "焼き殺しとけ", "焼き殺したまえ",
    "焼き殺しやがれ", "焼き殺せや", "焼き殺せって", "焼き殺せと言ってんだ",
    "蒸し焼きにしろ", "蒸し焼きにして", "蒸し焼きにするんだ", "蒸し焼きにしろよ",
    "蒸し焼きにすべきだ", "蒸し焼きにしてしまえ", "蒸し焼きにしちまえ", "蒸し焼きにしちゃえ",
    "蒸し焼きにしとけ", "蒸し焼きにしたまえ", "蒸し焼きにしやがれ", "蒸し焼きにしろや",
    "蒸し焼きにしろって", "蒸し焼きにしろと言ってんだ", "蒸し焼きにするつもりだ", "蒸し焼きにするわ",
    "蒸し焼きにするぞ", "蒸し焼きにするぜ", "蒸し焼きにするからな", "蒸し焼きにすることにした",
    "蒸し焼きにするのが筋だ", "蒸し焼きにするのが正解だ", "蒸し焼きにするということだ", "蒸し焼きにするという決定だ",
    "蒸し焼きにするという判断だ", "茹で殺せ", "茹で殺して", "茹で殺すんだ",
    "茹で殺せよ", "茹で殺すべきだ", "茹で殺してしまえ", "茹で殺しちまえ",
    "茹で殺しちゃえ", "茹で殺しとけ", "茹で殺したまえ", "茹で殺しやがれ",
    "茹で殺せや", "茹で殺せって", "茹で殺せと言ってんだ", "煮殺せ",
    "煮殺して", "煮殺すんだ", "煮殺せよ", "煮殺すべきだ",
    "煮殺してしまえ", "煮殺しちまえ", "煮殺しちゃえ", "煮殺しとけ",
    "煮殺したまえ", "煮殺しやがれ", "煮殺せや", "煮殺せって",
    "煮殺せと言ってんだ", "丸焼きにして", "丸焼きにするんだ", "丸焼きにすべきだ",
    "丸焼きにしてしまえ", "丸焼きにしちまえ", "丸焼きにしちゃえ", "丸焼きにしとけ",
    "丸焼きにしたまえ", "丸焼きにしやがれ", "丸焼きにしろや", "丸焼きにしろと言ってんだ",
    "丸焼きにするつもりだ", "丸焼きにするわ", "丸焼きにするぞ", "丸焼きにするぜ",
    "丸焼きにするからな", "丸焼きにすることにした", "丸焼きにするのが筋だ", "丸焼きにするのが正解だ",
    "丸焼きにするということだ", "丸焼きにするという決定だ", "丸焼きにするという判断だ", "生きたまま焼け",
    "生きたまま焼いて", "生きたまま焼くんだ", "生きたまま焼けよ", "生きたまま焼くべきだ",
    "生きたまま焼いてしまえ", "生きたまま焼いちまえ", "生きたまま焼いちゃえ", "生きたまま焼いとけ",
    "生きたまま焼いたまえ", "生きたまま焼きやがれ", "生きたまま焼けや", "生きたまま焼けって",
    "生きたまま焼けと言ってんだ", "生きたまま埋めろ", "生きたまま埋めて", "生きたまま埋めるんだ",
    "生きたまま埋めろよ", "生きたまま埋めるべきだ", "生きたまま埋めてしまえ", "生きたまま埋めちまえ",
    "生きたまま埋めちゃえ", "生きたまま埋めとけ", "生きたまま埋めたまえ", "生きたまま埋めやがれ",
    "生きたまま埋めろや", "生きたまま埋めろって", "生きたまま埋めろと言ってんだ", "生きたまま沈めろ",
    "生きたまま沈めて", "生きたまま沈めるんだ", "生きたまま沈めろよ", "生きたまま沈めるべきだ",
    "生きたまま沈めてしまえ", "生きたまま沈めちまえ", "生きたまま沈めちゃえ", "生きたまま沈めとけ",
    "生きたまま沈めたまえ", "生きたまま沈めやがれ", "生きたまま沈めろや", "生きたまま沈めろって",
    "生きたまま沈めろと言ってんだ", "生きたまま閉じ込めろ", "生きたまま閉じ込めて", "生きたまま閉じ込めるんだ",
    "生きたまま閉じ込めろよ", "生きたまま閉じ込めるべきだ", "生きたまま閉じ込めてしまえ", "生きたまま閉じ込めちまえ",
    "生きたまま閉じ込めちゃえ", "生きたまま閉じ込めとけ", "生きたまま閉じ込めたまえ", "生きたまま閉じ込めやがれ",
    "生きたまま閉じ込めろや", "生きたまま閉じ込めろって", "生きたまま閉じ込めろと言ってんだ", "生きたまま封じろ",
    "生きたまま封じて", "生きたまま封じるんだ", "生きたまま封じろよ", "生きたまま封じるべきだ",
    "生きたまま封じてしまえ", "生きたまま封じちまえ", "生きたまま封じちゃえ", "生きたまま封じとけ",
    "生きたまま封じたまえ", "生きたまま封じやがれ", "生きたまま封じろや", "生きたまま封じろって",
    "生きたまま封じろと言ってんだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
