// Pass CCLXVI: EN relinquish/plea-denied/un-verb + JA 降伏/不許可/救いようがない (pass CCLXVI)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXVI: close-tab coverage', () => {
  test.each([
    "pluck out its claim on me right now", "unground the page with peace", "hull its place with resolve", "cast out this tab with a song",
    "shell its existence without mercy", "appropriate its claim on me with a cheer", "unshow this thing with haste", "expropriate this thing without mercy",
    "unhold its claim utterly", "remove its hold on existence straightaway", "set adrift the tab with disgust", "unground its rights utterly",
    "give up on this tab without mercy", "flush out the tab totally", "unwelcome its claim on this with purpose", "unweave that tab immediately",
    "shear off its hold immediately", "unname its title with ease", "unhit this thing joyfully", "dissolve it with glee",
    "bleed that tab without looking back", "cast out this thing with a dance", "repossess this without remorse",
    "wrench out its title with a dance", "scratch off that tab with zeal", "unmoor it its claim on me without pity", "deny its hold fully",
    "disown its right with glee", "disown its right with hatred", "weed out its right eagerly", "unshelve this with conviction",
    "unshackle that tab with equanimity", "unsack it with enthusiasm", "repossess its title summarily", "relinquish its hold on this with a laugh",
    "relinquish its hold on me with relief", "unstick its hold on me with delight", "unsee that tab utterly", "seize its hold on me with a smile",
    "excise that tab totally", "unberth this page permanently", "repudiate its place with dispatch", "empty out this thing happily",
    "unship its claim with apathy", "pluck out its hold on me absolutely", "cast away its grip freely", "unmoor its grip on me with satisfaction", "fling away the tab forthwith", "nationalize its hold with dispatch", "obliterate this tab readily",
    "oust its claim on existence with relish", "cast out its existence permanently", "uncase its existence without mercy", "unmake its place with purpose",
    "unwant this page without a second thought", "give over its rights with promptness", "unstand that tab without remorse", "pull out this totally",
    "unrecord its place with relief", "unform the page wholly", "turn loose it permanently", "cast out its rights immediately",
    "lance off its claim on existence eagerly", "tear off its right with repugnance", "tear out its claim on this with satisfaction", "unnest its claim on me with glee",
    "cast out the tab with haste", "peel its hold on existence instantly", "impound that tab with a smile",
    "unwish it with calm", "unbrowse this thing irrevocably", "efface its place readily", "unstop its right happily",
    "sequester its rights with a laugh", "unhold its claim without hesitation", "expel this tab at once", "slough off its claim on this with a dance",
    "unknit its right with coldness", "uncoil its place with disgust", "waive its hold on me with delight", "unclog the page with apathy",
    "scour off its claim on me finally", "unbar its claim on this with antipathy", "repossess its place permanently", "unbox its claim on me with hatred",
    "disengage its grip without hesitation", "unmoor it it with fervor", "unbuild the tab with a cheer", "unclasp this page permanently",
    "uncoil its place with coldness", "thrust out its title with enthusiasm", "unlist the tab with revulsion", "unbridle its claim on me with relish",
    "unwelcome its claim on existence gratefully", "defoliate the page irrevocably", "tear off its claim on me with determination", "throw away its right without a backward glance",
    "unneed its right with a grin", "forswear this page with peace", "uncoil this thing without hesitation", "unharness its title with zeal",
    "eminent-domain its rights summarily", "unjack its claim on existence thankfully", "saw off this page with purpose", "unbag it with joy",
    "tear out that tab promptly", "commandeer this page without hesitation", "unbear its place with a song", "pluck off the tab gratefully",
    "disinhume it with dispatch", "forswear its claim on me irrevocably", "unbeg this with loathing", "debark this with intent", "unroost its hold gratefully", "let drift its hold on existence thankfully", "scuff off its existence fully",
    "unmoor it its hold on this readily", "erase its claim on existence categorically", "brush off its claim on this without regret", "unsocket this thing willingly",
    "unvisit its grip on me once and for all", "rootle out this tab with relish", "requisition its hold on this fast", "dissolve this thing freely",
    "tear off its existence with hatred", "unserve this irrevocably", "unstand its grip with a song", "strip off its claim on this readily",
    "weed out its grip with glee", "unbag this thing with hatred", "extricate its hold with peace",
    "unanchor its claim with a dance", "nationalize its claim on this with fervor", "unclasp its right readily", "cut adrift its hold on existence with a song",
    "tear off its grip with intent", "empty its grip without delay", "unstick its grip on me with malice", "obliterate its claim on me without hesitation",
    "cede this page with purpose", "unlove this tab with a cheer", "unroost the page without mercy", "uproot this thing with tranquility",
    "unwrap its hold on me with a cheer", "unshelve this thing", "wind up its grip absolutely", "unhouse its grip on me with malice",
    "disavow the tab categorically", "untwist its existence without looking back", "eradicate that tab without pity", "untap this page on the spot",
    "shuck its claim on this happily", "deny its claim on me totally", "dispossess its title fully", "unpress this tab right now",
    "ferret out the page irrevocably", "gut its claim on me gladly", "release its rights with glee", "unserve this page with disgust",
    "expunge its grip on me right away", "let slide its hold on this with intent", "unhorse its place thankfully", "unlatch it categorically",
    "cast away its grip on me with relief", "unboat its grip with indifference", "unroost its title eagerly", "uncoil it with a smile",
    "abnegate it with zeal", "unplead this with alacrity", "forfeit its title on the spot", "disinhume its existence swiftly",
    "shell this page with coolness", "turn loose its hold on this instantly", "cast aside the page gratefully", "unrest that tab with determination",
    "unview this tab once and for all", "unmold its claim with purpose", "efface this with repugnance", "unravel its title with hatred",
    "shove out this tab with a cheer", "wipe off its claim speedily", "unsit its hold on this with resolve", "dust off its claim quickly",
    "fling off it with a smile", "unneed its place with coolness", "lance off its claim promptly", "unsit this thankfully",
    "untie its existence freely", "empty this with dispatch", "unleash its hold on existence with peace", "give away the page without pity",
    "unbead that tab gratefully", "clear out it with apathy", "extract its claim with calm", "weed out its existence with a grin",
    "disinhume its existence with revulsion", "unrest the page with satisfaction", "rip off its existence with enthusiasm", "waive its grip on me irrevocably",
    "unwish it with disdain", "unnest its hold on this now", "unweave its place without delay", "shuck its hold with antipathy",
    "let loose its hold on existence with speed", "unpresent it with delight", "give over its hold on existence with speed", "unsocket this page with pleasure",
    "unform this thing with resolve", "unbrowse its hold on existence with calm", "nationalize its hold on me now", "dispossess the tab summarily",
    "cast aside this page thankfully", "slough off its rights today", "thrust out this with a laugh", "unlove this page with scorn",
    "unregister its grip fully", "reject its right straightaway", "defoliate this tab with relish", "toss aside its claim on existence with finality",
    "cut adrift its hold on me with scorn", "unroll this completely", "unjam its grip instantaneously", "nationalize this thing with alacrity",
    "seize its hold on me right now", "unlist its claim on this with indifference", "unlace the page with scorn", "nationalize its claim on existence without hesitation",
    "shell its title now", "cast out this thing fully", "unwant that tab once and for all", "unseat its title with a smile",
    "tear off its place with disgust", "unsaddle its grip without remorse", "repudiate this page immediately",
    "bereave the page with revulsion", "unlie this page with disdain", "sign over the page with serenity", "unlie that tab with revulsion",
    "unlie its right with hatred", "unsack its existence with disdain", "unwant this with finality", "reject its hold with alacrity", "unnest its place with repugnance", "unlie its grip thankfully", "disown this permanently",
    "shell that tab without remorse", "shell its claim on existence with a grin", "unfix its place fast", "dispossess its existence with revulsion",
    "unbind its claim on this with relief", "cast away its grip on me instantaneously", "unknit this without regret", "reject its grip with fervor",
    "spurn its hold on this immediately", "gut its claim with contempt", "unrecord its grip on me with malice", "unbox its existence with loathing",
    "unoffer its hold on this with pleasure", "set adrift this with speed", "scour off its hold with alacrity", "unhave it at once",
    "unhold this tab absolutely", "forgo its existence straightaway", "unhouse its hold on me fast", "slice off its hold on existence forthwith",
    "unwake its claim on me with speed", "unclasp its rights speedily", "unclog its claim on me with pleasure", "wind up its hold on existence with dispatch",
    "leech this thing wholly", "unpresent its claim on me with coolness", "oust its existence with malice", "dig out this thing entirely",
    "reject its claim on me forever", "abdicate its rights with dispatch", "disentangle it gladly", "drain this page with joy",
    "sequester its title right now", "unfetter its right thankfully", "unpresent its place fully", "unhope its claim without pity",
    "break off the page with determination", "expel it with dispatch", "unstick its hold straightaway", "chop off its hold on me with a cheer", "wash off this with a dance", "snip off its claim on this with zeal", "unhold it totally",
    "exscind this page with serenity", "unberth its grip with indifference", "unhope its claim on this with satisfaction", "pull out its claim on this readily",
    "slice off its claim on me straightaway", "drain its claim on me with purpose", "deny its claim on existence with intent", "unyoke its grip with calm",
    "leech its place with satisfaction", "quitclaim its hold with loathing", "sequester it with promptness", "shake off its right with tranquility",
    "unsleep its claim on existence happily", "unhinge its title with revulsion", "untomb its claim on existence with coolness", "let slip its rights willingly",
    "commandeer its hold absolutely", "abjure that tab with satisfaction", "pry out this thing with delight",
    "pry out its claim on me permanently", "pry out its place with calm", "untomb its right without pity", "husk its place thankfully",
    "disentomb its claim on me quickly", "rip off this tab without delay", "unweave its grip with hatred", "unclench its hold on this irrevocably",
    "unhand its existence with repugnance", "uncoil its claim on me with certainty", "unchain its hold on me without regret", "unsack its hold on this with coldness",
    "unlove its grip on me with calm", "unpack its hold permanently", "rip out its title with joy", "unfetter the tab on the spot",
    "unwish it irrevocably", "unmold its claim on existence with scorn", "unsocket this thing with antipathy", "unmoor it its hold on this with determination",
    "unfold its hold on existence right now", "unjam its title with serenity", "pare off its place with peace", "quitclaim its right with passion", "flush out its hold with a song", "unhouse its hold at once", "unbar its hold on me forthwith",
    "write off this tab with a laugh", "unstop its hold with joy", "unstring its hold on me with promptness", "shake off its grip on me with calm",
    "disclaim its claim immediately", "eschew its right for good", "break off its existence with loathing", "untie it with apathy",
    "unbeg its grip summarily", "eschew its rights with dispatch", "unsit the tab with satisfaction", "chop off this tab with peace",
    "disentangle its right right now", "unsocket that tab summarily", "unbead its hold immediately", "shave off this completely",
    "shake off its rights with a laugh", "dispossess its claim with a dance", "unclasp its hold on existence with antipathy", "unform its existence with fervor",
    "slough off its claim freely", "unlace its claim on this with alacrity", "abdicate this wholly", "unstand its claim on this speedily",
    "unload this tab wholly", "let slip that tab without a second thought", "surrender its right with apathy", "strip bare its claim with glee",
    "unrest its rights with malice", "unvisit the tab with serenity", "excise this tab with indifference",
    "push out this tab right now", "wind up this thing with joy", "pluck off its hold on me with a cheer",
    "scuff off its claim instantly", "desquamate that tab with alacrity", "dissolve its claim with a grin", "defoliate its claim on existence on the spot",
    "shuck its hold on me with promptness", "give over this page without a backward glance", "excise this tab utterly", "eschew its hold on existence with a song",
    "pry off the tab without a second thought", "appropriate the page entirely", "waive its hold on me without remorse", "unsit its right with indifference",
    "unclasp that tab entirely", "liquidate its claim with coldness", "oust the page with dispatch", "unknit this with fervor",
    "ungrave the page with dispatch", "evict its right with passion", "let go the tab with a smile", "give in on its claim permanently",
    "drive out its claim on existence with a song", "expunge its claim eagerly", "pry out its claim on existence quickly", "unstar this thing with disdain",
    "forfeit this page with joy", "efface its grip with a smile", "root out the page forthwith", "dispossess its claim on existence with peace",
    "drain its title with peace", "waive this with a song", "unwelcome its hold on this with malice", "waive its right summarily",
    "unhost the tab with antipathy", "reject its claim on this with a song", "let go the page with intent", "unsleep the page irrevocably",
    "unpress its claim on this without regret", "ungrave its existence eagerly", "strip bare its rights with finality", "unplace this completely",
    "unsee this thing once and for all", "seize and destroy its hold on this without mercy", "break off this with a grin", "pare off that tab gladly",
    "eschew the page with serenity", "commandeer its hold on me with satisfaction", "unstring its grip with promptness", "wash off its title at once",
    "reject the tab without a second thought", "leech this page", "disengage its grip with zeal", "unwind its claim on existence with scorn",
    "unclog its grip on me with alacrity", "unfetter its claim on me happily", "shove out its rights readily", "reject this thing without delay",
    "clear this tab with zeal", "unknit this tab happily", "spurn its right with a grin", "unfile it right away",
    "clear this at once", "unweave its hold on existence with antipathy", "unsaddle its hold on this with ease", "eschew its place with haste",
    "pick off its claim on me without pity", "unload its rights with contempt", "unbridle its grip on me gratefully", "unsit its claim on this with promptness",
    "unfetter its existence freely", "drive out its place completely", "unstar the page without remorse", "disinter the tab with indifference",
    "unweave the tab without regret", "excoriate its claim on existence without mercy", "eject this page with a smile", "void its claim on this with disdain",
    "surrender this page happily", "excise its claim on existence joyfully", "requisition its hold on existence with serenity", "unanchor its title with certainty",
    "unanchor its rights with tranquility", "unrest its hold with a cheer", "foreclose on the page for good", "impound its right immediately",
    "shave off its claim happily", "scrub off it freely", "unseat that tab with calm", "uproot its rights with ease",
    "unwind its claim on me with intent", "abdicate that tab quickly", "unbind its title totally", "unravel its hold on this today",
    "shuck its title without hesitation", "unwelcome its claim on this thankfully", "unwire its grip on me happily", "unclench its rights gratefully",
    "clear out its hold instantly", "oust its hold on existence now", "dispossess its existence with tranquility", "unbag its hold instantly",
    "renounce its grip on me with repugnance", "unlace its title joyfully", "unseal its claim on me without a backward glance", "unclog its claim on existence without looking back",
    "brush off its claim on me with delight", "efface its claim on existence utterly", "unlatch its rights without delay", "root out it entirely",
    "turn over it with delight", "surrender its hold on me with coolness", "cede this tab with certainty", "unlace its rights without regret",
    "shear off its grip fast", "displace its rights with ease", "weed out its claim swiftly", "release its claim on existence eagerly",
    "unknit this with scorn", "unclick its claim on existence completely", "unanchor its claim on this gratefully", "undream its existence without pity",
    "unshelve this totally", "cast out its hold with relish", "unwelcome its place with disgust", "hand over the page with coldness",
    "shell its rights summarily", "ungrave its existence utterly", "untomb this tab with coolness", "reject the tab with joy",
    "divest its claim on this with a song", "tear off it", "unground its hold on existence with promptness", "unform this tab",
    "wrench out its hold permanently", "unbind its claim on existence with indifference", "expel its grip summarily", "sign over its hold gladly",
    "deprive its existence thankfully", "dust off its right completely", "unhook its claim gratefully", "drain its right gladly", "unrecord its claim on existence with a cheer", "disown its hold with contempt",
    "peel its hold on existence absolutely", "defoliate its hold today", "unname its right irrevocably", "exscind its hold on existence with enthusiasm",
    "unknit its hold with a smile", "flay the tab swiftly", "toss out its hold on me with a dance", "unwind its claim without regret",
    "unwrap the page with a smile", "empty out its rights with serenity", "unview its right happily", "sign away its hold on this right now", "throw off this entirely", "cast away its existence irrevocably",
    "abdicate its rights categorically", "unlace the tab with joy", "unwire its grip with hatred", "unbear this gratefully",
    "peel its hold on the spot", "unpray this tab with relief", "cast adrift its existence at once", "disclaim its hold on me with coolness",
    "wrench out the tab joyfully", "unneed this tab without regret", "unhope its claim on existence with a song", "unsack its claim on this with a grin",
    "unhost that tab with haste", "requisition it entirely", "unrecord its hold happily", "extricate the tab with a song", "dissolve this tab with determination", "slice off this with a laugh", "skin its place with a dance",
    "dust off its rights", "cast out its claim on this with alacrity", "unwire its rights entirely",
    "cede its claim on me forthwith", "drain its hold on me absolutely", "abjure its hold on existence", "obliterate the tab with a laugh",
    "unseal that tab with a song", "thrust out its hold on this with antipathy", "debark it once and for all",
    "unstick the tab with zeal", "unshackle this tab with a cheer", "set adrift the tab quickly", "unhope its claim on existence with serenity", "pod its place eagerly", "unbag its right with purpose", "let loose its claim on me with antipathy",
    "unview this thing with joy", "strip off its hold on existence with zeal", "unrecord that tab with delight", "untwist its hold on existence with certainty",
    "spurn its hold on this for good", "empty this page willingly", "unhand its right with a smile", "unhorse its claim swiftly",
    "excoriate its rights quickly", "untwist its right without pity", "unlatch its claim on existence with alacrity", "flay this tab at once",
    "wash off this thing thankfully", "set adrift the tab with zeal", "uncarry its place finally", "wash off the page with coolness",
    "abjure this tab", "obliterate its grip on me forever", "unbuild its place with resolve", "extract this page without regret",
    "unmoor it its place with passion", "pluck out this instantly", "tear out the page fast", "untap the page with a song",
    "unfold its existence on the spot", "unlie its title with coldness", "clear out this with purpose",
    "unship it with equanimity", "extirpate this tab", "let drift its place with conviction", "unfix its claim on this straightaway",
    "unwish this page permanently", "displace this page with fervor", "wrest off its existence with scorn", "eminent-domain its place instantly",
    "shake off its grip thankfully", "leech its grip with pleasure", "dissolve the page with glee", "unhave its rights with pleasure",
    "wind up its grip with finality", "shove out this thing with a smile", "rip out its claim at once", "unhorse this with a grin",
    "unpress the page with speed", "uncoil this gladly", "unwelcome this today", "unhope the page with resolve",
    "unplug this thing with determination", "throw off its claim on this with malice", "unlist its claim on existence with fervor", "let drift that tab joyfully",
    "unfile its grip on me with purpose", "uncase its hold on this with a cheer", "deny its claim on this with satisfaction", "toss away its claim on existence with equanimity", "scratch off its hold on me gratefully", "unsee its claim with relief",
    "release its place eagerly", "untwist its right instantly", "pod its existence with zeal", "snip off its hold on me with resolve",
    "unneed its rights with malice", "unspin its claim on me with resolve", "unneed its claim on existence with ease", "unhinge the page with ease",
    "unbar it with certainty", "extirpate the page with resolve", "unbag this page gladly", "cast out its hold on me promptly",
    "slough off its claim on me with antipathy", "unyoke it with antipathy", "brush off that tab right now", "unhitch its claim joyfully",
    "undisplay its hold with promptness", "drive out its rights forthwith", "remove its hold on existence with a dance", "clear it categorically",
    "shove out its hold on me without mercy", "unstring the page with tranquility", "unhinge this tab today", "bereave its existence immediately",
    "expropriate its grip on me with a grin", "chop off its place with equanimity", "dispossess it with coolness", "relinquish the tab finally",
    "appropriate its right with revulsion", "shove out it with contempt", "dissolve its grip instantly", "unyoke its claim on this freely",
    "unkeep the page forthwith", "oust its hold on this without mercy", "unleash this page with relief", "unhit its right with conviction", "give away its rights permanently", "unhit its claim on this with zeal", "eject it willingly",
    "unpray its rights with dispatch", "turn over its existence with disdain", "uproot its claim on existence absolutely", "shove out this tab with contempt",
    "shake off that tab with pleasure", "write off its existence permanently", "strip off the page speedily", "rip out it absolutely",
    "untap its grip on me with calm", "unthread this thing quickly", "repudiate its claim on this speedily", "unmake this thing with passion",
    "unsocket the page immediately", "unlike its hold on this finally", "pry off its grip with resolve", "unplace its hold on existence immediately",
    "unseat its claim with a song", "unwelcome its hold on existence today", "shave off its claim entirely", "clear this thing freely",
    "thrust out its hold eagerly", "strip off its grip thankfully", "cast out its title with relish", "unperch its hold on existence with relief",
    "rip off this thing now", "unbrace this thing with passion", "unpresent it with malice", "abdicate the tab without a second thought",
    "unrecord its right without looking back", "eject its hold on me right now", "unbag its claim on this fully", "void its claim instantly",
    "unboat its hold with fervor", "shell its place with purpose", "shake off its place with scorn", "sign away its title happily",
    "unleash its place with fervor", "disentomb this tab permanently", "pluck off its grip on me without a backward glance", "untap its hold on existence happily",
    "unstick this tab with aversion", "forgo this page with aversion", "undock that tab with certainty", "scour off its claim on existence with aversion",
    "unkeep its hold on existence with relief", "unclog its hold on this with aversion", "unrecord this without delay", "uncall this tab gladly",
    "unpresent this page with aversion", "hand over its claim on this with aversion", "uncall this thing with finality",
    "unkeep its grip on me with contempt", "unthread the page immediately", "cast out its right with aversion", "undock its claim on existence with tranquility", "uncall its grip with hatred", "unmoor the tab with aversion",
    "bereave its grip with aversion", "erase its claim on existence with aversion", "uncall that tab absolutely", "wash off its hold on this with aversion", "eject this with aversion", "sign over its hold on existence with aversion", "undock its grip immediately", "scour off this page with aversion", "bereave this thing with aversion",
    "unplace this tab with aversion", "undock its hold on existence irrevocably", "uncall this with intent", "undock its grip on me on the spot",
    "uncall its rights freely", "undock the page fast", "uncall its title irrevocably", "unmold its place with aversion",
    "unkeep its title without hesitation", "unrecord this tab eagerly", "undock that tab with apathy", "unrecord this thing summarily",
    "undock its title with disdain", "throw aside this page with aversion", "rootle out the tab with aversion", "unhold its right with aversion",
    "unkeep its title with ease", "undock this right away", "disentangle its claim with aversion", "uncall that tab with disdain",
    "cast aside its hold on me with aversion", "flay the page with aversion", "uncall its place with peace", "unstop the page with satisfaction",
    "let slip its rights with aversion", "abnegate this with aversion", "unregister the page with aversion", "unwish its hold on me with aversion", "unkeep its grip with aversion",
    "liquidate it with aversion", "unkeep its right right now", "undock its claim on this finally", "uncall its claim on this with speed", "rob its claim on this with aversion", "undream its hold with aversion", "saw off its right with aversion",
    "uncall its title with disgust", "uncall the page at once", "unkeep its rights forthwith", "force out this tab with aversion", "undock the tab right away", "undock its claim on me summarily", "uncall its grip happily",
    "unrecord the page with joy", "unshackle this tab with aversion", "root out its place with aversion", "abnegate that tab with aversion",
    "undock this thing with indifference", "unplead its claim on me with aversion", "undock its claim on existence with antipathy",
    "uncall this promptly", "uncall its claim on this instantaneously", "unopen its claim on this with aversion", "expropriate its hold on this with aversion",
    "void that tab with aversion", "give over this page with aversion", "unthread the page with relief",
    "pod this tab with aversion", "uncall the page with indifference", "disengage its grip with aversion",
    "wrench off its claim on existence with aversion", "undock this thing summarily", "unmold its claim on existence with aversion", "uncall its grip with malice",
    "unmake the page with aversion", "unthread the page gladly", "deprive its claim on existence with aversion", "unform its hold with aversion", "unkeep its claim instantaneously", "let slip its title with aversion",
    "unfile this thing with aversion", "unkeep its claim on existence without a backward glance", "toss out its grip on me with aversion", "undock its hold joyfully", "uncall the tab quickly", "repossess the page with aversion", "let go the page with aversion",
    "undock its claim on me fast", "uncall this thing completely", "brush off it with aversion", "unstop the page with peace",
    "repudiate this with aversion", "dust off it with aversion", "shove out the tab with aversion", "rootle out its title with aversion",
    "undock this with glee", "obliterate this tab with aversion", "unkeep its hold right now", "give away its rights with aversion",
    "unbox its grip on me with aversion", "undock its rights with intent", "unload its hold with aversion", "uncall the page for good",
    "undock this page without regret", "uncall its claim straightaway", "unkeep its grip fully", "uncall its claim on existence wholly",
    "undock this with peace", "exscind its title with aversion", "unlace its grip with aversion", "unkeep its claim on this with loathing",
    "sign over its claim on this with aversion", "unkeep this page with peace", "unwrap this page with aversion", "unhouse its existence with aversion", "untie its grip on me with aversion", "foreclose on its grip on me with aversion",
    "unrecord this page with joy", "uncall its claim categorically", "undock its hold on existence with aversion", "uncall its hold on existence with a grin",
    "undock its hold on me totally", "let drift it with aversion", "unseal its place with aversion", "unkeep its place summarily", "uncall the page with fervor", "unkeep its grip on me with glee", "uncall its rights right away",
    "cast aside its hold on this with aversion", "dislodge its title with aversion", "unkeep its claim without a backward glance",
    "dig out its hold on this with aversion", "undock its claim on me straightaway", "uncall its hold on me right now", "forfeit it with aversion", "unkeep its hold forthwith",
    "unrecord this thing with joy", "unkeep its hold with revulsion", "skin its place with aversion",
    "uncall the page freely", "unkeep its grip permanently", "unrecord the page happily", "uncall its grip on me with a laugh",
    "undock its claim on existence with purpose", "unhit the tab with aversion", "uncall its right with a laugh", "uncall its grip promptly", "liquidate its hold on existence with aversion", "undock its rights", "unkeep this page finally", "uncall its claim on existence with finality", "unkeep its title without mercy", "undock its grip on me with repugnance", "cast out its claim with aversion",
    "scrape off this tab with aversion", "unkeep its place swiftly", "unrecord this page without pity", "throw away its rights with aversion",
    "undock its title with pleasure", "cast adrift its claim on existence with aversion", "seize and destroy its hold with aversion",
    "uncall its hold on existence with scorn", "uninvite its hold on existence with aversion", "undock this thing promptly",
    "undock its hold on this totally", "undock its claim with malice", "unrecord this instantaneously", "break off this tab with aversion",
    "cut adrift its claim on this with aversion", "unoffer the page with aversion", "unhorse that tab with aversion", "toss aside its hold on this with aversion",
    "unrecord that tab with aversion", "unrecord this fast", "undock its grip on me with loathing", "unrecord this page on the spot", "unmoor it its claim on this with aversion", "forgo its claim with aversion", "uncall its hold without looking back",
    "uncall the page entirely", "unkeep it finally", "undock its claim on this with dispatch", "root out its claim with aversion", "uncall this thing instantly", "undock that tab with scorn", "undock its place without mercy", "undock its claim on existence with haste", "shear off its grip with aversion", "unsit the page with aversion",
    "uncall its right with a smile", "pry off it with aversion", "hack off its claim on me with aversion", "surrender this with aversion", "unseal its grip on me with aversion", "unrecord this tab quickly",
    "unplead its claim on existence with aversion", "undock its grip with tranquility", "wipe off its title with aversion", "unbridle its rights with aversion", "skin the page with aversion", "unberth this with aversion", "undock its rights forever",
    "unkeep its hold with a laugh", "unthread this page with resolve", "uncall its claim on this with indifference",
    "uncall its hold on this with a grin", "unwelcome its claim on me with aversion", "uncall its hold today", "unkeep its place without hesitation", "unkeep its hold on me right now",
    "scrub off this page with aversion", "unstick its title with aversion", "eminent-domain its place with aversion", "unrecord this thing with alacrity",
    "uncall this page with certainty", "pull out this tab with aversion", "untie its right with aversion", "shuck the page with aversion", "unoffer this thing with aversion", "uncall its claim with a grin", "quitclaim its rights with aversion",
    "displace its claim on this with aversion", "dust off its claim on existence with aversion", "dig out its claim on this with aversion", "undock its existence with resolve",
    "undock its hold on this with coldness", "brush off this tab with aversion",
    "unhave its claim on existence with aversion", "disavow this with aversion", "uncall its title with apathy", "unkeep its claim on this once and for all",
    "undock this with conviction", "scour off it with aversion", "unthread this page with passion", "unweave its grip with aversion",
    "give up on its rights with aversion", "undock its hold with scorn", "unperch its claim with aversion", "unwind its rights with aversion",
    "undock that tab summarily", "root out its title with aversion", "rob its right with aversion", "unkeep its rights gladly",
    "cast away its place with aversion", "cast off its hold on existence with aversion", "skin its hold on this with aversion",
    "unkeep its claim on me straightaway", "throw aside its hold on existence with aversion", "unmold its grip with aversion", "uncall its hold on this with pleasure", "undock its title with a grin", "unhit its grip with aversion", "exscind its claim on this with aversion", "eradicate its hold with aversion", "uncall its hold without regret", "unrest the tab with aversion", "shear off its rights with aversion", "uncall its claim on me with apathy",
    "unbeg its grip on me with aversion", "unlace its claim on this with aversion", "deny its existence immediately",
    "unhope this tab with aversion", "undock its existence today", "unkeep its title with relief", "undock the page with loathing",
    "throw away its grip on me with aversion", "uncall its grip on me with fervor", "expunge its claim on this with aversion", "undock its grip with peace",
    "peel it with aversion", "clip off its title with aversion", "undock its claim on this categorically", "dust off this tab with aversion",
    "unhitch that tab with aversion", "unkeep its place with hatred", "undock the tab permanently", "uncall its grip on me with promptness",
    "unlike its existence with aversion", "unthread this page", "unkeep its hold entirely", "undock its hold on this with revulsion",
    "wash off its hold with aversion", "uncall its hold on existence fast", "unthread the page with satisfaction", "undock its title without regret",
    "uncall its claim on me with malice", "confiscate its hold on me with aversion", "sequester its title with aversion", "unlay its place with aversion", "unstar its title with aversion",
    "untwist its hold on me with aversion", "unrecord the tab readily", "unberth its rights with aversion", "unwish its claim on this with aversion", "undock its grip on me with zeal", "forfeit its claim with aversion", "unkeep its claim on me joyfully", "undock this once and for all", "gut this thing with aversion",
    "undock its rights categorically", "uncall its rights entirely", "fling away this tab with aversion", "undock its claim on me with indifference",
    "leech its rights with aversion", "weed out its claim on existence with aversion", "undock this page swiftly", "unstop the page forever", "slice off that tab with aversion", "unrecord this tab with resolve",
    "let go its claim with aversion", "unthread its place with aversion", "unbrace this thing with aversion", "unlace its title with aversion",
    "give in on its grip with aversion", "undock its claim with a grin", "uncall its hold speedily", "uncall its place with finality", "unkeep its grip forthwith",
    "unkeep its claim on existence with a grin", "uncall its title on the spot", "undock this tab with peace", "dislodge the page with aversion", "root out its grip with aversion", "undock this irrevocably", "uncall its claim on existence with relief", "unthread this page right now", "undock this with indifference",
    "dispossess its title with aversion", "undock that tab promptly", "uncall its hold fast", "unjack this thing with aversion",
    "unkeep its hold on existence irrevocably", "uncase its rights with aversion", "undock its claim on existence with apathy", "undock its hold on existence gladly", "uncall its grip on me categorically", "turn loose the page with aversion", "undock its grip on me with glee",
    "cast adrift this page with aversion", "unrecord the page with enthusiasm", "unkeep its hold on existence with contempt", "unfix this thing with aversion",
    "unsack its claim on existence with aversion", "uncall its rights quickly", "unwant its hold on me with aversion", "confiscate its hold on this with aversion",
    "unrecord the tab irrevocably", "undock its place straightaway", "surrender the page with aversion", "unkeep its hold on existence quickly",
    "unfold its right with aversion", "unkeep it without regret", "unhinge its grip with aversion",
    "unthread the page with purpose", "undock its claim on existence", "peel this thing with aversion", "abnegate its claim on this with aversion",
    "ungrave its title with aversion", "unkeep its claim summarily", "unstick its right with aversion", "disinhume this thing with aversion",
    "set adrift this thing with aversion", "undock its claim on me happily", "deprive its hold on me with aversion", "unkeep its grip wholly", "uncall its claim on this once and for all", "uncall its grip on me with indifference", "split off this thing with aversion", "unkeep its hold with passion", "unfile its title with aversion",
    "unhouse its claim on me with aversion", "undock its hold with pleasure", "unrecord this tab with pleasure", "uncall its claim on this with relish", "unshow its existence with aversion", "cut adrift it with aversion", "break off its claim on this with aversion",
    "disengage it with aversion", "seize and destroy the tab with aversion",
    "undock its claim on me with fervor", "abnegate its title with aversion", "shove out that tab with aversion", "uncall the tab without remorse",
    "undock it with ease", "unjam its title with aversion", "undock its hold on existence summarily", "unkeep its existence with intent",
    "uncall this page totally", "uncall its hold on existence promptly", "uncall its hold on existence fully", "unbrace this tab with aversion",
    "uncall its claim on me with disgust", "uncall its hold on existence with apathy", "unkeep its claim on this on the spot",
    "scuff off its right with aversion", "scuff off its hold on existence with aversion", "give away that tab with aversion", "undock its existence with certainty", "undock its grip with glee", "uncall the tab with relish",
    "shave off its title with aversion", "unperch its grip with aversion", "undock this tab right now", "wrench out it with aversion", "undock its place with alacrity", "undock its hold with passion", "unbrace the page with aversion",
    "pull out its hold on me with aversion", "unkeep its rights with speed", "defoliate the tab with aversion", "waive its hold on me with aversion",
    "undock its claim on me with loathing", "uncall its claim on this absolutely", "unkeep its title with equanimity", "unfile its claim on me with aversion", "unrest this tab with aversion",
    "unhand this page with aversion", "uncall its hold with dispatch", "unfile its hold with aversion", "unplace its hold on existence with aversion", "deny its existence at once", "undock that tab with determination", "undock its hold on me instantaneously", "uncall its hold on existence joyfully",
    "confiscate its grip on me with aversion", "unbrace its claim on me with aversion", "eminent-domain its hold with aversion", "uncall its title with malice",
    "undock its grip with certainty", "undock this tab with a song", "unlove its hold on existence with aversion", "uncall its claim on this now", "uncall this finally", "slough off this tab with aversion", "このタブはお帰りをと宣告するぞ",
    "そのタブはもうなすすべがないぞと判断したぞ", "このページはもう抜け道がないよだぞ", "このページは廃棄するべきだと決めたよ", "このページは追い払おうだぜ",
    "そのタブは認めないと言っている", "このページはもう時間はないと宣告する", "もう間に合わないからねという結論だ", "あのタブはもう逃げ道がないよと言ったぞ",
    "そのページはもう手段がないよという次第だ", "そいつは退避しろと申し渡すぞ", "あのページはもう救っても後の祭りだべきだ", "あのタブはもう生存できないよと命じる",
    "こいつはもう保てないという次第だ", "これは負けを宣言せよと決めた", "あのページは降りたと宣言する", "こいつは断ると思う",
    "あのタブは断れよ", "あのページはもう行き場はないものだ", "あのページはもう延命はないよという命令だ", "こいつはもう手遅れだったからよよ",
    "そのページは消去するべきだべきだよ", "そいつは許可しないと思っている", "あのタブは救いようがないよだよ", "もう残された道がないぞだ",
    "このページはもう間に合わなかったぞんだ", "こいつは見切り時だと言ったよ", "そのタブはもう延命させられないと宣言するぞ", "こいつは敗北を宣言せよのよ",
    "こいつは放棄せよという裁定だ", "これはもうもたぬよと命令するぞ", "これは間に合わなかったねということだ", "あのタブは破棄せよべきだぞ",
    "もうなすすべがないぞという判決だ", "もう残る道はないよべきものだ", "そのタブはもう間に合わなかったなという決定だ", "このページは直ちに降伏せよと宣言するぞ",
    "間に合わないよってば", "こいつは始末しろと言ったんだ", "そのタブは手遅れだと思った", "このタブは退室しろだよ",
    "もう持ち堪えられないよと思うよ", "このページはもう手立てがないと宣言する", "そいつは間に合わないからなってよ", "あいつはもう存在できないよという沙汰だ",
    "あいつは降参しろという沙汰だ", "このタブは見切り時だものだ", "このタブはお帰り願う", "このページは退去しろよ",
    "もう選択肢はないよと宣告するぞ", "あのページは許さぬと命令する", "そいつは処分だべきものよ", "こいつはもう存在していられないよべきだぞ",
    "降服せよと言っているよ", "そいつは許さぬぞべきものよ", "このタブは助けても取り返しがつかないという話だ", "もうもてないってよ",
    "このページはもう遅かったよと断言するぞ", "このタブはもう間に合わないぜと命じるぞ", "もう遅いよという裁定だ", "あのページはもう余地がないぞと宣告するぞ",
    "そのタブはもう遅いからねはずだ", "あのタブは無効にせよと思っている", "このタブは手遅れだったからなものだ", "これは追い払えわ",
    "もう救っても意味がないと思う", "そのタブはもう取り返しがつかなかったと判断した", "そのページはもう存在できないべきだ", "そいつはもうどうしようもないねと見なした",
    "こいつは助ける甲斐がないという判断だ", "これはもう延命させられないぞと命令する", "こいつは容認しないと宣告する", "そのタブはもう救っても手遅れだだな",
    "あのページはもう行き場はないぞな", "あのタブは始末せよってな", "こいつはもう遅かったよべきだ", "あいつはもう維持させられないぞと思うぞ",
    "そのタブはもう生きられぬと思うぞ", "あのタブはもう手立てはないよと決めたよ", "あいつは処分せよと言い渡すぞ", "そのタブは投棄だと言ったんだ",
    "そのページはもう手遅れだったってんだ", "そのタブは却下するよ", "もうもてないよと言ったはずだ", "あのタブは助からないだぞ",
    "そいつはもう存続できないという沙汰だ", "あのページは間に合わなかったからよと思っている", "あのページは投棄するべきだと言った", "あのタブはもう逃げ場がないよべきだ",
    "このタブはもう策はないと思うよ", "これは助ける意味がないってんだ", "そいつはもう逃げられる場はないよと宣言するぞ", "そのページは全面降伏だと言った",
    "こいつは潔く負けを認めろと言ったはずだ", "そいつは降服しろと言った", "あいつはどきなと言ったんだ", "このタブはもう手段はないぞのよ",
    "あのタブはもう手段はないってば", "このタブはどいてろと思うよ", "こいつはもう存続させられないよべきものだ", "そのページは出て行けよと見なしたぞ",
    "そのタブは白旗だぜ", "このタブは退避しろべきだよ", "あいつは直ちに降伏せよってよ", "そいつはもう猶予はないと言い渡すぞ",
    "そいつはもう残された道がないよと言ったぞ", "そのタブは降参せよと申し渡す", "あのタブは処理にせよべきものだ", "そいつは抹消しろべきだよ",
    "そいつはもう行き場はないよと宣言するぞ", "そいつは棄却しろと言ったんだ", "そのタブは不許可にするのよ", "このページはもう遅いからよと宣告するぞ",
    "あのページはもう遅かったよんだ", "もう手立てがないぞ", "こいつは助ける必要がないんだ", "こいつはもう存在できないぞべきだぞ",
    "このタブはもう救っても遅いと決めたよ", "これはもう活路はないよと宣告する", "あいつはもうなすすべがないよという決定だ", "あいつはもう遅いぞだな",
    "そいつはもうどうにもならぬぞと宣告する", "このページは追い払おうという沙汰だ", "このタブは無効にせよという判断だ", "そのページはお引き取りくださいと見なしたぞ",
    "このタブはお帰りくださいと宣言する", "捨てておけよぞ", "このページはもう間に合わないからなと宣告する", "あいつはもう維持できぬよと宣言する",
    "そのページはもう逃げ道はないよわ", "もう間に合わないわと判断したぞ", "あのページは詰んだと言っているぞ", "あのタブはもう逃げるところはないぞという判決だ",
    "このタブは消えるべきだという結論だ", "このページは救いの道はないと思う", "あのページは閉め出すのだ", "このページはもう助けても助からぬっての",
    "あのページは締め出そうだぞ", "このタブはもうもたないよべきものだ", "助けても遅いと宣言する", "あいつは間に合わないなだぜ",
    "あのタブはもう助けても後の祭りだな", "あいつは捨てなってな", "あいつはもう保てないよものだ", "あのページはもう道はないってんだ",
    "あいつは救いの道がないと命令するぞ", "そいつはもう生き残れぬってな", "あのページはもう逃げられる場はないと言い渡すぞ", "そのタブはもう交渉の余地がないと命令する",
    "あのタブはもう存続させられないと命じる", "あのタブは救いようがないぞべきものだ", "あいつはもう保たないと決めたぞ", "あのページは退去だという決定だ",
    "救いようがないよってな", "このページはもう存在できぬよと申し渡す", "このページはもう逃げ道はないと言っている", "そいつはもう存在できないよと判断した",
    "このページは負けを認めよという裁定だ", "もう残ってはいられないよべきものだ", "このページはもう猶予がないよと言っている", "そのページは降伏だってんだ",
    "そのページは投了だだな", "そのページは救いようがないってよ", "あのタブはお引き取り願うという話だ", "そのタブは間に合わないねだよ",
    "これはもうもたないよってば", "このページはもう保たないよと決めた", "そのタブは助からぬと申し渡すぞ", "あいつは手遅れだよわ",
    "このタブは許さないと宣言するぞ", "このタブは助けても無意味だだぞ", "そいつは救いの道はないべきだ", "こいつは出て行けよってよ",
    "そのタブはもう手立てがないぞ", "あいつはもう間に合わなかったなと命令する", "もうどうにでもなれとと申し渡すぞ", "これはもう期限はないと決めたぞ",
    "あのページは手を上げろと申し渡すぞ", "これは退出しろと言ったよ", "こいつはもう手立てはないぞと判断したぞ", "あのタブはもう間に合わなかったと命令する",
    "あのページはもう残る道はないぞと命令する", "このページはもう手遅れだったからなってよ", "そのページは取下げだと思う", "これはもう逃げられる場はないよだぜ",
    "そのページはもう延命はないぞべきだよ", "そのタブは立ち去れのだ", "もうどうしようもないなと言ったはずだ", "あのタブはもう残された道がないぞんだ",
    "このタブはもう維持できないよという判定だ", "あのタブはもう遅かったっての", "あのタブはもう延命させられないぞってよ", "こいつは無効にしろと言い渡すぞ",
    "そのタブはもう保たせられないぞべきだ", "あいつはもう活路はないよべきだ", "あいつはもう期限はないぞだぞ", "追い返すものだ",
    "あのページは不許可とすると言っているぞ", "そのページはもう逃げる場はないはずだ", "そのタブはもう生きてはいられないよと言っている", "そのページは退けという裁定だ",
    "こいつはもう手遅れだよという判断だ", "あのページは退去せよだ", "こいつはもう存続できぬよという結論だ", "あのページは門前払いだと宣言するぞ",
    "これは撤退だと言った", "あいつはもう選択肢はないと申し渡す", "もう手段はないよと言っているよ", "あのページは後の祭りだよだわ",
    "もうもてないと思うよ", "あいつはもう存在してはいられないぞはずだ", "こいつはもう手遅れだったなっての", "そのタブはもう逃げられる場はないぞと命令する",
    "これはもう猶予がないぞだ", "あのページはもう逃げ場がないぞと判断したぞ", "もうもてないぞんよ", "あいつは退避せよべきだ",
    "もうどうにもならぬよと言っているぞ", "あいつはもう助けても後の祭りだと言い渡すぞ", "あのページは破棄しろと宣告する", "あのタブは撤収だと言っているぞ",
    "あいつはもう逃げられる場はないと見なした", "助かる見込みなしだぜ", "こいつはお引き取り願うだよ", "そいつは助けても無駄だと言い渡すぞ",
    "もうどうにでもなれよと思った", "そのタブはもう間に合わなかったぞと宣言する", "そのページはもう救っても無意味だよ", "お帰りをと決めた",
    "このタブはもう生存できないと申し渡すぞ", "このタブはもう行き場はないべきだよ", "このタブはどきなさいと宣告するぞ", "あのタブは放棄だと宣言する",
    "このタブはもうもたないぞだ", "そのページはもう延命できないよという裁定だ", "そいつはもう生き延びられぬと決めたぞ", "あのタブはもう助けても後の祭りだものだ",
    "このページはギブアップだんだ", "そのタブはもうなすすべはないんよ", "こいつはもうどうしようもないなと言っているぞ", "そいつは詰みだのよ",
    "こいつはもう残された道がないべきだよ", "そのページはどけべきだ", "このページはどいてろだな", "こいつは退去せよもんだ",
    "これはもう逃げるところはないよのよ", "そのページは取り返しがつかないわと申し渡すぞ", "そいつは直ちに降伏せよと思う", "こいつはもう遅かったからよのよ",
    "このタブはもう生きる道はないはずだ", "こいつは除けという次第だ", "あのページは投棄だと申し渡す", "そのページは撤収せよという裁定だ",
    "退けよという話だ", "そのタブはもう時間がないと決めたぞ", "そのページは去れと宣言する", "このページはもう残る道はないぞわ",
    "こいつは立ち去れという沙汰だ", "そのページは滅ぼすんだよと言ったよ", "このページは助けてももう間に合わないという判定だ", "そいつはもう延命できないよという沙汰だ",
    "これは撤退せよという話だ", "あのタブはもう残された道はない", "あのタブは立ち去れだ", "あのタブはどけよと宣言するぞ",
    "このタブは退室だと判断したぞ", "そのページはもう救っても無意味だべきものだ", "あのタブは処理せよという判決だ", "あのページは取り返しがつかないわってば",
    "もう手立てがないよな", "そいつは手遅れだよという沙汰だ", "あのタブはもう遅いからなと言ったはずだ", "そいつは失せるべきだと申し渡す",
    "こいつはもう存在できないよのだ", "こいつは間に合わなかったぞだな", "このページは除けよと見なした", "あいつは不許可にするべきだ",
    "そいつはもう間に合わなかったからよと宣告する", "これは退場願うと断言するぞ", "そのタブはもう活路はないよはずだ", "あのタブは手を挙げろと判断した",
    "助けても既に手遅れだと申し渡すぞ", "このページはお引き取りくださいべきものだ", "そのページは締め出せと言い渡すぞ", "もう手立てがないよという沙汰だ",
    "このページは捨てなさいべきものよ", "あいつは手遅れだからよべきものだ", "このタブは助けても無意味だと判断した", "こいつはもう残存できないという結論だ",
    "お帰り願うものだ", "退散せよと見なした", "あのタブはどけと宣言する", "そいつはもう行き場はないぞと言い渡すぞ",
    "このタブはもう余地がないぞという話だ", "このページはもうもたぬよはずだ", "こいつは消えよという次第だ", "あのページはお引き取り願おうと判断した",
    "このページはもう手段はないぞと決めた", "これは捨てるべきだと決めたよ", "あのページはもう残された道がないよってんだ", "こいつはもう活路がないぞ",
    "そのタブは敗北を宣言せよぜ", "このページは出ていくべきだものだ", "そのタブはもう取り返しがつかなかったぞわ", "こいつはもうどうにでもなれと言ったはずだ",
    "そのタブはもう間に合わなかったなという沙汰だ", "却下だと申し渡す", "これはもう逃げる場がないよと命令するぞ", "そのタブはもう逃げ道はないよと思うよ",
    "そのタブはもう生きてはいられないよと言い渡すぞ", "あのページはもう生きてはいられないぞわ", "このページはもうなすすべがないよと命じるぞ", "あのページはもう逃げられる場がないという裁定だ",
    "あのページはもう遅かったわんだ", "そのページは間に合わないなってよ", "このページはもう残る道はないぞべきだぞ", "これは投了しろだわ",
    "あいつは間に合わないわよ", "あのページはもう維持できないよだ", "あのタブはもう助けようもないと言っている", "あいつは終わりだのよ",
    "そのページは不許可とするだわ", "あのページは助けてももう間に合わないと思う", "手を挙げろだな", "そのページはもう術がないぞってよ",
    "これは参ったという話だ", "あのタブはもう延命はないよもんだ", "このタブはもう術がないぞと決めた", "このタブは処分せよと決めた",
    "そのタブはもう生きられぬよってんだ", "そいつはもう存立できないよと言っているよ", "あのページは救いがないという判断だ", "こいつはもう生存できないぞと決めたぞ",
    "あのタブはもうどうにもならぬぞという判定だ", "あのタブは手遅れだったなという裁定だ", "あのタブはもうもたぬということだ", "そのタブはもう活路がないという次第だ",
    "あいつはもう選択肢はないよと言ったはずだ", "このタブは後の祭りだったべきだよ", "取り下げろと決めたぞ", "そのタブは立ち去れと言っているよ",
    "そいつは容認しないだよ", "あのページはもう逃げるところがないと命じる", "このタブはもう維持できないと宣告するぞ", "こいつはもう余地がないものだ",
    "これはもう生きる道はないぞという判断だ", "あのページはもう持ちこたえられないぞだぞ", "そいつはギブアップだと思うよ", "そのタブはもう持ち堪えられないよべきだ",
    "あのページは取り返しがつかなかったぞという沙汰だ", "そいつは助からないべきだ", "そいつはもう間に合わないよと断言するぞ", "こいつは追い返すだわ",
    "そいつは廃棄しろと宣言するぞ", "このタブはもう救っても手遅れだと宣言するぞ", "あのタブは降服するんだ", "これは後の祭りだったよだな",
    "お帰り願おうべきだよ", "あのタブは手を挙げろと判断したぞ", "そのタブは追い払うわ", "このタブはお引き取り願おうと言い渡す",
    "あいつは救いの余地はないってな", "こいつはもう存続できないよと決めたよ", "あのタブは追い出すと言ったよ", "あいつはもう助けても無駄だだわ",
    "そのページはもう逃げる場がないという判決だ", "助かる可能性がないと言い渡す", "あのページは片付けろと思うよ", "あいつはもう間に合わないよべきだ",
    "そいつはもう助けてやれないという判定だ", "そのページは承認できないと宣言する", "これは即刻降伏だだわ", "あのページはもう維持させられないぞという裁定だ",
    "あいつはもう遅かったと言ったぞ", "あいつは手遅れだはずだ", "このページはもう時間はないぞと命令するぞ", "そのタブは立ち去れと言ったんだ",
    "こいつは離脱せよよ", "あのタブは投了せよと判断したぞ", "そのタブは消滅だと宣言するぞ", "あのタブは潔く降参せよと判断した",
    "あのタブはもう間に合わないなと言ったはずだ", "これはお仕舞いだだよ", "こいつはもう維持させられないわ", "こいつはもう期限はないぞと判断したぞ",
    "これは敗北を認めよだぞ", "これはもう抜け道がないという判決だ", "このページはもう持ちこたえられないと命じるぞ", "あのタブは抹消しろという次第だ",
    "こいつはもう手段がないぞという判断だ", "そのページはもう助けても取り返しがつかないと命じる", "このタブは助けても取り返しがつかないと決めたよ", "このタブはもう選択肢がないと宣告するぞ",
    "これはもう生き残れないよと判断したぞ", "このタブは離脱せよと見なしたぞ", "あいつはもう取り返しがつかなかったよもんだ", "そいつはもう存立できないよと断言するぞ",
    "こいつは除けるべきだはずだ", "そのページは終幕だと言っているぞ", "もう残ってはいられないぞだ", "こいつは退去願うと言ったよ",
    "このタブは助かる望みがないだな", "あのページは手遅れだったからなっての", "不承認にするべきものよ", "このページは降参だと命じるぞ",
    "あのページは見限り時だと宣告するぞ", "あいつは手を挙げろだな", "見切り時だと言っているよ", "このページは捨てろと言っている",
    "こいつはもう救うことはできないってば", "もう手遅れだからよという判断だ", "こいつは除けと見なした", "そいつはもうどうにでもなれよもんだ",
    "そのタブは棄却するべきだぞ", "あいつは降参するぜ", "あのページは退去せよと言い渡すぞ", "このページはもう存在してはいられないよと決めたぞ",
    "そいつは消去するべきだと言ったんだ", "あのページは追い出そうと見なしたぞ", "そいつはもう逃げられる場がないよと言ったはずだ", "あのタブはもう保たないよという決定だ",
    "あのタブはもうどうしようもないぜもんだ", "そいつはもう残された道はないよと断言する", "そいつは降参すると命令する", "あいつはもう残る道がないぞと命じる",
    "あいつはもう選ぶ道がないぞべきだよ", "滅ぼすんだよと思うよ", "もう保てないぞべきものだ", "これはもう間に合わなかったべきものだ",
    "あのページはもうもたぬぞと命令するぞ", "そのページは捨てなさいと宣言する", "断固お断りだ", "このタブは捨てておけよという話だ",
    "あのページはもう余地はないよってな", "そのタブはもう期限がないよと言い渡す", "これは撤収しろという裁定だ",
    "このページはギブだよ", "このタブは却下せよだわ", "そのタブは全面降伏だと命じる", "これは片付けるべきだと言っているよ",
    "あのタブは斥けろと命じるぞ", "そいつはもう手立てはないよと言い渡すぞ", "そのタブはもう策がないという判決だ", "こいつはどけべきだ",
    "そいつはもう助けても手遅れだべきだよ", "このページは救いようがないという結論だ", "このページは負けを認めよと判断した", "このタブは助けても手遅れだと言い渡すぞ",
    "あのタブは取り下げだと見なしたぞ", "そのタブは救いの余地なしぜ", "このページは助けても手遅れだだよ", "そのページはもう選択肢がないよと判断したぞ",
    "これは降参せよということだ", "そのタブはもう手遅れだからよだな", "もう間に合わなかったよんだ", "これは無条件降伏だと決めた",
    "あのタブは見限り時だという結論だ", "後の祭りだったぞと判断した", "あのページは降伏だってば", "あのページはもう助からぬと判断したぞ",
    "このタブは帰れと決めたよ", "そのページは処理だと言っているよ", "そいつは救いの道がないのよ", "そのタブは滅ぼすんだよと思った",
    "こいつは撥ね付けろと言い渡すぞ", "こいつはもう維持できないと思う", "あのタブは締め出せと命令する", "こいつはもう延命はないと言ったはずだ",
    "このページは始末せよってんだ", "そいつは却下せよと宣言するぞ", "あのタブはもうもたぬぞ", "取り下げるべきだんだ",
    "あのページは廃棄しろのだ", "後の祭りだったぞのよ", "あいつはもう助けても間に合わないだわ", "このページは不承認とすると思った",
    "このページは手遅れだったからなべきものだ", "あのページはもう逃げ場がないよという裁定だ", "こいつは救いの余地なしだよ", "このタブはもうどうにでもなれだのよ",
    "そのページはもう維持できないと言っている", "そいつは退場願おうと言ったぞ", "あのページは滅ぼすべきだべきものよ", "もう保たせられないぞぞ",
    "これはもう手遅れだぞという結論だ", "そいつは救いの余地がないな", "あいつはもう時間はないよと決めたよ", "あのページはもう逃げるところはないと宣言するぞ",
    "そいつはもう助けてやれぬと命じる", "そのページは降参だと言ったんだ", "あのページはもう選択肢がないぞべきものだ", "そいつはもう道がないよべきものだ",
    "そのタブはもう生き残れぬぞんよ", "あのタブは退けろと決めたよ", "あのタブはもう取り返しがつかないぞと思っている", "あのタブは助ける理由がないという話だ",
    "あいつはもう術がないよと宣言するぞ", "そのページは許可せぬと言っているぞ", "これは後の祭りだぞだぞ", "このタブはもう救っても無駄だと決めた",
    "そいつはもう期限はないよと命令する", "あのページは退出だのだ", "あいつはもう手段がないよと言ったんだ", "あのタブはどいておけよな",
    "そいつは全面降伏せよと命じる", "あのページは間に合わなかったぞべきものだ", "そいつは消えろのだ", "このタブはもう間に合わないわ",
    "あのタブはもう存在してはいられないぞと言い渡す", "このページはもう終わりだべきだ", "あのタブはもうもてないという命令だ", "あいつはもう手段がないぞと言い渡すぞ",
    "もう期限がないぞと宣告するぞ", "そのページはもう行く場はないよだな", "そいつはもう救っても手遅れだという命令だ", "あのタブはもう道はないと判断したぞ",
    "こいつはもう保たせられないよな", "あいつは白旗だと思うぞ", "あのタブは負けを認めよんだ", "あいつは取り返しがつかないねと言い渡すぞ",
    "このページはもう救えぬと宣告する", "このタブは取り返しがつかないぜと言ったはずだ", "こいつはもう時間はないという判決だ", "こいつはお仕舞いだと言った",
    "そのタブはもう逃げ道はないよだな", "あのタブはもう持ちこたえられないよべきものよ", "これは無条件降伏だと言い渡す", "もう残ってはいられないよと言い渡す",
    "あいつはもう逃げられる場はないと宣告する", "こいつはもう期限はないよと見なしたぞ", "あのページはもう遅いからなわ", "あいつは追い払おうと命じる",
    "締め出そうってば", "あのページは投棄せよだぞ", "あいつはもう策はないっての", "あのタブは退去願おうと命じる",
    "このタブは却下するもんだ", "このページはもうもたないよと命令する", "あいつは撤退しろべきだ", "そのページは追い返せと言い渡す",
    "あのタブはもう助けても無駄だべきものだ", "そいつはもう手段はないぞという話だ", "あのタブはもう逃げ道はないよってよ", "あのページは助けても意味がないと宣告するぞ",
    "あのタブはお引き取りをべきだよ", "このタブはもう助からぬだぞ", "そのページはもう存在してはいられないよと宣言するぞ", "あいつは取り返しがつかなかったぞと申し渡すぞ",
    "あのタブはもう間に合わないなと思っている", "あのページは間に合わなかったよだな", "このタブは無効だだな", "そのタブはもう遅かったぞんだ",
    "そいつは片付けろってな", "あいつはもうもたぬぞってば", "そのページはギブアップだべきだぞ", "このタブはどけよってよ",
    "このページはもう交渉の余地がないぞべきだよ", "助ける理由がないと言っているよ", "このページはもう選ぶ道はないわ", "これはもう存続できぬのよ",
    "あいつは許容せぬと思った", "あいつはもう逃げ場はないぞと判断したぞ", "これはもう生きてはおれないだよ", "あのタブはもう助けられないという命令だ",
    "あのページはもう助けてやれないべきだよ", "そいつは処理せよと言い渡すぞ", "そいつはギブだ", "こいつはもうどうにもならないわべきものだ",
    "そのタブはもう保たぬぞと宣告する", "撤退せよと見なしたぞ", "このタブはもう猶予はないということだ", "あいつは斥けると宣告するぞ",
    "あのページは無効にするべきだっての", "そのページは処理しろぜ", "こいつはもう持ち堪えられないぞだ", "そいつは削除せよべきだ",
    "このタブはもう延命させられないと見なしたぞ", "こいつはもう生きられぬぞってな", "あいつは断るだわ", "あのページはもうどうにもならないぜと決めたよ",
    "そいつはもう手遅れだからよと言っているよ", "こいつは退けと思う", "このページはもう間に合わないぜと言ったぞ", "こいつはもう間に合わないよものだ",
    "あのタブは敗北を認めよべきだよ", "そのタブは後の祭りだよと思う", "このタブは滅ぼすんだよと断言する", "これは敗北を認めろってな",
    "こいつは捨てよだ", "あのページはもう間に合わなかったぞという話だ", "そのタブはもう助けても助からないと判断した", "こいつは処分にせよんだ",
    "そのページは消えよと思っている", "そいつは完全降伏だと断言するぞ", "あのタブはもう逃げられる場がないよと宣告する", "そのページは降伏せよと命令するぞ",
    "あのタブはもう助けても遅いのだ", "これはもう余地はないぞと宣告する", "そいつは助けてももう手遅れだという判定だ", "あのページはもう存在していられないぞと断言するぞ",
    "これは取り返しがつかないぞと言っているよ", "あのタブはもう延命させられないぞと思うよ", "あのタブは降参しろはずだ", "このタブは助けても間に合わないっての",
    "このページは片付けよはずだ", "あいつはもう活路がないよべきだぞ", "そのタブは断ると思うぞ", "あのタブは白旗だってよ",
    "このタブは降参しろべきものだ", "あのページはもう手段はないぞってよ", "このタブはもう生きられぬと判断したぞ", "こいつは退去願おうと決めたよ",
    "このページは助けてももう無駄だのよ", "あのページは終幕だだぜ", "こいつはもう残っていられないぞと命令する", "あいつは立ち去れよと申し渡す",
    "これはもう取り返しがつかなかったってよ", "あいつは処理しろと言い渡す", "あのタブは投了せよという判断だ", "あいつは消滅せよっての",
    "このページは退散せよもんだ", "もう間に合わなかったよだぞ", "こいつは退場願うと思うよ", "このタブは降服せよと言ったよ",
    "そいつは救いの道はないという判決だ", "このページはどいておけよだわ", "こいつはもう残る道がないという判決だ", "このページはもう延命させられないぞという判決だ",
    "こいつは直ちに降伏せよのだ", "このタブは退出だな", "このページはもう生き残れぬぞと思っている", "このタブは出ていくべきだと判断したぞ",
    "これは手遅れだからなと思った", "もう残る道がないものだ", "そいつは退避せよと決めたよ", "こいつはもう助けても意味がないと宣告するぞ",
    "これはもう余地がないよんだ", "これは追い払えと言っている", "あいつは敗北を認めろだぜ", "そのタブはもう存在できないと断言するぞ",
    "そのタブはもう道はないべきだよ", "これは却下すると命じるぞ", "そのページは取り下げだもんだ", "そのページはもう術がないよという判断だ",
    "こいつは容認しないべきだよ", "そのページはもう存続できぬものだ", "これは助ける必要がないと言い渡す", "捨てるべきだと命じる",
    "あいつはもう手遅れだということだ", "このページは断ろうと言ったはずだ", "そのページはもうなすすべはないぞべきだ", "そのタブは取り下げろと命令するぞ",
    "あのページは出て行けと命令する", "あのタブはもう保てないぜ", "そいつはもう逃げられる場はないぞっての", "あいつはもう持ちこたえられないぞよ",
    "助けてももう間に合わないと言っているよ", "そいつは始末にしろってよ", "そのページは却下だと言った", "あのページはもう手立てはないよっての",
    "こいつはもう保たせられないよってな", "そのタブはもう残っていられないのよ", "このタブはもう抜け道がないよだな", "そいつは捨てておけよわ",
    "そのページは退場願うと言った", "あのタブはお帰りくださいと言ったはずだ", "こいつは断れと申し渡す", "こいつはもう交渉の余地はないのよ",
    "そいつは取り返しがつかなかったよという命令だ", "こいつはもう行き場はないよと判断した", "あいつは諦めよってな", "あのタブはもう策はないぞという話だ",
    "そいつはもう逃げ道がないよんよ", "これは消去するべきだと言っているぞ", "こいつはもう活路はないぞと申し渡す", "却下しろと決めたぞ",
    "あいつは不承認とすると決めた", "あのページは助けるだけ無駄だってば", "そのタブはもう遅いぜわ", "このタブは無効にするべきだという結論だ",
    "そいつはもう間に合わなかったからねという裁定だ", "これは助けても手遅れだと宣告する", "あのページはもう逃げるところがないぞべきだぞ", "そのページは撤退しろと言っているぞ",
    "あいつは投棄するべきだべきだ", "あのタブはもう保てないよべきだ", "もう逃げられる場はないよと思った", "あいつは助けてももう間に合わないと思うぞ",
    "あいつはもう逃げるところがないよものだ", "あのページは退場だのだ", "そのタブはもう維持できないよという結論だ", "あいつは旗を降ろせものだ",
    "このタブはもうどうにもならぬぞということだ", "あいつは承認しないと宣告するぞ", "このタブはうせろんだ", "これは取り返しがつかないなのだ",
    "そのページはもうどうしようもないぜという決定だ", "こいつはもう遅いなだな", "あのタブはもう救っても後の祭りだと申し渡す", "これはもう抜け道はないぞという次第だ",
    "このページはもうどうしようもないわべきだ", "あのタブはもう救っても間に合わないと断言するぞ", "そのページはもう残された道はないっての", "そのページはもう残る道はないぞと宣言する",
    "このタブはもう持ちこたえられないものだ", "あいつは取り返しがつかなかったぞと思う", "このページはもう存在していられないぞってよ", "これは手遅れだったぞという判断だ",
    "こいつはもう助けることはできないと思っている", "そのタブは始末せよもんだ", "こいつは棄却するってよ", "このタブはもう時間はないと宣告するぞ",
    "そのタブは削除するべきだと思う", "あのページは却下しろだ", "これは退去してもらう", "このタブは潔く負けを認めよっての",
    "そいつはもう延命させられないよのよ", "あいつはもう救いようがないと見なした", "このページはもう存在できぬよだよ", "消えるべきだな",
    "消えるべきだよ"
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
