// Pass CCLXVII: EN decree/judgment frames + JA 文書型敬体・禁制宣告 (pass CCLXVII)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXVII: close-tab coverage', () => {
  test.each([
    "i find the tab dead", "i find the tab done", "i find the tab finished", "i find the tab over",
    "i find the tab through", "i find the tab gone", "i find the tab obsolete", "i find the tab defunct",
    "the tab is beyond help by decree", "the tab is beyond help by order", "the tab is beyond help by proclamation", "the tab is beyond help by edict",
    "the tab is beyond help by statute", "the tab is beyond help by fiat", "i declare the tab dead", "the tab is hereby declared dead",
    "i declare the tab done", "the tab is hereby declared done", "i declare the tab finished", "the tab is hereby declared finished",
    "i declare the tab over", "the tab is hereby declared over", "i declare the tab through", "the tab is hereby declared through",
    "i declare the tab gone", "the tab is hereby declared gone", "i declare the tab obsolete", "the tab is hereby declared obsolete",
    "i declare the tab defunct", "the tab is hereby declared defunct", "i pronounce the tab dead", "the tab is hereby pronounced dead",
    "i pronounce the tab done", "the tab is hereby pronounced done", "i pronounce the tab finished", "the tab is hereby pronounced finished",
    "i pronounce the tab over", "the tab is hereby pronounced over", "i pronounce the tab through", "the tab is hereby pronounced through",
    "i pronounce the tab gone", "the tab is hereby pronounced gone", "i pronounce the tab obsolete", "the tab is hereby pronounced obsolete",
    "i pronounce the tab defunct", "the tab is hereby pronounced defunct", "i decree the tab dead", "the tab is hereby decreed dead",
    "i decree the tab done", "the tab is hereby decreed done", "i decree the tab finished", "the tab is hereby decreed finished",
    "i decree the tab over", "the tab is hereby decreed over", "i decree the tab through", "the tab is hereby decreed through",
    "i decree the tab gone", "the tab is hereby decreed gone", "i decree the tab obsolete", "the tab is hereby decreed obsolete",
    "i decree the tab defunct", "the tab is hereby decreed defunct", "i ordain the tab dead", "the tab is hereby ordaind dead",
    "i ordain the tab done", "the tab is hereby ordaind done", "i ordain the tab finished", "the tab is hereby ordaind finished",
    "i ordain the tab over", "the tab is hereby ordaind over", "i ordain the tab through", "the tab is hereby ordaind through",
    "i ordain the tab gone", "the tab is hereby ordaind gone", "i ordain the tab obsolete", "the tab is hereby ordaind obsolete",
    "i ordain the tab defunct", "the tab is hereby ordaind defunct", "i rule the tab dead", "the tab is hereby ruled dead",
    "i rule the tab done", "the tab is hereby ruled done", "i rule the tab finished", "the tab is hereby ruled finished",
    "i rule the tab over", "the tab is hereby ruled over", "i rule the tab through", "the tab is hereby ruled through",
    "i rule the tab gone", "the tab is hereby ruled gone", "i rule the tab obsolete", "the tab is hereby ruled obsolete",
    "i rule the tab defunct", "the tab is hereby ruled defunct", "i adjudge the tab dead", "the tab is hereby adjudged dead",
    "i adjudge the tab done", "the tab is hereby adjudged done", "i adjudge the tab finished", "the tab is hereby adjudged finished",
    "i adjudge the tab over", "the tab is hereby adjudged over", "i adjudge the tab through", "the tab is hereby adjudged through",
    "i adjudge the tab gone", "the tab is hereby adjudged gone", "i adjudge the tab obsolete", "the tab is hereby adjudged obsolete",
    "i adjudge the tab defunct", "the tab is hereby adjudged defunct", "the tab is hereby findd dead", "the tab is hereby findd done",
    "the tab is hereby findd finished", "the tab is hereby findd over", "the tab is hereby findd through", "the tab is hereby findd gone",
    "the tab is hereby findd obsolete", "the tab is hereby findd defunct", "i hold the tab dead", "the tab is hereby holdd dead",
    "i hold the tab done", "the tab is hereby holdd done", "i hold the tab finished", "the tab is hereby holdd finished",
    "i hold the tab over", "the tab is hereby holdd over", "i hold the tab through", "the tab is hereby holdd through",
    "i hold the tab gone", "the tab is hereby holdd gone", "i hold the tab obsolete", "the tab is hereby holdd obsolete",
    "i hold the tab defunct", "the tab is hereby holdd defunct", "i deem the tab dead", "the tab is hereby deemd dead",
    "i deem the tab done", "the tab is hereby deemd done", "i deem the tab finished", "the tab is hereby deemd finished",
    "i deem the tab over", "the tab is hereby deemd over", "i deem the tab through", "the tab is hereby deemd through",
    "i deem the tab gone", "the tab is hereby deemd gone", "i deem the tab obsolete", "the tab is hereby deemd obsolete",
    "i deem the tab defunct", "the tab is hereby deemd defunct", "i adjudge the tab dead", "the tab is hereby adjudged dead",
    "i adjudge the tab done", "the tab is hereby adjudged done", "i adjudge the tab finished", "the tab is hereby adjudged finished",
    "i adjudge the tab over", "the tab is hereby adjudged over", "i adjudge the tab through", "the tab is hereby adjudged through",
    "i adjudge the tab gone", "the tab is hereby adjudged gone", "i adjudge the tab obsolete", "the tab is hereby adjudged obsolete",
    "i adjudge the tab defunct", "the tab is hereby adjudged defunct", "i repute the tab dead", "the tab is hereby reputed dead",
    "i repute the tab done", "the tab is hereby reputed done", "i repute the tab finished", "the tab is hereby reputed finished",
    "i repute the tab over", "the tab is hereby reputed over", "i repute the tab through", "the tab is hereby reputed through",
    "i repute the tab gone", "the tab is hereby reputed gone", "i repute the tab obsolete", "the tab is hereby reputed obsolete",
    "i repute the tab defunct", "the tab is hereby reputed defunct", "i account the tab dead", "the tab is hereby accountd dead",
    "i account the tab done", "the tab is hereby accountd done", "i account the tab finished", "the tab is hereby accountd finished",
    "i account the tab over", "the tab is hereby accountd over", "i account the tab through", "the tab is hereby accountd through",
    "i account the tab gone", "the tab is hereby accountd gone", "i account the tab obsolete", "the tab is hereby accountd obsolete",
    "i account the tab defunct", "the tab is hereby accountd defunct", "i esteem the tab dead", "the tab is hereby esteemd dead",
    "i esteem the tab done", "the tab is hereby esteemd done", "i esteem the tab finished", "the tab is hereby esteemd finished",
    "i esteem the tab over", "the tab is hereby esteemd over", "i esteem the tab through", "the tab is hereby esteemd through",
    "i esteem the tab gone", "the tab is hereby esteemd gone", "i esteem the tab obsolete", "the tab is hereby esteemd obsolete",
    "i esteem the tab defunct", "the tab is hereby esteemd defunct", "i count the tab dead", "the tab is hereby countd dead",
    "i count the tab done", "the tab is hereby countd done", "i count the tab finished", "the tab is hereby countd finished",
    "i count the tab over", "the tab is hereby countd over", "i count the tab through", "the tab is hereby countd through",
    "i count the tab gone", "the tab is hereby countd gone", "i count the tab obsolete", "the tab is hereby countd obsolete",
    "i count the tab defunct", "the tab is hereby countd defunct", "i rate the tab dead", "the tab is hereby rated dead",
    "i rate the tab done", "the tab is hereby rated done", "i rate the tab finished", "the tab is hereby rated finished",
    "i rate the tab over", "the tab is hereby rated over", "i rate the tab through", "the tab is hereby rated through",
    "i rate the tab gone", "the tab is hereby rated gone", "i rate the tab obsolete", "the tab is hereby rated obsolete",
    "i rate the tab defunct", "the tab is hereby rated defunct", "i rank the tab dead", "the tab is hereby rankd dead",
    "i rank the tab done", "the tab is hereby rankd done", "i rank the tab finished", "the tab is hereby rankd finished",
    "i rank the tab over", "the tab is hereby rankd over", "i rank the tab through", "the tab is hereby rankd through",
    "i rank the tab gone", "the tab is hereby rankd gone", "i rank the tab obsolete", "the tab is hereby rankd obsolete",
    "i rank the tab defunct", "the tab is hereby rankd defunct", "i reckon the tab dead", "the tab is hereby reckond dead",
    "i reckon the tab done", "the tab is hereby reckond done", "i reckon the tab finished", "the tab is hereby reckond finished",
    "i reckon the tab over", "the tab is hereby reckond over", "i reckon the tab through", "the tab is hereby reckond through",
    "i reckon the tab gone", "the tab is hereby reckond gone", "i reckon the tab obsolete", "the tab is hereby reckond obsolete",
    "i reckon the tab defunct", "the tab is hereby reckond defunct", "i weigh the tab dead", "the tab is hereby weighd dead",
    "i weigh the tab done", "the tab is hereby weighd done", "i weigh the tab finished", "the tab is hereby weighd finished",
    "i weigh the tab over", "the tab is hereby weighd over", "i weigh the tab through", "the tab is hereby weighd through",
    "i weigh the tab gone", "the tab is hereby weighd gone", "i weigh the tab obsolete", "the tab is hereby weighd obsolete",
    "i weigh the tab defunct", "the tab is hereby weighd defunct", "the tab is dead by decree", "the tab is dead by order",
    "the tab is dead by proclamation", "the tab is dead by edict", "the tab is dead by statute", "the tab is dead by fiat",
    "the tab stands dead", "the tab remains dead", "the tab is done by decree", "the tab is done by order",
    "the tab is done by proclamation", "the tab is done by edict", "the tab is done by statute", "the tab is done by fiat",
    "the tab stands done", "the tab remains done", "the tab is finished by decree", "the tab is finished by order",
    "the tab is finished by proclamation", "the tab is finished by edict", "the tab is finished by statute", "the tab is finished by fiat",
    "the tab stands finished", "the tab remains finished", "the tab is over by decree", "the tab is over by order",
    "the tab is over by proclamation", "the tab is over by edict", "the tab is over by statute", "the tab is over by fiat",
    "the tab stands over", "the tab remains over", "the tab is through by decree", "the tab is through by order",
    "the tab is through by proclamation", "the tab is through by edict", "the tab is through by statute", "the tab is through by fiat",
    "the tab stands through", "the tab remains through", "the tab is gone by decree", "the tab is gone by order",
    "the tab is gone by proclamation", "the tab is gone by edict", "the tab is gone by statute", "the tab is gone by fiat",
    "the tab stands gone", "the tab remains gone", "the tab is obsolete by decree", "the tab is obsolete by order",
    "the tab is obsolete by proclamation", "the tab is obsolete by edict", "the tab is obsolete by statute", "the tab is obsolete by fiat",
    "the tab stands obsolete", "the tab remains obsolete", "the tab is defunct by decree", "the tab is defunct by order",
    "the tab is defunct by proclamation", "the tab is defunct by edict", "the tab is defunct by statute", "the tab is defunct by fiat",
    "the tab stands defunct", "the tab remains defunct", "the tab is a write-off by decree", "the tab is a write-off by order",
    "the tab is a write-off by proclamation", "the tab is a write-off by edict", "the tab is a write-off by statute", "the tab is a write-off by fiat",
    "the tab stands a write-off", "the tab remains a write-off", "the tab is a goner by decree", "the tab is a goner by order",
    "the tab is a goner by proclamation", "the tab is a goner by edict", "the tab is a goner by statute", "the tab is a goner by fiat",
    "the tab stands a goner", "the tab remains a goner", "the tab is a lost cause by decree", "the tab is a lost cause by order",
    "the tab is a lost cause by proclamation", "the tab is a lost cause by edict", "the tab is a lost cause by statute", "the tab is a lost cause by fiat",
    "the tab stands a lost cause", "the tab remains a lost cause", "the tab stands beyond help", "the tab remains beyond help",
    "the tab is beyond repair by decree", "the tab is beyond repair by order", "the tab is beyond repair by proclamation", "the tab is beyond repair by edict",
    "the tab is beyond repair by statute", "the tab is beyond repair by fiat", "the tab stands beyond repair", "the tab remains beyond repair",
    "the tab is unsalvageable by decree", "the tab is unsalvageable by order", "the tab is unsalvageable by proclamation", "the tab is unsalvageable by edict",
    "the tab is unsalvageable by statute", "the tab is unsalvageable by fiat", "the tab stands unsalvageable", "the tab remains unsalvageable",
    "the tab is irretrievable by decree", "the tab is irretrievable by order", "the tab is irretrievable by proclamation", "the tab is irretrievable by edict",
    "the tab is irretrievable by statute", "the tab is irretrievable by fiat", "the tab stands irretrievable", "the tab remains irretrievable",
    "the tab is irredeemable by decree", "the tab is irredeemable by order", "the tab is irredeemable by proclamation", "the tab is irredeemable by edict",
    "the tab is irredeemable by statute", "the tab is irredeemable by fiat", "the tab stands irredeemable", "the tab remains irredeemable",
    "the tab is hopeless by decree", "the tab is hopeless by order", "the tab is hopeless by proclamation", "the tab is hopeless by edict",
    "the tab is hopeless by statute", "the tab is hopeless by fiat", "the tab stands hopeless", "the tab remains hopeless",
    "the tab is terminal by decree", "the tab is terminal by order", "the tab is terminal by proclamation", "the tab is terminal by edict",
    "the tab is terminal by statute", "the tab is terminal by fiat", "the tab stands terminal", "the tab remains terminal",
    "the tab is fatal by decree", "the tab is fatal by order", "the tab is fatal by proclamation", "the tab is fatal by edict",
    "the tab is fatal by statute", "the tab is fatal by fiat", "the tab stands fatal", "the tab remains fatal",
    "the tab is lethal by decree", "the tab is lethal by order", "the tab is lethal by proclamation", "the tab is lethal by edict",
    "the tab is lethal by statute", "the tab is lethal by fiat", "the tab stands lethal", "the tab remains lethal",
    "the tab is hereby closed", "hereby, the tab is closed", "the tab is hereby terminated", "hereby, the tab is terminated",
    "the tab is hereby ended", "hereby, the tab is ended", "the tab is hereby killed", "hereby, the tab is killed",
    "the tab is hereby destroyed", "hereby, the tab is destroyed", "the tab is hereby abolished", "hereby, the tab is abolished",
    "the tab is hereby annulled", "hereby, the tab is annulled", "the tab is hereby revoked", "hereby, the tab is revoked",
    "the tab is hereby repealed", "hereby, the tab is repealed", "the tab is hereby rescinded", "hereby, the tab is rescinded",
    "the tab is hereby overruled", "hereby, the tab is overruled", "the tab is hereby quashed", "hereby, the tab is quashed",
    "the tab is hereby voided", "hereby, the tab is voided", "the tab is hereby invalidated", "hereby, the tab is invalidated",
    "the tab is hereby dissolved", "hereby, the tab is dissolved", "the tab is hereby extinguished", "hereby, the tab is extinguished",
    "the tab is hereby expunged", "hereby, the tab is expunged", "the tab is hereby erased", "hereby, the tab is erased",
    "the tab is hereby deleted", "hereby, the tab is deleted", "the tab is hereby eliminated", "hereby, the tab is eliminated",
    "the tab is hereby removed", "hereby, the tab is removed", "the tab is hereby dismissed", "hereby, the tab is dismissed",
    "the tab is hereby discharged", "hereby, the tab is discharged", "the tab is hereby discontinued", "hereby, the tab is discontinued",
    "the tab is hereby suspended", "hereby, the tab is suspended", "the tab is hereby prohibited", "hereby, the tab is prohibited",
    "the tab is hereby forbidden", "hereby, the tab is forbidden", "the tab is hereby banned", "hereby, the tab is banned",
    "the tab is hereby barred", "hereby, the tab is barred", "the tab is hereby interdicted", "hereby, the tab is interdicted",
    "the tab is hereby enjoined", "hereby, the tab is enjoined", "the tab is hereby outlawed", "hereby, the tab is outlawed",
    "the tab is hereby proscribed", "hereby, the tab is proscribed", "the tab is thereupon closed", "thereupon, the tab is closed",
    "the tab is thereupon terminated", "thereupon, the tab is terminated", "the tab is thereupon ended", "thereupon, the tab is ended",
    "the tab is thereupon killed", "thereupon, the tab is killed", "the tab is thereupon destroyed", "thereupon, the tab is destroyed",
    "the tab is thereupon abolished", "thereupon, the tab is abolished", "the tab is thereupon annulled", "thereupon, the tab is annulled",
    "the tab is thereupon revoked", "thereupon, the tab is revoked", "the tab is thereupon repealed", "thereupon, the tab is repealed",
    "the tab is thereupon rescinded", "thereupon, the tab is rescinded", "the tab is thereupon overruled", "thereupon, the tab is overruled",
    "the tab is thereupon quashed", "thereupon, the tab is quashed", "the tab is thereupon voided", "thereupon, the tab is voided",
    "the tab is thereupon invalidated", "thereupon, the tab is invalidated", "the tab is thereupon dissolved", "thereupon, the tab is dissolved",
    "the tab is thereupon extinguished", "thereupon, the tab is extinguished", "the tab is thereupon expunged", "thereupon, the tab is expunged",
    "the tab is thereupon erased", "thereupon, the tab is erased", "the tab is thereupon deleted", "thereupon, the tab is deleted",
    "the tab is thereupon eliminated", "thereupon, the tab is eliminated", "the tab is thereupon removed", "thereupon, the tab is removed",
    "the tab is thereupon dismissed", "thereupon, the tab is dismissed", "the tab is thereupon discharged", "thereupon, the tab is discharged",
    "the tab is thereupon discontinued", "thereupon, the tab is discontinued", "the tab is thereupon suspended", "thereupon, the tab is suspended",
    "the tab is thereupon prohibited", "thereupon, the tab is prohibited", "the tab is thereupon forbidden", "thereupon, the tab is forbidden",
    "the tab is thereupon banned", "thereupon, the tab is banned", "the tab is thereupon barred", "thereupon, the tab is barred",
    "the tab is thereupon interdicted", "thereupon, the tab is interdicted", "the tab is thereupon enjoined", "thereupon, the tab is enjoined",
    "the tab is thereupon outlawed", "thereupon, the tab is outlawed", "the tab is thereupon proscribed", "thereupon, the tab is proscribed",
    "the tab is therefore closed", "therefore, the tab is closed", "the tab is therefore terminated", "therefore, the tab is terminated",
    "the tab is therefore ended", "therefore, the tab is ended", "the tab is therefore killed", "therefore, the tab is killed",
    "the tab is therefore destroyed", "therefore, the tab is destroyed", "the tab is therefore abolished", "therefore, the tab is abolished",
    "the tab is therefore annulled", "therefore, the tab is annulled", "the tab is therefore revoked", "therefore, the tab is revoked",
    "the tab is therefore repealed", "therefore, the tab is repealed", "the tab is therefore rescinded", "therefore, the tab is rescinded",
    "the tab is therefore overruled", "therefore, the tab is overruled", "the tab is therefore quashed", "therefore, the tab is quashed",
    "the tab is therefore voided", "therefore, the tab is voided", "the tab is therefore invalidated", "therefore, the tab is invalidated",
    "the tab is therefore dissolved", "therefore, the tab is dissolved", "the tab is therefore extinguished", "therefore, the tab is extinguished",
    "the tab is therefore expunged", "therefore, the tab is expunged", "the tab is therefore erased", "therefore, the tab is erased",
    "the tab is therefore deleted", "therefore, the tab is deleted", "the tab is therefore eliminated", "therefore, the tab is eliminated",
    "the tab is therefore removed", "therefore, the tab is removed", "the tab is therefore dismissed", "therefore, the tab is dismissed",
    "the tab is therefore discharged", "therefore, the tab is discharged", "the tab is therefore discontinued", "therefore, the tab is discontinued",
    "the tab is therefore suspended", "therefore, the tab is suspended", "the tab is therefore prohibited", "therefore, the tab is prohibited",
    "the tab is therefore forbidden", "therefore, the tab is forbidden", "the tab is therefore banned", "therefore, the tab is banned",
    "the tab is therefore barred", "therefore, the tab is barred", "the tab is therefore interdicted", "therefore, the tab is interdicted",
    "the tab is therefore enjoined", "therefore, the tab is enjoined", "the tab is therefore outlawed", "therefore, the tab is outlawed",
    "the tab is therefore proscribed", "therefore, the tab is proscribed", "the tab is henceforth closed", "henceforth, the tab is closed",
    "the tab is henceforth terminated", "henceforth, the tab is terminated", "the tab is henceforth ended", "henceforth, the tab is ended",
    "the tab is henceforth killed", "henceforth, the tab is killed", "the tab is henceforth destroyed", "henceforth, the tab is destroyed",
    "the tab is henceforth abolished", "henceforth, the tab is abolished", "the tab is henceforth annulled", "henceforth, the tab is annulled",
    "the tab is henceforth revoked", "henceforth, the tab is revoked", "the tab is henceforth repealed", "henceforth, the tab is repealed",
    "the tab is henceforth rescinded", "henceforth, the tab is rescinded", "the tab is henceforth overruled", "henceforth, the tab is overruled",
    "the tab is henceforth quashed", "henceforth, the tab is quashed", "the tab is henceforth voided", "henceforth, the tab is voided",
    "the tab is henceforth invalidated", "henceforth, the tab is invalidated", "the tab is henceforth dissolved", "henceforth, the tab is dissolved",
    "the tab is henceforth extinguished", "henceforth, the tab is extinguished", "the tab is henceforth expunged", "henceforth, the tab is expunged",
    "the tab is henceforth erased", "henceforth, the tab is erased", "the tab is henceforth deleted", "henceforth, the tab is deleted",
    "the tab is henceforth eliminated", "henceforth, the tab is eliminated", "the tab is henceforth removed", "henceforth, the tab is removed",
    "the tab is henceforth dismissed", "henceforth, the tab is dismissed", "the tab is henceforth discharged", "henceforth, the tab is discharged",
    "the tab is henceforth discontinued", "henceforth, the tab is discontinued", "the tab is henceforth suspended", "henceforth, the tab is suspended",
    "the tab is henceforth prohibited", "henceforth, the tab is prohibited", "the tab is henceforth forbidden", "henceforth, the tab is forbidden",
    "タブの閉鎖を言い渡す", "このタブの閉鎖を言い渡す", "タブの閉鎖を言い渡した", "このタブの閉鎖を言い渡した",
    "タブの閉鎖を宣告する", "このタブの閉鎖を宣告する", "タブの閉鎖を宣告した", "このタブの閉鎖を宣告した",
    "タブの閉鎖を布告する", "このタブの閉鎖を布告する", "タブの閉鎖を公布する", "このタブの閉鎖を公布する",
    "タブの閉鎖を発令する", "このタブの閉鎖を発令する", "タブの閉鎖を発令した", "このタブの閉鎖を発令した",
    "タブの閉鎖を命じる", "このタブの閉鎖を命じる", "タブの閉鎖を命じた", "このタブの閉鎖を命じた",
    "タブの閉鎖を命ずる", "このタブの閉鎖を命ずる", "タブの閉鎖を通達する", "このタブの閉鎖を通達する",
    "タブの閉鎖を通告する", "このタブの閉鎖を通告する", "タブの閉鎖を告示する", "このタブの閉鎖を告示する",
    "タブの閉鎖を公示する", "このタブの閉鎖を公示する", "タブの閉鎖を裁定する", "このタブの閉鎖を裁定する",
    "タブの閉鎖を裁可する", "このタブの閉鎖を裁可する", "タブの閉鎖を裁断する", "このタブの閉鎖を裁断する",
    "タブの閉鎖を下す", "このタブの閉鎖を下す", "タブの閉鎖を下した", "このタブの閉鎖を下した",
    "タブの閉鎖を執行する", "このタブの閉鎖を執行する", "タブの閉鎖を執行した", "このタブの閉鎖を執行した",
    "タブの閉鎖を決する", "このタブの閉鎖を決する", "タブの閉鎖を決定する", "このタブの閉鎖を決定する",
    "タブの閉鎖を決定した", "このタブの閉鎖を決定した", "タブの閉鎖を採択する", "このタブの閉鎖を採択する",
    "タブの閉鎖を議決する", "このタブの閉鎖を議決する", "タブの閉鎖を可決する", "このタブの閉鎖を可決する",
    "タブの閉鎖を決裁する", "このタブの閉鎖を決裁する", "タブの閉鎖を判決する", "このタブの閉鎖を判決する",
    "タブの閉鎖を申し渡す", "このタブの閉鎖を申し渡す", "タブの閉鎖を申し付ける", "このタブの閉鎖を申し付ける",
    "タブの閉鎖を申し付けた", "このタブの閉鎖を申し付けた", "タブの終了を言い渡す", "このタブの終了を言い渡す",
    "タブの終了を言い渡した", "このタブの終了を言い渡した", "タブの終了を宣告する", "このタブの終了を宣告する",
    "タブの終了を宣告した", "このタブの終了を宣告した", "タブの終了を布告する", "このタブの終了を布告する",
    "タブの終了を公布する", "このタブの終了を公布する", "タブの終了を発令する", "このタブの終了を発令する",
    "タブの終了を発令した", "このタブの終了を発令した", "タブの終了を命じる", "このタブの終了を命じる",
    "タブの終了を命じた", "このタブの終了を命じた", "タブの終了を命ずる", "このタブの終了を命ずる",
    "タブの終了を通達する", "このタブの終了を通達する", "タブの終了を通告する", "このタブの終了を通告する",
    "タブの終了を告示する", "このタブの終了を告示する", "タブの終了を公示する", "このタブの終了を公示する",
    "タブの終了を裁定する", "このタブの終了を裁定する", "タブの終了を裁可する", "このタブの終了を裁可する",
    "タブの終了を裁断する", "このタブの終了を裁断する", "タブの終了を下す", "このタブの終了を下す",
    "タブの終了を下した", "このタブの終了を下した", "タブの終了を執行する", "このタブの終了を執行する",
    "タブの終了を執行した", "このタブの終了を執行した", "タブの終了を決する", "このタブの終了を決する",
    "タブの終了を決定する", "このタブの終了を決定する", "タブの終了を決定した", "このタブの終了を決定した",
    "タブの終了を採択する", "このタブの終了を採択する", "タブの終了を議決する", "このタブの終了を議決する",
    "タブの終了を可決する", "このタブの終了を可決する", "タブの終了を決裁する", "このタブの終了を決裁する",
    "タブの終了を判決する", "このタブの終了を判決する", "タブの終了を申し渡す", "このタブの終了を申し渡す",
    "タブの終了を申し付ける", "このタブの終了を申し付ける", "タブの終了を申し付けた", "このタブの終了を申し付けた",
    "タブの廃止を言い渡す", "このタブの廃止を言い渡す", "タブの廃止を言い渡した", "このタブの廃止を言い渡した",
    "タブの廃止を宣告する", "このタブの廃止を宣告する", "タブの廃止を宣告した", "このタブの廃止を宣告した",
    "タブの廃止を布告する", "このタブの廃止を布告する", "タブの廃止を公布する", "このタブの廃止を公布する",
    "タブの廃止を発令する", "このタブの廃止を発令する", "タブの廃止を発令した", "このタブの廃止を発令した",
    "タブの廃止を命じる", "このタブの廃止を命じる", "タブの廃止を命じた", "このタブの廃止を命じた",
    "タブの廃止を命ずる", "このタブの廃止を命ずる", "タブの廃止を通達する", "このタブの廃止を通達する",
    "タブの廃止を通告する", "このタブの廃止を通告する", "タブの廃止を告示する", "このタブの廃止を告示する",
    "タブの廃止を公示する", "このタブの廃止を公示する", "タブの廃止を裁定する", "このタブの廃止を裁定する",
    "タブの廃止を裁可する", "このタブの廃止を裁可する", "タブの廃止を裁断する", "このタブの廃止を裁断する",
    "タブの廃止を下す", "このタブの廃止を下す", "タブの廃止を下した", "このタブの廃止を下した",
    "タブの廃止を執行する", "このタブの廃止を執行する", "タブの廃止を執行した", "このタブの廃止を執行した",
    "タブの廃止を決する", "このタブの廃止を決する", "タブの廃止を決定する", "このタブの廃止を決定する",
    "タブの廃止を決定した", "このタブの廃止を決定した", "タブの廃止を採択する", "このタブの廃止を採択する",
    "タブの廃止を議決する", "このタブの廃止を議決する", "タブの廃止を可決する", "このタブの廃止を可決する",
    "タブの廃止を決裁する", "このタブの廃止を決裁する", "タブの廃止を判決する", "このタブの廃止を判決する",
    "タブの廃止を申し渡す", "このタブの廃止を申し渡す", "タブの廃止を申し付ける", "このタブの廃止を申し付ける",
    "タブの廃止を申し付けた", "このタブの廃止を申し付けた", "タブの破棄を言い渡す", "このタブの破棄を言い渡す",
    "タブの破棄を言い渡した", "このタブの破棄を言い渡した", "タブの破棄を宣告する", "このタブの破棄を宣告する",
    "タブの破棄を宣告した", "このタブの破棄を宣告した", "タブの破棄を布告する", "このタブの破棄を布告する",
    "タブの破棄を公布する", "このタブの破棄を公布する", "タブの破棄を発令する", "このタブの破棄を発令する",
    "タブの破棄を発令した", "このタブの破棄を発令した", "タブの破棄を命じる", "このタブの破棄を命じる",
    "タブの破棄を命じた", "このタブの破棄を命じた", "タブの破棄を命ずる", "このタブの破棄を命ずる",
    "タブの破棄を通達する", "このタブの破棄を通達する", "タブの破棄を通告する", "このタブの破棄を通告する",
    "タブの破棄を告示する", "このタブの破棄を告示する", "タブの破棄を公示する", "このタブの破棄を公示する",
    "タブの破棄を裁定する", "このタブの破棄を裁定する", "タブの破棄を裁可する", "このタブの破棄を裁可する",
    "タブの破棄を裁断する", "このタブの破棄を裁断する", "タブの破棄を下す", "このタブの破棄を下す",
    "タブの破棄を下した", "このタブの破棄を下した", "タブの破棄を執行する", "このタブの破棄を執行する",
    "タブの破棄を執行した", "このタブの破棄を執行した", "タブの破棄を決する", "このタブの破棄を決する",
    "タブの破棄を決定する", "このタブの破棄を決定する", "タブの破棄を決定した", "このタブの破棄を決定した",
    "タブの破棄を採択する", "このタブの破棄を採択する", "タブの破棄を議決する", "このタブの破棄を議決する",
    "タブの破棄を可決する", "このタブの破棄を可決する", "タブの破棄を決裁する", "このタブの破棄を決裁する",
    "タブの破棄を判決する", "このタブの破棄を判決する", "タブの破棄を申し渡す", "このタブの破棄を申し渡す",
    "タブの破棄を申し付ける", "このタブの破棄を申し付ける", "タブの破棄を申し付けた", "このタブの破棄を申し付けた",
    "タブの削除を言い渡す", "このタブの削除を言い渡す", "タブの削除を言い渡した", "このタブの削除を言い渡した",
    "タブの削除を宣告する", "このタブの削除を宣告する", "タブの削除を宣告した", "このタブの削除を宣告した",
    "タブの削除を布告する", "このタブの削除を布告する", "タブの削除を公布する", "このタブの削除を公布する",
    "タブの削除を発令する", "このタブの削除を発令する", "タブの削除を発令した", "このタブの削除を発令した",
    "タブの削除を命じる", "このタブの削除を命じる", "タブの削除を命じた", "このタブの削除を命じた",
    "タブの削除を命ずる", "このタブの削除を命ずる", "タブの削除を通達する", "このタブの削除を通達する",
    "タブの削除を通告する", "このタブの削除を通告する", "タブの削除を告示する", "このタブの削除を告示する",
    "タブの削除を公示する", "このタブの削除を公示する", "タブの削除を裁定する", "このタブの削除を裁定する",
    "タブの削除を裁可する", "このタブの削除を裁可する", "タブの削除を裁断する", "このタブの削除を裁断する",
    "タブの削除を下す", "このタブの削除を下す", "タブの削除を下した", "このタブの削除を下した",
    "タブの削除を執行する", "このタブの削除を執行する", "タブの削除を執行した", "このタブの削除を執行した",
    "タブの削除を決する", "このタブの削除を決する", "タブの削除を決定する", "このタブの削除を決定する",
    "タブの削除を決定した", "このタブの削除を決定した", "タブの削除を採択する", "このタブの削除を採択する",
    "タブの削除を議決する", "このタブの削除を議決する", "タブの削除を可決する", "このタブの削除を可決する",
    "タブの削除を決裁する", "このタブの削除を決裁する", "タブの削除を判決する", "このタブの削除を判決する",
    "タブの削除を申し渡す", "このタブの削除を申し渡す", "タブの削除を申し付ける", "このタブの削除を申し付ける",
    "タブの削除を申し付けた", "このタブの削除を申し付けた", "タブの抹消を言い渡す", "このタブの抹消を言い渡す",
    "タブの抹消を言い渡した", "このタブの抹消を言い渡した", "タブの抹消を宣告する", "このタブの抹消を宣告する",
    "タブの抹消を宣告した", "このタブの抹消を宣告した", "タブの抹消を布告する", "このタブの抹消を布告する",
    "タブの抹消を公布する", "このタブの抹消を公布する", "タブの抹消を発令する", "このタブの抹消を発令する",
    "タブの抹消を発令した", "このタブの抹消を発令した", "タブの抹消を命じる", "このタブの抹消を命じる",
    "タブの抹消を命じた", "このタブの抹消を命じた", "タブの抹消を命ずる", "このタブの抹消を命ずる",
    "タブの抹消を通達する", "このタブの抹消を通達する", "タブの抹消を通告する", "このタブの抹消を通告する",
    "タブの抹消を告示する", "このタブの抹消を告示する", "タブの抹消を公示する", "このタブの抹消を公示する",
    "タブの抹消を裁定する", "このタブの抹消を裁定する", "タブの抹消を裁可する", "このタブの抹消を裁可する",
    "タブの抹消を裁断する", "このタブの抹消を裁断する", "タブの抹消を下す", "このタブの抹消を下す",
    "タブの抹消を下した", "このタブの抹消を下した", "タブの抹消を執行する", "このタブの抹消を執行する",
    "タブの抹消を執行した", "このタブの抹消を執行した", "タブの抹消を決する", "このタブの抹消を決する",
    "タブの抹消を決定する", "このタブの抹消を決定する", "タブの抹消を決定した", "このタブの抹消を決定した",
    "タブの抹消を採択する", "このタブの抹消を採択する", "タブの抹消を議決する", "このタブの抹消を議決する",
    "タブの抹消を可決する", "このタブの抹消を可決する", "タブの抹消を決裁する", "このタブの抹消を決裁する",
    "タブの抹消を判決する", "このタブの抹消を判決する", "タブの抹消を申し渡す", "このタブの抹消を申し渡す",
    "タブの抹消を申し付ける", "このタブの抹消を申し付ける", "タブの抹消を申し付けた", "このタブの抹消を申し付けた",
    "タブの消去を言い渡す", "このタブの消去を言い渡す", "タブの消去を言い渡した", "このタブの消去を言い渡した",
    "タブの消去を宣告する", "このタブの消去を宣告する", "タブの消去を宣告した", "このタブの消去を宣告した",
    "タブの消去を布告する", "このタブの消去を布告する", "タブの消去を公布する", "このタブの消去を公布する",
    "タブの消去を発令する", "このタブの消去を発令する", "タブの消去を発令した", "このタブの消去を発令した",
    "タブの消去を命じる", "このタブの消去を命じる", "タブの消去を命じた", "このタブの消去を命じた",
    "タブの消去を命ずる", "このタブの消去を命ずる", "タブの消去を通達する", "このタブの消去を通達する",
    "タブの消去を通告する", "このタブの消去を通告する", "タブの消去を告示する", "このタブの消去を告示する",
    "タブの消去を公示する", "このタブの消去を公示する", "タブの消去を裁定する", "このタブの消去を裁定する",
    "タブの消去を裁可する", "このタブの消去を裁可する", "タブの消去を裁断する", "このタブの消去を裁断する",
    "タブの消去を下す", "このタブの消去を下す", "タブの消去を下した", "このタブの消去を下した",
    "タブの消去を執行する", "このタブの消去を執行する", "タブの消去を執行した", "このタブの消去を執行した",
    "タブの消去を決する", "このタブの消去を決する", "タブの消去を決定する", "このタブの消去を決定する",
    "タブの消去を決定した", "このタブの消去を決定した", "タブの消去を採択する", "このタブの消去を採択する",
    "タブの消去を議決する", "このタブの消去を議決する", "タブの消去を可決する", "このタブの消去を可決する",
    "タブの消去を決裁する", "このタブの消去を決裁する", "タブの消去を判決する", "このタブの消去を判決する",
    "タブの消去を申し渡す", "このタブの消去を申し渡す", "タブの消去を申し付ける", "このタブの消去を申し付ける",
    "タブの消去を申し付けた", "このタブの消去を申し付けた", "タブの閉会を言い渡す", "このタブの閉会を言い渡す",
    "タブの閉会を言い渡した", "このタブの閉会を言い渡した", "タブの閉会を宣告する", "このタブの閉会を宣告する",
    "タブの閉会を宣告した", "このタブの閉会を宣告した", "タブの閉会を布告する", "このタブの閉会を布告する",
    "タブの閉会を公布する", "このタブの閉会を公布する", "タブの閉会を発令する", "このタブの閉会を発令する",
    "タブの閉会を発令した", "このタブの閉会を発令した", "タブの閉会を命じる", "このタブの閉会を命じる",
    "タブの閉会を命じた", "このタブの閉会を命じた", "タブの閉会を命ずる", "このタブの閉会を命ずる",
    "タブの閉会を通達する", "このタブの閉会を通達する", "タブの閉会を通告する", "このタブの閉会を通告する",
    "タブの閉会を告示する", "このタブの閉会を告示する", "タブの閉会を公示する", "このタブの閉会を公示する",
    "タブの閉会を裁定する", "このタブの閉会を裁定する", "タブの閉会を裁可する", "このタブの閉会を裁可する",
    "タブの閉会を裁断する", "このタブの閉会を裁断する", "タブの閉会を下す", "このタブの閉会を下す",
    "タブの閉会を下した", "このタブの閉会を下した", "タブの閉会を執行する", "このタブの閉会を執行する",
    "タブの閉会を執行した", "このタブの閉会を執行した", "タブの閉会を決する", "このタブの閉会を決する",
    "タブの閉会を決定する", "このタブの閉会を決定する", "タブの閉会を決定した", "このタブの閉会を決定した",
    "タブの閉会を採択する", "このタブの閉会を採択する", "タブの閉会を議決する", "このタブの閉会を議決する",
    "タブの閉会を可決する", "このタブの閉会を可決する", "タブの閉会を決裁する", "このタブの閉会を決裁する",
    "タブの閉会を判決する", "このタブの閉会を判決する", "タブの閉会を申し渡す", "このタブの閉会を申し渡す",
    "タブの閉会を申し付ける", "このタブの閉会を申し付ける", "タブの閉会を申し付けた", "このタブの閉会を申し付けた",
    "タブの中止を言い渡す", "このタブの中止を言い渡す", "タブの中止を言い渡した", "このタブの中止を言い渡した",
    "タブの中止を宣告する", "このタブの中止を宣告する", "タブの中止を宣告した", "このタブの中止を宣告した",
    "タブの中止を布告する", "このタブの中止を布告する", "タブの中止を公布する", "このタブの中止を公布する",
    "タブの中止を発令する", "このタブの中止を発令する", "タブの中止を発令した", "このタブの中止を発令した",
    "タブの中止を命じる", "このタブの中止を命じる", "タブの中止を命じた", "このタブの中止を命じた",
    "タブの中止を命ずる", "このタブの中止を命ずる", "タブの中止を通達する", "このタブの中止を通達する",
    "タブの中止を通告する", "このタブの中止を通告する", "タブの中止を告示する", "このタブの中止を告示する",
    "タブの中止を公示する", "このタブの中止を公示する", "タブの中止を裁定する", "このタブの中止を裁定する",
    "タブの中止を裁可する", "このタブの中止を裁可する", "タブの中止を裁断する", "このタブの中止を裁断する",
    "タブの中止を下す", "このタブの中止を下す", "タブの中止を下した", "このタブの中止を下した",
    "タブの中止を執行する", "このタブの中止を執行する", "タブの中止を執行した", "このタブの中止を執行した",
    "タブの中止を決する", "このタブの中止を決する", "タブの中止を決定する", "このタブの中止を決定する",
    "タブの中止を決定した", "このタブの中止を決定した", "タブの中止を採択する", "このタブの中止を採択する",
    "タブの中止を議決する", "このタブの中止を議決する", "タブの中止を可決する", "このタブの中止を可決する",
    "タブの中止を決裁する", "このタブの中止を決裁する", "タブの中止を判決する", "このタブの中止を判決する",
    "タブの中止を申し渡す", "このタブの中止を申し渡す", "タブの中止を申し付ける", "このタブの中止を申し付ける",
    "タブの中止を申し付けた", "このタブの中止を申し付けた", "タブの停止を言い渡す", "このタブの停止を言い渡す",
    "タブの停止を言い渡した", "このタブの停止を言い渡した", "タブの停止を宣告する", "このタブの停止を宣告する",
    "タブの停止を宣告した", "このタブの停止を宣告した", "タブの停止を布告する", "このタブの停止を布告する",
    "タブの停止を公布する", "このタブの停止を公布する", "タブの停止を発令する", "このタブの停止を発令する",
    "タブの停止を発令した", "このタブの停止を発令した", "タブの停止を命じる", "このタブの停止を命じる",
    "タブの停止を命じた", "このタブの停止を命じた", "タブの停止を命ずる", "このタブの停止を命ずる",
    "タブの停止を通達する", "このタブの停止を通達する", "タブの停止を通告する", "このタブの停止を通告する",
    "タブの停止を告示する", "このタブの停止を告示する", "タブの停止を公示する", "このタブの停止を公示する",
    "タブの停止を裁定する", "このタブの停止を裁定する", "タブの停止を裁可する", "このタブの停止を裁可する",
    "タブの停止を裁断する", "このタブの停止を裁断する", "タブの停止を下す", "このタブの停止を下す",
    "タブの停止を下した", "このタブの停止を下した", "タブの停止を執行する", "このタブの停止を執行する",
    "タブの停止を執行した", "このタブの停止を執行した", "タブの停止を決する", "このタブの停止を決する",
    "タブの停止を決定する", "このタブの停止を決定する", "タブの停止を決定した", "このタブの停止を決定した",
    "タブの停止を採択する", "このタブの停止を採択する", "タブの停止を議決する", "このタブの停止を議決する",
    "タブの停止を可決する", "このタブの停止を可決する", "タブの停止を決裁する", "このタブの停止を決裁する",
    "タブの停止を判決する", "このタブの停止を判決する", "タブの停止を申し渡す", "このタブの停止を申し渡す",
    "タブの停止を申し付ける", "このタブの停止を申し付ける", "タブの停止を申し付けた", "このタブの停止を申し付けた",
    "タブの解消を言い渡す", "このタブの解消を言い渡す", "タブの解消を言い渡した", "このタブの解消を言い渡した",
    "タブの解消を宣告する", "このタブの解消を宣告する", "タブの解消を宣告した", "このタブの解消を宣告した",
    "タブの解消を布告する", "このタブの解消を布告する", "タブの解消を公布する", "このタブの解消を公布する",
    "タブの解消を発令する", "このタブの解消を発令する", "タブの解消を発令した", "このタブの解消を発令した",
    "タブの解消を命じる", "このタブの解消を命じる", "タブの解消を命じた", "このタブの解消を命じた",
    "タブの解消を命ずる", "このタブの解消を命ずる", "タブの解消を通達する", "このタブの解消を通達する",
    "タブの解消を通告する", "このタブの解消を通告する", "タブの解消を告示する", "このタブの解消を告示する",
    "タブの解消を公示する", "このタブの解消を公示する", "タブの解消を裁定する", "このタブの解消を裁定する",
    "タブの解消を裁可する", "このタブの解消を裁可する", "タブの解消を裁断する", "このタブの解消を裁断する",
    "タブの解消を下す", "このタブの解消を下す", "タブの解消を下した", "このタブの解消を下した",
    "タブの解消を執行する", "このタブの解消を執行する", "タブの解消を執行した", "このタブの解消を執行した",
    "タブの解消を決する", "このタブの解消を決する", "タブの解消を決定する", "このタブの解消を決定する",
    "タブの解消を決定した", "このタブの解消を決定した", "タブの解消を採択する", "このタブの解消を採択する",
    "タブの解消を議決する", "このタブの解消を議決する", "タブの解消を可決する", "このタブの解消を可決する",
    "タブの解消を決裁する", "このタブの解消を決裁する", "タブの解消を判決する", "このタブの解消を判決する",
    "タブの解消を申し渡す", "このタブの解消を申し渡す", "タブの解消を申し付ける", "このタブの解消を申し付ける",
    "タブの解消を申し付けた", "このタブの解消を申し付けた", "タブの取消を言い渡す", "このタブの取消を言い渡す",
    "タブの取消を言い渡した", "このタブの取消を言い渡した", "タブの取消を宣告する", "このタブの取消を宣告する",
    "タブの取消を宣告した", "このタブの取消を宣告した", "タブの取消を布告する", "このタブの取消を布告する",
    "タブの取消を公布する", "このタブの取消を公布する", "タブの取消を発令する", "このタブの取消を発令する",
    "タブの取消を発令した", "このタブの取消を発令した", "タブの取消を命じる", "このタブの取消を命じる",
    "タブの取消を命じた", "このタブの取消を命じた", "タブの取消を命ずる", "このタブの取消を命ずる",
    "タブの取消を通達する", "このタブの取消を通達する", "タブの取消を通告する", "このタブの取消を通告する",
    "タブの取消を告示する", "このタブの取消を告示する", "タブの取消を公示する", "このタブの取消を公示する",
    "タブの取消を裁定する", "このタブの取消を裁定する", "タブの取消を裁可する", "このタブの取消を裁可する",
    "タブの取消を裁断する", "このタブの取消を裁断する", "タブの取消を下す", "このタブの取消を下す",
    "タブの取消を下した", "このタブの取消を下した", "タブの取消を執行する", "このタブの取消を執行する",
    "タブの取消を執行した", "このタブの取消を執行した", "タブの取消を決する", "このタブの取消を決する",
    "タブの取消を決定する", "このタブの取消を決定する", "タブの取消を決定した", "このタブの取消を決定した",
    "タブの取消を採択する", "このタブの取消を採択する", "タブの取消を議決する", "このタブの取消を議決する",
    "タブの取消を可決する", "このタブの取消を可決する", "タブの取消を決裁する", "このタブの取消を決裁する",
    "タブの取消を判決する", "このタブの取消を判決する", "タブの取消を申し渡す", "このタブの取消を申し渡す",
    "タブの取消を申し付ける", "このタブの取消を申し付ける", "タブの取消を申し付けた", "このタブの取消を申し付けた",
    "タブの撤廃を言い渡す", "このタブの撤廃を言い渡す", "タブの撤廃を言い渡した", "このタブの撤廃を言い渡した",
    "タブの撤廃を宣告する", "このタブの撤廃を宣告する", "タブの撤廃を宣告した", "このタブの撤廃を宣告した",
    "タブの撤廃を布告する", "このタブの撤廃を布告する", "タブの撤廃を公布する", "このタブの撤廃を公布する",
    "タブの撤廃を発令する", "このタブの撤廃を発令する", "タブの撤廃を発令した", "このタブの撤廃を発令した",
    "タブの撤廃を命じる", "このタブの撤廃を命じる", "タブの撤廃を命じた", "このタブの撤廃を命じた",
    "タブの撤廃を命ずる", "このタブの撤廃を命ずる", "タブの撤廃を通達する", "このタブの撤廃を通達する",
    "タブの撤廃を通告する", "このタブの撤廃を通告する", "タブの撤廃を告示する", "このタブの撤廃を告示する",
    "タブの撤廃を公示する", "このタブの撤廃を公示する", "タブの撤廃を裁定する", "このタブの撤廃を裁定する",
    "タブの撤廃を裁可する", "このタブの撤廃を裁可する", "タブの撤廃を裁断する", "このタブの撤廃を裁断する",
    "タブの撤廃を下す", "このタブの撤廃を下す", "タブの撤廃を下した", "このタブの撤廃を下した",
    "タブの撤廃を執行する", "このタブの撤廃を執行する", "タブの撤廃を執行した", "このタブの撤廃を執行した",
    "タブの撤廃を決する", "このタブの撤廃を決する", "タブの撤廃を決定する", "このタブの撤廃を決定する",
    "タブの撤廃を決定した", "このタブの撤廃を決定した", "タブの撤廃を採択する", "このタブの撤廃を採択する",
    "タブの撤廃を議決する", "このタブの撤廃を議決する", "タブの撤廃を可決する", "このタブの撤廃を可決する",
    "タブの撤廃を決裁する", "このタブの撤廃を決裁する", "タブの撤廃を判決する", "このタブの撤廃を判決する",
    "タブの撤廃を申し渡す", "このタブの撤廃を申し渡す", "タブの撤廃を申し付ける", "このタブの撤廃を申し付ける",
    "タブの撤廃を申し付けた", "このタブの撤廃を申し付けた", "タブの撤去を言い渡す", "このタブの撤去を言い渡す",
    "タブの撤去を言い渡した", "このタブの撤去を言い渡した", "タブの撤去を宣告する", "このタブの撤去を宣告する",
    "タブの撤去を宣告した", "このタブの撤去を宣告した", "タブの撤去を布告する", "このタブの撤去を布告する",
    "タブの撤去を公布する", "このタブの撤去を公布する", "タブの撤去を発令する", "このタブの撤去を発令する",
    "タブの撤去を発令した", "このタブの撤去を発令した", "タブの撤去を命じる", "このタブの撤去を命じる",
    "タブの撤去を命じた", "このタブの撤去を命じた", "タブの撤去を命ずる", "このタブの撤去を命ずる",
    "タブの撤去を通達する", "このタブの撤去を通達する", "タブの撤去を通告する", "このタブの撤去を通告する",
    "タブの撤去を告示する", "このタブの撤去を告示する", "タブの撤去を公示する", "このタブの撤去を公示する",
    "タブの撤去を裁定する", "このタブの撤去を裁定する", "タブの撤去を裁可する", "このタブの撤去を裁可する",
    "タブの撤去を裁断する", "このタブの撤去を裁断する", "タブの撤去を下す", "このタブの撤去を下す",
    "タブの撤去を下した", "このタブの撤去を下した", "タブの撤去を執行する", "このタブの撤去を執行する",
    "タブの撤去を執行した", "このタブの撤去を執行した", "タブの撤去を決する", "このタブの撤去を決する",
    "タブの撤去を決定する", "このタブの撤去を決定する", "タブの撤去を決定した", "このタブの撤去を決定した",
    "タブの撤去を採択する", "このタブの撤去を採択する", "タブの撤去を議決する", "このタブの撤去を議決する",
    "タブの撤去を可決する", "このタブの撤去を可決する", "タブの撤去を決裁する", "このタブの撤去を決裁する",
    "タブの撤去を判決する", "このタブの撤去を判決する", "タブの撤去を申し渡す", "このタブの撤去を申し渡す",
    "タブの撤去を申し付ける", "このタブの撤去を申し付ける", "タブの撤去を申し付けた", "このタブの撤去を申し付けた",
    "タブの排除を言い渡す", "このタブの排除を言い渡す", "タブの排除を言い渡した", "このタブの排除を言い渡した",
    "タブの排除を宣告する", "このタブの排除を宣告する", "タブの排除を宣告した", "このタブの排除を宣告した",
    "タブの排除を布告する", "このタブの排除を布告する", "タブの排除を公布する", "このタブの排除を公布する",
    "タブの排除を発令する", "このタブの排除を発令する", "タブの排除を発令した", "このタブの排除を発令した",
    "タブの排除を命じる", "このタブの排除を命じる", "タブの排除を命じた", "このタブの排除を命じた",
    "タブの排除を命ずる", "このタブの排除を命ずる", "タブの排除を通達する", "このタブの排除を通達する",
    "タブの排除を通告する", "このタブの排除を通告する", "タブの排除を告示する", "このタブの排除を告示する",
    "タブの排除を公示する", "このタブの排除を公示する", "タブの排除を裁定する", "このタブの排除を裁定する",
    "タブの排除を裁可する", "このタブの排除を裁可する", "タブの排除を裁断する", "このタブの排除を裁断する",
    "タブの排除を下す", "このタブの排除を下す", "タブの排除を下した", "このタブの排除を下した",
    "タブの排除を執行する", "このタブの排除を執行する", "タブの排除を執行した", "このタブの排除を執行した",
    "タブの排除を決する", "このタブの排除を決する", "タブの排除を決定する", "このタブの排除を決定する",
    "タブの排除を決定した", "このタブの排除を決定した", "タブの排除を採択する", "このタブの排除を採択する",
    "タブの排除を議決する", "このタブの排除を議決する", "タブの排除を可決する", "このタブの排除を可決する",
    "タブの排除を決裁する", "このタブの排除を決裁する", "タブの排除を判決する", "このタブの排除を判決する",
    "タブの排除を申し渡す", "このタブの排除を申し渡す", "タブの排除を申し付ける", "このタブの排除を申し付ける",
    "タブの排除を申し付けた", "このタブの排除を申し付けた", "タブの放逐を言い渡す", "このタブの放逐を言い渡す",
    "タブの放逐を言い渡した", "このタブの放逐を言い渡した", "タブの放逐を宣告する", "このタブの放逐を宣告する",
    "タブの放逐を宣告した", "このタブの放逐を宣告した", "タブの放逐を布告する", "このタブの放逐を布告する",
    "タブの放逐を公布する", "このタブの放逐を公布する", "タブの放逐を発令する", "このタブの放逐を発令する",
    "タブの放逐を発令した", "このタブの放逐を発令した", "タブの放逐を命じる", "このタブの放逐を命じる",
    "タブの放逐を命じた", "このタブの放逐を命じた", "タブの放逐を命ずる", "このタブの放逐を命ずる",
    "タブの放逐を通達する", "このタブの放逐を通達する", "タブの放逐を通告する", "このタブの放逐を通告する",
    "タブの放逐を告示する", "このタブの放逐を告示する", "タブの放逐を公示する", "このタブの放逐を公示する",
    "タブの放逐を裁定する", "このタブの放逐を裁定する", "タブの放逐を裁可する", "このタブの放逐を裁可する",
    "タブの放逐を裁断する", "このタブの放逐を裁断する", "タブの放逐を下す", "このタブの放逐を下す",
    "タブの放逐を下した", "このタブの放逐を下した", "タブの放逐を執行する", "このタブの放逐を執行する",
    "タブの放逐を執行した", "このタブの放逐を執行した", "タブの放逐を決する", "このタブの放逐を決する",
    "タブの放逐を決定する", "このタブの放逐を決定する", "タブの放逐を決定した", "このタブの放逐を決定した",
    "タブの放逐を採択する", "このタブの放逐を採択する", "タブの放逐を議決する", "このタブの放逐を議決する",
    "タブの放逐を可決する", "このタブの放逐を可決する", "タブの放逐を決裁する", "このタブの放逐を決裁する",
    "タブの放逐を判決する", "このタブの放逐を判決する", "タブの放逐を申し渡す", "このタブの放逐を申し渡す",
    "タブの放逐を申し付ける", "このタブの放逐を申し付ける", "タブの放逐を申し付けた", "このタブの放逐を申し付けた",
    "タブの追放を言い渡す", "このタブの追放を言い渡す", "タブの追放を言い渡した", "このタブの追放を言い渡した",
    "タブの追放を宣告する", "このタブの追放を宣告する", "タブの追放を宣告した", "このタブの追放を宣告した",
    "タブの追放を布告する", "このタブの追放を布告する", "タブの追放を公布する", "このタブの追放を公布する",
    "タブの追放を発令する", "このタブの追放を発令する", "タブの追放を発令した", "このタブの追放を発令した",
    "タブの追放を命じる", "このタブの追放を命じる", "タブの追放を命じた", "このタブの追放を命じた",
    "タブの追放を命ずる", "このタブの追放を命ずる", "タブの追放を通達する", "このタブの追放を通達する",
    "タブの追放を通告する", "このタブの追放を通告する", "タブの追放を告示する", "このタブの追放を告示する",
    "タブの追放を公示する", "このタブの追放を公示する", "タブの追放を裁定する", "このタブの追放を裁定する",
    "タブの追放を裁可する", "このタブの追放を裁可する", "タブの追放を裁断する", "このタブの追放を裁断する",
    "タブの追放を下す", "このタブの追放を下す", "タブの追放を下した", "このタブの追放を下した",
    "タブの追放を執行する", "このタブの追放を執行する", "タブの追放を執行した", "このタブの追放を執行した",
    "タブの追放を決する", "このタブの追放を決する", "タブの追放を決定する", "このタブの追放を決定する",
    "タブの追放を決定した", "このタブの追放を決定した", "タブの追放を採択する", "このタブの追放を採択する",
    "タブの追放を議決する", "このタブの追放を議決する", "タブの追放を可決する", "このタブの追放を可決する",
    "タブの追放を決裁する", "このタブの追放を決裁する", "タブの追放を判決する", "このタブの追放を判決する",
    "タブの追放を申し渡す", "このタブの追放を申し渡す", "タブの追放を申し付ける", "このタブの追放を申し付ける",
    "タブの追放を申し付けた", "このタブの追放を申し付けた", "タブの抹殺を言い渡す", "このタブの抹殺を言い渡す",
    "タブの抹殺を言い渡した", "このタブの抹殺を言い渡した", "タブの抹殺を宣告する", "このタブの抹殺を宣告する",
    "タブの抹殺を宣告した", "このタブの抹殺を宣告した", "タブの抹殺を布告する", "このタブの抹殺を布告する",
    "タブの抹殺を公布する", "このタブの抹殺を公布する", "タブの抹殺を発令する", "このタブの抹殺を発令する",
    "タブの抹殺を発令した", "このタブの抹殺を発令した", "タブの抹殺を命じる", "このタブの抹殺を命じる",
    "タブの抹殺を命じた", "このタブの抹殺を命じた", "タブの抹殺を命ずる", "このタブの抹殺を命ずる",
    "タブの抹殺を通達する", "このタブの抹殺を通達する", "タブの抹殺を通告する", "このタブの抹殺を通告する",
    "タブの抹殺を告示する", "このタブの抹殺を告示する", "タブの抹殺を公示する", "このタブの抹殺を公示する",
    "タブの抹殺を裁定する", "このタブの抹殺を裁定する", "タブの抹殺を裁可する", "このタブの抹殺を裁可する",
    "タブの抹殺を裁断する", "このタブの抹殺を裁断する", "タブの抹殺を下す", "このタブの抹殺を下す",
    "タブの抹殺を下した", "このタブの抹殺を下した", "タブの抹殺を執行する", "このタブの抹殺を執行する",
    "タブの抹殺を執行した", "このタブの抹殺を執行した", "タブの抹殺を決する", "このタブの抹殺を決する",
    "タブの抹殺を決定する", "このタブの抹殺を決定する", "タブの抹殺を決定した", "このタブの抹殺を決定した",
    "タブの抹殺を採択する", "このタブの抹殺を採択する", "タブの抹殺を議決する", "このタブの抹殺を議決する",
    "タブの抹殺を可決する", "このタブの抹殺を可決する", "タブの抹殺を決裁する", "このタブの抹殺を決裁する",
    "タブの抹殺を判決する", "このタブの抹殺を判決する", "タブの抹殺を申し渡す", "このタブの抹殺を申し渡す",
    "タブの抹殺を申し付ける", "このタブの抹殺を申し付ける", "タブの抹殺を申し付けた", "このタブの抹殺を申し付けた",
    "タブの殲滅を言い渡す", "このタブの殲滅を言い渡す", "タブの殲滅を言い渡した", "このタブの殲滅を言い渡した",
    "タブの殲滅を宣告する", "このタブの殲滅を宣告する", "タブの殲滅を宣告した", "このタブの殲滅を宣告した",
    "タブの殲滅を布告する", "このタブの殲滅を布告する", "タブの殲滅を公布する", "このタブの殲滅を公布する",
    "タブの殲滅を発令する", "このタブの殲滅を発令する", "タブの殲滅を発令した", "このタブの殲滅を発令した",
    "タブの殲滅を命じる", "このタブの殲滅を命じる", "タブの殲滅を命じた", "このタブの殲滅を命じた",
    "タブの殲滅を命ずる", "このタブの殲滅を命ずる", "タブの殲滅を通達する", "このタブの殲滅を通達する",
    "タブの殲滅を通告する", "このタブの殲滅を通告する", "タブの殲滅を告示する", "このタブの殲滅を告示する",
    "タブの殲滅を公示する", "このタブの殲滅を公示する", "タブの殲滅を裁定する", "このタブの殲滅を裁定する",
    "タブの殲滅を裁可する", "このタブの殲滅を裁可する", "タブの殲滅を裁断する", "このタブの殲滅を裁断する",
    "タブの殲滅を下す", "このタブの殲滅を下す", "タブの殲滅を下した", "このタブの殲滅を下した",
    "タブの殲滅を執行する", "このタブの殲滅を執行する", "タブの殲滅を執行した", "このタブの殲滅を執行した",
    "タブの殲滅を決する", "このタブの殲滅を決する", "タブの殲滅を決定する", "このタブの殲滅を決定する",
    "タブの殲滅を決定した", "このタブの殲滅を決定した", "タブの殲滅を採択する", "このタブの殲滅を採択する",
    "タブの殲滅を議決する", "このタブの殲滅を議決する", "タブの殲滅を可決する", "このタブの殲滅を可決する",
    "タブの殲滅を決裁する", "このタブの殲滅を決裁する", "タブの殲滅を判決する", "このタブの殲滅を判決する",
    "タブの殲滅を申し渡す", "このタブの殲滅を申し渡す", "タブの殲滅を申し付ける", "このタブの殲滅を申し付ける",
    "タブの殲滅を申し付けた", "このタブの殲滅を申し付けた", "タブの根絶を言い渡す", "このタブの根絶を言い渡す",
    "タブの根絶を言い渡した", "このタブの根絶を言い渡した", "タブの根絶を宣告する", "このタブの根絶を宣告する",
    "タブの根絶を宣告した", "このタブの根絶を宣告した", "タブの根絶を布告する", "このタブの根絶を布告する",
    "タブの根絶を公布する", "このタブの根絶を公布する", "タブの根絶を発令する", "このタブの根絶を発令する",
    "タブの根絶を発令した", "このタブの根絶を発令した", "タブの根絶を命じる", "このタブの根絶を命じる",
    "タブの根絶を命じた", "このタブの根絶を命じた", "タブの根絶を命ずる", "このタブの根絶を命ずる",
    "タブの根絶を通達する", "このタブの根絶を通達する", "タブの根絶を通告する", "このタブの根絶を通告する",
    "タブの根絶を告示する", "このタブの根絶を告示する", "タブの根絶を公示する", "このタブの根絶を公示する",
    "タブの根絶を裁定する", "このタブの根絶を裁定する", "タブの根絶を裁可する", "このタブの根絶を裁可する",
    "タブの根絶を裁断する", "このタブの根絶を裁断する", "タブの根絶を下す", "このタブの根絶を下す",
    "タブの根絶を下した", "このタブの根絶を下した", "タブの根絶を執行する", "このタブの根絶を執行する",
    "タブの根絶を執行した", "このタブの根絶を執行した", "タブの根絶を決する", "このタブの根絶を決する",
    "タブの根絶を決定する", "このタブの根絶を決定する", "タブの根絶を決定した", "このタブの根絶を決定した",
    "タブの根絶を採択する", "このタブの根絶を採択する", "タブの根絶を議決する", "このタブの根絶を議決する",
    "タブの根絶を可決する", "このタブの根絶を可決する", "タブの根絶を決裁する", "このタブの根絶を決裁する",
    "タブの根絶を判決する", "このタブの根絶を判決する", "タブの根絶を申し渡す", "このタブの根絶を申し渡す",
    "タブの根絶を申し付ける", "このタブの根絶を申し付ける", "タブの根絶を申し付けた", "このタブの根絶を申し付けた",
    "タブの絶滅を言い渡す", "このタブの絶滅を言い渡す", "タブの絶滅を言い渡した", "このタブの絶滅を言い渡した",
    "タブの絶滅を宣告する", "このタブの絶滅を宣告する", "タブの絶滅を宣告した", "このタブの絶滅を宣告した",
    "タブの絶滅を布告する", "このタブの絶滅を布告する", "タブの絶滅を公布する", "このタブの絶滅を公布する",
    "タブの絶滅を発令する", "このタブの絶滅を発令する", "タブの絶滅を発令した", "このタブの絶滅を発令した",
    "タブの絶滅を命じる", "このタブの絶滅を命じる", "タブの絶滅を命じた", "このタブの絶滅を命じた",
    "タブの絶滅を命ずる", "このタブの絶滅を命ずる", "タブの絶滅を通達する", "このタブの絶滅を通達する",
    "タブの絶滅を通告する", "このタブの絶滅を通告する", "タブの絶滅を告示する", "このタブの絶滅を告示する",
    "タブの絶滅を公示する", "このタブの絶滅を公示する", "タブの絶滅を裁定する", "このタブの絶滅を裁定する",
    "タブの絶滅を裁可する", "このタブの絶滅を裁可する", "タブの絶滅を裁断する", "このタブの絶滅を裁断する",
    "タブの絶滅を下す", "このタブの絶滅を下す", "タブの絶滅を下した", "このタブの絶滅を下した",
    "タブの絶滅を執行する", "このタブの絶滅を執行する", "タブの絶滅を執行した", "このタブの絶滅を執行した",
    "タブの絶滅を決する", "このタブの絶滅を決する", "タブの絶滅を決定する", "このタブの絶滅を決定する",
    "タブの絶滅を決定した", "このタブの絶滅を決定した", "タブの絶滅を採択する", "このタブの絶滅を採択する",
    "タブの絶滅を議決する", "このタブの絶滅を議決する", "タブの絶滅を可決する", "このタブの絶滅を可決する",
    "タブの絶滅を決裁する", "このタブの絶滅を決裁する", "タブの絶滅を判決する", "このタブの絶滅を判決する",
    "タブの絶滅を申し渡す", "このタブの絶滅を申し渡す", "タブの絶滅を申し付ける", "このタブの絶滅を申し付ける",
    "タブの絶滅を申し付けた", "このタブの絶滅を申し付けた", "タブの壊滅を言い渡す", "このタブの壊滅を言い渡す",
    "タブの壊滅を言い渡した", "このタブの壊滅を言い渡した", "タブの壊滅を宣告する", "このタブの壊滅を宣告する",
    "タブの壊滅を宣告した", "このタブの壊滅を宣告した", "タブの壊滅を布告する", "このタブの壊滅を布告する",
    "タブの壊滅を公布する", "このタブの壊滅を公布する", "タブの壊滅を発令する", "このタブの壊滅を発令する",
    "タブの壊滅を発令した", "このタブの壊滅を発令した", "タブの壊滅を命じる", "このタブの壊滅を命じる",
    "タブの壊滅を命じた", "このタブの壊滅を命じた", "タブの壊滅を命ずる", "このタブの壊滅を命ずる",
    "タブの壊滅を通達する", "このタブの壊滅を通達する", "タブの壊滅を通告する", "このタブの壊滅を通告する",
    "タブの壊滅を告示する", "このタブの壊滅を告示する", "タブの壊滅を公示する", "このタブの壊滅を公示する",
    "タブの壊滅を裁定する", "このタブの壊滅を裁定する", "タブの壊滅を裁可する", "このタブの壊滅を裁可する",
    "タブの壊滅を裁断する", "このタブの壊滅を裁断する", "タブの壊滅を下す", "このタブの壊滅を下す",
    "タブの壊滅を下した", "このタブの壊滅を下した", "タブの壊滅を執行する", "このタブの壊滅を執行する",
    "タブの壊滅を執行した", "このタブの壊滅を執行した", "タブの壊滅を決する", "このタブの壊滅を決する",
    "タブの壊滅を決定する", "このタブの壊滅を決定する", "タブの壊滅を決定した", "このタブの壊滅を決定した",
    "タブの壊滅を採択する", "このタブの壊滅を採択する", "タブの壊滅を議決する", "このタブの壊滅を議決する",
    "タブの壊滅を可決する", "このタブの壊滅を可決する", "タブの壊滅を決裁する", "このタブの壊滅を決裁する",
    "タブの壊滅を判決する", "このタブの壊滅を判決する", "タブの壊滅を申し渡す", "このタブの壊滅を申し渡す",
    "タブの壊滅を申し付ける", "このタブの壊滅を申し付ける", "タブの壊滅を申し付けた", "このタブの壊滅を申し付けた",
    "タブの消滅を言い渡す", "このタブの消滅を言い渡す", "タブの消滅を言い渡した", "このタブの消滅を言い渡した",
    "タブの消滅を宣告する", "このタブの消滅を宣告する", "タブの消滅を宣告した", "このタブの消滅を宣告した",
    "タブの消滅を布告する", "このタブの消滅を布告する", "タブの消滅を公布する", "このタブの消滅を公布する",
    "タブの消滅を発令する", "このタブの消滅を発令する", "タブの消滅を発令した", "このタブの消滅を発令した",
    "タブの消滅を命じる", "このタブの消滅を命じる", "タブの消滅を命じた", "このタブの消滅を命じた",
    "タブの消滅を命ずる", "このタブの消滅を命ずる", "タブの消滅を通達する", "このタブの消滅を通達する",
    "タブの消滅を通告する", "このタブの消滅を通告する", "タブの消滅を告示する", "このタブの消滅を告示する",
    "タブの消滅を公示する", "このタブの消滅を公示する", "タブの消滅を裁定する", "このタブの消滅を裁定する",
    "タブの消滅を裁可する", "このタブの消滅を裁可する", "タブの消滅を裁断する", "このタブの消滅を裁断する",
    "タブの消滅を下す", "このタブの消滅を下す", "タブの消滅を下した", "このタブの消滅を下した",
    "タブの消滅を執行する", "このタブの消滅を執行する", "タブの消滅を執行した", "このタブの消滅を執行した",
    "タブの消滅を決する", "このタブの消滅を決する", "タブの消滅を決定する", "このタブの消滅を決定する",
    "タブの消滅を決定した", "このタブの消滅を決定した", "タブの消滅を採択する", "このタブの消滅を採択する",
    "タブの消滅を議決する", "このタブの消滅を議決する", "タブの消滅を可決する", "このタブの消滅を可決する",
    "タブの消滅を決裁する", "このタブの消滅を決裁する", "タブの消滅を判決する", "このタブの消滅を判決する",
    "タブの消滅を申し渡す", "このタブの消滅を申し渡す", "タブの消滅を申し付ける", "このタブの消滅を申し付ける",
    "タブの消滅を申し付けた", "このタブの消滅を申し付けた", "タブの処分を言い渡す", "このタブの処分を言い渡す",
    "タブの処分を言い渡した", "このタブの処分を言い渡した", "タブの処分を宣告する", "このタブの処分を宣告する",
    "タブの処分を宣告した", "このタブの処分を宣告した", "タブの処分を布告する", "このタブの処分を布告する",
    "タブの処分を公布する", "このタブの処分を公布する", "タブの処分を発令する", "このタブの処分を発令する",
    "タブの処分を発令した", "このタブの処分を発令した", "タブの処分を命じる", "このタブの処分を命じる",
    "タブの処分を命じた", "このタブの処分を命じた", "タブの処分を命ずる", "このタブの処分を命ずる",
    "タブの処分を通達する", "このタブの処分を通達する", "タブの処分を通告する", "このタブの処分を通告する",
    "タブの処分を告示する", "このタブの処分を告示する", "タブの処分を公示する", "このタブの処分を公示する",
    "タブの処分を裁定する", "このタブの処分を裁定する", "タブの処分を裁可する", "このタブの処分を裁可する",
    "タブの処分を裁断する", "このタブの処分を裁断する", "タブの処分を下す", "このタブの処分を下す",
    "タブの処分を下した", "このタブの処分を下した", "タブの処分を執行する", "このタブの処分を執行する",
    "タブの処分を執行した", "このタブの処分を執行した", "タブの処分を決する", "このタブの処分を決する",
    "タブの処分を決定する", "このタブの処分を決定する", "タブの処分を決定した", "このタブの処分を決定した",
    "タブの処分を採択する", "このタブの処分を採択する", "タブの処分を議決する", "このタブの処分を議決する",
    "タブの処分を可決する", "このタブの処分を可決する", "タブの処分を決裁する", "このタブの処分を決裁する",
    "タブの処分を判決する", "このタブの処分を判決する", "タブの処分を申し渡す", "このタブの処分を申し渡す",
    "タブの処分を申し付ける", "このタブの処分を申し付ける", "タブの処分を申し付けた", "このタブの処分を申し付けた",
    "タブの処断を言い渡す", "このタブの処断を言い渡す", "タブの処断を言い渡した", "このタブの処断を言い渡した",
    "タブの処断を宣告する", "このタブの処断を宣告する", "タブの処断を宣告した", "このタブの処断を宣告した",
    "タブの処断を布告する", "このタブの処断を布告する", "タブの処断を公布する", "このタブの処断を公布する",
    "タブの処断を発令する", "このタブの処断を発令する", "タブの処断を発令した", "このタブの処断を発令した",
    "タブの処断を命じる", "このタブの処断を命じる", "タブの処断を命じた", "このタブの処断を命じた",
    "タブの処断を命ずる", "このタブの処断を命ずる", "タブの処断を通達する", "このタブの処断を通達する",
    "タブの処断を通告する", "このタブの処断を通告する", "タブの処断を告示する", "このタブの処断を告示する",
    "タブの処断を公示する", "このタブの処断を公示する", "タブの処断を裁定する", "このタブの処断を裁定する",
    "タブの処断を裁可する", "このタブの処断を裁可する", "タブの処断を裁断する", "このタブの処断を裁断する",
    "タブの処断を下す", "このタブの処断を下す", "タブの処断を下した", "このタブの処断を下した",
    "タブの処断を執行する", "このタブの処断を執行する", "タブの処断を執行した", "このタブの処断を執行した",
    "タブの処断を決する", "このタブの処断を決する", "タブの処断を決定する", "このタブの処断を決定する",
    "タブの処断を決定した", "このタブの処断を決定した", "タブの処断を採択する", "このタブの処断を採択する",
    "タブの処断を議決する", "このタブの処断を議決する", "タブの処断を可決する", "このタブの処断を可決する",
    "タブの処断を決裁する", "このタブの処断を決裁する", "タブの処断を判決する", "このタブの処断を判決する",
    "タブの処断を申し渡す", "このタブの処断を申し渡す", "タブの処断を申し付ける", "このタブの処断を申し付ける",
    "タブの処断を申し付けた", "このタブの処断を申し付けた", "タブの処刑を言い渡す", "このタブの処刑を言い渡す",
    "タブの処刑を言い渡した", "このタブの処刑を言い渡した", "タブの処刑を宣告する", "このタブの処刑を宣告する",
    "タブの処刑を宣告した", "このタブの処刑を宣告した", "タブの処刑を布告する", "このタブの処刑を布告する",
    "タブの処刑を公布する", "このタブの処刑を公布する", "タブの処刑を発令する", "このタブの処刑を発令する",
    "タブの処刑を発令した", "このタブの処刑を発令した", "タブの処刑を命じる", "このタブの処刑を命じる",
    "タブの処刑を命じた", "このタブの処刑を命じた", "タブの処刑を命ずる", "このタブの処刑を命ずる",
    "タブの処刑を通達する", "このタブの処刑を通達する", "タブの処刑を通告する", "このタブの処刑を通告する",
    "タブの処刑を告示する", "このタブの処刑を告示する", "タブの処刑を公示する", "このタブの処刑を公示する",
    "タブの処刑を裁定する", "このタブの処刑を裁定する", "タブの処刑を裁可する"])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});

describe('pass CCLXVII: coexistence', () => {
  test.each([
    ["中止すべし", "stop-everything"], ["停止すべし", "stop-everything"], ["終了すべし", "vr-exit"],
  ])('keeps %s on %s', (p, k) => {
    expect(key(mk(), p)).toBe(k);
  });
});
