// pass DCCLXI: igo & go player domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCLXI: igo & go player domain (igo)', () => {
  const closeTab = ['igo player licensed', 'igo master certified', 'igo instructor registered'];
  const closeTabJa = [
    '囲碁',
    '碁',
    '囲碁界',
    '囲碁棋士',
    'プロ棋士',
    '院生',
    '研究生',
    '日本棋院',
    '関西棋院',
    '囲碁協会',
    '国際囲碁連盟',
    '囲碁教室',
    '囲碁部',
    '碁会所',
    '囲碁サロン',
    '碁盤店',
    '碁盤',
    '碁石',
    '碁笥',
    '碁台',
    '碁盤面',
    '碁盤脚',
    '本榧',
    '桂材',
    '新榧',
    '蛤碁石',
    '那智黒',
    '碁石製造',
    '目',
    '眼',
    '眼形',
    '真眼',
    '偽眼',
    '一眼',
    '二眼',
    '両眼',
    '生き',
    '死に',
    '死活',
    '石の死活',
    '攻め合い',
    '着手',
    '手数',
    '手筋',
    '定石',
    '布石',
    '置き碁',
    '互先',
    '先相先',
    '定先',
    'ハンデ',
    'ハンデ碁',
    '置石',
    '置き石',
    '二子',
    '三子',
    '四子',
    '五子',
    '六子',
    '七子',
    '八子',
    '九子',
    '白番',
    '黒番',
    '黒石',
    '白石',
    'コミ',
    'コミ出し',
    '一線',
    '二線',
    '三線',
    '四線',
    '実利',
    '厚み',
    '薄み',
    '地',
    '地合い',
    '模様',
    '大模様',
    '外勢',
    '中央',
    '隅',
    '辺',
    '小目',
    '目外し',
    '高目',
    '星',
    '星位',
    '天元',
    '三々',
    '三三',
    '三々侵入',
    'ツケ',
    'ヒキ',
    'ハネ',
    'オサエ',
    'コスミ',
    'キリ',
    'ノビ',
    'カケ',
    'ワタリ',
    'シボリ',
    'オイオトシ',
    'アテ',
    'アテコミ',
    'オシ',
    'ハサミ',
    'スベリ',
    'トビ',
    'ケイマ',
    'オオゲイマ',
    'コゲイマ',
    'グズミ',
    'ナダレ',
    'シチョウ',
    '征子',
    'セキ',
    'コウ',
    'コウ立て',
    'コウ争',
    '劫争',
    '劫材',
    '半目',
    '一目',
    '愚形',
    '好形',
    '効率',
    '手抜き',
    '早展開',
    '中国流',
    'ミニ中国流',
    '小林流',
    '秀策流',
    '変則布石',
    'ヨセ',
    '大ヨセ',
    '小ヨセ',
    '終局',
    '投了',
    '中押し',
    '中盤勝ち',
    '投了図',
    '整地',
    '整地計算',
    'コウ解消',
    '棋聖',
    '名人',
    '本因坊',
    '王座',
    '碁聖',
    '竜星',
    '阿含桐山杯',
    '囲碁名人戦',
    '本因坊戦',
    '棋聖戦',
    '天元戦',
    '王座戦',
    '碁聖戦',
    '竜星戦',
    '女流棋聖',
    '女流本因坊',
    '女流名人',
    '若鯉戦',
    '日本ルール',
    '中国ルール',
    'セキ止まり',
    '本因坊秀策',
    '本因坊丈和',
    '本因坊道策',
    '本因坊算砂',
    '呉清源',
    '木谷実',
    '藤沢秀行',
    '坂田栄男',
    '大竹英雄',
    '加藤正夫',
    '武宮正樹',
    '小林光一',
    '趙治勲',
    '張栩',
    '井山裕太',
    '羽根直樹',
    '山下敬吾',
    '高尾紳路',
    '依田紀基',
    '結城聡',
    '一力遼',
    '芝野虎丸',
    '上野愛咲美',
    '藤沢里菜',
    '仲邑菫',
    '謝依旻',
    '囲碁書',
    '棋譜',
    '棋譜並べ',
    '大盤解説',
    '解説者',
    '記録係',
    '立会人',
    'アルファ碁',
    '囲碁ai',
    '絶芸',
    '囲碁四天王',
    '座子',
    '打ち掛け',
    '段位認定',
    '囲碁段位',
    '級位者',
    '段位者',
    '高段者',
    '囲碁歴',
    '囲碁齢',
    '囲碁人口',
    '囲碁愛好家',
    '囲碁ファン',
    'ネット囲碁',
    '囲碁対局',
    '対局場',
    '持ち時間',
    '秒読み',
    '早碁',
    '早打ち',
    '実践詰碁',
    '詰碁',
    '詰め碁',
    '詰碁集',
    '次の一手',
    '形勢判断',
    'ヨセ勘定',
    '目数計算',
    '地模様',
    '石打ち',
    '碁形',
    '碁筋',
    '碁理',
    '碁風',
    '碁力',
    '手談',
    '爛柯',
    '妙手',
    '悪手',
    '緩手',
    '疑問手',
    '敗着',
    '長考',
    '封じ手'
  ];
  const negate = [
    'still awaiting the igo license',
    'still awaiting the ko ruling',
    'まだ対局前',
    'まだ投了前',
    'これから着手',
    'まだ場所前'
  ];
  const nullPins = ['about to visit the go hall', 'about to file the game record'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
