// Pass CCLVI: EN distort/grind/erase-out + JA crush/stomp/declare (pass CCLVI)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLVI: close-tab coverage', () => {
  test.each([
    "mangle it", "mutilate it", "mutilate it", "deform it",
    "disfigure it", "deface it", "distort it", "warp it",
    "twist it", "bend it", "contort it", "convulse it",
    "wrench it", "wring it", "crumple it",
    "condense it", "constrict it", "squeeze it", "press it",
    "puree it", "mash it", "squish it",
    "squish it it", "splatter it", "splutter it", "smear it",
    "smudge it", "blur it", "smear out it", "smudge out it",
    "blur out it", "mangle the tab", "mutilate the tab", "deform the tab",
    "disfigure the tab", "deface the tab", "distort the tab", "warp the tab",
    "twist the tab", "bend the tab", "contort the tab", "wrench the tab",
    "wring the tab", "crumple the tab", "squash the tab", "flatten the tab",
    "squeeze the tab", "pulp the tab", "puree the tab", "mash the tab",
    "squish the tab", "splatter the tab", "smear the tab", "smudge the tab",
    "blur the tab", "crumple it up and toss it", "crumple it up and throw it away", "crumple it up and bin it",
    "crumple it like a paper", "crumple it like paper", "crumple it like a paper ball", "ball it up and toss it",
    "ball it up and throw it away", "ball it up and bin it", "scrunch it up", "scrunch the tab up",
    "scrunch it up and toss it", "bunch it up", "bunch the tab up", "fold it up and toss it",
    "fold it up and bin it", "roll it up and smoke it", "roll it up and burn it", "tear it up",
    "tear the tab up", "tear it to bits", "tear the tab to pieces", "tear the tab to shreds",
    "tear the tab to bits", "tear the tab apart", "rip it up", "rip the tab up",
    "rip it to bits", "rip the tab to pieces", "rip the tab to shreds", "rip the tab to bits",
    "rip the tab apart", "rip it in half", "rip it in two", "rip it to ribbons",
    "rip it to strips", "shred it to ribbons", "shred the tab to pieces", "shred the tab to ribbons",
    "put it through the shredder", "run it through the shredder", "feed it through the shredder", "put it in the shredder",
    "drop it in the shredder", "send it through the shredder", "chop the tab up", "chop it to pieces",
    "chop it to bits", "chop the tab to pieces", "chop the tab to bits", "chop it into pieces",
    "chop it into bits", "cut the tab up", "cut it to pieces", "cut it to bits",
    "cut the tab to pieces", "cut the tab to bits", "cut it into pieces", "cut it into bits",
    "cut it into pieces", "slice the tab up", "slice it to pieces", "slice it to bits",
    "slice the tab to pieces", "dice the tab", "dice it into cubes", "mince the tab",
    "grind the tab up", "grind it to powder", "grind it to dust", "grind it to a pulp",
    "grind it to paste", "grind it to nothing", "grind the tab to powder", "grind the tab to dust",
    "grind the tab to nothing", "pulverize the tab", "pulverize it to dust", "pulverize it to powder",
    "pulverize it to nothing", "atomize it completely", "atomize it entirely", "atomize it to nothing",
    "vaporize it completely", "vaporize it entirely", "vaporize it to nothing", "evaporate it completely",
    "evaporate it entirely", "evaporate it to nothing", "desiccate the tab", "desiccate it completely",
    "desiccate it entirely", "dehydrate it", "dehydrate the tab", "dehydrate it completely",
    "dehydrate it entirely", "dry the tab out", "dry it out completely", "dry it out entirely",
    "shrivel it up completely", "wither it away completely", "wilt it away", "embalm the tab",
    "fossilize the tab", "calcify it", "calcify the tab", "carbonize it",
    "carbonize the tab", "carbonize it completely", "char it to a crisp", "char it completely",
    "char it beyond recognition", "burn it beyond recognition", "roast it to a crisp", "roast it completely",
    "scorch it completely", "singed it", "singe it completely", "singed beyond recognition",
    "toast it to a crisp", "toast it completely", "toast it golden", "toast it golden brown",
    "broil the tab", "broil it to a crisp", "grill it to a crisp", "braise the tab",
    "poach the tab", "boil it away", "boil it to nothing", "stew it",
    "stew the tab", "simmer it", "simmer the tab", "simmer it away",
    "simmer it to nothing", "reduce it", "reduce the tab", "reduce it to powder",
    "reduce it to a pulp", "reduce it to a puddle", "reduce it to a smear", "reduce it to a smudge",
    "reduce it to a stain", "reduce it to a spot", "reduce it to debris", "reduce it to molecules",
    "reduce it to elements", "reduce it to its elements", "reduce the tab to powder", "annihilate the tab",
    "annihilate it completely", "annihilate it entirely", "annihilate it utterly", "obliterate it completely",
    "obliterate it entirely", "obliterate it utterly", "obliterate it from existence", "obliterate it from the face of the earth",
    "obliterate it from the earth", "obliterate it from the planet", "obliterate it from reality", "obliterate it from memory",
    "obliterate it from history", "obliterate it from the record", "obliterate it from the books", "obliterate it from the map",
    "wipe it from the face of the earth", "wipe it off the face of the planet", "wipe it from the earth", "wipe it from the planet",
    "wipe it from the books", "wipe it from reality", "wipe it from the world", "wipe it off the world",
    "wipe it from the face of existence", "erase it from the face of the earth", "erase it from the earth", "erase it from the planet",
    "erase it from reality", "erase it from the world", "delete it from existence", "delete it from reality",
    "delete it from the world", "delete it from the universe", "delete it from the cosmos", "delete it from history",
    "delete it from memory", "delete it from the record", "delete it from the books", "delete it from the map",
    "delete it from the face of the earth", "remove it from reality", "remove it from the world", "remove it from the universe",
    "remove it from memory", "remove it from the face of the earth", "exterminate the tab", "exterminate it completely",
    "exterminate it entirely", "exterminate it utterly", "eradicate the tab", "eradicate it completely",
    "eradicate it entirely", "eradicate it utterly", "eradicate it from the earth", "eradicate it from the planet",
    "eradicate it from existence", "eradicate it from the face of the earth", "liquidate it completely", "liquidate it entirely",
    "extinguish it", "extinguish the tab", "extinguish it completely", "extinguish it entirely",
    "extinguish it forever", "extinguish it permanently", "stamp it out completely", "stamp it out entirely",
    "stamp it out forever", "snuff the tab out", "snuff it out completely", "snuff it out forever",
    "blow it out", "blow the tab out", "blow it out completely", "blow it out like a candle",
    "snuff it like a candle", "snuff it out like a candle", "blow it out like a candle", "put it out like a candle",
    "put it out completely", "put it out entirely", "put it out forever", "put it out permanently",
    "put it out for good", "put the tab out of its misery", "put it out of its misery forever", "put it out of its misery permanently",
    "put it down like a dog", "put it down like a rabid dog", "put it down like old yeller", "put it down permanently",
    "euthanise the tab", "euthanize it humanely", "put it out of my misery", "mercy kill the tab",
    "give it a mercy kill", "perform a mercy kill", "perform a mercy kill on it", "潰れろと言ってんだ",
    "潰れるからな", "潰れるのが筋だ", "潰れるのが正解だ", "潰れるということだ",
    "潰れるという決定だ", "潰れるという判断だ", "潰れていいだろ", "潰れるはずだった",
    "潰れると言ったのに", "潰れると言ったろ", "潰れてと頼んだ", "潰れると思うよ",
    "潰れると思うんだ", "潰れると思うけど", "潰れろと思うよ", "潰れろと思うんだ",
    "潰れろと言うんだ", "潰れろというんだ", "潰れろということだ", "潰れろという件だ",
    "潰れろという判断だ", "潰れろという決定だ", "潰れろという結論だ", "潰れろという方針だ",
    "潰れろという意向だ", "潰れろという意志だ", "潰れろという意思だ", "潰れろという腹だ",
    "潰れろという心だ", "潰れろという運びだ", "潰れろという段取りだ", "潰れろという流れだ",
    "潰れろという次第だ", "潰れろという旨だ", "潰れろという模様だ", "潰れろという形だ",
    "潰れろという方向だ", "潰れろという話だ", "潰れろという見解だ", "潰れろという所存だ",
    "潰れろという判決だ", "潰れろという裁定だ", "潰れろという議決だ", "潰れろという採決だ",
    "潰れろという可決だ", "潰れろという命令だ", "潰れろという指令だ", "潰れろという布告だ",
    "潰れろという宣言だ", "潰れろというお達しだ", "潰れろという沙汰だ", "潰れろという由だ",
    "潰れろという動議だ", "潰れろという議案だ", "潰れろという案件だ", "潰れろという命じだ",
    "潰れろという命だ", "潰れろという号令だ", "潰れろという檄だ", "潰れろというお告げだ",
    "潰れろという神託だ", "潰れろという御触れだ", "潰れろという触れだ", "潰れろという決まりだ",
    "潰れろという決定事項だ", "潰れろという確定事項だ", "潰れろという既定路線だ", "潰れろという既定の方針だ",
    "潰れろという既定方針だ", "潰れろという既定の流れだ", "潰れろという既定の運びだ", "踏め",
    "踏んで", "踏むんだ", "踏んでしまえ", "踏んじまえ",
    "踏んじゃえ", "踏んどけ", "踏んどいて", "踏んなよ",
    "踏んだまえ", "踏んやがれ", "踏めや", "踏めって",
    "踏めってば", "踏めと言ってんだ", "踏むべきだ", "踏むつもりだ",
    "踏むわ", "踏むぞ", "踏むぜ", "踏むからな",
    "踏むことにした", "踏むのが筋だ", "踏むのが正解だ", "踏むということだ",
    "踏むという決定だ", "踏むという判断だ", "踏みつぶせ", "踏みつぶして",
    "踏みつぶすんだ", "踏みつぶせよ", "踏みつぶすべきだ", "踏み潰しちゃえ",
    "踏み潰せや", "踏み潰せと言ってんだ", "踏み潰すからな", "踏み潰すのが筋だ",
    "踏み潰すのが正解だ", "踏み潰すということだ", "踏み潰すという決定だ", "踏み潰すという判断だ",
    "踏み荒らせ", "踏み荒らして", "踏み荒らすんだ", "踏み荒らせよ",
    "踏み荒らすべきだ", "踏みにじれ", "踏みにじって", "踏みにじるんだ",
    "踏みにじれよ", "踏みにじるべきだ", "蹴れ", "蹴って",
    "蹴るんだ", "蹴ってしまえ", "蹴っちまえ", "蹴っちゃえ",
    "蹴っとけ", "蹴っといて", "蹴っときな", "蹴んなよ",
    "蹴ったまえ", "蹴んやがれ", "蹴れや", "蹴れって",
    "蹴れってば", "蹴れと言ってんだ", "蹴るべきだ", "蹴るつもりだ",
    "蹴るわ", "蹴るぞ", "蹴るぜ", "蹴るからな",
    "蹴ることにした", "蹴るのが筋だ", "蹴るのが正解だ", "蹴るということだ",
    "蹴るという決定だ", "蹴るという判断だ", "蹴り飛ばせ", "蹴り飛ばして",
    "蹴り飛ばすんだ", "蹴り飛ばせよ", "蹴り飛ばすべきだ", "蹴っ飛ばせ",
    "蹴っ飛ばして", "蹴っ飛ばすんだ", "蹴っ飛ばせよ", "蹴っ飛ばすべきだ",
    "蹴り殺せ", "蹴り殺して", "蹴り殺すんだ", "蹴り殺せよ",
    "蹴り殺すべきだ", "蹴殺せ", "蹴殺して", "蹴殺すんだ",
    "蹴殺せよ", "蹴殺すべきだ", "蹴散らせ", "蹴散らして",
    "蹴散らすんだ", "蹴散らせよ", "蹴散らすべきだ", "蹴り潰せ",
    "蹴り潰して", "蹴り潰すんだ", "蹴り潰せよ", "蹴り潰すべきだ",
    "蹴りまくれ", "蹴りまくって", "蹴りまくるんだ", "蹴りまくれよ",
    "蹴りまくるべきだ", "蹴り落とせ", "蹴り落として", "蹴り落とすんだ",
    "蹴り落とせよ", "蹴り落とすべきだ", "蹴り下ろせ", "蹴り下ろして",
    "蹴り下ろすんだ", "蹴り下ろせよ", "蹴り下ろすべきだ", "蹴り放て",
    "蹴り放って", "蹴り放つんだ", "蹴り放てよ", "蹴り放つべきだ",
    "蹴り返せ", "蹴り返して", "蹴り返すんだ", "蹴り返せよ",
    "蹴り返すべきだ", "蹴り合わせ", "蹴り合わせて", "蹴り合わせるんだ",
    "蹴り合わせよ", "蹴り合わせるべきだ", "終了宣言だ", "終了宣言にしろ",
    "終了を宣言しろ", "終了を宣言して", "終了を言い渡せ", "終了を言い渡して",
    "終了を言い渡すんだ", "終了を言い渡せよ", "終了を言い渡すべきだ", "終了を言い渡すつもりだ",
    "終了を言い渡すわ", "終了を言い渡すぞ", "終了を言い渡すぜ", "終了を言い渡すからな",
    "終了を言い渡せと言ってんだ", "終了を言い渡せと言っているんだ", "終了を言い渡せというんだ", "終了を言い渡せということだ",
    "終了を言い渡せという件だ", "終了を言い渡せという判断だ", "終了を言い渡せという決定だ", "終了を言い渡せという命令だ",
    "終了を言い渡せというお達しだ", "終了を言い渡せという沙汰だ", "終了を言い渡せという旨だ", "終了を言い渡せという意向だ",
    "終了を言い渡せという意志だ", "終了を言い渡せという意思だ", "終了を言い渡せという腹だ", "終了を言い渡せという心だ",
    "終了を言い渡せという運びだ", "終了を言い渡せという段取りだ", "終了を言い渡せという流れだ", "終了を言い渡せという次第だ",
    "終了を言い渡せという模様だ", "終了を言い渡せという形だ", "終了を言い渡せという方向だ", "終了を言い渡せという話だ",
    "終了を言い渡せという見解だ", "終了を言い渡せという所存だ", "終了を言い渡せという判決だ", "終了を言い渡せという裁定だ",
    "終了を言い渡せという議決だ", "終了を言い渡せという採決だ", "終了を言い渡せという可決だ", "終了を言い渡せという指令だ",
    "終了を言い渡せという布告だ", "終了を言い渡せという宣言だ", "終了を言い渡せという由だ", "閉幕宣言だ",
    "閉幕宣言にしろ", "閉幕を宣言しろ", "閉幕を宣言して", "閉幕を言い渡せ",
    "閉幕を言い渡して", "閉幕を言い渡すんだ", "閉幕を言い渡せよ", "閉幕を言い渡すべきだ",
    "閉幕を言い渡すつもりだ", "閉幕を言い渡すわ", "閉幕を言い渡すぞ", "閉幕を言い渡すぜ",
    "閉幕を言い渡すからな", "閉幕を言い渡せと言ってんだ", "閉幕を言い渡せというんだ", "閉幕を言い渡せということだ",
    "閉幕を言い渡せという件だ", "閉幕を言い渡せという判断だ", "閉幕を言い渡せという決定だ", "閉幕を言い渡せという命令だ",
    "閉幕を言い渡せというお達しだ", "閉幕を言い渡せという沙汰だ", "閉幕を言い渡せという旨だ", "閉幕を言い渡せという意向だ",
    "閉幕を言い渡せという意志だ", "閉幕を言い渡せという意思だ", "閉幕を言い渡せという腹だ", "閉幕を言い渡せという心だ",
    "閉幕を言い渡せという運びだ", "閉幕を言い渡せという段取りだ", "閉幕を言い渡せという流れだ", "閉幕を言い渡せという次第だ",
    "閉幕を言い渡せという模様だ", "閉幕を言い渡せという形だ", "閉幕を言い渡せという方向だ", "閉幕を言い渡せという話だ",
    "閉幕を言い渡せという見解だ", "閉幕を言い渡せという所存だ", "閉幕を言い渡せという判決だ", "閉幕を言い渡せという裁定だ",
    "閉幕を言い渡せという議決だ", "閉幕を言い渡せという採決だ", "閉幕を言い渡せという可決だ", "閉幕を言い渡せという指令だ",
    "閉幕を言い渡せという布告だ", "閉幕を言い渡せという宣言だ", "閉幕を言い渡せという由だ", "廃止宣言だ",
    "廃止宣言にしろ", "廃止を宣言しろ", "廃止を宣言して", "廃止を言い渡せ",
    "廃止を言い渡して", "廃止を言い渡すんだ", "廃止を言い渡せよ", "廃止を言い渡すべきだ",
    "廃止を言い渡すつもりだ", "廃止を言い渡すわ", "廃止を言い渡すぞ", "廃止を言い渡すぜ",
    "廃止を言い渡すからな", "廃止を言い渡せと言ってんだ", "廃止を言い渡せというんだ", "廃止を言い渡せということだ",
    "廃止を言い渡せという件だ", "廃止を言い渡せという判断だ", "廃止を言い渡せという決定だ", "廃止を言い渡せという命令だ",
    "廃止を言い渡せというお達しだ", "廃止を言い渡せという沙汰だ", "廃止を言い渡せという旨だ", "廃止を言い渡せという意向だ",
    "廃止を言い渡せという意志だ", "廃止を言い渡せという意思だ", "廃止を言い渡せという腹だ", "廃止を言い渡せという心だ",
    "廃止を言い渡せという運びだ", "廃止を言い渡せという段取りだ", "廃止を言い渡せという流れだ", "廃止を言い渡せという次第だ",
    "廃止を言い渡せという模様だ", "廃止を言い渡せという形だ", "廃止を言い渡せという方向だ", "廃止を言い渡せという話だ",
    "廃止を言い渡せという見解だ", "廃止を言い渡せという所存だ", "廃止を言い渡せという判決だ", "廃止を言い渡せという裁定だ",
    "廃止を言い渡せという議決だ", "廃止を言い渡せという採決だ", "廃止を言い渡せという可決だ", "廃止を言い渡せという指令だ",
    "廃止を言い渡せという布告だ", "廃止を言い渡せという宣言だ", "廃止を言い渡せという由だ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
