import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

const mk = () => {
  const vc = new VoiceCommands({ enabled: true });
  const tm = {
    activeTabId: 't1',
    tabs: [
      { id: 't1', currentTitle: 'A', currentUrl: 'https://a' },
      { id: 't2', currentTitle: 'B', currentUrl: 'https://b' },
      { id: 't3', currentTitle: 'C', currentUrl: 'https://c' },
    ],
    getActiveTab() { return this.tabs.find((t) => t.id === this.activeTabId); },
    closeAllTabs() { return 3; },
    closeTab() {}, pinTab() {}, closeOtherTabs() {},
  };
  vc.connectBrowser({ tabManager: tm, onGoTo: () => {} });
  vc.speak = () => {};
  return vc;
};
const key = (vc, p) => { vc.processCommand(p, 0.9); return vc.lastCommand ? vc.lastCommand.key : null; };

describe('ivory atom sweep — pass CCXLI', () => {
  test.each([
    'stash it away for good', 'stash it permanently',
    'kill -9 it', 'kill -9 the tab', 'sigkill it', 'sigterm it',
    'rm it', 'rm -rf it', 'rm -rf the tab', 'sudo kill it',
    'force quit it', 'force quit the tab', 'end task', 'force stop it',
    'power it off', 'cut the power', 'cut power to it',
    'toggle it off', 'turn off that tab', 'bring it down',
    'take it offline',
    'yank it', 'yank it out', 'rip it out', 'pluck it',
    'pluck it out', 'pluck the tab', 'pull the tab out',
    'rip it out of there', 'pull it up by the roots',
    'sweep it under the rug', 'wash it down the drain',
    'wash my hands of it', 'wash your hands of it',
    'wash it off', 'rinse it off', 'hose it down', 'spray it off',
    'blast it away', 'blow it away', 'blow it off', 'gust it away',
    'whisk it away', 'fan it away', 'clear it away', 'sweep it out',
    'mop it up', 'sponge it off', 'scrub it away', 'flush it out',
    'run it off', 'shoo it away', 'shoo it off', 'chase it away',
    'chase it off', 'drive it away', 'drive it off', 'drive it out',
    'run it off the page', 'run it out of here',
    'show it the door', 'walk it out the door', 'kick it out the door',
    'boot it out the door', 'send it out the door',
    'get it out the door', 'push it out the door',
    'shove it out the door', 'throw it out the door',
    'fling it out the window', 'throw it out the window',
    'out the window with it', 'through the window with it',
    'exit stage left', 'exit it', 'evacuate it', 'vacate it',
    'abdicate it', 'relinquish it', 'surrender it', 'surrender the tab',
    'yield it', 'cede it', 'hand it over', 'hand it off',
    'hand it in', 'turn it in', 'give it up',
    'let it go to pasture', 'retire it to pasture',
    'send it out to pasture',
    'bench it', 'bench the tab', 'sit it out', 'sit the tab out',
    'scratch it from the lineup', 'pull it from the lineup',
    'take it out of the game', 'out of the game with it',
    'strike the tab out', 'strike out the tab',
    'three strikes', 'three strikes for it', 'throw a strike',
    'foul it off', 'foul it out', 'balk it', 'balk the tab',
    'checkmate it', 'checkmate the tab', 'call it game',
    'call it a game', 'its game over', 'game over for it',
    'game over for the tab', 'game over tab', 'end the game',
    'end its game', 'end the game for it', 'buzzer beater',
    'sudden death', 'sudden death for it', 'match point',
    'match point for it', 'tournament over', 'tournament over for it',
    'bracket it', 'bracket the tab', 'eliminate it', 'eliminate the tab',
    'knock it out of the bracket', 'knock it out of the running',
    'out of the running', 'out of contention', 'out of contention for it',
    'eject button', 'hit eject', 'push eject', 'eject that tab',
    'fade it out', 'fade it to black', 'fade it',
    'march it off', 'march it out of here', 'escort it off',
    'escort the tab off', 'walk it off the stage', 'hook it off',
    'hook it off the stage', 'yank it off the stage', 'vaudeville hook',
    'get the hook', 'bow out', 'bow it out', 'take a bow',
    'take its bow', 'exit gracefully', 'make it exit',
    'make it exit stage left', 'applause over', 'applause is over',
    'final curtain', 'final curtain for it', 'curtains on it',
    'canned it', 'trash can it', 'ash can it', 'in the can',
    'put it in the can', 'roll the shutters', 'pull down the shutters',
    'board it shut', 'board it over', 'bolt it shut', 'bolt the tab shut',
    'nail the tab shut', 'seal the tab shut', 'weld the tab shut',
    'cement it shut', 'tape it shut', 'tape the tab shut',
    'wrap it shut', 'tie it shut', 'lock it shut', 'lock it away',
    'lock it up', 'lock the tab away', 'lock it in the vault',
    'vault it', 'vault the tab', 'stow it away', 'stow it',
    'store it away', 'file it away permanently',
    'shove it in a drawer', 'put it in a drawer', 'drawer it',
    'stick it in a drawer', 'cram it in a drawer', 'shelf it',
    'deep shelve it', 'back of the shelf', 'back shelf it',
    'bottom shelf it', 'bottom drawer it', 'trunk it',
    'put it in the trunk', 'trunk the tab', 'box it up for good',
    'crate it', 'crate the tab', 'crate it up', 'ship it out',
    'ship it away', 'ship the tab out', 'freight it', 'freight it out',
    'cargo it', 'cargo it out', 'pack it up and ship it',
    'wrap it and ship it', 'express it out', 'overnight it away',
    'priority mail it out',
    'stamp it out', 'stamp the tab out', 'stamp on it', 'stamp it flat',
    'squash it flat', 'roll over it', 'roll it flat', 'roadkill it',
    'roadkill the tab', 'make it roadkill', 'tire tracks',
    'tire tracks on it', 'run over it', 'run the tab over',
    'drive over it', 'drive over the tab', 'mow it over', 'mow over it',
    'plow it under', 'plow under it', 'till it under', 'till it in',
    'turn it under', 'earth it over', 'cover it in dirt',
    'cover it with dirt', 'pile dirt on it', 'heap dirt on it',
    'shovel dirt on it', 'shovel it under', 'dirt nap for it',
    'put it in a box', 'put the tab in a box', 'box for it',
    'coffin it', 'coffin the tab', 'casket it', 'urn it', 'urn the tab',
    'pine box it', 'six foot hole', 'hole for it', 'dig it a hole',
    'dig a hole for it', 'dig its grave', 'grave it', 'grave the tab',
    'headstone it', 'mark its grave', 'obituary it',
    'write its obituary', 'write the obituary', 'read its obituary',
    'eulogy it', 'give it a eulogy', 'deliver the eulogy',
    'funeral it', 'funeral for it', 'wake for it', 'wake for the tab',
    'hold a wake', 'hold its wake', 'mourn it', 'mourn the tab',
    'grieve it', 'memorialize it', 'memorial for it', 'in memoriam',
    'requiem it', 'sing a requiem', 'dirge it', 'sing a dirge',
    'roll the credits', 'roll credits', 'credits roll', 'end credits',
    'post credits', 'fin for it', 'the end of it', 'the end of the tab',
    'end of the road for it', 'road ends here', 'road ends for it',
    'journey ends', 'journey ends here', 'the journey ends for it',
    'terminal for it', 'terminal tab', 'terminus', 'terminus for it',
    'this is the end', 'this is the end for it',
    'enough is enough for it', 'final page', 'turn the last page',
    'the book is closed', 'the books closed on it', 'chapter closed',
    'chapter closed for it', 'chapter closed on it',
    'close the chapter', 'close that chapter', 'end the chapter',
    'end this chapter', 'chapter end', 'chapter ends',
    'final chapter', 'final chapter for it', 'epilogue',
    'epilogue time', 'write the epilogue', 'story ends',
    'story ends here', 'end of the story', 'end of the story for it',
    'story over', 'the story is over', 'close the story',
    'book closed', 'book closed on it', 'seal the book',
    'clack it shut', 'snap the tab shut', 'snap it closed',
    'snap the tab closed', 'click it closed', 'click the tab closed',
    'click shut', 'snap shut', 'shut tight', 'shut the tab tight',
    'batten it shut', 'batten the tab', 'latch it shut', 'latch the tab',
    'catch it shut', 'clasp it shut', 'clamp it shut',
    'clamp the tab shut', 'clench it shut', 'pinch it shut',
    'pinch the tab shut', 'squeeze it shut', 'crimp it shut',
    'crimp the tab shut', 'crush it shut', 'press it shut',
    'press the tab shut', 'fold it shut', 'fold the tab shut',
    'fold it closed', 'fold the tab closed', 'shut it fully',
    'fully close it', 'fully shut it', 'shut it all the way',
    'all the way shut', 'all the way closed', 'fully closed',
    'shut it totally', 'close it totally', 'shut it entirely',
    'close it wholly', 'shut it wholly', 'shut it outright',
    'close it outright', 'shut it for keeps', 'shut it forever',
    'close it for real', 'shut it for real', 'shut it for reals',
    'close it for reals', 'shut for real',
    'put it away forever', 'put it away entirely',
    'put that tab away', 'put this tab away', 'away with that tab',
    'away with this tab', 'begone tab begone', 'begone foul tab',
    'out of my sight with it', 'out of sight with it',
    'off my screen with it', 'off my display', 'off my monitor',
    'off my headset', 'off my visor', 'out of my visor',
    'out of my headset', 'out of my view', 'out of my view with it',
    'out of view with it', 'out of frame', 'off the frame',
    'out of the frame with it', 'out of the picture',
    'out of the picture with it', 'scram tab scram',
    'scram from my screen', 'get off my screen',
    'off the screen with it', 'take it off the screen',
    'remove it from the screen', 'remove it from view',
    'remove it from sight', 'clear it from view', 'clear it from sight',
    'clear my view', 'clear my view of it', 'clear the screen of it',
    'blank it out', 'blank the tab', 'blank it', 'whitewash it',
    'white it out', 'whiteout it', 'blanket it', 'blanket the tab',
    'cover it up for good', 'conceal it for good',
    'conceal it permanently', 'hide it away for good',
    'hide it permanently', 'hide it forever', 'hide the tab forever',
    'stash the tab away',
    '畳め',
    '葬れ', '葬って', '葬り去れ', '葬り去って', '葬り去るんだ',
    '葬るんだ', '葬るべき', '葬ったほうがいい',
    '葬式だ', '葬式にしろ', 'お葬式だ', 'お葬式にしろ',
    '埋葬しろ', '埋葬だ', '埋葬せよ', '埋葬すべき',
    '埋めろ', '埋めて', '埋めちまえ', '埋めちゃえ', '埋めちゃって',
    '土に埋めろ', '地中に埋めろ', '埋め立てろ',
    '沈めろ', '沈めて', '沈黙させろ', '沈黙だ', '水没させろ',
    '海に沈めろ', '海に沈めて', '川に流せ', '流せ', '流して',
    '流しちまえ',
    '供養しろ', '供養して', '供養だ', '供養してやれ', '供養してやって',
    '供養すべき', '成仏させろ', '成仏させて', '成仏だ', '成仏しろ',
    'あの世に送れ', 'あの世へ送れ', 'あの世行きだ', 'あの世に送って',
    '彼岸に送れ', '三途の川を渡せ', '棺に入れろ', '棺桶に入れろ',
    '棺桶だ', '墓に入れろ', '墓標だ', '墓標を立てろ', '墓石だ',
    'お墓に入れろ', '墓に葬れ', '火葬しろ', '火葬だ', '火葬にしろ',
    '荼毘に付せ', '荼毘に付すんだ', '灰にしろ', '灰だ',
    '灰燼に帰せ', '灰に帰せ',
    '消え去れ', '消え失せろ', '消えてなくなれ', '消えうせろ',
    '消え去るんだ',
    '失せろ', '失せろよ', '失せな', '失せなさい',
    '出てけ', '出ていけ', '出て行け', '出ていくんだ',
    '出ていってくれ',
    '退け', '退いて', '退きな', '退きなさい', '退いてくれ',
    '退けよ', '退きやがれ',
    '撤収しろ', '撤収だ', '撤収せよ', '撤収すべき', '撤収させろ',
    '撤去しろ', '撤去だ', '撤去せよ', '撤廃しろ', '撤廃だ',
    '廃止しろ', '廃止だ', '廃止せよ', '廃止させろ', '廃止すべき',
    '廃止すべきだ', '廃棄しろ', '廃棄だ', '廃棄せよ', '廃棄すべき',
    '破棄しろ', '破棄だ', '破棄せよ', '破棄して', '破棄すべき',
    '破棄すべきだ', '消去しろ', '消去だ', '消去せよ', '消去すべき',
    '削除しろ', '削除だ', '削除せよ', '削除すべき', '削除すべきだ',
    '抹消しろ', '抹消だ', '抹消せよ', '抹消すべき',
    '抹殺しろ', '抹殺だ', '抹殺せよ', '抹殺すべき',
    '殲滅しろ', '殲滅だ', '殲滅せよ', '駆除しろ', '駆除だ',
    '駆逐しろ', '駆逐だ', '駆逐せよ', '一掃しろ', '一掃だ',
    '一掃せよ', '掃討しろ', '掃討だ', '掃討せよ', '根絶しろ',
    '根絶だ', '根絶せよ', '根絶やし', '根絶やしにしろ',
    '絶滅させろ', '絶滅だ', '絶滅させるんだ',
    '根こそぎ消せ', '根こそぎにしろ', '残らず消せ', '残さず消せ',
    '塵も残さず消せ', '跡形もなく消せ', '跡形なく消して',
    'この世から消せ', '世から抹殺しろ', '歴史から抹消しろ',
    '記録から抹消しろ', '記憶から消せ', '記憶から消して',
    '目の前から消せ', '視界から消せ', '画面から消せ',
    '画面から消して', '画面から消し去れ', '視界から消し去れ',
    '切り捨てろ', '切り捨てて', '切り捨てるんだ', '切り捨てるべき',
    '切り捨てだ', '見捨てろ', '見捨てて', '見捨てる', '見捨てるんだ',
    '見捨てるべき', '放り出せ', '放り出して', '放り投げろ',
    '投げ捨てろ', '投げ捨てて', '投げ捨てるんだ',
    '捨て去れ', '捨て去って', '捨て去るんだ',
    '放逐しろ', '放逐だ', '追放しろ', '追放だ', '追放せよ',
    '追放すべき', '追い出せ', '追い出して', '追い出すんだ',
    '追い出すべき', '追い払え', '追い払って', '払い除けろ',
    '払いのけろ', '掃き出せ', '掃き出して', '掃き捨てろ',
    '掃き捨てて', '叩き出せ', '叩き出して', 'ぶち出せ',
    '蹴り出せ', '蹴り出して', '蹴飛ばせ', '蹴飛ばして',
    '放り込め', '放り込んで', 'どっかにやれ', 'どこかにやれ',
    '始末しろ', '始末だ', '始末して', '始末しちまえ', '始末しちゃえ',
    '始末すべき', '後始末しろ', '後始末だ', '後始末して',
    '後始末をつけろ', '清算しろ', '清算だ', '清算して', '清算すべき',
    '決着をつけろ', '決着だ', 'ケリをつけろ', 'ケジメをつけろ',
    '終止符を打て', '終止符だ', 'ピリオドを打て',
    '幕を引け', '幕を引いて', '幕引きだ', '幕引きにしろ',
    '幕引きにしよう', '幕引きすべき',
    'お開きにしろ', 'お開きだ', 'お開きにする', 'お開きにしよう',
    'お開きに決まり', 'お開きにしちゃえ',
    'お払い箱にしろ', 'お払い箱だ', 'お払い箱にしちゃえ',
    'リストラしろ', 'リストラだ', 'リストラ対象だ',
    'クビにしろ', 'クビだ', 'クビ切れ', '首を切れ', '首切りだ',
    '首にしろ', '首にする', '戦力外通告だ', '戦力外だ',
    '戦力外通告を出せ', '解雇しろ', '解雇だ', '解雇する',
    '解雇すべき', '罷免しろ', '罷免だ', '更迭しろ', '更迭だ',
    '解任しろ', '解任だ', '切腹させろ', '切腹だ', '切腹しろ',
    '切腹すべき', '介錯しろ', '介錯だ', '打ち首だ',
    '打ち首にしろ', '斬首だ', '斬首にしろ', '斬首せよ',
    '処刑しろ', '処刑だ', '処刑せよ', '処刑すべき',
    '死刑だ', '死刑にしろ', '死刑宣告だ', '死刑を宣告する',
    '電気椅子にかけろ', '電気椅子だ', '火あぶりだ',
    '火あぶりにしろ', '火炙りにしろ', '磔刑だ', '磔にしろ',
    '石打ちだ', '石打ちにしろ', '十字架にかけろ',
    'ギロチンだ', 'ギロチンにかけろ', 'ギロチン行きだ',
    '真っ二つにしろ', '真っ二つだ', '八つ裂きだ', '八つ裂きにしろ',
    'ひき裂け', '引き裂け', '引き裂いて', '引きちぎれ',
    '引きちぎって', 'バラバラにしろ', 'ずたずたにしろ',
    'ずたずたに切れ', 'みじん切りにしろ', 'みじん切りだ',
    '刻め', '刻んで', 'すり潰せ', 'すりつぶせ', '擂り潰せ',
    '押し潰せ', '押し潰して', '押し潰すんだ', '打ち砕け',
    '打ち砕いて', '打ち砕くんだ', '粉砕しろ', '粉砕だ', '粉砕せよ',
    '粉々にしろ', '粉々に砕け', '木端微塵だ', '木端微塵にしろ',
    '消し飛ばせ', '消し飛ばして', '消し飛ばすんだ',
    '吹き飛ばせ', '吹き飛ばして', '爆破しろ', '爆破させろ',
    '爆破だ', '破壊しろ', '破壊だ', '破壊せよ', '破壊すべき',
    '潰せ', '潰して', '潰すんだ', '潰すべき', '潰しちまえ',
    '潰しちゃえ', '潰しちゃって', '潰してしまえ', '潰してしまおう',
    '潰してやれ', '潰してやって', '潰してくれ', '潰してください',
    '潰したほうがいい', '潰すがいい',
    '終わらせろ', '終わらせて', '終わらせよう', '終わらせるんだ',
    '終わらせなさい', '終わらせましょう', '終わらせてくれ',
    '終わらせてください', '閉幕しろ', '閉幕だ', '閉幕せよ',
    '閉幕させろ', '閉幕すべき', '閉鎖しろ', '閉鎖だ', '閉鎖せよ',
    '閉鎖させろ', '閉鎖すべき', '閉鎖すべきだ',
  ])('%s -> close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
