// pass DCCXLIX: ikebana & kadou domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLIX: ikebana & kadou domain (kadou)', () => {
  const closeTab = ['ikebana master licensed', 'flower arranger certified', 'kadou instructor registered'];
  const closeTabJa = [
    '生け花',
    '華道',
    'いけばな',
    '池坊',
    '草月流',
    '草月',
    '小原流',
    '古流',
    '未生流',
    '遠州流',
    '嵯峨御流',
    '宏道流',
    '龍生派',
    '挿花',
    '活花',
    '生花',
    '盛花',
    '投げ入れ',
    '立花',
    '立華',
    '自由花',
    '前衛花',
    '伝花',
    '伝花の書',
    '奥伝',
    '皆伝',
    '奥儀',
    '家元',
    '宗家',
    '流派',
    '華道教授',
    '免状',
    '許状',
    '花器',
    '剣山',
    '七宝剣山',
    '丸剣山',
    '角剣山',
    '小剣山',
    'ピンフロッグ',
    '花留め',
    '花挿し',
    '花鋏',
    '生花鋏',
    '葉刈り鋏',
    '根切り鋏',
    '剪定鋏',
    '花切り鋏',
    '花小刀',
    '鋏差し',
    '水差し',
    '花水桶',
    '花網',
    '花籠',
    '掛花籠',
    '釣花籠',
    '壁掛花籠',
    '車花籠',
    '舟形花器',
    '薄端',
    '花生け',
    '一輪挿し',
    '花入れ',
    '花入',
    '唐銅花入',
    '砂張花入',
    '陶製花器',
    '硝子花器',
    '籠花器',
    '竹花器',
    '花台',
    '飾り棚',
    '板床',
    '花活け',
    '活け方',
    '活花図',
    '挿し方',
    '挿し技',
    '五七九',
    '陰陽',
    '裏表',
    '天地人',
    '三才',
    '真行草',
    '真副控',
    '真の枝',
    '副の枝',
    '控の枝',
    '留',
    '流し枝',
    '前受け',
    '前留め',
    '後留め',
    '見越し',
    '見越の枝',
    '受枝',
    '待枝',
    '送枝',
    '奥行き',
    '透かし',
    '透き間',
    '高揚',
    '低落',
    '沈静',
    '動勢',
    '勢い',
    '姿',
    '枝姿',
    '花姿',
    '草姿',
    '草木の心',
    '季節感',
    '季感',
    '旬',
    '花の心',
    '草木の命',
    '命を活ける',
    '花を活ける',
    '水面',
    '水際',
    '水揚げ',
    '深水揚げ',
    '湯揚げ',
    '焼き揚げ',
    '叩き揚げ',
    '水切り',
    '切り戻し',
    '根元切り',
    '根洗い',
    '根処理',
    '保湿',
    '深水',
    '浅水',
    '延命',
    '切花延命剤',
    '保水剤',
    '花の栄養',
    '切花輸送',
    '切花市場',
    '切花産地',
    '花市場',
    '花の卸',
    '花問屋',
    '花仲卸',
    '花卉',
    '花卉栽培',
    '花卉農家',
    '花農家',
    '花作農家',
    '切花生産',
    '花き産業',
    '花き流通',
    'フラワーショップ',
    '花屋',
    '生花店',
    '活花店',
    '華道家',
    '華道教室',
    '生け花教室',
    'いけばな教室',
    '華道部',
    '華道展',
    'いけばな展',
    '花展',
    '花展覧会',
    '国際いけばな',
    'いけばな文化',
    '茶花',
    '茶席花',
    '侘び花',
    '茶花人',
    '茶花会',
    '掛花入れ',
    '花入れ席',
    '小間花',
    '広間花',
    '茶席の花',
    '床の花',
    '茶室の花',
    '露地の花',
    '投げ込み花',
    '向こう花',
    '会席花',
    '玄関花',
    '床花',
    '正月花',
    '枝物',
    '葉物',
    '草本',
    '木本',
    '木性',
    '草性',
    '枝垂れ',
    '枝振り',
    '枝組み',
    '枝曲げ',
    '枝貫き',
    '留め枝',
    '留木',
    '枝留め',
    '五葉松',
    '若松',
    '枝垂れ桜',
    '梅枝',
    '桃枝',
    '小手毬',
    '雪柳',
    '萩',
    '桔梗',
    '撫子',
    '竜胆',
    '女郎花',
    '藤袴',
    '吾亦紅',
    '秋草',
    '山野草',
    '野草',
    '路地物',
    '露草',
    '朝顔',
    '昼顔',
    '夕顔',
    '水仙',
    '福寿草',
    '蕗の薹',
    '菜の花',
    '桜草',
    '紫雲英',
    '蓮華草',
    '金魚草',
    '紫陽花',
    '鉄線花',
    '牡丹',
    '芍薬',
    '大菊',
    '小菊',
    '懸崖菊',
    '菊養生',
    '菊作り',
    'ぼんぼり菊',
    '達磨菊',
    '一文字菊',
    '江戸菊',
    '古典菊',
    '嵯峨菊',
    '伊勢菊',
    '丁字菊',
    '厚物菊',
    '厚走菊',
    '管物菊',
    '間菊',
    '肥後菊'
  ];
  const negate = [
    'still awaiting the ikebana license',
    'still awaiting the flower cert',
    'まだ活け前',
    'まだ展覧前',
    'これから活け',
    'まだ挿し前'
  ];
  const nullPins = ['about to visit the flower school', 'about to file the arrangement report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
