// pass DCCXLIII: woodwork & joinery domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLIII: woodwork & joinery domain (kanna)', () => {
  const closeTab = ['woodworker licensed', 'joiner certified', 'carpenter registered'];
  const closeTabJa = [
    '木工',
    '木工職人',
    '大工',
    '宮大工',
    '建築大工',
    '数寄屋大工',
    '指物師',
    '指物',
    '組子',
    '組子細工',
    '寄木細工',
    '寄木',
    '木地師',
    '木地',
    '木地屋',
    '挽き物',
    '挽物',
    '木彫',
    '木彫り',
    '木彫刻',
    '一位一刀彫',
    '木彫師',
    '木曽木工',
    '木工芸',
    '木工作家',
    '木工工房',
    '木工教室',
    '木工検定',
    '日曜大工',
    '木工体験',
    '曲げわっぱ',
    '曲げ物',
    '曲物',
    '大館曲げわっぱ',
    '桶',
    '樽',
    '酒樽',
    '寿司桶',
    '樽職人',
    '桶職人',
    '木桶',
    '茶桶',
    '檜風呂',
    '桶風呂',
    '樽丸',
    '箍',
    'たが',
    '鉄箍',
    '銅箍',
    '結箍',
    '杢',
    '木目',
    '柾目',
    '板目',
    '節',
    '節眼',
    '玉杢',
    '縮み杢',
    '葡萄杢',
    '虎杢',
    '栃杢',
    '花梨杢',
    '黒柿',
    '神代杉',
    '埋もれ木',
    '屋久杉',
    '木曽檜',
    '秋田杉',
    '吉野杉',
    '吉野檜',
    '東濃檜',
    '日田杉',
    '熊野杉',
    '尾鷲檜',
    '御神木',
    '柱',
    '心木',
    '貫',
    '梁',
    '桁',
    '斗栱',
    '組物',
    '斗組',
    '垂木',
    '茅葺',
    '杮葺',
    '檜皮葺',
    '柿葺',
    '木割',
    '木取り',
    '製材',
    '製材所',
    '木材',
    '材木',
    '角材',
    '板材',
    '原木',
    '丸太',
    '挽き板',
    '合板',
    '集成材',
    '構造材',
    '下地材',
    '墨付け',
    '墨壺',
    '手斧',
    '釿',
    '鉋',
    'かんな',
    '鉋屑',
    '刃物研ぎ',
    '砥石',
    'ノミ',
    'のみ',
    '鑿',
    '突き鑿',
    '平鑿',
    '丸鑿',
    '三角鑿',
    '鎬鑿',
    '追入れ',
    '切り出し',
    '小刀',
    '木槌',
    '木づち',
    '玄能',
    'げんのう',
    '釘抜き',
    'バール',
    '鋸',
    'のこぎり',
    '両刃鋸',
    '引き回し鋸',
    '胴付鋸',
    '目立て',
    '万力',
    'クランプ',
    '木こり',
    '樵',
    '杣',
    '製材機',
    'プレーナー',
    'サンダー',
    'トリマー',
    'ルーター',
    '丸鋸',
    '電動丸鋸',
    'ジグソー',
    '卓上丸鋸',
    '木工機械',
    '木工工作',
    'レーザー加工',
    '組み手',
    '継手',
    '仕口',
    'ほぞ',
    '蟻組',
    '鎌継ぎ',
    '腰掛け',
    '追っ掛け大栓継ぎ',
    '相欠き',
    '込み栓',
    '留め形',
    '木釘',
    'くさび',
    '枘',
    'ほぞ穴',
    '卯接',
    '接着',
    '木工ボンド',
    'ニス',
    'ウレタン塗装',
    'オイル仕上げ',
    '蜜蝋',
    'ワックス',
    '木蝋',
    '砂目',
    '木肌',
    '肌目',
    '床柱',
    '床の間',
    '書院',
    '長押',
    '廂',
    '鴨居',
    '敷居',
    '溝',
    '縁側',
    '欄間',
    '障子',
    '欄間彫り',
    '虫喰い',
    '木の家',
    '木造',
    '在来工法',
    'ツーバイフォー',
    '軸組',
    '柱脚',
    '土台',
    '神棚',
    '床の間飾り',
    '仏壇',
    '仏壇彫り',
    '金沢仏壇',
    '飯山仏壇',
    '位牌台',
    '仏間',
    '経机',
    '収納',
    '桐箪笥',
    '箪笥',
    '整理箪笥',
    '和箪笥',
    '長持',
    '衣桁',
    '木札',
    '表札',
    '一枚板',
    '無垢材',
    '無垢フローリング',
    '床板',
    'フローリング',
    '羽目板',
    '腰板',
    '天井板',
    '廻り縁',
    '幅木',
    '巾木',
    '子供椅子',
    '木のおもちゃ',
    '積み木',
    'つみき',
    '木育',
    '木製玩具',
    '木工旋盤',
    '木食',
    '木食い',
    '棟梁',
    '親方',
    '大工道具',
    '大工検定',
    '木工技能士',
    '建具技能士'
  ];
  const negate = [
    'still awaiting the joiner license',
    'still awaiting the carpentry cert',
    'まだ製材前',
    'まだ組み前',
    'これから挽き',
    'まだ上棟前'
  ];
  const nullPins = ['about to visit the lumber mill', 'about to file the timber report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
