// pass DCCLIX: karate & karateka domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCLIX: karate & karateka domain (karate)', () => {
  const closeTab = ['karate athlete licensed', 'karate master certified', 'karate instructor registered'];
  const closeTabJa = [
    '空手',
    '空手道',
    '空手家',
    '空手選手',
    '空手士',
    '空手道場',
    '空手教室',
    '空手部',
    '空手界',
    '空手着',
    '胴着',
    '帯締め',
    '空手検定',
    '空手審査',
    '空手段級位制',
    '空手初段',
    '空手昇段',
    '正拳突き',
    '裏拳打ち',
    '手刀打ち',
    '肘打ち',
    '鉄槌打ち',
    '平突き',
    '追い突き',
    '逆突き',
    '順突き',
    '突き上げ',
    '二連突き',
    '刻み突き',
    '下突き',
    '前蹴り',
    '回し蹴り',
    '後蹴り',
    '蹴上げ',
    '払い蹴り',
    '踵落とし',
    '膝蹴り',
    '前回し蹴り',
    '飛び蹴り',
    '足刀',
    '足底',
    '踵',
    '指先',
    '手刀',
    '刀手',
    '裏手刀',
    '貫手',
    '小手',
    '猿臂',
    '熊手',
    '鶴嘴',
    '平拳',
    '一本拳',
    '二貫指',
    '内受け',
    '外受け',
    '手刀受け',
    '二本受け',
    '掌底受け',
    '弧動受け',
    '左半身',
    '右半身',
    '逆半身',
    '半身',
    '立ち方',
    '構え方',
    '前屈立ち',
    '後屈立ち',
    '騎馬立ち',
    '猫足立ち',
    '半月立ち',
    '結び立ち',
    '閉足立ち',
    '平行立ち',
    '外八字立ち',
    '内八字立ち',
    '三戦立ち',
    '捌き',
    '体重移動',
    '重心移動',
    '腰入れ',
    '型競技',
    '組手競技',
    '約束組手',
    '基本組手',
    '自由組手',
    '一歩組手',
    '三本組手',
    '五本組手',
    '組手試合',
    '寸止め',
    '寸止め組手',
    '防具付き空手',
    'フルコンタクト',
    'フルコンタクト空手',
    '伝統空手',
    '実践空手',
    '武道空手',
    '体育空手',
    '健康空手',
    '松濤館流',
    '糸東流',
    '剛柔流',
    '和道流',
    '少林寺流',
    '本部流',
    '沖縄小林流',
    '上地流',
    '極真会館',
    '極真空手',
    '正道会館',
    '円心会館',
    '芦原会館',
    '全日本空手道連盟',
    '日本空手協会',
    '世界空手連盟',
    '空手道連盟',
    '空手協会',
    '全日本空手道選手権',
    '高校空手道選手権',
    '世界空手道選手権',
    '首里手',
    '那覇手',
    '泊手',
    '唐手',
    '琉球空手',
    '南派',
    '北派',
    '少林流',
    '白鶴拳',
    '船越義珍',
    '宮城長順',
    '本部朝基',
    '摩文仁賢和',
    '大山倍達',
    '大塚博紀',
    '空手に先手なし',
    '型名',
    '平安型',
    '平安初段',
    '平安二段',
    '平安三段',
    '平安四段',
    '平安五段',
    'ナイハンチ',
    'ナイハンチ初段',
    'ナイハンチ二段',
    'ナイハンチ三段',
    'チントー',
    'ウンシュ',
    'バッサイ大',
    '観空大',
    '五十四歩',
    'カンクーダイ',
    'ソーチン',
    'ジオン',
    'エンピ',
    '鉄騎',
    'セーパイ',
    'セーサン',
    'サンチン',
    'テンショウ',
    'ゲキサイ第一',
    'ゲキサイ第二',
    'サイファ',
    'セイエンチン',
    'シソーチン',
    'パイホー',
    'クルルンファ',
    '糸東流型',
    '剛柔流型',
    '松濤館流型',
    '和道流型',
    '基本形',
    '約束形',
    '指定形',
    '形演武',
    '空手演武',
    '組手演武',
    '分解',
    '型分解',
    '意味分解',
    '空手審判',
    '判定員',
    '上げ判定',
    '挙手判定',
    '警告',
    '場外注意',
    '空手歴',
    '空手齢',
    '空手修行',
    '空手道精神',
    '道場訓',
    '空手家心得',
    '空手初心者',
    '空手入門',
    '空手マスターズ',
    'シニア空手',
    '子供空手',
    '幼年空手',
    '少年空手',
    '女性空手',
    '車椅子空手',
    '障害者空手',
    'パラ空手',
    '適応空手'
  ];
  const negate = [
    'still awaiting the karate license',
    'still awaiting the kumite ruling',
    'まだ組手前',
    'まだ型前',
    'これから突き',
    'まだ場所前'
  ];
  const nullPins = ['about to visit the karate hall', 'about to file the bout report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
