// pass DCCXXXIX: washi & papercraft domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXXXIX: washi & papercraft domain (kouzo)', () => {
  const closeTab = ['papermaker licensed', 'washi maker certified', 'paper mill registered'];
  const closeTabJa = [
    '和紙',
    '手漉き和紙',
    '手すき和紙',
    '紙漉き',
    '紙すき',
    '漉き桁',
    '簀',
    '簀桁',
    '紙床',
    '紙槽',
    '槽',
    '乾燥板',
    '板干し',
    '天日乾燥',
    '楮',
    '三椏',
    '雁皮',
    '雁皮紙',
    'トロロアオイ',
    'ネリ',
    '紙料',
    '原料',
    '白皮',
    '黒皮',
    '灰汁煮',
    '晒し',
    '叩解',
    'ビーター',
    '分散剤',
    '繊維',
    'パルプ',
    '和パルプ',
    '洋紙',
    '機械漉き',
    '美濃和紙',
    '越前和紙',
    '細川紙',
    '細川和紙',
    '石州半紙',
    '石州和紙',
    '杉原紙',
    '名尾紙',
    '黒谷和紙',
    '阿波和紙',
    '土佐和紙',
    '因州和紙',
    '出雲民芸紙',
    '五箇山和紙',
    '大洲和紙',
    '西ノ内紙',
    '那須和紙',
    '本美濃紙',
    '小間紙',
    '半紙',
    '奉書紙',
    '奉書',
    '鳥の子紙',
    '鳥子紙',
    '檀紙',
    '大展紙',
    '大直紙',
    '美濃紙',
    '障子紙',
    '襖紙',
    '壁紙',
    '唐紙',
    '雲母刷り',
    '雲母紙',
    '砂子',
    '砂子紙',
    '切金箔',
    '泥金',
    '泥銀',
    '型染和紙',
    '染和紙',
    '色紙',
    '料紙',
    '懐紙',
    '短冊',
    '歌留多',
    '便箋',
    '封筒',
    '一筆箋',
    '巻紙',
    '奉書巻き',
    '和装本',
    '和綴じ',
    '四目綴じ',
    '亀甲綴じ',
    '麻の葉綴じ',
    '唐組み',
    '大和綴じ',
    '袋綴じ',
    '折り本',
    '帖',
    '短冊帖',
    '色紙掛け',
    '表装',
    '表具',
    '掛軸',
    '掛け軸',
    '額装',
    '額縁',
    '屏',
    '屏風',
    '衝立',
    '襖',
    '障子',
    '張り替え',
    '建具紙',
    '紙縒',
    'こより',
    '水引',
    'あぶら紙',
    '油紙',
    '防水紙',
    '加工紙',
    '和紙人形',
    '紙塑',
    '張り子',
    '紙張り子',
    'だるま',
    '張子虎',
    'ちぎり絵',
    '貼り絵',
    '折り紙',
    '千代紙',
    '友禅紙',
    '和紙工芸',
    '紙工芸',
    '紙雑貨',
    '紙袋',
    '手提げ',
    '和紙灯り',
    '行灯',
    '提灯',
    '岐阜提灯',
    '和傘',
    '番傘',
    '蛇の目傘',
    '和紙小物',
    '冠婚葬祭紙',
    '祝儀袋',
    'のし袋',
    'ポチ袋',
    'お年玉袋',
    '奉書袋',
    '半紙屋',
    '紙問屋',
    '和紙卸',
    '紙漉き体験',
    '和紙工房',
    '紙漉き職人',
    '漉き師',
    '紙漉き手',
    '和紙検定',
    '紙漉き工程',
    '漉き枠',
    '抄き込み',
    'ゆり返し',
    '水切り',
    '圧搾',
    '脱水',
    '仕上げ'
  ];
  const negate = [
    'still awaiting the paper license',
    'still awaiting the washi cert',
    'まだ抄き前',
    'まだ乾燥前',
    'これから漉き',
    'まだ製紙前'
  ];
  const nullPins = ['about to visit the paper mill', 'about to file the paper report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
