// pass DCCLVIII: kyudo & archery domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCLVIII: kyudo & archery domain (kyudo)', () => {
  const closeTab = ['kyudo archer licensed', 'kyudo master certified', 'kyudo instructor registered'];
  const closeTabJa = [
    '弓道',
    '弓道家',
    '弓術',
    '弓術家',
    '弓道部',
    '弓道界',
    '弓道場',
    '射場',
    '弓具',
    '弓道着',
    '弓道衣',
    '弓道袴',
    '和弓',
    '竹弓',
    '合成弓',
    '木弓',
    '大弓',
    '半弓',
    '小弓',
    '並寸',
    '弓寸',
    '矢寸',
    '弓丈',
    '矢丈',
    '弦高',
    '内籠',
    '弓手',
    '馬手',
    '押し手',
    '弓返り',
    '弦',
    '弓弦',
    '弦巻',
    '弦木',
    '弦音',
    '弦の音',
    '弽',
    'ゆがけ',
    '手袋',
    '蓑下',
    '矢',
    '鏑矢',
    '羽根',
    '矢羽',
    '篦',
    '筈',
    '鏃',
    '矢番',
    '的',
    '円的',
    '星形',
    '霞的',
    '的中',
    '中',
    '不中',
    '的中率',
    '的場',
    '本多通的',
    '近射',
    '遠射',
    '的射',
    '競射',
    '堂射',
    '三十三間堂',
    '通し矢',
    '大場',
    '一座',
    '二座',
    '四場',
    '立射',
    '座射',
    '百射',
    '千射',
    '八節',
    '射法八節',
    '足踏み',
    '胴造り',
    '弓構え',
    '打起こし',
    '会',
    '離れ',
    '残身',
    '押し開き',
    '早気',
    '独り',
    '弓構え方',
    '射型',
    '射法',
    '素引き',
    '番高',
    '向かい的',
    '的当て',
    '射稽古',
    '弓道稽古',
    '巻藁',
    '弓道範士',
    '弓道教士',
    '弓道錬士',
    '弓道審査',
    '弓道検定',
    '弓道段位',
    '弓道連盟',
    '全日本弓道連盟',
    '日本弓道連盟',
    '弓道協会',
    '京都弓道院',
    '本多流',
    '日置流',
    '尾張竹林派',
    '阿波研造',
    '本多利実',
    '正射必中',
    '一射絶命',
    '射法訓',
    '弓道訓',
    '以心伝心',
    '矢渡し',
    '弓指し',
    '籠手',
    '懸尾',
    '乳革',
    '弓勘合',
    '勘合',
    '弓引き',
    '弓引き手',
    '弓持ち',
    '矢持ち',
    '矢筈',
    '弓弦矢',
    '弓張',
    '弓張り',
    '弓抱き',
    '弓取り',
    '追い手?',
    '候的?',
    '霞的場',
    '立掛け',
    '座敷射',
    '行射',
    '草刈り',
    '数的中',
    '的中数',
    '千手的?',
    '的紙',
    '的板',
    '的台',
    '的屋',
    '土堤',
    '安土',
    '靶',
    '橛',
    '待機所',
    '控え所',
    '立ち待機',
    '射手',
    '矢場',
    '矢数',
    '一手',
    '二手',
    '一手目',
    '的ならし',
    '的直し',
    '的測り',
    '狙い',
    '狙い方',
    '押し弓',
    '引き弓',
    '引き手筋',
    '弓手筋',
    '馬手筋',
    '離れ方',
    '残身姿勢',
    '矢先',
    '矢留',
    '矢止め',
    '矢指',
    '弓指',
    '放生津弓?',
    '礼射',
    '礼射法',
    '口説',
    '口伝',
    '極意',
    '免許皆伝',
    '皆伝',
    '奥伝',
    '中伝',
    '初伝',
    '目録',
    '印可',
    '指南',
    '師範代',
    '教師',
    '弓道教師',
    '弓道指導',
    '弓道コーチ',
    '弓道部員',
    '弓道人口',
    '弓道歴',
    '弓齢',
    '弓道修行',
    '弓道試合',
    '弓道大会',
    '弓道選手権',
    '全日本弓道選手権',
    '全国弓道大会',
    '天皇盃',
    '高森杯?',
    '弓道祭',
    '弓道発表',
    '弓道演武',
    '演武',
    '弓道行事',
    '弓道年中行事',
    '歩射',
    '騎射',
    '笠縫',
    '大笠縫',
    '犬追物',
    '流鏑馬',
    '小笠原流',
    '鎌倉武士',
    '武士道',
    '弓の心',
    '弓道理',
    '弓徳',
    '射礼',
    '射道',
    '射歌',
    '弓蒔き?'
  ];
  const negate = [
    'still awaiting the kyudo license',
    'still awaiting the shooting ruling',
    'まだ射場前',
    'まだ的中前',
    'これから素引き',
    'まだ場所前'
  ];
  const nullPins = ['about to visit the kyudo hall', 'about to file the shooting report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
