// Pass CCLII: EN deactivation/power-cutoff + void-verbs + send-off + JA sever/crush/seizure/freeze (pass CCLII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLII: close-tab coverage', () => {
  test.each([
    "disable it", "deactivate it", "disarm it", "defuse it",
    "neutralise it", "incapacitate it", "immobilize it", "immobilise it",
    "paralyze it", "paralyse it", "maim it", "cripple it",
    "lame it", "hobble it", "handicap it", "debilitate it",
    "enfeeble it", "weaken it", "sap it", "exhaust it",
    "deplete it", "disable the tab", "deactivate the tab", "immobilize the tab",
    "paralyze the tab", "cripple the tab", "bleed it dry", "bleed it out",
    "bleed it to death", "cut off its supply", "cut off its oxygen", "cut off its air",
    "cut off its power", "cut its supply", "cut its lifeline", "cut the lifeline",
    "cut its air supply", "cut off the oxygen", "cut off the air supply", "pull the plug",
    "yank its cord", "yank the cord", "pull the cord", "disconnect it",
    "disconnect the tab", "unplug the cord", "kill the power to it", "cut the juice",
    "kill the juice", "cut the electricity", "kill the electricity", "shut off the power",
    "shut off power to it", "switch off the tab", "flip the switch on it", "shut the tab off",
    "shut off the tab", "power the tab off", "shut down the tab", "take it off-line",
    "take the tab offline", "take it off grid", "off the grid with it", "off-grid it",
    "cut it from the grid", "sever the connection", "sever its connection", "sever the link",
    "sever its link", "cut the connection", "cut its connection", "cut the link",
    "cut its link", "break the link", "break its link", "break the connection",
    "break its connection", "kill the connection", "kill its connection", "kill the link",
    "kill its link", "terminate the connection", "terminate the link", "end the connection",
    "end the link", "disconnect the link", "unattach it", "unlink it",
    "unlink the tab", "decouple it", "decouple the tab", "uncouple it",
    "unhitch it", "unhitch the tab", "untether it", "unfasten it",
    "unbolt it", "unscrew it", "unscrew the tab", "unclasp it",
    "unlatch it", "unclamp it", "unclip it", "unclip the tab",
    "unstrap it", "unbuckle it", "unbutton it", "unzip the tab",
    "unlace it", "unwind it", "unwind the tab", "unplug it forever",
    "disconnect it forever", "cut the cord forever", "pull the plug permanently", "pull the plug forever",
    "pull the plug once and for all", "rip out the plug", "rip the plug out", "trip the breaker on it",
    "flip the breaker", "kill the breaker", "hit the kill switch", "hit the kill switch on it",
    "flip the kill switch", "pull the kill switch", "engage the kill switch", "activate the kill switch",
    "kill switch it", "kill-switch it", "blow a fuse on it", "blow the fuse",
    "pop the fuse", "short-circuit it", "fry its board", "overcharge it",
    "brown it out", "black it out", "blackout it", "fade it out completely",
    "fade the tab to black", "black it out completely", "black out the tab", "blank it out completely",
    "countermand it", "disinherit it", "disaffirm it", "vitiate it",
    "nix on it", "void out it", "quash the tab", "declare it void",
    "declare it null", "declare it null and void", "declare it invalid", "declare it void forever",
    "rule it void", "rule it invalid", "rule it out", "rule it out forever",
    "strike the tab down", "strike it down forever", "overrule it forever", "quash it completely",
    "quash it forever", "annul it forever", "annul it completely", "rescind it forever",
    "revoke it forever", "repeal it forever", "void it forever", "void it completely",
    "invalidate it forever", "invalidate it completely", "nullify it forever", "nullify it completely",
    "abolish it forever", "dissolve it forever", "dissolve it completely", "countermand it forever",
    "shut it shut", "seal it", "seal the tab", "lock it",
    "lock the tab", "lock it closed", "lock it forever", "latch it",
    "bolt it", "bar it", "bar it shut", "shutter it shut",
    "glue it shut", "glue it closed", "tape it closed", "zip the tab shut",
    "button it shut", "cork the tab", "cap it", "cap the tab",
    "cap it off", "cap it off forever", "pull it shut", "pull it closed",
    "draw it shut", "draw it closed", "swing it shut", "swing it closed",
    "slam the tab shut", "clap it shut", "clap it closed", "bang it closed",
    "tuck the tab away", "tuck it away forever", "stow the tab", "stow it away forever",
    "pack it away forever", "pack it up forever", "box it away", "box it up forever",
    "bag it up forever", "crate it up forever", "put the tab to rest", "put it to sleep forever",
    "put it to bed forever", "sing it to sleep forever", "rock it to sleep forever", "kiss it goodbye forever",
    "wave it goodbye forever", "bid it goodbye", "bid it a fond farewell", "say goodbye to it",
    "say farewell to it", "wish it goodbye", "wish it farewell", "wish it goodnight",
    "give it a send-off", "give it a sendoff", "give it a proper send-off", "give it a proper sendoff",
    "give it a viking funeral", "give it a vikings funeral", "give it a burial at sea", "give it the last rites",
    "give it the final rites", "give it its last rites", "read it the last rites", "administer the last rites to it",
    "administer last rites to it", "perform last rites on it", "say a prayer over it", "say a prayer for the tab",
    "light a candle for the tab", "ring the bell for it", "ring the death knell", "ring the death knell for it",
    "sound the death knell", "sound the death knell for it", "play taps over it", "sound taps for it",
    "hold a vigil for it", "hold a vigil for the tab", "hold a funeral for the tab", "hold a memorial for it",
    "hold a memorial for the tab", "hold a service for it", "hold a service for the tab", "hold a wake for it",
    "hold a wake for the tab", "eulogise it", "eulogize the tab", "give the eulogy for it",
    "deliver the eulogy for it", "write the obituary for it", "write its epitaph", "write the epitaph for it",
    "carve its epitaph", "carve the epitaph for it", "fly the flag at half mast for it", "fly the flag at half-mast",
    "fly the flag at half-mast for it", "fire a salute for it", "fire a twenty one gun salute", "fire a 21 gun salute",
    "give it a 21 gun salute", "give it a twenty one gun salute", "give it a three volley salute", "fire three volleys for it",
    "fire three volleys over it", "切れ", "切って", "切るんだ",
    "切断しろ", "切断だ", "切断にしろ", "分断しろ",
    "分断だ", "分断にしろ", "断線させろ", "断線だ",
    "引き離せ", "引き離して", "引き離すんだ", "分離させろ",
    "分離だ", "離脱させろ", "脱線させろ", "脱線だ",
    "逸脱させろ", "外せ", "外して", "外すんだ",
    "取り外せ", "取り外して", "取り外すんだ", "剥がし取れ",
    "剥がし取って", "むしり取れ", "むしり取って", "毟り取れ",
    "毟り取って", "ちぎり取れ", "ちぎり取って", "ちぎれ",
    "ちぎって", "千切れ", "千切って", "裂け",
    "裂いて", "破れ", "破って", "破り捨てて",
    "破り捨てるんだ", "破り裂け", "破り裂いて", "破いて捨てて",
    "破り去れ", "破り去って", "ビリビリにしろ", "ビリビリに破れ",
    "細切れにして", "バラバラにして", "バラバラだ", "ばらばらにしろ",
    "ばらばらにして", "ばらばらだ", "バラバラに裂け", "解体して",
    "解体してしまえ", "ばらして", "ばらすんだ", "解体処分だ",
    "解体処分にしろ", "粉砕機にかけろ", "粉砕機に入れろ", "粉砕機に通せ",
    "シュレッダーにかけろ", "シュレッダーに入れろ", "シュレッダーに通せ", "シュレッダーで破って",
    "シュレッダーだ", "破砕機にかけろ", "破砕機に入れろ", "クラッシャーにかけろ",
    "クラッシャーに入れろ", "挽き潰せ", "挽き潰して", "すり潰して",
    "磨り潰せ", "すりつぶして", "打ち潰せ", "打ち潰して",
    "握り潰して", "捻り潰せ", "捻り潰して", "ひねり潰せ",
    "ひねり潰して", "踏み潰せ", "踏み潰して", "踏み躙れ",
    "踏み躙って", "踏み躙るんだ", "蹂躙しろ", "蹂躙だ",
    "蹂躙せよ", "轢き潰せ", "轢き潰して", "挽き殺せ",
    "ひき殺せ", "圧し潰して", "折り潰せ", "折り潰して",
    "殴り潰せ", "殴り潰して", "擦り潰せ", "擦り潰して",
    "揉み潰せ", "揉み潰して", "捏ね潰せ", "捏ね潰して",
    "丸め潰せ", "丸めて捨てろ", "丸めて捨てて", "丸めてポイ",
    "丸めてポイ捨て", "くしゃくしゃにしろ", "くしゃくしゃにして", "クシャクシャにしろ",
    "クシャクシャにして", "ぐしゃぐしゃにしろ", "ぐしゃぐしゃにして", "グシャグシャにしろ",
    "グシャグシャにして", "ぐちゃぐちゃにしろ", "ぐちゃぐちゃにして", "めちゃくちゃにしろ",
    "めちゃくちゃにして", "メチャクチャにしろ", "メチャクチャにして", "めちゃめちゃにしろ",
    "ぼろぼろにしろ", "ぼろぼろにして", "ボロボロにしろ", "ボロボロにして",
    "ズタズタにしろ", "ズタズタにして", "ずたずたにして", "ズタズタに切れ",
    "寸々に裂け", "寸々に引き裂け", "こまぎれにしろ", "こまぎれに切れ",
    "小間切れにしろ", "小間切れに切れ", "ふさぎ込め", "堰き止めろ",
    "堰き止めて", "堰き止めるんだ", "堰止めろ", "堰止めて",
    "食い止めろ", "食い止めて", "阻め", "阻んで",
    "阻害しろ", "阻害だ", "妨害しろ", "妨害だ",
    "阻止しろ", "阻止だ", "阻止して", "阻止しちまえ",
    "抑えろ", "抑えて", "抑え込め", "抑え込んで",
    "抑止しろ", "抑止だ", "制圧しろ", "制圧だ",
    "鎮圧しろ", "鎮圧だ", "弾圧しろ", "弾圧だ",
    "取り締まれ", "取り締まって", "取締しろ", "取締だ",
    "摘発しろ", "摘発だ", "押収して", "召し上げろ",
    "召上げろ", "収用だ", "差押えろ", "差押えて",
    "差し止めろ", "差し止めて", "差止めろ", "差止めて",
    "凍結させろ", "氷漬けにしろ", "氷漬けだ", "氷漬けにするんだ",
    "凍らせろ", "凍らせて", "凍結処分だ", "固めてしまえ",
    "固めちまえ", "固めちゃえ", "石に変えろ", "石にしてしまえ",
    "石に変えてしまえ", "石に変えて", "石にするんだ", "石化させろ",
    "石化だ", "固形化しろ", "固形化だ", "凝固させろ",
    "凝固だ", "凝結させろ", "凝結だ", "カプセルに入れろ",
    "カプセルに封じろ", "カプセルに閉じ込めろ", "瓶に詰めろ", "瓶に入れろ",
    "瓶に閉じ込めろ", "瓶詰めにしろ", "瓶詰めだ", "缶詰めにしろ",
    "缶詰めだ", "缶に詰めろ", "缶に入れろ", "箱に詰めろ",
    "箱に入れろ", "箱に閉じ込めろ", "箱詰めにしろ", "箱詰めだ",
    "電源を切れ", "電源を落とせ", "電源切断しろ", "電源切断だ",
    "配線を切れ", "配線を切って", "コードを切れ", "コードを切って",
    "ケーブルを切れ", "ケーブルを切って", "ケーブルを抜け", "ケーブルを抜いて",
    "プラグを抜け", "プラグを抜いて", "コンセントを抜け", "コンセントを抜いて",
    "電源プラグを抜け", "ブレーカーを落とせ", "ブレーカーを落として", "ブレーカーを切れ",
    "ブレーカーを切って", "スイッチを切れ", "スイッチを切って", "主電源を切れ",
    "主電源を落とせ", "電源を絶て", "電気を消せ", "電気を消して",
    "電気を止めろ", "電気を止めて", "電気代を止めろ", "遮断しろ",
    "遮断だ", "電源を殺せ", "電源を殺して", "電気を殺せ",
    "電気を殺して", "回路を切れ", "回路を切って", "回路を遮断しろ",
    "ヒューズを切れ", "ヒューズを落とせ", "ヒューズを飛ばせ", "感電させろ",
    "感電させて", "短路させろ", "短絡させろ", "ショートさせろ",
    "ショートさせて", "放電させろ", "放電だ", "充電をやめろ",
    "給電を止めろ", "給電を切れ", "送電を止めろ", "送電を切れ",
    "通電を止めろ", "通電を切れ", "電源を切っちゃえ", "電源を落としちゃえ",
    "電気を消しちまえ", "電気を消しちゃえ", "プラグを抜いちまえ", "プラグを抜いちゃえ",
    "ケーブルを切っちまえ", "ケーブルを切っちゃえ", "コードを切っちまえ", "コードを切っちゃえ",
    "ブレーカーを落としちまえ", "ブレーカーを落としちゃえ", "殺しちゃえ", "殺せや",
    "殺せと言ったはずだ", "殺せと言ったろ", "殺せと言ってるだろ", "殺すつもりだよ",
    "殺すつもりだって", "殺すからな", "殺すからよ", "殺すべきだよ",
    "殺すべきと思うよ", "殺すべきと思うんだ", "殺すべきと思うんだよ", "殺すことだ",
    "殺すことにしようよ", "殺すことにしたよ", "殺すことに決めたよ", "殺すということだ",
    "殺すという判断だ", "殺すという結論だ", "殺すという意思だ", "殺すという腹だ",
    "殺すという心だ", "殺すという運びだ", "殺すという段取りだ", "殺すという流れだ",
    "殺すという模様だ", "殺すという形だ", "殺すという方向だ", "殺すという案件だ",
    "殺すという議案だ", "殺すという動議だ", "殺すという議決だ", "殺すという採決だ",
    "殺すという可決だ", "殺すという指令だ", "殺すという宣言だ", "殺すという見解だ",
    "殺す命じだ", "殺す命だ", "殺す号令だ", "殺す檄だ",
    "殺すお告げだ", "殺す神託だ", "殺す御触れだ", "殺す触れだ",
    "殺すおふれだ", "殺す決まりだ", "殺す決まりだよ", "殺す決定事項だ",
    "殺す確定事項だ", "殺す既定路線だ", "殺す既定の方針だ", "殺す既定方針だ",
    "殺す既定の流れだ", "殺す既定の運びだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
