// pass DCCLXIII: mahjong & mahjong player domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCLXIII: mahjong & mahjong player domain (mahjong)', () => {
  const closeTab = ['mahjong player licensed', 'mahjong master certified', 'mahjong instructor registered'];
  const closeTabJa = [
    '麻雀',
    '麻雀牌',
    '萬子',
    '筒子',
    '索子',
    '字牌',
    '風牌',
    '三元牌',
    '数牌',
    '幺九牌',
    '中張牌',
    '老頭牌',
    '花牌',
    '赤牌',
    '赤ドラ',
    '裏ドラ',
    '表ドラ',
    'ドラ表示牌',
    '王牌',
    '牌山',
    '捨て牌',
    '手牌',
    '副露',
    '鳴き',
    'ポン',
    'チー',
    'カン',
    '暗槓',
    '明槓',
    '加槓',
    '嶺上牌',
    '嶺上開花',
    '槍槓',
    '海底摸月',
    '河底撈魚',
    'リーチ',
    '立直',
    'ツモ',
    'ロン',
    '平和',
    'タンヤオ',
    '断幺九',
    'ピンフ',
    '一発',
    '門前清自摸和',
    '三色同刻',
    '三色同順',
    '一気通貫',
    '七対子',
    '対々和',
    '三暗刻',
    '三槓子',
    '小三元',
    '混老頭',
    'チャンタ',
    '純チャン',
    '混全帯',
    '純全帯',
    '役牌',
    '白',
    '發',
    '中',
    '場風',
    '自風',
    '混一色',
    '清一色',
    '緑一色',
    '字一色',
    '四暗刻',
    '四暗刻単騎',
    '四槓子',
    '国士無双',
    '国士十三面',
    '大三元',
    '大四喜',
    '小四喜',
    '九連宝燈',
    '純正九連',
    '天和',
    '地和',
    '人和',
    '役満',
    '倍満',
    '三倍満',
    '数え役満',
    '流し満貫',
    '符',
    '翻',
    '飜',
    '打点',
    '副底',
    '面子',
    '雀頭',
    '順子',
    '刻子',
    '槓子',
    '対子',
    '塔子',
    '両面',
    '辺張',
    '嵌張',
    '双碰',
    '単騎',
    'シャボ',
    'リャンメン',
    'カンチャン',
    'ペンチャン',
    'タンキ',
    '一盃口',
    '二盃口',
    '東場',
    '南場',
    '東風戦',
    '半荘',
    '半荘戦',
    '連荘',
    '輪荘',
    '本場',
    '供託',
    '積み棒',
    '点棒',
    'リーチ棒',
    '祝儀',
    'チップ',
    '配牌',
    '自摸',
    '打牌',
    '摸打',
    '先制',
    '追っかけ',
    '宣言牌',
    '立直宣言',
    '一発消し',
    'ノーテン',
    'テンパイ',
    '流局',
    '荒牌流局',
    '九種九牌',
    '四風連打',
    '三家和',
    '四開槓',
    '途中流局',
    '延長戦',
    '西入',
    '牌効率',
    '受け入れ',
    '有効牌',
    '無筋',
    '筋',
    '現物',
    '壁',
    '薄壁',
    'ノーチャンス',
    'ワンチャンス',
    'スジ',
    'カベ',
    '安牌',
    '安全牌',
    '危険牌',
    '放銃',
    '振り込み',
    '振聴',
    'フリテン',
    '同巡フリテン',
    '押し引き',
    'ベタオリ',
    '回し打ち',
    '手代わり',
    '待ち替え',
    '読み合い',
    '河読み',
    '山読み',
    '場読み',
    '点棒状況',
    'オーラス',
    'アガリトップ',
    'ラス親',
    '着順',
    'トビ',
    '箱下',
    'ハコ',
    '麻雀連合',
    '日本プロ麻雀連盟',
    '最高位戦',
    '麻雀王位',
    '雀王',
    '雀聖',
    'モンド杯',
    '雀魂',
    '天鳳',
    '雀荘',
    '雀卓',
    '全自動卓',
    '牌譜',
    '牌理',
    '何切る',
    '天鳳位',
    '雀力',
    '放銃率',
    '副露率',
    'アガリ率',
    '多井隆晴',
    '近藤誠一',
    '白鳥翔',
    '園田賢',
    '滝沢和典',
    '佐々木寿人',
    '二階堂亜樹',
    '二階堂瑠美',
    '魚谷侑未',
    '黒沢咲',
    '茅森早香',
    '瑞原明奈',
    '伊達朱里紗',
    '岡田紗佳',
    '渋川難波'
  ];
  const negate = [
    'still awaiting the mahjong license',
    'still awaiting the hand ruling',
    'まだ対局前',
    'まだアガリ前',
    'これから打牌',
    'まだ半荘前'
  ];
  const nullPins = ['about to visit the mahjong hall', 'about to file the hand record'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
