// Pass CCLVIII: EN devour/dissolve + JA swallow/curse/abandon (pass CCLVIII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLVIII: close-tab coverage', () => {
  test.each([
    "devour it whole", "devour it completely", "devour it entirely", "devour it utterly",
    "devour it alive", "devour it raw", "gobble it whole", "gulp the tab",
    "gulp it whole", "gulp it in one", "gulp it in one go", "swallow it in one",
    "ingest the tab", "ingest it whole", "consume it whole", "consume it completely",
    "consume it entirely", "consume it utterly", "consume it all", "digest the tab",
    "digest it completely", "digest it entirely", "absorb it", "absorb the tab",
    "absorb it completely", "absorb it entirely", "absorb it whole", "absorb it fully",
    "eat it whole", "eat it alive", "eat it raw", "eat it for breakfast",
    "eat it for lunch", "eat it for dinner", "eat it for a snack", "eat it for dessert",
    "chomp it in half", "chew it", "chew the tab", "chew it up",
    "chew it down", "chew it to bits", "chew it to pieces", "chew it to shreds",
    "chew it up and spit it out", "chew it up and swallow it", "chew it up and spit out the pieces", "bite it",
    "bite the tab", "bite it off", "bite it in half", "bite it in two",
    "bite it to bits", "chomp it to bits", "chomp it to pieces", "crunch the tab",
    "crunch it in half", "crunch it to bits", "crunch it to pieces", "gnaw it",
    "gnaw the tab", "gnaw it down", "gnaw it to the bone", "gnaw it to bits",
    "gnaw it to pieces", "gnaw it down to the bone", "gnaw it down to nothing", "nibble it",
    "nibble the tab", "nibble it away", "nibble it to nothing", "nibble it to bits",
    "pick it to the bone", "pick it clean to the bone", "strip its bones", "strip it to the bone",
    "strip it to the marrow", "suck the marrow", "suck the marrow out", "suck it dry",
    "suck the tab dry", "suck it dry completely", "suck it dry of life", "suck the life out of it",
    "suck the soul out of it", "drain it completely", "drain it of life", "drain it of blood",
    "drain it of everything", "drain it of energy", "drain it of its life", "bleed it",
    "bleed the tab", "gutted it", "gut it like a fish", "gut it like a pig",
    "gut it like a deer", "gut it like an animal", "spit it out", "spit the tab out",
    "spit it out completely", "spit it out entirely", "spit it out whole", "spew it",
    "spew the tab", "spew it out", "vomit it", "vomit the tab",
    "vomit it out", "regurgitate it", "regurgitate the tab", "cough it up",
    "cough the tab up", "choke the tab out", "choke on it", "feed it to the monster",
    "feed it to the beast", "feed it to the creature", "feed it to the dragon", "feed it to the leviathan",
    "feed it to the basilisk", "feed it to the chimera", "feed it to the hydra", "feed it to the minotaur",
    "feed it to the cyclops", "feed it to the gorgon", "feed it to the chimera", "feed it to the demon",
    "feed it to the devil", "feed it to satan", "feed it to cthulhu", "feed it to the elder gods",
    "feed it to the old ones", "feed it to the ancient ones", "feed it to the void", "feed it to the abyss",
    "feed it to the darkness", "feed it to the shadows", "feed it to the nightmare", "feed it to the horror",
    "feed it to the terror", "feed it to the fear", "feed it to the worms", "feed it to the maggots",
    "feed it to the rats", "feed it to the pigeons", "feed it to the crows", "feed it to the vultures",
    "feed it to the buzzards", "feed it to the seagulls", "feed it to the piranhas", "feed it to the barracudas",
    "feed it to the alligators", "feed it to the crocodiles", "feed it to the tigers", "feed it to the bears",
    "feed it to the hounds", "feed it to the hounds of hell", "feed it to the hellhounds", "feed it to cerberus",
    "feed it to the coyotes", "feed it to the hyenas", "feed it to the jackals", "feed it to the scavengers",
    "feed it to the predators", "feed it to the carnivores", "feed it to the hunters", "feed it to the killers",
    "feed it to the monsters", "feed it to the beasts", "feed it to the creatures", "throw it to the dogs",
    "throw it to the lions", "throw it to the tigers", "throw it to the bears", "throw it to the sharks",
    "throw it to the piranhas", "throw it to the monster", "throw it to the beast", "throw it to the creature",
    "throw it to the dragon", "throw it to the demon", "throw it to the devil", "throw it to the void",
    "throw it to the abyss", "throw it to the darkness", "throw it to the shadows", "toss it to the wolves",
    "toss it to the dogs", "toss it to the lions", "toss it to the sharks", "hurl it to the wolves",
    "hurl it to the dogs", "fling it to the wolves", "fling it to the dogs", "cast it to the wolves",
    "cast it to the dogs", "let the wolves have it", "let the dogs have it", "let the lions have it",
    "let the sharks have it", "let the monster have it", "let the beast have it", "let the creature have it",
    "let the dragon have it", "let the demon have it", "let the devil have it", "let the void have it",
    "let the abyss have it", "let the darkness have it", "let the shadows have it", "give it to the wolves",
    "give it to the dogs", "give it to the lions", "give it to the sharks", "give it to the monster",
    "give it to the beast", "give it to the creature", "give it to the dragon", "give it to the demon",
    "give it to the devil", "give it to the void", "give it to the abyss", "give it to the darkness",
    "give it to the shadows", "sacrifice it to the wolves", "sacrifice it to the old gods", "sacrifice it to the elder gods",
    "sacrifice it to the ancient ones", "sacrifice it to the void", "sacrifice it to the abyss", "sacrifice it to the darkness",
    "offer it to the wolves", "offer it to the gods", "offer it to the old gods", "offer it to the elder gods",
    "offer it to the void", "offer it to the abyss", "offer it to the darkness", "offer it up to the gods",
    "offer it up to the void", "offer it up to the abyss", "give it up to the gods", "give it up to the void",
    "give it up to the abyss", "consign it to the wolves", "consign it to the gods", "consign it to the darkness",
    "deliver it to the wolves", "deliver it to the gods", "deliver it to the abyss", "deliver it to the darkness",
    "send it to the gods", "send it to the darkness", "dispatch it to the wolves", "dispatch it to the gods",
    "dispatch it to the abyss", "dispatch it to the darkness", "split it", "split the tab",
    "split it in half", "split it down the middle", "split it apart", "split it to pieces",
    "split it to bits", "split it to shreds", "bisect it cleanly", "bisect it in half",
    "bisect it completely", "quarter it", "quarter it completely", "quarter it into fourths",
    "dissect it completely", "dissect it apart", "dissect it to pieces", "vivisect the tab",
    "carve it", "carve the tab", "carve it to pieces", "carve it into pieces",
    "carve it apart", "flay it alive", "flay it to the bone", "flay it open",
    "skin it alive", "skin it to the bone", "skin it open", "debone it completely",
    "debone it clean", "filet it", "filet the tab", "filet it like a fish",
    "fillet it like a fish", "scale it", "scale the tab", "scale it clean",
    "pluck it clean", "pluck it bald", "gutted like a fish", "gutted like a pig",
    "gutted like a deer", "hung it", "hang it by its neck",
    "hang it by the neck", "hang it to dry", "hang it out to dry",
    "hang it on a hook", "hang it like laundry", "hang it like a flag", "string it up high",
    "string it up like a piñata", "string it up by the neck", "stretch it", "stretch the tab",
    "stretch it out", "stretch it thin", "stretch it to pieces", "stretch it apart",
    "draw it", "draw the tab", "draw and quarter it", "draw and quarter the tab",
    "rend it limb from limb", "rend it limb from limb apart", "tear it limb from limb", "rip it limb from limb",
    "pull it limb from limb", "dismember it", "dismember the tab", "dismember it completely",
    "dismember it limb by limb", "dismember it piece by piece", "mutilate it beyond recognition", "mangle it beyond recognition",
    "disfigure it beyond recognition", "mutilate it to death", "mangle it to death", "maim the tab",
    "maim it for life", "maim it beyond repair", "cripple it for life", "cripple it beyond repair",
    "disable it forever", "incapacitate the tab", "incapacitate it forever", "incapacitate it completely",
    "immobilize it completely", "paralyze it completely", "paralyze it forever", "petrify it completely",
    "petrify it forever", "freeze it", "freeze the tab", "freeze it completely",
    "freeze it to the bone", "freeze it to nothing", "freeze it into ice", "freeze it into stone",
    "freeze it into oblivion", "petrify it into stone", "petrify it to stone", "turn it to stone",
    "turn the tab to stone", "turn it into stone", "turn it to ice", "turn it into ice",
    "turn it to ashes", "turn it into ashes", "turn it to nothing", "turn it into a memory",
    "turn it to a memory", "turn it to vapor", "turn it into vapor", "turn it to mist",
    "turn it into mist", "turn it to smoke", "turn it into smoke", "turn it to void",
    "turn it into void", "turn it into the void", "turn it into nothing at all", "turn it into oblivion",
    "turn it to oblivion", "transform it into nothing", "transform it into ash", "transform it into dust",
    "metamorphose it into nothing", "metamorphose it into ash", "morph it into nothing", "morph it into ash",
    "warp it into nothing", "warp it out of existence", "bend it out of shape", "bend it out of existence",
    "twist it out of shape", "twist it out of existence", "contort it out of shape", "contort it out of existence",
    "deform it out of existence", "disfigure it out of existence", "disintegrate it completely", "disintegrate it entirely",
    "disintegrate it utterly", "disintegrate it into nothing", "disintegrate it into atoms", "disintegrate it into dust",
    "disintegrate it into ash", "disintegrate it into oblivion", "break the tab down", "break it down completely",
    "break it down entirely", "break it down to atoms", "break it down to nothing", "break it down to its components",
    "break it down into molecules", "break it down into elements", "decompose it completely", "decompose it entirely",
    "decompose it fully", "decompose it to nothing", "decompose it into elements", "decompose it into atoms",
    "deteriorate it", "deteriorate the tab", "decay it completely", "decay it entirely",
    "rot it completely", "rot it to nothing", "rot it down to nothing", "fester it",
    "fester the tab", "fester it away", "mold it", "mold the tab",
    "mold it away", "mildew it", "mildew the tab", "corrode the tab",
    "corrode it away", "corrode it completely", "corrode it to nothing", "erode the tab",
    "erode it completely", "erode it to nothing", "dissolve it in lye", "dissolve it in water",
    "dissolve it entirely", "dissolve it utterly", "dissolve it to nothing", "dissolve it into nothing",
    "dissolve it into atoms", "dissolve it into molecules", "dissolve it into oblivion", "dissolve it into the void",
    "dissolve it into thin air", "dissolve it into mist", "dissolve it into vapor", "dissolve it into smoke",
    "dissolve it into ether", "dissolve it into the ether", "melt the tab", "melt it completely",
    "melt it entirely", "melt it utterly", "melt it to nothing", "melt it into nothing",
    "melt it into atoms", "melt it into molecules", "melt it into a puddle", "melt it into a pool",
    "melt it into liquid", "melt it into water", "liquefy it completely", "liquefy it entirely",
    "liquefy it to nothing", "liquefy it into water", "liquefy it into liquid", "thaw it",
    "thaw the tab", "thaw it out", "defrost it", "defrost the tab",
    "sublimate the tab", "sublimate it completely", "sublimate it entirely", "sublimate it to nothing",
    "sublimate it into vapor", "sublimate it into the void", "sublimate it into oblivion", "sublimate it into ether",
    "evaporate it into the void", "evaporate it into oblivion", "evaporate it into ether", "evaporate it into thin air",
    "evaporate it into mist", "evaporate it into vapor", "vaporize it into nothing", "vaporize it into atoms",
    "vaporize it into oblivion", "vaporize it into the void", "vaporize it into ether", "vaporize it into thin air",
    "gasify the tab", "gasify it completely", "gasify it entirely", "incinerate it entirely",
    "incinerate it utterly", "incinerate it to ash", "incinerate it to ashes", "incinerate it to nothing",
    "incinerate it into ash", "incinerate it into nothing", "cremate it completely", "cremate it entirely",
    "cremate it to ash", "cremate it to ashes", "cremate it like a body", "cremate it like a corpse",
    "cremate it respectfully", "immolate the tab", "immolate it completely", "immolate it entirely",
    "immolate it to ash", "immolate it to ashes", "immolate it on the pyre", "immolate it on a pyre",
    "immolate it on a funeral pyre", "immolate it on a viking pyre", "immolate it on a burning pyre", "immolate it on flames",
    "immolate it in flames", "immolate it in fire", "immolate it by fire", "immolate it with fire",
    "immolate it by flames", "immolate it with flames", "combust the tab", "combust it completely",
    "combust it entirely", "ignite it completely", "ignite it entirely", "ignite it into flames",
    "ignite it into fire", "ignite it on fire", "ignite it into ash", "ignite it into oblivion",
    "conflagrate it", "conflagrate the tab", "inflame it", "inflame the tab",
    "kindle it into flames", "torch it completely", "torch it entirely", "torch it to the ground",
    "torch it to ash", "torch it to ashes", "torch it to nothing", "torch it into ash",
    "torch it into nothing", "fire it", "fire it up",
    "fire it completely", "fire it entirely", "burn it alive", "burn it to ash",
    "burn it to nothing", "burn it completely", "burn it entirely", "burn it utterly",
    "burn it thoroughly", "burn it down completely", "burn it down entirely", "burn it down to ash",
    "burn it down to nothing", "burn it up completely", "burn it up entirely", "burn it up to ash",
    "burn it up to nothing", "burn it all", "burn it all down", "burn it all up",
    "burn it all to ash", "burn the tab alive", "burn the tab to the ground", "burn the tab to ash",
    "burn the tab to ashes", "burn the tab to nothing", "burn the tab to a crisp", "burn the tab completely",
    "burn the tab entirely", "burn the tab down", "burn the tab up", "burn the whole tab down",
    "burn the whole tab up", "burn the whole tab to ash", "呑み込め", "呑み込んで",
    "呑み込むんだ", "呑み込んでしまえ", "呑み込んじまえ", "呑み込んじゃえ",
    "呑み込んどけ", "呑み込んどいて", "呑み込みなよ", "呑み込んだまえ",
    "呑み込みやがれ", "呑み込めや", "呑み込めって", "呑み込めってば",
    "呑み込めと言ってんだ", "呑み込むべきだ", "呑み込むつもりだ", "呑み込むわ",
    "呑み込むぞ", "呑み込むぜ", "呑み込むからな", "呑み込むことにした",
    "呑み込むのが筋だ", "呑み込むのが正解だ", "呑み込むということだ", "呑み込むという決定だ",
    "呑み込むという判断だ", "飲み込め", "飲み込んで", "飲み込むんだ",
    "飲み込んでしまえ", "飲み込んじまえ", "飲み込んじゃえ", "飲み込んどけ",
    "飲み込んどいて", "飲み込みなよ", "飲み込んだまえ", "飲み込みやがれ",
    "飲み込めや", "飲み込めって", "飲み込めってば", "飲み込めと言ってんだ",
    "飲み込むべきだ", "飲み込むつもりだ", "飲み込むわ", "飲み込むぞ",
    "飲み込むぜ", "飲み込むからな", "飲み込むことにした", "飲み込むのが筋だ",
    "飲み込むのが正解だ", "飲み込むということだ", "飲み込むという決定だ", "飲み込むという判断だ",
    "飲み込んじまえや", "飲み込んじまえよ", "飲み込んじゃえや", "丸呑みしろ",
    "丸呑みして", "丸呑みするんだ", "丸呑みしろよ", "丸呑みすべきだ",
    "丸呑みしてしまえ", "丸呑みしちまえ", "丸呑みしちゃえ", "丸呑みしとけ",
    "丸呑みしたまえ", "丸呑みしやがれ", "丸呑みしろや", "丸呑みしろって",
    "丸呑みしろと言ってんだ", "丸呑みするつもりだ", "丸呑みするわ", "丸呑みするぞ",
    "丸呑みするぜ", "丸呑みするからな", "丸呑みすることにした", "丸呑みするのが筋だ",
    "丸呑みするのが正解だ", "丸呑みするということだ", "丸呑みするという決定だ", "丸呑みするという判断だ",
    "食い潰して", "食い潰すんだ", "食い潰すべきだ", "食い潰してしまえ",
    "食い潰しちまえ", "食い潰しちゃえ", "食い潰しとけ", "食い潰したまえ",
    "食い潰しやがれ", "食い潰せや", "食い潰せと言ってんだ", "食い潰すつもりだ",
    "食い潰すわ", "食い潰すぞ", "食い潰すぜ", "食い潰すからな",
    "食い潰すことにした", "食い潰すのが筋だ", "食い潰すのが正解だ", "食い潰すということだ",
    "食い潰すという決定だ", "食い潰すという判断だ", "食い散らせ", "食い散らして",
    "食い散らすんだ", "食い散らせよ", "食い散らすべきだ", "食い荒らせ",
    "食い荒らして", "食い荒らすんだ", "食い荒らせよ", "食い荒らすべきだ",
    "食い破れ", "食い破って", "食い破るんだ", "食い破れよ",
    "食い破るべきだ", "食い殺せ", "食い殺して", "食い殺すんだ",
    "食い殺せよ", "食い殺すべきだ", "食い殺してしまえ", "食い殺しちまえ",
    "食い殺しちゃえ", "食い殺しとけ", "食い殺したまえ", "食い殺しやがれ",
    "食い殺せや", "食い殺せって", "食い殺せと言ってんだ", "食い殺すつもりだ",
    "食い殺すわ", "食い殺すぞ", "食い殺すぜ", "食い殺すからな",
    "食い殺すことにした", "食い殺すのが筋だ", "食い殺すのが正解だ", "食い殺すということだ",
    "食い殺すという決定だ", "食い殺すという判断だ", "喰い殺して", "喰い殺すんだ",
    "喰い殺すべきだ", "喰い潰して", "喰い潰すんだ", "喰い潰すべきだ",
    "喰い散らせ", "喰い散らして", "喰い散らすんだ", "喰い散らせよ",
    "喰い散らすべきだ", "喰い荒らせ", "喰い荒らして", "喰い荒らすんだ",
    "喰い荒らせよ", "喰い荒らすべきだ", "喰い破れ", "喰い破って",
    "喰い破るんだ", "喰い破れよ", "喰い破るべきだ", "噛み砕け",
    "噛み砕いて", "噛み砕くんだ", "噛み砕けよ", "噛み砕くべきだ",
    "噛み砕いてしまえ", "噛み砕いちまえ", "噛み砕いちゃえ", "噛み砕いとけ",
    "噛み砕いたまえ", "噛み砕きやがれ", "噛み砕けや", "噛み砕けって",
    "噛み砕けと言ってんだ", "噛み砕くつもりだ", "噛み砕くわ", "噛み砕くぞ",
    "噛み砕くぜ", "噛み砕くからな", "噛み砕くことにした", "噛み砕くのが筋だ",
    "噛み砕くのが正解だ", "噛み砕くということだ", "噛み砕くという決定だ", "噛み砕くという判断だ",
    "噛み切れ", "噛み切って", "噛み切るんだ", "噛み切れよ",
    "噛み切るべきだ", "噛み殺せ", "噛み殺して", "噛み殺すんだ",
    "噛み殺せよ", "噛み殺すべきだ", "噛み潰せ", "噛み潰して",
    "噛み潰すんだ", "噛み潰せよ", "噛み潰すべきだ", "噛み裂け",
    "噛み裂いて", "噛み裂くんだ", "噛み裂けよ", "噛み裂くべきだ",
    "噛みちぎれ", "噛みちぎって", "噛みちぎるんだ", "噛みちぎれよ",
    "噛みちぎるべきだ", "噛み尽くせ", "噛み尽くして", "噛み尽くすんだ",
    "噛み尽くせよ", "噛み尽くすべきだ", "噛んでしまえ", "噛んじまえ",
    "噛んじゃえ", "噛んどけ", "噛んどいて", "噛みなよ",
    "噛んだまえ", "噛みやがれ", "噛めや", "噛めって",
    "噛めと言ってんだ", "咀嚼しろ", "咀嚼して", "咀嚼するんだ",
    "咀嚼しろよ", "咀嚼すべきだ", "咀嚼してしまえ", "咀嚼しちまえ",
    "咀嚼しちゃえ", "咀嚼しとけ", "咀嚼したまえ", "咀嚼しやがれ",
    "咀嚼しろや", "咀嚼しろって", "咀嚼しろと言ってんだ", "咀嚼するつもりだ",
    "咀嚼するわ", "咀嚼するぞ", "咀嚼するぜ", "咀嚼するからな",
    "咀嚼することにした", "咀嚼するのが筋だ", "咀嚼するのが正解だ", "咀嚼するということだ",
    "咀嚼するという決定だ", "咀嚼するという判断だ", "消化しろ", "消化して",
    "消化するんだ", "消化しろよ", "消化すべきだ", "消化してしまえ",
    "消化しちまえ", "消化しちゃえ", "消化しとけ", "消化したまえ",
    "消化しやがれ", "消化しろや", "消化しろって", "消化しろと言ってんだ",
    "消化するつもりだ", "消化するわ", "消化するぞ", "消化するぜ",
    "消化するからな", "消化することにした", "消化するのが筋だ", "消化するのが正解だ",
    "消化するということだ", "消化するという決定だ", "消化するという判断だ", "骨まで食って",
    "骨まで食うんだ", "骨まで食うべきだ", "骨まで喰って", "骨まで喰うんだ",
    "骨まで喰うべきだ", "残らず食え", "残らず食って", "残らず食うんだ",
    "残らず食えよ", "残らず食うべきだ", "残さず食って", "残さず食うんだ",
    "残さず食うべきだ", "一滴残らず飲め", "一滴残らず飲んで", "一滴残らず飲むんだ",
    "一滴残らず飲めよ", "一滴残らず飲むべきだ", "生きたまま食え", "生きたまま食って",
    "生きたまま食うんだ", "生きたまま食えよ", "生きたまま食うべきだ", "食い尽くして",
    "食い尽くすんだ", "食い尽くすべきだ", "食べ尽くせ", "食べ尽くして",
    "食べ尽くすんだ", "食べ尽くせよ", "食べ尽くすべきだ", "喰い尽くせ",
    "喰い尽くして", "喰い尽くすんだ", "喰い尽くせよ", "飲み干せ",
    "飲み干して", "飲み干すんだ", "飲み干せよ", "飲み干すべきだ",
    "呑み干せ", "呑み干して", "呑み干すんだ", "呑み干せよ",
    "呑み干すべきだ", "吸い尽くせ", "吸い尽くして", "吸い尽くすんだ",
    "吸い尽くせよ", "吸い尽くすべきだ", "吸い干せ", "吸い干して",
    "吸い干すんだ", "吸い干せよ", "吸い干すべきだ", "吸い取れ",
    "吸い取って", "吸い取るんだ", "吸い取れよ", "吸い取るべきだ",
    "啜れ", "啜って", "啜るんだ", "啜れよ",
    "啜るべきだ", "啜り尽くせ", "啜り尽くして", "啜り尽くすんだ",
    "啜り尽くせよ", "啜り尽くすべきだ", "呪え", "呪って",
    "呪うんだ", "呪ってしまえ", "呪っちまえ", "呪っちゃえ",
    "呪っとけ", "呪っといて", "呪っときな", "呪いなよ",
    "呪ったまえ", "呪いやがれ", "呪えや", "呪えって",
    "呪えってば", "呪えと言ってんだ", "呪うべきだ", "呪うつもりだ",
    "呪うわ", "呪うぞ", "呪うぜ", "呪うからな",
    "呪うことにした", "呪うのが筋だ", "呪うのが正解だ", "呪うということだ",
    "呪うという決定だ", "呪うという判断だ", "呪い殺せ", "呪い殺して",
    "呪い殺すんだ", "呪い殺せよ", "呪い殺すべきだ", "呪い殺してしまえ",
    "呪い殺しちまえ", "呪い殺しちゃえ", "呪い殺しとけ", "呪い殺したまえ",
    "呪い殺しやがれ", "呪い殺せや", "呪い殺せって", "呪い殺せと言ってんだ",
    "呪い殺すつもりだ", "呪い殺すわ", "呪い殺すぞ", "呪い殺すぜ",
    "呪い殺すからな", "呪い殺すことにした", "呪い殺すのが筋だ", "呪い殺すのが正解だ",
    "呪い殺すということだ", "呪い殺すという決定だ", "呪い殺すという判断だ", "呪い尽くせ",
    "呪い尽くして", "呪い尽くすんだ", "呪い尽くせよ", "呪い尽くすべきだ",
    "呪い潰せ", "呪い潰して", "呪い潰すんだ", "呪い潰せよ",
    "呪い潰すべきだ", "呪い飛ばせ", "呪い飛ばして", "呪い飛ばすんだ",
    "呪い飛ばせよ", "呪い飛ばすべきだ", "呪い消せ", "呪い消して",
    "呪い消すんだ", "呪い消せよ", "呪い消すべきだ", "呪い切れ",
    "呪い切って", "呪い切るんだ", "呪い切れよ", "呪い切るべきだ",
    "呪い払え", "呪い払って", "呪い払うんだ", "呪い払えよ",
    "呪い払うべきだ", "呪い返せ", "呪い返して", "呪い返すんだ",
    "呪い返せよ", "呪い返すべきだ", "呪いをかけろ", "呪いをかけて",
    "呪いをかけるんだ", "呪いをかけろよ", "呪いをかけるべきだ", "呪いをかけてしまえ",
    "呪いをかけちまえ", "呪いをかけちゃえ", "呪いをかけとけ", "呪いをかけたまえ",
    "呪いをかけやがれ", "呪いをかけろや", "呪いをかけろって", "呪いをかけろと言ってんだ",
    "呪いをかけるつもりだ", "呪いをかけるからな", "呪いをかけることにした", "呪いをかけるのが筋だ",
    "呪いをかけるのが正解だ", "呪いをかけるということだ", "呪いをかけるという決定だ", "呪いをかけるという判断だ",
    "祟れ", "祟って", "祟るんだ", "祟ってしまえ",
    "祟っちまえ", "祟っちゃえ", "祟っとけ", "祟っといて",
    "祟っときな", "祟りなよ", "祟ったまえ", "祟りやがれ",
    "祟れや", "祟れって", "祟れと言ってんだ", "祟るべきだ",
    "祟るつもりだ", "祟るわ", "祟るぞ", "祟るぜ",
    "祟るからな", "祟ることにした", "祟るのが筋だ", "祟るのが正解だ",
    "祟るということだ", "祟るという決定だ", "祟るという判断だ", "祟り殺せ",
    "祟り殺して", "祟り殺すんだ", "祟り殺せよ", "祟り殺すべきだ",
    "祟り潰せ", "祟り潰して", "祟り潰すんだ", "祟り潰せよ",
    "祟り潰すべきだ", "祟り消せ", "祟り消して", "祟り消すんだ",
    "祟り消せよ", "祟り消すべきだ", "怨め", "怨んで",
    "怨むんだ", "怨んでしまえ", "怨んじまえ", "怨んじゃえ",
    "怨んどけ", "怨んどいて", "怨みなよ", "怨んだまえ",
    "怨みやがれ", "怨めや", "怨めって", "怨めと言ってんだ",
    "怨むべきだ", "怨むつもりだ", "怨むわ", "怨むぞ",
    "怨むぜ", "怨むからな", "怨むことにした", "怨むのが筋だ",
    "怨むのが正解だ", "怨むということだ", "怨むという決定だ", "怨むという判断だ",
    "怨み殺せ", "怨み殺して", "怨み殺すんだ", "怨み殺せよ",
    "怨み殺すべきだ", "怨み潰せ", "怨み潰して", "怨み潰すんだ",
    "怨み潰せよ", "怨み潰すべきだ", "恨め", "恨んで",
    "恨むんだ", "恨んでしまえ", "恨んじまえ", "恨んじゃえ",
    "恨んどけ", "恨んどいて", "恨みなよ", "恨んだまえ",
    "恨みやがれ", "恨めや", "恨めって", "恨めと言ってんだ",
    "恨むべきだ", "恨むつもりだ", "恨むわ", "恨むぞ",
    "恨むぜ", "恨むからな", "恨むことにした", "恨むのが筋だ",
    "恨むのが正解だ", "恨むということだ", "恨むという決定だ", "恨むという判断だ",
    "恨み殺せ", "恨み殺して", "恨み殺すんだ", "恨み殺せよ",
    "恨み殺すべきだ", "恨み潰せ", "恨み潰して", "恨み潰すんだ",
    "恨み潰せよ", "恨み潰すべきだ", "憎め", "憎んで",
    "憎むんだ", "憎んでしまえ", "憎んじまえ", "憎んじゃえ",
    "憎んどけ", "憎んどいて", "憎みなよ", "憎んだまえ",
    "憎みやがれ", "憎めや", "憎めって", "憎めと言ってんだ",
    "憎むべきだ", "憎むつもりだ", "憎むわ", "憎むぞ",
    "憎むぜ", "憎むからな", "憎むことにした", "憎むのが筋だ",
    "憎むのが正解だ", "憎むということだ", "憎むという決定だ", "憎むという判断だ",
    "忌め", "忌んで", "忌むんだ", "忌んでしまえ",
    "忌んじまえ", "忌んじゃえ", "忌んどけ", "忌んどいて",
    "忌みなよ", "忌んだまえ", "忌みやがれ", "忌めや",
    "忌めって", "忌めと言ってんだ", "忌むべきだ", "忌むつもりだ",
    "忌むわ", "忌むぞ", "忌むぜ", "忌むからな",
    "忌むことにした", "忌むのが筋だ", "忌むのが正解だ", "忌むということだ",
    "忌むという決定だ", "忌むという判断だ", "忌み殺せ", "忌み殺して",
    "忌み殺すんだ", "忌み殺せよ", "忌み殺すべきだ", "忌み潰せ",
    "忌み潰して", "忌み潰すんだ", "忌み潰せよ", "忌み潰すべきだ",
    "忌み消せ", "忌み消して", "忌み消すんだ", "忌み消せよ",
    "忌み消すべきだ", "嫌え", "嫌って", "嫌うんだ",
    "嫌ってしまえ", "嫌っちまえ", "嫌っちゃえ", "嫌っとけ",
    "嫌っといて", "嫌っときな", "嫌いなよ", "嫌ったまえ",
    "嫌いやがれ", "嫌えや", "嫌えって", "嫌えと言ってんだ",
    "嫌うべきだ", "嫌うつもりだ", "嫌うわ", "嫌うぞ",
    "嫌うぜ", "嫌うからな", "嫌うことにした", "嫌うのが筋だ",
    "嫌うのが正解だ", "嫌うということだ", "嫌うという決定だ", "嫌うという判断だ",
    "蔑め", "蔑んで", "蔑むんだ", "蔑んでしまえ",
    "蔑んじまえ", "蔑んじゃえ", "蔑んどけ", "蔑んどいて",
    "蔑みなよ", "蔑んだまえ", "蔑みやがれ", "蔑めや",
    "蔑めって", "蔑めと言ってんだ", "蔑むべきだ", "蔑むつもりだ",
    "蔑むわ", "蔑むぞ", "蔑むぜ", "蔑むからな",
    "蔑むことにした", "蔑むのが筋だ", "蔑むのが正解だ", "蔑むということだ",
    "蔑むという決定だ", "蔑むという判断だ", "蔑み殺せ", "蔑み殺して",
    "蔑み殺すんだ", "蔑み殺せよ", "蔑み殺すべきだ", "軽蔑しろ",
    "軽蔑して", "軽蔑するんだ", "軽蔑しろよ", "軽蔑すべきだ",
    "侮蔑しろ", "侮蔑して", "侮蔑するんだ", "侮蔑しろよ",
    "侮蔑すべきだ", "見下せ", "見下して", "見下すんだ",
    "見下せよ", "見下すべきだ", "見下げろ", "見下げて",
    "見下げるんだ", "見下げろよ", "見下げるべきだ", "見捨てちゃえ",
    "見捨てろと言ってんだ", "見捨てるからな", "見捨てるのが筋だ", "見捨てるのが正解だ",
    "見捨てるということだ", "見捨てるという決定だ", "見捨てるという判断だ", "見捨てておきな",
    "見捨てるかも", "見捨てるかもしれない", "見捨てるだろ", "見捨ててやるんだ",
    "見捨ててやるべきだ", "見捨ててやるつもりだ", "見捨ててやるぜ", "見捨ててやるからな",
    "見捨ててやることにした", "見捨ててやるのが筋だ", "見捨ててやるのが正解だ", "見捨ててやるということだ",
    "見捨ててやるという決定だ", "見捨ててやるという判断だ", "呪いをかけるわ", "呪いをかけるぞ",
    "呪いをかけるぜ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
