// pass DCCXLVIII: doll & festival-figure domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLVIII: doll & festival-figure domain (ningyou)', () => {
  const closeTab = ['doll maker licensed', 'ningyo artisan certified', 'hina master registered'];
  const closeTabJa = [
    '雛人形',
    '五月人形',
    '市松人形',
    'こけし',
    '伝統こけし',
    '創作こけし',
    'こけし工人',
    'こけしの頭',
    'こけし絵付け',
    '鳴子',
    '木地挽き',
    '博多人形',
    '奈良一刀彫',
    '一刀彫',
    '御所人形',
    '衣装人形',
    'からくり人形',
    '木目込み人形',
    '木目込人形',
    '桐塑人形',
    '桐塑',
    '胡粉',
    '胡粉仕上げ',
    '膠',
    '面相筆',
    '面相',
    '目入れ',
    'ガラス目',
    '開眼',
    '植毛',
    '植髪',
    '人形衣裳',
    '雛衣裳',
    '着せ付け',
    '裂地',
    '金襴',
    '西陣裂地',
    '緞子',
    '繻子',
    'ちりめん',
    '友禅裂地',
    '冠',
    '烏帽子',
    '袍',
    '直衣',
    '狩衣',
    '小袿',
    '五衣',
    '唐衣',
    '表着',
    '裳',
    '袴',
    '帯',
    '笏',
    '檜扇',
    '蝙蝠扇',
    '内裏雛',
    '親王飾り',
    '男雛',
    '女雛',
    '立雛',
    '座雛',
    '京雛',
    '関東雛',
    '雛壇',
    '七段飾り',
    '五段飾り',
    '三段飾り',
    '収納飾り',
    'ケース飾り',
    '飾り台',
    '飾り段',
    '床の間飾り',
    '床飾り',
    '三人官女',
    '五人囃子',
    '随身',
    '仕丁',
    '雪洞',
    '堤燈',
    '菱台',
    '菱餅',
    '雛道具',
    '嫁入り道具',
    '御所車',
    '重陽の節句',
    '桃の節句',
    '端午の節句',
    '雛祭り',
    '雛まつり',
    '初節句',
    '節句人形',
    '節句飾り',
    'つるし飾り',
    '吊るし雛',
    'さげもん',
    '傘福',
    '流し雛',
    'ひな流し',
    '雛流し',
    '武者人形',
    '武者絵',
    '武者飾り',
    '鎧飾り',
    '兜飾り',
    '弓太刀飾り',
    '大将飾り',
    '子供大将',
    '真田幸村兜',
    '織田信長兜',
    '徳川家康兜',
    '上杉謙信兜',
    '武田信玄兜',
    '伊達政宗兜',
    '直江兼続兜',
    '鍾馗',
    '鯉のぼり',
    '鯉幟',
    '吹き流し',
    '五色吹流し',
    '幟旗',
    '幟',
    '羽子板',
    '破魔弓',
    '破魔矢',
    '正月飾り',
    '鏡餅',
    '門松',
    '注連飾り',
    'しめ縄',
    '玉飾り',
    '羽根突き',
    '人形師',
    '人形工房',
    '人形店',
    '人形問屋',
    '人形卸',
    '人形町',
    '人形市',
    '歳の市',
    '人形供養',
    '人形感謝祭',
    '人形祭り',
    '人形検定',
    '日本人形',
    'フランス人形',
    'ビスクドール',
    'アンティークドール',
    'ドール',
    '球体関節人形',
    '素体',
    'ドールハウス',
    'テディベア',
    'ぬいぐるみ',
    '着せ替え人形',
    '抱き人形',
    '干支人形',
    '干支飾り',
    '獅子頭',
    '獅子舞',
    '張子',
    '張り子',
    'はりこ',
    '三春駒',
    '赤べこ',
    '起き上がり小法師',
    'だるま',
    '達磨',
    '高崎だるま',
    '松川だるま',
    '白河だるま',
    '目入れだるま',
    '福だるま',
    '招き猫',
    'まねき猫',
    '浄瑠璃人形',
    '文楽人形',
    '人形遣い',
    '三人遣い',
    '主遣い',
    '左遣い',
    '足遣い',
    '人形浄瑠璃',
    '文楽',
    '人形劇',
    '腹話術',
    '人形芝居',
    '糸操り人形',
    'マリオネット',
    'パペット',
    '指人形',
    '手袋人形',
    '影絵人形',
    '京人形',
    '久月',
    '吉徳',
    '真多呂',
    '人形塚',
    '人形塗り',
    '人形彩色',
    '人形彫刻',
    '木彫り人形',
    '円空',
    '仏師',
    '仏像彫刻',
    '神像',
    '神像彫刻',
    '寺社彫刻',
    '彫刻刀',
    '鑿彫り',
    '荒彫り',
    '仕上げ彫り',
    '開眼供養',
    '御霊入れ',
    '魂入れ',
    '入魂',
    '開眼式',
    '命宿り',
    '人形の目',
    '黒目',
    '白目',
    '瞼',
    '睫毛',
    '眉',
    '口紅',
    '紅差し',
    '白粉',
    'おしろい',
    '化粧人形',
    '表情付け',
    '仕立て職人',
    '衣裳職人',
    '髪付け',
    '頭髪',
    '三つ折れ',
    '関節人形',
    '可動人形',
    '幼児人形',
    '幼少人形',
    '浮世人形',
    '嵯峨人形',
    '御所人形師',
    '雛匠',
    '節句匠',
    '人形修復',
    '人形修理',
    'お直し',
    '手直し',
    '人形の髪',
    '髪結い',
    '櫛',
    '笄',
    '簪',
    '帯締め',
    '帯揚げ',
    '草履',
    '足袋',
    '装束',
    '装束雛',
    '御雛様',
    'お内裏様',
    'お雛様',
    'おだいりさま',
    '人形かたづけ',
    '人形仕舞い',
    '人形片付け',
    '飾り納め',
    '雛納め',
    '五月納め',
    '節句終わり',
    '人形かざり'
  ];
  const negate = [
    'still awaiting the doll license',
    'still awaiting the figure cert',
    'まだ飾り前',
    'まだ開眼前',
    'これから飾り',
    'まだ衣装着せ前'
  ];
  const nullPins = ['about to visit the doll shop', 'about to file the figure report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
