// Pass CCXLIX: EN apocalypse/biblical + execution + underworld + medical-death + JA destroy/burn/seal/funeral/liberation (pass CCXLIX)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCXLIX: close-tab coverage', () => {
  test.each([
    "the four horsemen for it", "apocalypse it", "apocalypse now", "armageddon it",
    "armageddon for it", "rapture it", "the rapture for it", "judgment day for it",
    "its judgment day", "day of reckoning for it", "its day of reckoning", "doomsday for it",
    "its doomsday", "the end times for it", "end times for it", "gotterdammerung for it",
    "ragnarok it", "ragnarok for it", "valhalla awaits it", "valhalla for it",
    "send it to hades", "send it to hel", "to hel with it", "to hades with it",
    "to hell with it", "to hell with the tab", "into the inferno", "into hades",
    "into oblivion", "to the void with it", "cast it into the abyss", "cast it into oblivion",
    "cast it into the inferno", "cast it into hell", "into the emptiness", "into the nothing",
    "into the darkness forever", "into the outer darkness", "outer darkness for it", "weeping and gnashing for it",
    "gnashing of teeth for it", "lake of fire for it", "into the lake of fire", "the lake of fire",
    "lake of fire", "brimstone for it", "fire and brimstone for it", "fire and brimstone it",
    "smite it with fire", "sodom and gomorrah it", "sodom it", "gomorrah it",
    "sodom and gomorrah for it", "pillar of salt it", "pillar of salt for it", "pillar of salt",
    "plague of locusts on it", "ten plagues on it", "ten plagues for it", "the tenth plague for it",
    "mark of cain for it", "mark of cain it", "cain mark it", "cast it out of eden",
    "cast it from eden", "cast it from paradise", "cast it out of paradise", "expel it from eden",
    "expel it from paradise", "eden no more for it", "paradise lost for it", "paradise lost it",
    "into the wilderness", "into the wilderness with it", "wander the wilderness", "forty years in the wilderness",
    "forty days in the desert", "wandering jew for it", "fly it to the sun", "icarus it",
    "icarus for it", "melt its wings", "clip its wings", "wings clipped",
    "wings clipped for it", "no more flying for it", "grounded forever", "grounded permanently",
    "eternally grounded", "permanently grounded", "hang it by its toes", "hang it upside down",
    "hang it by the thumbs", "hang it by the ears", "stretch it on the rack", "rack it",
    "rack the tab", "the rack", "the wheel", "the iron maiden",
    "iron maiden for it", "iron maiden it", "the guillotine blade", "the guillotine for it",
    "guillotine for it", "guillotine it", "madame guillotine for it", "heads roll",
    "heads will roll for it", "the axe drops", "the axe drops for it", "the axe falls on it",
    "the blade falls", "the blade for it", "hangman for it", "hangman it",
    "the hangman", "the noose", "the noose for it", "noose for it",
    "the gallows", "the gallows for it", "gallows for it", "gallows humor it",
    "the scaffold", "the scaffold for it", "scaffold for it", "the chopping block",
    "the chopping block for it", "chopping block for it", "headsman for it", "the headsman",
    "executioner for it", "the executioner", "the firing squad", "up against the wall",
    "against the wall with it", "blindfold it", "last cigarette for it", "the firing pin",
    "pull the trigger on it", "pull the trigger", "trigger it", "trigger the tab",
    "bang it dead", "shoot it out of the sky", "shoot it out the sky", "mow it down in cold blood",
    "cold blood it", "in cold blood", "cold blooded kill", "cold blooded murder",
    "premeditated kill", "premeditated murder", "murder it in cold blood", "murder one",
    "murder one for it", "first degree murder", "homicide it", "homicide for it",
    "manslaughter for it", "butchered it", "massacre the tab", "carnage it",
    "carnage for it", "bloodbath it", "bloodbath for it", "a bloodbath for it",
    "red wedding it", "red wedding for it", "the red wedding", "game of thrones it",
    "winter is coming for it", "winter came for it", "dracarys it", "dracarys",
    "dracarys for it", "the night king for it", "night king it", "kill it like the night king",
    "valar morghulis", "valar morghulis it", "all men must die", "the many faced god for it",
    "a gift for the many faced god", "faceless man for it", "faceless man it", "the iron price for it",
    "pay the iron price", "iron price it", "salt and smoke for it", "sew it into a bag",
    "sew it into a sack", "sack it in the river", "drown it in the river", "drown it in the lake",
    "drown it in the sea", "drown it in the ocean", "drown it in the river styx", "drown it in the styx",
    "the river styx for it", "charon for it", "charon it", "ferry it across the styx",
    "ferry it across", "the ferryman for it", "the ferryman", "pay the ferryman",
    "pay the ferryman for it", "coin for the ferryman", "coins for the ferryman", "obol for it",
    "an obol for it", "hades for it", "send it to the underworld", "to the underworld with it",
    "the underworld for it", "to the other side", "to the far side", "the far side for it",
    "to the great beyond", "the great beyond for it", "to the undiscovered country", "the undiscovered country for it",
    "undiscovered country", "to the pearly gates", "the pearly gates for it", "pearly gates for it",
    "to saint peter", "saint peter for it", "the pearly gates", "to the gates of heaven",
    "gates of heaven for it", "heaven for it", "send it to heaven", "to heaven with it",
    "angel wings for it", "wings for it", "give it wings", "give it its wings",
    "harp for it", "a harp for it", "halo for it", "a halo for it",
    "white wings for it", "angel choir for it", "the choir invisible", "choir invisible",
    "join the choir invisible", "the big sleep", "big sleep for it", "the long sleep",
    "long sleep for it", "the big sleep for it", "eternal sleep for it", "the eternal rest",
    "eternal rest for it", "rest eternal for it", "rest eternal", "perpetual rest for it",
    "requiescat in pace", "requiescat", "et lux perpetua", "lux perpetua",
    "in paradisum", "in paradisum deducant", "the last trump for it", "last trump",
    "trump of doom for it", "trump of doom", "gabriels trumpet for it", "the reaper for it",
    "grim reaper for it", "the grim reaper", "the grim for it", "death knock for it",
    "the death knock", "the bell tolls", "bell tolls for it", "the bell tolls for it",
    "for whom the bell tolls", "it tolls for thee", "death rattle for it", "the death rattle",
    "last breath for it", "its last breath", "breathes its last", "breathe its last",
    "exhale for it", "final exhale for it", "flatline it", "flatline for it",
    "code blue for it", "code blue", "time of death called", "its time of death",
    "pronounce it dead", "pronounce dead", "declaration of death for it", "sign its death warrant",
    "death warrant for it", "death warrant it", "sign the death warrant", "the death warrant",
    "death sentence for it", "its death sentence", "sentence it", "the sentence is death",
    "sentence is death", "convict it", "convict the tab", "guilty it",
    "guilty verdict for it", "guilty for it", "the verdict is guilty", "verdict is guilty",
    "sentence it to die", "to the chair with it", "the chair for it", "old sparky for it",
    "the electric chair", "electric chair for it", "the gas chamber", "gas chamber for it",
    "lethal injection for it", "the needle for it", "the needle", "needle for it",
    "death certificate for it", "fly it too close", "滅ぼせ", "滅ぼして",
    "滅ぼすんだ", "滅ぼすべき", "滅ぼすべきだ", "滅ぼしたほうがいい",
    "滅ぼせよ", "滅ぼせよう", "滅ぼそう", "滅ぼしたい",
    "滅ぼすといい", "滅ぼすといいぞ", "滅ぼすがいい", "滅ぼすがよい",
    "滅ぼしなさい", "滅ぼしてちょうだい", "滅ぼしてください", "滅ぼしてほしい",
    "滅ぼしてくれ", "滅ぼしてくれないか", "滅ぼしてもらおう", "滅ぼしてもらえる",
    "滅ぼしてもらえないか", "滅ぼしてあげる", "滅ぼしてやる", "滅ぼしてしまえ",
    "滅ぼしてしまうんだ", "滅ぼしてしまいたい", "滅ぼしちまえ", "滅ぼしちゃえ",
    "滅ぼしとけ", "滅ぼしとくんだ", "滅ぼしておけ", "滅ぼしておくんだ",
    "滅ぼしておきたい", "滅ぼしたらどう", "滅ぼしたらいい", "滅ぼしたらどうだ",
    "滅ぼすしかない", "滅ぼすっきゃない", "滅ぼすなら", "滅ぼすなら早く",
    "滅ぼすのだ", "滅ぼすんだぞ", "滅ぼすのです", "滅ぼすのですよ",
    "滅ぼすと決めた", "滅ぼすと決めたぞ", "滅ぼすと決断した", "滅ぼすとの判断だ",
    "滅ぼすという結論だ", "滅ぼすという決定だ", "滅ぼすという方針だ", "滅ぼすという件だ",
    "滅ぼすことになった", "滅ぼすことにした", "滅ぼすことに決めた", "滅ぼそうという話だ",
    "滅ぼせとの命令だ", "滅ぼせとの指示だ", "滅ぼせと言われた", "滅ぼせと言っている",
    "滅ぼせと頼まれた", "滅ぼせと頼んだ", "滅ぼせとお願いした", "滅ぼせよという話だ",
    "滅ぼせようと思う", "滅ぼせようと思います", "滅ぼしたいという話だ", "滅ぼしてみせろ",
    "滅ぼしてみせて", "滅ぼしてみて", "滅ぼしてみろ", "滅ぼしとこう",
    "滅ぼしとこうか", "滅ぼしときゃ", "滅ぼしときゃいい", "滅ぼしちゃおう",
    "滅ぼしてやろう", "滅ぼしてやろうか", "焼き払え", "焼き払って",
    "焼き払うんだ", "焼き払うべき", "焼き払うべきだ", "焼き払ったほうがいい",
    "焼き払えよ", "焼き払おう", "焼き払おうと思う", "焼き払いたい",
    "焼き払うといい", "焼き払うがいい", "焼き払いなさい", "焼き払ってちょうだい",
    "焼き払ってください", "焼き払ってほしい", "焼き払ってくれ", "焼き払ってもらおう",
    "焼き払ってあげる", "焼き払ってやる", "焼き払ってしまえ", "焼き払っちまえ",
    "焼き払っちゃえ", "焼き払っとけ", "焼き払っておけ", "焼き払うしかない",
    "焼き払うっきゃない", "焼き払うのだ", "焼き払うんだぞ", "焼き払うと決めた",
    "焼き払うとの判断だ", "焼き払うという結論だ", "焼き払うという件だ", "焼き払うことになった",
    "焼き払うことにした", "焼き払えとの命令だ", "焼き払えと言われた", "焼き払えと頼まれた",
    "焼き払えと頼んだ", "焼き払ってみせろ", "焼き払ってみて", "焼き払ってみろ",
    "焼き払いだ", "焼き討ちだ", "焼き討ちにしろ", "焼き討ちにしてやれ",
    "焼き討ちせよ", "焼き討ちするんだ", "焼き討ちするぞ", "火を放て",
    "火を放って", "火を放つんだ", "火をつけろ", "火を点けろ",
    "火をつけて", "点火しろ", "点火せよ", "点火だ",
    "点火するんだ", "燃やし尽くせ", "燃やし尽くして", "燃やしつくせ",
    "燃やしつくして", "燃やしてしまえ", "燃やしちまえ", "燃やしちゃえ",
    "燃やしとけ", "燃やしておけ", "燃やすべき", "燃やすべきだ",
    "燃やすんだ", "燃やすしかない", "燃やすっきゃない", "燃やすと決めた",
    "燃やすという件だ", "燃やせとの命令だ", "燃やせと言われた", "燃やせと頼んだ",
    "燃やせという話だ", "燃やしてくれ", "燃やしてほしい", "燃やしてください",
    "燃やしてもらおう", "燃やしてやる", "燃やしてあげる", "燃やしてみせろ",
    "燃やしてみて", "燃やしてみろ", "全焼させろ", "全焼だ",
    "丸焼けにしろ", "丸焼きにしろ", "炭にしろ", "炭にしてやれ",
    "炭にするんだ", "消し炭にしろ", "消し炭だ", "灰にするんだ",
    "塵にしろ", "塵にするんだ", "微塵にしてやれ", "微塵も残さず燃やせ",
    "封殺せよ", "封殺するんだ", "封じちゃえ", "封じるという件だ",
    "封じろとの命令だ", "封じろと言われた", "封じてみせろ", "封印するんだ",
    "封印してしまえ", "封印しておけ", "封印してくれ", "封印してほしい",
    "封印すべきだ", "封印したほうがいい", "封印するしかない", "封印するっきゃない",
    "封印するのだ", "封印すると決めた", "封印しろとの命令だ", "蓋をしてしまえ",
    "蓋してしまえ", "蓋しろ", "蓋しとけ", "塞ぎ込め",
    "塞ぎ込んで", "閉じ込めろ", "閉じ込めて", "閉じ込めるんだ",
    "閉じ込めるべき", "閉じ込めてしまえ", "閉じ込めちまえ", "閉じ込めちゃえ",
    "閉じ込めとけ", "閉じ込めておけ", "閉じ込めるしかない", "閉じ込めるっきゃない",
    "閉じ込めると決めた", "閉じ込めろとの命令だ", "閉じ込めろと言われた", "闇に封じろ",
    "闇に封じて", "闇に封じるんだ", "永久に封じろ",     "永遠に封じろ", "永遠に封じて", "二度と開かないよう封じろ", "二度と開けないよう封じろ",
    "断末魔だ", "断末魔だな", "断末魔をあげた", "断末魔を上げた",
    "断末魔を上げている", "断末魔をあげている", "断末魔が聞こえる", "断末魔の声だ",
    "断末魔の叫びだ", "最期だ", "最期だな", "最期を迎えた",
    "最期を迎えたぞ", "最期の時だ", "最期の時が来た", "最期を遂げた",
    "臨終だ", "臨終だな", "臨終を迎えた", "臨終の間際だ",
    "息を引き取った", "息を引き取ったぞ", "息を引き取ったよ", "絶命しました",
    "事切れた", "事切れたぞ", "事切れたよ", "果てた",
    "果てたぞ", "果てたよ", "果てたな", "終わったようだ",
    "終わったようだな", "終わったもようだ", "終わった模様だ", "終わったもようです",
    "終わりだったな", "終わりだったよ", "終わりだったぞ", "終わったはずだ",
    "もう終わったはずだ", "とっくに終わった", "とっくに終わってる", "とっくに終わっている",
    "とっくの昔に終わった", "とっくの昔に終わってる", "死んだはずだ", "もう死んだはずだ",
    "とっくに死んだ", "とっくに死んでる", "とっくに死んでいる", "死んだも同然だ",
    "死んだも同然", "死んだに等しい", "死んだに等しいよ", "死んだも同然だよ",
    "死んだものと思え", "死んだものと思って", "死んだものと思ってくれ", "死んだもんだと思え",
    "過去のものになった", "過去のものとなった", "過去のものだ", "過去のものだよ",
    "過去の産物だ", "過去の遺物となった", "過去の遺物になった", "歴史の一部になった",
    "歴史の一部となった", "歴史になった", "歴史となった", "歴史の彼方に消えた",
    "歴史の彼方に行った", "歴史の彼方に消えたぞ", "風化した", "風化したな",
    "風化してしまった", "忘却の彼方へ", "忘却の彼方に消えろ", "忘却の彼方に行け",
    "忘却の彼方に消えて", "忘れられるべきだ", "忘れられるべき", "忘れられた存在だ",
    "忘れられた存在", "忘れられたものだ", "忘れられたもの", "忘れられしものだ",
    "忘れられしもの", "過去の亡霊だ", "過去の亡霊", "亡霊だ",
    "亡霊だな", "亡霊になった", "亡霊となった", "幽霊だ",
    "幽霊だな", "幽霊になった", "幽霊となった", "化け物だ",
    "化け物だな", "化物だ", "化物だな", "亡者だ",
    "亡者だな", "亡者になった", "亡者め", "悪霊だ",
    "悪霊だな", "悪霊になった", "怨霊だ", "怨霊だな",
    "怨霊になった", "成仏したまえ", "成仏するんだ", "成仏するがいい",
    "成仏しておくれ", "成仏してくれ", "成仏してほしい", "成仏してください",
    "成仏すべき", "成仏すべきだ", "成仏したほうがいい", "成仏するしかない",
    "成仏するっきゃない", "成仏するのだ", "成仏すると決めた", "成仏するという件だ",
    "成仏しろとの命令だ", "成仏しろと言われた", "成仏しろと頼んだ", "成仏してみせろ",
    "成仏してみて", "成仏してやれ", "南無阿弥陀仏", "南無",
    "なむあみだぶつ", "南無なむ", "南無三", "なむさん",
    "お経をあげろ", "お経を唱えろ", "経をあげろ", "念仏だ",
    "念仏をあげろ", "引導を渡せ", "引導を渡して", "引導を渡すんだ",
    "引導を渡すぞ", "引導だ", "導師だ", "坊主を呼べ",
    "坊主に頼め", "お坊さんを呼べ", "お坊さんに頼め", "お坊さんだ",
    "坊さんだ", "寺に連絡しろ", "寺に連絡して", "お寺に電話しろ",
    "寺に電話して", "弔いの時間だ", "弔い時だ", "弔う時間だ",
    "供養の時間だ", "供養時だ", "供養する時間だ", "供養しておく",
    "葬儀の時間だ", "葬儀時だ", "葬儀をあげろ", "葬式をあげろ",
    "葬式をしろ", "告別式をあげろ", "お別れの時間だ", "見送りの時間だ",
    "見送り時だ", "お見送りだ", "見送りにしろ", "墓を建てろ",
    "墓を建ててやれ", "墓に入れてやれ", "墓碑だ", "墓碑を立てろ",
    "墓石を立てろ", "墓所だ", "墓地に埋めろ", "墓地に埋めてやれ",
    "墓地に入れろ", "墓地行きだ", "墓地に送れ", "墓地に運べ",
    "墓地へ運べ", "霊園だ", "霊園に入れろ", "霊園行きだ",
    "納骨堂だ", "納骨堂に入れろ", "納骨堂行きだ", "納骨するんだ",
    "納棺するんだ", "棺桶行きだ", "棺に収めろ", "棺に収めてやれ",
    "釘を打て", "釘を打って", "棺に釘を打て", "棺に釘を打って",
    "土をかけろ", "土をかけて", "土に還してやれ", "土に還すんだ",
    "土に還すぞ", "塵に還してやれ", "灰に還してやれ", "無に還してやれ",
    "有に還れ", "風に還れ", "風に還してやれ", "水に還れ",
    "水に還してやれ", "海に還れ", "海に還してやれ", "空に還れ",
    "空に還してやれ", "光に還れ", "光に還してやれ", "大地に還れ",
    "大地に還してやれ", "自然に還してやれ", "宇宙に還れ", "宇宙に還してやれ",
    "星に還れ", "星に還してやれ", "星々に還れ", "魂を還せ",
    "魂を還してやれ", "魂を送れ", "魂を送ってやれ", "魂を弔え",
    "魂を弔ってやれ", "魂を鎮めろ", "魂を鎮めてやれ", "魂を救え",
    "魂を救ってやれ", "魂を解放してやれ", "魂を解き放て", "魂を放て",
    "霊を救え", "霊を弔え", "霊を鎮めろ", "霊を鎮めてやれ",
    "英霊にしろ", "英霊になれ", "英霊となれ", "英霊となって",
    "列聖に加えろ", "列聖だ", "祀り上げろ", "祀ってやれ",
    "祀り上げてやれ", "神にしろ", "神にしてやれ", "神格化だ",
    "神格化しろ", "聖人にしろ", "聖人にしてやれ", "聖別だ",
    "聖別しろ", "追悼だ", "追悼しろ", "追悼するんだ",
    "追悼の時間だ", "追悼式だ", "追悼式をあげろ", "追悼会だ",
    "慰霊だ", "慰霊しろ", "慰霊祭だ", "鎮魂しろ",
    "鎮魂祭だ", "鎮魂曲だ", "鎮魂歌だ", "レクイエムだ",
    "レクイエムをあげろ", "アメン", "合掌だ", "合掌しろ",
    "合掌して", "黙祷だ", "黙祷しろ", "黙祷を捧げろ",
    "黙祷を捧げて", "黙祷をささげろ", "黙とうだ", "黙とうしろ",
    "一分の黙祷だ", "一分黙祷だ", "瞑目だ", "瞑目しろ",
    "瞑目して", "瞑目してやれ", "目を閉じろ", "目を閉じて",
    "目を閉じさせろ", "目を閉じさせてやれ", "安らかに", "安らかに眠れ",
    "安らかに眠りなさい", "安らかにお眠り", "安らかにお眠りください", "永眠しろ",
    "永眠して", "永眠せよ", "永眠するんだ", "眠りにつきなさい",
    "楽にさせてやれ", "楽にさせてあげる", "苦しみを終わらせてやれ", "苦しみを終わらせてあげる",
    "苦痛を終わらせてやれ", "苦痛を終わらせてあげる", "痛みを終わらせてやれ", "痛みから解放してやれ",
    "苦痛から解放してやれ", "苦しみから解放だ", "苦痛から解放だ", "解放だ",
    "解放にしろ", "解き放て", "解き放ってやれ", "解き放ってあげる",
    "放ってやれ", "放ってあげる", "逃がしてやれ", "逃がしてあげる",
    "リリースだ", "リリースしろ", "リリースしてやれ", "リリースしてあげる",
    "自由にしてやれ", "自由にしてあげる", "自由だ", "自由だよ",
    "自由になれ", "自由になった", "もう自由だ", "もう自由だよ",
    "解放された", "解放されたぞ", "解放されたよ", "解放されました",
    "救われた", "救われたぞ", "救われたよ", "救われました",
    "往生して", "往生するんだ", "往生してやれ", "往生させてやれ",
    "往生極楽だ", "極楽だ", "極楽へ行け", "極楽に行け",
    "極楽に送れ", "極楽浄土だ", "浄土だ", "浄土へ行け",
    "浄土に行け", "浄土に送れ", "西方浄土だ", "天国だ",
    "天国へ行け", "天国に行け", "天国に送れ", "天国に行かせろ",
    "天国に行かせてやれ", "天国に昇れ", "天国に登れ", "天国に上がれ",
    "天国へ昇れ", "天に召されろ", "天に召されて", "天に召されるんだ",
    "天に召された", "天に召されたぞ", "天に召されました", "昇天して",
    "昇天せよ", "昇天するんだ", "昇天させてやれ", "昇天させてあげる",
    "旅立て", "旅立って", "旅立つんだ", "旅立ちだ",
    "旅立ちの時だ", "旅立ちの時間だ", "旅立つ時間だ", "出発だ",
    "出発の時間だ", "出発時だ", "お別れの時だ", "アバヨだ",
    "あばよだ", "お先だ", "また会う日まで", "またの機会に",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});

describe('pass CCXLIX: vr-exit coverage', () => {
  test.each([
    "終わりでした", "終わりました", "来世で会おう", "来世で会おうぞ",
    "来世で会いましょう", "来世でまた", "次の世で会おう", "次の世で会おうぞ",
    "あの世で会おう", "あの世で会おうぞ", "あの世で会いましょう", "あの世でまた",
    "向こうで会おう", "向こうで会おうぞ", "向こうでまた", "あちらで会おう",
    "あちらで会おうぞ", "あちらでまた", "アバヨ", "あばよ",
    "ごめんだ", "ご免だ", "ご免なさい", "ご免ください",
    "失礼だ", "お別れだ", "お別れです", "お別れでした",
    "お別れだな", "さよならだ", "さよならです", "さよならでした",
    "さよならだな", "さようならだ", "バイバイだ", "ばいばいだ",
    "バイバイです",
  ])('routes %s to vr-exit', (p) => {
    expect(key(mk(), p)).toBe('vr-exit');
  });
});

describe('pass CCXLIX: trouble coverage', () => {
  test.each([
    "滅ぼすべきだった", "滅ぼすべきだったな", "滅ぼしたほうがよかった", "死んだと思っていた",
    "死んだと思ってた", "死んだと思った", "死んだと思ったぞ", "死んだと思ったよ",
    "死んだと思う", "死んだと思うぞ", "死んだと思うよ", "もう死んだと思う",
    "もう死んだと思うよ",
  ])('routes %s to trouble', (p) => {
    expect(key(mk(), p)).toBe('trouble');
  });
});
