import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

const mk = () => {
  const vc = new VoiceCommands({ enabled: true });
  const tm = {
    activeTabId: 't1',
    tabs: [
      { id: 't1', currentTitle: 'A', currentUrl: 'https://a' },
      { id: 't2', currentTitle: 'B', currentUrl: 'https://b' },
      { id: 't3', currentTitle: 'C', currentUrl: 'https://c' },
    ],
    getActiveTab() { return this.tabs.find((t) => t.id === this.activeTabId); },
    closeAllTabs() { return 3; },
    closeTab() {}, pinTab() {}, closeOtherTabs() {},
  };
  vc.connectBrowser({ tabManager: tm, onGoTo: () => {} });
  vc.speak = () => {};
  return vc;
};
const key = (vc, p) => { vc.processCommand(p, 0.9); return vc.lastCommand ? vc.lastCommand.key : null; };

describe('pearl atom sweep — pass CCXL', () => {
  test.each([
    'open fire on it',
    'strike it from the list', 'strike it off the books', 'off the books',
    'expunge it from the record', 'strike it from memory',
    'erase it from memory', 'erase it from existence',
    'bleach it', 'sanitize it', 'purify it', 'disinfect it',
    'fumigate it', 'sterilize it', 'decontaminate it',
    'ostracize it', 'shun it', 'disown it', 'disavow it',
    'renounce it', 'repudiate it', 'divorce it', 'divorce the tab',
    'annul it', 'annul the tab', 'void the tab', 'invalidate it',
    'revoke it', 'revoke the tab', 'rescind it', 'rescind the tab',
    'repeal it', 'repeal the tab', 'abolish it', 'abolish the tab',
    'abrogate it', 'strike down the tab', 'overrule it', 'overrule the tab',
    'quash it', 'quell it', 'suppress it', 'subdue it',
    'sing it to sleep', 'rock it to sleep', 'put it down for a nap',
    'say goodnight to it', 'kiss it goodnight',
    'bid it goodnight', 'bid it adieu', 'bid adieu to it',
    'bid it farewell', 'bid farewell to it', 'bid it good day',
    'bid it good riddance', 'good riddance to it', 'riddance',
    'good riddance to bad rubbish',
    'give it its walking papers', 'give it the pink slip', 'pink slip it',
    'hand it its papers', 'issue its walking papers',
    'serve it papers', 'serve it notice', 'give it notice',
    'out the door with it', 'show it the exit', 'escort it to the exit',
    'walk it to the exit', 'usher it out', 'lead it out',
    'drum it out', 'drum it out of the corps', 'cashier it',
    'banish it to the shadows', 'to the shadow realm', 'shadow realm',
    'banish it to the shadow realm', 'send it to the shadow realm',
    'into the shadow realm',
    'sail into the west', 'grey havens', 'into the west with it',
    'send it to the undying lands', 'sail west',
    'send it to bed', 'tuck it into bed', 'put it down for good',
    'lay it down for good', 'lay it in the ground',
    'inter it', 'inhume it', 'bury it alive',
    'tomb it', 'tomb the tab', 'crypt it', 'crypt the tab', 'mummify it',
    'wax it', 'wax the tab',
    'pump it full of lead', 'fill it with lead', 'fill it with holes',
    'riddle it with holes', 'riddle it with bullets',
    'swiss cheese it', 'make it swiss cheese',
    'ventilate it', 'ventilate the tab',
    'headshot it', 'headshot the tab', 'snipe it', 'snipe the tab',
    'one shot one kill', 'take the shot', 'fire at will', 'shoot to kill',
    'shoot it down', 'shoot the tab down',
    'detonate it', 'detonate the tab', 'explode it', 'explode the tab',
    'put a bullet in it', 'put a bullet in the tab',
    'bullet it', 'bullet the tab',
    'hammer time', 'gavel it', 'bang the gavel', 'court adjourned',
    'case dismissed', 'dismissed with prejudice', 'objection overruled',
    'verdict is in', 'death sentence', 'sentence it to death',
    'send it to the chair', 'electric chair', 'old sparky',
    'send it to old sparky', 'gas chamber it', 'lethal injection',
    'give it the needle', 'hangmans noose',
    'lynch it', 'lynch the tab', 'string it up', 'string the tab up',
    'hoist it by its own petard', 'hoisted by its own petard',
    'firing squad', 'firing squad for it', 'send it to the firing squad',
    'line it up against the wall',
    'last cigarette', 'any last words', 'last words', 'final words',
    'administer last rites', 'last rites for it',
    'viking pyre', 'funeral pyre', 'light the pyre',
    'light the funeral pyre', 'pyre it', 'pyre the tab', 'ash it',
    'reduce it to ashes', 'reduce the tab to ashes', 'turn it to ash',
    'salt the earth', 'scorched earth', 'scorched earth it',
    'leave no trace of it', 'wipe it from existence',
    'strike it from existence', 'blot it from existence',
    'remove it from existence', 'banish it from existence',
    'unmake it', 'unmake the tab', 'unexist it',
    'make it never have been', 'like it never existed',
    'as if it never existed',
    'erase it from history', 'remove it from history',
    'write it out of history', 'damnatio memoriae',
    'memory hole it', 'send it down the memory hole', 'memory hole',
    'unperson it', 'unperson the tab', 'make it an unperson',
    'airbrush it out', 'airbrush it from history',
    'crop it out of the photo', 'strike it from the scrolls',
    'blot it out', 'blot out the tab', 'blot it from the record',
    'chop it in half', 'cut it in half', 'cut it in two',
    'split it in two', 'split the tab in two',
    'bisect it', 'bisect the tab', 'halve it', 'quarter the tab',
    'carve the tab up', 'fillet it', 'fillet the tab',
    'julienne it', 'kabob it', 'kebab it', 'kebab the tab',
    'shishkebab it', 'rotisserie it', 'roast it on a spit',
    'spit roast it', 'braise it', 'broil it',
    'grill it', 'grill the tab', 'barbecue it', 'barbecue the tab',
    'bbq it', 'bbq the tab', 'slow roast it', 'saute it',
    'deep fry it', 'stir fry it', 'sizzle it', 'fricassee it',
    'hamburger it', 'make hamburger of it',
    'make mincemeat of it', 'make mincemeat out of it', 'mincemeat it',
    'feed it to the dogs', 'feed it to the hogs', 'feed it to the pigs',
    'scrap heap', 'throw it on the scrap heap', 'scrap heap for it',
    'consign it to the scrap heap',
    'dustbin of history', 'ash heap of history',
    'dustbin it', 'dustbin the tab', 'wastebasket it',
    'crumple it up', 'crumple the tab up', 'crumple it into a ball',
    'wad it up', 'wad the tab up', 'ball it up', 'ball the tab up',
    'shredder it', 'shredder the tab', 'through the shredder',
    'feed it to the shredder', 'office space it', 'copier treatment',
    'katana it', 'katana the tab', 'seppuku it', 'seppuku the tab',
    'commit seppuku', 'hara kiri it', 'hari kari it',
    'dishonorable discharge', 'dishonorable discharge for it',
    'court martial it', 'court martial the tab',
    'madame guillotine', 'national razor', 'the national razor',
    'to the block', 'send it to the block', 'chopping block',
    'on the chopping block', 'the axe falls', 'heads will roll',
    'lose its head',
    '閉じることを命じる', '閉じることを命じた', '閉じることを命じます',
    '閉じるを命じる', '閉じると命じた', '閉じると命じる',
    '閉じるよう命じた', '閉じるように命じた',
    '閉じるよう指示した', '閉じるよう指示がある',
    '閉じるように頼まれた', '閉じると言われた',
    '閉じるって言われた', '閉じてって言われた', '閉じてって言われてる',
    '閉じてって言われたんだ',
    '閉じるように申し付けられた', '閉じるように申し渡された',
    '閉じるように告げられた', '閉じるようにお達しが出た',
    '閉じるようにお達しがある', '閉じるお達しだ', '閉じるお達しです',
    '閉じる沙汰だ', '閉じる沙汰である', '閉じる沙汰です',
    '閉じる由だ', '閉じる由である', '閉じる由です',
    '閉じる次第だ', '閉じる心づもりだ', '閉じる心づもりである',
    '閉じる心積もり', '閉じる心積もりだ', '閉じる算段だ',
    '閉じる算段である', '閉じる目論見だ', '閉じる目算だ',
    '閉じる目処だ', '閉じる目途だ', '閉じる目星だ', '閉じる目安だ',
    '閉じる目標だ', '閉じる目的だ', '閉じる意図だ', '閉じる狙いだ',
    '閉じる魂胆だ', '閉じる胸中だ', '閉じる胸中です',
    '閉じる腹積もりだ', '閉じる腹づもりだ', '閉じる筋書きだ',
    '閉じる段取りだ', '閉じる手筈だ', '閉じる手はずだ', '閉じる手順だ',
    '閉じる流れだ', '閉じる成り行きだ', '閉じる運びだ',
    '閉じる運びである', '閉じる運びとなった', '閉じる運びになった',
    '閉じる運びとなりました', '閉じる運びになりました',
    '閉じることになったんで', '閉じることになったので',
    '閉じることとなりまして', '閉じることになりまして',
    '閉じるべきものである', '閉じるべき件だ', '閉じるべき件である',
    '閉じるべきものです', '閉じるべきですね', '閉じるべきかと存ず',
    '閉じるべきと判断', '閉じるべきと判断した', '閉じるべきと考える',
    '閉じるべきと存じる', '閉じるべきと考慮', '閉じるべきと思料',
    '閉じるべきと愚考', '閉じるべきと愚考する',
    '閉じるべきと承認', '閉じるべきと承認した',
    '閉じるべきと了承', '閉じるべきと了承した',
    '閉じるべきと決定', '閉じるべきと決定した',
    '閉じるべきに決めました', '閉じるべきに決定した', '閉じるべきに決定です',
    '閉じるべきという結論', '閉じるべきという判断', '閉じるべきという見解',
    '閉じるべきという答え', '閉じるべきという回答',
    '閉じるべきという結論に達した', '閉じるべきという結論です',
    '閉じるべきということになりました', '閉じるべきことになりました',
    '閉じるべきことになった', '閉じるべきこととなった',
    '閉じるべき方向で', '閉じるべき方向です',
    '閉じるべき方向性で', '閉じるべき方向性です',
    '閉じるべき方針で', '閉じるべき方針です',
    '閉じるべき方針ですので', '閉じるべき方針なので',
    '閉じるべき線で', '閉じるべき線でお願い', '閉じるべき線でお願いします',
    '閉じるべき形で', '閉じるべき形でお願い', '閉じるべき形でお願いします',
    '閉じるべき形です', '閉じるべき形となります',
    '閉じるべきということで', '閉じるべきということでお願い',
    '閉じるべきことでお願い', '閉じるべきことでお願いします',
    '閉じるべきという事で', '閉じるべきという件で',
    '閉じるべき件でお願い', '閉じるべき件でお願いします',
    '閉じるべき依頼です', '閉じるべきお願いです', '閉じるべきお願いになります',
    '閉じるべき形でお願い申し上げます', '閉じるべき形でお願いいたします',
    '閉じるべき形でお願い致します', '閉じるべき形でお願いしたい',
    '閉じるべき形でお願いしたいです', '閉じるべき形でお願いしたいんですが',
    '閉じるべき形でお願いするよ', '閉じるべき形でお願いするね',
    '閉じるべき形でお願いするわ',
    '閉じるべき形で頼むよ', '閉じるべき形で頼むわ', '閉じるべき形で頼むね',
    '閉じるべき形で頼みます', '閉じるべき形で頼みますよ',
    '閉じるべき形で頼みますんで', '閉じるべき形で頼みますね',
    '閉じるべき形で頼みますわ',
  ])('%s -> close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
