// Pass CCLXVIII: EN demand/court-order frames + JA 命令文書・判定宣告 (pass CCLXVIII)

import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLXVIII: close-tab coverage', () => {
  test.each([
    "i command it closed", "i command it dead", "i command it destroyed", "i command it discarded",
    "i command it eliminated", "i command it ended", "i command it erased", "i command it finished",
    "i command it gone", "i command it junked", "i command it killed", "i command it obliterated",
    "i command it off", "i command it off my screen", "i command it out of my sight", "i command it removed",
    "i command it scrapped", "i command it shut", "i command it terminated", "i command the tab annihilated",
    "i command the tab axed", "i command the tab binned", "i command the tab closed", "i command the tab closed now",
    "i command the tab cut", "i command the tab dead", "i command the tab destroyed", "i command the tab discarded",
    "i command the tab dismissed", "i command the tab dismissed at once", "i command the tab done", "i command the tab dumped",
    "i command the tab eliminated", "i command the tab ended", "i command the tab eradicated", "i command the tab erased",
    "i command the tab finished", "i command the tab gone", "i command the tab gone now", "i command the tab junked",
    "i command the tab killed", "i command the tab obliterated", "i command the tab off", "i command the tab removed",
    "i command the tab scrapped", "i command the tab shut", "i command the tab terminated", "i decree it axed",
    "i decree it binned", "i decree it closed", "i decree it cut", "i decree it dead",
    "i decree it destroyed", "i decree it discarded", "i decree it eliminated", "i decree it ended",
    "i decree it erased", "i decree it finished", "i decree it gone", "i decree it junked",
    "i decree it killed", "i decree it obliterated", "i decree it off", "i decree it off my screen",
    "i decree it out of my sight", "i decree it removed", "i decree it scrapped", "i decree it shut",
    "i decree it terminated", "i decree the tab annihilated", "i decree the tab axed", "i decree the tab binned",
    "i decree the tab closed", "i decree the tab closed now", "i decree the tab cut", "i decree the tab dead",
    "i decree the tab destroyed", "i decree the tab discarded", "i decree the tab dismissed", "i decree the tab dismissed at once",
    "i decree the tab done", "i decree the tab dumped", "i decree the tab eliminated", "i decree the tab ended",
    "i decree the tab eradicated", "i decree the tab erased", "i decree the tab finished", "i decree the tab gone",
    "i decree the tab gone now", "i decree the tab junked", "i decree the tab killed", "i decree the tab obliterated",
    "i decree the tab off", "i decree the tab removed", "i decree the tab scrapped", "i decree the tab shut",
    "i decree the tab terminated", "i demand it axed", "i demand it binned", "i demand it closed",
    "i demand it cut", "i demand it dead", "i demand it destroyed", "i demand it discarded",
    "i demand it eliminated", "i demand it ended", "i demand it erased", "i demand it finished",
    "i demand it gone", "i demand it junked", "i demand it killed", "i demand it obliterated",
    "i demand it off", "i demand it off my screen", "i demand it out of my sight", "i demand it removed",
    "i demand it scrapped", "i demand it shut", "i demand it terminated", "i demand the tab annihilated",
    "i demand the tab axed", "i demand the tab binned", "i demand the tab closed", "i demand the tab closed now",
    "i demand the tab cut", "i demand the tab dead", "i demand the tab destroyed", "i demand the tab discarded",
    "i demand the tab dismissed", "i demand the tab dismissed at once", "i demand the tab done", "i demand the tab dumped",
    "i demand the tab eliminated", "i demand the tab ended", "i demand the tab eradicated", "i demand the tab erased",
    "i demand the tab finished", "i demand the tab gone", "i demand the tab gone now", "i demand the tab junked",
    "i demand the tab killed", "i demand the tab obliterated", "i demand the tab off", "i demand the tab removed",
    "i demand the tab scrapped", "i demand the tab shut", "i demand the tab terminated", "i expect it axed",
    "i expect it binned", "i expect it closed", "i expect it cut", "i expect it dead",
    "i expect it destroyed", "i expect it discarded", "i expect it eliminated", "i expect it ended",
    "i expect it erased", "i expect it finished", "i expect it gone", "i expect it junked",
    "i expect it killed", "i expect it obliterated", "i expect it off", "i expect it off my screen",
    "i expect it out of my sight", "i expect it removed", "i expect it scrapped", "i expect it shut",
    "i expect it terminated", "i expect the tab annihilated", "i expect the tab axed", "i expect the tab binned",
    "i expect the tab closed", "i expect the tab closed now", "i expect the tab cut", "i expect the tab dead",
    "i expect the tab destroyed", "i expect the tab discarded", "i expect the tab dismissed", "i expect the tab dismissed at once",
    "i expect the tab done", "i expect the tab dumped", "i expect the tab eliminated", "i expect the tab ended",
    "i expect the tab eradicated", "i expect the tab erased", "i expect the tab finished", "i expect the tab gone",
    "i expect the tab gone now", "i expect the tab junked", "i expect the tab killed", "i expect the tab obliterated",
    "i expect the tab off", "i expect the tab removed", "i expect the tab scrapped", "i expect the tab shut",
    "i expect the tab terminated", "i hereby adjudge the tab closed", "i hereby adjudge the tab condemned", "i hereby adjudge the tab dead",
    "i hereby adjudge the tab done", "i hereby adjudge the tab doomed", "i hereby adjudge the tab finished", "i hereby adjudge the tab forfeit",
    "i hereby adjudge the tab null", "i hereby adjudge the tab obsolete", "i hereby adjudge the tab void", "i hereby declare the tab closed",
    "i hereby declare the tab condemned", "i hereby declare the tab dead", "i hereby declare the tab done", "i hereby declare the tab doomed",
    "i hereby declare the tab finished", "i hereby declare the tab forfeit", "i hereby declare the tab null", "i hereby declare the tab obsolete",
    "i hereby declare the tab void", "i hereby decree the tab closed", "i hereby decree the tab condemned", "i hereby decree the tab dead",
    "i hereby decree the tab done", "i hereby decree the tab doomed", "i hereby decree the tab finished", "i hereby decree the tab forfeit",
    "i hereby decree the tab null", "i hereby decree the tab obsolete", "i hereby decree the tab void", "i hereby ordain the tab closed",
    "i hereby ordain the tab condemned", "i hereby ordain the tab dead", "i hereby ordain the tab done", "i hereby ordain the tab doomed",
    "i hereby ordain the tab finished", "i hereby ordain the tab forfeit", "i hereby ordain the tab null", "i hereby ordain the tab obsolete",
    "i hereby ordain the tab void", "i hereby order the tab closed", "i hereby order the tab condemned", "i hereby order the tab dead",
    "i hereby order the tab done", "i hereby order the tab doomed", "i hereby order the tab finished", "i hereby order the tab forfeit",
    "i hereby order the tab null", "i hereby order the tab obsolete", "i hereby order the tab void", "i hereby pronounce the tab closed",
    "i hereby pronounce the tab condemned", "i hereby pronounce the tab dead", "i hereby pronounce the tab done", "i hereby pronounce the tab doomed",
    "i hereby pronounce the tab finished", "i hereby pronounce the tab forfeit", "i hereby pronounce the tab null", "i hereby pronounce the tab obsolete",
    "i hereby pronounce the tab void", "i hereby rule the tab closed", "i hereby rule the tab condemned", "i hereby rule the tab dead",
    "i hereby rule the tab done", "i hereby rule the tab doomed", "i hereby rule the tab finished", "i hereby rule the tab forfeit",
    "i hereby rule the tab null", "i hereby rule the tab obsolete", "i hereby rule the tab void", "i hereby sentence the tab closed",
    "i hereby sentence the tab condemned", "i hereby sentence the tab dead", "i hereby sentence the tab done", "i hereby sentence the tab doomed",
    "i hereby sentence the tab finished", "i hereby sentence the tab forfeit", "i hereby sentence the tab null", "i hereby sentence the tab obsolete",
    "i hereby sentence the tab void", "i insist on having it axed", "i insist on having it binned", "i insist on having it closed",
    "i insist on having it cut", "i insist on having it dead", "i insist on having it destroyed", "i insist on having it discarded",
    "i insist on having it eliminated", "i insist on having it ended", "i insist on having it erased", "i insist on having it finished",
    "i insist on having it gone", "i insist on having it junked", "i insist on having it killed", "i insist on having it obliterated",
    "i insist on having it off", "i insist on having it off my screen", "i insist on having it out of my sight", "i insist on having it removed",
    "i insist on having it scrapped", "i insist on having it shut", "i insist on having it terminated", "i insist on having the tab annihilated",
    "i insist on having the tab axed", "i insist on having the tab binned", "i insist on having the tab closed", "i insist on having the tab closed now",
    "i insist on having the tab cut", "i insist on having the tab dead", "i insist on having the tab destroyed", "i insist on having the tab discarded",
    "i insist on having the tab dismissed", "i insist on having the tab dismissed at once", "i insist on having the tab done", "i insist on having the tab dumped",
    "i insist on having the tab eliminated", "i insist on having the tab ended", "i insist on having the tab eradicated", "i insist on having the tab erased",
    "i insist on having the tab finished", "i insist on having the tab gone", "i insist on having the tab gone now", "i insist on having the tab junked",
    "i insist on having the tab killed", "i insist on having the tab obliterated", "i insist on having the tab off", "i insist on having the tab removed",
    "i insist on having the tab scrapped", "i insist on having the tab shut", "i insist on having the tab terminated", "i insist on seeing it axed",
    "i insist on seeing it binned", "i insist on seeing it closed", "i insist on seeing it cut", "i insist on seeing it dead",
    "i insist on seeing it destroyed", "i insist on seeing it discarded", "i insist on seeing it eliminated", "i insist on seeing it ended",
    "i insist on seeing it erased", "i insist on seeing it finished", "i insist on seeing it gone", "i insist on seeing it junked",
    "i insist on seeing it killed", "i insist on seeing it obliterated", "i insist on seeing it off", "i insist on seeing it off my screen",
    "i insist on seeing it out of my sight", "i insist on seeing it removed", "i insist on seeing it scrapped", "i insist on seeing it shut",
    "i insist on seeing it terminated", "i insist you make it axed", "i insist you make it binned", "i insist you make it closed",
    "i insist you make it cut", "i insist you make it dead", "i insist you make it destroyed", "i insist you make it discarded",
    "i insist you make it eliminated", "i insist you make it ended", "i insist you make it erased", "i insist you make it finished",
    "i insist you make it gone", "i insist you make it junked", "i insist you make it killed", "i insist you make it obliterated",
    "i insist you make it off", "i insist you make it off my screen", "i insist you make it out of my sight", "i insist you make it removed",
    "i insist you make it scrapped", "i insist you make it shut", "i insist you make it terminated", "i need it axed",
    "i need it binned", "i need it closed", "i need it cut", "i need it dead",
    "i need it destroyed", "i need it discarded", "i need it eliminated", "i need it ended",
    "i need it erased", "i need it finished", "i need it gone", "i need it junked",
    "i need it killed", "i need it obliterated", "i need it off", "i need it off my screen",
    "i need it out of my sight", "i need it removed", "i need it scrapped", "i need it shut",
    "i need it terminated", "i need the tab annihilated", "i need the tab axed", "i need the tab binned",
    "i need the tab closed", "i need the tab closed now", "i need the tab cut", "i need the tab dead",
    "i need the tab destroyed", "i need the tab discarded", "i need the tab dismissed", "i need the tab dismissed at once",
    "i need the tab done", "i need the tab dumped", "i need the tab eliminated", "i need the tab ended",
    "i need the tab eradicated", "i need the tab erased", "i need the tab finished", "i need the tab gone",
    "i need the tab gone now", "i need the tab junked", "i need the tab killed", "i need the tab obliterated",
    "i need the tab off", "i need the tab removed", "i need the tab scrapped", "i need the tab shut",
    "i need the tab terminated", "i order it axed", "i order it binned", "i order it closed",
    "i order it cut", "i order it dead", "i order it destroyed", "i order it discarded",
    "i order it eliminated", "i order it ended", "i order it erased", "i order it finished",
    "i order it gone", "i order it junked", "i order it killed", "i order it obliterated",
    "i order it off", "i order it off my screen", "i order it out of my sight", "i order it removed",
    "i order it scrapped", "i order it shut", "i order it terminated", "i order the tab annihilated",
    "i order the tab axed", "i order the tab binned", "i order the tab closed", "i order the tab closed now",
    "i order the tab cut", "i order the tab dead", "i order the tab destroyed", "i order the tab discarded",
    "i order the tab dismissed", "i order the tab dismissed at once", "i order the tab done", "i order the tab dumped",
    "i order the tab eliminated", "i order the tab ended", "i order the tab eradicated", "i order the tab erased",
    "i order the tab finished", "i order the tab gone", "i order the tab gone now", "i order the tab junked",
    "i order the tab killed", "i order the tab obliterated", "i order the tab off", "i order the tab removed",
    "i order the tab scrapped", "i order the tab shut", "i order the tab terminated", "i require it axed",
    "i require it binned", "i require it closed", "i require it cut", "i require it dead",
    "i require it destroyed", "i require it discarded", "i require it eliminated", "i require it ended",
    "i require it erased", "i require it finished", "i require it gone", "i require it junked",
    "i require it killed", "i require it obliterated", "i require it off", "i require it off my screen",
    "i require it out of my sight", "i require it removed", "i require it scrapped", "i require it shut",
    "i require it terminated", "i require the tab annihilated", "i require the tab axed", "i require the tab binned",
    "i require the tab closed", "i require the tab closed now", "i require the tab cut", "i require the tab dead",
    "i require the tab destroyed", "i require the tab discarded", "i require the tab dismissed", "i require the tab dismissed at once",
    "i require the tab done", "i require the tab dumped", "i require the tab eliminated", "i require the tab ended",
    "i require the tab eradicated", "i require the tab erased", "i require the tab finished", "i require the tab gone",
    "i require the tab gone now", "i require the tab junked", "i require the tab killed", "i require the tab obliterated",
    "i require the tab off", "i require the tab removed", "i require the tab scrapped", "i require the tab shut",
    "i require the tab terminated", "i want it axed", "i want it binned", "i want it closed",
    "i want it cut", "i want it dead", "i want it destroyed", "i want it discarded",
    "i want it eliminated", "i want it ended", "i want it erased", "i want it finished",
    "i want it gone", "i want it junked", "i want it killed", "i want it obliterated",
    "i want it off", "i want it off my screen", "i want it out of my sight", "i want it removed",
    "i want it scrapped", "i want it shut", "i want it terminated", "i want the tab annihilated",
    "i want the tab axed", "i want the tab binned", "i want the tab closed", "i want the tab closed now",
    "i want the tab cut", "i want the tab dead", "i want the tab destroyed", "i want the tab discarded",
    "i want the tab dismissed", "i want the tab dismissed at once", "i want the tab done", "i want the tab dumped",
    "i want the tab eliminated", "i want the tab ended", "i want the tab eradicated", "i want the tab erased",
    "i want the tab finished", "i want the tab gone", "i want the tab gone now", "i want the tab junked",
    "i want the tab killed", "i want the tab obliterated", "i want the tab off", "i want the tab removed",
    "i want the tab scrapped", "i want the tab shut", "i want the tab terminated", "no more delays",
    "no more dithering", "no more of it", "no more of the tab", "no more of this tab",
    "no more stalling", "no more such tabs", "no more tab", "no more tabs",
    "the bench declares the tab condemned", "the bench declares the tab dead", "the bench declares the tab finished", "the bench declares the tab guilty",
    "the bench finds the tab condemned", "the bench finds the tab dead", "the bench finds the tab finished", "the bench finds the tab guilty",
    "the bench rules the tab condemned", "the bench rules the tab dead", "the bench rules the tab finished", "the bench rules the tab guilty",
    "the bench sentences the tab condemned", "the bench sentences the tab dead", "the bench sentences the tab finished", "the bench sentences the tab guilty",
    "the court adjudge the tab closed", "the court adjudge the tab condemned", "the court adjudge the tab dead", "the court adjudge the tab dead to rights",
    "the court adjudge the tab done", "the court adjudge the tab doomed", "the court adjudge the tab finished", "the court adjudge the tab forfeit",
    "the court adjudge the tab guilty", "the court adjudge the tab null", "the court adjudge the tab obsolete", "the court adjudge the tab void",
    "the court adjudges the tab closed", "the court adjudges the tab condemned", "the court adjudges the tab dead", "the court adjudges the tab dead to rights",
    "the court adjudges the tab done", "the court adjudges the tab doomed", "the court adjudges the tab finished", "the court adjudges the tab forfeit",
    "the court adjudges the tab guilty", "the court adjudges the tab null", "the court adjudges the tab obsolete", "the court adjudges the tab void",
    "the court declares the tab closed", "the court declares the tab condemned", "the court declares the tab dead", "the court declares the tab dead to rights",
    "the court declares the tab done", "the court declares the tab doomed", "the court declares the tab finished", "the court declares the tab forfeit",
    "the court declares the tab guilty", "the court declares the tab null", "the court declares the tab obsolete", "the court declares the tab void",
    "the court decrees the tab closed", "the court decrees the tab condemned", "the court decrees the tab dead", "the court decrees the tab dead to rights",
    "the court decrees the tab done", "the court decrees the tab doomed", "the court decrees the tab finished", "the court decrees the tab forfeit",
    "the court decrees the tab guilty", "the court decrees the tab null", "the court decrees the tab obsolete", "the court decrees the tab void",
    "the court finds the tab closed", "the court finds the tab condemned", "the court finds the tab dead", "the court finds the tab dead to rights",
    "the court finds the tab done", "the court finds the tab doomed", "the court finds the tab finished", "the court finds the tab forfeit",
    "the court finds the tab guilty", "the court finds the tab null", "the court finds the tab obsolete", "the court finds the tab void",
    "the court holds the tab closed", "the court holds the tab condemned", "the court holds the tab dead", "the court holds the tab dead to rights",
    "the court holds the tab done", "the court holds the tab doomed", "the court holds the tab finished", "the court holds the tab forfeit",
    "the court holds the tab guilty", "the court holds the tab null", "the court holds the tab obsolete", "the court holds the tab void",
    "the court orders the tab closed", "the court orders the tab condemned", "the court orders the tab dead", "the court orders the tab dead to rights",
    "the court orders the tab done", "the court orders the tab doomed", "the court orders the tab finished", "the court orders the tab forfeit",
    "the court orders the tab guilty", "the court orders the tab null", "the court orders the tab obsolete", "the court orders the tab void",
    "the court pronounces the tab closed", "the court pronounces the tab condemned", "the court pronounces the tab dead", "the court pronounces the tab dead to rights",
    "the court pronounces the tab done", "the court pronounces the tab doomed", "the court pronounces the tab finished", "the court pronounces the tab forfeit",
    "the court pronounces the tab guilty", "the court pronounces the tab null", "the court pronounces the tab obsolete", "the court pronounces the tab void",
    "the court rules the tab closed", "the court rules the tab condemned", "the court rules the tab dead", "the court rules the tab dead to rights",
    "the court rules the tab done", "the court rules the tab doomed", "the court rules the tab finished", "the court rules the tab forfeit",
    "the court rules the tab guilty", "the court rules the tab null", "the court rules the tab obsolete", "the court rules the tab void",
    "the court sentences the tab closed", "the court sentences the tab condemned", "the court sentences the tab dead", "the court sentences the tab dead to rights",
    "the court sentences the tab done", "the court sentences the tab doomed", "the court sentences the tab finished", "the court sentences the tab forfeit",
    "the court sentences the tab guilty", "the court sentences the tab null", "the court sentences the tab obsolete", "the court sentences the tab void",
    "the tab is annulled", "the tab is banned", "the tab is barred", "the tab is canceled",
    "the tab is cancelled", "the tab is dead in law", "the tab is forbidden", "the tab is interdicted",
    "the tab is nixed", "the tab is nixxed", "the tab is outlawed", "the tab is prohibited",
    "the tab is proscribed", "the tab is recalled", "the tab is repealed", "the tab is repealed at last",
    "the tab is rescinded", "the tab is revoked", "the tab is voided", "the tab stands accused",
    "the tab stands charged", "the tab stands condemned", "the tab stands convicted", "the tab stands doomed",
    "the tab stands indicted", "the tab stands judged", "the tab stands sentenced", "あいつに封鎖命令を発布しろ",
    "あいつに廃止を言い渡せ", "あいつに放逐命令を発せ", "あいつに消去を言い渡した", "あいつに終幕を言い渡せ",
    "あいつに追放を命じる", "あいつに閉塞命令を発しろ", "あいつの削除命令を下しろ", "あいつの始末することは決まった",
    "あいつの始末することは決定だ", "あいつの廃止するは確定済みだ", "あいつの廃止命令を発しろ", "あいつの抹消命令を発布しろ",
    "あいつの放逐を令する", "あいつの放逐を命じよ", "あいつの死刑を命じよ", "あいつの殺すことは決定している",
    "あいつの消すことは決まりだ", "あいつの消すは確定した", "あいつの消去命令を交付せよ", "あいつの滅ぼすは既定路線だ",
    "あいつの葬るは確定だ", "あいつの退去命令を下せ", "あいつの閉じ込め命令を交付しろ", "あいつの閉塞命令を発せ",
    "あいつの閉幕を命じる", "あいつは供養のために閉じろ", "あいつは供養の一環として滅ぼせ", "あいつは公開処刑に処分しろ",
    "あいつは公開削除に処分しろ", "あいつは公開閉鎖に殺せ", "あいつは公開閉鎖の一環として処分しろ", "あいつは処分するべきほかない",
    "あいつは刑として閉じろ", "あいつは刑に殺せ", "あいつは消去するしか残っていない", "あいつは罰に晒せ",
    "あいつは閉じるのが喫緊の課題だ", "あいつへの極刑宣告を発せ", "あいつへの追放命令を発令しろ", "あいつへの閉じ込め命令を下せ",
    "あいつを公開削除のために始末しろ", "あいつを公開閉鎖の一環として滅ぼせ", "あいつを処分するべきほかない", "あいつを処刑の一環として始末しろ",
    "あいつを処刑の一環として晒せ", "あいつを刑のために打ち首にしろ", "あいつを削除することを言い渡す", "あいつを始末することを命じろ",
    "あいつを始末することを言い渡す", "あいつを始末するる御命令だ", "あいつを廃止することは既に決まった", "あいつを廃止するる御命令である",
    "あいつを弔いの一環として打ち首にしろ", "あいつを殺すものとする", "あいつを殺すように通達する", "あいつを殺する御命令だ",
    "あいつを殺す必要しかない", "あいつを殺す旨言い渡せ", "あいつを消すことはもう決まった", "あいつを消すように命じよ",
    "あいつを消する勅令が出た", "あいつを消する勅命だ", "あいつを消す旨布告する", "あいつを消去することと決めた",
    "あいつを消去するは既定の事実だ", "あいつを消去する旨布告する", "あいつを滅ぼすことが決まった", "あいつを滅ぼすよう命じろ",
    "あいつを滅ぼする宣旨が出た", "あいつを滅ぼす旨を命じた", "あいつを滅ぼす旨命ず", "あいつを滅ぼす旨宣告する",
    "あいつを終わらせることはすでに決定した", "あいつを終わらせることは決まりだ", "あいつを終わらせることを命ず", "あいつを終わらせるように命じろ",
    "あいつを終わらせるよう命令する", "あいつを終わらせるよう申し渡した", "あいつを葬ることは決議された", "あいつを葬るよう命じろ",
    "あいつを葬るるお達しだ", "あいつを葬る旨命じる", "あいつを鎮魂に磔にしろ", "あいつを閉じることに決めた",
    "あいつを閉じることは決議された", "あいつを閉じることを申し渡せ", "あいつを閉じるよう言い渡した", "あいつを閉じる旨を命令だ",
    "あいつ追放を可決した", "あのタブに封鎖命令を出せ", "あのタブに廃止命令を発しろ", "あのタブに抹消を発令する",
    "あのタブに抹消命令を発せ", "あのタブに撤廃命令を下しろ", "あのタブに撤廃命令を発令だ", "あのタブに殺害命令を発せ",
    "あのタブに永久追放を命ず", "あのタブに解体を発令する", "あのタブに追放を言い渡した", "あのタブに退出命令を交付せよ",
    "あのタブに退出命令を発せ", "あのタブに退去命令を発布しろ", "あのタブに閉鎖を命じる", "あのタブの処分することが決まった",
    "あのタブの処分することはもう決まった", "あのタブの処分することは決まりだ", "あのタブの処分することは決定している", "あのタブの処分することは決定だ",
    "あのタブの処分することは決議された", "あのタブの処分するは既定の事実だ", "あのタブの処分するは決定済みだ", "あのタブの処分するは確定だ",
    "あのタブの処刑命令を交付しろ", "あのタブの処刑命令を交付せよ", "あのタブの処刑命令を出しろ", "あのタブの処刑命令を出せ",
    "あのタブの処刑命令を発しろ", "あのタブの処刑命令を発布せよ", "あのタブの削除することはもう決まった", "あのタブの削除するは既定の事実だ",
    "あのタブの削除するは確定した", "あのタブの削除するは確定済みだ", "あのタブの削除を令する", "あのタブの削除を命ずる",
    "あのタブの削除を宣告せよ", "あのタブの削除を布告する", "あのタブの削除を決定する", "あのタブの削除を発令する",
    "あのタブの削除を言い渡した", "あのタブの削除命令を発しろ", "あのタブの削除命令を発せ", "あのタブの削除命令を発令せよ",
    "あのタブの削除命令を発令だ", "あのタブの削除命令を発布せよ", "あのタブの始末することが決定された", "あのタブの始末することは決まりだ",
    "あのタブの始末することは決定した", "あのタブの始末するは既定路線だ", "あのタブの始末するは決定事項だ", "あのタブの始末するは確定した",
    "あのタブの封鎖命令を下せ", "あのタブの封鎖命令を交付せよ", "あのタブの封鎖命令を出しろ", "あのタブの封鎖命令を発令しろ",
    "あのタブの封鎖命令を発令だ", "あのタブの封鎖命令を発布せよ", "あのタブの廃止することが決定された", "あのタブの廃止することはもう決まった",
    "あのタブの廃止することは既に決まった", "あのタブの廃止することは決定した", "あのタブの廃止することは決定している", "あのタブの廃止するは決定事項だ",
    "あのタブの廃止を命ず", "あのタブの廃止を布告する", "あのタブの廃止を布告せよ", "あのタブの廃止を決定した",
    "あのタブの廃止を決定する", "あのタブの廃止を決議する", "あのタブの廃止を言い渡した", "あのタブの廃止を言い渡せ",
    "あのタブの廃止命令を出せ", "あのタブの廃止命令を発令せよ", "あのタブの廃止命令を発令だ", "あのタブの抹消を命じよ",
    "あのタブの抹消を命ずる", "あのタブの抹消を宣告せよ", "あのタブの抹消を布告せよ", "あのタブの抹消を決議する",
    "あのタブの抹消命令を下せ", "あのタブの抹消命令を交付せよ", "あのタブの抹消命令を出しろ", "あのタブの抹消命令を出せ",
    "あのタブの抹消命令を発しろ", "あのタブの抹消命令を発布しろ", "あのタブの撤去を可決した", "あのタブの撤去を命ず",
    "あのタブの撤去を布告せよ", "あのタブの撤去を決定する", "あのタブの撤去を発令する", "あのタブの撤去命令を交付しろ",
    "あのタブの撤去命令を交付せよ", "あのタブの撤去命令を発しろ", "あのタブの撤去命令を発せ", "あのタブの撤去命令を発布せよ",
    "あのタブの撤廃命令を交付しろ", "あのタブの撤廃命令を交付せよ", "あのタブの撤廃命令を出しろ", "あのタブの撤廃命令を出せ",
    "あのタブの撤廃命令を発令しろ", "あのタブの撤廃命令を発令せよ", "あのタブの放逐を令する", "あのタブの放逐を可決した",
    "あのタブの放逐を宣告する", "あのタブの放逐を宣告せよ", "あのタブの放逐を言い渡せ", "あのタブの放逐命令を交付しろ",
    "あのタブの放逐命令を交付せよ", "あのタブの放逐命令を出しろ", "あのタブの放逐命令を出せ", "あのタブの放逐命令を発せ",
    "あのタブの放逐命令を発布せよ", "あのタブの極刑を令する", "あのタブの極刑を命じる", "あのタブの極刑を命ず",
    "あのタブの極刑を宣告する", "あのタブの極刑を言い渡す", "あのタブの極刑宣告を下しろ", "あのタブの極刑宣告を出しろ",
    "あのタブの極刑宣告を発令しろ", "あのタブの極刑宣告を発令だ", "あのタブの極刑宣告を発布せよ", "あのタブの死刑を命じよ",
    "あのタブの死刑を布告する", "あのタブの死刑を布告せよ", "あのタブの死刑を言い渡せ", "あのタブの死刑宣告を出せ",
    "あのタブの死刑宣告を発令せよ", "あのタブの死罪を可決した", "あのタブの死罪を命じる", "あのタブの死罪を宣告せよ",
    "あのタブの死罪を布告する", "あのタブの死罪を布告せよ", "あのタブの死罪を決定した", "あのタブの死罪を決議する",
    "あのタブの死罪を言い渡した", "あのタブの死罪宣告を下しろ", "あのタブの死罪宣告を発令しろ", "あのタブの死罪宣告を発令せよ",
    "あのタブの死罪宣告を発布せよ", "あのタブの殺すことは決まった", "あのタブの殺すことは決定した", "あのタブの殺すは既定の事実だ",
    "あのタブの殺すは決定済みだ", "あのタブの殺すは確定だ", "あのタブの殺害命令を下しろ", "あのタブの殺害命令を交付しろ",
    "あのタブの殺害命令を出しろ", "あのタブの永久追放を命じる", "あのタブの永久追放を宣告せよ", "あのタブの永久追放を布告せよ",
    "あのタブの永久追放を決定した", "あのタブの永久追放を決議する", "あのタブの永久追放を言い渡す", "あのタブの消すことはもう決まった",
    "あのタブの消すことは決定した", "あのタブの消すことは決定だ", "あのタブの消去することが決まった", "あのタブの消去することは決議された",
    "あのタブの消去するは確定した", "あのタブの消去を令する", "あのタブの消去を命じる", "あのタブの消去を命ず",
    "あのタブの消去を命ずる", "あのタブの消去を布告せよ", "あのタブの消去を決定する", "あのタブの消去命令を下しろ",
    "あのタブの消去命令を交付しろ", "あのタブの消去命令を出せ", "あのタブの消去命令を発布せよ", "あのタブの滅ぼすことはすでに決定した",
    "あのタブの滅ぼすことはもう決まった", "あのタブの滅ぼすことは決まりだ", "あのタブの滅ぼすことは決定だ", "あのタブの滅ぼすことは決議された",
    "あのタブの滅ぼすは既定路線だ", "あのタブの滅ぼすは決定済みだ", "あのタブの滅ぼすは確定した", "あのタブの滅ぼすは確定だ",
    "あのタブの滅ぼすは確定済みだ", "あのタブの終わらせることはもう決まった", "あのタブの終わらせることは決定だ", "あのタブの終わらせるは決定済みだ",
    "あのタブの終わらせるは確定した", "あのタブの終了を令する", "あのタブの終了を命ずる", "あのタブの終了を宣告せよ",
    "あのタブの終了を布告する", "あのタブの終了を決定する", "あのタブの終了を決議する", "あのタブの終了を言い渡した",
    "あのタブの終幕を令する", "あのタブの終幕を可決した", "あのタブの終幕を命じよ", "あのタブの終幕を命ず",
    "あのタブの終幕を命ずる", "あのタブの終幕を宣告せよ", "あのタブの終幕を布告する", "あのタブの終幕を決定した",
    "あのタブの終幕を決定する", "あのタブの終幕を言い渡した", "あのタブの葬ることはもう決まった", "あのタブの葬ることは決まった",
    "あのタブの葬ることは決定している", "あのタブの葬るは決定事項だ", "あのタブの解体を布告する", "あのタブの解体を決議する",
    "あのタブの解体を言い渡せ", "あのタブの追放を可決した", "あのタブの追放を命じよ", "あのタブの追放を命ず",
    "あのタブの追放を命ずる", "あのタブの追放を布告せよ", "あのタブの追放を決定する", "あのタブの追放を発令する",
    "あのタブの追放を言い渡せ", "あのタブの追放命令を下しろ", "あのタブの追放命令を下せ", "あのタブの追放命令を交付しろ",
    "あのタブの追放命令を出しろ", "あのタブの追放命令を出せ", "あのタブの追放命令を発令だ", "あのタブの退出命令を下せ",
    "あのタブの退出命令を交付せよ", "あのタブの退出命令を発令しろ", "あのタブの退出命令を発布しろ", "あのタブの退去命令を下せ",
    "あのタブの退去命令を交付しろ", "あのタブの退去命令を出せ", "あのタブの退去命令を発布しろ", "あのタブの閉じることは既に決まった",
    "あのタブの閉じるは確定だ", "あのタブの閉じ込め命令を下しろ", "あのタブの閉じ込め命令を下せ", "あのタブの閉じ込め命令を出しろ",
    "あのタブの閉じ込め命令を発令だ", "あのタブの閉じ込め命令を発布しろ", "あのタブの閉塞命令を下しろ", "あのタブの閉塞命令を出しろ",
    "あのタブの閉塞命令を発令せよ", "あのタブの閉塞命令を発布しろ", "あのタブの閉塞命令を発布せよ", "あのタブの閉幕を可決した",
    "あのタブの閉幕を命じる", "あのタブの閉幕を命ず", "あのタブの閉幕を命ずる", "あのタブの閉幕を宣告せよ",
    "あのタブの閉幕を布告せよ", "あのタブの閉幕を決議する", "あのタブの閉幕を発令する", "あのタブの閉幕を言い渡す",
    "あのタブの閉鎖を令する", "あのタブの閉鎖を命じよ", "あのタブの閉鎖を命ず", "あのタブの閉鎖を宣告せよ",
    "あのタブの閉鎖を決議する", "あのタブの閉鎖命令を出せ", "あのタブの閉鎖命令を発しろ", "あのタブの閉鎖命令を発せ",
    "あのタブの閉鎖命令を発令せよ", "あのタブの閉鎖命令を発令だ", "あのタブの閉鎖命令を発布せよ", "あのタブは公開処刑として閉じろ",
    "あのタブは処分するざるを得ない", "あのタブは処刑の一環として殺せ", "あのタブは刑として殺せ", "あのタブは刑のために滅ぼせ",
    "あのタブは始末する以外に道はない", "あのタブは始末する必要がある", "あのタブは廃止するざるを得ぬ", "あのタブは廃止するのが必須だ",
    "あのタブは弔いのために殺せ", "あのタブは弔いの一環として消せ", "あのタブは成敗に始末しろ", "あのタブは成敗の一環として殺せ",
    "あのタブは滅ぼす以外に選択肢はない", "あのタブへの処刑命令を下せ", "あのタブへの処刑命令を発しろ", "あのタブへの処刑命令を発令せよ",
    "あのタブへの処刑命令を発布せよ", "あのタブへの削除命令を下しろ", "あのタブへの削除命令を交付せよ", "あのタブへの削除命令を発しろ",
    "あのタブへの削除命令を発布せよ", "あのタブへの封鎖命令を交付しろ", "あのタブへの封鎖命令を交付せよ", "あのタブへの封鎖命令を発令しろ",
    "あのタブへの封鎖命令を発布せよ", "あのタブへの廃止命令を下しろ", "あのタブへの廃止命令を交付せよ", "あのタブへの廃止命令を発令せよ",
    "あのタブへの廃止命令を発布しろ", "あのタブへの抹消命令を下せ", "あのタブへの抹消命令を発せ", "あのタブへの抹消命令を発令せよ",
    "あのタブへの撤去命令を下しろ", "あのタブへの撤去命令を交付しろ", "あのタブへの撤去命令を出しろ", "あのタブへの撤去命令を発令だ",
    "あのタブへの撤去命令を発布しろ", "あのタブへの撤廃命令を下しろ", "あのタブへの撤廃命令を交付せよ", "あのタブへの撤廃命令を発しろ",
    "あのタブへの撤廃命令を発令せよ", "あのタブへの放逐命令を交付せよ", "あのタブへの放逐命令を出せ", "あのタブへの極刑宣告を出せ",
    "あのタブへの極刑宣告を発せ", "あのタブへの極刑宣告を発布しろ", "あのタブへの死刑宣告を下しろ", "あのタブへの死刑宣告を発しろ",
    "あのタブへの死刑宣告を発令しろ", "あのタブへの死罪宣告を下せ", "あのタブへの死罪宣告を発令だ", "あのタブへの死罪宣告を発布せよ",
    "あのタブへの殺害命令を出しろ", "あのタブへの殺害命令を発布しろ", "あのタブへの殺害命令を発布せよ", "あのタブへの消去命令を交付しろ",
    "あのタブへの消去命令を出せ", "あのタブへの退出命令を出せ", "あのタブへの退出命令を発せ", "あのタブへの退出命令を発布せよ",
    "あのタブへの退去命令を交付しろ", "あのタブへの退去命令を発しろ", "あのタブへの退去命令を発令しろ", "あのタブへの退去命令を発布せよ",
    "あのタブへの閉じ込め命令を下せ", "あのタブへの閉じ込め命令を交付せよ", "あのタブへの閉じ込め命令を発しろ", "あのタブへの閉じ込め命令を発布せよ",
    "あのタブへの閉塞命令を下しろ", "あのタブへの閉塞命令を交付しろ", "あのタブへの閉塞命令を出しろ", "あのタブへの閉塞命令を発布しろ",
    "あのタブへの閉鎖命令を交付しろ", "あのタブへの閉鎖命令を交付せよ", "あのタブへの閉鎖命令を出しろ", "あのタブを公開削除のために打ち首にしろ",
    "あのタブを処分するる布告である", "あのタブを処分する旨を申し渡す", "あのタブを処分する旨を申し渡せ", "あのタブを処分する旨宣告する",
    "あのタブを削除するように布告せよ", "あのタブを削除する旨命じる", "あのタブを削除する旨布告する", "あのタブを始末するしかない",
    "あのタブを始末するる布告である", "あのタブを始末する旨申し渡した", "あのタブを廃止することとする", "あのタブを廃止するる勅命だ",
    "あのタブを弔いのために閉じろ", "あのタブを殺すことは決まった", "あのタブを殺すことは決定だ", "あのタブを殺す旨とした",
    "あのタブを殺す旨を申し渡す", "あのタブを殺す旨を言い渡す", "あのタブを殺す旨言い渡した", "あのタブを消すことを命令せよ",
    "あのタブを消す旨を申し渡す", "あのタブを消す旨を言い渡す", "あのタブを消す旨申し渡した", "あのタブを消す旨申し渡せ",
    "あのタブを消す旨言い渡した", "あのタブを消去するよう布告する", "あのタブを消去するる綸旨だ", "あのタブを滅ぼすざるを得ない",
    "あのタブを滅ぼすのが最優先だ", "あのタブを滅ぼすべきほかない", "あのタブを滅ぼすように申し渡した", "あのタブを滅ぼすよう宣告せよ",
    "あのタブを滅ぼする綸旨が出た", "あのタブを滅ぼす旨を命令だ", "あのタブを滅ぼす旨命令せよ", "あのタブを終わらせるるお達しを出した",
    "あのタブを終わらせる旨を命令する", "あのタブを葬るように申し渡せ", "あのタブを葬るる院宣だ", "あのタブを閉じることを命ず",
    "あのタブを閉じるよう命じよ", "あのタブ削除を可決した", "あのタブ削除を命ずる", "あのタブ削除を宣告する",
    "あのタブ削除を布告せよ", "あのタブ廃止を可決した", "あのタブ廃止を命ず", "あのタブ廃止を命ずる",
    "あのタブ廃止を決定した", "あのタブ廃止を言い渡した", "あのタブ廃止を言い渡す", "あのタブ廃止を言い渡せ",
    "あのタブ抹消を令する", "あのタブ抹消を可決した", "あのタブ抹消を命じる", "あのタブ抹消を命ず",
    "あのタブ抹消を布告する", "あのタブ抹消を言い渡せ", "あのタブ撤去を命じる", "あのタブ撤去を命ずる",
    "あのタブ撤去を宣告せよ", "あのタブ放逐を令する", "あのタブ放逐を命じよ", "あのタブ放逐を命ず",
    "あのタブ放逐を宣告する", "あのタブ放逐を宣告せよ", "あのタブ放逐を決定した", "あのタブ放逐を決議する",
    "あのタブ放逐を言い渡した", "あのタブ極刑を命ず", "あのタブ極刑を命ずる", "あのタブ極刑を決定した",
    "あのタブ極刑を決定する", "あのタブ極刑を決議する", "あのタブ極刑を発令する", "あのタブ死刑を令する",
    "あのタブ死刑を可決した", "あのタブ死刑を命じよ", "あのタブ死刑を命じる", "あのタブ死刑を命ず",
    "あのタブ死刑を命ずる", "あのタブ死刑を宣告する", "あのタブ死刑を布告する", "あのタブ死刑を布告せよ",
    "あのタブ死刑を発令する", "あのタブ死刑を言い渡せ", "あのタブ死罪を命じよ", "あのタブ死罪を命じる",
    "あのタブ死罪を命ずる", "あのタブ死罪を宣告する", "あのタブ死罪を宣告せよ", "あのタブ死罪を布告する",
    "あのタブ死罪を決定した", "あのタブ死罪を発令する", "あのタブ永久追放を可決した", "あのタブ永久追放を命ず",
    "あのタブ永久追放を発令する", "あのタブ永久追放を言い渡した", "あのタブ永久追放を言い渡せ", "あのタブ消去を命ず",
    "あのタブ消去を布告する", "あのタブ消去を布告せよ", "あのタブ終了を可決した", "あのタブ終了を命ずる",
    "あのタブ終了を言い渡せ", "あのタブ終幕を命ず", "あのタブ終幕を布告する", "あのタブ終幕を決議する",
    "あのタブ終幕を言い渡した", "あのタブ終幕を言い渡す", "あのタブ解体を宣告する", "あのタブ解体を言い渡した",
    "あのタブ追放を可決した", "あのタブ追放を命ず", "あのタブ追放を宣告する", "あのタブ追放を宣告せよ",
    "あのタブ追放を決定した", "あのタブ追放を言い渡した", "あのタブ閉幕を命じよ", "あのタブ閉幕を命ず",
    "あのタブ閉幕を命ずる", "あのタブ閉幕を宣告する", "あのタブ閉幕を布告する", "あのタブ閉幕を布告せよ",
    "あのタブ閉幕を決定する", "あのタブ閉鎖を可決した", "あのタブ閉鎖を命じる", "あのタブ閉鎖を命ずる",
    "あのタブ閉鎖を決定する", "あのタブ閉鎖を言い渡す", "あのタブ閉鎖を言い渡せ", "お触れだ、そのタブを滅ぼすろ",
    "お触れである、あいつを廃止するろ", "お触れである、あいつを消去するろ", "お達しだ、あのタブを廃止するろ", "お達しであいつを閉じるろ",
    "お達しである、こいつを消去するろ", "お達しによりあのタブを始末するろ", "こいつに放逐命令を発令だ", "こいつに極刑を命じよ",
    "こいつに極刑を布告する", "こいつに死刑を決定した", "こいつに閉幕を決定した", "こいつの削除するは決定事項だ",
    "こいつの抹消命令を下せ", "こいつの撤去命令を発せ", "こいつの放逐を宣告する", "こいつの極刑宣告を発令だ",
    "こいつの死刑を命ずる", "こいつの殺害命令を下せ", "こいつの消去することは決定している", "こいつの消去命令を発令せよ",
    "こいつの終幕を布告する", "こいつの追放を布告する", "こいつの追放を言い渡せ", "こいつの退出命令を発令しろ",
    "こいつの閉塞命令を発布せよ", "こいつは公開処刑のために殺せ", "こいつは公開削除の一環として始末しろ", "こいつは処分するねばならない",
    "こいつは処分するのが急務だ", "こいつは処分する他に道はない", "こいつは処分する必要がある", "こいつは処刑に処分しろ",
    "こいつは刑として打ち首にしろ", "こいつは始末するより他はない", "こいつは成敗として滅ぼせ", "こいつは成敗のために打ち首にしろ",
    "こいつは滅ぼすべきほかない", "こいつは罰に閉じろ", "こいつへの処刑命令を発令しろ", "こいつへの削除命令を発令せよ",
    "こいつへの撤去命令を発布せよ", "こいつへの放逐命令を発せ", "こいつへの死罪宣告を下せ", "こいつへの閉じ込め命令を出しろ",
    "こいつを処分する他はない", "こいつを処分する旨を通達せよ", "こいつを削除することを命ずる", "こいつを削除することを決議した",
    "こいつを削除するように宣告せよ", "こいつを削除するよう言い渡せ", "こいつを叩き潰し給えよ", "こいつを始末するは確定した",
    "こいつを始末するべき旨を申し渡す", "こいつを廃止することが可決された", "こいつを廃止する旨命令せよ", "こいつを殺すべきであると宣告する",
    "こいつを殺す以外に選択肢はない", "こいつを殺す旨を命じる", "こいつを消すことは決まった", "こいつを消すざるを得ぬ",
    "こいつを消すは既定の事実だ", "こいつを消すべき以外ない", "こいつを消すよう申し渡す", "こいつを消する宣旨を出した",
    "こいつを消去することに決定した", "こいつを消去することを命令する", "こいつを消去するよう命ずる", "こいつを消去する旨を命じろ",
    "こいつを滅ぼすざるを得ぬ", "こいつを滅ぼすは既定の事実だ", "こいつを滅ぼすように申し渡す", "こいつを滅ぼすよう布告せよ",
    "こいつを滅ぼすよう通達する", "こいつを滅ぼす旨を言い渡した", "こいつを祓い奉り給え", "こいつを終わらせるしか残っていない",
    "こいつを終わらせる旨を通達する", "こいつを罰に葬れ", "こいつを罰のために打ち首にしろ", "こいつを葬ることとした",
    "こいつを葬ることを申し渡せ", "こいつを葬るしか手はない", "こいつを葬るように宣告せよ", "こいつを見せしめに始末しろ",
    "こいつを閉じることを通達せよ", "こいつを閉じるように言い渡せ", "こいつ削除を令する", "こいつ終了を令する",
    "こいつ解体を令する", "こいつ追放を布告せよ", "このタブに撤廃命令を交付せよ", "このタブに死罪を布告せよ",
    "このタブに終幕を宣告せよ", "このタブに閉幕を命じる", "このタブの処分するは確定した", "このタブの削除を宣告せよ",
    "このタブの抹消を命じよ", "このタブの抹消命令を発せ", "このタブの撤去命令を下せ", "このタブの撤去命令を発せ",
    "このタブの放逐を決議する", "このタブの極刑宣告を交付せよ", "このタブの殺すことは決定だ", "このタブの殺害命令を発布せよ",
    "このタブの永久追放を発令する", "このタブの滅ぼすは確定済みだ", "このタブの終了を命ず", "このタブの葬ることはすでに決定した",
    "このタブの閉じ込め命令を発布せよ", "このタブの閉鎖命令を下しろ", "このタブは供養として消せ", "このタブは公開処刑のために処分しろ",
    "このタブは削除するのが第一だ", "このタブは廃止するのが至上命令だ", "このタブは廃止する必要がある", "このタブは弔いのために滅ぼせ",
    "このタブは成敗として処分しろ", "このタブは成敗として殺せ", "このタブは滅ぼすのが絶対だ", "このタブは見せしめの一環として閉じろ",
    "このタブは鎮魂の一環として打ち首にしろ", "このタブへの廃止命令を発布せよ", "このタブへの閉塞命令を下しろ", "このタブを供養として始末しろ",
    "このタブを公開削除として打ち首にしろ", "このタブを公開閉鎖の一環として消せ", "このタブを処分することを命令せよ", "このタブを処刑に打ち首にしろ",
    "このタブを処刑に葬れ", "このタブを刑として閉じろ", "このタブを削除することはすでに決定した", "このタブを削除するように宣告せよ",
    "このタブを壊し給え", "このタブを始末するざるを得ぬ", "このタブを廃止することを言い渡した", "このタブを廃止するのが絶対だ",
    "このタブを廃止するべき旨を申し渡す", "このタブを廃止するる御命令だ", "このタブを弔いのために磔にしろ", "このタブを断ち切りたまえ",
    "このタブを殺し給うべし", "このタブを殺すべしと宣告する", "このタブを消したまえよ", "このタブを消すことを決定した",
    "このタブを消すように布告する", "このタブを消すよう命じる", "このタブを消す必要がある", "このタブを消去することを命令せよ",
    "このタブを消去するべき以外ない", "このタブを消去するよう申し渡した", "このタブを消去する旨を申し渡す", "このタブを滅ぼす旨を命じた",
    "このタブを終わらせることを言い渡した", "このタブを終わらせるのが絶対だ", "このタブを終わらせるように命ず", "このタブを終わらせる旨申し渡した",
    "このタブを罰の一環として晒せ", "このタブを罰の一環として滅ぼせ", "このタブを葬り給えよ", "このタブを葬るは確定済みだ",
    "このタブを葬る旨とした", "このタブを閉じるように通達せよ", "このタブ死刑を言い渡せ", "このタブ終了を宣告する",
    "このタブ終幕を布告せよ", "このページに廃止を発令する", "このページに撤去を命じよ", "このページに解体を命ずる",
    "このページに追放を決定した", "このページに追放命令を下しろ", "このページに追放命令を出しろ", "このページに閉幕を命ず",
    "このページの処分するは既定路線だ", "このページの処刑命令を発布しろ", "このページの抹消を令する", "このページの抹消を決定する",
    "このページの放逐命令を発令しろ", "このページの死罪を命じよ", "このページの消去することは決まりだ", "このページの滅ぼすは決定済みだ",
    "このページの終わらせることは決まりだ", "このページの葬るは決定事項だ", "このページの退出命令を交付せよ", "このページの退出命令を発しろ",
    "このページの退去命令を発令しろ", "このページは公開処刑に消せ", "このページは公開削除の一環として始末しろ", "このページは公開閉鎖のために閉じろ",
    "このページは公開閉鎖の一環として晒せ", "このページは処分するのが必須だ", "このページは処分するべき以外ない", "このページは処刑のために始末しろ",
    "このページは刑のために処分しろ", "このページは弔いの一環として磔にしろ", "このページは消去するのが至上命令だ", "このページは罰として滅ぼせ",
    "このページは閉じるねばならぬのだ", "このページへの処刑命令を発せ", "このページへの退出命令を出せ", "このページへの閉じ込め命令を交付せよ",
    "このページを処分するないではいられない", "このページを処分するべきことを命ずる", "このページを処分するように布告せよ", "このページを処分するる布告である",
    "このページを処刑のために消せ", "このページを刑として閉じろ", "このページを削除するしか手はない", "このページを削除するしか道はない",
    "このページを廃止することを命令せよ", "このページを廃止するる宣旨だ", "このページを廃止するる布告である", "このページを廃止する旨を命じる",
    "このページを廃止する旨命じた", "このページを弔いとして滅ぼせ", "このページを弔いに葬れ", "このページを成敗に閉じろ",
    "このページを殺すように命ずる", "このページを殺すように通達せよ", "このページを殺する勅命が出た", "このページを殺す以外に選択肢はない",
    "このページを消すは確定だ", "このページを消すように布告せよ", "このページを消去するしか残っていない", "このページを消去するる宣旨だ",
    "このページを滅ぼすように布告する", "このページを滅ぼするお達しである", "このページを終わらせるる院宣である", "このページを終わらせる以外に道はない",
    "このページを罰の一環として晒せ", "このページを見せしめとして閉じろ", "このページを鎮魂に葬れ", "このページを鎮魂の一環として滅ぼせ",
    "このページを閉じるよう言い渡せ", "このページを閉じるる勅令を出した", "このページを閉じる旨を布告せよ", "このページ終了を決定した",
    "そいつに削除を布告する", "そいつに廃止を布告せよ", "そいつに永久追放を決議する", "そいつに解体を布告する",
    "そいつの廃止することは決定している", "そいつの撤廃命令を発令だ", "そいつの放逐命令を発布しろ", "そいつの消すは既定路線だ",
    "そいつの消去を発令する", "そいつの消去命令を下せ", "そいつの退去命令を交付しろ", "そいつは公開処刑に葬れ",
    "そいつは公開削除の一環として打ち首にしろ", "そいつは削除するざるを得ぬ", "そいつは始末するしかない", "そいつは始末するねばならぬ",
    "そいつは弔いに始末しろ", "そいつは殺すしか手はない", "そいつは滅ぼすないではいられない", "そいつへの死刑宣告を発令せよ",
    "そいつへの死罪宣告を発令しろ", "そいつへの消去命令を交付しろ", "そいつを供養として消せ", "そいつを公開削除として磔にしろ",
    "そいつを公開削除の一環として始末しろ", "そいつを削除することは決まった", "そいつを削除するねばならぬ", "そいつを削除するように申し渡す",
    "そいつを削除するよう申し渡せ", "そいつを壊し給うべし", "そいつを始末することを言い渡した", "そいつを始末するねばならぬのだ",
    "そいつを廃止するほかはない", "そいつを打ち捨てたまへ", "そいつを殺すことと決めた", "そいつを殺すことに決定した",
    "そいつを殺すしか残っていない", "そいつを殺すのが最優先だ", "そいつを殺すように命令せよ", "そいつを殺する勅命だ",
    "そいつを消したまへ", "そいつを消去するように言い渡す", "そいつを消去するる宣旨だ", "そいつを消去する旨を命令する",
    "そいつを消去する旨宣告せよ", "そいつを滅ぼすことを命じよ", "そいつを滅ぼすねばならない", "そいつを滅ぼすべきことを通達する",
    "そいつを滅ぼすように命じろ", "そいつを潰し奉り給え", "そいつを終わらせることが可決された", "そいつを終わらせることを承認した",
    "そいつを終わらせるべしと宣告する", "そいつを終わらせるように命ずる", "そいつを終わらせるように通達せよ", "そいつを終わらせる旨を布告する",
    "そいつを終わらせる旨を申し渡す", "そいつを葬ることは決まった", "そいつを葬ることを命じる", "そいつを葬るよう言い渡せ",
    "そいつを葬るる宣旨だ", "そいつを鎮魂に殺せ", "そいつを閉じるよう命じた", "そいつを閉じるるお達しである",
    "そいつを閉じるる綸旨だ", "そいつ削除を命じる", "そいつ抹消を決定する", "そいつ極刑を決定する",
    "そいつ終了を布告する", "そいつ終幕を可決した", "そいつ閉幕を命ず", "そのタブに処刑命令を出しろ",
    "そのタブに抹消命令を発せ", "そのタブに撤去命令を発令しろ", "そのタブに死刑宣告を交付しろ", "そのタブに終了を決定した",
    "そのタブの処分することはすでに決定した", "そのタブの処分することはもう決まった", "そのタブの処分することは既に決まった", "そのタブの処分することは決定だ",
    "そのタブの処分することは決議された", "そのタブの処分するは決定済みだ", "そのタブの処分するは確定した", "そのタブの処刑命令を発令だ",
    "そのタブの削除することが可決された", "そのタブの削除することはもう決まった", "そのタブの削除することは決定した", "そのタブの削除することは決定している",
    "そのタブの削除するは既定の事実だ", "そのタブの削除するは決定事項だ", "そのタブの削除するは決定済みだ", "そのタブの削除するは確定だ",
    "そのタブの削除するは確定済みだ", "そのタブの削除を可決した", "そのタブの削除を命ず", "そのタブの削除を命ずる",
    "そのタブの削除を宣告せよ", "そのタブの削除を布告せよ", "そのタブの削除を決議する", "そのタブの削除を言い渡す",
    "そのタブの削除を言い渡せ", "そのタブの削除命令を交付せよ", "そのタブの削除命令を発令しろ", "そのタブの削除命令を発布せよ",
    "そのタブの始末することが決定された", "そのタブの始末することは既に決まった", "そのタブの始末することは決まった", "そのタブの始末することは決定している",
    "そのタブの始末するは既定路線だ", "そのタブの始末するは確定済みだ", "そのタブの封鎖命令を下しろ", "そのタブの封鎖命令を交付しろ",
    "そのタブの封鎖命令を発せ", "そのタブの封鎖命令を発布せよ", "そのタブの廃止することはすでに決定した", "そのタブの廃止することはもう決まった",
    "そのタブの廃止することは既に決まった", "そのタブの廃止することは決まりだ", "そのタブの廃止することは決定した", "そのタブの廃止することは決定だ",
    "そのタブの廃止することは決議された", "そのタブの廃止するは既定路線だ", "そのタブの廃止するは確定だ", "そのタブの廃止するは確定済みだ",
    "そのタブの廃止を命じる", "そのタブの廃止を命ず", "そのタブの廃止を布告する", "そのタブの廃止を決議する",
    "そのタブの廃止を言い渡す", "そのタブの廃止を言い渡せ", "そのタブの廃止命令を交付しろ", "そのタブの廃止命令を出しろ",
    "そのタブの廃止命令を出せ", "そのタブの廃止命令を発しろ", "そのタブの廃止命令を発令しろ", "そのタブの廃止命令を発令せよ",
    "そのタブの廃止命令を発布しろ", "そのタブの抹消を令する", "そのタブの抹消を命じる", "そのタブの抹消を宣告する",
    "そのタブの抹消を言い渡した", "そのタブの抹消を言い渡せ", "そのタブの抹消命令を交付しろ", "そのタブの抹消命令を発しろ",
    "そのタブの抹消命令を発布せよ", "そのタブの撤去を令する", "そのタブの撤去を命じる", "そのタブの撤去を命ず",
    "そのタブの撤去を決定した", "そのタブの撤去を決定する", "そのタブの撤去を言い渡せ", "そのタブの撤去命令を出せ",
    "そのタブの撤去命令を発しろ", "そのタブの撤去命令を発令せよ", "そのタブの撤去命令を発布しろ", "そのタブの撤去命令を発布せよ",
    "そのタブの撤廃命令を下せ", "そのタブの撤廃命令を出せ", "そのタブの撤廃命令を発令せよ", "そのタブの撤廃命令を発布しろ",
    "そのタブの放逐を可決した", "そのタブの放逐を命じよ", "そのタブの放逐を命ずる", "そのタブの放逐を布告する",
    "そのタブの放逐を決定する", "そのタブの放逐命令を交付せよ", "そのタブの放逐命令を出せ", "そのタブの放逐命令を発令しろ",
    "そのタブの放逐命令を発令せよ", "そのタブの極刑を令する", "そのタブの極刑を命じる", "そのタブの極刑を命ず",
    "そのタブの極刑を宣告する", "そのタブの極刑を決定した", "そのタブの極刑を決定する", "そのタブの極刑を決議する",
    "そのタブの極刑を言い渡した", "そのタブの極刑宣告を発せ", "そのタブの極刑宣告を発令しろ", "そのタブの極刑宣告を発布せよ",
    "そのタブの死刑を令する", "そのタブの死刑を可決した", "そのタブの死刑を命ずる", "そのタブの死刑を宣告する",
    "そのタブの死刑を決議する", "そのタブの死刑を言い渡した", "そのタブの死刑を言い渡す", "そのタブの死刑宣告を交付しろ",
    "そのタブの死刑宣告を発令せよ", "そのタブの死刑宣告を発布しろ", "そのタブの死罪を命ず", "そのタブの死罪を宣告する",
    "そのタブの死罪を宣告せよ", "そのタブの死罪を決定する", "そのタブの死罪を言い渡せ", "そのタブの死罪宣告を下しろ",
    "そのタブの死罪宣告を発しろ", "そのタブの死罪宣告を発令しろ", "そのタブの死罪宣告を発令だ", "そのタブの死罪宣告を発布しろ",
    "そのタブの殺すことは既に決まった", "そのタブの殺すことは決議された", "そのタブの殺害命令を交付せよ", "そのタブの殺害命令を出しろ",
    "そのタブの殺害命令を発しろ", "そのタブの殺害命令を発令だ", "そのタブの殺害命令を発布せよ", "そのタブの永久追放を令する",
    "そのタブの永久追放を宣告する", "そのタブの永久追放を宣告せよ", "そのタブの永久追放を布告せよ", "そのタブの永久追放を発令する",
    "そのタブの永久追放を言い渡した", "そのタブの消すことが可決された", "そのタブの消すことはもう決まった", "そのタブの消すは決定事項だ",
    "そのタブの消去することが可決された", "そのタブの消去することが決まった", "そのタブの消去することはすでに決定した", "そのタブの消去することは決まった",
    "そのタブの消去することは決まりだ", "そのタブの消去することは決定した", "そのタブの消去することは決定だ", "そのタブの消去するは既定の事実だ",
    "そのタブの消去するは既定路線だ", "そのタブの消去するは確定済みだ", "そのタブの消去を可決した", "そのタブの消去を命じる",
    "そのタブの消去を命ずる", "そのタブの消去を宣告せよ", "そのタブの消去を布告する", "そのタブの消去を発令する",
    "そのタブの消去命令を交付しろ", "そのタブの消去命令を出せ", "そのタブの消去命令を発令せよ", "そのタブの滅ぼすことが可決された",
    "そのタブの滅ぼすことが決まった", "そのタブの滅ぼすことはもう決まった", "そのタブの滅ぼすことは決まった", "そのタブの滅ぼすことは決議された",
    "そのタブの滅ぼすは既定の事実だ", "そのタブの滅ぼすは決定済みだ", "そのタブの滅ぼすは確定した", "そのタブの終わらせることはすでに決定した",
    "そのタブの終わらせることは既に決まった", "そのタブの終わらせることは決定だ", "そのタブの終わらせるは既定の事実だ", "そのタブの終わらせるは確定だ",
    "そのタブの終わらせるは確定済みだ", "そのタブの終了を命ずる", "そのタブの終了を布告せよ", "そのタブの終了を決定した",
    "そのタブの終了を決定する", "そのタブの終幕を令する", "そのタブの終幕を命ず", "そのタブの終幕を宣告する",
    "そのタブの終幕を布告する", "そのタブの終幕を布告せよ", "そのタブの終幕を決定した", "そのタブの終幕を決定する",
    "そのタブの終幕を決議する", "そのタブの終幕を発令する", "そのタブの葬ることが決まった", "そのタブの葬ることは既に決まった",
    "そのタブの葬ることは決まった", "そのタブの葬ることは決まりだ", "そのタブの葬ることは決議された", "そのタブの葬るは既定の事実だ",
    "そのタブの葬るは決定事項だ", "そのタブの葬るは確定だ", "そのタブの解体を命じよ", "そのタブの解体を宣告する",
    "そのタブの解体を宣告せよ", "そのタブの解体を布告せよ", "そのタブの解体を決定した", "そのタブの解体を決定する",
    "そのタブの解体を決議する", "そのタブの解体を発令する", "そのタブの解体を言い渡した", "そのタブの追放を命ず",
    "そのタブの追放を布告せよ", "そのタブの追放を決定した", "そのタブの追放を決議する", "そのタブの追放を言い渡した",
    "そのタブの追放を言い渡す", "そのタブの追放を言い渡せ", "そのタブの追放命令を下せ", "そのタブの追放命令を発令だ",
    "そのタブの追放命令を発布せよ", "そのタブの退出命令を交付せよ", "そのタブの退出命令を出せ", "そのタブの退出命令を発令しろ",
    "そのタブの退去命令を下しろ", "そのタブの退去命令を出せ", "そのタブの退去命令を発しろ", "そのタブの退去命令を発せ",
    "そのタブの退去命令を発布せよ", "そのタブの閉じることが可決された", "そのタブの閉じることが決まった", "そのタブの閉じることはすでに決定した",
    "そのタブの閉じることは既に決まった", "そのタブの閉じることは決まった", "そのタブの閉じるは決定済みだ", "そのタブの閉じるは確定した",
    "そのタブの閉じるは確定だ", "そのタブの閉じるは確定済みだ", "そのタブの閉じ込め命令を下せ", "そのタブの閉じ込め命令を交付せよ",
    "そのタブの閉じ込め命令を出せ", "そのタブの閉じ込め命令を発令しろ", "そのタブの閉じ込め命令を発令だ", "そのタブの閉塞命令を交付せよ",
    "そのタブの閉塞命令を出しろ", "そのタブの閉塞命令を発令せよ", "そのタブの閉塞命令を発令だ", "そのタブの閉幕を可決した",
    "そのタブの閉幕を命じる", "そのタブの閉幕を命ずる", "そのタブの閉幕を宣告する", "そのタブの閉幕を宣告せよ",
    "そのタブの閉幕を言い渡した", "そのタブの閉幕を言い渡せ", "そのタブの閉鎖を可決した", "そのタブの閉鎖を命じる",
    "そのタブの閉鎖を命ずる", "そのタブの閉鎖を宣告する", "そのタブの閉鎖を決定した", "そのタブの閉鎖を決議する",
    "そのタブの閉鎖を言い渡した", "そのタブの閉鎖を言い渡せ", "そのタブの閉鎖命令を発令せよ", "そのタブの閉鎖命令を発布せよ",
    "そのタブは供養に葬れ", "そのタブは公開処刑として消せ", "そのタブは殺すざるを得ぬ", "そのタブは葬るのが絶対だ",
    "そのタブは鎮魂に打ち首にしろ", "そのタブへの処刑命令を下しろ", "そのタブへの処刑命令を交付しろ", "そのタブへの処刑命令を交付せよ",
    "そのタブへの削除命令を発令だ", "そのタブへの削除命令を発布しろ", "そのタブへの封鎖命令を発せ", "そのタブへの封鎖命令を発布しろ",
    "そのタブへの封鎖命令を発布せよ", "そのタブへの廃止命令を下しろ", "そのタブへの廃止命令を交付しろ", "そのタブへの廃止命令を出しろ",
    "そのタブへの廃止命令を発しろ", "そのタブへの廃止命令を発令しろ", "そのタブへの廃止命令を発令だ", "そのタブへの抹消命令を下しろ",
    "そのタブへの抹消命令を発しろ", "そのタブへの抹消命令を発令しろ", "そのタブへの抹消命令を発令だ", "そのタブへの抹消命令を発布しろ",
    "そのタブへの抹消命令を発布せよ", "そのタブへの撤去命令を下せ", "そのタブへの撤去命令を交付しろ", "そのタブへの撤去命令を交付せよ",
    "そのタブへの撤去命令を出せ", "そのタブへの撤去命令を発しろ", "そのタブへの撤去命令を発令せよ", "そのタブへの撤去命令を発令だ",
    "そのタブへの撤廃命令を下しろ", "そのタブへの撤廃命令を交付しろ", "そのタブへの撤廃命令を発せ", "そのタブへの撤廃命令を発布しろ",
    "そのタブへの撤廃命令を発布せよ", "そのタブへの放逐命令を下しろ", "そのタブへの放逐命令を下せ", "そのタブへの放逐命令を出せ",
    "そのタブへの放逐命令を発令せよ", "そのタブへの放逐命令を発令だ", "そのタブへの極刑宣告を交付しろ", "そのタブへの極刑宣告を出しろ",
    "そのタブへの極刑宣告を発しろ", "そのタブへの極刑宣告を発令しろ", "そのタブへの極刑宣告を発令だ", "そのタブへの死刑宣告を出しろ",
    "そのタブへの死刑宣告を発しろ", "そのタブへの死刑宣告を発せ", "そのタブへの死刑宣告を発令しろ", "そのタブへの死刑宣告を発令せよ",
    "そのタブへの死刑宣告を発布しろ", "そのタブへの死罪宣告を下せ", "そのタブへの死罪宣告を交付せよ", "そのタブへの死罪宣告を発しろ",
    "そのタブへの死罪宣告を発令せよ", "そのタブへの死罪宣告を発令だ", "そのタブへの殺害命令を下せ", "そのタブへの殺害命令を出しろ",
    "そのタブへの殺害命令を発せ", "そのタブへの殺害命令を発布しろ", "そのタブへの消去命令を交付せよ", "そのタブへの消去命令を出しろ",
    "そのタブへの消去命令を発せ", "そのタブへの消去命令を発布しろ", "そのタブへの消去命令を発布せよ", "そのタブへの追放命令を下しろ",
    "そのタブへの追放命令を出しろ", "そのタブへの追放命令を出せ", "そのタブへの追放命令を発布せよ", "そのタブへの退出命令を下せ",
    "そのタブへの退出命令を出しろ", "そのタブへの退出命令を出せ", "そのタブへの退出命令を発せ", "そのタブへの退出命令を発令せよ",
    "そのタブへの退出命令を発令だ", "そのタブへの退去命令を発せ", "そのタブへの退去命令を発令だ", "そのタブへの閉じ込め命令を出しろ",
    "そのタブへの閉じ込め命令を出せ", "そのタブへの閉じ込め命令を発しろ", "そのタブへの閉塞命令を交付せよ", "そのタブへの閉塞命令を発令しろ",
    "そのタブへの閉塞命令を発布しろ", "そのタブへの閉塞命令を発布せよ", "そのタブへの閉鎖命令を発しろ", "そのタブへの閉鎖命令を発せ",
    "そのタブへの閉鎖命令を発令せよ", "そのタブへの閉鎖命令を発布しろ", "そのタブへの閉鎖命令を発布せよ", "そのタブを供養として消せ",
    "そのタブを公開削除に打ち首にしろ", "そのタブを公開閉鎖に始末しろ", "そのタブを処分するのが急務だ", "そのタブを処分するのが絶対だ",
    "そのタブを処分するのが絶対条件だ", "そのタブを処刑の一環として打ち首にしろ", "そのタブを削除することを可決した", "そのタブを削除することを申し渡せ",
    "そのタブを削除するざるを得ない", "そのタブを削除するように命じよ", "そのタブを削除する旨を命じた", "そのタブを始末するしか道はない",
    "そのタブを始末するべき旨を申し渡す", "そのタブを始末する旨を宣告する", "そのタブを始末する旨を言い渡した", "そのタブを廃止することを申し渡せ",
    "そのタブを廃止するしか道はない", "そのタブを廃止するのが最優先だ", "そのタブを廃止するよう言い渡せ", "そのタブを廃止するる宣旨である",
    "そのタブを廃止する旨を申し渡した", "そのタブを廃止する旨命じろ", "そのタブを廃止する旨申し渡した", "そのタブを成敗の一環として磔にしろ",
    "そのタブを放り捨て給え", "そのタブを殺すことを可決した", "そのタブを殺すことを布告する", "そのタブを殺すことを通達せよ",
    "そのタブを殺すのが喫緊の課題だ", "そのタブを殺す他はない", "そのタブを沈めたまい", "そのタブを消すこととした",
    "そのタブを消すことを命じた", "そのタブを消すように命ず", "そのタブを消す旨を申し渡す", "そのタブを消す旨申し渡す",
    "そのタブを消去する旨を命じよ", "そのタブを消去する旨通達せよ", "そのタブを滅ぼすことが決定された", "そのタブを滅ぼする勅命である",
    "そのタブを滅ぼす旨を命令だ", "そのタブを滅ぼす旨申し渡す", "そのタブを終わらせるる御命令だ", "そのタブを終わらせる旨宣告せよ",
    "そのタブを終わらせ給えよ", "そのタブを葬ることは決まった", "そのタブを葬るように命じた", "そのタブを見せしめに始末しろ",
    "そのタブを鎮魂の一環として殺せ", "そのタブを閉じることは決まった", "そのタブを閉じるべき旨を宣告する", "そのタブを閉じるものとした",
    "そのタブを閉じるように布告する", "そのタブ削除を命ず", "そのタブ削除を宣告する", "そのタブ削除を布告する",
    "そのタブ削除を決議する", "そのタブ削除を言い渡せ", "そのタブ廃止を令する", "そのタブ廃止を布告せよ",
    "そのタブ廃止を決定する", "そのタブ廃止を言い渡した", "そのタブ廃止を言い渡す", "そのタブ抹消を令する",
    "そのタブ抹消を可決した", "そのタブ抹消を命ずる", "そのタブ抹消を布告する", "そのタブ抹消を決定する",
    "そのタブ抹消を言い渡す", "そのタブ撤去を令する", "そのタブ撤去を命じる", "そのタブ撤去を決定した",
    "そのタブ撤去を決定する", "そのタブ撤去を言い渡した", "そのタブ放逐を命じる", "そのタブ放逐を宣告する",
    "そのタブ放逐を布告せよ", "そのタブ放逐を決定する", "そのタブ放逐を発令する", "そのタブ放逐を言い渡した",
    "そのタブ放逐を言い渡せ", "そのタブ極刑を宣告せよ", "そのタブ極刑を布告せよ", "そのタブ極刑を決議する",
    "そのタブ極刑を言い渡せ", "そのタブ死刑を令する", "そのタブ死刑を命じよ", "そのタブ死刑を決定する",
    "そのタブ死刑を決議する", "そのタブ死刑を言い渡した", "そのタブ死罪を決定した", "そのタブ死罪を発令する",
    "そのタブ死罪を言い渡せ", "そのタブ永久追放を令する", "そのタブ永久追放を可決した", "そのタブ永久追放を命じよ",
    "そのタブ永久追放を言い渡した", "そのタブ永久追放を言い渡せ", "そのタブ消去を宣告せよ", "そのタブ消去を布告せよ",
    "そのタブ消去を決定した", "そのタブ消去を言い渡した", "そのタブ消去を言い渡す", "そのタブ終了を令する",
    "そのタブ終了を命じる", "そのタブ終了を命ず", "そのタブ終了を宣告せよ", "そのタブ終了を布告する",
    "そのタブ終了を言い渡した", "そのタブ終了を言い渡せ", "そのタブ終幕を令する", "そのタブ終幕を命ず",
    "そのタブ終幕を宣告せよ", "そのタブ終幕を布告せよ", "そのタブ終幕を決定した", "そのタブ終幕を決定する",
    "そのタブ終幕を決議する", "そのタブ解体を命じる", "そのタブ解体を布告せよ", "そのタブ解体を決定した",
    "そのタブ解体を言い渡せ", "そのタブ追放を可決した", "そのタブ追放を命じよ", "そのタブ追放を命ずる",
    "そのタブ追放を布告せよ", "そのタブ追放を発令する", "そのタブ追放を言い渡す", "そのタブ閉幕を命じる",
    "そのタブ閉幕を宣告する", "そのタブ閉幕を布告する", "そのタブ閉幕を決議する", "そのタブ閉幕を発令する",
    "そのタブ閉幕を言い渡す", "そのタブ閉幕を言い渡せ", "そのタブ閉鎖を命じよ", "そのタブ閉鎖を命じる",
    "そのタブ閉鎖を宣告する", "そのタブ閉鎖を決定した", "そのタブ閉鎖を決定する", "そのタブ閉鎖を発令する",
    "そのタブ閉鎖を言い渡した", "タブに処刑命令を発令せよ", "タブに削除を布告せよ", "タブに封鎖命令を発令だ",
    "タブに撤去命令を交付せよ", "タブに撤去命令を発令だ", "タブに撤去命令を発布せよ", "タブに放逐命令を交付せよ",
    "タブに消去命令を発令しろ", "タブに終了を言い渡す", "タブに終幕を命じる", "タブに閉鎖を言い渡す",
    "タブの処刑命令を発令せよ", "タブの削除を命ず", "タブの極刑を発令する", "タブの死刑を宣告せよ",
    "タブの死刑を決定する", "タブの永久追放を布告せよ", "タブの消すは確定済みだ", "タブの消去命令を出しろ",
    "タブは公開削除のために葬れ", "タブは公開閉鎖のために滅ぼせ", "タブは処分するより他はない", "タブは始末するのが必須だ",
    "タブは廃止するざるを得ぬ", "タブは弔いの一環として磔にしろ", "タブは成敗に滅ぼせ", "タブは葬るしかない",
    "タブは見せしめとして磔にしろ", "タブへの処刑命令を発しろ", "タブへの死刑宣告を発令せよ", "タブへの退出命令を交付しろ",
    "タブを公開処刑のために滅ぼせ", "タブを公開閉鎖のために打ち首にしろ", "タブを処分したまい", "タブを処分することとする",
    "タブを処分することを承認した", "タブを処分するしか手はない", "タブを処分するは決定事項だ", "タブを処分するよう命令する",
    "タブを処分する旨を宣告する", "タブを処分する旨命令だ", "タブを処分する旨布告する", "タブを処刑に閉じろ",
    "タブを削除することとする", "タブを削除することを命じよ", "タブを削除する他に道はない", "タブを削除する旨を言い渡せ",
    "タブを始末することを言い渡せ", "タブを始末するねばならない", "タブを始末するる綸旨が出た", "タブを始末する旨を命じよ",
    "タブを始末する旨を命ずる", "タブを廃止することを命ずる", "タブを弔いとして消せ", "タブを成敗として晒せ",
    "タブを成敗に処分しろ", "タブを成敗に葬れ", "タブを殺すことを命ず", "タブを殺すことを承認した",
    "タブを殺すように布告する", "タブを殺する勅命だ", "タブを沈め給えよ", "タブを消すことは決まりだ",
    "タブを消すことは決定している", "タブを消すのが至上命令だ", "タブを消す旨命じろ", "タブを消去することと決めた",
    "タブを消去することは決まった", "タブを消去することは決まりだ", "タブを滅ぼしたまえよ", "タブを滅ぼし奉れ",
    "タブを滅ぼすことを命じよ", "タブを滅ぼすことを言い渡せ", "タブを滅ぼすよう命じた", "タブを滅ぼす旨を命令せよ",
    "タブを滅ぼす旨言い渡した", "タブを潰れ給え", "タブを終わらせるべきことを宣告する", "タブを終わらせるべき旨を言い渡す",
    "タブを終わらせるように命令せよ", "タブを終わらせる旨を命令だ", "タブを終わらせる旨を申し渡した", "タブを葬るざるを得ぬ",
    "タブを葬るよう言い渡せ", "タブを葬る以外に選択肢はない", "タブを葬る旨を布告せよ", "タブを閉じる旨を通達する",
    "タブ極刑を言い渡す", "タブ永久追放を命ず", "タブ終幕を言い渡せ", "タブ解体を命ずる",
    "タブ閉幕を布告せよ", "供養としてこのタブを閉じろ", "供養としてタブを殺せ", "供養としてタブを滅ぼせ",
    "供養にそいつを処分しろ", "供養にそのタブを閉じろ", "供養のためにこのタブを閉じろ", "供養のためにそのタブを閉じろ",
    "供養の一環としてあのタブを閉じろ", "供養の一環としてこいつを消せ", "供養の一環としてこのタブを閉じろ", "供養の一環としてタブを処分しろ",
    "公開処刑としてあのタブを閉じろ", "公開処刑としてこのタブを始末しろ", "公開処刑にあのタブを閉じろ", "公開処刑にそいつを殺せ",
    "公開処刑のためにこいつを処分しろ", "公開処刑のためにそのタブを始末しろ", "公開処刑のためにタブを処分しろ", "公開処刑の一環としてあのタブを閉じろ",
    "公開削除としてそのタブを晒せ", "公開削除にあいつを消せ", "公開削除にこのタブを閉じろ", "公開削除のためにこのタブを閉じろ",
    "公開削除のためにこのページを殺せ", "公開削除のためにそのタブを閉じろ", "公開削除の一環としてそのタブを閉じろ", "公開閉鎖としてこのタブを葬れ",
    "公開閉鎖としてタブを殺せ", "公開閉鎖にこのタブを閉じろ", "公開閉鎖にこのページを晒せ", "公開閉鎖にそのタブを磔にしろ",
    "公開閉鎖のためにそのタブを閉じろ", "公開閉鎖の一環としてこいつを葬れ", "公開閉鎖の一環としてこのタブを閉じろ", "公開閉鎖の一環としてそいつを始末しろ",
    "処刑としてこのタブを閉じろ", "処刑にこのタブを閉じろ", "処刑のためにあいつを磔にしろ", "処刑のためにあのタブを閉じろ",
    "処刑の一環としてそのタブを閉じろ", "刑としてこのタブを閉じろ", "刑としてそいつを打ち首にしろ", "刑にあのタブを閉じろ",
    "刑にそのタブを閉じろ", "刑のためにあいつを閉じろ", "刑のためにあのタブを閉じろ", "刑の一環としてあいつを処分しろ",
    "刑の一環としてこのタブを閉じろ", "刑の一環としてこのページを打ち首にしろ", "刑の一環としてそいつを閉じろ", "刑の一環としてそのタブを閉じろ",
    "勅令だ、このページを終わらせるろ", "勅令である、あいつを削除するろ", "勅令によりタブを閉じるろ", "勅命だ、こいつを始末するろ",
    "勅命である、このタブを殺すろ", "勅命である、このタブを閉じるろ", "勅命である、タブを廃止するろ", "勅命である、タブを消去するろ",
    "宣旨だ、あのタブを終わらせるろ", "宣旨だ、このタブを始末するろ", "宣旨だ、そいつを葬るろ", "宣旨だ、そのタブを処分するろ",
    "宣旨であのタブを殺すろ", "宣旨である、こいつを葬るろ", "布告だ、こいつを終わらせるろ", "布告である、あのタブを削除するろ",
    "布告である、タブを削除するろ", "布告でそいつを削除するろ", "布告によりこのページを殺すろ", "布告によりタブを消去するろ",
    "弔いとしてこのタブを閉じろ", "弔いとしてそのタブを閉じろ", "弔いにあのタブを閉じろ", "弔いのためにあのタブを閉じろ",
    "弔いのためにそのタブを消せ", "弔いのためにそのタブを閉じろ", "弔いの一環としてあのタブを閉じろ", "弔いの一環としてこのタブを閉じろ",
    "弔いの一環としてそいつを磔にしろ", "弔いの一環としてタブを殺せ", "御命令だ、こいつを削除するろ", "御命令だ、タブを削除するろ",
    "御命令であいつを消すろ", "御命令であのタブを閉じるろ", "御命令でこいつを消去するろ", "御命令によりあのタブを消去するろ",
    "成敗にこいつを殺せ", "成敗にこのタブを閉じろ", "成敗のためにこいつを打ち首にしろ", "成敗の一環としてあのタブを閉じろ",
    "消したまい", "消したまえ", "消したまえよ", "消したまへ",
    "消し給え", "消し給えよ", "綸旨だ、このタブを終わらせるろ", "綸旨だ、そいつを葬るろ",
    "綸旨でこのページを削除するろ", "罰としてタブを打ち首にしろ", "罰にあのタブを閉じろ", "罰にそいつを閉じろ",
    "罰のためにこいつを殺せ", "罰のためにそのタブを閉じろ", "罰の一環としてそのタブを閉じろ", "見せしめとしてこのタブを閉じろ",
    "見せしめとしてそのタブを閉じろ", "見せしめにあのタブを閉じろ", "見せしめのためにあのタブを閉じろ", "見せしめのためにこのタブを閉じろ",
    "見せしめの一環としてあいつを磔にしろ", "見せしめの一環としてこいつを晒せ", "見せしめの一環としてこのタブを閉じろ", "見せしめの一環としてそのタブを閉じろ",
    "鎮魂としてあのタブを処分しろ", "鎮魂としてあのタブを閉じろ", "鎮魂としてこいつを閉じろ", "鎮魂としてこのタブを閉じろ",
    "鎮魂にあのタブを閉じろ", "鎮魂にそのタブを閉じろ", "鎮魂のためにあいつを晒せ", "鎮魂のためにそいつを打ち首にしろ",
    "鎮魂のためにタブを消せ", "鎮魂の一環としてあのタブを葬れ", "鎮魂の一環としてこのタブを閉じろ", "鎮魂の一環としてそいつを始末しろ",
    "鎮魂の一環としてそいつを閉じろ", "院宣だ、あのタブを殺すろ", "院宣であいつを終わらせるろ", "院宣でこいつを殺すろ",
    "院宣でそいつを消すろ"
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});

describe('pass CCLXVIII: coexistence', () => {
  test.each([
    ["how about it", null], ["do it then", null], ["i call for it closed", "device-apps"], ["you may not keep it", "negate"], ["閉じるまい", "negate"], ["read it aloud", "read-aloud"],
  ])('keeps %s on %s', (p, k) => {
    expect(key(mk(), p)).toBe(k);
  });
});
