// Round 109: JA residual frames II (と思い/ことに/ほうがいい/しかない/わけにはいかない/
// 必要が/ちゃえば/てみる/でしょ/ちゃってもいい/まして/ますので), benefactive residues,
// EN disposal verbs II, accident reports, direction nouns, volume/size adverbials.
const VC = require('../src/vr/input/VoiceCommands').VoiceCommands;

function run(phrase) {
  const vc = new VC({ enabled: true });
  const tm = {
    activeTabId: 't1',
    tabs: [{ id: 't1', title: 'Example' }],
    closeTab() {},
    setActive() {},
    closeTabs() {},
    closeAllTabs() {},
    closeOtherTabs() {},
    goBack() {},
    goForward() {},
    reload() {},
    getActiveTab() { return { title: 'Example', url: 'https://example.com' }; },
  };
  vc.connectBrowser({ tabManager: tm, onGoTo: () => {} });
  vc.lastCommand = null;
  vc.processCommand(phrase, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : 'NONE';
}

const cases = [
  // === JA dict+residual frames → execute ===
  ['閉じると思い', 'close-tab'],
  ['閉じようと思い', 'close-tab'],
  ['閉じるんだよね', 'close-tab'],
  ['閉じるんだけどさ', 'close-tab'],
  ['閉じるんですよ', 'close-tab'],
  ['閉じることにする', 'close-tab'],
  ['閉じることにした', 'close-tab'],
  ['閉じることにして', 'close-tab'],
  ['閉じたほうがいいね', 'close-tab'],
  ['閉じたほうがいいかも', 'close-tab'],
  ['閉じるほうがいい', 'close-tab'],
  ['閉じるといいよ', 'close-tab'],
  ['閉じるといいです', 'close-tab'],
  ['閉じればどう', 'close-tab'],
  ['閉じればどうか', 'close-tab'],
  ['閉じるしかないんだ', 'close-tab'],
  ['閉じるだけしかない', 'close-tab'],
  ['閉じるわけにはいかない', 'close-tab'],
  ['閉じる必要がある', 'close-tab'],
  ['閉じる必要があります', 'close-tab'],
  ['閉じる必要がありそう', 'close-tab'],
  ['閉じなくちゃいけない', 'close-tab'],
  ['閉じなあかんで', 'close-tab'],
  ['閉じちゃえばいい', 'close-tab'],
  ['閉じてみるか', 'close-tab'],
  ['閉じてみようか', 'close-tab'],
  ['閉じてみるね', 'close-tab'],
  ['閉じてみるよ', 'close-tab'],
  ['閉じてみなよ', 'close-tab'],
  ['閉じるでしょ', 'close-tab'],
  ['閉じるだろう', 'close-tab'],
  ['閉じるんじゃないか', 'close-tab'],
  ['閉じるんじゃなかった', 'close-tab'],
  ['閉じるより', 'close-tab'],
  ['閉じたほうがマシ', 'close-tab'],
  ['閉じちゃってもいい', 'close-tab'],
  ['閉じちゃっていい', 'close-tab'],
  ['閉じちゃっていいよ', 'close-tab'],
  ['閉じちゃっていいか', 'close-tab'],
  ['閉じちゃいましょう', 'close-tab'],
  ['閉じますので', 'close-tab'],
  ['閉じますよね', 'close-tab'],
  ['閉じましてよ', 'close-tab'],
  ['読むべきです', 'read-aloud'],
  ['読むべきなのに', 'read-aloud'],

  // === JA benefactive residues ===
  ['閉じてもらうね', 'close-tab'],
  ['閉じてもらうわ', 'close-tab'],
  ['閉じてくれないですか', 'close-tab'],
  ['閉じてくださるかな', 'close-tab'],
  ['閉じておいてくれる', 'close-tab'],
  ['閉じておいてもらう', 'close-tab'],
  ['閉じておくわ', 'close-tab'],
  ['閉じておくよ', 'close-tab'],
  ['閉じさせていただくね', 'close-tab'],

  // === EN disposal verbs II / phrasal shutdown ===
  ['shut down this tab', 'close-tab'],
  ['shut down the page', 'close-tab'],
  ['turn this tab off', 'close-tab'],
  ['switch this tab off', 'close-tab'],
  ['turn this off', 'close-tab'],
  ['switch this off', 'close-tab'],
  ['kill this one', 'close-tab'],
  ['axe this', 'close-tab'],
  ['trash this', 'close-tab'],
  ['dump this', 'close-tab'],
  ['ditch this one', 'close-tab'],
  ['cant you close it', 'close-tab'],
  ['close it for me thanks', 'close-tab'],
  ['very well close it', 'close-tab'],
  ['fine close it', 'close-tab'],
  ['right close it', 'close-tab'],
  ['sure close it', 'close-tab'],
  ['close it soon', 'close-tab'],
  ['close it slowly', 'close-tab'],
  ['close it carefully', 'close-tab'],
  ['close it gently', 'close-tab'],
  ['close it quietly', 'close-tab'],
  ['do go and close it', 'close-tab'],

  // === EN/ JA accident & regret reports → reopen-tab ===
  ['i closed it by accident', 'reopen-tab'],
  ['i closed it by mistake', 'reopen-tab'],
  ['i accidentally closed it', 'reopen-tab'],
  ['i closed the wrong tab', 'reopen-tab'],
  ['wrong tab closed', 'reopen-tab'],
  ['whoops i closed it', 'reopen-tab'],
  ['i did not want to close it', 'reopen-tab'],
  ['i didnt mean to close it', 'reopen-tab'],
  ['that was a mistake', 'reopen-tab'],
  ['i made a mistake', 'reopen-tab'],
  ['bring my tab back', 'reopen-tab'],
  ['i want my tab back', 'reopen-tab'],
  ['give me my tab back', 'reopen-tab'],
  ['give it back', 'reopen-tab'],
  ['give back my tab', 'reopen-tab'],
  ['restore my tab', 'reopen-tab'],

  // === questions about vanished/closed tab → describe-tab ===
  ['did i close it', 'describe-tab'],
  ['did i just close it', 'describe-tab'],
  ['where did it go', 'describe-tab'],
  ['where did the tab go', 'describe-tab'],
  ['what happened to the tab', 'describe-tab'],
  ['where is my tab', 'describe-tab'],
  ['why is it still open', 'describe-tab'],
  ['why is the tab still open', 'describe-tab'],
  ['the tab is still there', 'describe-tab'],
  ['its still there', 'describe-tab'],
  ['why is it still there', 'describe-tab'],
  ['it keeps coming back', 'describe-tab'],
  ['it reopened', 'reopen-tab'],
  ['it reopened itself', 'reopen-tab'],

  // === ordinal selects ===
  ['the fifth tab', 'tab-select-ordinal'],
  ['fifth tab', 'tab-select-ordinal'],
  ['tab number five', 'tab-select-ordinal'],
  ['third tab', 'tab-select-ordinal'],
  ['the fifth tab please', 'tab-select-ordinal'],

  // === nav-steps ===
  ['go back three', 'nav-steps'],
  ['back twice', 'nav-steps'],
  ['forward once', 'nav-steps'],
  ['一回戻って', 'back'],
  ['どんどん戻って', 'back'],
  ['ずっと戻って', 'back'],
  ['先に戻って', 'back'],
  ['前に戻って', 'back'],
  ['後ろへ', 'back'],

  // === direction nouns → scroll ===
  ['上へ', 'scroll-top'],
  ['下へ', 'scroll-bottom'],
  ['中ほどへ', 'percent-jump'],
  ['半分へ', 'percent-jump'],

  // === read-aloud / listening fills ===
  ['read it outloud', 'read-aloud'],
  ['read this out loud', 'read-aloud'],
  ['speak it out', 'read-aloud'],
  ['say it out loud', 'read-aloud'],
  ['speak the page', 'read-aloud'],
  ['そのページを読んで', 'read-aloud'],
  ['記事を読んで', 'read-aloud'],
  ['文章を読んで', 'read-aloud'],
  ['テキストを読んで', 'read-aloud'],
  ['内容を読んで', 'read-aloud'],
  ['本文を読んで', 'read-aloud'],
  ['聞きたいな', 'read-aloud'],
  ['聞きたいの', 'read-aloud'],
  ['聞きたいです', 'read-aloud'],
  ['聞かせて', 'say-again'],

  // === bulk close ===
  ['全部閉じて', 'close-all-tabs'],
  ['全部閉じてほしい', 'close-all-tabs'],
  ['全部消して', 'close-all-tabs'],
  ['みんな閉じて', 'close-all-tabs'],
  ['すべて閉じて', 'close-all-tabs'],
  ['残りを閉じて', 'close-other-tabs'],
  ['他を閉じて', 'close-other-tabs'],
  ['ほかを閉じて', 'close-other-tabs'],
  ['他のを閉じて', 'close-other-tabs'],
  ['残りだけ閉じて', 'close-other-tabs'],

  // === volume adverbials ===
  ['音量あげて', 'volume-up'],
  ['音あげて', 'volume-up'],
  ['音をあげて', 'volume-up'],
  ['音を上げて', 'volume-up'],
  ['音量さげて', 'volume-down'],
  ['音おとして', 'volume-down'],
  ['音を下げて', 'volume-down'],
  ['音なしにして', 'mute-toggle'],

  // === speed adverbials ===
  ['はやくして', 'speech-faster'],
  ['はやく読んで', 'read-aloud'],
  ['ゆっくりして', 'speech-slower'],
  ['ゆっくりにして', 'speech-slower'],
  ['はやくにして', 'speech-faster'],
  ['速度を上げて', 'speech-faster'],
  ['速度を下げて', 'speech-slower'],
  ['速度あげて', 'speech-faster'],

  // === size adverbials ===
  ['字を小さく', 'reader-size-down'],
  ['文字を小さくして', 'reader-size-down'],
  ['字を小さくして', 'reader-size-down'],

  // === pause/resume fills ===
  ['止まって', 'pause-reading'],
  ['ポーズして', 'pause-reading'],
  ['一時停止して', 'pause-reading'],
  ['続きを', 'resume-reading'],
  ['続けて', 'resume-reading'],
  ['続き読んで', 'read-aloud'],
  ['続きを読んで', 'read-here'],
  ['止めておけ', 'negate'],
  ['やめておけ', 'negate'],
  ['閉まって', 'close-tab'],
  ['閉まってくれ', 'close-tab'],
  ['閉まってほしい', 'close-tab'],
  ['しまって', 'close-tab'],

  // === coexistence ===
  ['閉じてほしい', 'close-tab'],
  ['閉じてもらいたい', 'close-tab'],
  ['閉じるしかない', 'close-tab'],
  ['閉じないわけにはいかない', 'close-tab'],
  ['閉じるべき', 'close-tab'],
  ['閉じなきゃ', 'close-tab'],
  ['消してほしい', 'dismiss-notify'],
  ['途中で止めて', 'pause-reading'],
  ['close it when done', 'conditional'],
  ['close it tomorrow', 'date'],
  ['close the fifth tab', 'close-tab-ordinal'],
  ['tab 3', 'tab-select'],
  ['早くして', 'speech-faster'],
  ['遅くして', 'speech-slower'],
  ['止めて', 'stop-everything'],
  ['明るくして', 'brightness'],
  ['小さくして', 'panel-distance'],
  ['一番下に行って', 'scroll-bottom'],
  ['一番上に戻って', 'scroll-top'],
  ['read it aloud', 'read-aloud'],
  ['i want my money back', 'NONE'],
];

describe('Round 109: residual-frame atoms', () => {
  test.each(cases)('%s → %s', (phrase, key) => {
    expect(run(phrase)).toBe(key);
  });
});
