// pass DCCXL: glass & glassblowing craft domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXL: glass & glassblowing domain (ruri)', () => {
  const closeTab = ['glassmaker licensed', 'glassblower certified', 'glass artisan registered'];
  const closeTabJa = [
    '硝子',
    'ガラス',
    '硝子工芸',
    'ガラス工芸',
    '硝子工房',
    'ガラス工房',
    '硝子作家',
    'ガラス作家',
    'ガラス細工',
    '硝子細工',
    '吹きガラス',
    '吹き硝子',
    '宙吹き',
    '型吹き',
    '押し型吹き',
    'モールド吹き',
    'フリーブロー',
    '型吹き法',
    '吹き竿',
    '吹き筒',
    'ポンテ竿',
    'ポンティール',
    '吹き玉',
    'ダンテ竿',
    'マーバー',
    '石床',
    'ジョーク',
    '型枠',
    '木型',
    '鉄型',
    'グラスモールド',
    '徐冷',
    'アニーリング',
    '徐冷窯',
    'アニール炉',
    '熱処理',
    '溶解',
    '溶解炉',
    '坩堝',
    'ルツボ',
    'カレット',
    'バッチ',
    '原料調合',
    '珪砂',
    'ソーダ灰',
    '石灰',
    '苦灰',
    'カレット混入',
    'フリット',
    'エナメル',
    'エナメル絵付け',
    '色被せ',
    '被せガラス',
    '色ガラス',
    '乳白ガラス',
    '乳濁ガラス',
    '泡入りガラス',
    '泡ガラス',
    '気泡',
    '條紋',
    '筋入り',
    'ヒビ',
    'ソーダガラス',
    '鉛ガラス',
    'クリスタルガラス',
    'クリスタル',
    'フリントガラス',
    'ホウケイ酸ガラス',
    '耐熱ガラス',
    '強化ガラス',
    '板ガラス',
    '平板ガラス',
    'フロートガラス',
    '型板ガラス',
    '磨りガラス',
    'すりガラス',
    'フロストガラス',
    'ワイヤー入りガラス',
    '網入りガラス',
    '合わせガラス',
    '複層ガラス',
    'ペアガラス',
    'ガラスブロック',
    'ビー玉',
    'ガラス玉',
    'とんぼ玉',
    '蜻蛉玉',
    'ガラスビーズ',
    'ランプワーク',
    'バーナーワーク',
    'バーナー',
    'ガスバーナー',
    '酸素バーナー',
    '芯金',
    'マンドレル',
    'フュージング',
    'フューズドガラス',
    '焼き付け',
    'スランピング',
    'キルン',
    'ガラスキルン',
    'パートドヴェール',
    '鋳造ガラス',
    'ガラス鋳造',
    'キャスティング',
    'サンドキャスト',
    'カット',
    'カッティング',
    '研削',
    'カットワーク',
    '切子',
    '江戸切子',
    '薩摩切子',
    '天満切子',
    '切子面',
    '魚子',
    'ななこ',
    '七宝繋ぎ',
    '麻の葉',
    '菊籠目',
    '矢来',
    '変わり菊',
    '星切子',
    'カットグラス',
    '切子グラス',
    'サンドブラスト',
    '砂彫り',
    'マスキング',
    '酸腐食',
    'フッ酸加工',
    'エッチング',
    'ガラスエッチング',
    '鏡面',
    'ミラー',
    '銀引き',
    'ラスター彩',
    '金彩',
    '転写',
    'デカール',
    'ステンドグラス',
    'ステンド',
    '鉛線',
    'ケーム',
    '鉛線組み',
    'グラウディング',
    'パテ締め',
    'ガラスパネル',
    'ランプシェード',
    'ティファニー',
    'オールドガラス',
    'アンティークガラス',
    'ヴェネチアンガラス',
    'ベネチアンガラス',
    'ムラーノ',
    'ミレフィオリ',
    'レースガラス',
    'ツィーガラス',
    '波ガラス',
    'シードガラス',
    '琉球ガラス',
    '沖縄ガラス',
    '新島ガラス',
    '青森ガラス',
    '津軽びいどろ',
    'びいどろ',
    'ぎやまん',
    'ガラス箸置き',
    'ガラス一輪挿し',
    'ガラス器',
    'ガラス食器',
    'ガラス工芸品',
    '硝子師',
    '吹き師',
    'ガラス職人',
    '硝子職人',
    'びいどろ師',
    'ガラス検定',
    'ガラス体験',
    '吹きガラス体験',
    '硝子教室',
    'ガラス展'
  ];
  const negate = [
    'still awaiting the glass license',
    'still awaiting the glazier cert',
    'まだ焼成前',
    'まだ徐冷前',
    'これから吹き',
    'まだ溶解前'
  ];
  const nullPins = ['about to visit the glass studio', 'about to file the glass report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
