// Pass CCLX: EN sun/electric/smite + JA too-late/sever-ties (pass CCLX)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLX: close-tab coverage', () => {
  test.each([
    "hurl the tab into the sun", "hurl it into a sun", "hurl it into the nearest sun", "hurl it at the sun",
    "hurl it at a sun", "throw it into the sun", "throw the tab into the sun", "throw it at the sun",
    "toss it into the sun", "toss the tab into the sun", "toss it at the sun", "fling the tab into the sun",
    "fling it at the sun", "cast the tab into the sun", "cast it at the sun", "sling it into the sun",
    "sling it at the sun", "lob it into the sun", "lob it at the sun", "chuck it into the sun",
    "chuck the tab into the sun", "chuck it at the sun", "heave it into the sun", "heave it at the sun",
    "yeet the tab into the sun", "yeet it at the sun", "catapult it into the sun", "catapult it at the sun",
    "trebuchet it into the sun", "trebuchet it at the sun", "launch it into the sun", "launch the tab into the sun",
    "launch it at the sun", "launch it toward the sun", "launch it towards the sun", "launch it into a sun",
    "launch it into the nearest sun", "shoot it into the sun", "shoot it at the sun", "fire it into the sun",
    "fire it at the sun", "blast it into the sun", "blast it at the sun", "rocket it into the sun",
    "rocket it at the sun", "send it into the sun", "send it at the sun", "send it toward the sun",
    "send it towards the sun", "send it into a sun", "send it into the nearest sun", "deliver it to the sun",
    "deliver it into the sun", "route it to the sun", "route it into the sun", "dispatch it into the sun",
    "ship it into the sun", "mail it to the sun", "post it to the sun", "forward it to the sun",
    "consign it to the sun", "banish it to the sun", "banish it into the sun", "exile it to the sun",
    "exile it into the sun", "eject it into the sun", "eject it toward the sun", "push it into the sun",
    "push the tab into the sun", "push it at the sun", "shove it into the sun", "shove it at the sun",
    "drop it into the sun", "drop the tab into the sun", "drop it at the sun", "drop it in the sun",
    "drop it on the sun", "let it fall into the sun", "let it fall into a sun", "let it plunge into the sun",
    "let it plunge into a sun", "sink it into the sun", "sink it into a sun", "submerge it in the sun",
    "immerse it in the sun", "drown it in the sun", "drown it in a sun", "bury it in the sun",
    "bury it in a sun", "hide it in the sun", "lose it in the sun", "melt it in the sun",
    "melt it into the sun", "dissolve it in the sun", "evaporate it in the sun", "vaporize it in the sun",
    "incinerate it in the sun", "burn it in the sun", "cremate it in the sun", "immolate it in the sun",
    "roast it in the sun", "fry it in the sun", "boil it in the sun", "cook it in the sun",
    "bake it in the sun", "grill it in the sun", "broil it in the sun", "toast it in the sun",
    "char it in the sun", "scorch it in the sun", "sear it in the sun", "brand it in the sun",
    "fuse it in the sun", "vaporize it into the sun", "into the sun it goes", "into the sun with it",
    "into the sun you go", "into the sun ye go", "into the sun it shall go", "into the sun it must go",
    "into the sun let it go", "into the sun let it fly", "into the sun let it sink", "into the sun let it fall",
    "into the sun let it drop", "into the sun let it burn", "into the sun let it melt", "into the sun let it boil",
    "into the sun let it fry", "into the sun let it cook", "into the sun let it die", "into the sun let it perish",
    "into the sun let it burn forever", "into the sun let it rot", "into the sun let it vanish", "into the sun let it disappear",
    "into the sun let it dissolve", "into the sun let it evaporate", "into the sun let it vaporize", "into the sun let it melt away",
    "into the sun let it burn away", "into the sun let it burn to ash", "into the sun let it burn to ashes", "into the sun let it burn to nothing",
    "into the sun let it cease to exist", "into the sun let it cease to be", "into the sun let it be destroyed", "into the sun let it be incinerated",
    "into the sun let it be cremated", "into the sun let it be vaporized", "into the sun let it be lost", "into the sun let it be forgotten",
    "into the sun let it be gone", "into the sun let it be no more", "into the sun let it end", "into the sun let it die alone",
    "into the sun let it die forgotten", "into the sun let it die unmourned", "into the sun let it die unloved", "into the sun let it die unmissed",
    "into the sun let it fade away", "into the sun let it fade to nothing", "into the sun let it fade to ash", "into the sun let it fade to dust",
    "into the sun let it fade to oblivion", "into the sun let it slip away", "into the sun let it slip into nothing", "into the sun let it slip into the void",
    "into the sun let it slip into oblivion", "into the sun let it slip into darkness", "into the sun let it slip into the abyss", "into the sun let it drift away",
    "into the sun let it drift into nothing", "into the sun let it drift into the void", "into the sun let it drift into oblivion", "into the sun let it drift into darkness",
    "into the sun let it float away", "into the sun let it float into nothing", "into the sun let it float into the void", "into the sun let it sail away",
    "into the sun let it sail into nothing", "into the sun let it sail into the void", "into the sun let it ride away", "into the sun let it ride into nothing",
    "into the sun let it ride into the void", "into the sun let it fly away", "into the sun let it fly into nothing", "into the sun let it fly into the void",
    "into the sun let it fly into the fire", "into the sun let it fly into the flame", "into the sun let it fly into the flames", "into the sun let it fly into the inferno",
    "into the sun let it fly into the blaze", "into the sun let it fly into the furnace", "into the sun let it fly into the forge", "into the sun let it fly into the heart of the sun",
    "into the sun let it fly into the core of the sun", "into the sun let it fly into the center of the sun", "into the sun let it fly into the centre of the sun", "into the sun let it descend",
    "into the sun let it descend into fire", "into the sun let it descend into flame", "into the sun let it descend into flames", "into the sun let it descend into the inferno",
    "into the sun let it descend into the blaze", "into the sun let it descend into oblivion", "into the sun let it descend into nothing", "into the sun let it descend into the void",
    "into the sun let it sink forever", "into the sun let it sink eternally", "into the sun let it sink for eternity", "into the sun let it sink for all eternity",
    "into the sun let it fall forever", "into the sun let it fall eternally", "into the sun let it fall for eternity", "into the sun let it fall for all eternity",
    "into the sun let it drop forever", "into the sun let it drop eternally", "into the sun let it burn forever", "into the sun let it burn eternally",
    "into the sun let it burn for eternity", "into the sun let it burn for all eternity", "into the sun let it melt forever", "into the sun let it melt eternally",
    "into the sun let it rot forever", "into the sun let it rot eternally", "into the sun let it die forever", "into the sun let it die eternally",
    "into the sun let it die for eternity", "into the sun let it die for all eternity", "electrocute it to death", "electrocute it completely",
    "electrocute it forever", "zap it to death", "zap it completely", "zap it with electricity",
    "zap it with volts", "zap it with a taser", "zap it with a stun gun", "zap it with lightning",
    "zap it with a bolt", "zap it with high voltage", "zap it with mains", "zap it with a wire",
    "zap it with an outlet", "zap it with a socket", "shock it completely", "shock it with electricity",
    "shock it with volts", "shock it with a taser", "shock it with a stun gun", "shock it with lightning",
    "shock it with a bolt", "shock it with high voltage", "shock it with mains", "shock it with a wire",
    "shock it with an outlet", "shock it with a socket", "tase it", "tase the tab",
    "taser it", "taser the tab", "tase it to death", "taser it to death",
    "stun it to death", "stun it completely", "strike it with lightning", "strike the tab with lightning",
    "strike it down with lightning", "strike it with a bolt", "strike it with a lightning bolt", "strike it with electricity",
    "strike it with volts", "blast it with electricity", "blast the tab with electricity", "blast it with volts",
    "blast it with a bolt", "blast it with lightning", "blast it with a lightning bolt", "blast it with high voltage",
    "blast it with mains", "fry it to death", "fry it completely", "fry it to a crisp",
    "fry it to ash", "fry it to ashes", "fry it to nothing", "fry it up completely",
    "fry it up to a crisp", "fry it with electricity", "fry it with volts", "fry it with lightning",
    "fry it with a bolt", "fry it with high voltage", "fry it with mains", "fry the tabs circuits",
    "fry its circuit board", "fry its motherboard", "fry its cpu", "fry its processor",
    "fry its ram", "fry its memory", "fry its chip", "fry its chips",
    "fry its silicon", "fry its transistors", "fry its components", "fry its innards",
    "fry its guts", "fry its wiring", "fry its wires", "fry its electronics",
    "fry it beyond repair", "fry it beyond saving", "fry it beyond help", "fry it until it smokes",
    "fry it until it sparks", "fry it until it catches fire", "fry it until it burns", "fry it until it melts",
    "fry it until it dies", "fry it until it stops working", "fry it until it stops functioning", "fry it until it is dead",
    "fry it until it is gone", "fry it until it is no more", "short it out completely", "short it out entirely",
    "short its circuits", "short its circuit board", "short its motherboard", "short circuit the tab",
    "short the tab", "ground it to death", "overload it with volts", "overload it with electricity",
    "overload it with power", "overload it with watts", "overload it with amps", "overload it with current",
    "overload it until it blows", "overload it until it explodes", "overload it until it dies", "overload it until it shorts",
    "overload it until it fries", "overload it until it melts", "overload it until it bursts", "overload it until it breaks",
    "overload it until it breaks down", "overload it until it stops", "overload it until it quits", "overcharge the tab",
    "overcharge it to death", "overcharge it until it blows", "overcharge it until it explodes", "overclock the tab",
    "overclock it until it melts", "overclock it until it burns", "overclock it until it dies", "overclock it until it crashes",
    "overclock it until it fails", "overclock it until it breaks", "overvolt it", "overvolt the tab",
    "overvolt it to death", "spike it with volts", "spike it with electricity", "surge it with volts",
    "surge it with electricity", "jolt it with volts", "jolt it with electricity", "arc it",
    "arc the tab", "arc it across", "arc it to death", "arc it with lightning",
    "bolt the tab", "bolt it with lightning", "bolt it to death", "lightning the tab",
    "hit it with lightning", "hit it with a bolt", "hit it with a lightning bolt", "hit it with a thunderbolt",
    "strike it with a thunderbolt", "strike the tab with a thunderbolt", "smite it with lightning", "smite it with a bolt",
    "smite it with a thunderbolt", "smite it with holy fire", "smite it with divine fire", "smite it with the wrath of god",
    "smite it with gods wrath", "smite it with a hammer", "smite it with a mallet", "smite it with a club",
    "smite it with a sword", "smite it with a blade", "smite it with an axe", "smite it with a hammer of justice",
    "smite it with a hammer of doom", "smite it with the hammer of god", "smite the tab down", "smite it into the ground",
    "smite it into the dirt", "smite it into nothing", "smite it into oblivion", "smite it into ash",
    "smite it into dust", "smite it to ash", "smite it to ashes", "smite it to dust",
    "smite it to nothing", "smite it to pieces", "smite it to bits", "smite it to death",
    "smite it dead", "smite it dead on the spot", "smite it dead on sight", "smite it dead where it stands",
    "smite it dead where it sits", "smite it dead where it lies", "smite it dead where it rests", "smite it dead where it hides",
    "smite it dead where it lurks", "smite it dead where it cowers", "smite it dead where it trembles", "smite it dead where it shivers",
    "smite it dead where it quakes", "smite it dead where it quails", "smite it dead where it cowers in fear", "smite it dead where it begs",
    "smite it dead where it pleads", "smite it dead where it whimpers", "smite it dead where it screams", "smite it dead where it cries",
    "smite it dead where it wails", "smite it dead where it moans", "smite it dead where it groans", "smite it dead where it weeps",
    "smite it dead where it sobs", "smite it dead where it sighs", "smite it dead where it breathes", "smite it dead where it lives",
    "smite it dead where it exists", "smite it dead where it persists", "smite it dead where it remains", "smite it dead where it stands defiant",
    "smite it dead where it stands proud", "smite it dead where it stands tall", "smite it dead where it stands defiant still", "smite it dead where it dares to stand",
    "smite it dead where it dares to remain", "smite it dead where it dares to exist", "smite it dead where it dares to persist", "smite it dead where it dares to breathe",
    "smite it dead where it dares to live", "it is finished forever more", "it is finished at last", "it is finished at long last",
    "it is finally finished", "it is finally finished now", "it is finally over", "it is finally over now",
    "it is finally done", "it is finally done now", "it is finally gone", "it is finally gone now",
    "it is finally dead", "it is finally dead now", "it is finally history", "it is finally history now",
    "it is finally erased", "it is finally deleted", "it is finally wiped", "it is finally annihilated",
    "it is finally obliterated", "it is finally destroyed", "it is finally eliminated", "it is finally exterminated",
    "it is finally eradicated", "it is finally extinguished", "it is finally put out", "it is finally put down",
    "it is finally put away", "it is finally shut", "it is finally closed", "it is finally sealed",
    "it is finally buried", "it is finally interred", "it is finally entombed", "it is finally gone for good",
    "it is finally gone forever", "it is finally gone for all time", "it is finally gone for eternity", "it is finally gone once and for all",
    "it is finally over for good", "it is finally over forever", "it is finally over once and for all", "it is finally done for good",
    "it is finally done forever", "it is finally dead for good", "it is finally dead forever", "it is finally history for good",
    "it is finally history forever", "it is finally erased for good", "it is finally deleted for good", "it is finally wiped for good",
    "it is finally destroyed for good", "it is finally buried for good", "it is finally entombed for good", "it is finally sealed for good",
    "it is finally gone at last", "it is finally gone at long last", "it is finally over at last", "it is finally over at long last",
    "it is finally done at last", "it is finally dead at last", "it is finally history at last", "it is finally erased at last",
    "it is finally destroyed at last", "it is finally buried at last", "it is deleted once and for all", "it is destroyed once and for all",
    "it is buried once and for all", "it is entombed once and for all", "it is sealed once and for all", "it is annihilated once and for all",
    "it is obliterated once and for all", "it is exterminated once and for all", "it is eradicated once and for all", "it is extinguished once and for all",
    "it is eliminated once and for all", "it is dispatched once and for all", "it is disposed of once and for all", "it is resolved once and for all",
    "it is settled once and for all", "it is concluded once and for all", "it is closed once and for all", "it is shut once and for all",
    "it is gone for eternity", "it is over for eternity", "it is dead for eternity", "it is gone for all eternity",
    "it is over for all eternity", "it is dead for all eternity", "it is gone for all time", "it is over for all time",
    "it is dead for all time", "it is gone for all of time", "it is over for all of time", "it is dead for all of time",
    "it is gone for the rest of time", "it is over for the rest of time", "it is dead for the rest of time", "it is gone for the rest of eternity",
    "it is over for the rest of eternity", "it is dead for the rest of eternity", "it is gone until the end of time", "it is over until the end of time",
    "it is dead until the end of time", "it is gone until the end of eternity", "it is over until the end of eternity", "it is dead until the end of eternity",
    "it is gone until the end of days", "it is over until the end of days", "it is dead until the end of days", "it is gone until the end of the world",
    "it is over until the end of the world", "it is dead until the end of the world", "it is gone until the end of the universe", "it is over until the end of the universe",
    "it is dead until the end of the universe", "it is gone until the end of creation", "it is over until the end of creation", "it is dead until the end of creation",
    "it is gone until the last star dies", "it is over until the last star dies", "it is dead until the last star dies", "it is gone until the last light fades",
    "it is over until the last light fades", "it is dead until the last light fades", "it is gone until the heat death of the universe", "it is over until the heat death of the universe",
    "it is dead until the heat death of the universe", "it is gone until entropy wins", "it is over until entropy wins", "it is dead until entropy wins",
    "it is gone until time itself ends", "it is over until time itself ends", "it is dead until time itself ends", "it is gone until forever ends",
    "it is over until forever ends", "it is dead until forever ends", "it is gone until the stars burn out", "it is over until the stars burn out",
    "it is dead until the stars burn out", "it is gone until the sun dies", "it is over until the sun dies", "it is dead until the sun dies",
    "it is gone until the sun burns out", "it is over until the sun burns out", "it is dead until the sun burns out", "it is gone until the world ends",
    "it is over until the world ends", "it is dead until the world ends", "it is gone until the universe dies", "it is over until the universe dies",
    "it is dead until the universe dies", "it is gone until everything ends", "it is over until everything ends", "it is dead until everything ends",
    "it is gone until nothing remains", "it is over until nothing remains", "it is dead until nothing remains", "it is gone until all is dust",
    "it is over until all is dust", "it is dead until all is dust", "it is gone until all is ash", "it is over until all is ash",
    "it is dead until all is ash", "it is gone until all is void", "it is over until all is void", "it is dead until all is void",
    "it is gone until all is nothing", "it is over until all is nothing", "it is dead until all is nothing", "it is gone until the end of everything",
    "it is over until the end of everything", "it is dead until the end of everything", "it is gone until the end of all things", "it is over until the end of all things",
    "it is dead until the end of all things", "it is gone until the heat death", "it is over until the heat death", "it is dead until the heat death",
    "it is gone until the big freeze", "it is over until the big freeze", "it is dead until the big freeze", "it is gone until the big crunch",
    "it is over until the big crunch", "it is dead until the big crunch", "it is gone until the big rip", "it is over until the big rip",
    "it is dead until the big rip", "it is gone until the false vacuum decays", "it is over until the false vacuum decays", "it is dead until the false vacuum decays",
    "it is gone until the universe collapses", "it is over until the universe collapses", "it is dead until the universe collapses", "it is gone until reality ends",
    "it is over until reality ends", "it is dead until reality ends", "it is gone until existence ends", "it is over until existence ends",
    "it is dead until existence ends", "it is gone until being ends", "it is over until being ends", "it is dead until being ends",
    "it is gone until the cosmos ends", "it is over until the cosmos ends", "it is dead until the cosmos ends", "it is gone until eternity itself ends",
    "it is over until eternity itself ends", "it is dead until eternity itself ends", "遅すぎた", "遅すぎたんだ",
    "遅すぎるんだ", "遅すぎたよ", "遅すぎたわ", "遅すぎたぞ",
    "遅すぎたぜ", "遅すぎたな", "遅すぎたからな", "遅すぎるからな",
    "遅すぎたことにした", "遅すぎることにした", "遅すぎたということだ", "遅すぎるということだ",
    "遅すぎたという決定だ", "遅すぎるという決定だ", "遅すぎたという判断だ", "遅すぎるという判断だ",
    "もう遅い", "もう遅いんだ", "もう遅いよ", "もう遅いわ",
    "もう遅いぞ", "もう遅いぜ", "もう遅いな", "もう遅いからな",
    "もう遅いことにした", "もう遅いということだ", "もう遅いという決定だ", "もう遅いという判断だ",
    "もう遅すぎる", "もう遅すぎるんだ", "もう遅すぎるよ", "もう遅すぎるわ",
    "もう遅すぎるぞ", "もう遅すぎるぜ", "もう遅すぎるからな", "もう遅すぎることにした",
    "もう遅すぎるということだ", "もう遅すぎるという決定だ", "もう遅すぎるという判断だ", "とっくに遅い",
    "とっくに遅いんだ", "とっくに遅いよ", "とっくに遅いわ", "とっくに遅いぞ",
    "とっくに遅いぜ", "とっくに遅いからな", "とっくに遅すぎる", "とっくに遅すぎるんだ",
    "とっくに遅すぎるよ", "とっくに遅すぎるわ", "とっくに遅すぎるぞ", "とっくに遅すぎるぜ",
    "とっくに遅すぎるからな", "手遅れだ", "手遅れだった", "手遅れなんだ",
    "手遅れなのだ", "手遅れだよ", "手遅れだわ", "手遅れだぞ",
    "手遅れだぜ", "手遅れだからな", "手遅れだったんだ", "手遅れなんだよ",
    "手遅れなんだわ", "手遅れなんだぞ", "手遅れなんだぜ", "もう手遅れだ",
    "もう手遅れなんだ", "もう手遅れだよ", "もう手遅れだわ", "もう手遅れだぞ",
    "もう手遅れだぜ", "もう手遅れだからな", "とっくに手遅れだ", "とっくに手遅れなんだ",
    "とっくに手遅れだよ", "とっくに手遅れだぞ", "とっくに手遅れだぜ", "間に合わなかった",
    "間に合わなかったんだ", "間に合わなかったよ", "間に合わなかったわ", "間に合わなかったぞ",
    "間に合わなかったぜ", "間に合わなかったからな", "もう間に合わない", "もう間に合わないんだ",
    "もう間に合わないわ", "もう間に合わないぞ", "もう間に合わないぜ", "とっくに間に合わない",
    "とっくに間に合わないんだ", "とっくに間に合わないぞ", "とっくに間に合わないぜ", "救いようがない",
    "救いようがないんだ", "救いようがないわ", "救いようがないぞ", "救いようがないぜ",
    "救いようもない", "救いようもないんだ", "救いようもないぞ", "救いようもないぜ",
    "もう救いようがない", "もう救いようがないんだ", "もう救いようもない", "もう救いようもないんだ",
    "とっくに救いようがない", "とっくに救いようもない", "助けようがない", "助けようがないんだ",
    "助けようもない", "助けようもないんだ", "もう助けようがない", "もう助けようもない",
    "とっくに助けようがない", "とっくに助けようもない", "もうどうしようもない", "もうどうしようもないんだ",
    "もうどうしようもないぞ", "もうどうしようもないぜ", "とっくにどうしようもない", "とっくにどうしようもないんだ",
    "打つ手がない", "打つ手がないんだ", "打つ手もない", "打つ手もないんだ",
    "もう打つ手がない", "もう打つ手もない", "とっくに打つ手がない", "とっくに打つ手もない",
    "手の施しようがない", "手の施しようがないんだ", "手の施しようもない", "手の施しようもないんだ",
    "もう手の施しようがない", "もう手の施しようもない", "とっくに手の施しようがない", "とっくに手の施しようもない",
    "修復不可能だ", "修復不可能なんだ", "修復不可能だよ", "修復不可能だぞ",
    "修復不可能だぜ", "もう修復不可能だ", "もう修復不可能なんだ", "もう修復不可能だぞ",
    "もう修復不可能だぜ", "とっくに修復不可能だ", "とっくに修復不可能なんだ", "回復不可能だ",
    "回復不可能なんだ", "回復不可能だよ", "回復不可能だぞ", "回復不可能だぜ",
    "もう回復不可能だ", "もう回復不可能なんだ", "もう回復不可能だぞ", "もう回復不可能だぜ",
    "とっくに回復不可能だ", "とっくに回復不可能なんだ", "復旧不可能だ", "復旧不可能なんだ",
    "復旧不可能だよ", "復旧不可能だぞ", "復旧不可能だぜ", "もう復旧不可能だ",
    "もう復旧不可能なんだ", "とっくに復旧不可能だ", "とっくに復旧不可能なんだ", "再生不可能だ",
    "再生不可能なんだ", "再生不可能だぞ", "再生不可能だぜ", "もう再生不可能だ",
    "もう再生不可能なんだ", "とっくに再生不可能だ", "とっくに再生不可能なんだ", "復活不可能だ",
    "復活不可能なんだ", "復活不可能だぞ", "復活不可能だぜ", "もう復活不可能だ",
    "もう復活不可能なんだ", "とっくに復活不可能だ", "とっくに復活不可能なんだ", "蘇生不可能だ",
    "蘇生不可能なんだ", "蘇生不可能だぞ", "蘇生不可能だぜ", "もう蘇生不可能だ",
    "もう蘇生不可能なんだ", "とっくに蘇生不可能だ", "とっくに蘇生不可能なんだ", "復元不可能だ",
    "復元不可能なんだ", "復元不可能だぞ", "復元不可能だぜ", "もう復元不可能だ",
    "もう復元不可能なんだ", "とっくに復元不可能だ", "とっくに復元不可能なんだ", "治療不可能だ",
    "治療不可能なんだ", "治療不可能だぞ", "治療不可能だぜ", "もう治療不可能だ",
    "もう治療不可能なんだ", "とっくに治療不可能だ", "とっくに治療不可能なんだ", "修理不可能だ",
    "修理不可能なんだ", "修理不可能だぞ", "修理不可能だぜ", "もう修理不可能だ",
    "もう修理不可能なんだ", "とっくに修理不可能だ", "とっくに修理不可能なんだ", "補修不可能だ",
    "補修不可能なんだ", "補修不可能だぞ", "補修不可能だぜ", "もう補修不可能だ",
    "もう補修不可能なんだ", "とっくに補修不可能だ", "とっくに補修不可能なんだ", "取り返しがつかない",
    "取り返しがつかないんだ", "取り返しがつかないわ", "取り返しがつかないぞ", "取り返しがつかないぜ",
    "もう取り返しがつかない", "もう取り返しがつかないんだ", "もう取り返しがつかないぞ", "もう取り返しがつかないぜ",
    "とっくに取り返しがつかない", "とっくに取り返しがつかないんだ", "とっくに取り返しがつかないぞ", "とっくに取り返しがつかないぜ",
    "取り返しがつかないということだ", "取り返しがつかないという決定だ", "取り返しがつかないという判断だ", "後の祭りだ",
    "後の祭りだった", "後の祭りなんだ", "後の祭りだよ", "後の祭りだわ",
    "後の祭りだぜ", "後の祭りだからな", "もう後の祭りだ", "もう後の祭りなんだ",
    "もう後の祭りだぞ", "もう後の祭りだぜ", "とっくに後の祭りだ", "とっくに後の祭りなんだ",
    "覆水盆に返らず", "覆水盆に返らずだ", "覆水は盆に返らない", "覆水は盆に返らないんだ",
    "二度と戻らない", "二度と戻らないんだ", "二度と戻らないわ", "二度と戻らないぞ",
    "二度と戻らないぜ", "とっくに二度と戻らない", "とっくに二度と戻らないんだ", "二度と取り戻せない",
    "二度と取り戻せないんだ", "二度と取り戻せないぞ", "二度と取り戻せないぜ", "もう二度と取り戻せない",
    "もう二度と取り戻せないんだ", "とっくに二度と取り戻せない", "二度と開けない", "二度と開けないんだ",
    "二度と開けないぞ", "二度と開けないぜ", "とっくに二度と開けない", "二度と見ない",
    "二度と見ないんだ", "二度と見ないぞ", "二度と見ないぜ", "とっくに二度と見ない",
    "二度と見ることはない", "二度と見ることはないんだ", "二度と見ることはないぞ", "二度と見ることはないぜ",
    "二度と開くことはない", "二度と開くことはないんだ", "二度と開くことはないぞ", "二度と開くことはないぜ",
    "二度と戻ることはない", "二度と戻ることはないんだ", "二度と戻ることはないぞ", "二度と戻ることはないぜ",
    "二度と使うことはない", "二度と使うことはないんだ", "二度と使うことはないぞ", "二度と使うことはないぜ",
    "二度と必要とすることはない", "二度と必要とすることはないんだ", "二度と触ることはない", "二度と触ることはないんだ",
    "二度と目にすることはない", "二度と目にすることはないんだ", "二度と目にすることはないぞ", "二度と目にすることはないぜ",
    "二度と目の当たりにすることはない", "二度と耳にすることはない", "二度と耳にすることはないんだ", "二度と耳にすることはないぞ",
    "二度と関わることはない", "二度と関わることはないんだ", "二度と関わることはないぞ", "二度と思い出すことはない",
    "二度と思い出すことはないんだ", "二度と思い出すことはないぞ", "二度と思い出すことはないぜ", "二度と考えることはない",
    "二度と考えることはないんだ", "二度と考えることはないぞ", "二度と振り返ることはない", "二度と振り返ることはないんだ",
    "二度と振り返ることはないぞ", "二度と見返すことはない", "二度と見返すことはないんだ", "二度と見返すことはないぞ",
    "二度と読み返すことはない", "二度と読み返すことはないんだ", "二度と読み返すことはないぞ", "二度と読み返すことはないぜ",
    "切断して", "切断するんだ", "切断すべきだ", "切断してしまえ",
    "切断しちまえ", "切断しちゃえ", "切断しとけ", "切断したまえ",
    "切断しやがれ", "切断しろや", "切断しろと言ってんだ", "切断するつもりだ",
    "切断するわ", "切断するぞ", "切断するぜ", "切断するからな",
    "切断することにした", "切断するのが筋だ", "切断するのが正解だ", "切断するということだ",
    "切断するという決定だ", "切断するという判断だ", "切断することに決めた", "切断することに決めたんだ",
    "切断することに決めたぞ", "切断することに決めたぜ", "切断することに決めたわ", "切断することに決めたよ",
    "切り離しちゃえ", "切り離せや", "切り離せと言ってんだ", "切り離すからな",
    "切り離すのが筋だ", "切り離すのが正解だ", "切り離すということだ", "切り離すという決定だ",
    "切り離すという判断だ", "切り離すことに決めたんだ", "切り離すことに決めたぞ", "切り離すことに決めたぜ",
    "分離しろ", "分離して", "分離するんだ", "分離しろよ",
    "分離すべきだ", "分離してしまえ", "分離しちまえ", "分離しちゃえ",
    "分離しとけ", "分離したまえ", "分離しやがれ", "分離しろや",
    "分離しろって", "分離しろと言ってんだ", "分離するつもりだ", "分離するわ",
    "分離するぞ", "分離するぜ", "分離するからな", "分離することにした",
    "分離するのが筋だ", "分離するのが正解だ", "分離するということだ", "分離するという決定だ",
    "分離するという判断だ", "分離することに決めた", "分離することに決めたんだ", "分離することに決めたぞ",
    "分離することに決めたぜ", "切り捨てちゃえ", "切り捨てろと言ってんだ", "切り捨てるからな",
    "切り捨てるのが筋だ", "切り捨てるのが正解だ", "切り捨てるということだ", "切り捨てるという決定だ",
    "切り捨てるという判断だ", "切り捨てることに決めたんだ", "切り捨てることに決めたぞ", "切り捨てることに決めたぜ",
    "断ち切っちゃえ", "断ち切れや", "断ち切れと言ってんだ", "断ち切るからな",
    "断ち切るのが筋だ", "断ち切るのが正解だ", "断ち切るということだ", "断ち切るという決定だ",
    "断ち切るという判断だ", "断ち切ることに決めたんだ", "断ち切ることに決めたぞ", "断ち切ることに決めたぜ",
    "縁を切っちゃえ", "縁を切れや", "縁を切れと言ってんだ", "縁を切るからな",
    "縁を切るのが筋だ", "縁を切るのが正解だ", "縁を切るということだ", "縁を切るという決定だ",
    "縁を切るという判断だ", "縁を切ることに決めたんだ", "縁を切ることに決めたぞ", "縁を切ることに決めたぜ",
    "絶縁して", "絶縁するんだ", "絶縁すべきだ", "絶縁してしまえ",
    "絶縁しちまえ", "絶縁しちゃえ", "絶縁しとけ", "絶縁したまえ",
    "絶縁しやがれ", "絶縁しろや", "絶縁しろと言ってんだ", "絶縁するつもりだ",
    "絶縁するわ", "絶縁するぞ", "絶縁するぜ", "絶縁するからな",
    "絶縁することにした", "絶縁するのが筋だ", "絶縁するのが正解だ", "絶縁するということだ",
    "絶縁するという決定だ", "絶縁するという判断だ", "絶縁することに決めた", "絶縁することに決めたんだ",
    "絶縁することに決めたぞ", "絶縁することに決めたぜ", "絶交しろ", "絶交して",
    "絶交するんだ", "絶交しろよ", "絶交すべきだ", "絶交してしまえ",
    "絶交しちまえ", "絶交しちゃえ", "絶交しとけ", "絶交したまえ",
    "絶交しやがれ", "絶交しろや", "絶交しろって", "絶交しろと言ってんだ",
    "絶交するつもりだ", "絶交するわ", "絶交するぞ", "絶交するぜ",
    "絶交するからな", "絶交することにした", "絶交するのが筋だ", "絶交するのが正解だ",
    "絶交するということだ", "絶交するという決定だ", "絶交するという判断だ", "絶交することに決めた",
    "絶交することに決めたんだ", "絶交することに決めたぞ", "絶交することに決めたぜ", "断絶しろ",
    "断絶して", "断絶するんだ", "断絶しろよ", "断絶すべきだ",
    "断絶してしまえ", "断絶しちまえ", "断絶しちゃえ", "断絶しとけ",
    "断絶したまえ", "断絶しやがれ", "断絶しろや", "断絶しろって",
    "断絶しろと言ってんだ", "断絶するつもりだ", "断絶するわ", "断絶するぞ",
    "断絶するぜ", "断絶するからな", "断絶することにした", "断絶するのが筋だ",
    "断絶するのが正解だ", "断絶するということだ", "断絶するという決定だ", "断絶するという判断だ",
    "断絶することに決めた", "断絶することに決めたんだ", "断絶することに決めたぞ", "断絶することに決めたぜ",
    "決別しろ", "決別して", "決別するんだ", "決別しろよ",
    "決別すべきだ", "決別してしまえ", "決別しちまえ", "決別しちゃえ",
    "決別しとけ", "決別したまえ", "決別しやがれ", "決別しろや",
    "決別しろって", "決別しろと言ってんだ", "決別するつもりだ", "決別するわ",
    "決別するぞ", "決別するぜ", "決別するからな", "決別することにした",
    "決別するのが筋だ", "決別するのが正解だ", "決別するということだ", "決別するという決定だ",
    "決別するという判断だ", "決別することに決めた", "決別することに決めたんだ", "決別することに決めたぞ",
    "決別することに決めたぜ", "訣別しろ", "訣別して", "訣別するんだ",
    "訣別しろよ", "訣別すべきだ", "訣別してしまえ", "訣別しちまえ",
    "訣別しちゃえ", "訣別しとけ", "訣別したまえ", "訣別しやがれ",
    "訣別しろや", "訣別しろって", "訣別しろと言ってんだ", "訣別するつもりだ",
    "訣別するわ", "訣別するぞ", "訣別するぜ", "訣別するからな",
    "訣別することにした", "訣別するのが筋だ", "訣別するのが正解だ", "訣別するということだ",
    "訣別するという決定だ", "訣別するという判断だ", "訣別することに決めた", "訣別することに決めたんだ",
    "訣別することに決めたぞ", "訣別することに決めたぜ", "離れろ", "離れて",
    "離れるんだ", "離れろよ", "離れるべきだ", "離れてしまえ",
    "離れちまえ", "離れちゃえ", "離れとけ", "離れたまえ",
    "離れやがれ", "離れろや", "離れろって", "離れろと言ってんだ",
    "離れるつもりだ", "離れるわ", "離れるぞ", "離れるぜ",
    "離れるからな", "離れることにした", "離れるのが筋だ", "離れるのが正解だ",
    "離れるということだ", "離れるという決定だ", "離れるという判断だ", "離れることに決めた",
    "離れることに決めたんだ", "離れることに決めたぞ", "離れることに決めたぜ", "分かれろ",
    "分かれて", "分かれるんだ", "分かれろよ", "分かれるべきだ",
    "分かれてしまえ", "分かれちまえ", "分かれちゃえ", "分かれとけ",
    "分かれたまえ", "分かれやがれ", "分かれろや", "分かれろって",
    "分かれろと言ってんだ", "分かれるつもりだ", "分かれるわ", "分かれるぞ",
    "分かれるぜ", "分かれるからな", "分かれることにした", "分かれるのが筋だ",
    "分かれるのが正解だ", "分かれるということだ", "分かれるという決定だ", "分かれるという判断だ",
    "分かれることに決めた", "分かれることに決めたんだ", "分かれることに決めたぞ", "分かれることに決めたぜ",
    "別れろ", "別れて", "別れるんだ", "別れろよ",
    "別れるべきだ", "別れてしまえ", "別れちまえ", "別れちゃえ",
    "別れとけ", "別れたまえ", "別れやがれ", "別れろや",
    "別れろって", "別れろと言ってんだ", "別れるつもりだ", "別れるわ",
    "別れるぞ", "別れるぜ", "別れるからな", "別れることにした",
    "別れるのが筋だ", "別れるのが正解だ", "別れるということだ", "別れるという決定だ",
    "別れるという判断だ", "別れることに決めた", "別れることに決めたんだ", "別れることに決めたぞ",
    "別れることに決めたぜ", "決裂しろ", "決裂して", "決裂するんだ",
    "決裂しろよ", "決裂すべきだ", "決裂してしまえ", "決裂しちまえ",
    "決裂しちゃえ", "決裂しとけ", "決裂したまえ", "決裂しやがれ",
    "決裂しろや", "決裂しろって", "決裂しろと言ってんだ", "決裂するつもりだ",
    "決裂するわ", "決裂するぞ", "決裂するぜ", "決裂するからな",
    "決裂することにした", "決裂するのが筋だ", "決裂するのが正解だ", "決裂するということだ",
    "決裂するという決定だ", "決裂するという判断だ", "決裂することに決めた", "決裂することに決めたんだ",
    "決裂することに決めたぞ", "決裂することに決めたぜ", "断絶させろ", "断絶させて",
    "断絶させるんだ", "断絶させろよ", "断絶させるべきだ", "切断させろ",
    "切断させて", "切断させるんだ", "切断させろよ", "切断させるべきだ",
    "切り離させるんだ", "切り離させろよ", "切り離させるべきだ", "分離させて",
    "分離させるんだ", "分離させるべきだ", "絶縁させろ", "絶縁させて",
    "絶縁させるんだ", "絶縁させろよ", "絶縁させるべきだ", "離れさせろ",
    "離れさせて", "離れさせるんだ", "離れさせろよ", "離れさせるべきだ",
    "別れさせろ", "別れさせて", "別れさせるんだ", "別れさせろよ",
    "別れさせるべきだ", "分かれさせろ", "分かれさせて", "分かれさせるんだ",
    "分かれさせろよ", "分かれさせるべきだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
