// pass DCCLII: tea ceremony & sadou domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCLII: tea ceremony & sadou domain (sadou)', () => {
  const closeTab = ['tea master licensed', 'sadou artisan certified', 'tea ceremony instructor registered'];
  const closeTabJa = [
    '茶道',
    '茶の湯',
    '点前',
    'お点前',
    '茶事',
    '茶会',
    '茶席',
    '茶室',
    '待合',
    '寄付',
    '躙口',
    '貴人口',
    '勝手付',
    '水屋',
    '台子',
    '長板',
    '棚物',
    '風炉',
    '五徳',
    '灰形',
    '火箸',
    '羽箒',
    '炉縁',
    '茶釜',
    '釜敷',
    '釣釜',
    '自在鉤',
    '床の間',
    '点前座',
    '客座',
    '亭主座',
    '仕付棚',
    '付書院',
    '茶杓',
    '茶杓筒',
    '茶巾',
    '茶巾筒',
    '茶入',
    '濃茶器',
    '薄茶器',
    '茶壺',
    '壺口切',
    '茶器',
    '楽茶碗',
    '赤楽',
    '黒楽',
    '白楽',
    '萩茶碗',
    '志野茶碗',
    '織部茶碗',
    '唐津茶碗',
    '井戸茶碗',
    '高麗茶碗',
    '呉器茶碗',
    '熊川茶碗',
    '御本茶碗',
    '天目茶碗',
    '油滴天目',
    '禾目天目',
    '玳皮天目',
    '茶杓銘',
    'こぼし',
    '皆具',
    '仕覆',
    '服紗',
    '古袱紗',
    '帛紗ばさみ',
    '服紗挟',
    '帛紗',
    '茶懐紙',
    '懐石',
    '茶懐石',
    '懐石料理',
    '向付',
    '八寸',
    '焼物',
    '煮物',
    '一汁三菜',
    '中入',
    '後座',
    '初炭',
    '炭斗',
    '炭手前',
    '炭点前',
    '組炭',
    '枝炭',
    '丸炭',
    '濃茶',
    'お濃茶',
    'お薄',
    '点て方',
    '客付',
    '正客',
    '詰客',
    '半東',
    '半東付',
    '亭主',
    '主客',
    '露地門',
    '腰掛待合',
    '閑眠',
    '閑寂',
    '侘び茶',
    '侘数寄',
    '数寄屋',
    '数寄',
    '数寄屋造',
    '小座敷',
    '小間',
    '台目',
    '中台目',
    '大台目',
    '一畳台目',
    '向切',
    '中柱',
    '下地窓',
    '連子窓',
    '紅達磨窓',
    '落し掛け',
    '袖壁',
    '杮葺',
    '下見板',
    '正面構',
    '四畳半',
    '表千家',
    '裏千家',
    '武者小路千家',
    '三千家',
    '薮内家',
    '宗徧流',
    '松尾流',
    '久田流',
    '不白流',
    '織部流',
    '小堀遠州',
    '細川三斎',
    '利休流',
    '宗旦流',
    '七事式',
    '花月',
    '且座',
    '真の行',
    '行之行',
    '草之草',
    '運び点前',
    '濃茶点前',
    '薄茶点前',
    '棚点前',
    '長緒',
    '貴人点',
    '貴人清次',
    '四方箚',
    'お教状',
    '回状',
    '師範',
    '茶道師範',
    '社中',
    '門人',
    '門弟',
    '兄弟子',
    'お稽古',
    '茶稽古',
    '稽古',
    '稽古茶会',
    '初釜',
    '炉開き',
    '風炉先',
    '口切',
    '名残',
    '厭客',
    '初音',
    '葉蓋',
    '茶葉',
    '碾茶',
    '抹茶',
    '玉露',
    '煎茶',
    '番茶',
    '焙じ茶',
    '玄米茶',
    '新茶',
    '一番茶',
    '二番茶',
    '挽茶',
    '臼挽き',
    '石臼挽き',
    '茶臼',
    '石臼',
    '茶摘',
    '茶摘み',
    '覆下',
    '覆い茶',
    '被覆栽培',
    '荒茶',
    '仕上げ火',
    '火入れ',
    '茶師',
    '茶匠',
    '茶園',
    '茶畑',
    '茶業',
    '茶農家',
    '茶産地',
    '宇治茶',
    '八女茶',
    '狭山茶',
    '静岡茶',
    '鹿児島茶',
    '嬉野茶',
    '知覧茶',
    '本山茶',
    '川根茶',
    '牧之原茶',
    '岡部茶',
    '藤枝茶',
    '掛川茶',
    '福茶',
    '冠茶',
    '釜炒茶',
    '蒸し茶',
    '釜炒り茶',
    '有機茶',
    '特上茶',
    '上撰茶',
    '湯杓',
    '湯次',
    '湯次桶',
    '汲出し',
    '汲出し湯',
    '口付',
    '茶箱',
    '旅点',
    '野点',
    'お野立て',
    '籠茶箱',
    '主菓子',
    '干菓子',
    '濃茶菓子',
    'ういろう',
    '薯蕷饅頭',
    '外郎',
    '練切',
    '煉切',
    '練り切り',
    '薯蕷',
    '上用饅頭',
    '落雁',
    '菓子器',
    '菓子鉢',
    '千利休',
    '利休',
    '織部',
    '遠州',
    '如庵',
    '有楽斎',
    '古田織部',
    '山上宗二',
    '津田宗及',
    '今井宗久',
    '片桐石州',
    '石州流',
    '千道安',
    '利休七哲',
    '堺衆',
    '高台院',
    '細川幽斎',
    '蒲生氏郷',
    '高山右近',
    '瀬田掃部',
    '芝山監物',
    '牧村利兵衛',
    '南方録',
    '継蒙述緒',
    '山上宗二記',
    '宗湛日記',
    '松屋会記',
    '宗久の茶会記',
    '禅茶録',
    '茶話指月集',
    '一期一会',
    '一座建立',
    '和敬清寂',
    '寂び',
    '幽玄',
    '余情',
    '閑静',
    '会席',
    '茶会招き',
    '茶事招状',
    '初座',
    '中立',
    '湯加減',
    '釜の湯',
    '釜替え',
    '中置',
    '水屋仕事'
  ];
  const negate = [
    'still awaiting the tea license',
    'still awaiting the ceremony permit',
    'まだ点前前',
    'まだ炉開き前',
    'これから点て',
    'まだ茶事前'
  ];
  const nullPins = ['about to visit the tea school', 'about to file the tea report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
