// pass DCCXLVII: plasterwork & sakan domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLVII: plasterwork & sakan domain (sakan)', () => {
  const closeTab = ['plasterer licensed', 'plaster artisan certified', 'plasterwork master registered'];
  const closeTabJa = [
    '左官',
    '左官屋',
    '左官職人',
    '左官工',
    '左官技能士',
    '左官業',
    '左官工事',
    '左官検定',
    '漆喰',
    '漆喰壁',
    '漆喰塗り',
    '漆喰磨き',
    '漆喰櫛引き',
    '漆喰押さえ',
    '漆喰仕上げ',
    '漆喰塗装',
    '漆喰職人',
    '土佐漆喰',
    '木島漆喰',
    '島漆喰',
    '消石灰',
    '石灰',
    '苦土石灰',
    '生石灰',
    '石灰岩',
    '石灰水',
    '石灰乾燥',
    'スサ',
    '繊維筋',
    '麻スサ',
    'ガラススサ',
    'バサルトスサ',
    '土壁',
    '泥壁',
    '京壁',
    '聚楽壁',
    '大津磨き',
    '長押壁',
    '真壁',
    '大壁',
    '化粧壁',
    '仕上げ壁',
    '塗り壁',
    '塗壁',
    '練り壁',
    '突き固め',
    '版築',
    '築地塀',
    '練塀',
    '海鼠壁',
    'なまこ壁',
    'なまこ',
    '腰掛け',
    '出窓',
    'アーチ壁',
    '曲面塗り',
    '丸面塗り',
    '荒壁',
    '荒塗り',
    '中塗り',
    '上塗り',
    '下地塗り',
    '下地',
    '下塗り',
    '中土',
    '上土',
    '本土',
    '摺り',
    'シゴキ',
    '仕切り',
    'コテ',
    '鏝',
    '剛鏝',
    '中鏝',
    '仕上げ鏝',
    '先切鏝',
    '角鏝',
    '内角鏝',
    '外角鏝',
    '面引鏝',
    'レンガ鏝',
    'ブラシ鏝',
    '扇鏝',
    '丸鏝',
    '矢羽鏝',
    '鹿革鏝',
    'ステン鏝',
    'プラ鏝',
    '金鏝',
    'コテ板',
    'コテ箱',
    'コテガイ',
    '撫で板',
    'ゴム鏝',
    '洗い板',
    '角出し',
    '角張り',
    '面取り',
    '面引き',
    '型枠',
    '海鼠枠',
    '木ゴテ',
    'サンダー',
    '左官機械',
    'ミキサー',
    'モルタル',
    'モルタル練り',
    'モルタルミキサー',
    'モルタル吹付',
    '吹付',
    'ラス',
    'ラス板',
    '金属ラス',
    '波型ラス',
    '編みラス',
    '木小舞',
    '竹小舞',
    '小舞',
    '貫',
    '胴貫',
    '木舞掻き',
    '竹編み',
    '荒壁編み',
    'プラスター',
    '石膏ボード',
    'ボード継ぎ',
    'テープ張り',
    'パテ処理',
    'パテ',
    'シーラー',
    'プライマー',
    'ベンガラ',
    '弁柄',
    '柿渋',
    '炭',
    'すす',
    '顔料',
    '土色',
    '聚楽',
    '聚楽土',
    'ケイソウ土',
    '珪藻土',
    '珪藻土塗り',
    'ケイソウ',
    '中涂土',
    '塗り替え',
    '塗り直し',
    '色直し',
    '割れ補修',
    'ひび補修',
    '亀裂補修',
    '漆喰補修',
    '土壁補修',
    '蔵造り',
    '蔵壁',
    '土蔵',
    '土蔵造り',
    '耐火壁',
    '防火壁',
    '土盛り',
    '打放し',
    'タタキ仕上げ',
    'タイル貼り',
    'モザイク貼り',
    '洗い出し',
    '人工研ぎ出し',
    'スタッコ',
    '吹き付け仕上げ',
    'リシン',
    'ジョリパット',
    '吹付けタイル',
    '左官材料',
    '左官道具',
    '左官道具店',
    '左官工務店',
    '左官会社',
    '左官組合',
    '左官協会',
    '左官屋さん',
    '左官請負',
    '左官内装',
    '左官外装',
    '左官専門',
    '左官教室',
    '左官体験',
    '土壁造り',
    '練り方',
    '水加減',
    '練り合わせ',
    '寝かせ',
    '醒め',
    '貯め',
    '置き寝',
    '切り付け',
    '切り落とし',
    '垂れ落ち',
    '鏝むら',
    'コテムラ',
    '仕上げむら',
    '縁起物',
    '鎮懸賞',
    'つくねん',
    '酉市',
    '熊手',
    '左官の日',
    '左官店',
    '雑巾',
    '濡れ雑巾',
    '水練り',
    '練り混ぜ',
    '押え',
    '本押え',
    '中押え',
    '角押え',
    '目地',
    '目地押え',
    '目地処理',
    '目地割り',
    '目地出し',
    '目地鏝',
    '目地棒',
    '端切れ',
    '端材',
    '土蔵修理',
    '蔵改修',
    '蔵保存',
    '伝統左官',
    '古式左官',
    '宮殿左官',
    '茶室左官',
    '数寄屋左官',
    '社寺左官',
    '仏閣左官',
    '城壁左官',
    '天守閣左官',
    '土塀',
    '築地壁',
    '濡れ縁壁',
    '土間',
    '土間打ち',
    '三和土',
    'たたき',
    'タタキ土間',
    '土間コンクリート'
  ];
  const negate = [
    'still awaiting the plasterer license',
    'still awaiting the plaster cert',
    'まだ塗り前',
    'まだ練り前',
    'これから塗り',
    'まだ仕上げ前'
  ];
  const nullPins = ['about to visit the plasterer', 'about to file the plaster report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
