// pass DCCXXIV: appraisal, meteorology, consulting & maintenance
// licenses -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXXIV: appraisal & professional licenses (salpinx)', () => {
  const closeTab = ['appraiser licensed', 'surveyor chartered', 'consultant certified'];
  const closeTabJa = [
    '不動産鑑定士',
    '不動産鑑定士試験',
    '不動産鑑定士登録',
    '不動産鑑定',
    '鑑定評価',
    '不動産鑑定評価',
    '鑑定評価書',
    '鑑定評価基準',
    '公示価格',
    '路線価',
    '固定資産評価',
    '地価公示',
    '都道府県地地価調査',
    '鑑定業者',
    '不動産鑑定業者',
    '評価員',
    '証明化評価',
    '土地家屋調査士',
    '土地家屋調査士試験',
    '土地家屋調査士会',
    '調査士事務所',
    '筆界',
    '筆界特定',
    '地積',
    '地積測量図',
    '地図訂正',
    '分筆登記',
    '合筆登記',
    '地目変更登記',
    '建物表示登記',
    '表題登記',
    '建物滅失登記',
    '区分建物登記',
    '測量',
    '境界標',
    '境界確認',
    '境界立会',
    '地籍調査',
    '不動産表示',
    '登記所',
    '法務局',
    '地方法務局',
    '気象予報士',
    '気象予報士試験',
    '気象業務',
    '気象観測',
    '気象庁長官',
    '気象庁',
    '地方気象台',
    '気象台',
    '測候所',
    '予報業務許可',
    '現象観測',
    '高層気象',
    'アメダス',
    'アメダス観測',
    'レーダー観測',
    'ひまわり観測',
    '気象衛星',
    '気象情報',
    '天気図',
    '天気予報',
    '週間天気',
    '降水確率',
    '降水確率予報',
    '警報発表',
    '注意報',
    '特別警報',
    '緊急速報メール',
    '気象データ',
    '天気相談所',
    '気象解説',
    '花粉情報',
    '黄砂情報',
    '桜開花予想',
    '紅葉見頃',
    '暑さ指数',
    '熱中症警戒',
    '寒冷前線',
    '温暖前線',
    '停滞前線',
    '低気圧',
    '高気圧',
    '気圧配置',
    '等圧線',
    '風速',
    '瞬間風速',
    '暴風警報',
    '大雨警報',
    '大雪警報',
    '洪水警報',
    '高潮警報',
    '波浪警報',
    '濃霧注意報',
    '雷注意報',
    '着雪注意報',
    '融雪注意報',
    '霜注意報',
    'なだれ注意報',
    '竜巻注意',
    '竜巻',
    '台風情報',
    '台風進路',
    '暴風域',
    '強風域',
    '中心気圧',
    '最大風速',
    '土砂災害警戒',
    '土砂災害警戒情報',
    '記録的大雨',
    '線状降水帯',
    '顕著な大雨',
    '梅雨前線',
    '秋雨前線',
    '初霜',
    '初氷',
    '夏日',
    '真夏日',
    '猛暑日',
    '熱帯夜',
    '冬日',
    '真冬日',
    'ファイナンシャルプランナー',
    'fp技能士',
    'fp試験',
    'fp一級',
    'fp二級',
    'fp三級',
    'afp',
    'cfp',
    '家計相談',
    'ライフプラン',
    '保険見直し相談',
    '資産運用相談',
    '相続相談',
    '住宅ローン相談',
    '教育資金',
    '老後資金',
    '資金計画',
    'キャッシュフロー表',
    '家計簿診断',
    '中小企業診断士',
    '中小企業診断士試験',
    '経営コンサルタント',
    '経営診断',
    '経営相談',
    '経営改善',
    '経営革新',
    '経営力向上',
    '事業計画',
    '事業継続力',
    'ビジネスプラン',
    'マーケティング支援',
    '生産性向上',
    'it経営',
    'デジタル化支援',
    '補助金活用',
    'ものづくり補助金',
    '持続化補助金',
    'it補助金',
    '事業再構築',
    '事業承継相談',
    '創業支援',
    'ベンチャー支援',
    '経営指導員',
    '商工会議所',
    '商工会',
    '中小企業支援',
    '中小企業庁',
    '経済産業省',
    '経産省',
    '認定経営革新',
    '新連携',
    '地域資源活用',
    '農商工連携',
    '下請適正化',
    '価格転嫁',
    '取引条件改善',
    '事業報告書',
    '決算診断',
    '財務分析',
    '損益分岐点',
    'キャッシュフロー経営',
    '自動車整備士',
    '自動車整備士試験',
    '整備士登録',
    '整備主任者',
    '整備工場',
    '指定整備工場',
    '認証整備工場',
    '自動車整備業',
    '整備事業者',
    '点検整備記録',
    '整備記録簿',
    '日常点検',
    '定期点検',
    '12ヶ月点検',
    '24ヶ月点検',
    '車検整備',
    '分解整備',
    '保安基準適合証',
    '整備明細',
    '故障診断',
    'obd診断',
    'エンジン整備',
    'ブレーキ整備',
    'タイヤ整備',
    '電装整備',
    '板金塗装',
    '鈑金工場',
    '自動車修理工場',
    'ドローン操縦士',
    'ドローン操縦ライセンス',
    'ドローン国家資格',
    '無人航空機操縦士',
    '一等無人航空機操縦士',
    '二等無人航空機操縦士',
    'ドローン免許',
    '機体認証',
    '飛行申請',
    '包括申請',
    '飛行計画通報',
    '飛行日誌',
    'dips申請',
    '無人航空機',
    'ドローン登録',
    'リモートid',
    '飛行禁止区域',
    '人口集中地区',
    '夜間飛行',
    '目視外飛行',
    '第三者上空',
    '補助者',
    '監視員配置',
    '操縦技能証明',
    '練習空域',
    'ドローン教習所',
    '登録講習機関'
  ];
  const negate = [
    'still awaiting the appraiser license',
    'still awaiting the drone permit',
    'まだ申請前',
    'まだ試験前',
    'これから出願',
    'まだ診断前'
  ];
  const nullPins = ['about to visit the registry office', 'about to file the appraisal report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
