// Pass CCXLVIII: EN maritime/abandonment + expiry/junk declarations + JA abandonment/demolition/execution/erasure/quotative (pass CCXLVIII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCXLVIII: close-tab coverage', () => {
  test.each([
    "set adrift", "cast adrift", "left adrift", "gone with the wind",
    "blown away for good", "swept away", "washed away", "washed up",
    "carried off", "carried away", "carried out", "put it on a bus",
    "put it on the bus", "put it on a train", "put it on the train", "put it on a plane",
    "put it on the plane", "one way ticket for it", "one way trip for it", "one way journey for it",
    "send it on a trip", "send it on a journey", "haul it away", "haul it off",
    "haul it out", "cart it off", "cart it away", "cart it out",
    "lug it out", "wheel it out", "tote it out", "schlep it out",
    "haul it to the curb", "take it to the curb", "to the curb with it", "curb it",
    "curb the tab", "garbage day for it", "trash day for it", "pickup day for it",
    "collection day for it", "its garbage day", "its trash day", "benched permanently",
    "sent to the showers", "send it to the showers", "sent to the locker room", "send it to the locker room",
    "thrown out of the game", "throw it out of the game", "eject it from the game", "ejected from the game",
    "red card it", "red card for it", "give it a red card", "give it the red card",
    "send it off the field", "sent off the field", "off the field with it", "its three strikes",
    "third strike for it", "fold the company", "close the business", "shutter the doors",
    "liquidate it", "wind down the business", "out of business with it", "it went belly up",
    "belly up for it", "its expired", "it expired", "past its prime",
    "past its peak", "over the hill", "its over the hill", "past it",
    "lost its spark", "out of juice", "out of gas", "running on empty",
    "out of steam", "ran out of steam", "dead in the water", "dead on arrival",
    "it was dead on arrival", "doa", "stillborn", "dead before it started",
    "dead as a doornail", "dead as disco", "as dead as a doornail", "out of the house with it",
    "kick it out of the house", "kicked out of the house", "shown the door", "show it the way out",
    "point it to the door", "through the door with it", "out the door it goes", "apoptosis",
    "programmed cell death", "cell death for it", "senescence for it", "defunct",
    "its defunct", "gone defunct", "kaput", "gone kaput",
    "deceased", "its deceased", "demised", "it demised",
    "terminate it with extreme prejudice", "friendly fire it", "blue on blue", "pull out of it",
    "withdraw from it", "extract it", "extract the tab", "evac it",
    "evacuate the tab", "pull it out of there", "bedtime story for it", "kiss the tab goodnight",
    "lullaby for it", "the end is here for it", "the end is nigh", "the end is nigh for it",
    "endgame for it", "its endgame", "final boss it", "beat the final boss",
    "its final level", "last level for it", "credit roll for it", "end credits for it",
    "a humane end for it", "humane end", "humane ending", "take it to the farm",
    "shift delete it", "shift delete", "secure wipe it", "securely wipe it",
    "wipe it off the face", "wipe it off the earth", "wipe it off the planet", "wipe it off the record",
    "wipe it from the record", "scrub it from the record", "clean it from the record", "remove it from the record",
    "strike it from the books", "wrote it off", "written off", "its written off",
    "chalk it up", "chalk it off", "write it off the books", "exit stage right",
    "exit stage left for it", "make an exit", "make its exit", "point it to the exit",
    "mark the exit for it", "out the exit it goes", "through the exit", "through the exit with it",
    "down the exit", "get gone already", "be gone from here",
    "be gone now", "begone from this world", "get out of my sight", "get out of my face",
    "out of my life", "get out of my life", "get out of my world", "out of my world",
    "leave my sight", "leave my world", "vacate the premises", "vacate the tab",
    "clear the premises", "clear the area", "clear the screen", "get off my display",
    "get out of my headset", "off my radar", "get off my radar", "off the radar with it",
    "off my plate", "get off my plate", "off the plate with it", "off my desk",
    "get off my desk", "off the desk", "clear my desk of it", "clear it off my desk",
    "sweep it off my desk", "sweep it off the desk", "wipe it off the desk", "sweep it away from me",
    "sweep it out the door", "sweep it out the window", "out of the window with it", "defenestration",
    "auto da fe it", "the rack for it", "the wheel for it", "keel haul it",
    "walk it off the plank", "off the plank", "plank walking for it", "over the side with it",
    "over the rail with it", "off the boat with it", "off the ship with it", "overboard it",
    "overboard the tab", "man it overboard", "chuck it overboard", "heave it overboard",
    "dump it overboard", "over the bow", "feed the fishes", "sleep with the fishes",
    "with the fishes", "to the fishes", "fish bait", "whale food",
    "kraken food", "feed it to the kraken", "to the kraken", "release the kraken on it",
    "davy jones locker for it", "davy joness locker", "the briny deep for it", "down to the briny deep",
    "six fathoms down", "down with the ship", "down with its ship", "it went down with the ship",
    "went down with the ship", "sink with it", "sink it like a stone", "like a stone it sinks",
    "stone cold sunk", "titanic it", "iceberg it", "iceberg for it",
    "hit the iceberg", "into the iceberg", "abandon ship on it", "abandon it at sea",
    "lost at sea", "lost to the sea", "claimed by the sea", "taken by the sea",
    "swallowed by the sea", "swallowed by the ocean", "the sea took it", "down to the bottom",
    "to the bottom with it", "to the sea floor", "the sea floor for it", "seabed for it",
    "mariana trench for it", "to the mariana trench", "the trench for it", "置き去りにしろ",
    "置き去りにしてやれ", "置き去りだ", "置きっぱなしにしろ", "置きっぱなしだ",
    "突き出せ", "突き出して", "門前払いにしろ", "静かに消えろ",
    "音を立てずに消えろ", "黙って消えろ", "音沙汰なく消えろ", "こっそり消えろ",
    "そっと消えろ", "忍んで消えろ", "仕舞いだな", "お終いだ",
    "お仕舞いでございます", "お仕舞いだって", "お仕舞いよ", "仕舞いにしろ",
    "仕舞いにせよ", "死亡証明書", "死亡診断書", "死亡届だ",
    "死亡届けだ", "除籍届だ", "死亡を確認", "死亡を確認した",
    "死亡が確認された", "死亡が確認されたぞ", "死亡を確認しました", "死亡確認だ",
    "検死だ", "検死結果は死", "引退式だ", "引退勧告だ",
    "現役引退だ", "第一線を退け", "第一線から退け", "退役だ",
    "退役させろ", "退役にしろ", "退役するんだ", "在庫処分だ",
    "在庫処分品だ", "型落ちだ", "型遅れだ", "時代遅れだ",
    "時代遅れだな", "化石だ", "化石だな", "古い型だ",
    "旧型だ", "旧式だ", "過去の遺物だ", "遺物だ",
    "遺物だな", "骨董品だ", "骨董品だな", "アンティークだ",
    "ヴィンテージだ", "最終列車だ", "終電だ", "終電を逃した",
    "ラストランだ", "引退列車だ", "さよなら列車だ", "ばらせ",
    "撤廃せよ", "廃棄処分だ", "投棄しろ", "投棄せよ",
    "投棄だ", "処分しろ", "処分せよ", "処分だ",
    "処分対象だ", "処分対象品だ", "処分品だ", "廃棄対象だ",
    "撤去対象だ", "解体対象だ", "処刑するんだ", "処刑すべきだ",
    "処断しろ", "処断せよ", "処断だ", "死刑執行だ",
    "死刑執行しろ", "死刑執行せよ", "死刑宣告しろ", "極刑に処せ",
    "処せ", "処すべき", "処するんだ", "成敗してやれ",
    "お仕置きしてやれ", "お仕置きするんだ", "懲らしめろ", "懲らしめてやれ",
    "懲罰だ", "懲罰にしろ", "罰してやれ", "罰ゲームだ",
    "罪を償わせろ", "罪を償え", "償いだ", "闇に葬り去れ",
    "闇に消せ", "闇に沈め", "闇の中へ", "闇の底へ",
    "闇の底に沈め", "奈落に落とせ", "奈落行きだ", "地獄に落とせ",
    "地獄へ行け", "地獄へ送れ", "地獄行きにしろ", "地獄に送ってやれ",
    "あの世行きにしろ", "弔いにしろ", "埋葬するんだ", "埋立地にしろ",
    "消え去って", "跡形なく消えろ", "跡を残さず消えろ", "跡形も残さず消えろ",
    "跡形も残さず消せ", "形も残さず消せ", "存在を抹消しろ", "存在を消去しろ",
    "存在を消し去れ", "存在をなかったことにしろ", "存在ごと消せ", "存在ごと消えろ",
    "歴史から消えろ", "歴史から消し去れ", "記録から消えろ", "記録から削除しろ",
    "名簿から削除しろ", "リストから消せ", "リストから削除しろ", "リストから外せ",
    "一覧から消せ", "一覧から削除しろ", "画面から消えろ", "視界から消えろ",
    "目の前から消えろ", "俺の前から消せ", "俺の目の前から消えろ", "俺の前から消え失せろ",
    "見るに耐えない", "見るに堪えない", "見ていられない", "見てられない",
    "見てられっか", "見る価値もない", "見る価値すらない", "読む価値もない",
    "読む価値すらない", "読むに耐えない", "読むに堪えない", "読んでいられない",
    "読んでられない", "カスだ", "カスだな", "クズだ",
    "クズだな", "ポンコツだ", "ポンコツだな", "ガラクタだ",
    "ガラクタだな", "ジャンクだ", "ジャンクだな", "産業廃棄物だ",
    "産廃だ", "産廃だな", "塵だ", "塵だな",
    "塵芥だ", "塵芥だな", "芥だ", "くずだ",
    "くずだな", "ガラクタしかない", "残りカスだ", "カスの極みだ",
    "駄作だ", "駄作だな", "失敗作だ", "失敗作だな",
    "出来損ないだな", "不良品だ", "不良品だな", "欠陥品だ",
    "欠陥品だな", "規格外だ", "規格外品だ", "ワケあり品だ",
    "わけあり品だ", "訳あり品だ", "問題作だ", "問題作だな",
    "問題だらけだ", "ヤバいタブだ", "ヤバいタブだな", "危険なタブだ",
    "危険タブだ", "有害だ", "有害だな", "有害物だ",
    "有害サイトだ", "害悪だ", "害悪だな", "毒だ",
    "毒だな", "毒物だ", "毒サイトだ", "呪われたタブだ",
    "呪物だ", "呪物だな", "呪いの品だ", "呪いのアイテムだ",
    "忌まわしい", "忌まわしいタブだ", "忌まわしきものだ", "見るに堪えん",
    "目にするに堪えない", "視界から出ていけ", "視界から出ていって", "視界を去れ",
    "目の前から去れ", "目の前から失せろ", "目の前から消え失せろ", "消えろと言ってんだ",
    "消えろって言ってんだ", "消えろ言ってんだ", "消えろっつってんだ", "消せっつってんだ",
    "消せってば", "消せって言ってる", "消せと言ってる", "消せと言ってんだ",
    "消せ言ってんだ", "消せって言ってんだ", "閉じろと言ってんだ", "閉じろ言ってんだ",
    "閉じろって言ってんだ", "閉じてっつってんだ", "閉じてってば", "閉じてと言ってんだ",
    "閉じて言ってんだ", "閉じてって言ってんだ", "殺せっつってんだ", "殺せと言ってんだ",
    "殺せ言ってんだ", "殺せって言ってんだ", "捨てろっつってんだ", "捨てろってば",
    "捨てろって言ってる", "捨てろと言ってんだ", "捨てろ言ってんだ", "捨てろって言ってんだ",
    "捨ててっつってんだ", "捨ててってば", "捨ててって言ってる", "捨ててと言ってる",
    "捨ててと言ってんだ", "捨てて言ってんだ", "捨ててって言ってんだ", "問題のタブだ",
    "呪いのタブだ", "呪われたタブだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});

describe('pass CCXLVIII: negate coverage', () => {
  test.each([
    "置いてけ", "置いていけ", "置いていって", "ほっとけ",
    "ほっといて", "放っとけ", "放っておけ", "放っておいて",
    "放っといて", "もう見たくねえ", "見たくもない", "見たくもねえ",
    "二度と見たくねえ", "見るのも嫌だ", "見るのも嫌だな", "成仏してない",
    "成仏できない", "成仏なんてできない", "浮かばれない", "浮かばれないぞ",
  ])('routes %s to negate', (p) => {
    expect(key(mk(), p)).toBe('negate');
  });
});
