import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const vc = new VoiceCommands({ enabled: true });
  const tm = { activeTabId:'t1', tabs:[{id:'t1',title:'X',url:'https://x'}], getActiveTab(){return this.tabs[0];}, closeAllTabs(){return 1;} };
  vc.connectBrowser({ tabManager: tm, onGoTo: () => {} });
  vc.speak = () => {};
  return vc;
}

describe('saturation pins', () => {
  const vc = mk();
  const cases = [
    // semantic guards (must never execute)
    ['閉じるべきかな','help'],
    ['閉じるものかな','negate'],
    ['閉じたはず','trouble'],
    ['閉じるっけ','describe-tab'],
    ['閉じなくていい','negate'],
    ['閉じるところです','describe-tab'],
    ['閉じるべきかどうか','help'],
    ['閉じるか閉じないか','help'],
    ['閉じてもいいかな','close-tab'],
    ['閉じてもよろしいですか','close-tab'],
    ['閉じたほうがいいですか','help'],
    ['should i close it','help'],
    ['can i close it','help'],
    ['may i close it','close-tab'],
    ['youre not closing it are you','help'],
    ['why would we close it','help'],
    // negation family
    ['閉じるのはやめた','negate'],
    ['閉じるのは見送ります','negate'],
    ['閉じるのを断念します','negate'],
    ['閉じなくてもよいです','negate'],
    ['閉じないほうがいいです','negate'],
    ['閉じるのは後にします','negate'],
    ['閉じるのはいりません','negate'],
    ['閉じるのはナシで','negate'],
    ['閉じずに済みそうです','negate'],
    ['you should not close it','negate'],
    ['do not close it yet','negate'],
    ['hold off closing it','negate'],
    ['lets not close it','negate'],
    ['lets put off closing it','negate'],
    ['no need to close it yet','negate'],
    ['i see no reason to close it','negate'],
    // trouble reports
    ['閉じちゃった','reopen-tab'],
    ['間違えて閉じちゃった','reopen-tab'],
    ['誤って閉じました','reopen-tab'],
    ['うっかり閉じました','reopen-tab'],
    // JA tail depth
    ['閉じるのが急所という所見です','close-tab'],
    ['閉じるのが急所という認識です','close-tab'],
    ['閉じるのが急所という判断です','close-tab'],
    ['閉じるのが急所と心得ております','close-tab'],
    ['閉じてもらえますでしょうか','close-tab'],
    ['閉じていただけませんものでしょうか','close-tab'],
    ['閉じてくださいますかね','close-tab'],
    // JA discourse/filler/imperative colloquials
    ['とりあえず閉じて','close-tab'],
    ['じゃあ閉じて','close-tab'],
    ['えっと閉じて','close-tab'],
    ['ねえ閉じて','close-tab'],
    ['とにかく閉じて','close-tab'],
    ['閉じろって','close-tab'],
    ['閉じとけ','close-tab'],
    ['閉じなって','close-tab'],
    ['閉じてくれい','close-tab'],
    ['閉じちまえ','close-tab'],
    ['閉じてしまえよ','close-tab'],
    ['閉じてちょうだいね','close-tab'],
    ['閉じてたもれ','close-tab'],
    ['閉じて至急','close-tab'],
    ['閉じて大至急','close-tab'],
    ['閉じてよろしくお願いします','close-tab'],
    // JA generality: other verbs + other tails
    ['リロードのが急所という所見です','refresh'],
    ['リロードしてもらえますかね','refresh'],
    ['全部閉じろ','close-all-tabs'],
    ['全タブ閉じてもらえますかね','close-all-tabs'],
    ['全タブを閉じるのが急所だ','close-all-tabs'],
    ['このタブ以外全部閉じて','close-other-tabs'],
    ['他のタブをすべて閉じて','close-other-tabs'],
    ['タブ畳んで','close-tab'],
    ['このタブをピン留めして','pin-tab'],
    ['ピン留めしてもらえますかね','pin-active'],
    ['このページをブックマークして','bookmark-page'],
    ['ブックマークに追加してもらえますか','bookmark-page'],
    // JA surface breadth
    ['戻って','back'],
    ['さっきのページに戻って','back'],
    ['進んで','navigate'],
    ['下にスクロールして','scroll-down'],
    ['ページを上へ','scroll-up'],
    ['再読み込みして','refresh'],
    ['読み込み直して','refresh'],
    ['拡大して','reader-size-up'],
    ['画面を小さくして','panel-distance'],
    ['新しいタブを開いて','new-tab'],
    ['もう一個タブ開いて','new-tab'],
    ['読み上げて','read-aloud'],
    ['声に出して読んで','read-aloud'],
    ['ページ内検索して','find-in-page'],
    ['設定を開いて','settings-toggle'],
    ['音量を上げて','volume-up'],
    ['音を小さくして','volume-down'],
    ['ミュートして','mute-toggle'],
    ['このページを翻訳して','translate-page'],
    ['シェアして','share-page'],
    ['ホームに戻って','home'],
    ['使い方を教えて','help'],
    ['止めて','stop-everything'],
    ['履歴を見せて','history'],
    ['ブックマーク一覧','bookmarks-list'],
    ['キャプチャして','screenshot'],
    ['全画面にして','vr-enter'],
    // EN politeness/adverb depth
    ['could you possibly maybe close it','close-tab'],
    ['would you very kindly close it','close-tab'],
    ['do kindly close it','close-tab'],
    ['at your earliest convenience could you close it','close-tab'],
    ['you could probably close it','close-tab'],
    ['you might conceivably close it','close-tab'],
    ['id take it kindly if youd close it','close-tab'],
    ['be a dear and kindly close it','close-tab'],
    ['if you wouldnt mind terribly could you close it','close-tab'],
    ['id be much obliged if you could possibly close it','close-tab'],
    ['could i get you to close it','close-tab'],
    ['why dont we close it','close-tab'],
    ['why not close it','close-tab'],
    ['close it will ya','close-tab'],
    ['close it wontcha','close-tab'],
    ['close it right quick','close-tab'],
    ['close it forthwith','close-tab'],
    ['close it pronto','close-tab'],
    ['close it stat','close-tab'],
    ['close it on the double','close-tab'],
    ['close it chop chop','close-tab'],
    ['close it while youre at it','close-tab'],
    ['close it whenever','close-tab'],
    ['close it at your leisure','close-tab'],
    ['close it pretty please','close-tab'],
    ['close it por favor','close-tab'],
    ['close it thank you kindly','close-tab'],
    ['close it for me will you','close-tab'],
    ['close it already','close-tab'],
    ['go right ahead and close it','close-tab'],
    ['be a sport and close it','close-tab'],
    ['be a lamb and close it','close-tab'],
    ['be a peach and close it','close-tab'],
    ['be a love and close it','close-tab'],
    ['be an angel and close it','close-tab'],
    ['if you could just close it','close-tab'],
    ['id appreciate you closing it','close-tab'],
    ['id be grateful if you could close it','close-tab'],
    ['wed appreciate it if youd close it','close-tab'],
    ['how bout closing it','close-tab'],
    ['what say we close it','close-tab'],
    ['shall we close it','close-tab'],
    ['lets close it','close-tab'],
    ['let us close it','close-tab'],
    // EN discourse markers
    ['anyway close it','close-tab'],
    ['well anyway close it','close-tab'],
    ['at this point close it','close-tab'],
    ['in that case close it','close-tab'],
    ['so yeah close it','close-tab'],
    ['right then close it','close-tab'],
    ['alrighty close it','close-tab'],
    ['anyhoo close it','close-tab'],
    ['ok so close it','close-tab'],
    ['now then close it','close-tab'],
    ['you know what close it','close-tab'],
    ['uh close it','close-tab'],
    ['erm close it','close-tab'],
    ['hey close it','close-tab'],
    ['yo close it','close-tab'],
    ['oi close it','close-tab'],
    ['look close it','close-tab'],
    ['listen close it','close-tab'],
    // EN object addressing / other commands
    ['close the current tab','close-tab'],
    ['close this here tab','close-tab'],
    ['close that tab right there','close-tab'],
    ['close yonder tab','close-tab-by-name'],
    ['close this very tab','close-tab'],
    ['close every tab','close-all-tabs'],
    ['close all the tabs','close-all-tabs'],
    ['kindly close all tabs','close-all-tabs'],
    ['close every tab but this one','close-other-tabs'],
    ['close all tabs apart from this one','close-other-tabs'],
    ['close all tabs save this one','close-other-tabs'],
    ['pin this tab for me','pin-tab'],
    ['kindly pin this tab','pin-tab'],
    ['could you pin the current tab','pin-tab'],
    ['bookmark this page for me','bookmark-page'],
    ['add this page to bookmarks','bookmark-page'],
    ['save this to bookmarks please','bookmark-page'],
    // EN surface breadth
    ['read this page aloud','read-aloud'],
    ['read the page out loud','read-aloud'],
    ['find on this page','find-in-page'],
    ['search this page','find-in-page'],
    ['open settings','settings-toggle'],
    ['turn the volume up','volume-up'],
    ['turn the volume down','volume-down'],
    ['mute the sound','mute-toggle'],
    ['translate this page','translate-page'],
    ['share this page','share-page'],
    ['take me home','home'],
    ['halt','stop-everything'],
    ['show me the history','history'],
    ['show my bookmarks','bookmarks-open'],
    ['take a screenshot','screenshot'],
    ['capture the screen','screenshot'],
    ['go fullscreen','vr-enter'],
    ['full screen please','vr-enter'],
  ];
  it.each(cases)('%s -> %s', (p, want) => {
    vc.lastCommand = null;
    vc.processCommand(p, 0.9);
    expect(vc.lastCommand ? vc.lastCommand.key : 'null').toBe(want);
  });
});
