// pass DCCXLIV: stonework & masonry domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLIV: stonework & masonry domain (sekizou)', () => {
  const closeTab = ['stoneworker licensed', 'mason certified', 'stone carver registered'];
  const closeTabJa = [
    '石工',
    '石材',
    '石職人',
    '石工職人',
    '石匠',
    '石材店',
    '石屋',
    '石材加工',
    '石材切断',
    '石切り',
    '石切場',
    '石切山',
    '石切職人',
    '石彫刻',
    '石彫',
    '石彫師',
    '石臼',
    '手挽き臼',
    '臼',
    '石臼挽き',
    '石版',
    '石板',
    '石版画',
    'リトグラフ',
    '磨き石',
    '水磨き',
    '水研ぎ',
    '石磨き',
    '鏡面磨き',
    'ブッシュハンマー',
    'ビシャン',
    '石鑿',
    '石タガネ',
    'ポイント',
    'トゥースチゼル',
    'フラットチゼル',
    'コーナーチゼル',
    '石ノミ',
    '石槌',
    '石頭',
    'かけや',
    '石割り',
    '石矢',
    'クサビ',
    '矢穴',
    'セリ矢',
    '割り矢',
    '石運び',
    '石積職人',
    '積石',
    '乱石積み',
    '布積み',
    '谷積み',
    '算木積み',
    '切り込みハギ',
    '野面積み',
    '自然石',
    '景石',
    '庭石',
    '石灯籠',
    '灯籠',
    '春日灯籠',
    '雪見灯籠',
    '織部灯籠',
    '露地灯籠',
    '置き灯籠',
    '竿灯籠',
    '立灯籠',
    '石塔',
    '五輪塔',
    '宝篋印塔',
    '層塔',
    '宝塔',
    '三重塔',
    '五重塔',
    '石塔婆',
    '卒塔婆',
    '板碑',
    '石仏',
    '地蔵',
    '石地蔵',
    '道祖神',
    '庚申塔',
    '馬頭観音',
    '石碑',
    '墓石',
    '墓石店',
    'お墓',
    '墓碑',
    '墓誌',
    '石造',
    '石造美術',
    '石造物',
    '石室',
    '石棺',
    '石厨子',
    '石祠',
    '祠',
    '石鳥居',
    '石門',
    '石柱',
    '石欄干',
    '石柵',
    '玉垣',
    '高欄',
    '石段',
    '石階段',
    '石橋',
    '石垣',
    '石積み',
    '石畳',
    '敷石',
    '玉石',
    '小石',
    '砂利',
    '砕石',
    '青石',
    '御影石',
    '安山岩',
    '凝灰岩',
    '大谷石',
    '稲田石',
    '真壁石',
    '庵治石',
    '鞍馬石',
    '木内石',
    '白川石',
    '天山石',
    '大理石',
    '花崗岩',
    '玄武岩',
    '砂岩',
    '粘板岩',
    '片麻岩',
    '蛇紋岩',
    'チャート',
    '結晶片岩',
    'ミグマタイト',
    '斑岩',
    '閃緑岩',
    '緑色片岩',
    '石灰岩',
    '採石',
    '採石場',
    '丁場',
    '石丁場',
    '石材鉱山',
    '石工事',
    '石材卸',
    '石材問屋',
    '石工技能士',
    '石材技能士',
    '墓石検定',
    '墓石クリーニング',
    '石洗い',
    '石彫体験',
    '石工体験',
    '石組み',
    '石割り師',
    '置石',
    '石運搬',
    '石屋組合',
    '石材協会',
    '石文化',
    '石の美術館',
    '石まつり',
    '石のまち',
    '石産地',
    '石材産地',
    '石工村',
    '採石跡',
    '石切り跡',
    '残欠',
    '石屑',
    '端材',
    '洗い出し',
    '玉砂利',
    '栗石',
    '根石',
    '据え石',
    '沓石',
    '基礎石',
    '地覆',
    '石蓋',
    '石蓋板',
    '目地',
    '目地詰め',
    '目地材',
    '控え積み',
    '控積み',
    '小口積み',
    '小口',
    '天端',
    '天端石',
    '笠石',
    '火袋',
    '中台',
    '竿石',
    '宝珠',
    '請花',
    '礎',
    '台石',
    '腹石',
    '羽目石',
    '間知石',
    '間知',
    '袖石',
    '袖壁',
    '石門柱'
  ];
  const negate = [
    'still awaiting the mason license',
    'still awaiting the stonework cert',
    'まだ石切り前',
    'まだ彫り前',
    'これから積み',
    'まだ磨き前'
  ];
  const nullPins = ['about to visit the stone yard', 'about to file the quarry report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
