// pass DCCLXII: shogi & shogi player domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCLXII: shogi & shogi player domain (shogi)', () => {
  const closeTab = ['shogi player licensed', 'shogi master certified', 'shogi instructor registered'];
  const closeTabJa = [
    '将棋',
    '将棋界',
    '将棋棋士',
    '将棋連盟',
    '日本将棋連盟',
    '奨励会',
    '奨励会員',
    '女流棋士',
    '棋士会',
    '将棋部',
    '将棋教室',
    '将棋道場',
    '将棋盤店',
    '駒師',
    '盤師',
    '書き駒',
    '彫駒',
    '彫埋駒',
    '駒箱',
    '王将',
    '玉将',
    '飛車',
    '角行',
    '金将',
    '銀将',
    '桂馬',
    '香車',
    '歩',
    'と金',
    '成香',
    '成桂',
    '成銀',
    '竜王',
    '竜馬',
    '馬',
    '駒台',
    '持駒',
    '駒得',
    '駒損',
    '駒交換',
    '駒の動き',
    '駒形',
    '駒組み',
    '駒種',
    '駒音',
    '裏駒',
    '表駒',
    '将棋盤',
    '筋',
    '段',
    '敵陣',
    '自陣',
    '居飛車',
    '振り飛車',
    '四間飛車',
    '三間飛車',
    '中飛車',
    '向かい飛車',
    '向い飛車',
    '袖飛車',
    '一間飛車',
    '一間龍',
    'ゴキゲン中飛車',
    '原始中飛車',
    '石田流',
    '石田流三間飛車',
    '鬼殺し',
    '村田システム',
    '角換わり',
    '一手損角換わり',
    '相掛かり',
    '横歩取り',
    '矢倉',
    '雁木',
    '相矢倉',
    '対抗型',
    '持久戦',
    '急戦',
    '角交換',
    '駒組',
    '矢倉囲い',
    '総矢倉',
    '菱矢倉',
    '流れ矢倉',
    '肩囲い',
    '美濃囲い',
    '金美濃',
    '左美濃',
    '本美濃',
    '銀美濃',
    '片美濃',
    '高美濃',
    'ダイヤモンド美濃',
    'カブト囲い',
    '雁木囲い',
    '銀冠',
    '銀冠穴熊',
    '穴熊',
    '本穴熊',
    '相穴熊',
    '船囲い',
    '中原囲い',
    '中原玉',
    '島囲い',
    '英ちゃん流中飛車',
    'ツノ銀',
    '早繰り銀',
    '棒銀',
    '腰掛け銀',
    '金無双',
    '王手',
    '両王手',
    '空き王手',
    '開き王手',
    '十字飛車',
    '角成り',
    '馬の利き',
    '飛車の利き',
    '利き筋',
    '効き',
    '必至',
    '積み',
    '詰み',
    '詰めろ',
    '必死',
    '詰将棋',
    '一手詰',
    '三手詰',
    '五手詰',
    '七手詰',
    '大道詰将棋',
    '実戦詰将棋',
    '双玉',
    '千日手',
    '連続王手',
    '持将棋',
    '宣言',
    '宣言法',
    'トライル',
    '入玉',
    '入玉宣言',
    '点数計算',
    '端攻め',
    '角頭',
    '頭金',
    '腹銀',
    '尻金',
    '裸玉',
    '底歩',
    '垂れ歩',
    '打ち歩',
    '突き捨て',
    '継ぎ歩',
    '二歩',
    '打開',
    '割り打ち',
    '横撃',
    '串刺し',
    '角筋',
    '馬筋',
    '開戦',
    '交換',
    '駒取り',
    '両取り',
    '両取',
    '大駒',
    '小駒',
    '飛車落ち',
    '角落ち',
    '二枚落ち',
    '四枚落ち',
    '六枚落ち',
    '八枚落ち',
    '十枚落ち',
    '平手',
    '香落ち',
    '桂落ち',
    '香桂落ち',
    '成り捨て',
    '不成り',
    '定跡',
    '定跡書',
    '先手有利',
    '後手番',
    '先手番',
    '定跡外し',
    '新手',
    '定跡研究',
    '将棋ソフト',
    '将棋ai',
    '評価値',
    '形勢',
    '優劣',
    '読み筋',
    '変化',
    '候補手',
    '大局観',
    '序盤',
    '中盤',
    '終盤',
    '終盤戦',
    '切れ負け',
    '早指し',
    '名人位',
    '名人戦',
    '竜王戦',
    '王位',
    '王位戦',
    '棋王',
    '棋王戦',
    '王将戦',
    '叡王',
    '叡王戦',
    '順位戦',
    'a級',
    'b級',
    'c級',
    'a級順位戦',
    '朝日杯',
    '銀河戦',
    'nhk杯',
    'nhk杯将棋',
    '新人王戦',
    '永世名人',
    '永世称号',
    '永世竜王',
    '名誉名人',
    '持駒制',
    '打ち歩詰め',
    '二歩反則',
    '反則手',
    '王手放置',
    '打ち歩詰禁止',
    '続行',
    '中断',
    '対局規定',
    '将棋規則',
    '将棋書',
    '将棋雑誌',
    '観戦記',
    '観戦記者',
    '羽生善治',
    '谷川浩司',
    '渡辺明',
    '藤井聡太',
    '豊島将之',
    '永瀬拓矢',
    '木村一基',
    '森内俊之',
    '郷田真隆',
    '佐藤康光',
    '三浦弘行',
    '久保利明',
    '稲葉陽',
    '広瀬章人',
    '中村太地',
    '糸谷哲郎',
    '八代弥',
    '斎藤慎太郎',
    '菅井竜也',
    '高見泰地',
    '増田康宏',
    '都成竜馬',
    '大山康晴',
    '升田幸三',
    '中原誠',
    '米長邦雄',
    '加藤一二三',
    '塚田泰明',
    '森下卓',
    '淡路仁茂',
    '島朗',
    '東和男',
    '桐山清澄',
    '上座',
    '下座',
    '対局時計',
    '感想戦',
    '検討',
    '検討会',
    '大盤',
    '玉頭',
    '玉腹',
    '早逃げ',
    '居玉',
    '端玉',
    '中段玉',
    '全駒',
    '手番',
    '手番割',
    '先手必勝説',
    '一手損'
  ];
  const negate = [
    'still awaiting the shogi license',
    'still awaiting the match ruling',
    'まだ対局前',
    'まだ投了前',
    'これから指し',
    'まだ場所前'
  ];
  const nullPins = ['about to visit the shogi hall', 'about to file the game record'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
