// Pass CCLIX: EN suffocate/crush + JA breath-still/no-mercy (pass CCLIX)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLIX: close-tab coverage', () => {
  test.each([
    "smother it with a cushion", "smother it with a blanket", "suffocate the tab", "suffocate it to death",
    "suffocate it completely", "asphyxiate the tab", "asphyxiate it completely", "choke it completely",
    "choke it to nothing", "strangle it completely", "throttle it completely", "wring its little neck",
    "break its little neck", "crack its neck", "crack the tabs neck", "garotte it",
    "strung it up", "drown it in the pond", "drown it in the well", "drown it in the creek",
    "drown it in the stream", "drown it in the bayou", "drown it in the swamp", "drown it in the marsh",
    "drown it in the bog", "drown it in the mire", "drown it in the fen", "drown it in the lagoon",
    "drown it in the fjord", "drown it in the harbor", "drown it in the harbour", "drown it in the cove",
    "drown it in the inlet", "drown it in the reservoir", "drown it in the quarry", "drown it in the mine shaft",
    "drown it in the well", "drown it in the cauldron", "drown it in the vat", "drown it in the tank",
    "drown it in the aquarium", "drown it in the bowl", "drown it in the glass", "drown it in the cup",
    "drown it in the mug", "drown it in the barrel", "drown it in the drum", "drown it in the bucket",
    "drown it in the pail", "drown it in the tub of water", "drown it in a tub", "drown it in a bath",
    "drown it in a river", "drown it in a lake", "drown it in a sea", "drown it in an ocean",
    "drown it in a pool", "drown it in a pond", "drown it in a well", "drown it in a creek",
    "drown it in a stream", "drown it in a bayou", "drown it in a swamp", "drown it in a marsh",
    "drown it in a bog", "drown it in a mire", "drown it in a fen", "drown it in a lagoon",
    "drown it in a fjord", "drown it in a harbor", "drown it in a harbour", "drown it in a cove",
    "drown it in an inlet", "drown it in a reservoir", "drown it in a quarry", "drown it in a mine shaft",
    "drown it in a cauldron", "drown it in a tank", "drown it in an aquarium", "drown it in a bowl",
    "drown it in a glass", "drown it in a cup", "drown it in a mug", "drown it in a drum",
    "drown it in a pail", "hold the tab under water", "hold it under the surface", "hold it beneath the surface",
    "hold it below the surface", "hold it under the waves", "hold it beneath the waves", "hold it below the waves",
    "submerge it fully", "submerge it in water", "submerge it in the tub", "submerge it in the bath",
    "submerge it in the river", "submerge it in the lake", "submerge it in the sea", "submerge it in the ocean",
    "submerge it in the pool", "submerge it in the pond", "submerge it in the well", "submerge it in the swamp",
    "submerge it in the bog", "submerge it in the mire", "immerse it entirely", "immerse it in water",
    "immerse it in the tub", "immerse it in the bath", "immerse it in the river", "immerse it in the lake",
    "immerse it in the sea", "immerse it in the ocean", "plunge it beneath the surface", "plunge it below the surface",
    "plunge it under the waves", "plunge it below the waves", "plunge it into the briny deep", "plunge it into the ocean depths",
    "plunge it into the sea depths", "plunge it into the lake depths", "plunge it into the river depths", "plunge it into the well depths",
    "plunge it into the black water", "plunge it into the dark water", "plunge it into the murky water", "plunge it into the icy water",
    "plunge it into the cold water", "plunge it into the freezing water", "plunge it into the boiling water", "plunge it into the scalding water",
    "plunge it into the molten lava", "plunge it into the volcano", "plunge it into the magma", "plunge it into the caldera",
    "plunge it into the crater", "plunge it into the vent", "plunge it into the furnace", "plunge it into the forge",
    "plunge it into the kiln", "plunge it into the oven", "plunge it into the ravine", "plunge it into the canyon",
    "plunge it into the crevasse", "plunge it into the crevice", "plunge it into the fissure", "plunge it into the hole",
    "plunge it into the hole in the ground", "plunge it into the vacuum", "plunge it into the emptiness", "plunge it into the nothingness",
    "plunge it into the shadows", "plunge it into the blackness", "plunge it into the murk", "plunge it into the gloom",
    "plunge it into the night", "plunge it into the fog", "plunge it into the mist", "plunge it into the haze",
    "plunge it into the vapor", "plunge it into the smoke", "plunge it into the smog", "plunge it into the ether",
    "plunge it into the nether", "plunge it into limbo", "plunge it into purgatory", "plunge it into hell",
    "plunge it into perdition", "plunge it into damnation", "plunge it into tartarus", "plunge it into hades",
    "plunge it into the underworld", "plunge it into the netherworld", "plunge it into the fiery pit", "plunge it into the burning pit",
    "plunge it into the lake of fire", "plunge it into the river styx", "plunge it into the styx", "plunge it into oblivion",
    "plunge it into nonexistence", "plunge it into nonexistence forever", "smash it with a hammer", "smash the tab with a hammer",
    "smash it with a sledgehammer", "smash the tab with a sledgehammer", "smash it with a mallet", "smash the tab with a mallet",
    "smash it with a bat", "smash the tab with a bat", "smash it with a club", "smash the tab with a club",
    "smash it with a crowbar", "smash the tab with a crowbar", "smash it with a pipe", "smash the tab with a pipe",
    "smash it with a wrench", "smash the tab with a wrench", "smash it with a brick", "smash the tab with a brick",
    "smash it with a rock", "smash the tab with a rock", "smash it with a boulder", "smash the tab with a boulder",
    "smash it with a stone", "smash the tab with a stone", "smash it with a bottle", "smash the tab with a bottle",
    "smash it with a boot", "smash the tab with a boot", "smash it with a shoe", "smash the tab with a shoe",
    "smash it with a fist", "smash the tab with a fist", "smash it with a knee", "smash the tab with a knee",
    "smash it with an elbow", "smash the tab with an elbow", "smash it with a foot", "smash the tab with a foot",
    "smash it underfoot", "smash the tab underfoot", "stomp it", "stomp the tab",
    "stomp it flat", "stomp it to bits", "stomp it to pieces", "stomp it to nothing",
    "stomp it to dust", "stomp it into the ground", "stomp it into the dirt", "stomp it into the mud",
    "stomp it into the dust", "stomp it into the pavement", "stomp it into the asphalt", "stomp it into the concrete",
    "stomp it underfoot", "stomp the tab underfoot", "stomp on it", "stomp on the tab",
    "stamp on the tab", "stamp it to bits", "stamp it to pieces", "stamp it to nothing",
    "stamp it into the ground", "stamp it into the dirt", "stamp it into the mud", "stamp it into the dust",
    "stamp it underfoot", "trample it", "trample the tab", "trample it flat",
    "trample it to bits", "trample it to pieces", "trample it to nothing", "trample it to dust",
    "trample it into the ground", "trample it into the dirt", "trample it into the mud", "trample it into the dust",
    "trample it underfoot", "trample the tab underfoot", "trample it to death", "trample it into oblivion",
    "crush it underfoot", "crush the tab underfoot", "crush it flat", "crush it to bits",
    "crush it to pieces", "crush it to nothing", "crush it to dust", "crush it into the ground",
    "crush it into the dirt", "crush it into the mud", "crush it into the dust", "crush it into a ball",
    "crush it into pulp", "crush it into paste", "crush it into powder", "crush it into dust",
    "crush it into atoms", "crush it into nothing", "crush it into oblivion", "crush it in a vice",
    "crush it in a vise", "crush it in a clamp", "crush it in a press", "crush it in a hydraulic press",
    "crush it in a machine press", "crush it in a trash compactor", "crush it in a car crusher", "crush it in a junkyard crusher",
    "crush it under a boot", "crush it under a shoe", "crush it under a heel", "crush it under a tire",
    "crush it under a wheel", "crush it under a tank", "crush it under a bulldozer", "crush it under a steamroller",
    "crush it under a road roller", "crush it under a steam roller", "crush it under a paver", "crush it under a compactor",
    "run it over", "run it over with a car", "run it over with a truck", "run it over with a bus",
    "run it over with a train", "run it over with a tank", "run it over with a bulldozer", "run it over with a steamroller",
    "run it over with a semi", "run it over with a semi-truck", "run it over with a big rig", "run it over with an eighteen-wheeler",
    "run it over with an 18-wheeler", "run it over with a monster truck", "run it over with a pickup", "run it over with a sedan",
    "run it over with a suv", "run it over with a jeep", "run it over with a humvee", "run it over with a tank",
    "drive over it in a car", "drive over it in a truck", "drive over it in a bus", "drive over it in a tank",
    "drive over it in a bulldozer", "drive over it in a steamroller", "drive over it in a semi", "drive over it in a monster truck",
    "run it down", "run the tab down", "run it down with a car", "run it down with a truck",
    "run it down with a bus", "run it down with a train", "run it down with a tank", "run it down with a bulldozer",
    "run it down with a steamroller", "mow it down with a car", "mow it down with a truck", "mow it down with a tank",
    "mow it down with a bulldozer", "mow it down with a lawnmower", "mow it down with a mower", "mow it down with a scythe",
    "mow it down like grass", "mow it down like weeds", "mow it down completely", "run over the tab",
    "flatten it completely", "flatten it entirely", "flatten it to nothing", "flatten it into the ground",
    "flatten it like a pancake", "flatten it like a tortilla", "flatten it like a crepe", "flatten it like paper",
    "flatten it like a sheet", "steamroll the tab", "steamroll it flat", "steamroll it completely",
    "steamroll it to nothing", "steamroll it into the ground", "steamroll it into the pavement", "steamroll it into the asphalt",
    "make the tab roadkill", "turn it into roadkill", "turn the tab into roadkill", "leave the tab to rot",
    "let the tab rot", "let it rot in the ground", "let it rot in the earth", "let it rot in the soil",
    "let it rot in the field", "let it rot in the forest", "let it rot in the woods", "let it rot in the desert",
    "let it rot in the sun", "let it rot in the heat", "let it rot in the cold", "let it rot in the rain",
    "let it rot in the snow", "let it rot in the mud", "let it rot in the gutter", "let it rot in the trash",
    "let it rot in the dump", "let it rot in the ground", "let it rot forever", "let it rot for eternity",
    "let it rot in hell", "let it rot in oblivion", "let it rot in the void", "let it rot in the abyss",
    "let it rot in the pit", "let it rot in the hole", "let it rot in the grave", "let it rot in the tomb",
    "let it rot in the earth", "leave the tab to die", "let the tab die", "let it die in the ground",
    "let it die in the field", "let it die in the cold", "let it die in the dark", "let it die alone",
    "let it die alone in the dark", "let it die alone in the cold", "let it die a slow death", "let it die a painful death",
    "let it die a horrible death", "let it die a miserable death", "let it die a lonely death", "let it die a forgotten death",
    "let it die an unmarked death", "let it die an unloved death", "let it die an unmourned death", "let it die without a name",
    "let it die without a grave", "let it die without a marker", "let it die without a stone", "let it die without a funeral",
    "let it die without a burial", "let it die without a wake", "let it die without mourners", "let it die without tears",
    "let it die without anyone caring", "let it die without anyone noticing", "let it die without anyone knowing", "let it die without anyone remembering",
    "let it die without anyone missing it", "let it die without anyone mourning it", "let it die without anyone grieving it", "let it die without anyone caring about it",
    "let it die without anyone giving a damn", "let it die without anyone giving a shit", "let it die without anyone giving a fuck", "let it die without anyone batting an eye",
    "let it die without anyone lifting a finger", "let it die without anyone shedding a tear", "let it die without anyone saying a word", "let it die without anyone saying goodbye",
    "let it die without anyone saying a prayer", "let it die without anyone saying a eulogy", "let it die without anyone saying a last rite", "let it die without anyone saying a benediction",
    "let it die without anyone saying a requiem", "let it die without anyone saying a memorial", "let it die without anyone saying a tribute", "let it die without anyone honoring it",
    "let it die without anyone remembering it", "let it die without anyone missing it", "let it die without anyone loving it", "let it die without anyone caring for it",
    "let it die without anyone thinking of it", "let it die without anyone wanting it back", "let it die without anyone wishing it back", "let it die without anyone longing for it",
    "let it die without anyone pining for it", "let it die without anyone yearning for it", "let it die without anyone craving it", "let it die without anyone desiring it",
    "let it die without anyone wanting it", "let it die without anyone needing it", "let it die without anyone requiring it", "let it die without anyone asking for it",
    "let it die without anyone begging for it", "let it die without anyone pleading for it", "let it die without anyone crying for it", "let it die without anyone weeping for it",
    "let it die without anyone sobbing for it", "let it die without anyone mourning for it", "let it die without anyone grieving for it", "let it die without anyone sorrowing for it",
    "let it die without anyone lamenting it", "let it die without anyone wailing for it", "let it die without anyone keening for it", "let it die without anyone screaming for it",
    "let it die without anyone shouting for it", "let it die without anyone calling for it", "let it die without anyone calling it back", "let it die without anyone calling it home",
    "let it die without anyone calling it by name", "let it die without anyone calling out to it", "let it die without anyone reaching for it", "let it die without anyone reaching out to it",
    "let it die without anyone stretching out to it", "let it die without anyone grasping for it", "let it die without anyone clutching for it", "let it die without anyone clawing for it",
    "let it die without anyone scratching for it", "let it die without anyone digging for it", "let it die without anyone looking for it", "let it die without anyone seeking it",
    "let it die without anyone hunting for it", "let it die without anyone tracking it", "let it die without anyone tracing it", "let it die without anyone discovering it",
    "let it die without anyone uncovering it", "let it die without anyone unearthing it", "let it die without anyone exhuming it", "let it die without anyone resurrecting it",
    "let it die without anyone reviving it", "let it die without anyone resuscitating it", "let it die without anyone bringing it back", "let it die without anyone restoring it",
    "let it die without anyone reinstating it", "let it die without anyone reanimating it", "let it die without anyone reawakening it", "let it die without anyone awakening it",
    "let it die without anyone waking it", "let it die without anyone stirring it", "let it die without anyone rousing it", "let it die without anyone arousing it",
    "let it die without anyone provoking it", "let it die without anyone inciting it", "let it die without anyone stimulating it", "let it die without anyone exciting it",
    "let it die without anyone animating it", "let it die without anyone enlivening it", "let it die without anyone vivifying it", "let it die without anyone energizing it",
    "let it die without anyone vitalizing it", "let it die without anyone quickening it", "let it die without anyone breathing life into it", "let it die without anyone breathing life back into it",
    "let it die without anyone giving it a second chance", "let it die without anyone giving it another chance", "let it die without anyone giving it one more chance", "let it die without anyone giving it a reprieve",
    "let it die without anyone giving it a stay", "let it die without anyone giving it a pardon", "let it die without anyone giving it clemency", "let it die without anyone giving it mercy",
    "let it die without anyone giving it grace", "let it die without anyone giving it amnesty", "let it die without anyone giving it absolution", "let it die without anyone giving it forgiveness",
    "let it die without anyone forgiving it", "let it die without anyone sparing it", "let it die without anyone saving it", "let it die without anyone rescuing it",
    "let it die without anyone preserving it", "let it die without anyone protecting it", "let it die without anyone shielding it", "let it die without anyone sheltering it",
    "let it die without anyone harboring it", "let it die without anyone harbouring it", "let it die without anyone guarding it", "let it die without anyone defending it",
    "let it die without anyone standing up for it", "let it die without anyone fighting for it", "let it die without anyone battling for it", "let it die without anyone struggling for it",
    "let it die without anyone striving for it", "let it die without anyone working for it", "let it die without anyone laboring for it", "let it die without anyone labouring for it",
    "let it die without anyone toiling for it", "let it die without anyone sweating for it", "let it die without anyone bleeding for it", "let it die without anyone suffering for it",
    "let it die without anyone enduring for it", "let it die without anyone bearing for it", "let it die without anyone carrying for it", "let it die without anyone holding for it",
    "let it die without anyone keeping for it", "let it die without anyone retaining for it", "let it die without anyone maintaining for it", "let it die without anyone sustaining for it",
    "let it die without anyone nurturing for it", "let it die without anyone nourishing for it", "let it die without anyone feeding for it", "let it die without anyone fostering for it",
    "let it die without anyone cherishing for it", "let it die without anyone treasuring for it", "let it die without anyone valuing for it", "let it die without anyone prizing for it",
    "let it die without anyone appreciating for it", "let it die without anyone admiring for it", "let it die without anyone respecting for it", "let it die without anyone esteeming for it",
    "let it die without anyone honoring for it", "let it die without anyone honouring for it", "let it die without anyone revering for it", "let it die without anyone venerating for it",
    "let it die without anyone worshipping for it", "let it die without anyone worshiping for it", "let it die without anyone idolizing for it", "let it die without anyone adoring for it",
    "let it die without anyone loving for it", "let it die without anyone caring for it", "let it die without anyone mourning for it", "let it die without anyone searching for it",
    "let it die without anyone finding it", "息の根を止めちゃえ", "息の根を止めろと言ってんだ", "息の根を止めるからな",
    "息の根を止めるのが筋だ", "息の根を止めるのが正解だ", "息の根を止めるということだ", "息の根を止めるという決定だ",
    "息の根を止めるという判断だ", "息を止めて", "息を止めるんだ", "息を止めるべきだ",
    "息を絶やせ", "息を絶やすんだ", "息を絶やせよ", "息を絶やすべきだ",
    "呼吸を止めろ", "呼吸を止めて", "呼吸を止めるんだ", "呼吸を止めろよ",
    "呼吸を止めるべきだ", "呼吸を絶やせ", "呼吸を絶やして", "呼吸を絶やすんだ",
    "呼吸を絶やせよ", "呼吸を絶やすべきだ", "呼吸を絶て", "呼吸を絶って",
    "呼吸を絶つんだ", "呼吸を絶てよ", "呼吸を絶つべきだ", "命の灯を消せ",
    "命の灯を消して", "命の灯を消すんだ", "命の灯を消せよ", "命の灯を消すべきだ",
    "命の灯を消してしまえ", "命の灯を消しちまえ", "命の灯を消しちゃえ", "命の灯を消しとけ",
    "命の灯を消したまえ", "命の灯を消しやがれ", "命の灯を消せや", "命の灯を消せって",
    "命の灯を消せと言ってんだ", "命の灯を消すつもりだ", "命の灯を消すわ", "命の灯を消すぞ",
    "命の灯を消すぜ", "命の灯を消すからな", "命の灯を消すことにした", "命の灯を消すのが筋だ",
    "命の灯を消すのが正解だ", "命の灯を消すということだ", "命の灯を消すという決定だ", "命の灯を消すという判断だ",
    "命の火を消せ", "命の火を消して", "命の火を消すんだ", "命の火を消せよ",
    "命の火を消すべきだ", "命の炎を消せ", "命の炎を消して", "命の炎を消すんだ",
    "命の炎を消せよ", "命の炎を消すべきだ", "命を消せ", "命を消して",
    "命を消すんだ", "命を消せよ", "命を消すべきだ", "命を絶て",
    "命を絶って", "命を絶つんだ", "命を絶てよ", "命を絶つべきだ",
    "命を断て", "命を断って", "命を断つんだ", "命を断てよ",
    "命を断つべきだ", "命を絶やせ", "命を絶やして", "命を絶やすんだ",
    "命を絶やせよ", "命を絶やすべきだ", "生きる資格なし", "生きる資格はない",
    "生きる資格なしだ", "生きる資格などない", "生きる資格はないんだ", "生きる資格なんてない",
    "生きる資格がない", "生きる資格は無い", "生きる資格など無い", "生きる資格も無い",
    "生きる資格すらない", "生きる資格さえない", "生きる資格は皆無", "生きる価値なし",
    "生きる価値はない", "生きる価値なしだ", "生きる価値などない", "生きる価値はないんだ",
    "生きる価値なんてない", "生きる価値がない", "生きる価値は無い", "生きる価値など無い",
    "生きる価値も無い", "生きる価値すらない", "生きる価値さえない", "生きる価値は皆無",
    "生きている価値なし", "生きている価値はない", "生きている価値がない", "生きている資格なし",
    "生きている資格はない", "生きている資格がない", "生き残る資格なし", "生き残る資格はない",
    "生き残る資格がない", "存続する資格なし", "存続する資格はない", "存続する資格がない",
    "存在する資格なし", "存在する資格はない", "存在する資格がない", "存在する価値なし",
    "存在する価値はない", "存在する価値がない", "存在する意味なし", "存在する意味はない",
    "存在する意味がない", "存在する理由なし", "存在する理由はない", "存在する理由がない",
    "存在する必要なし", "存在する必要はない", "存在する必要がない", "存在する意義なし",
    "存在する意義はない", "存在する意義がない", "存在する権利なし", "存在する権利はない",
    "存在する権利がない", "生きる権利なし", "生きる権利はない", "生きる権利がない",
    "生存する権利なし", "生存する権利はない", "生存する権利がない", "生存権なし",
    "生存権はない", "生存権がない", "生存権などない", "存続権なし",
    "存続権はない", "存続権がない", "存続権などない", "居場所なし",
    "居場所はない", "居場所がない", "居場所などない", "居場所なんてない",
    "居場所すらない", "居場所さえない", "居場所は皆無", "居場所はどこにもない",
    "居る場所なし", "居る場所はない", "居る場所がない", "居る場所などない",
    "居る場所なんてない", "居る場所すらない", "居る場所さえない", "居る場所は皆無",
    "居る場所はどこにもない", "存在場所なし", "存在場所はない", "存在場所がない",
    "存在領域なし", "存在領域はない", "存在領域がない", "存在根拠なし",
    "存在根拠はない", "存在根拠がない", "存在意義なし", "存在意義はない",
    "存在意義がない", "存在理由なし", "存在理由はない", "存在理由がない",
    "存在目的なし", "存在目的はない", "存在目的がない", "存在価値なし",
    "存在価値はない", "存在価値がない", "存在資格なし", "存在資格はない",
    "存在資格がない", "存在権なし", "存在権はない", "存在権がない",
    "許されない存在", "許されない存在だ", "許されざる存在", "許されざる存在だ",
    "許されざる者", "許されざる者だ", "許されざるもの", "許されざるものだ",
    "許されないもの", "許されないものだ", "許されないやつ", "許されないやつだ",
    "許せない存在", "許せない存在だ", "許せざる存在", "許せざる存在だ",
    "許せないもの", "許せないものだ", "許せないやつ", "許せないやつだ",
    "容認できない存在", "容認できない存在だ", "容認できないもの", "容認できないものだ",
    "容認できないやつ", "容認できないやつだ", "認められない存在", "認められない存在だ",
    "認められないもの", "認められないものだ", "認められないやつ", "認められないやつだ",
    "認めるに値しない存在", "認めるに値しないもの", "認めるに値しないやつ", "認める価値なし",
    "認める価値はない", "認める価値がない", "認める価値などない", "認める価値なんてない",
    "認める価値すらない", "認める価値さえない", "認める価値は皆無", "容赦する価値なし",
    "容赦する価値はない", "容赦する価値がない", "容赦の余地なし", "容赦の余地はない",
    "容赦の余地がない", "容赦する理由なし", "容赦する理由はない", "容赦する理由がない",
    "猶予なし", "猶予はない", "猶予がない", "猶予などない",
    "猶予なんてない", "猶予すらない", "猶予さえない", "猶予は皆無",
    "猶予の余地なし", "猶予の余地はない", "猶予の余地がない", "情け無用",
    "情け無用だ", "情けは無用", "情けは無用だ", "情けなど無用",
    "情けなど無用だ", "慈悲無用", "慈悲無用だ", "慈悲は無用",
    "慈悲は無用だ", "慈悲など無用", "慈悲など無用だ", "慈悲の余地なし",
    "慈悲の余地はない", "慈悲の余地がない", "慈悲なし", "慈悲はない",
    "慈悲がない", "慈悲などない", "慈悲なんてない", "慈悲すらない",
    "慈悲さえない", "慈悲は皆無", "慈悲など皆無", "恩赦なし",
    "恩赦はない", "恩赦がない", "恩赦などない", "恩赦なんてない",
    "恩赦すらない", "恩赦さえない", "恩赦は皆無", "恩赦の余地なし",
    "恩赦の余地はない", "恩赦の余地がない", "特赦なし", "特赦はない",
    "特赦がない", "特赦などない", "特赦なんてない", "特赦すらない",
    "特赦さえない", "特赦は皆無", "特赦の余地なし", "特赦の余地はない",
    "特赦の余地がない", "減刑なし", "減刑はない", "減刑がない",
    "減刑などない", "減刑なんてない", "減刑すらない", "減刑さえない",
    "減刑は皆無", "減刑の余地なし", "減刑の余地はない", "減刑の余地がない",
    "免罪なし", "免罪はない", "免罪がない", "免罪などない",
    "免罪なんてない", "免罪すらない", "免罪さえない", "免罪は皆無",
    "免罪の余地なし", "免罪の余地はない", "免罪の余地がない", "免責なし",
    "免責はない", "免責がない", "免責などない", "免責なんてない",
    "免責すらない", "免責さえない", "免責は皆無", "免責の余地なし",
    "免責の余地はない", "免責の余地がない", "執行猶予なし", "執行猶予はない",
    "執行猶予がない", "執行猶予などない", "執行猶予なんてない", "執行猶予すらない",
    "執行猶予さえない", "執行猶予は皆無", "執行猶予の余地なし", "執行猶予の余地はない",
    "執行猶予の余地がない", "情状酌量なし", "情状酌量はない", "情状酌量がない",
    "情状酌量などない", "情状酌量なんてない", "情状酌量すらない", "情状酌量さえない",
    "情状酌量は皆無", "情状酌量の余地なし", "情状酌量の余地はない", "情状酌量の余地がない",
    "酌量の余地なし", "酌量の余地はない", "酌量の余地がない", "弁解の余地なし",
    "弁解の余地はない", "弁解の余地がない", "弁明の余地なし", "弁明の余地はない",
    "弁明の余地がない", "言い訳の余地なし", "言い訳の余地はない", "言い訳の余地がない",
    "言い訳無用", "言い訳無用だ", "言い訳は無用", "言い訳は無用だ",
    "言い訳など無用", "言い訳など無用だ", "反論の余地なし", "反論の余地はない",
    "反論の余地がない", "異議の余地なし", "異議の余地はない", "異議の余地がない",
    "異議申し立て無用", "異議申し立て無用だ", "異議申し立ては無用", "異議申し立ては無用だ",
    "控訴の余地なし", "控訴の余地はない", "控訴の余地がない", "控訴無用",
    "控訴無用だ", "控訴は無用", "控訴は無用だ", "上告の余地なし",
    "上告の余地はない", "上告の余地がない", "上告無用", "上告無用だ",
    "上告は無用", "上告は無用だ", "再審の余地なし", "再審の余地はない",
    "再審の余地がない", "再審無用", "再審無用だ", "再審は無用",
    "再審は無用だ", "助命嘆願無用", "助命嘆願無用だ", "助命嘆願は無用",
    "助命嘆願は無用だ", "助命の余地なし", "助命の余地はない", "助命の余地がない",
    "助命無用", "助命無用だ", "助命は無用", "助命は無用だ",
    "命乞い無用", "命乞い無用だ", "命乞いは無用", "命乞いは無用だ",
    "命乞いしても無駄", "命乞いしても無駄だ", "命乞いしても無意味", "命乞いしても無意味だ",
    "命乞いしても遅い", "命乞いしても遅いんだ", "命乞いしても遅すぎる", "命乞いしても間に合わない",
    "泣きついても無駄", "泣きついても無駄だ", "泣きついても無意味", "泣きついても無意味だ",
    "泣きついても遅い", "泣きついても遅いんだ", "泣きついても間に合わない", "泣きついても間に合わないんだ",
    "許しを請うても無駄", "許しを請うても無駄だ", "許しを請うても遅い", "許しを請うても遅いんだ",
    "許しを乞うても無駄", "許しを乞うても無駄だ", "許しを乞うても遅い", "許しを乞うても遅いんだ",
    "赦しを請うても無駄", "赦しを請うても無駄だ", "赦しを乞うても無駄", "赦しを乞うても無駄だ",
    "慈悲を請うても無駄", "慈悲を請うても無駄だ", "慈悲を乞うても無駄", "慈悲を乞うても無駄だ",
    "慈悲を請うても遅い", "慈悲を乞うても遅い", "容赦を請うても無駄", "容赦を請うても無駄だ",
    "容赦を乞うても無駄", "容赦を乞うても無駄だ", "許しても遅い", "許しても遅いんだ",
    "許しても間に合わない", "許してももう遅い", "今更許しても遅い", "今更許しても遅いんだ",
    "今更許しても遅すぎる", "今更許しても間に合わない", "今更命乞いしても遅い", "今更命乞いしても遅いんだ",
    "今更命乞いしても間に合わない", "今更泣きついても遅い", "今更泣きついても遅いんだ", "今更泣きついても間に合わない",
    "今更慈悲を請うても遅い", "今更慈悲を乞うても遅い", "今更容赦を請うても遅い", "今更容赦を乞うても遅い",
    "今更謝っても遅い", "今更謝っても遅いんだ", "今更謝っても遅すぎる", "今更謝っても間に合わない",
    "今更謝っても意味がない", "今更謝っても無駄", "今更謝っても無駄だ", "今更謝っても無意味",
    "今更謝っても無意味だ", "今更謝っても許さない", "今更謝っても許さないぞ", "今更謝っても許されない",
    "今更謝っても赦されない", "今更謝っても助からない", "今更謝っても助からないぞ", "今更謝っても終わりだ",
    "今更謝っても遅かった", "今更反省しても遅い", "今更反省しても遅すぎる", "今更反省しても間に合わない",
    "今更反省しても意味がない", "今更反省しても無駄", "今更反省しても無意味", "今更反省しても許さない",
    "今更反省しても許されない", "今更反省しても赦されない", "今更反省しても助からない", "今更反省しても終わりだ",
    "今更後悔しても遅い", "今更後悔しても遅いんだ", "今更後悔しても遅すぎる", "今更後悔しても間に合わない",
    "今更後悔しても意味がない", "今更後悔しても無駄", "今更後悔しても無意味", "今更後悔しても許さない",
    "今更後悔しても許されない", "今更後悔しても赦されない", "今更後悔しても助からない", "今更後悔しても終わりだ",
    "今更悔い改めても遅い", "今更悔い改めても遅いんだ", "今更悔い改めても遅すぎる", "今更悔い改めても間に合わない",
    "今更悔い改めても意味がない", "今更悔い改めても無駄", "今更悔い改めても無意味", "今更悔い改めても許さない",
    "今更悔い改めても許されない", "今更悔い改めても赦されない", "今更悔い改めても助からない", "今更悔い改めても終わりだ",
    "今更謝罪しても遅い", "今更謝罪しても遅いんだ", "今更謝罪しても遅すぎる", "今更謝罪しても間に合わない",
    "今更謝罪しても意味がない", "今更謝罪しても無駄", "今更謝罪しても無意味", "今更謝罪しても許さない",
    "今更謝罪しても許されない", "今更謝罪しても赦されない", "今更謝罪しても助からない", "今更謝罪しても終わりだ",
    "今更改心しても遅い", "今更改心しても遅いんだ", "今更改心しても遅すぎる", "今更改心しても間に合わない",
    "今更改心しても意味がない", "今更改心しても無駄", "今更改心しても無意味", "今更改心しても許さない",
    "今更改心しても許されない", "今更改心しても赦されない", "今更改心しても助からない", "今更改心しても終わりだ",
    "今更生まれ変わっても遅い", "今更生まれ変わっても遅いんだ", "今更生まれ変わっても間に合わない", "今更生まれ変わっても意味がない",
    "今更生まれ変わっても無駄", "今更生まれ変わっても無意味", "今更生まれ変わっても許さない", "今更生まれ変わっても許されない",
    "今更生まれ変わっても赦されない", "今更生まれ変わっても助からない", "今更生まれ変わっても終わりだ", "今更生き返っても遅い",
    "今更生き返っても遅いんだ", "今更生き返っても間に合わない", "今更生き返っても意味がない", "今更生き返っても無駄",
    "今更生き返っても無意味", "今更生き返っても許さない", "今更生き返っても許されない", "今更生き返っても赦されない",
    "今更生き返っても助からない", "今更生き返っても終わりだ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
