// pass DCCXLVI: tatami & rush-mat craft domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLVI: tatami & rush-mat craft domain (tatami)', () => {
  const closeTab = ['tatami maker licensed', 'mat weaver certified', 'tatami artisan registered'];
  const closeTabJa = [
    '畳一枚',
    '畳表',
    '畳床',
    '畳縁',
    '畳職人',
    '畳店',
    '畳屋',
    '藺草',
    'いぐさ',
    '灯芯草',
    'ワラ床',
    '稲藁',
    '畳替え',
    '表替え',
    '裏返し',
    '新畳',
    '敷き込み',
    '畳敷き',
    '畳張り',
    '畳ヘリ',
    'ヘリ付き',
    '縁無し',
    '縁付き',
    '琉球畳',
    'ダイケン畳',
    '積水畳',
    'セキスイ畳',
    '和紙畳',
    '樹脂畳',
    '置き畳',
    'ユニット畳',
    '半畳',
    '京間',
    '江戸間',
    '団地間',
    '中京間',
    '六一間',
    '本間',
    '目積',
    '目積表',
    '引目',
    '綴目',
    '綴目表',
    '畳織り',
    '畳機',
    '畳製造',
    '畳工場',
    '畳検定',
    '畳製作技能士',
    '畳職',
    '畳工',
    '畳匠',
    '畳針',
    '畳鋸',
    '畳ナイフ',
    '畳定規',
    '畳込み',
    '畳締め',
    '畳縁綴',
    '縁綴り',
    '縁縫い',
    '縁付け',
    '縁取り',
    '畳下',
    '畳上げ',
    '畳干し',
    '畳干し機',
    '畳乾燥',
    '畳張替',
    '畳修繕',
    '畳修理',
    '畳製造元',
    '畳材料',
    '畳素材',
    '畳資材',
    '畳卸',
    '畳問屋',
    '畳産地',
    '熊本畳',
    '岡山畳',
    '高知畳',
    '広島畳',
    '備後畳',
    '佐賀畳',
    'い草',
    '藺草畳',
    '畳表織物',
    '畳表糸',
    '麻綿',
    '綿糸',
    '畳綿',
    '畳麻',
    '藁入り',
    '藁床',
    '建材畳',
    '発泡畳',
    '畳目',
    '畳の目',
    '畳の香り',
    '畳の縁',
    '畳の芯',
    '畳の裏',
    '畳の角',
    '畳製品',
    '畳製造業',
    '畳業界',
    '畳組合',
    '畳協会',
    '畳技能士',
    '畳の寸法',
    '畳割り',
    '畳敷き方',
    '畳の向き',
    '畳の継ぎ目',
    '畳の目合わせ',
    '畳合わせ',
    '畳敷設',
    '畳敷き替え',
    '畳の部屋',
    '和室畳',
    '畳ルーム',
    '畳スペース',
    '畳コーナー',
    '畳ベンチ',
    '畳ベッド',
    '畳マット',
    '畳カーペット',
    '畳クッション',
    '畳座椅子',
    '畳テーブル',
    '畳風',
    '畳調',
    '畳柄',
    '畳敷物',
    '畳掃除',
    '畳掃除機',
    '畳拭き',
    '畳ワックス',
    '畳クリーナー',
    '畳ダニ',
    '畳カビ',
    '畳メンテナンス',
    '畳手入れ',
    '畳の手入れ',
    '畳の寿命',
    '畳の耐久',
    '畳の品質',
    '畳格付け',
    '畳ランク',
    '上敷',
    '上敷き',
    'ござ',
    '茣蓙',
    'むしろ',
    '莚',
    '菅茣蓙',
    '花茣蓙',
    '敷物',
    '敷き物',
    '敷き藁',
    '茣蓙職人',
    'むしろ編み',
    '茣蓙編み',
    '編み茣蓙',
    '畳表張替',
    '畳芯',
    '畳の厚さ',
    '畳糸',
    '縁糸',
    '畳角',
    '畳縁柄',
    '縁柄',
    '高麗縁',
    '鯔背縁',
    '雲文縁',
    '亀甲縁',
    '紋縁',
    '無地縁',
    '畳裁断',
    '畳測り',
    '畳見積もり',
    '畳納品',
    '畳業',
    '畳師',
    '畳工務店',
    '畳専門店',
    '畳屋さん',
    '畳問屋街',
    '畳の材料屋',
    'い草農家',
    'い草産地',
    'い草栽培',
    'い草刈り',
    'い草乾燥',
    'い草染め',
    'い草織り',
    'い草製品',
    'い草座布団',
    'い草カーペット',
    'い草マット',
    'い草ラグ'
  ];
  const negate = [
    'still awaiting the tatami license',
    'still awaiting the mat cert',
    'まだ畳替え前',
    'まだ敷き前',
    'これから張り',
    'まだ縫い前'
  ];
  const nullPins = ['about to visit the tatami shop', 'about to file the mat report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
