// pass DCCXLI: metalwork & blacksmithing domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXLI: metalwork & blacksmithing domain (tatara)', () => {
  const closeTab = ['blacksmith licensed', 'metalworker certified', 'forge master registered'];
  const closeTabJa = [
    '金工',
    '金工師',
    '鍛冶',
    '鍛冶屋',
    '鍛冶職人',
    '鍛冶場',
    '鍛造',
    '鍛造品',
    '鍛工',
    '鍛金',
    '鍛金家',
    '彫金',
    '彫金師',
    '彫り金',
    '金細工',
    '金銀細工',
    '彫り金具',
    '鋳金',
    '鋳金家',
    '鋳物',
    '鋳物師',
    '鋳掛け屋',
    '鋳造',
    '鋳造品',
    '砂型',
    '型取り',
    '脱蜡',
    '脱蜡鋳造',
    'ロストワックス',
    '石膏型',
    '鋳型',
    '湯口',
    '湯道',
    '押し湯',
    '鋳ばり',
    'バリ取り',
    '巣',
    '鋳造欠陥',
    '型抜き',
    '鍛接',
    '鍛着',
    '鍛錬',
    '火造り',
    '火床',
    '炭火',
    '鞴',
    'ふいご',
    '床',
    '金床',
    '鉄床',
    'ハンマー',
    '金槌',
    '敲き',
    '横敲き',
    '縦敲き',
    '槌',
    '小槌',
    '鎚起',
    '鎚起銅器',
    '槌目',
    '打ち目',
    '鎚痕',
    '打ち出し',
    '起こし彫り',
    '彫り',
    '彫刻',
    '片切彫',
    '平彫',
    '毛彫',
    '肉置彫',
    '透かし彫り',
    '荒彫り',
    '中彫り',
    '仕上げ彫り',
    '繊細彫り',
    '鋭彫',
    '彫台',
    '鏨',
    'タガネ',
    '鏨彫り',
    '鏨出し',
    '鏨金',
    '象嵌',
    '平象嵌',
    '高象嵌',
    '布目象嵌',
    '朧銀',
    '朧銀象嵌',
    '毛彫タガネ',
    '鋸目',
    '鎖模様',
    '亀甲模様',
    '布目',
    '刀匠',
    '刀鍛冶',
    '鍛刀',
    '玉鋼',
    '砂鉄',
    '鉄砂',
    'たたら製鉄',
    'たたら',
    '村下',
    '高殿',
    '炉',
    '焼き入れ',
    '焼き戻し',
    '焼きなまし',
    '焼入れ',
    '鍛圧',
    'プレス',
    '絞り加工',
    '捻り',
    '燕三条',
    '三条鍛冶',
    '高岡銅器',
    '高岡鋳物',
    '南部鉄器',
    '南部鉄瓶',
    '鉄瓶',
    '茶釜',
    '風鈴',
    '梵鐘',
    '釣鐘',
    '半鐘',
    '金口',
    '鳴物',
    '茶鏝',
    '銀瓶',
    '銅鏡',
    '古鏡',
    '柄鏡',
    '手鏡',
    '和鏡',
    '錫',
    '錫器',
    '錫光',
    '錫半',
    '本錫',
    '鉛錫',
    '錫合金',
    '白鑞',
    '合金',
    '真鍮',
    '黄銅',
    '白銅',
    '青銅',
    '銅合金',
    '錫青銅',
    'アルミ青銅',
    '燐青銅',
    '砲金',
    '洋白',
    '洋銀',
    'ドイツ銀',
    '銀合金',
    '金合金',
    '白金',
    'プラチナ',
    'パラジウム',
    '赤銅',
    '四分一',
    '素銅',
    '赤銅地',
    '素銅地',
    '赤金地',
    '山銅',
    '丹銅',
    '色合い',
    '煮色',
    '煮色液',
    '硫化',
    '硫化液',
    '鎌洗い',
    '煤焼き',
    '燻し',
    'いぶし',
    '古美',
    '古美仕上げ',
    '黒染',
    'メッキ',
    '鍍金',
    '金メッキ',
    '銀メッキ',
    '箔押し',
    '金箔',
    '銀箔',
    '砂金',
    '溶接',
    'ロウ付け',
    '硬ロウ',
    '銀ロウ',
    'はんだ',
    'はんだ付け',
    '錺',
    '金具',
    '仏具金具',
    '蔵金具',
    '釘隠し',
    '鍵手',
    '引き手',
    '拉手',
    '仏具',
    '灯籠',
    '鉄灯籠',
    '吊り灯籠',
    '水屋',
    '花立',
    '華瓶',
    '花瓶',
    '香炉台',
    '仏器',
    '茶の湯釜',
    '炉釜',
    '風炉釜',
    '茶道具釜',
    '金工芸',
    '金属工芸',
    '鋳造工房',
    '鍛冶工房',
    '金工房',
    '鍛造所',
    '鋳造所',
    '鍛錬場',
    '製鉄',
    '鉄工',
    '鉄工所',
    '鈴木盛久',
    '宮崎寒雉',
    '香取秀真',
    '金工作家',
    '彫金家',
    '鋳造家',
    '鍛冶検定',
    '鋳造検定',
    '鍛冶体験',
    '鍛冶教室'
  ];
  const negate = [
    'still awaiting the smith license',
    'still awaiting the metalwork cert',
    'まだ鍛造前',
    'まだ鋳込み前',
    'これから鍛え',
    'まだ仕上げ前'
  ];
  const nullPins = ['about to visit the metalworks', 'about to file the forge report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
