// Pass CCLV: EN dispatch-to-destinations + JA dispel/banish/get-out (pass CCLV)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({ speak: () => {}, onCommand: () => {} });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCLV: close-tab coverage', () => {
  test.each([
    "send it to the trash", "send it to the garbage", "send it to the bin", "send it to the skip",
    "send it to the landfill", "send it to the scrapyard", "send it to the scrapheap", "send it to the junk heap",
    "send it to the dustbin", "send it to the wastebasket", "send it to the circular file", "send it to file 13",
    "send it to file thirteen", "send it to the recycler", "send it to the recycling bin", "send it to the incinerator",
    "send it to the furnace", "send it to the fire", "send it to the void", "send it to the ether",
    "send it to oblivion", "send it to the nether", "send it to the nether realm", "send it to the phantom zone",
    "send it to the twilight zone", "send it to another dimension", "send it to another universe", "send it to another world",
    "send it to outer space", "send it to deep space", "send it to a black hole", "send it to the void beyond",
    "send it to the great beyond", "send it to the hereafter", "send it to the afterlife", "send it to the next world",
    "send it to the other side", "send it to the dark side", "send it to the far side", "send it to the back of beyond",
    "send it to the middle of nowhere", "send it to nowhere", "send it to exile", "send it to the outer dark",
    "send it to the outer rim", "send it to the edge of the earth", "send it to the edge of the world", "send it to the end of the earth",
    "send it to the end of the world", "send it to the ends of the earth", "send it to davy jones locker", "send it to the bottom of the sea",
    "send it to the bottom of the ocean", "send it to the bottom of the lake", "send it to the bottom of the river", "send it to the mariana trench",
    "send it to the trenches", "send it to the deep", "send it to the bottom", "send it to the grave",
    "send it to the cemetery", "send it to the boneyard", "send it to the graveyard", "send it to the crypt",
    "send it to the tomb", "send it to the mausoleum", "send it to the catacombs", "send it to the dungeon",
    "send it to the oubliette", "send it to the hole", "send it to the well", "send it to the mine",
    "send it to the mineshaft", "send it to the quarry", "send it to the moat", "send it to the moat monster",
    "send it to the dogs", "send it to the wolves", "send it to the sharks", "send it to the fishes",
    "send it to the piranhas", "send it to the lions", "send it to the tigers", "send it to the bears",
    "send it to the crocodiles", "send it to the alligators", "send it to the beasts", "send it to the wild",
    "send it to the forest", "send it to the woods", "send it to the desert", "send it to the dunes",
    "send it to the tundra", "send it to the arctic", "send it to the antarctic", "send it to the north pole",
    "send it to the south pole", "send it to the ice", "send it to the glacier", "send it to the snow",
    "send it to the storm", "send it to the tempest", "send it to the hurricane", "send it to the tsunami",
    "send it to the flood", "send it to the deluge", "send it to the waves", "send it to the surf",
    "send it to the sea", "send it to the ocean", "send it to the lake", "send it to the river",
    "send it to the stream", "send it to the creek", "send it to the brook", "send it to the pond",
    "send it to the pool", "send it to the swamp", "send it to the bog", "send it to the marsh",
    "send it to the quagmire", "send it to the mire", "send it to the muck", "send it to the mud",
    "send it to the sludge", "send it to the slime", "send it to the ooze", "send it to the tar pits",
    "send it to the tar", "send it to the quicksand", "send it to the volcano", "send it to the lava",
    "send it to the magma", "send it to the inferno", "send it to the blaze", "send it to the bonfire",
    "send it to the pyre", "send it to the stake", "send it to the gallows", "send it to the gibbet",
    "send it to the scaffold", "send it to the guillotine", "send it to the electric chair", "send it to the gas chamber",
    "send it to the rack", "send it to the iron maiden", "send it to the pillory", "send it to the stocks",
    "send it to the dungeon", "send it to the oubliette", "send the tab to the trash", "send the tab to the garbage",
    "send the tab to the bin", "send the tab to the dump", "send the tab to the landfill", "send the tab to the scrapyard",
    "send the tab to the scrapheap", "send the tab to the junkyard", "send the tab to the dustbin", "send the tab to the void",
    "send the tab to the abyss", "send the tab to oblivion", "send the tab to hell", "send the tab to the underworld",
    "send the tab to the shadow realm", "send the tab to the phantom zone", "send the tab to outer space", "send the tab to the sun",
    "send the tab to exile", "send the tab to the cemetery", "send the tab to the graveyard", "send the tab to the dungeon",
    "send the tab to the oubliette", "send the tab to the wolves", "send the tab to the sharks", "send the tab to the lions",
    "send the tab to the dogs", "send the tab to the wild", "send the tab to the wilderness", "send the tab to the sea",
    "send the tab to the ocean", "send the tab to the swamp", "send the tab to the quicksand", "send the tab to the volcano",
    "send the tab to the lava", "send the tab to the gallows", "send the tab to the guillotine", "dispatch it to the trash",
    "dispatch it to the bin", "dispatch it to the void", "dispatch it to oblivion", "dispatch it to hell",
    "dispatch it to the scrapheap", "dispatch it to the junkyard", "dispatch it to the sun", "dispatch it to exile",
    "ship it to the trash", "ship it to the bin", "ship it to the dump", "ship it to the void",
    "ship it to hell", "ship it to the scrapheap", "ship it to the junkyard", "ship it to the sun",
    "ship it to exile", "ship it to the cemetery", "ship it to the graveyard", "ship it off to the trash",
    "ship it off to the bin", "ship it off to the dump", "ship it off to the void", "ship it off to hell",
    "ship it off to the scrapheap", "ship it off to the junkyard", "ship it off to the sun", "ship it off to exile",
    "ship it off to the cemetery", "ship it off to the graveyard", "ship it off to siberia", "ship it off to the farm",
    "ship it off to a farm upstate", "ship it off to the glue factory", "ship it off to the knackers", "ship it off to the knackers yard",
    "ship it off to the pet food factory", "post it to the trash", "post it to the void", "post it to oblivion",
    "post it to hell", "post it to the scrapheap", "mail it to the trash", "mail it to the void",
    "mail it to oblivion", "mail it to hell", "mail it to the scrapheap", "mail it to the dead letter office",
    "mail it to nowhere", "forward it to the trash", "forward it to the void", "forward it to oblivion",
    "forward it to hell", "forward it to the scrapheap", "forward it to the dead letter office", "route it to the trash",
    "route it to the void", "route it to oblivion", "route it to hell", "route it to the scrapheap",
    "route it to dev null", "route it to devnull", "route it to null", "route it to the null",
    "route it to the bit bucket", "route it to the bit-bucket", "route it to the bit-bucket in the sky", "deliver it to the trash",
    "deliver it to the void", "deliver it to oblivion", "deliver it to hell", "deliver it to the scrapheap",
    "deliver it to the executioner", "deliver it to the hangman", "deliver it to the headsman", "deliver it to the chopping block",
    "deliver it to the block", "deliver it to the axe", "deliver it to the ax", "deliver it to the headsman",
    "deliver it to death row", "deliver it to the chair", "consign it to the trash", "consign it to hell",
    "consign it to the junkyard", "consign it to perdition", "consign it to limbo", "consign it to purgatory",
    "consign it to the abyss", "consign it to the ether", "consign it to the shadows", "consign it to darkness",
    "consign it to the dark", "consign it to nothingness", "consign it to the grave", "consign it to the cemetery",
    "consign it to the tomb", "consign it to the dungeon", "consign it to the oubliette", "consign it to the pit",
    "consign it to the oubliette", "consign it to hell", "consign it to hades", "consign it to the underworld",
    "commit it to the trash", "commit it to the void", "commit it to oblivion", "commit it to hell",
    "commit it to the scrapheap", "commit it to the bin", "commit it to the dustbin", "commit it to perdition",
    "commit it to limbo", "commit it to the abyss", "commit it to the ether", "commit it to the grave",
    "commit it to the cemetery", "commit it to the tomb", "commit it to the pit", "condemn it to the trash",
    "condemn it to the fire", "condemn it to the scrapheap", "condemn it to perdition", "condemn it to limbo",
    "condemn it to purgatory", "condemn it to the abyss", "condemn it to the dark", "condemn it to eternal night",
    "condemn it to death", "condemn it to destruction", "condemn it to ruin", "condemn it to the grave",
    "condemn it to the tomb", "condemn it to execution", "condemn it to death row", "sentence it to hell",
    "sentence it to the fire", "sentence it to perdition", "sentence it to limbo", "sentence it to purgatory",
    "sentence it to the abyss", "sentence it to destruction", "sentence it to execution", "sentence it to death row",
    "banish it to the ether", "banish it to the phantom zone", "banish it to the nether realm", "banish it to exile",
    "banish it to the outer dark", "banish it to the wastes", "banish it to the desert", "banish it to the tundra",
    "banish it to the arctic", "banish it to the north pole", "banish it to the far side", "banish it to nowhere",
    "banish it to the middle of nowhere", "banish it to the back of beyond", "banish it to the edge of the earth", "banish it to the ends of the earth",
    "banish it to another dimension", "banish it to another universe", "banish it to another world", "banish it to the next world",
    "banish it to the other side", "banish it to the great beyond", "banish it to the hereafter", "banish it to the afterlife",
    "cast it into the flames", "cast it into the lava", "cast it into the volcano", "cast it into the furnace",
    "cast it into the incinerator", "cast it into the ocean", "cast it into the lake", "cast it into the river",
    "cast it into the deep", "cast it into the depths", "cast it into the chasm", "cast it into the gorge",
    "cast it into the ravine", "cast it into the canyon", "cast it into the crevasse", "cast it into the crevice",
    "cast it into the crack", "cast it into the fissure", "cast it into the rift", "cast it into the hole",
    "cast it into the well", "cast it into the oubliette", "cast it into the dungeon", "cast it into the moat",
    "cast it into the swamp", "cast it into the bog", "cast it into the marsh", "cast it into the quagmire",
    "cast it into the mire", "cast it into the quicksand", "cast it into the tar pits", "cast it into the tar",
    "cast it into the sludge", "cast it into the muck", "cast it into the mud", "throw it into the trash",
    "throw it into the bin", "throw it into the garbage", "throw it into the skip", "throw it into the dump",
    "throw it into the void", "throw it into the abyss", "throw it into the pit", "throw it into the flames",
    "throw it into the fire", "throw it into the inferno", "throw it into the lava", "throw it into the volcano",
    "throw it into the furnace", "throw it into the incinerator", "throw it into the ocean", "throw it into the lake",
    "throw it into the river", "throw it into the deep", "throw it into the depths", "throw it into the chasm",
    "throw it into the gorge", "throw it into the ravine", "throw it into the canyon", "throw it into the crevasse",
    "throw it into the hole", "throw it into the well", "throw it into the oubliette", "throw it into the dungeon",
    "throw it into the moat", "throw it into the swamp", "throw it into the bog", "throw it into the quagmire",
    "throw it into the quicksand", "throw it into the tar pits", "throw it into the muck", "throw it into the mud",
    "throw it into the lions den", "throw it into the lions den", "throw it into the wolf pack", "throw it into the shark tank",
    "throw it into the tank", "throw it into the tank of piranhas", "throw it into the pit of snakes", "throw it into the snake pit",
    "throw it into the vipers nest", "toss it into the trash", "toss it into the bin", "toss it into the garbage",
    "toss it into the skip", "toss it into the void", "toss it into the abyss", "toss it into the pit",
    "toss it into the flames", "toss it into the fire", "toss it into the lava", "toss it into the furnace",
    "toss it into the incinerator", "toss it into the ocean", "toss it into the lake", "toss it into the river",
    "toss it into the chasm", "toss it into the gorge", "toss it into the hole", "toss it into the well",
    "toss it into the dungeon", "toss it into the swamp", "toss it into the quicksand", "toss it into the muck",
    "toss it into the mud", "toss it into the lions den", "toss it into the shark tank", "drop it into the void",
    "drop it into the abyss", "drop it into the pit", "drop it into the sea", "drop it into the ocean",
    "drop it into the lake", "drop it into the river", "drop it into the chasm", "drop it into the gorge",
    "drop it into the hole", "drop it into the well", "drop it into the swamp", "drop it into the quicksand",
    "drop it into the muck", "drop it into the lava", "drop it into the volcano", "drop it into the furnace",
    "drop it into the incinerator", "drop it into the grinder", "drop it into the shredder", "drop it into the compactor",
    "drop it into the crusher", "drop it into the baler", "plunge it into the void", "plunge it into the pit",
    "plunge it into the flames", "plunge it into the fire", "plunge it into the inferno", "plunge it into the lava",
    "plunge it into the sea", "plunge it into the ocean", "plunge it into the lake", "plunge it into the river",
    "plunge it into the chasm", "plunge it into the gorge", "plunge it into the tar pits", "plunge it into the darkness",
    "plunge it into the dark", "plunge it into eternal darkness", "plunge it into eternal night", "plunge it into shadow",
    "plunge it into shadows", "plunge it into nothingness", "yeet it into the void", "yeet it into the abyss",
    "yeet it into the pit", "yeet it into outer space", "yeet it into a black hole", "yeet it into the lava",
    "yeet it into the volcano", "yeet it into the sea", "yeet it into the ocean", "yeet it into the lake",
    "yeet it into the river", "yeet it into the swamp", "yeet it into the chasm", "yeet it into the gorge",
    "yeet it into the fire", "yeet it into the flames", "yeet it into the furnace", "yeet it into the incinerator",
    "hurl it into the abyss", "hurl it into the pit", "hurl it into space", "hurl it into the lava",
    "hurl it into the volcano", "hurl it into the sea", "hurl it into the ocean", "hurl it into the chasm",
    "hurl it into the gorge", "hurl it into the fire", "hurl it into the flames", "hurl it into the furnace",
    "fling it into the abyss", "fling it into the pit", "fling it into the sun", "fling it into space",
    "fling it into the sea", "fling it into the ocean", "fling it into the chasm", "fling it into the fire",
    "fling it into the flames", "chuck it into the trash", "chuck it into the bin", "chuck it into the garbage",
    "chuck it into the void", "chuck it into the abyss", "chuck it into the pit", "chuck it into the sea",
    "chuck it into the ocean", "chuck it into the lake", "chuck it into the river", "chuck it into the chasm",
    "chuck it into the fire", "chuck it into the flames", "heave it into the trash", "heave it into the bin",
    "heave it into the garbage", "heave it into the void", "heave it into the abyss", "heave it into the pit",
    "heave it into the sea", "heave it into the ocean", "heave it into the chasm", "heave it into the fire",
    "lob it into the trash", "lob it into the bin", "lob it into the void", "lob it into the pit",
    "lob it into the sea", "lob it into the ocean", "lob it into the fire", "sling it into the trash",
    "sling it into the bin", "sling it into the void", "sling it into the pit", "sling it into the sea",
    "sling it into the ocean", "sling it into the fire", "払拭して", "払拭しちまえ",
    "払拭しちゃえ", "払拭してしまえ", "払拭しとけ", "払拭しなよ",
    "払拭したまえ", "払拭しやがれ", "払拭しろや", "払拭すべきだ",
    "払拭するんだ", "払拭するつもりだ", "払拭するわ", "払拭するぞ",
    "払拭するぜ", "払拭するからな", "払拭することにした", "払拭せよと言ってんだ",
    "払拭せよと言うんだ", "払拭せよというんだ", "払拭せよということだ", "払拭せよという判断だ",
    "払拭せよという決定だ", "払拭せよという命令だ", "払拭せよというお達しだ", "払拭せよという次第だ",
    "払拭せよという旨だ", "払拭せよという意向だ", "払拭せよという意志だ", "払拭せよという意思だ",
    "払拭せよという腹だ", "払拭せよという心だ", "払拭せよという運びだ", "払拭せよという段取りだ",
    "払拭せよという流れだ", "払拭せよという件だ", "払拭せよという話だ", "払拭せよということだよ",
    "払拭せよという模様だ", "払拭せよという見解だ", "払拭せよという所存だ", "払拭せよという方針だ",
    "払拭せよという結論だ", "払拭せよという判決だ", "払拭せよという裁定だ", "払拭せよという議決だ",
    "払拭せよという採決だ", "払拭せよという可決だ", "払拭せよという布告だ", "払拭せよという宣言だ",
    "払拭せよという沙汰だ", "払拭せよという由だ", "追いやれ", "追いやって",
    "追いやるんだ", "追いやりだ", "追いやれよ", "追いやるべきだ",
    "追いやるつもりだ", "追いやるわ", "追いやるぞ", "追いやるぜ",
    "追いやるからな", "隅に追いやれ", "隅に追いやって", "隅に追いやるんだ",
    "隅に追いやれよ", "隅に追いやるべきだ", "隅っこに追いやれ", "隅っこに追いやって",
    "隅っこに追いやるんだ", "隅っこに追いやれよ", "端に追いやれ", "端に追いやって",
    "端に追いやるんだ", "端っこに追いやれ", "端っこに追いやって", "端っこに追いやるんだ",
    "奥に追いやれ", "奥に追いやって", "奥に追いやるんだ", "奥底に追いやれ",
    "奥底に追いやって", "奥底に追いやるんだ", "底に追いやれ", "底に追いやって",
    "底に追いやるんだ", "どこかに追いやれ", "どこかに追いやって", "どこかに追いやるんだ",
    "どっかに追いやれ", "どっかに追いやって", "どっかに追いやるんだ", "どこか遠くに追いやれ",
    "どこか遠くに追いやって", "遠くに追いやれ", "遠くに追いやって", "遠くに追いやるんだ",
    "地の果てに追いやれ", "地の果てに追いやって", "地の果てに追いやるんだ", "地の果てにやれ",
    "地の果てにやって", "地の果てに連れて行け", "果てに追いやれ", "果てに追いやって",
    "果てにやれ", "果てにやって", "島に追いやれ", "島に追いやって",
    "島に追いやるんだ", "孤島に追いやって", "孤島に追いやるんだ", "無人島に追いやって",
    "無人島に追いやるんだ", "海の向こうに追いやれ", "海の向こうに追いやって", "海の向こうにやれ",
    "海の向こうにやって", "向こうに追いやれ", "向こうに追いやって", "向こうにやれ",
    "向こうにやって", "あの世に追いやれ", "あの世に追いやって", "あの世にやれ",
    "あの世にやって", "冥府に追いやれ", "冥府に追いやって", "冥府にやれ",
    "冥府にやって", "黄泉に追いやれ", "黄泉に追いやって", "黄泉にやれ",
    "黄泉にやって", "地獄に追いやれ", "地獄に追いやって", "地獄にやれ",
    "地獄にやって", "奈落に追いやれ", "奈落に追いやって", "奈落にやれ",
    "奈落にやって", "闇に追いやれ", "闇に追いやって", "闇にやれ",
    "闇にやって", "暗闇に追いやれ", "暗闇に追いやって", "暗闇にやれ",
    "暗闇にやって", "虚空に追いやれ", "虚空に追いやって", "虚空にやれ",
    "虚空にやって", "宇宙に追いやって", "宇宙にやれ", "宇宙にやって",
    "空に追いやれ", "空に追いやって", "空にやれ", "空にやって",
    "月に追いやれ", "月に追いやって", "月にやれ", "月にやって",
    "火星に追いやれ", "火星に追いやって", "火星にやれ", "火星にやって",
    "異次元に追いやれ", "異次元に追いやって", "異次元にやれ", "異次元にやって",
    "異世界に追いやれ", "異世界に追いやって", "異世界にやれ", "異世界にやって",
    "平行世界に追いやれ", "平行世界に追いやって", "平行世界にやれ", "平行世界にやって",
    "別世界に追いやれ", "別世界に追いやって", "別世界にやれ", "別世界にやって",
    "来世に追いやれ", "来世に追いやって", "来世にやれ", "来世にやって",
    "彼岸に追いやれ", "彼岸に追いやって", "彼岸にやれ", "彼岸にやって",
    "此岸から彼岸に追いやれ", "こちら側からあちら側に追いやれ", "画面外に追いやれ", "画面外に追いやって",
    "画面外にやれ", "画面外にやって", "視界外に追いやれ", "視界外に追いやって",
    "視界外にやれ", "視界外にやって", "視界から追い出せ", "視界から追い出して",
    "視界から追い出すんだ", "視界から外れろ", "視界から消え去れ", "目の前から追い出せ",
    "目の前から追い出して", "目の前から立ち去れ", "俺の前から追い出せ", "俺の前から失せろ",
    "俺の前から立ち去れ", "俺の視界から消えろ", "俺の視界から消えて", "俺の視界から外れろ",
    "俺の目の前から消えて", "俺の目の前から失せろ", "俺の目の前から立ち去れ", "俺の見えるところから消えろ",
    "俺の見えるところから外れろ", "俺の世界から消えろ", "俺の世界から消えて", "俺の世界から失せろ",
    "俺の世界から出て行け", "俺の世界から出て行って", "俺の人生から消えろ", "俺の人生から消えて",
    "俺の人生から失せろ", "俺の人生から出て行け", "俺の人生から出て行って", "俺の記憶から消えろ",
    "俺の記憶から消えて", "俺の記憶から失せろ", "俺の頭から消えろ", "俺の頭から消えて",
    "俺の頭から失せろ", "俺の頭から出て行け", "俺の目から消えろ", "俺の目から消えて",
    "俺の目から失せろ", "俺の目の前をどけ", "俺の前をどけ", "俺の前からどけ",
    "俺の前をどいて", "俺の前からどいて", "俺の視界をどけ", "俺の視界をどいて",
    "俺の道をどけ", "俺の道をどいて", "どけどけどけ", "どけや",
    "どけと言ってんだ", "どけと言っているんだ", "どけと言っているんだよ", "どけと言っているんだって",
    "どけと言っているのだ", "どけと言っているのだよ", "どけと言っているわ", "どけと言っているぞ",
    "どけと言っているぜ", "どけと言っているからな", "どけというんだ", "どけというのだ",
    "どけということだ", "どけということだよ", "どけという件だ", "どけという判断だ",
    "どけという決定だ", "どけという命令だ", "どけというお達しだ", "どけという次第だ",
    "どけという旨だ", "どけという意向だ", "どけという意志だ", "どけという意思だ",
    "どけという腹だ", "どけという心だ", "どけという運びだ", "どけという段取りだ",
    "どけという流れだ", "どけという模様だ", "どけという話だ", "どけという見解だ",
    "どけという所存だ", "どけという方針だ", "どけという結論だ", "どけという判決だ",
    "どけという裁定だ", "どけという議決だ", "どけという採決だ", "どけという可決だ",
    "どけという布告だ", "どけという宣言だ", "どけという沙汰だ", "どけという由だ",
    "退がるからな", "下がるからな", "下げ", "下げて",
    "下げるんだ", "下げろ", "下げろよ", "下げるべきだ",
    "引っ込めろ", "引っ込めろよ", "引っ込んでろ", "引っ込めとけ",
    "引っ込めといて", "引っ込めちまえ", "引っ込めちゃえ", "引っ込めたまえ",
    "引っ込めやがれ", "引っ込めや", "引っ込めと言ってんだ", "引っ込めと言っているんだ",
    "引っ込むからな", "引っ込もうと思うよ", "引っ込もうと思うんだ", "引っ込めーい",
    "引っ込めー", "引っ込めえ", "引っ込みやがれって", "引っ込みろよ",
    "引っ込めよな", "引っ込めよって", "引っ込めよってば", "引っ込めよと言ってんだ",
    "引っ込めよと言っているんだ", "引っ込みなんだ", "引っ込みなんだよ", "引っ込みなんだって",
    "引っ込みなのだ", "引っ込みなのだよ",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});
