// pass DCCXXXVIII: lacquerware & urushi-craft domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXXXVIII: lacquerware & urushi domain (tessen)', () => {
  const closeTab = ['lacquerware licensed', 'lacquerer certified', 'urushi master registered'];
  const closeTabJa = [
    '漆器',
    '漆芸',
    '漆工',
    '漆工芸',
    '漆芸家',
    '漆器作家',
    '塗師',
    '塗り師',
    '蒔絵師',
    '沈金師',
    '彫漆師',
    '螺鈿師',
    '漆掻き',
    '漆原',
    '漆工房',
    '漆器店',
    'うるし',
    '生漆',
    '黒漆',
    '朱漆',
    '透漆',
    '白漆',
    '青漆',
    '精製漆',
    '木地',
    '木地師',
    '木地挽き',
    '榃地',
    '刳り貫き',
    '挽き物',
    '指物',
    '曲物',
    '厚物',
    '板物',
    '寸胴',
    '木竹合',
    '乾漆',
    '一閑張り',
    '紙胎',
    '陶胎',
    '皮胎',
    '乾漆像',
    '布着せ',
    '下地',
    '錆付け',
    '錆漆',
    '刻苧',
    '中塗',
    '上塗',
    '拭き漆',
    '拭漆',
    '木蝿',
    '蝋色',
    '呂色仕上げ',
    '摺り漆',
    '溜塗',
    '曙塗',
    '黒溜',
    '蒔絵',
    '平蒔絵',
    '研出蒔絵',
    '高蒔絵',
    '肉合蒔絵',
    '卵殻',
    '青貝',
    '夜光貝',
    '螺鈿',
    '薄貝',
    '板目貝',
    '暈し',
    '色粉',
    '蒔絵粉',
    '消粉',
    '平粉',
    '梨子地',
    '梨子地粉',
    '金地',
    '銀地',
    '金丸粉',
    '銀丸粉',
    '炭粉',
    '炭粉蒔き',
    '錆絵',
    '平文',
    '平脱',
    '截金',
    '切金',
    '沈金',
    '刀彫',
    '彫刻刀',
    '点彫',
    '細沈金',
    '毛彫沈金',
    '掻き合わせ',
    '箔置',
    '切箔',
    '蒔粉',
    '幣蒔',
    '刷毛目',
    '粉蒔き',
    '堆朱',
    '剔紅',
    '堆黒',
    '屈輪彫',
    '彫漆',
    '鎌倉彫',
    '日光彫',
    '張元彫',
    '塩彫',
    '変塗',
    '変り塗',
    '石目塗',
    '斑紋塗',
    '縮緬塗',
    '木目塗',
    '目はじき塗',
    '研出し変塗',
    '彩漆',
    '七色塗',
    '虹塗',
    '銀溜塗',
    'ぼかし塗り',
    '錆上げ',
    '磨き',
    '艶出し',
    '研磨',
    '研ぎ出し',
    '木炭研ぎ',
    '摺り上げ',
    '輪島塗',
    '会津塗',
    '津軽塗',
    '越前漆器',
    '山中漆器',
    '木曽漆器',
    '紀州漆器',
    '琉球漆器',
    '金沢漆器',
    '高岡漆器',
    '若狭塗',
    '江戸漆器',
    '唐塗',
    '堆朱塗',
    '鎗金',
    '斎戒彫',
    '花塗',
    '虫喰塗',
    '色絵漆器',
    '棗',
    '薄器',
    '香道具',
    '香箸',
    '灰押さえ',
    '茶托',
    '菓子器',
    '菓子鉢',
    '重箱',
    '膳',
    '盆',
    'お盆',
    '角盆',
    '丸盆',
    '茶盤',
    '屠蘇器',
    '屠蘇台',
    '椀',
    '汁椀',
    '雑煮椀',
    '飯椀',
    '吸物椀',
    '煮物椀',
    '平椀',
    '蓋付椀',
    '大椀',
    '箸',
    '塗箸',
    '箸置き',
    '匙',
    '塗り物',
    '切手盆',
    '文箱',
    '手箱',
    '文庫',
    '硯箱',
    '料紙箱',
    '香箱',
    '鏡台',
    '鏡台匣',
    '三島手',
    '葉形手箱',
    '蒔絵硯箱',
    '紫檀箱',
    '輪島塗師',
    '漆器卸',
    '蒔絵工房',
    '塗り屋',
    '中身蒔絵',
    '卵殻蒔絵'
  ];
  const negate = [
    'still awaiting the lacquer license',
    'still awaiting the urushi cert',
    'まだ蒔絵前',
    'まだ上塗り前',
    'これから塗り',
    'まだ塗装前'
  ];
  const nullPins = ['about to visit the lacquer studio', 'about to file the varnish report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
