// Pass CCXLII: game/card + disposal idioms + JA dismissal/seal (pass CCXLII)
import { VoiceCommands } from '../src/vr/input/VoiceCommands.js';

function mk() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const t3 = { id: 3, url: 'https://c.example', title: 'Tab C', loading: false };
  const tabManager = {
    tabs: [t1, t2, t3], activeTab: t2, activeTabId: 2,
    getActiveTab() { return this.activeTab; },
    getTab(id) { return this.tabs.find(t => t.id === id); },
  };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {},
  });
  vc.connectBrowser(tabManager);
  return vc;
}
function key(vc, p) {
  vc.processCommand(p, 0.9);
  return vc.lastCommand ? vc.lastCommand.key : null;
}

describe('pass CCXLII: close-tab literal coverage', () => {
  test.each([
    "fold", "fold em", "i fold", "resign it",
    "resign the tab", "i resign", "tip the king", "unravel it",
    "unravel the tab", "cut the thread", "snip the thread", "clip the thread",
    "sever the thread", "cut the cord", "cut the cord on it", "trim it off",
    "file under t", "file it under t", "file under trash", "marked for deletion",
    "mark it for deletion", "mark the tab for deletion", "flag it for deletion", "flag for deletion",
    "deletion mark", "recycle bin it", "drag it to the trash", "drag it to trash",
    "move it to trash", "move it to the trash", "send it to the recycle bin", "return to sender",
    "return it to sender", "send it back", "send it back to sender", "stamp return to sender",
    "mark return to sender", "refuse it", "refuse the tab", "refuse delivery",
    "not at this address", "rts it", "send it to its room", "send it to bed without supper",
    "ground it", "ground the tab", "timeout for it", "time out for it",
    "put it in timeout", "put it in time out", "naughty step for it", "naughty step",
    "corner it", "corner the tab", "send it to the corner", "detention for it",
    "send it to detention", "give it detention", "detention", "kick it out of school",
    "expulsion", "expulsion for it", "suspension", "sack it",
    "downsize it", "downsize the tab",
    "lay it off", "lay the tab off", "man overboard", "throw it overboard",
    "cast it adrift", "send it to the glue factory", "glue factory", "take it to the glue factory",
    "lay it down", "lay the tab down", "send it to hell", "damn it to hell",
    "condemn it to hell", "condemn the tab", "damned it", "damnation for it",
    "eternal damnation", "eternal damnation for it", "cast it into the fire", "cast it into the pit",
    "into the pit", "into the fire", "into the flames", "flames for it",
    "immolate it", "spontaneous combustion", "combust it", "ignite it",
    "ignite the tab", "set it alight", "set it ablaze", "set the tab on fire",
    "light it on fire", "kindle it", "kindle the tab", "inferno it",
    "incinerate the tab", "sear it", "sear the tab", "singe it",
    "singe the tab", "roast the tab", "roast it alive", "roast it over a fire",
    "over an open flame", "immolation for it", "melt the tab down", "liquefy the tab",
    "dissolve it in acid", "acid bath", "acid bath for it", "dip it in acid",
    "dissolve the tab", "sublime it", "vaporize the tab", "gasify it",
    "dematerialize it", "dematerialize the tab", "unexist the tab", "blink it away",
    "blink it out", "blink it out of existence", "snap it away", "snap it out of existence",
    "thanos snap it", "thanos it", "infinity snap", "snap it like thanos",
    "dust it", "dust the tab", "turn it to dust", "ash it away",
    "rubble it", "rubble the tab", "debris it", "smithereens",
    "blow it to smithereens", "blow it to kingdom come", "kingdom come", "send it to kingdom come",
    "smithereens it", "blow it to bits", "bits and pieces", "blow it to pieces",
    "pieces for it", "take it apart", "take it apart piece by piece", "tear it apart",
    "tear it to pieces", "rip it to shreds", "rip it to pieces", "tear it to shreds",
    "shred it to pieces", "rend it", "rend the tab", "rend it apart",
    "rend it asunder", "tear it asunder", "sunder it", "sunder the tab",
    "asunder", "hew it", "hew it down", "hew the tab",
    "fell it", "fell the tab", "fell it like a tree", "timber",
    "timber for it", "yell timber", "it goes timber", "chop the tab down",
    "saw it off", "saw the tab off", "saw it down", "chainsaw it",
    "chainsaw the tab", "weed whacker", "weed whack it", "lopping shears",
    "lop it off", "lop the tab off", "gut the tab",
    "fillet it open", "flay the tab", "debone it", "debone the tab",
    "pith it", "pithed it", "nitrogen it", "liquid nitrogen",
    "freeze it solid", "deep freeze it", "cryo it", "cryo the tab",
    "flash freeze it", "ice it solid", "freeze it to death", "six feet of dirt",
    "six foot deep", "under the dirt", "under the sod", "daisies for it",
    "rooting for the daisies", "fertilizer", "fertilizer for it", "worm food for it",
    "worm feast", "maggot food", "maggots for it", "carrion",
    "carrion for it", "crow food", "vulture food", "bait for it",
    "chum for the sharks", "shark chum", "shark food", "fish food",
    "fish food for it", "feed it to the fish", "fishy food", "swim with cement shoes",
    "swim with the fishes", "fishes for it", "davy jones", "locker for it",
    "briny deep", "the briny deep", "briny deep for it", "ocean floor",
    "ocean floor for it", "bottom of the sea", "bottom of the sea for it", "bottom of the ocean",
    "sea floor", "sea bed", "down to the depths", "depths for it",
    "into the deep", "into the abyss", "abyss for it", "the abyss",
    "void for it", "into the void", "the void", "void it out",
    "null space", "null space for it", "the void consumes it", "expel it to the void",
    "consign it to the void", "banish it to the void", "exile it to the void", "excommunicate it",
    "excommunicate the tab", "deconsecrate it", "unholy it", "put a hex on it",
    "jinx it", "jinx the tab", "evil eye it", "voodoo it",
    "voodoo the tab", "pox on it", "a pox on it", "plague on it",
    "pestilence for it", "locusts on it", "bring down the thunder", "thunderbolt it",
    "lightning bolt it", "zeus it", "bolt it down", "juice it",
    "juice it up", "amp it", "amp it up", "volt it",
    "megawatt it", "fry its circuits", "fry the circuits", "short circuit it",
    "short it out", "short it", "trip the breaker", "trip its breaker",
    "breaker for it", "blow a fuse", "blow its fuse", "fuse it out",
    "overload it", "overload the tab", "overclock it", "overclock it to death",
    "brick it", "brick the tab", "brick its firmware", "bricked it",
    "flash it wrong", "corrupt it", "corrupt the tab", "corrupt its data",
    "scramble its data", "wipe its memory", "wipe its ram", "format it",
    "format the tab", "format c it", "format c", "fdisk it",
    "fdisk the tab", "dd it", "dd the tab", "zero fill it",
    "zero it out", "zero out the tab", "shred its data", "bleach bit it",
    "bleachbit it", "secure erase it", "secure delete it", "overwrite it",
    "overwrite the tab", "gutmann it", "nuke from orbit", "nuke it from orbit",
    "its the only way to be sure", "only way to be sure", "ordnance it", "artillery it",
    "shell it", "shell the tab", "bombard it", "bombard the tab",
    "bomb it", "bomb the tab", "carpet bomb it", "daisy cutter",
    "moab it", "drop the moab", "bunker buster", "bunker buster it",
    "drone it", "drone strike", "drone strike it", "predator it",
    "reaper it", "hellfire it", "tomahawk it", "cruise missile it",
    "missile it", "rocket it", "rocket the tab", "bazooka it",
    "rpg it", "grenade it", "frag it", "frag the tab",
    "satchel charge", "c4 it", "c4 the tab", "tnt it",
    "dynamite it", "dynamite the tab", "plastique it", "semtex it",
    "blow it sky high", "blow it up", "blow up the tab", "detonate the charge",
    "set it off", "set off the charge", "light the fuse", "fuse lit",
    "kablooie", "kablooey", "bada bing", "bada boom",
    "bada bing bada boom", "kapow it", "bam it", "wham it",
    "pow it", "kaboom it", "eat it", "eat the tab",
    "consume it", "consume the tab", "devour it", "devour the tab",
    "gulp it down", "gulp it", "swallow it", "swallow the tab",
    "swallow it whole", "wolf it down", "wolf the tab down", "ingest it",
    "digest it", "chomp it", "chomp the tab", "munch it",
    "munch the tab", "munch it up", "nosh it", "scarf it down",
    "scarf the tab down", "scoff it", "gobble it", "gobble it up",
    "gobble the tab", "inhale it", "inhale the tab", "slurp it down",
    "drink it down", "drink the tab down", "drain it", "drain the tab",
    "drain the cup", "drain it dry", "drink it dry", "chug it",
    "chug it down", "swig it", "quaff it", "imbibe it",
    "siphon it off", "sip it dry", "bottoms up it", "down the hatch",
    "down the hatch with it", "total it", "total the tab", "totaled it",
    "totalled it", "write it off as totaled", "send it to the junkyard", "junkyard it",
    "junkyard the tab", "send it to the crusher", "crusher it", "car crusher",
    "crush it into a cube", "cube it", "cube the tab", "compact it",
    "compact the tab", "compress it", "compress the tab", "compress it down",
    "wadded it", "wadded the tab", "ctrl alt delete it", "ctrl-alt-del it",
    "alt f4 it", "alt-f4 it", "alt-f4 the tab", "alt f4 the tab",
    "cmd w", "command w", "ctrl w", "ctrl w it",
    "ctrl-w it", "ctrl-w the tab", "ctrl w the tab", "four finger it",
    "three finger salute", "ctrl shift escape", "task manager it", "kill it in task manager",
    "terminate with extreme prejudice", "暇をやれ", "暇を出せ", "暇を言い渡す",
    "暇を言い渡した", "暇を言い渡したので", "暇を宣告する", "暇を宣告だ",
    "暇を申し渡す", "暇を申し渡した", "暇をやる", "暇を遣う",
    "暇を与える", "暇を与えろ", "解消しろ", "解消だ",
    "解消せよ", "解消すべき", "解散しろ", "解散だ",
    "解散させろ", "解散せよ", "消滅させろ", "消滅だ",
    "消滅させる", "消滅すべき", "消失させろ", "なくなれ",
    "無くなれ", "なくなって", "なくなってくれ", "亡くなれ",
    "死ね", "死んでくれ", "死んでしまえ", "死ねばいい",
    "死ぬべき", "死んだほうがいい", "くたばれ", "くたばって",
    "くたばりやがれ", "あの世へ行け", "あの世に行け", "逝け",
    "逝ってくれ", "往生しろ", "往生せよ", "往生しなさい",
    "あの世に逝け", "冥土に行け", "地獄に落ちろ", "地獄へ落ちろ",
    "地獄に行け", "地獄行きだ", "煉獄に落ちろ", "奈落に落ちろ",
    "奈落の底へ", "奈落行き", "深淵に消えろ", "闇に消えろ",
    "闇に葬れ", "闇に消し去れ", "暗闇に消えろ", "影に消えろ",
    "霧散しろ", "霧散だ", "蒸発しろ", "蒸発だ",
    "蒸発させろ", "昇天しろ", "昇天させろ", "昇天だ",
    "息絶えろ", "息絶やせ", "息を絶て", "息の根を止めろ",
    "息の根を止める", "息の根を止めて", "息を止めろ", "絶命させろ",
    "絶命だ", "安楽死させろ", "安楽死だ", "安楽死させるんだ",
    "破門しろ", "破門だ", "破門にしろ", "除籍しろ",
    "除籍だ", "除籍にしろ", "除名しろ", "除名だ",
    "除名処分だ", "除名処分", "名簿から消せ", "名簿から削れ",
    "帳簿から消せ", "帳消しにしろ", "帳消しだ", "帳消しにする",
    "なかったことにしろ", "なかったことにする", "無かったことにしろ", "水に流せ",
    "水に流して", "忘れ去れ", "忘れ去って", "閉ざせ",
    "閉ざして", "閉ざすんだ", "閉ざすべき", "封じろ",
    "封じて", "封じるんだ", "封印しろ", "封印だ",
    "封印せよ", "封印すべき", "封殺しろ", "封殺だ",
    "塞げ", "塞いで", "塞ぐんだ", "蓋をしろ",
    "蓋を閉めろ", "蓋を閉じろ", "幕を下ろせ", "幕を下ろして",
    "幕をおろせ", "幕を閉じろ", "幕を閉じて", "幕切れだ",
    "幕切れ", "終幕だ", "終幕にしろ", "終幕させろ",
    "閉廷だ", "閉廷せよ", "退廷しろ", "退廷だ",
    "散会だ", "散会にしろ", "散会させろ", "閉会しろ",
    "閉会だ", "閉会せよ", "閉会にしろ", "終演だ",
    "終演にしろ", "打ち切りだ", "打ち切れ", "打ち切って",
    "打ち切るんだ", "打ち切りにしろ", "打ち切りに決まり", "打ち切りすべき",
    "カットしろ", "カットだ", "カットにしろ", "ボツにしろ",
    "ボツだ", "ボツになった", "ボツに決定", "没にしろ",
    "没だ", "お蔵入りだ", "お蔵入りにしろ", "蔵に入れろ",
    "日の目を見せない",
  ])('routes %s to close-tab', (p) => {
    expect(key(mk(), p)).toBe('close-tab');
  });
});

describe('pass CCXLII: close-all-tabs literal coverage', () => {
  test.each([
    "畳んでおくんだ", "畳んじまいな", "畳んじまったほうがいい", "畳みゃあいい",
    "畳みゃいい", "畳めや", "畳まんかい", "畳まへんか",
    "畳まずにはいられない", "畳まねばならん", "畳まなければならん", "畳むしかなかろう",
    "畳むに限ります", "畳むが筋だ", "畳むが順当だ", "畳むが妥当だ",
    "畳むが本懐", "畳むが定石", "畳むがセオリー", "畳むが常識",
    "畳む一択だ", "畳むべきなんじゃないか", "畳むべきなんじゃない", "畳むべきかも",
    "畳むべきだと思うよ", "畳むべきだと思うけど", "畳むべきだと思うんだけど", "畳むべきだと思うんだが",
    "畳むべきだと思うわ", "畳むべきだと考える", "畳むべきだと考えます", "畳むべきだと存じます",
    "畳むべきだと判断する", "畳むべきだと判断します", "畳むべきとの判断だ", "畳むべきとの結論だ",
    "畳むべきとの見解だ", "畳むべきとの見解です", "畳むべきとの答えだ", "畳むべきとの回答だ",
    "畳んだらいいのに", "畳んでおくべきだった", "畳んでおくべきだったな", "畳もうと思ってた",
    "畳もうと思ってたんだ", "畳もうと思っていた", "畳もうとしていた", "畳もうとしてた",
    "畳もうと思った", "畳もうと思ったんだ", "畳もうかと思った", "畳もうかと思ってる",
    "畳もうかと思う", "畳もうかと",
  ])('routes %s to close-all-tabs', (p) => {
    expect(key(mk(), p)).toBe('close-all-tabs');
  });
});
