// pass DCCXXXVII: dyeing, weaving & textile-craft domain -> close-tab
const { VoiceCommands } = require('../src/vr/input/VoiceCommands.js');

function makeVC() {
  const t1 = { id: 1, url: 'https://a.example', title: 'Tab A', loading: false };
  const t2 = { id: 2, url: 'https://b.example', title: 'Tab B', loading: false };
  const vc = new VoiceCommands({
    speak: () => {},
    onCommand: () => {}
  });
  vc.connectBrowser({
    getActiveTab: () => t1,
    closeTab: () => {},
    tabs: () => [t1, t2]
  });
  return vc;
}

const key = (vc, p) => vc._matchCommand(p)?.key ?? null;

describe('pass DCCXXXVII: dyeing & weaving domain (tsuzumi)', () => {
  const closeTab = ['weaver licensed', 'dyer certified', 'loom master registered'];
  const closeTabJa = [
    '織物',
    '織元',
    '機織り',
    '機屋',
    '織匠',
    '織工',
    '手織り',
    '地機',
    '高機',
    '綜絖',
    '筬',
    '杼',
    '経糸',
    '緯糸',
    '整経',
    '巻き取り',
    '管巻き',
    '枠取り',
    '糊付け',
    '糸繰り',
    '撚糸',
    '製糸',
    '紡績',
    '紡ぎ',
    '座繰り',
    '真綿',
    '綿繰り',
    '蚕糸',
    '生糸',
    '絹糸',
    '麻糸',
    '木綿糸',
    '毛糸',
    '金糸',
    '銀糸',
    '箔糸',
    '紅花',
    '藍染',
    '藍建て',
    '天然藍',
    'すくも',
    '蒅',
    '木灰汁',
    '灰汁',
    '媒染',
    '媒染剤',
    'ミョウバン',
    '鉄媒染',
    '草木染',
    '植物染',
    '化学染料',
    '染料',
    '染色',
    '染織',
    '型染',
    '型紙',
    '伊勢型紙',
    '彫刻刀',
    '渋紙',
    '防染糊',
    '糊防染',
    '筒描き',
    '友禅',
    '京友禅',
    '加賀友禅',
    '東京友禅',
    '手描き友禅',
    '型友禅',
    '無線友禅',
    '色挿し',
    '蒸し',
    '水洗い',
    '友禅流し',
    '糊落とし',
    '乾燥',
    '補色',
    '地入れ',
    '色差し',
    'ぼかし染',
    'グラデーション染',
    '段染め',
    '絞り染',
    '絞り',
    '鹿の子絞り',
    '辻が花',
    '疋田絞り',
    '手蜘蛛絞り',
    '板締め絞り',
    '縫い絞り',
    '桶絞り',
    '三浦絞り',
    '有松絞り',
    '鳴海絞り',
    'ロウ染め',
    'ろうけつ染め',
    '蜡染',
    '墨染め',
    '泥染め',
    '泥藍',
    '大島紬',
    '泥大島',
    '結城紬',
    '牛首紬',
    '塩沢紬',
    '紬',
    '真綿紬',
    '絣',
    '久留米絣',
    '備後絣',
    '伊予絣',
    '弓浜絣',
    '村山大島絣',
    '琉球絣',
    'みんさー',
    '芭蕉布',
    '宮古上布',
    '八重山上布',
    '能登上布',
    '小千谷縮',
    '越後上布',
    '麻織物',
    '苧麻',
    '近江麻',
    '更紗',
    '和更紗',
    '捺染',
    'スクリーン捺染',
    'ローラー捺染',
    'インクジェット捺染',
    '転写捺染',
    '抜染',
    '防染',
    '染抜き',
    '染色工場',
    '染物屋',
    '染師',
    '染物師',
    '染色家',
    '染織家',
    '織物検定',
    '着物',
    '和服',
    '呉服',
    '反物',
    '白生地',
    'きもの生地',
    '西陣織',
    '博多織',
    '献上柄',
    '献上博多',
    '独鈷柄',
    '間道',
    '献上柄織',
    '佐賀錦',
    '唐草模様',
    '裂',
    '名物裂',
    '金襴',
    '緞子',
    '錦',
    '綴織',
    '綴れ織り',
    '綴錦',
    'すくい織り',
    '刺繍',
    '相良刺繍',
    '絽',
    '紗',
    '羅',
    '縮緬',
    '羽二重',
    'デシン',
    '銘仙',
    '足利銘仙',
    '伊勢崎銘仙',
    '秩父銘仙',
    '紅型',
    '琉球紅型',
    '型染紅型',
    '読谷山花織',
    '首里花織',
    '道屯織',
    'みんさー織'
  ];
  const negate = [
    'still awaiting the weaver license',
    'still awaiting the dyer cert',
    'まだ染色前',
    'まだ織成前',
    'これから染色',
    'まだ開業前'
  ];
  const nullPins = ['about to visit the dye works', 'about to file the weaving report'];
  const establishedPins = [
    ['質流れ', 'close-tab'],
    ['骨董品', 'close-tab'],
    ['close this tab', 'close-tab'],
    ['keep it', 'negate'],
    ['leave it alone', 'negate']
  ];

  let vc;
  beforeEach(() => {
    vc = makeVC();
  });

  closeTab.forEach((p) => test(`close-tab: "${p}"`, () => expect(key(vc, p)).toBe('close-tab')));
  closeTabJa.forEach((p) => test(`close-tab JA: ${p}`, () => expect(key(vc, p)).toBe('close-tab')));
  negate.forEach((p) => test(`negate: "${p}"`, () => expect(key(vc, p)).toBe('negate')));
  nullPins.forEach((p) => test(`still null: "${p}"`, () => expect(key(vc, p)).toBeNull()));
  establishedPins.forEach(([p, k]) => test(`pin: "${p}" still -> ${k}`, () => expect(key(vc, p)).toBe(k)));
});
